import {chromium} from '../../../../tools/revenue-studio/node_modules/playwright/index.mjs';
import {database} from '../../../../tools/member-studio/test-fixtures.mjs';
import {communityRoute} from './server.mjs';
import {hash} from './store.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {fileURLToPath} from 'node:url';
const site=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),db=database(),secret='fixture-only-not-production',env={EVENTS:db,MEMBER_WATCH_SECRET:secret};
let local;const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(process.env.COMMUNITY_FONT_DIR&&u.pathname.startsWith('/__fonts/')){const file=path.resolve(process.env.COMMUNITY_FONT_DIR,u.pathname.slice(9));if(!file.startsWith(path.resolve(process.env.COMMUNITY_FONT_DIR)+'/'))throw Error();res.setHeader('Content-Type',file.endsWith('.css')?'text/css':'font/woff2');res.end(fs.readFileSync(file));return;}if(u.pathname.startsWith('/community-assets/')){const file=path.resolve(site,'.'+u.pathname);if(!file.startsWith(site+'/community-assets/'))throw Error();res.setHeader('Content-Type',file.endsWith('.css')?'text/css':'text/javascript');res.end(fs.readFileSync(file));return;}const chunks=[];for await(const chunk of req)chunks.push(chunk);const headers={...req.headers};if(headers.origin===local)headers.origin='https://agiscorecard.com';headers['CF-Connecting-IP']='browser-fixture';const request=new Request('https://agiscorecard.com'+req.url,{method:req.method,headers,...(chunks.length?{body:Buffer.concat(chunks)}:{})});const response=await communityRoute(request,env);if(!response){const file=path.join(site,u.pathname==='/cn'?'cn.html':'index.html');res.setHeader('Content-Type','text/html');res.end(fs.readFileSync(file));return;}res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));}catch(e){res.writeHead(500);res.end(String(e));}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));local='http://127.0.0.1:'+server.address().port;
let browser;try{browser=await chromium.launch({headless:true,...(process.env.WORKBENCH_CHROMIUM?{executablePath:process.env.WORKBENCH_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage','--single-process']}:{})});
for(const lang of ['en','zh']){const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true}),page=await context.newPage(),base=lang==='zh'?'/zh/discuss':'/discuss',errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(local+base+'/tool-evidence');await page.locator('textarea').fill('Browser fixture: I checked one real workflow and found a reproducible formatting problem.');await page.locator('input[name="agree"]').check();await page.locator('#post-form button[type="submit"]').click();await page.waitForURL('**/account');
 await page.locator('[name="handle"]').fill(lang==='zh'?'中文测试者':'Browser Reader');const download=page.waitForEvent('download');await page.locator('#backup-key').click();const downloaded=await download;const backup=JSON.parse(fs.readFileSync(await downloaded.path(),'utf8'));assert.equal(backup.service,'agi-workbench');await page.locator('[name="key_saved"]').check();await page.locator('#join-form button[type="submit"]').click();await page.waitForURL('**/tool-evidence');assert.match(await page.locator('textarea').inputValue(),/Browser fixture/);
 await page.waitForTimeout(150);await page.locator('[name="agree"]').check();await page.locator('#post-form button[type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('审核')||document.querySelector('#notice').textContent.includes('review'));await page.locator('#follow').click();await page.waitForFunction(()=>document.querySelector('#follow').dataset.following==='true');
 await page.goto(local+base+'/account');await page.waitForSelector('#account-data:not([hidden])');assert.match(await page.locator('#contributions').textContent(),/Browser fixture/);assert.match(await page.locator('#following').textContent(),/workflow|工作流/);
 await page.locator('#signout').click();await page.waitForSelector('#signed-out:not([hidden])');await page.locator('#login-panel summary').click();await page.locator('#import-key').setInputFiles({name:'agi-access-key.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForFunction(()=>document.getElementById('login-key').value.length===64);await page.locator('#login-form button[type="submit"]').click();await page.waitForSelector('#account-data:not([hidden])');
 await page.goto(local+base);if(process.env.COMMUNITY_FONT_DIR){await page.addStyleTag({url:local+'/__fonts/400.css'});await page.addStyleTag({url:local+'/__fonts/700.css'});await page.evaluate(async()=>{await document.fonts.load('400 17px "Noto Sans SC"');await document.fonts.load('700 22px "Noto Sans SC"');await document.fonts.ready;});}assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/agi-discuss-'+lang+'-mobile.png',fullPage:true});await page.setViewportSize({width:1280,height:900});await page.screenshot({path:'/tmp/agi-discuss-'+lang+'-desktop.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS '+lang+': draft → free registration → backup/import → pending reply → follow → sign out/in; mobile layout');/* Keep contexts alive until browser.close (single-process Chromium). */}
const p=await browser.newPage();await p.goto(local+'/discuss/moderate');await p.locator('#moderator-key').fill(await hash(secret+':community-moderator:v1'));await p.locator('#moderator-login button').click();await p.waitForSelector('#moderation article');assert.equal(await p.locator('#moderation article').count(),2);await p.locator('#moderation article').first().getByRole('button',{name:'Approve',exact:true}).click();await p.waitForFunction(()=>document.querySelectorAll('#moderation article').length===1);await p.goto(local+'/discuss/tool-evidence');assert.match(await p.locator('.reply').textContent(),/Browser fixture/);console.log('PASS moderation: private queue → approve → public SSR reply');
}finally{await browser?.close();await new Promise(r=>server.close(r));}
