export const ORIGIN='https://agiscorecard.com';
export const categories={tools:{en:'AI tools in practice',zh:'AI 工具实测'},future:{en:'The future of AI',zh:'AI 的未来'},work:{en:'AI and your work',zh:'AI 与工作'}};
export const seeds=[
 {id:'tool-evidence',category:'tools',en:['Which AI workflow survived a real task?','Share one task you actually completed. Include the tool and version, the input, the output you checked, time spent correcting it, and what failed. A small reproducible example is more useful than a list of favorite products. If you made or sell the tool, disclose that connection.','/ai-tools'],zh:['哪个 AI 工作流经得起真实任务？','分享一个你真正完成的任务：工具和版本、输入、核对过的输出、返工耗时，以及失败的地方。一个可复现的小例子，比一串工具推荐更有用。如果你开发或销售这个工具，请说明关系。','/zh/ai-tools']},
 {id:'model-tradeoffs',category:'tools',en:['When does a local model beat a hosted tool?','Compare the same task with the same success criterion. Include hardware or service tier, latency, cost assumptions and an example that went wrong. Keep private documents and API keys out of your post. Which trade-off changed your choice?','/ai-tools'],zh:['什么情况下，本地模型比在线工具更适合？','用同一个任务、同一套成功标准做对比。说明硬件或套餐、延迟、成本假设，以及一个失败例子。不要上传私人文档或 API 密钥。哪个取舍真正改变了你的选择？','/zh/ai-tools']},
 {id:'agi-flip-condition',category:'future',en:['What evidence would change your AGI timeline?','Name a claim, a date and a result that would make you revise your view. Start with the scorecard, then bring a primary source or a test someone else can reproduce. A benchmark improvement is a signal; explain what it does and does not establish.','/progress-index'],zh:['什么证据会改变你的 AGI 时间判断？','写下一个判断、一个时间点，以及会让你改判的结果。可以从本站记分牌出发，再提供一手来源或别人能复现的测试。基准提升是一种信号，请说明它能证明什么、不能证明什么。','/zh/progress-index']},
 {id:'benchmark-reality',category:'future',en:['Which AI capability still fails outside a benchmark?','Describe a real setting where a reported capability did not transfer. Separate your observation from your explanation. Include the date, model version and a counterexample that would weaken your conclusion.','/how-will-we-know-agi-arrived'],zh:['哪些 AI 能力离开基准测试就失效？','描述一个真实场景：某项宣称的能力没有成功迁移。把观察到的现象和自己的解释分开，说明日期、模型版本，以及什么反例会削弱你的结论。','/zh/how-will-we-know-agi-arrived']},
 {id:'work-changed',category:'work',en:['Which part of your job has actually changed?','Choose one recurring task. What did you do before, what do you do now, and who checks the result? Avoid naming an employer or sharing confidential material. A change to a task is not automatically evidence that a whole occupation is disappearing.','/ai-and-your-job'],zh:['你的工作里，哪一部分真的被 AI 改变了？','选一个重复发生的任务：过去怎么做、现在怎么做、由谁检查结果？请勿透露雇主身份或机密资料。一个任务发生变化，并不自动意味着整个职业正在消失。','/zh/ai-and-your-job']},
 {id:'skills-next',category:'work',en:['What skill became more useful after adopting AI?','Describe a recent situation where a skill helped you find a mistake, improve an output or make a decision. Explain the task and what you would practice next. First-hand examples are welcome; guaranteed job or income claims are not.','/what-jobs-are-safe-from-ai'],zh:['使用 AI 之后，什么技能变得更有用了？','讲一个近期场景：某项技能帮助你发现错误、改进输出或作出判断。说明具体任务，以及你接下来会练习什么。欢迎第一手经历，不接受保证就业或收入的宣传。','/zh/what-jobs-are-safe-from-ai']}
].map(s=>({...s,created:Date.parse('2026-09-20T00:00:00Z')/1000,status:'public',editorial:true}));
export const root=l=>l==='zh'?'/zh/discuss':'/discuss';
export const topicPath=(l,id)=>root(l)+'/'+id;
export function seed(id,lang='en'){const s=seeds.find(s=>s.id===id);return s?{...s,lang,title:s[lang][0],body:s[lang][1],source:s[lang][2],handle:lang==='zh'?'AGI 编辑话题':'AGI editorial prompt',id:s.id}:null;}
