#!/usr/bin/env sh
# Rebuild _fonts.js from npm (the only font route that passes the egress proxy).
# registry.npmjs.org/@fontsource/<name>/latest -> tarball -> files/<name>-latin-400-normal.woff2
# All faces SIL OFL 1.1; the license travels inside each package. Usage: sh build-fonts.sh
set -e
cd "$(dirname "$0")"
TMP=${TMPDIR:-/tmp}/fontsource; mkdir -p "$TMP"
OUT=_fonts.js
{
  echo "/* Display faces embedded as data URIs. All SIL Open Font License 1.1 (embedding"
  echo " * permitted; the license travels with the font, see the @fontsource packages)."
  echo " * Source: registry.npmjs.org/@fontsource/<name> -> files/<name>-latin-400-normal.woff2,"
  echo " * pre-subset latin, 12-15KB each. GENERATED by build-fonts.sh -- do not hand-edit. */"
  echo "module.exports = {"
  for pair in "fredoka:fredoka-one:Fredoka One" "audiowide:audiowide:Audiowide" "righteous:righteous:Righteous" "bungee:bungee:Bungee" "rubikmono:rubik-mono-one:Rubik Mono One" "russo:russo-one:Russo One" "racing:racing-sans-one:Racing Sans One"; do
    key=${pair%%:*}; rest=${pair#*:}; pkg=${rest%%:*}; fam=${rest#*:}
    if [ ! -f "$TMP/$pkg/package/files/$pkg-latin-400-normal.woff2" ]; then
      url=$(curl -sS "https://registry.npmjs.org/@fontsource/$pkg/latest" | sed -n 's/.*"tarball":"\([^"]*\)".*/\1/p')
      mkdir -p "$TMP/$pkg"; curl -sS "$url" | tar xz -C "$TMP/$pkg"
    fi
    b64=$(base64 -w0 "$TMP/$pkg/package/files/$pkg-latin-400-normal.woff2")
    echo "  $key: \`@font-face{font-family:'$fam';font-style:normal;font-weight:400;font-display:swap;src:url(data:font/woff2;base64,$b64) format('woff2');}\`,"
  done
  echo "};"
} > "$OUT"
node -e "var f=require('./$OUT');console.log(Object.keys(f).map(function(k){return k+' '+f[k].length}).join('\n'))"
