// Real pages and local assets; external calls and production analytics are blocked.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {hub,account} from '../community/render.mjs';
const require=createRequire(import.meta.url),{chromium}=require(require.resolve('playwright',{paths:[path.resolve('tools/revenue-studio/node_modules')]}));
const opts={headless:true};if(process.env.AGI_CHROMIUM){const c=require(process.env.AGI_CHROMIUM);opts.executablePath=await c.executablePath();opts.args=c.args.filter(x=>!['--disable-web-security','--single-process'].includes(x));}
const root=path.resolve('sites/agiscorecard'),artifacts=process.env.NAV_ARTIFACT_DIR||'/tmp/agi-nav-qa';fs.mkdirSync(artifacts,{recursive:true});
const browser=await chromium.launch(opts),ctx=await browser.newContext({viewport:{width:390,height:844}}),p=await ctx.newPage();
await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!=='https://agiscorecard.com')return r.abort();const lang=u.pathname.startsWith('/zh/')?'zh':'en';if(/^\/(zh\/)?discuss(?:\/account)?$/.test(u.pathname))return r.fulfill({contentType:'text/html',body:u.pathname.endsWith('/account')?account(lang):hub(lang,[],'')});if(u.pathname.startsWith('/api/'))return r.fulfill({contentType:'application/json',body:'{"ok":false,"error":"offline fixture"}'});const f=path.join(root,u.pathname==='/'?'index.html':u.pathname.slice(1));const file=[f,f+'.html',path.join(f,'index.html')].find(x=>fs.existsSync(x)&&fs.statSync(x).isFile());if(!file)return r.fulfill({status:404,body:'not found'});return r.fulfill({body:fs.readFileSync(file),contentType:({'.html':'text/html','.css':'text/css','.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.woff2':'font/woff2'})[path.extname(file)]||'text/plain'});});
const routes=['/','/cn',...['future-guide','progress-index','ai-tools','invest','jarvis','mentor','earn','create','portfolio-tracker','ai-infrastructure','workbench','members','agents/','discuss','discuss/account'].flatMap(x=>['/'+x,'/zh/'+x])];let checked=0;
try{
 for(const width of [390,1440]){await p.setViewportSize({width,height:900});let baseline;for(const route of routes){await p.goto('https://agiscorecard.com'+route+'?__qa=1');await p.locator('#agi-nav .agi-menu>summary').waitFor();await p.waitForFunction(()=>document.querySelector('#agi-site-menu summary').hasAttribute('aria-expanded'));
  const h=await p.locator('#agi-nav').evaluate(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return{height:r.height,x:r.x,width:r.width,color:s.color,font:s.fontFamily,bg:s.backgroundColor};});
  baseline??=h;assert.deepEqual(h,baseline,route+' consistent header at '+width);
  await p.locator('#agi-site-menu summary').click();assert.equal(await p.locator('#agi-site-menu').getAttribute('open'),'');assert.equal(await p.locator('#agi-menu-panel a').count(),19);
  assert.equal(await p.locator('#agi-menu-panel a[data-nav-destination=tools]').isVisible(),true);assert.equal(await p.locator('#agi-menu-panel a[data-nav-destination=invest]').isVisible(),true);
  assert.ok(await p.locator('#agi-nav').evaluate(e=>[...e.querySelectorAll('a,summary')].filter(a=>a.getClientRects().length).every(a=>{const r=a.getBoundingClientRect();return r.left>=-1&&r.right<=innerWidth+1;})),route+' navigation fits '+width);
  await p.keyboard.press('Escape');assert.equal(await p.locator('#agi-site-menu').getAttribute('open'),null);assert.equal(await p.locator('#agi-site-menu summary').evaluate(e=>document.activeElement===e),true);
  if(route==='/cn'&&width===390){await p.screenshot({path:path.join(artifacts,'mobile-home.png')});await p.locator('#agi-site-menu summary').click();await p.screenshot({path:path.join(artifacts,'mobile-menu.png')});await p.keyboard.press('Escape');}
  checked++;
 }}
 for(const width of [320,360,650,768,1024]){await p.setViewportSize({width,height:844});for(const route of ['/','/cn']){await p.goto('https://agiscorecard.com'+route+'?__qa=1');await p.locator('#agi-site-menu summary').click();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route+' overflow at '+width+' '+JSON.stringify(await p.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.right>innerWidth+1}).slice(-20).map(e=>({tag:e.tagName,id:e.id,cls:e.className,right:e.getBoundingClientRect().right})))) );await p.mouse.click(10,70);assert.equal(await p.locator('#agi-site-menu').getAttribute('open'),null);}}
 await p.setViewportSize({width:390,height:844});await p.goto('https://agiscorecard.com/cn?__qa=1');
 for(const [id,route]of [['tools','/zh/ai-tools'],['invest','/zh/invest'],['discuss','/zh/discuss']]){await p.locator('#agi-site-menu summary').click();await p.locator('#agi-menu-panel a[data-nav-destination='+id+']').click();assert.equal(new URL(p.url()).pathname,route);assert.equal(await p.locator('#agi-nav').getAttribute('data-nav-language'),'zh');}
 await p.locator('#language').click();assert.equal(new URL(p.url()).pathname,'/discuss');assert.equal(await p.locator('#agi-nav').getAttribute('data-nav-language'),'en');
 const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:320,height:844}}),np=await nojs.newPage();await np.route('**/*',r=>{const u=new URL(r.request().url());const file=u.pathname==='/cn'?path.join(root,'cn.html'):path.join(root,u.pathname);if(!u.pathname.startsWith('/api/')&&fs.existsSync(file)&&fs.statSync(file).isFile())return r.fulfill({body:fs.readFileSync(file),contentType:u.pathname.endsWith('.css')?'text/css':'text/html'});return r.abort();});await np.goto('https://agiscorecard.com/cn');await np.locator('#agi-site-menu summary').click();assert.equal(await np.locator('#agi-menu-panel a[data-nav-destination=tools]').isVisible(),true);await nojs.close();
 await p.goto('https://agiscorecard.com/zh/ai-tools?__qa=1#tools');await p.waitForFunction(()=>document.getElementById('language').hash==='#tools');assert.equal(await p.locator('#language').getAttribute('href'),'/ai-tools#tools');
 await p.goto('https://agiscorecard.com/zh/mentor?embed=1&__qa=1');assert.equal(await p.locator('#agi-nav').isVisible(),false);
 await p.goto('https://agiscorecard.com/zh/discuss/account?__qa=1');assert.equal(await p.locator('#login-key').count(),1);
 console.log(JSON.stringify({navigationPages:checked,widths:[320,360,390,650,768,1024,1440],menuDestinations:19,passed:true}));
}finally{await browser.close();}
