import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {normalize,eligible,files,root} from './build.mjs';import {siteHeader,groups,VERSION,sectionFor} from '../../site-nav/render.mjs';import {hub,account} from '../community/render.mjs';import {businessEvent} from '../../../../tools/fleet-analytics/business.mjs';
test('all static English and Chinese pages share one complete, idempotent navigation',()=>{let count=0;for(const f of files()){const rel=path.relative(root,f),html=fs.readFileSync(f,'utf8');if(!eligible(html,rel))continue;count++;assert.equal(normalize(html,rel),html,rel);assert.equal((html.match(/id="agi-nav"/g)||[]).length,1,rel);assert.equal((html.match(/id="language"/g)||[]).length,1,rel);assert.ok(html.includes(`data-nav-version="${VERSION}"`),rel);}assert.ok(count>290);});
test('all menu destinations exist in both editions or are explicitly English',()=>{for(const lang of ['en','zh']){const html=siteHeader(lang);for(const href of [...html.matchAll(/href="([^"]+)"/g)].map(m=>m[1])){if(href.startsWith('https:'))continue;const url=new URL(href,'https://agiscorecard.com');if(/^\/(zh\/)?discuss(?:\/|$)/.test(url.pathname))continue;const route=url.pathname==='/'?'index':url.pathname.slice(1);assert.ok([route,route+'.html',route+'index.html'].some(x=>fs.existsSync(path.join(root,x))),href);}}assert.equal(groups.flatMap(g=>g.links).length,19);});
test('language stays on verified counterparts; missing translations clearly go home',()=>{const src='<html lang="en"><head><link rel="canonical" href="https://agiscorecard.com/ai-tools"><link rel="alternate" hreflang="zh-CN" href="https://agiscorecard.com/zh/ai-tools"></head><body><header>old</header><main><form><input name="keep"></form></main></body></html>';const out=normalize(src,'ai-tools.html');assert.match(out,/id="language" href="\/zh\/ai-tools"/);assert.match(out,/<form><input name="keep"><\/form>/);assert.equal(normalize(out,'ai-tools.html'),out);const none=normalize(src.replace(/<link rel="alternate"[^>]*>/,''),'untranslated-fixture.html');assert.match(none,/id="language" href="\/cn"/);assert.match(none,/本页暂无中文/);assert.equal(normalize(src,'widget.html'),src);assert.equal(normalize(src.replace('lang="en"','lang="ja"'),'ja.html'),src.replace('lang="en"','lang="ja"'));});
test('dynamic discussions use the same renderer, preserve forms and locale routes',()=>{for(const lang of ['en','zh']){const html=hub(lang,[],'');assert.ok(html.includes(siteHeader(lang,{pathname:(lang==='zh'?'/zh':'')+'/discuss',alternate:(lang==='en'?'/zh':'')+'/discuss'})));const a=account(lang);assert.match(a,/id="join-form"/);assert.match(a,/id="login-key" type="password"/);assert.ok(a.includes(`href="${lang==='en'?'/zh':''}/discuss/account"`));}assert.equal(sectionFor('/zh/portfolio-tracker'),'invest');assert.equal(sectionFor('/zh/workbench/resume'),'tools');});
test('navigation analytics accept only fixed names, exclude account pages and private input',()=>{assert.equal(businessEvent('agiscorecard.com','/cn',{name:'nav_menu_open'}).site_edition,'zh');for(const p of ['/members','/zh/members','/discuss/account','/zh/discuss/account','/discuss/moderate','/zh/discuss/moderate'])assert.equal(businessEvent('agiscorecard.com',p,{name:'nav_language'}),null);assert.equal(businessEvent('agiscorecard.com','/',{name:'nav_private-text'}),null);assert.equal(businessEvent('agiscorecard.com','/',{name:'nav_menu_open',query:'private'}),null);assert.equal(businessEvent('other.com','/',{name:'nav_tools'}),null);});

test('legacy homepages pair correctly before edge hreflang injection',()=>{for(const [file,lang,target]of [['cn.html','zh','/'],['index.html','en','/cn']]){const input='<html lang="'+lang+'"><head></head><body><main>Existing content</main></body></html>',out=normalize(input,file);assert.ok(out.includes('id="language" href="'+target+'"'));assert.match(out,/data-nav-language-link="translation"/);assert.doesNotMatch(out,/暂无中文|no translation for this page/);}});
