// Continuous recording of the actual calculator. No analytics; fictional inputs.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{chromium}=require('playwright');
const out=process.env.ECO_MEDIA_OUT||'/tmp/eco-laundry-03',root=path.resolve('sites/getecoback/site');fs.mkdirSync(out,{recursive:true});
(async()=>{const server=http.createServer((req,res)=>{let p=path.join(root,new URL(req.url,'http://localhost').pathname);if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.writeHead(200,{'content-type':({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(p)]||'application/octet-stream'});res.end(fs.readFileSync(p));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--use-angle=swiftshader','--enable-unsafe-swiftshader']}: {})});try{const context=await browser.newContext({viewport:{width:510,height:680},recordVideo:{dir:out,size:{width:510,height:680}}}),page=await context.newPage(),started=Date.now();await page.route('**/*',r=>r.request().url().startsWith(base)&&!r.request().url().includes('/api/')?r.continue():r.abort());await page.goto(base+'/en/guide/dehumidifier-drying-clothes-cost.html?__probe=1');await page.addStyleTag({content:'.demo-cursor{position:fixed;width:22px;height:22px;border:3px solid #d78015;background:#d7801533;border-radius:50%;z-index:100000;pointer-events:none;left:-40px;top:-40px}'});await page.evaluate(()=>{const c=document.createElement('div');c.className='demo-cursor';document.body.append(c);addEventListener('mousemove',e=>{c.style.left=(e.clientX-11)+'px';c.style.top=(e.clientY-11)+'px';});});
const scroll=async(sel,block='center')=>{await page.locator(sel).evaluate((e,b)=>e.scrollIntoView({behavior:'smooth',block:b}),block);await page.waitForTimeout(550);};const click=async sel=>{await page.locator(sel).scrollIntoViewIfNeeded();const b=await page.locator(sel).boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:10});await page.locator(sel).click();};
if(await page.locator('#eb-sticky-x').isVisible())await page.locator('#eb-sticky-x').click();await scroll('#laundry-check [data-example]');const zero=Date.now(),offset=(zero-started)/1000;const until=async sec=>{let ms=zero+sec*1000-Date.now();if(ms>0)await page.waitForTimeout(ms);};
await until(.3);await click('#laundry-check [data-example]');await scroll('#laundry-check [data-results]','start');await page.screenshot({path:path.join(out,'frame-01.png')});await until(4);
await scroll('#laundry-check [name=hours]');await page.locator('#laundry-check [name=hours]').focus();await until(8);await page.screenshot({path:path.join(out,'frame-02.png')});
await until(10);await page.locator('#laundry-check [name=hours]').fill('');await page.locator('#laundry-check [name=hours]').pressSequentially('4',{delay:200});await until(11.5);await click('#laundry-check [type=submit]');await scroll('#laundry-check [data-results]','start');await page.screenshot({path:path.join(out,'frame-03.png')});await until(17);
await scroll('#laundry-check [name=comparable]');await page.mouse.move(55,330,{steps:12});await page.screenshot({path:path.join(out,'frame-04.png')});await until(21);await scroll('#laundry-check [data-results]','start');await until(26.5);const video=page.video();await context.close();fs.writeFileSync(path.join(out,'capture.json'),JSON.stringify({path:await video.path(),offset,duration:26,source:'Continuous real EcoBack calculator interaction at 1x; fictional 250 W, 8 h then 4 h, 1.5 kWh dryer, EUR 0.35/kWh; equal dryness assumed.'}));console.log(out);}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
