// Continuous recording of real local product interactions. No AI fixture, payment or telemetry.
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {createRequire} from 'node:module';import {blankState,solution,makeCase,record} from '../../../sites/agiscorecard/mentor-assets/core.mjs';
const require=createRequire(import.meta.url),{chromium}=require(path.resolve('tools/revenue-studio/node_modules/playwright')),out=path.resolve(process.env.MENTOR_MEDIA_OUT||'/tmp/mentor-report-01');fs.mkdirSync(out,{recursive:true});
const root=path.resolve('sites/agiscorecard'),server=http.createServer((req,res)=>{let p=path.join(root,new URL(req.url,'http://localhost').pathname);if(!path.extname(p))p+='.html';if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.writeHead(200,{'Content-Type':({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(p)]||'text/plain'});res.end(fs.readFileSync(p));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,...(process.env.MENTOR_BROWSER_CONFIG?JSON.parse(fs.readFileSync(process.env.MENTOR_BROWSER_CONFIG,'utf8')):{})}),base='http://127.0.0.1:'+server.address().port;
try{const context=await browser.newContext({viewport:{width:450,height:520},recordVideo:{dir:out,size:{width:450,height:520}}}),state=blankState();state.seed=42;await context.addInitScript(s=>localStorage.setItem('agi-work-mentor-v1',JSON.stringify(s)),record(state));const page=await context.newPage(),start=Date.now();await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await page.goto(base+'/mentor?__qa=1');await page.waitForFunction(()=>document.querySelector('#data-rows').children.length>5);const s=solution(makeCase(42));await page.locator('#orders').fill(String(s.orders));await page.locator('#revenue').fill(String(s.revenue+800));await page.locator('#channel').selectOption(s.channel[0]);await page.locator('#growth').fill(s.growth.toFixed(1));await page.locator('#claim').selectOption('unproven');
await page.addStyleTag({content:'.demo-cursor{position:fixed;width:22px;height:22px;border:3px solid #002fa7;background:#002fa720;border-radius:50%;z-index:100000;pointer-events:none;left:-40px;top:-40px;transition:transform .12s}.demo-cursor.down{transform:scale(1.8);background:#002fa760}'});await page.evaluate(()=>{const c=document.createElement('div');c.className='demo-cursor';document.body.append(c);addEventListener('mousemove',e=>{c.style.left=(e.clientX-11)+'px';c.style.top=(e.clientY-11)+'px';});addEventListener('mousedown',()=>c.classList.add('down'));addEventListener('mouseup',()=>c.classList.remove('down'));});
const scroll=async selector=>{await page.locator(selector).evaluate(e=>e.scrollIntoView({behavior:'smooth',block:'center'}));await page.waitForTimeout(650);};const click=async selector=>{const box=await page.locator(selector).boundingBox();if(box)await page.mouse.move(box.x+box.width/2,box.y+box.height/2,{steps:12});await page.locator(selector).click();};
await scroll('#revenue');const zero=Date.now(),offset=(zero-start)/1000;const until=async sec=>{const remaining=zero+sec*1000-Date.now();if(remaining>0)await page.waitForTimeout(remaining);};
await until(1);await click('#check');await scroll('#result');await page.screenshot({path:path.join(out,'frame-01.png')});await until(6);
await scroll('#data-rows .cancelled');await page.locator('#data-rows .cancelled').evaluate(e=>e.style.outline='2px solid #9f2636');await page.screenshot({path:path.join(out,'frame-02.png')});await until(12);
await scroll('#revenue');await page.locator('#revenue').fill('');await page.locator('#revenue').pressSequentially(String(s.revenue),{delay:180});await click('#check');await scroll('#result');await page.screenshot({path:path.join(out,'frame-03.png')});await until(19);
await click('#next-case');await until(20);await scroll('.table-wrap');await page.screenshot({path:path.join(out,'frame-04.png')});await until(26);
await page.evaluate(()=>scrollTo({top:0,behavior:'smooth'}));await until(28);await page.mouse.move(175,375,{steps:16});await page.screenshot({path:path.join(out,'frame-05.png')});await until(34.5);const video=page.video();await context.close();const videoPath=await video.path();fs.writeFileSync(path.join(out,'capture.json'),JSON.stringify({path:videoPath,offset,duration:34,seed:42,net:s.revenue,wrong:s.revenue+800,source:'real local interface with fictional practice data; no model inference'}));
const social=await browser.newContext({viewport:{width:1200,height:630}}),card=await social.newPage();await card.setContent('<html><body style="margin:0;background:#fff;font-family:Arial,sans-serif;color:#18191d;padding:65px;box-sizing:border-box;border-top:12px solid #002fa7"><p style="font-size:21px;color:#002fa7;letter-spacing:2px">AGI SCORECARD / WORK MENTOR</p><h1 style="font-size:67px;line-height:1.08;margin:45px 0 25px;letter-spacing:-3px">Make the report.<br>Then prove it adds up.</h1><p style="font-size:25px;color:#595d68">Five checks. Fresh data. A clear next step.</p><p style="font-size:23px;margin-top:48px;color:#002fa7">Practice free → agiscorecard.com/mentor</p></body></html>');await card.screenshot({path:path.join(root,'share/mentor.png')});await social.close();console.log('Continuous demonstration and social card captured: '+out);
}finally{await browser.close();server.close();}
