#!/usr/bin/env node
import {McpServer} from '@modelcontextprotocol/server';
import {serveStdio} from '@modelcontextprotocol/server/stdio';
import * as z from 'zod/v4';
import {audit,supplierDraft} from './engine.js';
import {auditSchema,reportSchema} from './schema.js';
import {example} from './example.js';
import {importTables,tableImportSchema} from './tables.js';
import {workflow} from './workflow.js';
const annotations={readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false};
const response=<T extends Record<string,unknown>>(value:T)=>({content:[{type:'text' as const,text:JSON.stringify(value)}],structuredContent:value});
const contract={purpose:'Two-way PO and supplier invoice review',version:'0.2.0',currencies:['USD','EUR','GBP','CAD','AUD','CNY','SGD','CHF','JPY'],quantities:'positive decimal strings, up to 3 places',unit_prices:'non-negative decimal strings, up to 4 places',totals:'non-negative decimal strings, 2 places; JPY integer totals',rounding:'half up per invoice line',limits:'100 lines per PO/current invoice; 20 prior invoices; 1,000 prior lines. No OCR, currency conversion, credit notes, discounts, receipt matching, tax or payment approval.',privacy:'Local process; no file reads, outbound requests, storage, model API calls or telemetry. Your host may send supplied documents to its model provider.',workflow};
export function createServer(){
 const server=new McpServer({name:'tradecheck-mcp',version:'0.2.0'});
 server.registerTool('tradecheck_import_tables',{title:'Prepare CSV or spreadsheet rows for review',description:'Convert supplied CSV or tab-separated PO and invoice rows using explicit zero-based column mappings. Supply every header amount and source name; never infer missing tax, charges, IDs, currency or units. Returns unreviewed data with unknown prior history, not an audit. Ask the user to confirm values and provide prior invoices before reconciliation.',inputSchema:tableImportSchema,outputSchema:z.strictObject({data:auditSchema}),annotations},async(args)=>{try{return response({data:importTables(args)});}catch(e){return {isError:true,content:[{type:'text' as const,text:e instanceof Error?e.message:'Check the table mappings.'}]};}});
 server.registerTool('tradecheck_example',{title:'Get a fictional importer invoice example',description:'Return the stable fictional PO-1042 example and input contract. It contains a EUR 44.00 signed price increase and cumulative quantity 320 against 300 ordered. Use this to learn the schema; never mix sample records with buyer data.',inputSchema:z.strictObject({}),outputSchema:z.strictObject({data:auditSchema,contract:z.record(z.string(),z.unknown())}),annotations},async()=>response({data:example,contract}));
 server.registerTool('tradecheck_reconcile',{title:'Review an invoice against its purchase order',description:'Compare caller-supplied normalized PO, invoice and prior history using exact decimal arithmetic. Flag price, identity, currency, quantity, duplicates and total discrepancies with caller-supplied source locators. Does not read source files or approve payment. Return summary plus a page of findings; fetch next_offset until null. Each finding carries up to 6 source locators and refs_omitted; inspect supplied source rows for omitted locators.',inputSchema:z.strictObject({data:auditSchema,offset:z.number().int().min(0).max(5000).default(0),limit:z.number().int().min(1).max(25).default(20)}),outputSchema:z.strictObject({report:reportSchema,findings_total:z.number().int(),next_offset:z.number().int().nullable()}),annotations},async({data,offset,limit})=>{
  try{const full=audit(data),page=full.findings.slice(offset,offset+limit).map(x=>({...x,refs:x.refs.slice(0,6),refs_omitted:Math.max(0,x.refs.length-6)}));return response({report:{...full,findings:page},findings_total:full.findings.length,next_offset:offset+limit<full.findings.length?offset+limit:null});}catch(e){return {isError:true,content:[{type:'text' as const,text:e instanceof Error?e.message:'Unable to review these inputs. Check the contract.'}]};}
 });
 server.registerTool('tradecheck_supplier_draft',{title:'Prepare an unsent supplier clarification',description:'Recompute the document review and return an unsent English or Chinese-introduction draft for up to 20 exceptions/gaps. Does not send messages. Chinese introductions preserve English diagnostic lines for exact traceability; the host can translate them. Use reconcile pagination for all findings.',inputSchema:z.strictObject({data:auditSchema,language:z.enum(['en','zh']).default('en')}),outputSchema:z.strictObject({subject:z.string(),body:z.string(),findings_total:z.number().int(),draft_items:z.number().int(),sent:z.literal(false)}),annotations},async({data,language})=>{try{const d=supplierDraft(data,language);return response({subject:d.subject,body:d.body,findings_total:d.report.findings.length,draft_items:Math.min(20,d.report.findings.filter(x=>x.severity!=='info').length),sent:false as const});}catch(e){return {isError:true,content:[{type:'text' as const,text:e instanceof Error?e.message:'Invalid document data.'}]};}});
 server.registerResource('contract','tradecheck://contract',{title:'TradeCheck scope, decimal rules and privacy',mimeType:'application/json'},async uri=>({contents:[{uri:uri.href,mimeType:'application/json',text:JSON.stringify(contract)}]}));
 server.registerPrompt('review_supplier_invoice',{title:'Review supplier invoice with evidence',description:'Guided document extraction, human confirmation, deterministic checks and an unsent clarification draft.',argsSchema:z.strictObject({})},()=>({messages:[{role:'user' as const,content:{type:'text' as const,text:workflow}}]}));
 return server;
}
void serveStdio(createServer);
