import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {sites,byId,hubHost} from '../public/catalog.mjs';
import {topics,scenarios,exampleLink,publicMetadata,inputSchema,updated} from '../public/experience.mjs';
import {run} from '../public/engine.mjs';
import {VERSION} from '../public/core.mjs';
const h=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ld=x=>'<script type="application/ld+json">'+JSON.stringify(x).replace(/</g,'\\u003c')+'</script>';
const replace=(text,needle,value)=>{if(!text.includes(needle))throw Error('Growth insertion missing: '+needle.slice(0,90));return text.replace(needle,value);};
const faq=s=>[{q:topics[s.id].question,a:topics[s.id].response},{q:'Is '+s.name+' free, and do I need a wallet?',a:'All current functions are free beta. No account, wallet connection, subscription or model API key is needed. '+s.limit},{q:'Can I use my own records and keep them private?',a:'Yes. Enter records, import JSON or paste CSV into record groups. Inputs and comparison snapshots stay in this browser tab. Share-example links contain only a public scenario name. Review downloaded reports before sharing your records.'}];
const faqs=s=>'<section class="faq"><h2>Questions before you start</h2>'+faq(s).map(x=>`<details><summary>${h(x.q)}</summary><p>${h(x.a)}</p></details>`).join('')+'</section>';
const breadcrumb=(s,path,name)=>({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Web3 Workbench',item:'https://'+hubHost+'/'},{'@type':'ListItem',position:2,name:s.name,item:'https://'+s.host+'/'},...(path?[{'@type':'ListItem',position:3,name,item:'https://'+s.host+'/'+path}]:[])]});
function enrichHead(text,s,path,title){
 const url='https://'+s.host+'/'+path;const t=topics[s.id];const description=t?s.description:'Free AI and Web3 tools with local records, worked scenarios and portable reports. Compare evidence, costs, permissions and payment exceptions.';
 text=text.replace(/<title>[^<]*<\/title>/,'<title>'+h(title)+'</title>').replace(/<meta property="og:title" content="[^"]*">/,'<meta property="og:title" content="'+h(title)+'">');
 const graph=[{'@type':'WebPage','@id':url,name:title,url,description,dateModified:updated,inLanguage:'en',isPartOf:{'@id':'https://'+hubHost+'/#website'}}];
 if(t){graph.push(breadcrumb(s,path,path==='guide.html'?'Method and input guide':path==='examples.html'?'Worked examples':path==='privacy.html'?'Privacy':s.name));if(!path)graph.push({'@type':'WebApplication','@id':url+'#app',name:s.name,url,description:t.answer,applicationCategory:'BusinessApplication',operatingSystem:'Any modern browser',browserRequirements:'JavaScript enabled for local calculation',isAccessibleForFree:true,offers:{'@type':'Offer',price:'0',priceCurrency:'USD'},featureList:[s.description,'Local input processing','Three fictional worked scenarios','JSON and Markdown reports','Offline Node.js runner'],softwareVersion:VERSION,author:{'@type':'Organization',name:'AGI Scorecard',url:'https://agiscorecard.com/'}});if(['','guide.html'].includes(path))graph.push({'@type':'FAQPage',mainEntity:faq(s).map(x=>({'@type':'Question',name:x.q,acceptedAnswer:{'@type':'Answer',text:x.a}}))});}
 else graph.push({'@type':'WebSite','@id':'https://'+hubHost+'/#website',name:'Web3 Workbench',url:'https://'+hubHost+'/',publisher:{'@type':'Organization',name:'AGI Scorecard',url:'https://agiscorecard.com/'}});
 const meta=`<meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:image" content="https://${s.host}/share.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="${h(t?t.query+' — fictional worked scenario':'Web3 Workbench — free local tools')}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="https://${s.host}/share.png">${t?'<link rel="alternate" type="text/markdown" href="https://'+s.host+'/guide.md" title="Method in Markdown"><link rel="alternate" type="application/json" href="https://'+s.host+'/tool.json" title="Tool capabilities">':''}${ld({'@context':'https://schema.org','@graph':graph})}`;
 return replace(text,'</head>',meta+'</head>');
}
const nav=text=>text.replace('<a href="/guide.html">Guide / 中文</a>','<a href="/examples.html">Examples</a><a href="/guide.html">Guide / 中文</a>');
const related=s=>`<div class="next-tools"><h2>Continue your review</h2>${topics[s.id].next.map(id=>`<a href="https://${byId[id].host}/"><strong>${h(byId[id].name)}</strong><span>${h(byId[id].description)}</span></a>`).join('')}</div>`;
const sharing=s=>`<section class="share-kit"><h2>Useful for your team or readers?</h2><p>Share a public example or use the card in your documentation. These links never contain your input records.</p><div class="share-actions"><button id="share-example" class="secondary" type="button">Copy example link</button><a href="/share.png" download>Download share card</a><a href="https://${hubHost}/publish.html">Get a link or embed card</a></div><label for="share-output">Public example link</label><input id="share-output" type="text" readonly value="${h(exampleLink(s.id,scenarios(s.id)[0].key))}"><p id="share-status" role="status"></p></section>`;
function upgradeHome(text,s){
 const t=topics[s.id],cases=scenarios(s.id);text=nav(text);text=replace(text,h(s.headline),h(t.heading));text=replace(text,`<p class="quiet">${h(s.category)}</p>`,`<p class="topic">${h(t.query)}</p>`);
 text=replace(text,`<a class="cta" href="#workbench">Open ${h(s.name)}</a>`,`<button class="cta" type="button" data-scenario="${cases[0].key}">Try a worked example</button><a class="secondary-cta" href="#editor-details">Use my own records</a>`);
 text=replace(text,'<div class="editor-toolbar">',`<details id="editor-details" class="input-editor" open><summary>Edit the inputs</summary><div class="editor-toolbar">`);
 text=replace(text,'<div class="actions"><button id="run"',`</details><div class="actions"><button id="run"`);
 text=replace(text,'<p id="result-summary"></p>','<p id="result-summary"></p><p id="result-context" class="quiet"></p>');
 text=replace(text,'<ul id="notes"></ul></section>',`<ul id="notes"></ul><div class="actions report-actions"><button id="save-readable" type="button">Save readable report</button><button id="print-report" class="secondary" type="button">Print / save PDF</button><button id="keep-comparison" class="secondary" type="button">Keep for comparison</button><button id="clear-comparison" class="subtle" type="button" hidden>Clear comparison</button></div><p class="quiet">Reports include your record labels. Review them before sharing.</p><div id="comparison-output"></div></section>`);
 const picker=`<div class="scenario-lab"><div><h3>What would you like to check?</h3><p class="quiet">Choose a fictional scenario to run it immediately, then change the assumptions.</p></div><div class="scenario-buttons">${cases.map(c=>`<button class="scenario-button" type="button" data-scenario="${c.key}"><strong>${h(c.title)}</strong><span>${h(c.description)}</span></button>`).join('')}</div><label for="scenario-picker" class="quiet">Selected example<select id="scenario-picker">${cases.map(c=>`<option value="${c.key}">${h(c.title)}</option>`).join('')}</select></label><a href="/examples.html">Explore the calculations and common mistakes</a></div>`;
 text=replace(text,'<div id="form-fields"></div>', '<div id="form-fields"></div>');
 text=replace(text,'<div class="workbench-top">',picker+'<div class="workbench-top">');
 text=replace(text,'<h2>Your '+h(s.name.toLowerCase())+' worksheet</h2>','<h2>Make it your own</h2>');
 text=replace(text,'</main>',`<section class="content-section"><div class="wrap"><div class="answer-block"><h2>What does ${h(s.name)} do?</h2><p>${h(t.answer)}</p><p class="quiet">By the AGI Scorecard team. Method and sources reviewed <time datetime="${updated}">19 September 2026</time>. <a href="/guide.html">Read the method</a>.</p></div>${faqs(s)}${related(s)}${sharing(s)}</div></section></main>`);
 return enrichHead(text,s,'',t.title);
}
const metrics=r=>`<dl class="case-metrics">${r.metrics.map(m=>`<div><dt>${h(m.label)}</dt><dd>${h(m.value)}</dd></div>`).join('')}</dl>`;
function exampleBody(s){const t=topics[s.id];return `<p class="intro">${h(t.answer)}</p><p>Three fictional scenarios, calculated by the same engine as the tool. They illustrate behavior and failure cases, not customer outcomes or measured provider performance.</p><nav class="case-index" aria-label="Worked cases">${scenarios(s.id).map(c=>`<a href="#${c.key}">${h(c.title)}</a>`).join('')}</nav>`+scenarios(s.id).map(c=>{const r=run(s.id,c.input);return `<section class="worked-case" id="${c.key}"><h2>${h(c.title)}</h2><p>${h(c.description)}</p>${metrics(r)}<div class="table-scroll"><table><caption>${h(r.tables[0].title)}</caption><thead><tr>${r.tables[0].columns.map(x=>`<th>${h(x)}</th>`).join('')}</tr></thead><tbody>${r.tables[0].rows.map(row=>'<tr>'+row.map(x=>'<td>'+h(x??'Unknown')+'</td>').join('')+'</tr>').join('')}</tbody></table></div><p><a class="cta" href="${h(exampleLink(s.id,c.key))}">Run this scenario</a> <a href="/examples/${c.key}.json" download>Input JSON</a> <a href="/examples/${c.key}-report.json" download>Calculated report</a></p><details><summary>Inspect every input</summary><pre>${h(JSON.stringify(c.input,null,2))}</pre></details></section>`;}).join('')+`<h2>A mistake worth catching</h2><p>${h(t.mistake)}</p><h2>Use the method with your records</h2><p>${h(s.method)}</p><p>${h(s.limit)}</p><p><a href="/guide.html">Read the complete method, sources and input contract</a>. Updated ${updated}; by the AGI Scorecard team.</p>${related(s)}`;}
function markdown(s){const t=topics[s.id];return `# ${t.query} — ${s.name}\n\nCanonical: https://${s.host}/guide.html\nReviewed: ${updated}\nAuthor: AGI Scorecard team\nVersion: ${VERSION}\n\n${t.answer}\n\n## Method\n\n${s.method}\n\n## Workflow\n\n`+s.workflow.map((x,i)=>`${i+1}. ${x}`).join('\n')+`\n\n## Common mistake\n\n${t.mistake}\n\n## Worked scenarios\n\n`+scenarios(s.id).map(c=>{const r=run(s.id,c.input);return `### ${c.title}\n\n${c.description}\nFictional inputs: https://${s.host}/examples/${c.key}.json\nRun: ${exampleLink(s.id,c.key)}\n`+r.metrics.map(m=>`- ${m.label}: ${m.value}`).join('\n');}).join('\n\n')+'\n\n## Questions\n\n'+faq(s).map(x=>'### '+x.q+'\n\n'+x.a).join('\n\n')+'\n\n## Alternatives and official sources\n\n'+s.competitors.map(c=>`- [${c.name}](${c.url}): ${c.capability}`).join('\n')+`\n\n${s.tradeoff}\n\n## Limits\n\n${s.limit}\n${run(s.id,s.sample).notes.join('\n\n')}\n\n## Input and output\n\nStructural schema: https://${s.host}/input.schema.json\nThe engine additionally validates ranges, dates, amount formats, uniqueness and cross-field rules.\nInput JSON and CSV paste are processed locally. No model, account or wallet is needed.\nReports can be downloaded as JSON or Markdown and printed locally. Public scenario links never include user records.\n\n## Price and license\n\nCurrent functions are free beta. No paid plan or update SLA is offered.\nTool bundle license: https://${s.host}/LICENSE.txt\nPrivacy: https://${s.host}/privacy.html\n`;}
function replaceMain(text,title,body){text=text.replace(/<main[^>]*>[\s\S]*?<\/main>/,`<main id="main" class="document"><h1>${h(title)}</h1>${body}</main>`);return text;}
async function hubPages(){
 const hub={id:'hub',name:'Web3 Workbench',host:hubHost};let text=await readFile('dist/index.html','utf8');text=replace(text,'Make the next Web3 decision inspectable.','Bring a question. Leave with a working result.');
 const filter=`<div class="tool-finder"><label for="tool-search">Find your task<input id="tool-search" type="search" placeholder="Try: payment, GPU, approval, 数据"></label><label for="tool-category">Focus<select id="tool-category"><option value="all">All workflows</option><option value="payments">Payments & calls</option><option value="agents">Agents & protocols</option><option value="data">Data & disclosures</option><option value="compute">Compute & proofs</option><option value="economics">Reward economics</option></select></label><p id="finder-status" role="status">11 tools, all free to try</p></div>`;
 text=replace(text,'<section class="portfolio">',`<section class="portfolio">${filter}`);text=text.replace('<tbody><tr><td><h3><a href="https://verify.','<tbody><tr data-tool="delivery" data-category="agents"><td><h3><a href="https://verify.');for(const s of sites)text=replace(text,`<tr><td><h3><a href="https://${s.host}/">`,`<tr data-tool="${s.id}" data-category="${topics[s.id].category}"><td><h3><a href="https://${s.host}/">`);
 text=replace(text,'</main>','<p id="finder-empty" hidden>No matching task. Try a broader term or select all workflows.</p><section class="hub-path"><h2>A useful place to start</h2><p>Comparing an AI supplier? Review <a href="https://evidence.agiscorecard.com/">task evidence</a>, plan a <a href="https://route.agiscorecard.com/">bounded fallback</a>, then check delivery with <a href="https://verify.agiscorecard.com/">Delivery Lab</a>. Each worksheet runs independently; you control the handoff.</p><p><a href="/publish.html">Share a tool with your team or readers</a> · <a href="/tools.json">Tool catalog for agents</a></p></section></main>');
 text=replace(text,'</body>','<script type="module" src="/hub.mjs"></script></body>');await writeFile('dist/index.html',enrichHead(text,hub,'','Free AI & Web3 Calculators and Review Tools | Web3 Workbench'));
 const cards=sites.map(s=>({id:s.id,name:s.name,url:'https://'+s.host+'/',description:topics[s.id].answer,category:topics[s.id].category,metadata:'https://'+s.host+'/tool.json'}));await writeFile('dist/tools.json',JSON.stringify({updated,version:VERSION,tools:cards},null,2)+'\n');
 const embed=s=>`<a href="https://${s.host}/?utm_source=embed" rel="nofollow"><img src="https://${s.host}/share.png" width="600" height="315" alt="${topics[s.id].query} — ${s.name}" loading="lazy"></a>`;
 const body=`<p>Help a colleague find the right worksheet. Public cards contain only tool information and fictional examples; they never contain a visitor’s records.</p><p>These prepared cards may be embedded or shared with attribution. They do not imply a partnership, endorsement or security certification. Images load from our hosting when embedded. The tool software retains its separate license.</p><div class="publisher-grid">${sites.map(s=>`<section class="publisher-item"><h2>${h(s.name)}</h2><img src="https://${s.host}/share.png" width="600" height="315" alt="${h(topics[s.id].query)}" loading="lazy"><p>${h(s.description)}</p><p><a href="https://${s.host}/share.png" download>Open image</a> · <a href="https://${s.host}/examples.html">Worked examples</a></p><details><summary>Copy a plain link, Markdown or HTML card</summary><label for="link-${s.id}">Public tool link</label><textarea id="link-${s.id}" readonly rows="2">https://${s.host}/</textarea><label for="md-${s.id}">Markdown link</label><textarea id="md-${s.id}" readonly rows="2">[${h(s.name)}](https://${s.host}/) — ${h(s.description)}</textarea><label for="embed-${s.id}">Optional HTML card</label><textarea id="embed-${s.id}" readonly rows="4">${h(embed(s))}</textarea></details></section>`).join('')}</div><h2>For an article or resource list</h2><p>Cite the specific tool’s method and worked example. Describe the task it actually handles and retain its assumptions. Please do not call these tools audited, independently certified, AI-powered analysis or investment advice.</p><p><a href="/tools.json">Structured catalog</a> · <a href="/llms-full.txt">Text reference</a> · <a href="/">Browse the tools</a></p>`;
 await writeFile('dist/publish.html',enrichHead(replaceMain(await readFile('dist/guide.html','utf8'),'Share a useful tool',body).replaceAll('https://'+hubHost+'/guide.html','https://'+hubHost+'/publish.html'),hub,'publish.html','Share AI & Web3 Tools — Links and Cards | Web3 Workbench'));
 for(const path of ['guide.html','privacy.html'])await writeFile('dist/'+path,enrichHead(await readFile('dist/'+path,'utf8'),hub,path,(path==='guide.html'?'Choose a workflow':'Privacy and local processing')+' | Web3 Workbench'));
 await writeFile('dist/llms-full.txt',sites.map(markdown).join('\n\n---\n\n'));
 await writeFile('dist/llms.txt','# Web3 Workbench\n\nFree local tools for AI and Web3 operational review. No live trading, custody or model calls.\n\n'+cards.map(c=>`- [${c.name}](${c.url}): ${c.description}`).join('\n')+'\n\n- [Structured catalog](https://'+hubHost+'/tools.json)\n- [Full methods](https://'+hubHost+'/llms-full.txt)\n- [Sharing cards](https://'+hubHost+'/publish.html)\n');
}
export async function enrich(){
 const cardData=[];
 for(const s of sites){const dir='dist/'+s.id;let html=await readFile(dir+'/index.html','utf8');await writeFile(dir+'/index.html',upgradeHome(html,s));
  let guide=nav(await readFile(dir+'/guide.html','utf8'));guide=replace(guide,'<h1>Use '+h(s.name)+'</h1>',`<h1>${h(topics[s.id].query)}: method and guide</h1><p class="byline">By the AGI Scorecard team · Reviewed <time datetime="${updated}">19 September 2026</time></p>`);guide=replace(guide,'<h2>Worked example</h2>',`<p><a href="/examples.html">Explore three scenarios and their calculated results</a>.</p><h2>Worked example</h2>`);guide=replace(guide,'</main>',`<h2>A mistake worth catching</h2><p>${h(topics[s.id].mistake)}</p>${faqs(s)}<p><a href="/guide.md">Markdown method</a> · <a href="/input.schema.json">Structural input schema</a> · <a href="/tool.json">Capabilities and limits</a></p>${related(s)}</main>`);await writeFile(dir+'/guide.html',enrichHead(guide,s,'guide.html',topics[s.id].query+' — Method | '+s.name));
  let example=replaceMain(await readFile(dir+'/guide.html','utf8'),topics[s.id].query+': worked examples',exampleBody(s));example=example.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/g,'').replace(/<meta (?:name="(?:robots|twitter:[^"]+)"|property="og:image[^"]*")[^>]*>/g,'');example=example.replace(/(rel="canonical" href=")[^"]+/,`$1https://${s.host}/examples.html`).replace(/(property="og:url" content=")[^"]+/,`$1https://${s.host}/examples.html`);await writeFile(dir+'/examples.html',enrichHead(example,s,'examples.html',topics[s.id].query+' — Examples | '+s.name));
  let privacy=nav(await readFile(dir+'/privacy.html','utf8'));privacy=replace(privacy,'<h2>Optional feedback</h2>','<h2>Reports and public sharing</h2><p>CSV paste and comparison snapshots remain in tab memory. Readable reports and printed pages may include your record labels, addresses or URLs. Public example links include only an allowlisted fictional scenario name. The site does not encode your inputs into share links. Optional embedded cards request a static image from this host.</p><h2>Optional feedback</h2>');await writeFile(dir+'/privacy.html',enrichHead(privacy,s,'privacy.html','Privacy and local processing | '+s.name));
  for(const c of scenarios(s.id)){await writeFile(dir+'/examples/'+c.key+'.json',JSON.stringify(c.input,null,2)+'\n');await writeFile(dir+'/examples/'+c.key+'-report.json',JSON.stringify(run(s.id,c.input),null,2)+'\n');}
  await writeFile(dir+'/tool.json',JSON.stringify(publicMetadata(s.id),null,2)+'\n');await writeFile(dir+'/input.schema.json',JSON.stringify(inputSchema(s.id),null,2)+'\n');await writeFile(dir+'/guide.md',markdown(s));await writeFile(dir+'/llms-full.txt',markdown(s));
  await writeFile(dir+'/llms.txt',`# ${s.name}\n\n${topics[s.id].answer}\n\n- [Tool](https://${s.host}/)\n- [Method](https://${s.host}/guide.html)\n- [Worked examples](https://${s.host}/examples.html)\n- [Markdown reference](https://${s.host}/guide.md)\n- [Capabilities](https://${s.host}/tool.json)\n- [Input structure](https://${s.host}/input.schema.json)\n- [Privacy](https://${s.host}/privacy.html)\n\nFree beta. Version ${VERSION}. Reviewed ${updated}. ${s.limit}\n`);
  cardData.push({id:s.id,name:s.name,topic:topics[s.id].query,host:s.host,color:s.color,metrics:run(s.id,s.sample).metrics.slice(0,2),scenario:scenarios(s.id)[0].title});
 }
 await hubPages();cardData.push({id:'hub',name:'Web3 Workbench',topic:'Bring a question. Leave with a working result.',host:hubHost,color:'#315aa2',metrics:[{label:'Local worksheets',value:'10'},{label:'Fictional scenarios',value:'30'}],scenario:'AI & Web3 operational tools'});
 await writeFile('dist/cards.json',JSON.stringify(cardData));execFileSync('python3',['scripts/cards.py']);
 for(const s of [{id:'hub',host:hubHost},...sites]){const dir='dist/'+(s.id==='hub'?'':s.id+'/'),paths=s.id==='hub'?['','guide.html','publish.html','privacy.html']:['','guide.html','examples.html','privacy.html'];await writeFile(dir+'sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`<url><loc>https://${s.host}/${p}</loc><lastmod>${updated}</lastmod></url>`).join('')}</urlset>`);}
}
