import {readFile,writeFile,mkdir,appendFile} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {sites,hubHost} from '../public/catalog.mjs';import {newPaths} from './market-pages.mjs';
const base='https://'+hubHost;
export async function audit(get){
 const report={asOf:new Date().toISOString(),ok:true,checks:[],sources:null,events:null,feedback:null,changes:[],outcomes:{indexedPages:null,verifiedThirdPartyBacklinks:null,aiCitations:null,paidBuyers:null,revenue:null},notes:['Availability is not indexing. AI-user-agent requests do not authenticate a crawler or prove citation.','Opt-in events are not people or a joined session funnel; incoming channel labels are unverified.','External referral counts are not verified backlinks. Price movements are not customer demand.']};
 async function check(name,fn){try{await fn();report.checks.push({name,ok:true});}catch(e){report.ok=false;report.checks.push({name,ok:false,reason:String(e.message).slice(0,180)});}}
 const require=(v,msg)=>{if(!v)throw Error(msg);};
 await check('source snapshots',async()=>{const [m,b]=await Promise.all([get(base+'/api/market'),get(base+'/api/briefs')]);require(m.status===200&&b.status===200,'Source endpoint unavailable');const market=JSON.parse(m.text),briefs=JSON.parse(b.text);report.sources={market:{status:market.status,retrievedAt:market.retrievedAt,ageSeconds:market.ageSeconds,quotes:market.quotes,source:market.source},briefs:{status:briefs.status,retrievedAt:briefs.retrievedAt,sources:briefs.sources?.map(s=>({id:s.id,status:s.status,checkedAt:s.checkedAt})),items:briefs.items}};require(market.status==='fresh'&&market.quotes?.length===4&&Date.now()-Date.parse(market.retrievedAt)<360000,'Market snapshot missing or stale');require(briefs.status==='fresh'&&Date.now()-Date.parse(briefs.retrievedAt)<3660000,'Official metadata missing or stale');});
 await check('usage and feedback',async()=>{const [g,f]=await Promise.all([get(base+'/api/growth'),get(base+'/api/stats')]);require(g.status===200&&f.status===200,'Measurement unavailable');const growth=JSON.parse(g.text),feedback=JSON.parse(f.text);require(growth.qa===false&&Array.isArray(growth.groups),'Invalid growth envelope');report.events={asOf:growth.asOf,windowDays:growth.windowDays,measurement:growth.measurement,groups:growth.groups};report.feedback={groups:feedback.groups.filter(g=>g.qa===0),measurement:'Self-reported submissions, not independent buyers.'};});
 await Promise.all([{id:'hub',host:hubHost},...sites].map(s=>check(s.host,async()=>{const paths=s.id==='hub'?['/',...newPaths.map(p=>'/'+p),'/for-agents.html']:['/','/guide.html','/for-agents.html'];const sitemap=await get('https://'+s.host+'/sitemap.xml');require(sitemap.status===200,'Sitemap unavailable');for(const p of paths){const url='https://'+s.host+p,r=await get(url);require(r.status===200,'HTTP '+r.status+' '+p);require(r.text.includes('rel="canonical" href="'+url+'"'),'Canonical mismatch '+p);require(!/noindex/i.test(r.headers?.['x-robots-tag']||''),'Noindex '+p);require(sitemap.text.includes('<loc>'+url+'</loc>'),'Sitemap missing '+p);require(r.text.includes('/measure.mjs')&&r.text.includes('measurement-optin'),'Consent/measurement entry missing '+p);}})));
 for(const ua of ['OAI-SearchBot','PerplexityBot'])await check('public AI access '+ua,async()=>{const r=await get(base+'/market.html?__probe=1',ua);require(r.status===200&&r.text.includes('market-live'),'Not reachable with '+ua);});
 const groups=report.events?.groups||[],sum=event=>groups.filter(g=>g.event===event).reduce((a,g)=>a+g.events,0);
 report.summary={optInPageEvents:report.events?sum('page_view'):null,ownTaskEvents:report.events?sum('own_run'):null,reportExportEvents:report.events?sum('report_export'):null,toolOpenEvents:report.events?sum('tool_open'):null,aiReferredEvents:report.events?groups.filter(g=>g.channel==='ai').reduce((a,g)=>a+g.events,0):null};
 report.nextAction=!report.ok?'Repair failed checks before acquisition work.':!report.summary.optInPageEvents?'No opted-in page events observed. Check exposure and consent bias; do not conclude no demand.':!report.summary.ownTaskEvents?'Observed opt-in visits but no own-task event. Inspect task fit and input friction before adding pages.':'Review own-task, report and recurring-need feedback together before proposing a paid deliverable.';
 return report;
}
export const markdown=r=>`# Web3 行情与转化检查\n\n时间：${r.asOf}\n运行检查：${r.ok?'通过':'需要处理'}\n\n行情状态：${r.sources?.market.status||'未知'}；官方动态：${r.sources?.briefs.status||'未知'}。\n自愿页面事件 ${r.summary.optInPageEvents??'未知'}；自己的任务完成事件 ${r.summary.ownTaskEvents??'未知'}；报告导出事件 ${r.summary.reportExportEvents??'未知'}。\n\n${r.nextAction}\n\n${r.checks.filter(c=>!c.ok).map(c=>'- '+c.name+': '+c.reason).join('\n')}\n\n真实收录、第三方外链、AI 引用、付费买家和收入均需另行取证；未接入证据记为 null。事件不是人数，也不是可相除的跨域转化漏斗。\n`;
async function get(url,ua='Web3Workbench-growth-healthbot/1.0'){const r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(20000),headers:{'User-Agent':ua}});return {status:r.status,text:await r.text(),headers:{'x-robots-tag':r.headers.get('x-robots-tag')}};}
async function main(){const report=await audit(get),args=process.argv.slice(2),root=path.resolve(fileURLToPath(new URL('../../..',import.meta.url))),out=path.join(root,'data/autopilot/web3'),check=args.includes('--check');
 if(!check){await mkdir(out,{recursive:true});let previous=null,history=[];try{previous=JSON.parse(await readFile(path.join(out,'latest.json'),'utf8'));}catch{}try{history=JSON.parse(await readFile(path.join(out,'history.json'),'utf8'));}catch{}
  const prior=new Set(previous?.sources?.briefs?.items?.map(x=>x.url)||[]);report.changes=(report.sources?.briefs?.items||[]).filter(x=>!prior.has(x.url)).map(x=>({url:x.url,title:x.title,task:x.task,kind:previous?'new_since_previous_check':'initial_inventory',requiresReview:true}));
  await writeFile(path.join(out,'latest.json'),JSON.stringify(report,null,2)+'\n');await writeFile(path.join(out,'latest.md'),markdown(report));history=history.filter(x=>x.asOf.slice(0,10)!==report.asOf.slice(0,10));history.push({asOf:report.asOf,ok:report.ok,...report.summary,marketStatus:report.sources?.market.status||'unknown'});await writeFile(path.join(out,'history.json'),JSON.stringify(history.slice(-30),null,2)+'\n');
 }
 if(process.env.GITHUB_STEP_SUMMARY)await appendFile(process.env.GITHUB_STEP_SUMMARY,'\n'+markdown(report));console.log(JSON.stringify({asOf:report.asOf,ok:report.ok,summary:report.summary,failed:report.checks.filter(c=>!c.ok)}));if(!report.ok)process.exitCode=1;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))await main();
