import {researchPage,researchPageZh} from './research-page.mjs';
import {readFile,writeFile} from 'node:fs/promises';
import {sites,hubHost} from '../public/catalog.mjs';
const h=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const newPaths=['market.html','briefs.html','stablecoin-payment-check.html','gas-budget-check.html','protocol-change-check.html'];
const link=(id,text,via)=>`<a class="cta" href="https://${id}.agiscorecard.com/?via=${via}#workbench">${text}</a>`;
const tasks=`<section class="decision-paths"><h2>What needs a decision?</h2><div><article><h3>Did the invoice actually settle?</h3><p>A token price near $1 does not match a payment to an invoice. Check the chain, asset, amount and confirmation record.</p><a href="/stablecoin-payment-check.html?via=stablecoin">Check a stablecoin payment</a></article><article><h3>Will fees erase the saving?</h3><p>Separate gas units, effective gas price and ETH/USD. Include proving and verification before comparing deployment choices.</p><a href="/gas-budget-check.html?via=gas">Build a gas and proof budget</a></article><article><h3>Does a protocol change affect my agent?</h3><p>Pin the implemented version, inspect the official change and rerun your evidence review.</p><a href="/protocol-change-check.html?via=protocol-change">Review an integration change</a></article></div></section>`;
const consent=`<aside class="measurement-choice"><label for="measurement-optin"><input id="measurement-optin" type="checkbox"> Share anonymous usage counts for this page visit</label><p>Optional and off by default. Sends fixed action/source categories only, never worksheet inputs or full URLs. <a href="/privacy.html">Privacy</a>.</p></aside>`;
const calc=`<section class="cost-check"><h2>Put the quote in the context of your task</h2><p>Enter a dated source price or your own settlement rate. We do not silently replace your inputs with a moving quote.</p><form id="cost-form"><div class="field-grid">${[['amount','Stablecoin amount','1000','0.01'],['price','Observed USD per token','','0.000001'],['gas','Estimated gas units','21000','1'],['feeGwei','Effective gas price (gwei)','','0.000001'],['ethUsd','Observed ETH/USD','','0.01']].map(([id,label,value,step])=>`<label for="${id}">${label}<input id="${id}" name="${id}" type="number" min="0" max="1000000000000" step="${step}" value="${value}" required></label>`).join('')}</div><button type="submit">Calculate the impact</button><p id="cost-result" role="status"></p></form><p class="quiet">21,000 is a simple native-transfer example, not a token-transfer or contract-call estimate. Obtain the actual gas estimate from your transaction. This calculator runs in your tab.</p></section>`;
const articles={
 'stablecoin-payment-check.html':{title:'Stablecoin invoice paid? Check the evidence before closing it',description:'A practical stablecoin reconciliation checklist: chain, asset, amount, finality and exceptions, with local examples and a downloadable report.',body:`<p class="intro">A wallet notification and a token near $1 are insufficient to close an invoice. Match the payment record to the amount you expected, and keep every exception visible.</p><p lang="zh-CN">稳定币收款痛点：同名代币、不同网络、部分付款和待确认交易都可能造成误判。行情用于金额参考，对账还需要你的实际记录。</p><h2>Check these fields before marking an invoice paid</h2><table><thead><tr><th>Question</th><th>Bring this evidence</th><th>If it is missing</th></tr></thead><tbody><tr><td>Is this the asset and chain you agreed?</td><td>Invoice terms, chain and exact asset identifier</td><td>Keep the receipt unmatched; a ticker alone is insufficient</td></tr><tr><td>How much was received?</td><td>Exact decimal amount and fees, in the agreed unit</td><td>Do not substitute a current USD quote for historical settlement</td></tr><tr><td>Is the payment final under your policy?</td><td>Transaction status and your confirmation rule</td><td>Keep it pending until independently checked</td></tr><tr><td>Does it cover the invoice?</td><td>All partial receipts, identifiers and expected amount</td><td>Report shortfall or overpayment explicitly</td></tr></tbody></table><h2>Try the exception before your real records</h2><p>Use the fictional examples to see how pending, partial and wrong-asset entries remain visible. Then enter your own records locally, review the exceptions and export the report. The worksheet does not query a chain or authenticate a transaction hash.</p>${link('reconcile','Reconcile payment records','stablecoin')} <a href="https://reconcile.agiscorecard.com/examples.html?via=stablecoin">See worked exceptions</a><h2>What a changing price does, and does not, tell you</h2><p>Reference USD value = token amount × observed USD price. Difference from a $1 reference = token amount × (price − 1). For a hypothetical 1,000 units at $0.998, the reference value is $998 and the difference is −$2. This is a fictional arithmetic example, not a current quote or loss claim. Issuer reserve reports and redemption conditions answer different questions from an exchange trade price.</p><p><a href="/market.html?via=stablecoin">Inspect the current source snapshot</a> · <a href="https://www.circle.com/transparency" rel="noreferrer">Circle reserve disclosures</a> · <a href="https://reconcile.agiscorecard.com/guide.html">Full reconciliation method</a></p><h2>What to do with the result</h2><p>Keep pending and mismatched records in an exception queue. Share a reviewed report with your finance colleague, including the agreed currency and the original evidence. Never enter a private key or seed phrase. Current tools are free; there is no custody or payment execution.</p>`},
 'gas-budget-check.html':{title:'Gas and zkML costs: compare the complete workflow',description:'Separate gas units, effective gas price, ETH price, proving time and retries before comparing a Web3 or zkML deployment.',body:`<p class="intro">A low advertised unit price can hide proving time, retries or verification costs. Compare the same workload and acceptance criteria before choosing an implementation.</p><p lang="zh-CN">费用痛点：gas 单价低不等于最终成本低。先核对实际 gas 用量、有效单价、ETH 价格和失败重试，再比较证明或算力方案。</p><h2>Keep the units separate</h2><p>Estimated USD gas cost = gas units × effective price in gwei × 10⁻⁹ × ETH/USD. A hypothetical 21,000 gas at 10 gwei and $2,000/ETH costs $0.42. Those inputs are illustrative, not current market data. A token transfer or contract call needs its own gas estimate; L2 data and operator fees require separate inputs.</p><p><a href="/market.html?via=gas">Use the price-context calculator</a> · <a href="https://ethereum.org/en/developers/docs/gas/" rel="noreferrer">Ethereum gas definitions</a></p><h2>Choose your budget question</h2><ul><li><strong>Proof deployment:</strong> measure proving time, verification gas, model/input/key versions and handoff latency. An artifact hash is not proof verification.</li><li><strong>Compute purchasing:</strong> compare accepted outputs after setup, storage, egress and failures. Do not compare two GPU hourly rates without equivalent measured workloads.</li><li><strong>Agent fallback:</strong> compare expected cost with the worst permitted sequence; a mean does not enforce a budget.</li></ul>${link('proof','Plan proving and verification costs','gas')} ${link('compute','Compare accepted-output costs','gas')} ${link('route','Check a fallback budget','gas')}<h2>Make the comparison reusable</h2><p>Keep a baseline in the same tab, change one assumption, and rerun. Export a readable report with the measurement date and the original method. None of these tools submits a transaction, launches a GPU or benchmarks a provider for you.</p><h2>Recheck when the implementation changes</h2><p>A release announcement is a reason to inspect the change, not evidence that your workload is cheaper. Read the official release and measure your pinned build before replacing a budget assumption.</p><p><a href="/briefs.html?via=gas">Watch official releases</a> · <a href="https://docs.ezkl.xyz/" rel="noreferrer">EZKL documentation</a> · <a href="https://proof.agiscorecard.com/guide.html">Proof Plan method</a></p>`},
 'protocol-change-check.html':{title:'An agent protocol changed. What should you recheck?',description:'Turn official x402, Ethereum and proof-system updates into a bounded integration review with versions, source evidence and repeatable checks.',body:`<p class="intro">A project announcement or code commit is a review trigger. It does not prove a released integration is compatible, secure or ready to accept payment.</p><p lang="zh-CN">协议更新痛点：看到新版本，不清楚自己的集成要改什么。先锁定实际版本、官方变更和验收条件，再运行任务证据与预算检查。</p><h2>A small change review you can repeat</h2><ol><li>Record the exact version or commit your integration runs. Distinguish a repository commit from a tagged release.</li><li>Open the official source and identify the field, network, payment flow or proof interface that changed.</li><li>Mark whether the change is relevant to your implementation. Unknown is a valid result.</li><li>Recheck your explicit acceptance rules on representative cases. Keep old-version and new-version evidence separate.</li><li>Recalculate retry and fallback budgets if the failure path changed. Document the result and unresolved questions before rollout.</li></ol><p><a href="/briefs.html?via=protocol-change">Read the official-source watch</a> · <a href="https://github.com/x402-foundation/x402" rel="noreferrer">x402 source repository</a></p><h2>Use the tool matching the evidence you have</h2>${link('protocol','Read the dated protocol profiles','protocol-change')} ${link('evidence','Review versioned task evidence','protocol-change')} ${link('route','Recheck fallback assumptions','protocol-change')}<p>The protocol profiles are an editorial release snapshot. The live source watch does not silently update those reviewed definitions. Agent Evidence checks supplied records and denominators, not reviewer independence or answer truth.</p><h2>What counts as a useful output?</h2><p>A short review that names the affected version, the original source, the cases you reran and what remains unknown. Keep a report rather than a claim that “the protocol is now safe”. If the change does not affect your integration, record that conclusion with its reason.</p><p><a href="https://evidence.agiscorecard.com/examples.html?via=protocol-change">Inspect conflicting-evidence examples</a> · <a href="/for-agents.html?via=mcp">Run the same calculators through MCP</a></p>`}
};
function page(template,path,title,description,body,lang='en'){

 const url='https://'+hubHost+'/'+path;
 let html=template.replace(/<title>[\s\S]*?<\/title>/,`<title>${h(title)} | Web3 Workbench</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${h(description)}">`).replace(/<meta property="og:title" content="[^"]*">/,`<meta property="og:title" content="${h(title)}">`).replace(/<meta property="og:description" content="[^"]*">/,`<meta property="og:description" content="${h(description)}">`).replace(/<meta property="og:url" content="[^"]*">/,`<meta property="og:url" content="${url}">`).replace(/https:\/\/web3\.agiscorecard\.com\/guide.html/g,url).replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>/g,'').replace(/<main[^>]*>[\s\S]*?<\/main>/,`<main id="main" class="document market-document"><h1>${h(title)}</h1>${body}</main>`);
 const schema={'@context':'https://schema.org','@graph':[{'@type':'WebPage',url,name:title,description,inLanguage:lang,author:{'@type':'Organization',name:'AGI Scorecard team'}}]};
 html=html.replace(/<link rel="canonical" href="[^"]*">/,`<link rel="canonical" href="${url}">`).replace(/<meta property="og:image"[^>]*>/, '').replace('</head>',`<meta property="og:image" content="https://${hubHost}/share.png"><link rel="alternate" hreflang="en" href="https://${hubHost}/market.html"><link rel="alternate" hreflang="zh-CN" href="https://${hubHost}/zh/market.html"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head>`).replace('</body>','<script type="module" src="/market-ui.mjs"></script></body>');return html;
}
export async function marketPages(){
 const template=await readFile('dist/guide.html','utf8');
 await writeFile('dist/market.html',page(template,'market.html','AI & Web3 market research: follow the evidence','Follow AI and compute tokens with dated prices, seven-day samples, a private watchlist baseline and an evidence notebook.',researchPage+`<details class="research-method"><summary>Calculate a payment or gas-cost impact</summary>${calc}${tasks}</details>`).replace('class="document market-document"','class="document market-document research-page"').replace('</body>','<script type="module" src="/research-ui.mjs"></script></body>'));
 const zhTemplate=await readFile('dist/zh/guide.html','utf8');
 await writeFile('dist/zh/market.html',page(zhTemplate,'zh/market.html','AI 与 Web3 行情研究：跟着证据走','跟踪 AI 与算力资产的时间标记行情、七日样本、自选基线和证据笔记。',researchPageZh,'zh-CN').replace('class="document market-document"','class="document market-document research-page"').replace('</body>','<script type="module" src="/research-ui.mjs"></script></body>'));
 await writeFile('dist/briefs.html',page(template,'briefs.html','Official updates, with a task to check next','Follow Ethereum announcements, x402 code changes and EZKL releases, with publication dates, source links and practical review checklists.',`<p class="intro">Read the original change before changing your assumptions.</p><p lang="zh-CN">官方动态每小时按需更新，保留发布时间、抓取时间和来源状态。代码提交不等于已发布功能；更新动态不自动改写工具的已核对规则。</p><p><a href="/updates.xml">Subscribe in an RSS reader</a> · <a href="/api/briefs">JSON for agents</a></p><section id="briefs-live"><!-- LIVE:briefs:start --><p>Checking official sources. Missing feeds are reported explicitly.</p><!-- LIVE:briefs:end --></section><button id="refresh-source" type="button" class="secondary">Refresh sources</button>${tasks}`));
 for(const [path,a]of Object.entries(articles)){
  const citation=`${a.title}. AGI Scorecard team. Method reviewed 2026-09-19. https://${hubHost}/${path}`;
  await writeFile('dist/'+path,page(template,path,a.title,a.description,a.body+`<p class="byline">By the AGI Scorecard team. Method reviewed 19 September 2026. Examples are fictional; source updates have their own dates.</p><section><h2>Cite this method</h2><label for="method-citation">Copyable citation</label><textarea id="method-citation" readonly rows="3">${h(citation)}</textarea><button type="button" data-copy-citation="method-citation">Copy citation</button><p id="citation-status" role="status"></p></section>`));
 }
 const hub=await readFile('dist/index.html','utf8');await writeFile('dist/index.html',hub.replace('<section class="portfolio">',`<section class="market-entry"><h2>What changed, and what should you check?</h2><p>Follow AI and compute markets, compare your saved watchlist and keep an evidence note to review later.</p><a class="cta" href="/market.html?via=market">Open the research board</a> <a href="/briefs.html?via=protocol-change">Read official updates</a></section><section class="portfolio">`));
 const notes='\n\n## Current market and source context\n\n- [Market context](https://'+hubHost+'/market.html): reference prices with retrieval time and stale/unavailable state, not executable quotes.\n- [Official-source watch](https://'+hubHost+'/briefs.html): original links and publication dates; not independent verification.\n- [Research board JSON](https://'+hubHost+'/api/research): curated assets, source timestamps and sampled history; check each quote status. Private notes are never in this feed.\n- [Market JSON](https://'+hubHost+'/api/market)\n- [Source JSON](https://'+hubHost+'/api/briefs)\n- [RSS](https://'+hubHost+'/updates.xml)\nNever treat stale snapshots as live quotes. Do not infer actual payment or price movements from fictional worksheets.\n';
 for(const s of [{id:'hub'},...sites]){
  const prefix='dist/'+(s.id==='hub'?'':s.id+'/');
  for(const name of ['llms.txt','llms-full.txt'])await writeFile(prefix+name,await readFile(prefix+name,'utf8')+notes);
  const filenames=s.id==='hub'?['index.html','guide.html','privacy.html','publish.html','for-agents.html',...newPaths]:['index.html','guide.html','privacy.html','examples.html','for-agents.html'];
  for(const name of filenames){let html=await readFile(prefix+name,'utf8');
   html=html.replace('<nav aria-label="Main">',`<nav aria-label="Main"><a href="https://${hubHost}/market.html?via=market">Market & tasks</a>`);
   html=html.replace('</footer>',consent+'</footer>').replace('</body>','<script type="module" src="/measure.mjs"></script></body>');
   if(name==='privacy.html')html=html.replace('<h2>Hosting and links</h2>',`<h2>Optional saved research</h2><p>The market research board saves a watchlist price baseline or a research note only when you choose Save. These remain in this browser, are never sent to our server, and are usable for up to 30 days; expired records are removed on the next page load. Each has a Delete button. Browser storage is not encrypted. Export downloads a note to your device; it does not publish or send it. Review dates do not schedule notifications. Usage-measurement consent remains separate and is never remembered.</p><h2>Optional usage measurement</h2><p>Measurement is off by default on each page. Choosing the checkbox sends fixed event, page, campaign and coarse source categories plus a random per-event ID for deduplication. No input values, referrer URL, query text, IP address, email, wallet or persistent visitor identifier are stored by this measurement code. No cookies or browser storage remember your choice. DNT/GPC and QA/probe visits are excluded. Consent applies only to this page visit and can be switched off.</p><p>Events are retained for up to 35 days, deleted on the next measurement request. Public /api/growth shows grouped counts over a rolling 28 days, with testing excluded by default. Counts are opt-in events, not people, linked cross-domain sessions, proven referrals or sales. Source categories can be missing or spoofed. Hosting provider metadata policies remain separate.</p><h2>Market and content sources</h2><p>Reference prices refresh on request after five minutes, official metadata after one hour. They may be cached at different edge locations. Receipt time is not trade time; stale snapshots are labelled and snapshots older than a day are hidden. Source failures do not fabricate replacement data. Quotes and official announcements are not transaction verification or investment signals.</p><h2>Hosting and links</h2>`);
   if(name==='for-agents.html')html=html.replace('</main>',`<h2>Current public context</h2><p>Read <a href="https://${hubHost}/api/research">the research board snapshot</a>, <a href="https://${hubHost}/api/market">core price snapshots</a> and <a href="https://${hubHost}/api/briefs">official update metadata</a> over HTTP. These are separate from the deterministic MCP calculators. Always preserve status, source and retrieval time when citing them.</p></main>`);
   await writeFile(prefix+name,html);
  }
 }
 let publish=await readFile('dist/publish.html','utf8');publish=publish.replace('</main>',`<h2>Link to a question your reader actually has</h2><p>Use a relevant method or worked example, not a sitewide unrelated link. These links contain only fixed campaign labels; they do not identify a reader.</p><ul>${Object.entries(articles).map(([path,a])=>`<li><a href="/${path}?via=publisher">${h(a.title)}</a></li>`).join('')}</ul><p>Third-party links and AI citations are only counted as verified when observed. Prepared copy is not a published backlink.</p></main>`);await writeFile('dist/publish.html',publish);
}
