import {createRequire} from 'node:module';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {mentorRoute,ensure} from './server.mjs';import {makeCase,solution,blankState,PRODUCT} from '../../mentor-assets/core.mjs';import {database} from '../create/test-support.mjs';
const require=createRequire(import.meta.url),{chromium}=require(path.resolve('tools/revenue-studio/node_modules/playwright')),root=path.resolve('sites/agiscorecard'),db=database();await ensure(db);let ip=0;
const env={EVENTS:db,MEMBER_WATCH_SECRET:'local-fixture',AI:{run:async(_m,b)=>({response:b.messages[0].content.includes('Simplified Chinese')?'先筛选本周已支付的订单。取消的那一行应该计入吗？':'Filter the current paid rows first. Should a cancelled order be included?'})}};
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://127.0.0.1:'+server.address().port),chunks=[];for await(const c of req)chunks.push(c);const request=new Request(u,{method:req.method,headers:{...req.headers,'CF-Connecting-IP':'browser-'+ip},...(['GET','HEAD'].includes(req.method)?{}:{body:Buffer.concat(chunks)})});let out=await mentorRoute(request,env);if(!out){let p=path.join(root,u.pathname);if(!path.extname(p))p+='.html';if(!p.startsWith(root+path.sep))throw Error('path');try{out=new Response(fs.readFileSync(p),{headers:{'Content-Type':({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png'})[path.extname(p)]||'text/plain'}});}catch{out=new Response('',{status:404});}}res.writeHead(out.status,Object.fromEntries(out.headers));res.end(Buffer.from(await out.arrayBuffer()));}catch(e){console.error(e);res.writeHead(500).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,...(process.env.MENTOR_BROWSER_CONFIG?JSON.parse(fs.readFileSync(process.env.MENTOR_BROWSER_CONFIG,'utf8')):{})});
try{for(const lang of ['en','zh']){ip++;const ctx=await browser.newContext({viewport:{width:390,height:844}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await page.goto(base+(lang==='zh'?'/zh':'')+'/mentor?__qa=1');await page.waitForFunction(()=>document.querySelectorAll('#data-rows tr').length>5);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('#measure').isChecked(),false);
const seed=Number((await page.locator('#case-label').textContent()).split('#')[1]),s=solution(makeCase(seed));await page.locator('#orders').fill(String(s.orders));await page.locator('#revenue').fill(String(s.revenue+800));await page.locator('#channel').selectOption(s.channel[0]);await page.locator('#growth').fill(s.growth.toFixed(1));await page.locator('#claim').selectOption('unproven');await page.locator('#check').click();assert.equal(await page.locator('#score').textContent(),'4 / 5');assert.equal(await page.locator('#level').textContent(),'L0');await page.locator('#revenue').fill(String(s.revenue));await page.locator('#check').click();assert.equal(await page.locator('#score').textContent(),'5 / 5');assert.equal(await page.locator('#level').textContent(),'L1');await page.locator('#next-case').click();const newSeed=Number((await page.locator('#case-label').textContent()).split('#')[1]),n=solution(makeCase(newSeed));await page.locator('#orders').fill(String(n.orders));await page.locator('#revenue').fill(String(n.revenue));await page.locator('#channel').selectOption(n.channel[0]);await page.locator('#growth').fill(n.growth.toFixed(1));await page.locator('#claim').selectOption('unproven');await page.locator('#check').click();assert.equal(await page.locator('#level').textContent(),'L2');await page.reload();await page.waitForFunction(()=>document.querySelector('#level').textContent==='L2');assert.equal(await page.locator('#revenue').inputValue(),String(n.revenue));
await page.locator('#question').fill(lang==='zh'?'退款怎么处理？':'How do refunds affect the total?');await page.locator('#ask').click();assert.equal(await page.locator('#ai-reply').textContent(),'');await page.locator('#ai-consent').check();await page.locator('#ask').click();await page.waitForFunction(()=>document.querySelector('#ai-reply').textContent.length>10);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM mentor_events').get().n,0);
const download=page.waitForEvent('download');await page.locator('#export').click();const file=await download;const backup=JSON.parse(fs.readFileSync(await file.path(),'utf8'));assert.equal(backup.product,PRODUCT);assert.equal(backup.values.attempts.length,3);await page.locator('#send-feedback').click();await page.waitForFunction(()=>document.querySelector('#feedback-status').textContent.length>0);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM mentor_feedback').get().n,0);
const popupWait=page.waitForEvent('popup');await page.locator('#save-cloud').click();const popup=await popupWait;await popup.waitForLoadState();assert.equal(new URL(popup.url()).searchParams.get('tool'),PRODUCT);await popup.waitForFunction(()=>document.querySelector('#payload')?.value.includes('work-mentor'));const cloudDraft=JSON.parse(await popup.locator('#payload').inputValue());assert.equal(cloudDraft.product,PRODUCT);assert.equal(cloudDraft.values.attempts.length,3);await popup.close();await page.locator('#practice').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/mentor-'+lang+'-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/tmp/mentor-'+lang+'-desktop.png',fullPage:true});assert.deepEqual(errors,[]);await ctx.close();console.log(lang+': mobile, corrected result, new-case transfer, persistence, consent, AI fixture, no QA telemetry, export and cloud handoff passed');}
}finally{await browser.close();server.close();db.sqlite.close();}
