import {scenarios} from './public/experience.mjs';
import {sites,hubHost} from './public/catalog.mjs';
import {profiles,selectProfiles,CHECKED_AT} from './public/profiles.mjs';
import {release} from './release.generated.mjs';
const hosts=new Map([[hubHost,'hub'],...sites.map(s=>[s.host,s.id])]);
const shared=new Set(['app.mjs','catalog.mjs','core.mjs','engine.mjs','finance.mjs','evidence.mjs','planning.mjs','inspection.mjs','profiles.mjs','style.css','mark.svg','runner.mjs','LICENSE.txt','offline-tools.zip','release.json','experience.mjs','hub.mjs','16507d8e1997c4be371f5fbaf7ac1985.txt']);
const pages=new Set(['/','/index.html','/guide.html','/privacy.html','/robots.txt','/sitemap.xml','/llms.txt','/examples/input.json','/examples/report.json','/share.png','/llms-full.txt']);
const security={'Content-Security-Policy':"default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' https://*.agiscorecard.com; connect-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'",'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Strict-Transport-Security':'max-age=31536000; includeSubDomains'};
const json=(v,status=200,headers={})=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}});
async function setup(db){await db.prepare('CREATE TABLE IF NOT EXISTS web3_studio_feedback (id TEXT PRIMARY KEY,site TEXT NOT NULL,frequency TEXT NOT NULL,usefulness TEXT NOT NULL,interest TEXT NOT NULL,own_completed INTEGER NOT NULL,qa INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)').run();await db.prepare("DELETE FROM web3_studio_feedback WHERE created_at < datetime('now','-35 days')").run();}
export function feedbackShape(v){if(!v||typeof v!=='object'||Array.isArray(v))return false;const fields=['id','frequency','usefulness','interest','ownCompleted','qa'];return Object.keys(v).length===fields.length&&fields.every(k=>Object.hasOwn(v,k))&&typeof v.id==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v.id)&&['zero','once','repeat'].includes(v.frequency)&&['sample','helped','blocked','alternative'].includes(v.usefulness)&&['no','free','discuss'].includes(v.interest)&&typeof v.ownCompleted==='boolean'&&typeof v.qa==='boolean';}
async function body(request){const reader=request.body?.getReader();if(!reader)throw Error('Missing body');let n=0,chunks=[];while(true){const r=await reader.read();if(r.done)break;n+=r.value.byteLength;if(n>1024){await reader.cancel();throw Error('Body limit');}chunks.push(r.value);}const bytes=new Uint8Array(n);let at=0;for(const c of chunks){bytes.set(c,at);at+=c.length;}return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}
function profileResponse(rows){const ageDays=Math.floor((Date.now()-Date.parse(CHECKED_AT))/86400000);return {version:release.version,revision:release.revision,checkedAt:CHECKED_AT,ageDays,stale:ageDays<0||ageDays>30,scope:'Editorial release snapshot; not conformance certification or live monitoring.',profiles:rows};}
const openapi={openapi:'3.1.0',info:{title:'Protocol Ledger source profiles',version:'1.0.0',description:'Free dated editorial snapshot. No live-chain, pricing or conformance guarantee.'},servers:[{url:'https://protocol.agiscorecard.com'}],paths:{'/api/v1/profiles':{get:{operationId:'listProfiles',parameters:[{name:'purpose',in:'query',schema:{type:'string',enum:['all','payment','identity','token']}},{name:'status',in:'query',schema:{type:'string',enum:['all','draft','standard','specification']}}],responses:{'200':{description:'Dated records, source URLs and stale state',content:{'application/json':{schema:{$ref:'#/components/schemas/ProfileResponse'}}}},'400':{description:'Unknown query field or enum'}}}},'/api/v1/profiles/{id}':{get:{operationId:'getProfile',parameters:[{name:'id',in:'path',required:true,schema:{type:'string'}}],responses:{'200':{description:'One source-backed record',content:{'application/json':{schema:{$ref:'#/components/schemas/ProfileResponse'}}}},'404':{description:'Unknown ID'}}}}},components:{schemas:{ProfileResponse:{type:'object',required:['version','revision','checkedAt','ageDays','stale','scope','profiles'],properties:{version:{type:'string'},revision:{type:'string'},checkedAt:{type:'string',format:'date'},ageDays:{type:'integer'},stale:{type:'boolean'},scope:{type:'string'},profiles:{type:'array',items:{type:'object',required:['id','name','purpose','network','status','version','source','checkedAt','claim','fields','boundary','tags'],properties:Object.fromEntries(['id','name','purpose','network','status','version','source','checkedAt','claim','boundary'].map(k=>[k,{type:'string'}]).concat([['fields',{type:'array',items:{type:'string'}}],['tags',{type:'array',items:{type:'string'}}]]))}}}}}}};
export async function handle(request,env){
 const u=new URL(request.url),site=hosts.get(u.hostname);if(!site)return json({error:'Unknown host'},404);if(u.pathname==='/api/health')return request.method==='GET'||request.method==='HEAD'?json({...release,site,host:u.hostname}):json({error:'Method not allowed'},405,{Allow:'GET, HEAD'});
 if(site==='protocol'&&(u.pathname==='/api/v1/profiles'||u.pathname.startsWith('/api/v1/profiles/')||u.pathname==='/openapi.json')){
  const cors={'Access-Control-Allow-Origin':'*'};if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...cors,'Access-Control-Allow-Methods':'GET, HEAD, OPTIONS'}});if(!['GET','HEAD'].includes(request.method))return json({error:'Read-only API'},405,cors);if(u.pathname==='/openapi.json')return json(openapi,200,cors);
  const keys=[...u.searchParams.keys()];if(keys.some(k=>!['purpose','status'].includes(k))||new Set(keys).size!==keys.length)return json({error:'Unknown or repeated filter'},400,cors);
  const purpose=u.searchParams.get('purpose')||'all',status=u.searchParams.get('status')||'all';if(!['all','payment','identity','token'].includes(purpose)||!['all','draft','standard','specification'].includes(status))return json({error:'Invalid filter'},400,cors);
  if(u.pathname==='/api/v1/profiles')return json(profileResponse(selectProfiles({purpose,status})),200,cors);const id=u.pathname.slice('/api/v1/profiles/'.length),record=profiles.find(p=>p.id===id);return record?json(profileResponse([record]),200,cors):json({error:'Unknown profile'},404,cors);
 }
 if(u.pathname==='/api/feedback'){
  if(site==='hub')return json({error:'Choose a tool first'},400);if(request.method!=='POST')return json({error:'POST required'},405,{Allow:'POST'});if(request.headers.get('Origin')!==u.origin)return json({error:'Origin rejected'},403);if(!/^application\/json(?:;|$)/i.test(request.headers.get('Content-Type')||''))return json({error:'Use application/json'},415);if(!env.DB||!env.EVENT_LIMIT)return json({error:'Feedback unavailable'},503);
  const limited=await env.EVENT_LIMIT.limit({key:site+':'+(request.headers.get('CF-Connecting-IP')||'unknown')});if(!limited.success)return json({error:'Please try again later'},429);
  let value;try{value=await body(request);}catch{return json({error:'Invalid JSON or body over 1 KiB'},400);}if(!feedbackShape(value))return json({error:'Invalid feedback fields'},400);await setup(env.DB);await env.DB.prepare('INSERT OR IGNORE INTO web3_studio_feedback (id,site,frequency,usefulness,interest,own_completed,qa) VALUES (?,?,?,?,?,?,?)').bind(value.id,site,value.frequency,value.usefulness,value.interest,value.ownCompleted?1:0,value.qa?1:0).run();return json({saved:true});
 }
 if(u.pathname==='/api/stats'){
  if(!['GET','HEAD'].includes(request.method))return json({error:'GET required'},405);if(!env.DB)return json({error:'Feedback unavailable'},503);await setup(env.DB);const query=site==='hub'?'SELECT site,frequency,usefulness,interest,own_completed,qa,COUNT(*) AS submissions FROM web3_studio_feedback GROUP BY site,frequency,usefulness,interest,own_completed,qa':'SELECT site,frequency,usefulness,interest,own_completed,qa,COUNT(*) AS submissions FROM web3_studio_feedback WHERE site=? GROUP BY site,frequency,usefulness,interest,own_completed,qa';const stmt=env.DB.prepare(query);const result=await(site==='hub'?stmt:stmt.bind(site)).all();return json({measurement:'Anonymous submissions, not verified people or customers. qa=1 is testing.',groups:result.results});
 }
 if(!['GET','HEAD'].includes(request.method))return json({error:'Method not allowed'},405,{Allow:'GET, HEAD'});
 if(u.pathname==='/index.html')return new Response(null,{status:308,headers:{Location:u.origin+'/'+u.search}});
 const toolPages=site!=='hub'?new Set(['/examples.html','/tool.json','/input.schema.json','/guide.md',...scenarios(site).flatMap(c=>['/examples/'+c.key+'.json','/examples/'+c.key+'-report.json'])]):new Set(['/publish.html','/tools.json']);
 let path;if(shared.has(u.pathname.slice(1)))path=u.pathname;else if(pages.has(u.pathname)||toolPages.has(u.pathname)){if(site==='hub'&&u.pathname.startsWith('/examples/'))return json({error:'Not found'},404);path=(site==='hub'?'':'/'+site)+(u.pathname==='/'?'/index.html':u.pathname);}else return json({error:'Not found'},404);
 const assetUrl=new URL(request.url);assetUrl.pathname=path;assetUrl.search='';const response=await env.ASSETS.fetch(new Request(assetUrl,{method:request.method}));const headers=new Headers(response.headers);
 if(u.pathname==='/guide.md')headers.set('Content-Type','text/markdown; charset=utf-8');
 if(['/guide.md','/llms-full.txt'].includes(u.pathname))headers.set('Link','<'+u.origin+'/guide.html>; rel="canonical"');
 if(u.pathname.endsWith('.json')||u.pathname==='/guide.md'||u.pathname==='/llms-full.txt')headers.set('X-Robots-Tag','noindex');
 return new Response(response.body,{status:response.status,headers});
}
export default {async fetch(request,env){let response;try{response=await handle(request,env);}catch{response=json({error:'Service temporarily unavailable'},503);}const headers=new Headers(response.headers);for(const[k,v]of Object.entries(security))headers.set(k,v);headers.set('Cache-Control',request.url.includes('/api/')?'no-store':'public, max-age=0, must-revalidate');return new Response(request.method==='HEAD'?null:response.body,{status:response.status,headers});}};
