import {VERSION,relevantMemory,markdown,safeURL} from './core.mjs';
const zh=document.body.dataset.lang==='zh',lang=zh?'zh':'en',t=(en,cn)=>zh?cn:en,$=s=>document.querySelector(s);
const KEY='agi-jarvis-key-v1',MEM='agi-jarvis-memory-v1';let tasks=[],selected=null,busy=false,poll=null;
const observed=new Set();
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const uid=bytes=>[...crypto.getRandomValues(new Uint8Array(bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');
const event=name=>{if(!new URL(location.href).searchParams.has('__qa'))dispatchEvent(new CustomEvent('fleet:business',{detail:{name:'jarvis_'+name}}));};
const status=text=>{$('#status').textContent=text;};
function storageGet(k){try{return localStorage.getItem(k);}catch{return null;}}
function storageSet(k,v){try{localStorage.setItem(k,v);return localStorage.getItem(k)===v;}catch{return false;}}
function key(){let token=storageGet(KEY);if(!/^[a-f0-9]{64}$/.test(token||'')){token=uid(32);if(!storageSet(KEY,token))throw Error('storage_unavailable');}return token;}
function memories(){try{const m=JSON.parse(storageGet(MEM)||'[]');return Array.isArray(m)?m.filter(s=>typeof s==='string'&&s.length<=300).slice(0,8):[];}catch{return [];}}
async function api(body){
 const r=await fetch('/api/jarvis'+(body?'':'/tasks'),{method:body?'POST':'GET',headers:{authorization:'Bearer '+key(),...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});
 let j;try{j=await r.json();}catch{throw Error('unavailable');}if(!r.ok||!j.ok)throw Error(j.code||'unavailable');return j;
}
const errors={rate_limited:t('The shared limit is reached. Your existing results are safe. Try again after the quota window resets.','已达到共享额度，现有结果仍保留。请在额度窗口重置后再试。'),active_limit:t('Pause an active mission or delete an old task (3 active, 20 saved maximum).','请先暂停正在执行的任务或删除旧记录（最多 3 个活动任务、20 条记录）。'),storage_unavailable:t('Browser storage is unavailable. Enable it before submitting so you can return to your private tasks.','浏览器存储不可用。请先启用存储，再提交任务，以便回来查看私有记录。'),cannot_resume:t('This task cannot resume. Start a new mission for another seven-day window.','本任务已不能恢复，可新建任务开始下一轮跟踪。'),unauthorized:t('The private browser key is missing or invalid.','本浏览器的私有访问密钥缺失或无效。'),invalid_request:t('Check the goal, language, memories and cloud consent.','请检查目标、记忆与云端执行选项。')};
function fail(e){status(errors[e.message]||t('Could not connect. Your current result is preserved; use Refresh to try again.','暂时连接失败，当前结果仍保留；可点击刷新重试。'));}
const labels={queued:t('Queued','等待执行'),running:t('Working','执行中'),watching:t('Daily watch active','每日跟踪中'),completed:t('Draft ready','草稿已生成'),limited:t('Source pack only','仅资料包'),paused:t('Paused','已暂停')};
const reasons={evidence_unavailable:t('The requested public evidence was not retrieved. AI synthesis was skipped.','未取得本次需要的公开证据，已跳过 AI 综合。'),rate_limited:t('The shared model allowance is exhausted.','共享模型额度已耗尽。'),ai_unavailable:t('The model is unavailable.','模型暂不可用。'),model_unavailable:t('The model provider did not return a usable response.','模型服务未返回可用结果。'),model_timeout:t('The model response timed out.','模型响应超时。'),invalid_model_output:t('The model output did not pass format or citation checks.','模型输出未通过格式或引用检查。'),run_failed:t('The run could not finish.','本次运行未完成。')};
function date(n){return new Date(n*1000).toLocaleString(zh?'zh-CN':'en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});}
function renderList(){const list=$('#task-list');list.replaceChildren();if(!tasks.length){list.append(el('p',t('Start with one real task. Your results will stay here for 30 days.','从一项真实任务开始，结果会在这里保留 30 天。'),'quiet'));return;}
 for(const task of tasks){const b=el('button',undefined,'mission-item');b.type='button';b.setAttribute('aria-current',String(task.id===selected));b.append(el('strong',task.input.goal.slice(0,85)),el('span',(labels[task.status]||task.status)+' · '+date(task.created)));b.onclick=()=>{selected=task.id;render();};list.append(b);}}
function btn(text,fn,cls='secondary'){const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;}
async function mutate(action,extra={}){if(busy)return;busy=true;try{await api({action,id:selected,...extra});if(action==='delete')selected=null;event(action);await refresh();}catch(e){fail(e);}finally{busy=false;}}
function render(){renderList();const task=tasks.find(x=>x.id===selected);$('#compose').hidden=!!task;const d=$('#task-detail');d.hidden=!task;if(!task)return;d.replaceChildren();
 const r=task.result||{},top=el('div',undefined,'status-line');top.append(el('span',labels[task.status]||task.status,'status-pill'),el('span',t('Run ','已运行 ')+task.runs+(task.input.cadence==='daily'?' / 7':'')));d.append(top,el('h2',task.input.goal,'mission-title'));
 const pipeline=el('ol',undefined,'pipeline'),steps=[['observe',t('Observe','观察')],['plan',t('Plan','规划')],['tools',t('Use tools','调用工具')],['verify',t('Check','检查')],['complete',t('Deliver','交付')]],stage=task.stage==='thinking'?'plan':task.stage;
 for(const [id,label] of steps)pipeline.append(el('li',label,(id===stage||stage==='complete')?'active':''));d.append(pipeline);
 if(task.status==='queued'||task.status==='running')d.append(el('p',t('This task is saved. You can leave this page; the background runner checks queued work about every two hours; scheduled checks can be delayed.','任务已保存。你可以离开页面，后台约每两小时检查待执行任务，调度可能延迟。'),'notice'));
 if(task.stage==='interrupted')d.append(el('p',t('The previous worker stopped before completion. Review the retained record, then choose Run again.','上次运行在完成前中断。请查看保留的记录，再点击重新运行。'),'notice'));
 if(r.reason)d.append(el('p',(reasons[r.reason]||reasons.run_failed)+' '+t('These are retrieved sources, not a completed AI report.','以下是检索到的资料，不是已完成的 AI 报告。'),'notice'));
 if(r.report){d.append(el('p',t('AI draft · check the original sources before relying on it.','AI 草稿 · 使用前请核对原始来源。'),'notice'),el('p',r.report.summary,'report-summary'));if(r.report.findings.length)d.append(el('h3',t('AI interpretations to check','AI 解读（待核对）')));
  for(const f of r.report.findings){const n=el('div',undefined,'finding');n.append(el('p',f.text));for(const id of f.sourceIds){const a=el('a','['+id+'] ');a.href='#source-'+id;n.append(a);}d.append(n);}
  d.append(el('h3',t('Next actions to try','建议尝试的下一步')));for(const a of r.report.nextActions){const n=el('div',undefined,'next-action');n.append(el('strong',a.action),el('p',t('Done when: ','完成标准：')+a.doneWhen,'quiet'));d.append(n);}
  d.append(el('h3',t('What is still uncertain','仍然不确定的部分')));const ul=el('ul');for(const u of r.report.uncertainties)ul.append(el('li',u));d.append(ul);
  d.append(el('p',t('Citation IDs were checked. They do not prove every interpretation is correct; inspect the linked sources.','已检查引用编号，但这不代表每条解读都正确，请核阅原始来源。'),'quiet small'));
 }
 if(r.sources){d.append(el('h3',t('Sources you can inspect','可以核阅的来源')+' ('+r.sources.length+')'));if(!r.sources.length)d.append(el('p',t('No matching sources were retrieved. Refine the goal or enable public search.','未检索到匹配来源，可以细化目标或启用公开搜索。'),'quiet'));
  for(const s of r.sources){const n=el('div',undefined,'source');n.id='source-'+s.id;const href=safeURL(s.url);if(href){const a=el('a',s.title);a.href=href;a.target='_blank';a.rel='noopener noreferrer';a.onclick=()=>event('source_open');n.append(a);}else n.append(el('strong',s.title));n.append(el('p',s.description||'','quiet'));const kinds={editorial_view:t('Editorial view','编辑观点'),discovered_metadata:t('Unreviewed publisher metadata','未核阅的发布者元数据'),repository_metadata:t('Repository metadata','仓库元数据'),discussion_metadata:t('Discussion metadata','讨论元数据'),arithmetic:t('Arithmetic','算术结果')};n.append(el('span',(kinds[s.kind]||s.kind)+' · '+(s.publishedAt||s.updatedAt||s.checkedAt||'').slice(0,10),'source-id'));d.append(n);}
 }
 if(task.nextRun)d.append(el('p',t('Next background check: ','下次后台检查：')+date(task.nextRun),'quiet'));if(task.previous?.summary){const previous=el('details');previous.append(el('summary',t('Previous result','上次结果')),el('p',task.previous.summary,'quiet'));d.append(previous);}
 const actions=el('div',undefined,'task-actions');actions.append(btn(t('Refresh','刷新'),()=>refresh()),btn(t('Export result','导出结果'),()=>{const blob=new Blob([markdown(task)],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='jarvis-result.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);event('export');}));
 if(['queued','running','watching'].includes(task.status))actions.append(btn(t('Pause','暂停'),()=>mutate('pause')));
 else if(task.runs<7&&task.until>Date.now()/1000)actions.append(btn(t('Run again','重新运行'),()=>mutate('resume')));
 actions.append(btn(t('Continue with this goal','继续这个目标'),()=>{selected=null;render();$('#goal').value=task.input.goal;$('#goal').focus();status(t('Edit the goal or memories, then start a new mission.','编辑目标或记忆后，即可开始新任务。'));}));
 actions.append(btn(t('Delete task','删除任务'),()=>{if(confirm(t('Delete this task and its saved result?','删除本任务及保存的结果？')))mutate('delete');},'danger'));d.append(actions);
 if(r.report||task.stage==='source_pack'){const fb=el('div',undefined,'feedback');fb.append(el('span',t('Did this help with your task?','这次结果对你的任务有帮助吗？'),'quiet'));for(const [value,label]of [['useful',t('Useful','有用')],['not_useful',t('Not yet','还没有')]]){const b=btn(label,()=>mutate('feedback',{value}));b.setAttribute('aria-pressed',String(task.feedback===value));fb.append(b);}d.append(fb);}
 const ex=el('details',undefined,'execution');ex.append(el('summary',t('Execution record','执行记录')+' · '+(r.modelCalls||0)+t(' model calls',' 次模型调用')));const ol=el('ol');for(const x of r.log||[])ol.append(el('li',x.step+': '+x.outcome));ex.append(ol,el('p',t('Only the listed tools ran. Proposed actions are not completed actions.','仅执行了记录中的工具，建议行动不等于已完成行动。'),'quiet small'));d.append(ex);
 d.append(el('p',t('Task expires: ','任务记录到期：')+date(task.expires),'quiet small'));
}
async function refresh(){try{const j=await api();tasks=j.tasks;for(const task of tasks){const k=task.id+':'+task.runs;if(task.runs&&!observed.has(k)){observed.add(k);if(task.result?.report)event('report_ready');else if(task.stage==='source_pack')event('source_pack');}}
 if(selected&&!tasks.some(x=>x.id===selected))selected=null;render();status('');schedulePoll();}catch(e){fail(e);schedulePoll();}}
function schedulePoll(){clearTimeout(poll);if(!document.hidden&&tasks.some(x=>['queued','running'].includes(x.status)))poll=setTimeout(refresh,10000);}
function renderMemories(){const selectedTexts=new Set([...document.querySelectorAll('[data-memory]:checked')].map(x=>x.value)),m=memories(),suggested=relevantMemory($('#goal').value,m);const box=$('#selected-memories');box.replaceChildren();if(!m.length)return;box.append(el('p',t('Include up to 3 memories in this task:','为本次任务选择最多 3 条记忆：'),'quiet'));const sorted=[...suggested,...m.filter(x=>!suggested.includes(x))];for(const text of sorted){const label=el('label',undefined,'check'),input=el('input');input.type='checkbox';input.dataset.memory='';input.value=text;input.checked=selectedTexts.has(text);input.onchange=()=>{if(document.querySelectorAll('[data-memory]:checked').length>3){input.checked=false;status(t('Choose at most 3 memories.','最多选择 3 条记忆。'));}};label.append(input,document.createTextNode(text));box.append(label);}}
$('#memory').value=memories().join('\n');$('#save-memory').onclick=()=>{const lines=$('#memory').value.split('\n').map(s=>s.trim()).filter(Boolean);if(lines.length>8||lines.some(s=>s.length>300)){status(t('Use up to 8 lines, with at most 300 characters each.','最多 8 行，每行不超过 300 个字符。'));return;}if(!storageSet(MEM,JSON.stringify([...new Set(lines)])))return fail(Error('storage_unavailable'));renderMemories();status(t('Memories saved on this device.','记忆已保存在本机。'));event('memory_save');};
$('#goal').addEventListener('change',renderMemories);$('#new-task').onclick=()=>{selected=null;render();$('#goal').focus();};
const examples=zh?['我每周花两小时整理工作报告。研究可以采用的 AI 工作流程，并设计一个本周能验证的小测试。','研究一个面向独立开发者的低成本 AI 助手产品：比较已有方案，列出反对理由和最小需求验证。','我想用每周三小时学习 AI Agent 开发。制定一个以可运行作品为目标的学习计划，并找出可参考的来源。']:['I spend two hours preparing a weekly report. Research a practical AI workflow and design a small test I can run this week.','Research a low-cost AI assistant for solo developers. Compare existing approaches, state the strongest counterargument and propose a small demand test.','I have three hours a week to learn AI agent development. Build a learning plan around a working project and find useful sources.'];
$('#web').onchange=()=>{$('#public-query-label').hidden=!$('#web').checked;$('#public-query').required=$('#web').checked;};
for(const b of document.querySelectorAll('[data-example]'))b.onclick=()=>{$('#goal').value=examples[Number(b.dataset.example)];$('#public-query').value=['AI workflow','personal AI agent','AI agent tutorial'][Number(b.dataset.example)];renderMemories();$('#goal').focus();};
$('#task-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('#start').disabled=true;status(t('Saving your mission…','正在保存任务…'));try{const j=await api({action:'create',goal:$('#goal').value,lang,cadence:$('#cadence').value,web:$('#web').checked,publicQuery:$('#public-query').value,consent:$('#cloud-consent').checked,memory:[...document.querySelectorAll('[data-memory]:checked')].map(x=>x.value),nonce:uid(16)});selected=j.task.id;tasks.unshift(j.task);render();event('start');schedulePoll();status(t('Saved. Your mission is queued.','已保存，任务正在等待执行。'));}catch(e){fail(e);}finally{busy=false;$('#start').disabled=false;}};
document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(poll);else if(storageGet(KEY))refresh();});
renderMemories();document.body.dataset.ready='true';if(storageGet(KEY))refresh();
export {VERSION};
