const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');
(async()=>{const browser=await chromium.launch({headless:true});const dir=process.env.QA_DIR||'/tmp/eco-energy-qa';await fs.mkdir(dir,{recursive:true});let checks=0;const ok=(a,b)=>{assert.equal(a,b);checks++;};const base=process.env.TEST_BASE_URL||'http://127.0.0.1:8765';
const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});let events=[],errors=[];await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.pathname==='/api/ev'){events.push(JSON.parse(route.request().postData()));await route.fulfill({status:200,body:'{}'});}else if(u.origin!==new URL(base).origin)await route.abort();else await route.continue();});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));const run=async()=>{await page.check('[name=confirm]');await page.click('button[type=submit]');await page.waitForSelector('#results:not([hidden])');};
for(const [slug,expected] of [['stromtarif-werkstatt.html','124,00'],['en/energy-tariff-workbench.html','124.00'],['fr/comparateur-electricite.html','0,00'],['es/comparar-tarifas-luz.html','84,00'],['it/confronto-tariffe-luce.html','3,00']]){await page.goto(base+'/'+slug+'?__probe=1');await page.waitForFunction(()=>document.querySelector('[name=Bmode]').value==='period'||document.querySelector('[name=market]').value==='de');ok(await page.isHidden('#results'),true);await page.click('button[type=submit]');ok(await page.isHidden('#results'),true);await run();ok((await page.textContent('#first-saving')).includes(expected),true);ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);ok((await page.textContent('#ledger')).includes('undefined'),false);await page.click('#save');ok((await page.locator('#saved>div').count())>0,true);await page.fill('[name=Afixed]','200');ok(await page.isHidden('#results'),true);}
ok(events.length,0);ok(errors.length,0);
await page.goto(base+'/stromtarif-werkstatt.html?__probe=1');await run();await page.screenshot({path:dir+'/de-mobile-result.png',fullPage:true});await page.setViewportSize({width:1280,height:900});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:dir+'/de-desktop.png',fullPage:true});
for(const market of ['de','fr','es','it']){await page.selectOption('[name=market]',market);await run();ok(await page.isVisible('#results'),true);ok(await page.locator('[data-band]:visible').count(),market==='de'?1:market==='fr'?2:3);}
await page.selectOption('[name=market]','fr');await page.check('[name=purpose][value=own]');await run();ok((await page.textContent('#scenarios')).includes('30'),true);await page.click('#share');const shared=await page.inputValue('#share-url');ok(shared.includes('#tariff='),true);const exportPromise=page.waitForEvent('download');await page.click('#export');const downloaded=await exportPromise;const exportFile=dir+'/roundtrip.json';await downloaded.saveAs(exportFile);const data=JSON.parse(await fs.readFile(exportFile,'utf8'));ok(data.scenario.own,true);ok(data.result.threshold>.299&&data.result.threshold<.301,true);
await page.selectOption('[name=market]','de');await run();await page.goto(shared.replace('#','?__probe=1#'));await page.waitForFunction(()=>document.querySelector('[name=market]').value==='fr'&&document.querySelector('#results').hidden);ok(await page.inputValue('[name=market]'),'fr');ok(await page.isHidden('#results'),true);await run();ok((await page.textContent('#first-saving')).includes('0,00'),true);await page.setInputFiles('#import-file',exportFile);await page.waitForFunction(()=>!document.querySelector('[name=confirm]').checked);ok(await page.isHidden('#results'),true);await run();
await page.setInputFiles('#csv-file',{name:'kwh.csv',mimeType:'text/csv',buffer:Buffer.from('kwh1;kwh2\n1000;500\n1100;400')});await page.waitForFunction(()=>!document.querySelector('[name=confirm]').checked);ok(await page.inputValue('[name=kwh0]'),'2100');ok(await page.inputValue('[name=kwh1]'),'900');await run();
await page.locator('#options').evaluate(e=>e.open=true);await page.fill('[name=shift]','2101');await page.click('button[type=submit]');ok(await page.isHidden('#results'),true);await page.fill('[name=shift]','300');await run();await page.screenshot({path:dir+'/fr-result.png',fullPage:true});
await page.setInputFiles('#import-file',{name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":999}')});await page.waitForFunction(()=>document.querySelector('#status').textContent.length>0);ok(await page.inputValue('[name=market]'),'fr');ok(errors.length,0);ok(events.length,0);
await page.goto(base+'/en/energy-tariff-workbench.html');await page.check('[name=purpose][value=own]');await run();await page.click('button[type=submit]');await page.waitForTimeout(100);ok(events.filter(e=>e.n==='solution_calc').length,1);ok(events.filter(e=>e.n==='page_view').length,1);ok(events.every(e=>Object.keys(e.m).sort().join(',')==='input,lang,market'),true);ok(events.find(e=>e.n==='solution_calc').m.input,'own');
const blocked=await browser.newContext();await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('blocked')}}));const p=await blocked.newPage();await p.goto(base+'/stromtarif-werkstatt.html?__probe=1');await p.check('[name=confirm]');await p.click('button[type=submit]');await p.waitForSelector('#results:not([hidden])');await p.click('#save');ok((await p.textContent('#storage-status')).length>0,true);
await browser.close();console.log(`PASS: ${checks} browser assertions, five languages, mobile layout, import/export/share and anonymous events.`);
})().catch(e=>{console.error(e);process.exit(1);});
