const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../site'),origin='https://getecoback.com',live=process.env.LIVE==='1';
const routes=['/rechner.html','/en/solution-calculator.html','/nl/wonen.html','/fr/calculateur.html','/guide/midea-portasplit-kaufen.html','/guide/waesche-trocknen-wohnung.html','/en/guide/dehumidifier-drying-clothes-cost.html'];
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});let checks=0;try{for(const url of routes){const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.__events=[];window.addEventListener('fleet:business',e=>window.__events.push(e.detail));});if(!live)await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!==origin)return route.abort();if(u.pathname.startsWith('/api/'))return route.fulfill({contentType:'application/json',body:'{}'});const file=path.join(root,u.pathname);if(!fs.existsSync(file))return route.fulfill({status:404,body:'missing'});return route.fulfill({body:fs.readFileSync(file),contentType:({'.html':'text/html','.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream'});});
await page.goto(origin+url+'?__probe=1#home-fit');await page.waitForSelector('#home-fit[data-ready]');const box=page.locator('#home-fit');assert.equal(await box.count(),1);assert.equal((await page.evaluate(()=>window.__events)).length,0);checks+=2;
for(const width of [320,390,1280]){await page.setViewportSize({width,height:900});assert(await box.evaluate(e=>e.scrollWidth<=e.clientWidth+1),url+' overflow');checks++;}
for(const mode of ['robot','laundry','ac','floor']){await box.locator('[data-mode='+mode+']').click();assert(!(await box.innerText()).match(/undefined|NaN|Infinity/));await box.locator('button[type=submit]').click();assert((await page.locator('#hf-result').innerText()).length>200);checks+=2;}
await box.locator('details').first().evaluate(e=>e.open=true);await page.fill('#hf-cleanup','30');assert(await box.locator('.hf-actions button').first().isDisabled());await box.locator('button[type=submit]').click();assert((await page.locator('#hf-result').innerText()).includes('-52'));checks+=2;
await box.locator('.hf-actions button').first().click();const link=await box.locator('textarea').inputValue(),before=await page.locator('#hf-result').innerText();assert.equal(new URL(link).search,'');for(const platform of ['Reddit','X']){const a=box.getByRole('link',{name:platform,exact:true});assert.equal(new URL(await a.getAttribute('href')).searchParams.get('url'),link);}checks+=3;
await page.goto(link.replace('.html#','.html?__probe=1#'));await page.waitForSelector('#home-fit[data-ready]');assert.equal(await page.locator('#hf-result').innerText(),before);assert.equal((await page.evaluate(()=>window.__events)).length,0);checks+=2;
await box.locator('details').first().evaluate(e=>e.open=true);await page.fill('#hf-manual','');await box.locator('button[type=submit]').click();assert.equal(await page.locator('#hf-result').innerText(),'');checks++;
await page.goto(origin+url+'?__probe=1#eco-fit-v1=%XX');await page.waitForSelector('#home-fit[data-ready]');assert((await box.locator('[role=status]').innerText()).length>20);assert.deepEqual(errors,[]);checks+=2;
if(url==='/nl/wonen.html'){await page.setViewportSize({width:390,height:844});await box.screenshot({path:process.env.SCREENSHOT||'/tmp/eco-home-fit-nl.png'});}await context.close();}
console.log(JSON.stringify({status:'PASS',pages:routes.length,checks,live}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
