const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'../site'),origin='https://getecoback.com',dir=process.env.QA_DIR||'/tmp/eco-tool-social';fs.mkdirSync(dir,{recursive:true});
(async()=>{const urls=Object.keys(JSON.parse(execFileSync('python3',['-c','import json;from build_tools_hub import discover;print(json.dumps(discover()))'],{cwd:__dirname,encoding:'utf8'})));for(const prefix of ['', '/en', '/it'])for(const slug of ['billlens','appliancepayback','homeenergy-log']){const u=prefix+'/workbench/'+slug+'.html';if(fs.existsSync(path.join(root,u)))urls.push(u);}const b=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}: {})});let checks=0,quick=0;const records=[];
try{for(const url of urls){const ctx=await b.newContext({viewport:{width:390,height:844},acceptDownloads:true});await ctx.addInitScript(()=>{window.__business=[];window.__legacy=[];window.addEventListener('fleet:business',e=>window.__business.push(e.detail));window.dataLayer=[];window.dataLayer.push=(...args)=>{window.__legacy.push(...args.map(a=>Array.from(a)));return Array.prototype.push.apply(window.dataLayer,args)};});await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!==origin)return r.abort();if(u.pathname.startsWith('/api/'))return r.fulfill({contentType:'application/json',body:'{}'});const f=path.join(root,u.pathname);return fs.existsSync(f)?r.fulfill({body:fs.readFileSync(f),contentType:({'.html':'text/html','.css':'text/css','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.svg':'image/svg+xml'})[path.extname(f)]||'application/octet-stream'}):r.fulfill({status:404,body:'missing'});});const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+url+'?__probe=1');const panel=p.locator('#eco-tool-experience');await panel.locator('[type=button]').first().waitFor();await p.waitForSelector('#eco-tool-experience[data-ready]');checks++;
for(const width of [320,390,1280]){await p.setViewportSize({width,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),url+' overflow '+width);checks++;}
if(await panel.getAttribute('data-quick')){quick++;const preview=panel.locator('.eco-preview');assert(await preview.isVisible(),url+' no initial result');assert(!(await preview.innerText()).includes('NaN'));assert.equal((await p.evaluate(()=>window.__legacy.filter(a=>a[0]==='event'&&/calc|check|fit/.test(a[1])))).length,0,url+' example emitted completion');assert.equal((await p.evaluate(()=>window.__business.filter(e=>e.name==='legacy:tool_complete'||e.name==='legacy:tool_start'))).length,0,url+' example counted');checks+=4;
const choices=panel.locator(':scope > .eco-actions').first().locator('button');if(await choices.count()>1)await choices.nth(1).click();const prepare=panel.locator(':scope > .eco-actions').last().locator('button').first();await prepare.click();const draft=panel.locator('textarea');assert((await draft.inputValue()).includes('https://getecoback.com'));const link=await panel.locator('.eco-fallback').getAttribute('href'),u=new URL(link);assert(u.hash.startsWith('#eco-v1='));assert.deepEqual([...u.searchParams.keys()].sort(),['utm_campaign','utm_medium','utm_source']);const data=JSON.parse(decodeURIComponent(u.hash.slice(8)));assert.equal(data.path,url);checks+=4;
for(const platform of ['Reddit','X']){const external=new URL(await panel.locator('.eco-links a').filter({hasText:new RegExp('^'+platform+'$')}).getAttribute('href'));const shared=new URL(external.searchParams.get('url'));assert.equal(shared.pathname,url);assert.equal(shared.hash,u.hash);checks+=2;}
const result=await preview.locator('p').innerText();await p.goto(link+'&ignored'); // Malformed fragments must fail closed, never break the page.
await p.waitForSelector('#eco-tool-experience[data-ready]');assert.deepEqual(errors,[]);checks++;
await p.goto(link);await p.waitForSelector('#eco-tool-experience[data-ready]');assert.equal(await panel.locator('.eco-preview p').innerText(),result,url+' scenario not reproducible');checks++;
const first=await p.evaluate(values=>{for(const key of Object.keys(values)){const es=[...document.querySelectorAll('input[type=number]')].filter(e=>e.name===key||e.id===key);const e=es.find(e=>e.getClientRects().length);if(e)return {id:e.id,name:e.name};}},data.values);assert(first,url+' no editable numeric input');const field=first.id?p.locator('#'+first.id):p.locator('input[name="'+first.name+'"]');await field.fill('');assert(await panel.locator(':scope > .eco-actions').last().locator('button').first().isDisabled());assert(!await panel.locator('.eco-preview').isVisible());checks+=2;
if(records.length<3){await panel.locator(':scope > .eco-actions').first().locator('button').first().click();await panel.locator(':scope > .eco-actions').last().locator('button').first().click();const download=p.waitForEvent('download');await panel.locator('.eco-links button').last().click();assert((await download).suggestedFilename().endsWith('.png'));checks++;await p.setViewportSize({width:390,height:844});await panel.screenshot({path:path.join(dir,'tool-'+records.length+'.png')});}
}
await panel.locator(':scope > .eco-actions').last().locator('button').last().click();const generic=new URL(await panel.locator('.eco-fallback').getAttribute('href'));assert.equal(generic.hash,'');assert(!generic.searchParams.has('mode'));assert.deepEqual(errors,[]);checks+=3;if(url==='/stromtarif-werkstatt.html'){await panel.locator(':scope > .eco-actions').first().locator('button').first().click();await p.click('#reset');await p.waitForFunction(()=>document.querySelector('#eco-tool-experience > .eco-actions:last-of-type button').disabled);assert(await panel.locator(':scope > .eco-actions').last().locator('button').first().isDisabled());await panel.locator(':scope > .eco-actions').first().locator('button').first().click();await p.check('[name=purpose][value=own]');assert(await panel.locator(':scope > .eco-actions').last().locator('button').first().isDisabled());checks+=2;}
records.push({url,quick:await panel.getAttribute('data-quick')==='true'});await ctx.close();}
fs.writeFileSync(path.join(dir,'tool-experience.json'),JSON.stringify({pages:urls.length,quickPages:quick,checks,records},null,2));console.log(`PASS tool experience: ${urls.length} pages, ${quick} instant-example pages, ${checks} assertions; reproducible social links, no automatic completion, stale-result protection and responsive layouts.`);}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
