// Task-level regression: every public tool loads on narrow screens; legacy decisions reject missing data.
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'../site'),origin='https://getecoback.com';
(async()=>{const {config}=await import('../site/assets/legacy-tool-guard.mjs');const inventory=JSON.parse(execFileSync('python3',['-c','import json;from build_tools_hub import discover;print(json.dumps(discover()))'],{cwd:__dirname,encoding:'utf8'}));const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}: {})});let checks=0,records=[];const dir=process.env.QA_DIR||'/tmp/eco-tool-audit';fs.mkdirSync(dir,{recursive:true});
try{for(const url of Object.keys(inventory)){
 const ctx=await browser.newContext({viewport:{width:390,height:844}}),errors=[];
 await ctx.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin!==origin)return route.abort();if(u.pathname.startsWith('/api/'))return route.fulfill({contentType:'application/json',body:'{"ok":false}'});const file=path.join(root,u.pathname);return fs.existsSync(file)?route.fulfill({contentType:({'.html':'text/html','.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream',body:fs.readFileSync(file)}):route.fulfill({status:404,body:'missing'});});
 const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+url+'?__probe=1');await page.waitForLoadState('load');
 for(const width of [320,390,1280]){await page.setViewportSize({width,height:844});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(overflow){const evidence=await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).map(e=>({tag:e.tagName,id:e.id,class:e.className,text:e.textContent.slice(0,150),right:e.getBoundingClientRect().right})).slice(-30));fs.writeFileSync(path.join(dir,'overflow.json'),JSON.stringify({url,width,evidence},null,2));await page.screenshot({path:path.join(dir,'overflow.png'),fullPage:true});}assert(!overflow,url+' overflow at '+width);checks++;}
 const c=config[url];if(c){await page.locator('#'+c.button+'[data-validation-ready=true]').waitFor();await page.evaluate(()=>{window.__auditEvents=[];window.gtag=(...a)=>window.__auditEvents.push(a)});const go=page.locator('#'+c.button),result=page.locator('#'+c.result);await go.click();assert(await result.isVisible(),url+' result');assert((await result.innerText()).trim().length>0,url+' empty result');assert(!/NaN|Infinity/.test(await result.innerText()),url);checks+=3;
  let input;for(const id of Object.keys(c.inputs)){if(await page.locator('#'+id).isVisible()){input=id;break}}
  const field=page.locator('#'+input),original=await field.inputValue();await field.fill('');assert(!await result.isVisible(),url+' stale result');const count=await page.evaluate(()=>window.__auditEvents.length);await go.click();assert(!await result.isVisible(),url+' missing input');assert((await page.locator('#legacy-tool-error').innerText()).length>0,url);assert.equal(await page.evaluate(()=>window.__auditEvents.length),count,url+' invalid action counted');checks+=4;
  await field.fill(String(c.inputs[input][1]+1));await go.click();assert(!await result.isVisible(),url+' out of range');await field.fill(original);await field.press('Enter');assert(await result.isVisible(),url+' keyboard');checks+=2;
  const inputKeys=['qm','btu','watt','hours','td','srh','w','h','d','diff_kwh','period_cost'];for(const event of await page.evaluate(()=>window.__auditEvents)){if(event[0]==='event')for(const key of inputKeys)assert(!Object.hasOwn(event[2]||{},key),url+' leaks '+key)}checks++;
 }
 assert.deepEqual(errors,[],url);checks++;records.push({url,layoutWidths:[320,390,1280],runtime:'pass',taskInputs:c?'valid, blank, out-of-range, stale-result and keyboard passed':'covered by family suite / inventory load only'});await ctx.close();
}
// Decision failures that a successful button click alone would miss.
const ctx=await browser.newContext();await ctx.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin!==origin)return route.abort();if(u.pathname.startsWith('/api/'))return route.fulfill({contentType:'application/json',body:'{"ok":false}'});let f=path.join(root,u.pathname);return fs.existsSync(f)?route.fulfill({contentType:f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':'text/javascript',body:fs.readFileSync(f)}):route.fulfill({status:404});});let page=await ctx.newPage();
await page.goto(origin+'/guide/stromkosten-rechner.html?__probe=1');await page.locator('[data-validation-ready]').waitFor();await page.fill('#price','0');await page.click('#calcBtn');assert((await page.locator('#result').innerText()).includes('0,00 €'));assert.equal(await page.locator('#result a[href*="amazon."]').count(),0);checks+=2;
await page.goto(origin+'/guide/keller-lueften-sommer.html?__probe=1');await page.locator('[data-validation-ready]').waitFor();for(const [id,v]of Object.entries({ta:20,rh:30,tk:17,rhin:20,wall:15}))await page.fill('#'+id,String(v));await page.click('#go');assert((await page.locator('#verdict').innerText()).includes('Keine Trocknung'));await page.fill('#rhin','70');await page.click('#go');assert((await page.locator('#verdict').innerText()).includes('kann Feuchte abführen'));await page.fill('#wall','-5');await page.click('#go');assert((await page.locator('#verdict').innerText()).includes('Kondensationsrisiko'));checks+=3;
await page.goto(origin+'/guide/infrarotheizung-gegen-schimmel.html?__probe=1');await page.locator('[data-validation-ready]').waitFor();await page.fill('#rh','65');await page.fill('#tw','24');await page.click('#go');const t=await page.locator('#out').innerText();assert(t.includes('51 %'),t);assert(!t.includes('kann nicht wärmer'));checks+=2;
await page.goto(origin+'/en/guide/desiccant-vs-compressor-dehumidifier.html?__probe=1');await page.locator('[data-validation-ready]').waitFor();await page.fill('#ta','10');await page.fill('#rh','60');await page.click('#go');assert((await page.locator('#out').innerText()).includes('not necessarily below freezing'));checks++;
await ctx.close();fs.writeFileSync(path.join(dir,'tools-audit.json'),JSON.stringify({checks,pages:records.length,legacyTools:Object.keys(config).length,records},null,2));console.log(`PASS tool audit: ${records.length} public pages, ${Object.keys(config).length} legacy input flows, ${checks} checks including decision counterexamples.`);
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
