const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../site'),origin='https://getecoback.com',live=process.env.LIVE==='1';
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}: {})});let checks=0;
try{for(const url of ['/rechner.html','/en/solution-calculator.html','/fr/calculateur.html','/nl/wonen.html','/wohnen.html','/geraete-austausch-rechner.html','/guide/duschen-kosten-rechner.html','/en/guide/shower-cost-calculator.html']){
 const c=await browser.newContext({viewport:{width:390,height:844}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{window.__events=[];window.addEventListener('fleet:business',e=>window.__events.push(e.detail));});
 if(!live)await c.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!==origin)return r.abort();if(u.pathname.startsWith('/api/'))return r.fulfill({contentType:'application/json',body:'{}'});const f=path.join(root,u.pathname);return fs.existsSync(f)?r.fulfill({body:fs.readFileSync(f),contentType:({'.html':'text/html','.css':'text/css','.js':'text/javascript','.mjs':'text/javascript','.json':'application/json','.svg':'image/svg+xml'})[path.extname(f)]||'application/octet-stream'}):r.fulfill({status:404,body:'missing'});});
 await p.goto(origin+url+'?__probe=1#product-decisions');await p.waitForSelector('#product-decisions[data-ready]');const box=p.locator('#product-decisions');assert.equal(await box.count(),1);assert(!(await p.locator('#pd-result').innerText()).match(/NaN|Infinity|undefined/));checks+=2;assert.equal(await box.locator('form > details').getAttribute('open'),null);checks++;if(url==='/nl/wonen.html')await box.screenshot({path:process.env.SCREENSHOT||'/tmp/eco-product-decisions-nl.png'});
 for(const width of [320,390,1280]){await p.setViewportSize({width,height:844});assert(await p.evaluate(()=>{const r=document.getElementById('product-decisions').getBoundingClientRect();return r.width<=innerWidth&&document.getElementById('product-decisions').scrollWidth<=r.width+1;}),url+' module overflow '+width);checks++;}
 for(const market of ['DE','AT','CH','NL','GB','FR','US','CA']){await p.selectOption('#pd-market',market);assert((await box.locator('.pd-local').innerText()).length>60);const shop=box.locator('.pd-commerce a');if(['AT','CH'].includes(market))assert.equal(await shop.count(),0);else{const u=new URL(await shop.getAttribute('href'));assert.equal(u.searchParams.get('tag'),market==='DE'?'getecoback-21':market==='US'?'ecoback0d-20':null);}checks+=2;}
 await p.selectOption('#pd-mode','dish');await box.locator('form > details').evaluate(e=>e.open=true);await p.fill('#pd-handWater','5');await box.locator('button[type=submit]').click();assert.equal(await box.locator('.pd-commerce').count(),0);checks++;
 await p.selectOption('#pd-mode','shower');assert.equal(await box.locator('.pd-commerce').count(),0);await p.selectOption('#pd-compatible','yes');assert.equal(await box.locator('.pd-commerce').count(),1);checks+=2;
 const before=await p.locator('#pd-result > p').nth(1).innerText();await p.selectOption('#pd-flowUnit','usgal');assert.equal(await p.locator('#pd-result > p').nth(1).innerText(),before);checks++;
 await box.locator(':scope > div[data-pd-mount] > .pd-actions button').first().click();const link=await box.locator('textarea').inputValue();assert.equal(new URL(link).search,'');assert(link.includes('#eco-buy-v1='));const snap=await p.locator('#pd-result').innerText();const social=await box.locator('a').filter({hasText:/^(Reddit|X)$/}).all();assert.equal(social.length,2);for(const a of social)assert.equal(new URL(await a.getAttribute('href')).searchParams.get('url'),link);checks+=4;
 await p.goto(link.replace('.html#','.html?__probe=1#'));await p.waitForSelector('#product-decisions[data-ready]');assert.equal(await p.locator('#pd-result').innerText(),snap);assert.equal((await p.evaluate(()=>window.__events)).length,0);checks+=2;
 await box.locator('form > details').evaluate(e=>e.open=true);await p.fill('#pd-flowA','');await box.locator('button[type=submit]').click();assert.equal((await p.locator('#pd-result').innerText()).trim(),'');assert(await box.locator(':scope > div[data-pd-mount] > .pd-actions button').first().isDisabled());checks+=2;
 await p.goto(origin+url+'?__probe=1#eco-buy-v1=%XX');await p.waitForSelector('#product-decisions[data-ready]');assert((await box.locator('[role=status]').innerText()).length>5);assert.deepEqual(errors,[]);checks+=2;
 await c.close();}
 console.log(JSON.stringify({status:'PASS',checks,pages:8,live}));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
