const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}: {})});let checks=0;const base=process.env.TEST_BASE_URL||'http://127.0.0.1:8765';const ctx=await browser.newContext({acceptDownloads:true}),errors=[];await ctx.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!==base)return r.abort();if(u.pathname.startsWith('/api/'))return r.fulfill({status:200,contentType:'application/json',body:'{"ok":false}'});return r.continue()});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));const visit=u=>p.goto(base+u+'?__probe=1');
try{
 for(const u of ['/rechner.html','/en/solution-calculator.html','/fr/calculateur.html','/es/calculadora.html','/it/calcolatore.html']){
  await visit(u);await p.check('#comparable');await p.locator('#country-form button[type=submit]').click();assert(await p.locator('#result table').count());assert(new URL(p.url()).searchParams.has('__probe'));checks+=2;
  await p.fill('#rate','');assert.equal(await p.locator('#result table').count(),0);const downloads=[];const cb=d=>downloads.push(d);p.on('download',cb);await p.click('#download-card');await p.waitForTimeout(50);assert.equal(downloads.length,0);assert((await p.locator('#form-error').innerText()).length>0);p.off('download',cb);checks+=3;
  await p.fill('#rate','0.3');await p.fill('#costB','0');await p.locator('#country-form button[type=submit]').click();assert(!/NaN|undefined/.test(await p.locator('#result').innerText()));const promise=p.waitForEvent('download');await p.click('#download-card');assert((await promise).suggestedFilename().endsWith('.png'));checks+=2;
 }
 for(const u of ['/strommess-protokoll.html','/geraete-austausch-rechner.html']){
  await visit(u);await p.locator('[data-household] button').click();const before=await p.locator('#result').innerText();assert(before.length>40);await p.locator('[data-household] input').first().fill('');assert((await p.locator('#result').innerText()).includes('neu berechnen'));checks+=2;
 }
 for(const lang of ['en','zh'])for(const slug of ['cbam-supplier-data','eudr-geolocation-evidence']){
  await visit('/'+lang+'/agents/'+slug+'.html');await p.locator('#evidence-check button[type=submit]').click();assert(await p.locator('#result').isVisible());const promise=p.waitForEvent('download');await p.click('#download');assert((await promise).suggestedFilename().length>0);const select=p.locator('#evidence-check select').last();await select.selectOption({index:1});assert(!await p.locator('#download').isVisible());checks+=3;
 }
 for(const prefix of ['','/en']){
  await visit(prefix+'/agents/compliance.html');await p.fill('#product','Sample M8 fastener');await p.locator('#diagForm button[type=submit]').click();assert(await p.locator('#result').isVisible());const promise=p.waitForEvent('download');await p.click('#download');const d=await promise;const content=fs.readFileSync(await d.path(),'utf8');assert(content.includes('\n\n'));assert(!content.includes('\\n'));await p.fill('#product','Changed product');assert(!await p.locator('#result').isVisible());assert(await p.locator('#download').isDisabled());checks+=5;
 }
 await visit('/pro-werkzeuge.html');await p.click('#energyRun');assert((await p.locator('#energyOut').innerText()).length>30);await p.locator('[data-tab=tender]').click();assert(await p.locator('#exportResult').isDisabled());await p.fill('#tKey','Insulation');await p.click('#tenderRun');assert(!await p.locator('#exportResult').isDisabled());await p.fill('#tKey','Ventilation');assert(await p.locator('#exportResult').isDisabled());await p.locator('[data-tab=energy]').click();assert(!await p.locator('#exportResult').isDisabled());await p.fill('#eBill','400');assert(await p.locator('#exportResult').isDisabled());await p.locator('[data-tab=compliance]').click();await p.click('#complianceRun');assert(!await p.locator('#exportResult').isDisabled());checks+=7;
 await visit('/guide/infrarotheizung-watt-rechner.html');await p.fill('#ir-qm','101');assert((await p.locator('#ir-ergebnis').innerText()).includes('zwischen 1 und 100'));await p.fill('#ir-qm','20');assert((await p.locator('#ir-ergebnis').innerText()).includes('Watt-Bedarf'));checks+=2;
 for(const u of ['/guide/hitze-check.html','/en/guide/heat-check.html']){await visit(u);const groups=p.locator('#hc .opts');for(let i=0;i<await groups.count();i++)await groups.nth(i).locator('button').first().click();assert((await p.locator('#hc-result').innerText()).length>60);checks++;}
 await visit('/guide/strompreis-radar.html');await p.waitForFunction(()=>getComputedStyle(document.querySelector('#r-fb')).display!=='none');assert((await p.locator('#r-fb').innerText()).length>20);checks++;
 // Standalone workbench tools: all three tasks in all three published languages.
 for(const prefix of ['','/en','/it'])for(const slug of ['billlens','appliancepayback','homeenergy-log']){
  await visit(prefix+'/workbench/'+slug+'.html');await p.locator('#input-form button').first().waitFor();await p.locator('#input-form button[type=submit]').click();await p.waitForSelector('#output table, #status.error');assert.equal(await p.locator('#status.error').count(),0,slug);assert(await p.locator('#output table').count());checks+=2;
 }
 assert.deepEqual(errors,[]);checks++;console.log(`PASS task flows: ${checks} assertions; five country calculators, household tools, evidence exports, three professional tabs and nine localized workbench tools.`);
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
