#!/usr/bin/env python3
"""Original household decision tools, not product tests or market-price feeds.
Run explicitly to edit these pages. Deployment only attaches existing chrome.
"""
from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parents[1]; SITE=ROOT/'site'; BASE='https://getecoback.com/'
PAGES={
'wohnkosten-werkstatt':('Haushaltskosten prüfen: messen, trocknen, vergleichen','Drei kostenlose Rechner für Haushaltsstrom: Wäsche trocknen, Verbrauch messen und Gerätewechsel prüfen. Mit Rechenbeispielen und Messprotokoll.'),
'waeschetrockner-oder-luftentfeuchter':('Trockner oder Entfeuchter? Stromkosten vergleichen','Vergleiche Trockner und Luftentfeuchter mit eigenen Verbrauchswerten: Kosten pro Ladung und Jahr, Grenzen des Vergleichs und Anleitung zum Messen.'),
'strommess-protokoll':('Stromverbrauch messen: Protokoll und Jahreskosten','Gemessene Kilowattstunden statt Typenschild-Watt: Verbrauch auf Betriebstage hochrechnen, Messprotokoll herunterladen und Stromfresser prüfen.'),
'geraete-austausch-rechner':('Altes Gerät behalten oder ersetzen? Kostenrechner','Berechne, wann geringere Stromkosten einen Gerätekauf ausgleichen. Mit Kaufpreis, eigenem Tarif, Jahresverbrauch und offenem Rechenweg.')}
LINKS=''.join(f'<a href="/{s}.html"><strong>{t}</strong><span>{d}</span></a>' for s,(t,d) in list(PAGES.items())[1:])
SOURCE_DRY='https://www.verbraucherzentrale.de/wissen/energie/strom-sparen/beim-kauf-eines-waeschetrockners-an-den-stromverbrauch-denken-37984'
SOURCE_AIR='https://www.verbraucherzentrale.de/wissen/energie/strom-sparen/heizen-und-lueften-so-gehts-richtig-10426'
def field(name,label,value,lo,hi,step='any'):
 return f'<label>{label}<input name="{name}" type="number" value="{value}" min="{lo}" max="{hi}" step="{step}" required inputmode="decimal"></label>'
def form(kind,fields,example):
 return f'''<section class="work-panel" aria-labelledby="calculator"><h2 id="calculator">Mit deinen Werten rechnen</h2><p class="work-note">Die vorbelegten Zahlen sind frei gewählte Rechenbeispiele, keine Produktmessungen oder aktuellen Stromtarife. Ersetze sie durch deine Werte.</p><form data-household="{kind}"><div class="work-fields">{''.join(field(*f) for f in fields)}</div><button type="submit">Kosten berechnen</button></form><p id="result" role="status" tabindex="-1">{example}</p><p class="work-note">Eingaben werden lokal im Browser verarbeitet und nicht gespeichert oder als Messwerte übertragen. Ein Rechenaufruf wird ohne Eingabewerte gezählt.</p><noscript><p>Für eigene Berechnungen ist JavaScript nötig. Der Rechenweg und das Beispiel darunter funktionieren auch ohne JavaScript.</p></noscript></section>'''
def ad(terms):
 links=''.join(f'<a href="https://www.amazon.de/s?k={term}&amp;tag=getecoback-21" target="_blank" rel="sponsored noopener">{label} bei Amazon.de suchen</a>' for term,label in terms)
 return f'<!--EB_HOUSEHOLD_AD--><aside class="work-ad"><p><strong>Anzeige · Affiliate-Links</strong></p><p>Als Amazon-Partner verdienen wir an qualifizierten Verkäufen. Für dich bleibt der Preis gleich. Suchergebnisse können variieren; wir haben die Geräte nicht selbst getestet. Prüfe das konkrete Modell und die Herstelleranleitung.</p>{links}</aside><!--/EB_HOUSEHOLD_AD-->'
def page(slug,lead,body,scheme):
 title,desc=PAGES[slug];url=BASE+slug+'.html'
 ld={'@context':'https://schema.org','@type':'WebPage','name':title,'description':desc,'url':url,'inLanguage':'de','datePublished':'2026-09-19','dateModified':'2026-09-19','publisher':{'@type':'Organization','name':'EcoBack','url':BASE}}
 return f'''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | EcoBack</title><meta name="description" content="{escape(desc)}"><link rel="canonical" href="{url}"><meta property="og:type" content="website"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(desc)}"><meta property="og:url" content="{url}"><link rel="stylesheet" href="/assets/household.css"><script type="application/ld+json">{json.dumps(ld,ensure_ascii=False)}</script><script type="module" src="/assets/household.mjs"></script></head><body class="eb-work"><main class="work-wrap" id="main"><a href="/tools.html">Alle EcoBack-Rechner</a><header class="work-intro"><div><p class="work-kicker">Die EcoBack Haushaltswerkstatt</p><h1>{title}</h1><p>{lead}</p><p class="work-note">EcoBack Redaktion · 19. September 2026</p></div><aside class="work-scheme">{scheme}</aside></header>{body}<h2>Dein nächster Schritt</h2><nav class="work-links" aria-label="Haushaltsrechner">{LINKS}</nav><p><a href="/wohnkosten-werkstatt.html">Zur Haushaltswerkstatt</a> · <a href="/wie-wir-empfehlen.html">Wie wir empfehlen</a></p></main></body></html>'''
def main():
 body='''<h2>Eine Messung ist besser als ein Werbeversprechen.</h2><p>Ein kleineres Gerät ist nicht automatisch billiger im Betrieb: Entscheidend sind Verbrauch und Laufzeit für dieselbe Aufgabe. Hier trennst du die Messung, den Kostenvergleich und die Kaufentscheidung.</p><nav class="work-links" aria-label="Aufgabe wählen">'''+LINKS+'''</nav><h2>In drei Schritten zur Entscheidung</h2><ol class="work-steps"><li><strong>Gleiches mit Gleichem vergleichen.</strong> Beim Trocknen dieselbe Wäschemenge und Restfeuchte, beim Kühlschrank vergleichbare Größe und Umgebung.</li><li><strong>Eine vollständige Nutzung messen.</strong> Einschaltleistung in Watt ist kein Jahresverbrauch. Notiere Energie in kWh und Dauer.</li><li><strong>Erst rechnen, dann auswählen.</strong> Wenn der Stromvorteil den Kaufpreis nicht ausgleicht, ist Weiterverwenden oft die günstigere Kostenannahme.</li></ol><h2>Feuchtigkeit zuerst verstehen</h2><p>Wer drinnen Wäsche trocknet, verändert auch das Raumklima. Ein Stromkostenvergleich diagnostiziert keine Feuchteursache und berechnet keine Gebäudeschäden. Nutze dafür unsere vorhandenen Ratgeber:</p><ul><li><a href="/guide/waesche-trocknen-wohnung.html">Wäsche in der Wohnung trocknen</a></li><li><a href="/guide/luftfeuchtigkeit-senken.html">Luftfeuchtigkeit senken und Lüften einordnen</a></li><li><a href="/guide/luftentfeuchter-keller.html">Was bei einem feuchten Keller anders ist</a></li></ul><h2>Dein Messblatt</h2><p><a href="/downloads/haushalt-messprotokoll.csv" download>Leeres Messprotokoll als CSV herunterladen</a>. Keine Anmeldung. Fülle es in deiner Tabellenkalkulation aus oder drucke die Rechnerseite. Namen, Adressen und Zählernummern sind nicht nötig.</p><h2>Was diese Werkstatt nicht behauptet</h2><p>Wir haben keine eigenen Produkttests durchgeführt. Die Beispielzahlen sind keine Rangliste. Ergebnisse hängen von deinen Eingaben ab; Energiebedarf, Laufzeit und Tarife können sich ändern. Ein Rechnerergebnis ist keine Zusage einer Ersparnis.</p>'''
 (SITE/'wohnkosten-werkstatt.html').write_text(page('wohnkosten-werkstatt','Messen, vergleichen, erst dann kaufen. Finde heraus, welche Haushaltsentscheidung sich mit deinen eigenen Zahlen trägt.',body,'<p><strong>Messen</strong>kWh statt nur Watt</p><p><strong>Vergleichen</strong>Dieselbe Aufgabe, derselbe Tarif</p><p><strong>Entscheiden</strong>Kaufpreis und Nutzungsdauer mitdenken</p>'))
 body=form('drying',[('dryer','Trockner: kWh je Ladung',1.5,0,20),('watts','Entfeuchter: mittlere Leistung in Watt',250,0,5000),('hours','Entfeuchter: Stunden je Trocknung',6,0,72),('loads','Ladungen pro Woche',3,0,30),('price','Dein Strompreis in €/kWh',.35,0,5)],'Beispiel: 1,5 kWh im Trockner und 250 W × 6 h = 1,5 kWh im Entfeuchter kosten beide 0,525 € je Durchgang. Bei drei Ladungen pro Woche: je 81,90 € im Jahr.')+f'''<h2>So wird der Vergleich fair</h2><ol class="work-steps"><li>Nimm für beide Varianten gleich viel Wäsche aus demselben Schleuderprogramm. Vergleiche den gleichen gewünschten Trocknungsgrad.</li><li>Lies beim Trockner die kWh je Ladung ab. Bei einem Label mit kWh je 100 Zyklen teilst du durch 100. Ein tatsächlicher Messwert passt besser zu deinem Programm als ein abweichender Prüfzyklus.</li><li>Miss beim Entfeuchter die gesamte Energie bis zum gleichen Trocknungsgrad. Für den Rechner ist die mittlere Leistung = gemessene kWh × 1.000 ÷ Stunden. Typenschild-Watt allein kann den Vergleich verzerren.</li></ol><h2>Der Rechenweg</h2><p>Entfeuchter: Watt × Stunden ÷ 1.000. Kosten je Ladung: kWh × €/kWh. Jahreskosten: Kosten je Ladung × Ladungen je Woche × 52. Reine Wäscheleine ohne elektrisches Gerät hat keine direkten Gerätestromkosten; zusätzliche Heiz- und Lüftungsenergie ist damit nicht erfasst.</p><h2>Was das Ergebnis nicht abdeckt</h2><p>Ein Entfeuchter kann auch Feuchte aus dem Raum aufnehmen. Wie viel davon aus der Wäsche stammt, weiß der Rechner nicht. Unterschiedliche Restfeuchte, Raumerwärmung, Anschaffung, Platzbedarf und deine Zeit fehlen im Kostenwert. Deshalb gibt es hier keinen pauschalen Sieger.</p><h2>Nach dem Rechnen</h2><p>Wenn du bereits einen Trockner besitzt, ist dessen Kaufpreis für diese einzelne Nutzung nicht erneut fällig. Wenn du erst kaufen müsstest, nutze zusätzlich den <a href="/geraete-austausch-rechner.html">Kaufpreisvergleich</a>. Für die Praxis: <a href="/guide/waesche-trocknen-wohnung.html">Wäsche in der Wohnung</a> und <a href="/guide/luftentfeuchter-ratgeber.html">Entfeuchter-Auswahlkriterien</a>.</p><h2>Quellen und Grenzen</h2><p>Die <a href="{SOURCE_DRY}">Verbraucherzentrale erklärt das Trockner-Energielabel</a>, einschließlich kWh je 100 Trocknungen. Unsere Szenariorechnung ist keine Prüfung eines bestimmten Geräts. <a href="{SOURCE_AIR}">Hinweise zu Heizen und Lüften</a> helfen, Raumfeuchte getrennt von den Stromkosten zu betrachten.</p>'''+ad([('Luftentfeuchter+Hygrostat','Entfeuchter mit Hygrostat'),('Waermepumpentrockner','Wärmepumpentrockner')])
 (SITE/'waeschetrockner-oder-luftentfeuchter.html').write_text(page('waeschetrockner-oder-luftentfeuchter','Nicht Watt allein entscheidet. Vergleiche den Strom für eine gleich trockene Wäscheladung und sieh, was deine Nutzung im Jahr kostet.',body,'<p><strong>Gleiche Wäsche</strong>Menge und Restfeuchte angleichen</p><p><strong>Ganzer Durchgang</strong>kWh und Laufzeit messen</p><p><strong>Offener Vergleich</strong>Kein pauschaler Testsieger</p>'))
 body=form('measured',[('kwh','Gemessene Energie in kWh',1.2,0,10000),('hours','Messdauer in Stunden',48,.01,8760),('days','Betriebstage pro Jahr',365,0,366),('price','Dein Strompreis in €/kWh',.35,0,5)],'Beispiel: 1,2 kWh in 48 Stunden = 0,6 kWh pro Tag. Bei 365 vergleichbaren Betriebstagen: 219 kWh und 76,65 € im Jahr.')+'''<h2>Ein Messplan für drei verschiedene Geräte</h2><div class="work-table"><table><thead><tr><th>Gerät</th><th>Was du misst</th><th>Warum die Momentaufnahme täuscht</th></tr></thead><tbody><tr><td>Kühlschrank</td><td>Mehrere vollständige Tage im üblichen Alltag</td><td>Der Kompressor läuft nicht durchgehend; Türöffnungen und Raumtemperatur verändern den Verbrauch.</td></tr><tr><td>Entfeuchter</td><td>Einen typischen Betriebstag bei notierter Feuchte und Zielvorgabe</td><td>Hygrostat und wechselnde Feuchtelast verändern die Laufzeit.</td></tr><tr><td>Trockner</td><td>Einen vollständigen Durchgang einschließlich Abkühlphase</td><td>Einzelne Lastspitzen sagen wenig über die Energie je Wäscheladung.</td></tr></tbody></table></div><h2>So füllst du das Protokoll aus</h2><ol class="work-steps"><li>Notiere Gerät, Datum und normalen Einsatz. Keine Seriennummer oder Adresse erforderlich.</li><li>Nutze nur ein für den Anschluss und die Last geeignetes Messgerät gemäß Herstelleranleitung. Keine Arbeiten an offenen Leitungen oder fest angeschlossenen Geräten.</li><li>Lies die Differenz des kWh-Zählers und die verstrichene Zeit ab. Wiederhole bei ungewöhnlicher Nutzung oder anderen Jahreszeiten.</li><li>Trage oben deine realistischen Betriebstage ein. Bei Geräten mit einzelnen Zyklen ist ein Vergleich pro vollständiger Nutzung sinnvoller als eine 24-Stunden-Hochrechnung.</li></ol><p><a href="/downloads/haushalt-messprotokoll.csv" download>Messprotokoll herunterladen</a></p><h2>Formel und Unsicherheit</h2><p>kWh je 24 Stunden = gemessene kWh ÷ Messstunden × 24. Jahreskosten = Tagesverbrauch × Betriebstage × Strompreis. Kurze Messungen, ein leerer Kühlschrank oder ungewöhnliche Außentemperaturen ergeben keine belastbare Jahresprognose. Der Rechner verlängert nur deinen beobachteten Durchschnitt.</p><h2>Wann lohnt sich ein neues Gerät?</h2><p>Ein hoher Verbrauch ist ein Anlass zum Prüfen, kein automatischer Kaufgrund. Erst Nutzung und Wartung ansehen, dann beim <a href="/geraete-austausch-rechner.html">Austauschrechner</a> Anschaffung und Stromkosten gemeinsam rechnen. Weitere Maßnahmen: <a href="/guide/strom-sparen-haushalt.html">Strom sparen im Haushalt</a>.</p>'''+ad([('Strommessgeraet+kWh','Strommessgerät mit kWh-Anzeige')])
 (SITE/'strommess-protokoll.html').write_text(page('strommess-protokoll','Finde große Verbraucher mit einer nachvollziehbaren Messung. Rechne deinen beobachteten Verbrauch hoch und halte die Annahmen fest.',body,'<p><strong>Energie</strong>1,2 kWh im Beispiel</p><p><strong>Zeit</strong>48 Stunden gemessen</p><p><strong>Vergleichswert</strong>0,6 kWh je 24 Stunden</p>'))
 body=form('replacement',[('oldKwh','Vorhandenes Gerät: kWh pro Jahr',400,0,20000),('newKwh','Neues Gerät: kWh pro Jahr',200,0,20000),('price','Dein Strompreis in €/kWh',.35,0,5),('purchase','Gesamter Kaufpreis einschließlich Lieferung in €',500,0,50000),('years','Vergleichszeitraum in Jahren',5,1,30,'1')],'Beispiel: 200 kWh weniger × 0,35 € = 70 € Stromersparnis pro Jahr. 500 € Kaufpreis ÷ 70 € = rund 7,14 Jahre. Nach fünf Jahren kostet Behalten 700 €, Neukauf einschließlich Strom 850 €.')+'''<h2>Behalten ist der richtige Vergleichspunkt</h2><p>Der frühere Kaufpreis des vorhandenen Geräts ist bereits bezahlt. Für die heutige Entscheidung vergleichst du seine künftigen Kosten mit dem Kauf und Betrieb des neuen Geräts. Ist das alte Gerät defekt oder erfüllt es die Aufgabe nicht mehr, beantwortet diese reine Stromrechnung die Entscheidung nicht vollständig.</p><h2>Gleiche Leistung, gleiche Grundlage</h2><p>Vergleiche ähnliche Gerätegröße und Nutzungsmenge. Ein kleineres Gerät mit weniger Funktionen löst möglicherweise eine andere Aufgabe. Setze bei beiden Geräten dieselbe Anzahl von Zyklen an. Bei Labelangaben je 100 Zyklen: Wert ÷ 100 × deine Zyklen pro Jahr. Mischt du alte Jahreslabel und neue Zykluslabel ungeprüft, entsteht ein falscher Vorteil.</p><h2>Formel</h2><p>Jährliche Stromersparnis = (alter Jahresverbrauch − neuer Jahresverbrauch) × Strompreis. Einfache Rückflusszeit = Kaufpreis ÷ positive jährliche Stromersparnis. Bei null oder negativem Vorteil gibt es durch Strom allein keine Rückflusszeit. Über den gewählten Zeitraum addiert der Rechner Stromkosten und neuen Kaufpreis.</p><h2>Was fehlt?</h2><p>Wartung, mögliche Reparaturen, Wiederverkaufswert, Finanzierung, künftige Tarifänderungen und die Umweltwirkungen der Herstellung fehlen. Auch die verbleibende Lebensdauer ist unbekannt. Eine Rückflusszeit von 15 Jahren bedeutet nicht, dass das neue Gerät so lange funktioniert.</p><h2>Vor dem Kauf</h2><ol class="work-steps"><li><a href="/strommess-protokoll.html">Vorhandenen Verbrauch messen</a>, statt nur einen hohen Typenschildwert zu übernehmen.</li><li>Für das konkrete neue Modell Herstellerdaten oder den Datensatz in <a href="https://eprel.ec.europa.eu/">EPREL</a> prüfen. Kein beliebiges Modell aus derselben Produktfamilie einsetzen.</li><li>Mindestens zwei realistische Szenarien rechnen: deine heutige Nutzung und eine niedrigere Nutzung. Einen höheren Strompreis nicht als sicher voraussetzen.</li></ol><p>Für zwei Trocknungsverfahren statt zweier Geräte: <a href="/waeschetrockner-oder-luftentfeuchter.html">Wäschekosten vergleichen</a>.</p>'''
 (SITE/'geraete-austausch-rechner.html').write_text(page('geraete-austausch-rechner','Ein sparsameres Gerät spart Strom. Ob es auch Geld spart, entscheidet sich erst mit Kaufpreis und Nutzungsdauer.',body,'<p><strong>Vorhanden</strong>Künftige Stromkosten</p><p><strong>Neu</strong>Kaufpreis plus Stromkosten</p><p><strong>Entscheidung</strong>Beide über denselben Zeitraum</p>'))
 (SITE/'downloads').mkdir(exist_ok=True)
 (SITE/'downloads/haushalt-messprotokoll.csv').write_text('Datum;Geraet;Energie_kWh;Messdauer_Stunden;Betriebstage_Jahr;Tarif_EUR_kWh;Bedingungen\n;;;;;;\n;;;;;;\n;;;;;;\n',encoding='utf-8-sig')
 print('Built 4 original household pages and blank measurement sheet.')

if __name__=='__main__':
 main()
