#!/usr/bin/env python3
"""Build a bounded EN/IT winter release after generic page generators."""
from pathlib import Path
from html import escape as e
import hashlib,json,re
from build_winter_guides import PAGES,FIELDS,SOURCES,SITE,DATE
from winter_locales import CONTENT
from build_agent_md import to_markdown, inject_md_link
BASE='https://getecoback.com'
HUB={'de':'/winter-energiesparen.html','en':'/en/winter-energy-saving.html','it':'/it/risparmio-energia-inverno.html'}
UI={
'en':dict(title='Winter energy: choose your next step',desc='Heating controls, draughts, shower costs and seasonal lights: seven practical guides and three free calculators to plan your next step with your own values.',lead='Adjust, measure or repair before buying. Choose the problem you want to solve.',kicker='EcoBack · Winter check',date='EcoBack editorial team · 4 October 2026 · Source-based guidance, no hands-on product tests',tasks='Choose a task',next='More winter decisions',home='English home',tools='All calculators',sources='Sources and limits',source_note='Technical sources below are in German, checked for the original guide on 4 October 2026. These adaptations do not establish local rental law, installation rules or tariffs. Follow local requirements and the instructions for your actual system.',faq='Common questions',calc='Calculate with your own values',note='Defaults are illustrative scenarios, not current tariffs or measured savings. Use one currency for every amount; no exchange-rate conversion. Units are litres, °C and kWh.',currency='Currency',own='I have checked these values for my own situation.',submit='Calculate result',export='Download calculation as text',privacy='Your inputs stay in this browser. Only fixed use and export actions may be counted after analytics consent; input values are not sent. The download contains your inputs.',noscript='JavaScript is needed for your own calculation. The method and example remain available below.',example='Method and example',read='Read the guide',formula=['Annual net saving = controllable heating cost × assumed saving percentage − additional running costs. Simple payback = purchase cost ÷ positive annual net saving. Example: 600 × 5% − 10 = 20 per year; 150 ÷ 20 = 7.5 years. Zero or negative net savings have no payback.','Heat = litres × temperature rise × 0.001163 kWh; input energy = heat ÷ system factor. Add variable water and wastewater cost. Example: 12 litres/minute × 8 minutes = 96 litres; 10 to 38 °C requires 3.126144 kWh of heat. With factor 1, energy at 0.35/kWh and water at 5/m³, cost is about 1.57 per shower; at 8 litres/minute, about 1.05.','Cost = watts × hours × days ÷ 1,000 × energy unit price. Add timer watts × 24 × days ÷ 1,000 × price. Example: 20 W × 8 h × 30 days at 0.35/kWh costs 1.68. Four lighting hours plus a 0.5 W timer costs about 0.97: a difference of 0.71, before buying the timer.']),
'it':dict(title='Risparmiare energia in inverno: da dove iniziare',desc='Riscaldamento, spifferi, costo della doccia e luci: sette guide pratiche e tre calcolatori gratuiti per scegliere il prossimo passo con i tuoi dati.',lead='Regola, misura o ripara prima di acquistare. Scegli il problema da risolvere.',kicker='EcoBack · Controllo invernale',date='Redazione EcoBack · 4 ottobre 2026 · Fonti pubbliche, nessun test diretto dei prodotti',tasks='Scegli un problema',next='Altre decisioni per l’inverno',home='Home in italiano',tools='Calcolatore energetico',sources='Fonti e limiti',source_note='Le fonti tecniche seguenti sono in tedesco, verificate per la guida originale il 4 ottobre 2026. L’adattamento non stabilisce norme locali su affitto, installazione o tariffe. Rispetta i requisiti locali e le istruzioni del tuo impianto.',faq='Domande frequenti',calc='Calcola con i tuoi valori',note='I valori iniziali sono esempi ipotetici, non tariffe attuali o risparmi misurati. Usa la stessa valuta per tutti gli importi; nessuna conversione valutaria. Unità: litri, °C e kWh.',currency='Valuta',own='Ho verificato questi valori per la mia situazione.',submit='Calcola il risultato',export='Scarica il calcolo come testo',privacy='I dati restano nel browser. Solo azioni fisse di utilizzo ed esportazione possono essere conteggiate dopo il consenso alle statistiche; i valori inseriti non vengono inviati. Il file scaricato contiene i tuoi dati.',noscript='Per il calcolo personale serve JavaScript. Metodo ed esempio restano disponibili qui sotto.',example='Metodo ed esempio',read='Leggi la guida',formula=['Risparmio netto annuo = costi di riscaldamento influenzabili × percentuale ipotizzata − costi aggiuntivi annui. Recupero semplice = costo di acquisto ÷ risparmio netto annuo positivo. Esempio: 600 × 5% − 10 = 20 all’anno; 150 ÷ 20 = 7,5 anni. Con risparmio nullo o negativo non c’è recupero.','Calore = litri × aumento di temperatura × 0,001163 kWh; energia acquistata = calore ÷ fattore del sistema. Aggiungi acqua e scarico variabili. Esempio: 12 litri/minuto × 8 minuti = 96 litri; da 10 a 38 °C servono 3,126144 kWh di calore. Con fattore 1, energia a 0,35/kWh e acqua a 5/m³, circa 1,57 per doccia; a 8 litri/minuto, circa 1,05.','Costo = watt × ore × giorni ÷ 1.000 × prezzo per kWh. Aggiungi watt del timer × 24 × giorni ÷ 1.000 × prezzo. Esempio: 20 W × 8 h × 30 giorni a 0,35/kWh costano 1,68. Quattro ore di luce e timer da 0,5 W costano circa 0,97: differenza 0,71, prima del costo del timer.'])}
LABELS={
'en':{'thermostat':['Controllable annual heating cost (currency)','Assumed saving (%)','Heads, hub and adapters: total cost (currency)','Additional annual running cost (currency)'],'shower':['Current flow (litres/minute)','Comparison flow (litres/minute)','Minutes per shower','Household showers per year','Cold water (°C)','Mixed shower water (°C)','System factor: useful heat ÷ input energy','Energy unit price (currency/kWh)','Variable water and wastewater (currency/m³)','Water-saving showerhead cost (currency)'],'lights':['Total lighting power (W)','Current hours per day','Hours per day with timer','Lighting days','Electricity unit price (currency/kWh)','Additional timer consumption (W)']},
'it':{'thermostat':['Costo annuo di riscaldamento influenzabile (valuta)','Risparmio ipotizzato (%)','Testine, centralina e adattatori: costo totale (valuta)','Costi aggiuntivi annui (valuta)'],'shower':['Portata attuale (litri/minuto)','Portata di confronto (litri/minuto)','Minuti per doccia','Docce annue del nucleo familiare','Acqua fredda (°C)','Acqua miscelata della doccia (°C)','Fattore: calore utile ÷ energia acquistata','Prezzo energia (valuta/kWh)','Acqua e scarico variabili (valuta/m³)','Costo del soffione a risparmio (valuta)'],'lights':['Potenza totale delle luci (W)','Ore attuali al giorno','Ore al giorno con timer','Giorni di accensione','Prezzo elettricità (valuta/kWh)','Consumo aggiuntivo del timer (W)']}}
DE=list(PAGES)
def route(lang,i):return '/guide/'+DE[i]+'.html' if lang=='de' else f'/{lang}/guide/{CONTENT[lang][i][0]}.html'
def languages(i=None):return {lang:HUB[lang] if i is None else route(lang,i) for lang in HUB}
def switch(i=None):return '<nav class="winter-languages" aria-label="Language">'+' · '.join(f'<a lang="{lang}" hreflang="{lang}" href="{url}">{label}</a>' for (lang,url),label in zip(languages(i).items(),['Deutsch','English','Italiano']))+'</nav>'
def alternates(i=None):return ''.join(f'<link rel="alternate" hreflang="{lang}" href="{BASE+url}">\n' for lang,url in languages(i).items())
def calculator(lang,kind):
 u=UI[lang];fields=''.join(f'<label>{e(label)}<input required type="number" name="{name}" value="{value}" min="{lo}" max="{hi}" step="any" inputmode="decimal"></label>' for (name,_,value,lo,hi),label in zip(FIELDS[kind],LABELS[lang][kind]))
 return f'''<section class="winter-calculator" id="calculator" data-winter-tool="{kind}"><h2>{u['calc']}</h2><p>{u['note']}</p><form><label>{u['currency']} <select name="currency">{''.join(f'<option value="{c}">{c}</option>' for c in ['EUR','GBP','USD','CHF'])}</select></label><div class="winter-fields">{fields}</div><label class="winter-confirm"><input type="checkbox" name="own"> {u['own']}</label><button type="submit">{u['submit']}</button></form><p data-error role="alert"></p><div data-result hidden tabindex="-1" aria-live="polite"></div><button type="button" data-export hidden>{u['export']}</button><p class="winter-note">{u['privacy']}</p><noscript><p>{u['noscript']}</p></noscript></section><h2>{u['example']}</h2><p>{u['formula'][['thermostat','shower','lights'].index(kind)]}</p>'''
def page(lang,i=None):
 u=UI[lang];hub=i is None;url=BASE+(HUB[lang] if hub else route(lang,i));faq=[];tool=None
 if hub:
  title,desc,lead=u['title'],u['desc'],u['lead'];body=f'<h2 id="tasks">{u["tasks"]}</h2><nav class="winter-grid">'+''.join(f'<a href="{route(lang,j)}"><strong>{e(p[1])}</strong><span>{e(p[3])}</span></a>' for j,p in enumerate(CONTENT[lang]))+'</nav>'
 else:
  slug,title,desc,lead,sections,faq=CONTENT[lang][i];source=PAGES[DE[i]];tool=source.get('tool')
  body=(calculator(lang,tool) if tool else '')+''.join(f'<h2>{e(h)}</h2><p>{e(t)}</p>' for h,t in sections)
  body+=f'<h2>{u["faq"]}</h2>'+''.join(f'<details><summary>{e(q)}</summary><p>{e(a)}</p></details>' for q,a in faq)
  body+=f'<h2>{u["sources"]}</h2><p>{u["source_note"]}</p><ul>'+''.join(f'<li><a href="{SOURCES[k][1]}" hreflang="de">{e(SOURCES[k][0])} (DE)</a></li>' for k in source['sources'])+'</ul>'
 schema=[{'@type':'WebPage' if hub else 'Article','headline':title,'description':desc,'url':url,'inLanguage':lang,'datePublished':DATE,'dateModified':DATE,'author':{'@type':'Organization','name':'EcoBack'},'publisher':{'@id':BASE+'/#org'}}]
 if faq:schema.append({'@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in faq]})
 assets=hashlib.sha256(b''.join((SITE/f'assets/{f}').read_bytes() for f in ['winter-tools.mjs','winter-math.mjs','winter-i18n.mjs'])).hexdigest()[:12]
 return f'''<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{e(title)} | EcoBack</title><meta name="description" content="{e(desc)}"><link rel="canonical" href="{url}">
{alternates(i)}<meta property="og:type" content="{'website' if hub else 'article'}"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(desc)}"><meta property="og:url" content="{url}"><link rel="stylesheet" href="/assets/winter.css"><script type="application/ld+json">{json.dumps({'@context':'https://schema.org','@graph':schema},ensure_ascii=False)}</script><script type="module" src="/assets/winter-tools.mjs?v={assets}"></script></head><body class="winter-page"><main class="winter-wrap">{switch(i)}<header class="winter-hero"><p class="winter-kicker">{u['kicker']}</p><h1>{e(title)}</h1><p class="winter-lead">{e(lead)}</p><p class="winter-note">{u['date']}</p><a class="winter-button" href="{'#tasks' if hub else '#calculator' if tool else '#decision'}">{u['tasks'] if hub else u['calc'] if tool else u['read']} ↓</a></header><article id="decision">{body}<nav class="winter-next"><h2>{u['next']}</h2><p><a href="{HUB[lang]}">{u['tasks']}</a> · <a href="/{lang}/">{u['home']}</a> · <a href="{'/tools.html' if lang=='en' else '/it/calcolatore.html'}">{u['tools']}{' (DE / EN)' if lang=='en' else ''}</a></p></nav></article></main></body></html>'''
def main():
 for lang in CONTENT:
  for i in [None,*range(len(DE))]:
   p=SITE/(HUB[lang] if i is None else route(lang,i)).lstrip('/');p.parent.mkdir(parents=True,exist_ok=True);p.write_text(page(lang,i))
   if i is None:
    md_url=HUB[lang][:-5]+'.md';p.with_suffix('.md').write_text(to_markdown(p.read_text(),HUB[lang],lang));p.write_text(inject_md_link(p.read_text(),BASE+md_url)[0])
  p=SITE/lang/'index.html';s=p.read_text();s=re.sub(r'<!--EB_WINTER_LOCALE-->.*?<!--/EB_WINTER_LOCALE-->','',s,flags=re.S)
  block=f'<!--EB_WINTER_LOCALE--><section style="max-width:1000px;margin:24px auto;padding:20px;background:#edf3e6;color:#163728"><h2><a href="{HUB[lang]}">{UI[lang]["title"]}</a></h2><p>{UI[lang]["lead"]}</p><ul>'+''.join(f'<li><a href="{route(lang,i)}">{e(item[1])}</a></li>' for i,item in enumerate(CONTENT[lang]))+'</ul></section><!--/EB_WINTER_LOCALE-->'
  match=re.search(r'</header>',s) or re.search(r'<main[^>]*>',s) or re.search(r'<body[^>]*>',s)
  if not match:raise ValueError('Missing homepage anchor: '+lang)
  s=s[:match.end()]+block+s[match.end():];p.write_text(s)
 # German source pages also expose the language group visibly and to crawlers.
 for i in [None,*range(len(DE))]:
  p=SITE/languages(i)['de'].lstrip('/');s=p.read_text();s=re.sub(r'<nav class="winter-languages".*?</nav>','',s,flags=re.S);s=re.sub(r'<link rel="alternate" hreflang="[^"]+" href="[^"]+">\s*','',s)
  s=re.sub(r'(<link rel="canonical" href="[^"]+">)\s*',r'\1\n',s);s=s.replace('</head>',alternates(i)+'</head>');s=s.replace('<main class="winter-wrap">','<main class="winter-wrap">'+switch(i),1);p.write_text(s)
 print('Built 14 localized winter guides, 2 hubs, 6 calculator experiences; linked both homepages and 8 three-language groups.')
if __name__=='__main__':main()
