#!/usr/bin/env python3
"""Australian cooling decisions; authored guidance, no market-demand claims."""
from pathlib import Path
from html import escape as e
import json,re,hashlib
ROOT=Path(__file__).resolve().parents[1];SITE=ROOT/'site';BASE='https://getecoback.com';DATE='2026-10-04'
SOURCES={
 'tariff':('Australian Energy Regulator · Energy Made Easy: electricity tariffs','https://www.energymadeeasy.gov.au/article/electricity-tariffs'),
 'ac':('CHOICE: portable air conditioner buying guide','https://www.choice.com.au/home-and-living/cooling/air-conditioners/buying-guides/portable-air-conditioners'),
 'evap':('CHOICE: portable evaporative coolers and portable air conditioners','https://www.choice.com.au/home-and-living/cooling/portable-air-conditioners/articles/portable-evaporative-coolers-vs-portable-air-conditioners'),
 'health':('Healthdirect Australia: hot weather risks and staying cool','https://www.healthdirect.gov.au/hot-weather-risks-and-staying-cool')}
PAGES={
'portable-air-conditioner-running-cost':dict(title='Portable air conditioner running costs in AUD',desc='Estimate portable air conditioner electricity costs in AUD using input watts, hours and your own peak or off-peak rates. Cooling capacity is not input power.',lead='Use electrical input power or measured average watts, not the advertised cooling capacity. Your tariff and operating hours determine the energy cost.',tool='ac',sources=['tariff','ac','health'],body=[
('Which watt number belongs in the calculator?', 'Cooling capacity describes heat removed; electrical input describes electricity consumed. Both can be expressed in kW, but they are not interchangeable. Find input watts in the manual or use a suitable energy meter within its rating. If you measure a full session, average watts = session kWh × 1,000 ÷ session hours. Do not substitute a headline 3.5 kW cooling capacity for input power.'),
('What the two time blocks mean', 'For a single-rate plan, use the same cents/kWh in both blocks or set the second block to zero hours. For time-of-use billing, match the hours to your retailer’s actual rate windows, including weekday, weekend and seasonal differences. If there are more than two rates, calculate separate non-overlapping scenarios and add their costs. Do not assign a controlled-load rate unless the appliance is actually on that eligible circuit.'),
('What is outside this estimate?', 'The estimate covers the chosen appliance’s usage charges. It excludes daily supply charges, demand charges, installation, purchase price and operation outside the entered hours. A demand tariff may add a cost based on peak load; this calculator cannot estimate it from daily kWh. Use rates on the same tax basis as your bill. Default numbers are invented examples, not an Australian average tariff or a tested model.'),
('Check the installation before choosing a unit', 'The room needs a permitted route for exhaust heat outdoors, a compatible window kit and enough space around the appliance. Follow the manual for duct length and drainage. A single-duct unit can draw replacement warm air into the home; a better seal does not eliminate every source of heat. Use the existing window-fit checklist before ordering. If the home remains dangerously hot, prioritise access to a cooler place and local health advice over a cost target.')],faq=[('Can I use the advertised cooling kW as electricity input?', 'No. Use electrical input watts or a measured whole-session average. Cooling capacity measures a different quantity.'),('Does the result include my entire electricity bill?', 'No. It estimates usage charges for the entered appliance hours. Supply, demand and other household charges are excluded.')]),
'fan-running-cost':dict(title='Fan running costs in Australia: AUD calculator',desc='Calculate ceiling, pedestal or desk fan energy costs from actual watts and hours. Use your Australian electricity rates and compare like-for-like use.',lead='A fan can improve personal comfort with moving air. Its electricity cost does not prove that it can replace room cooling in every condition.',tool='fan',sources=['tariff','health'],body=[
('Use the speed you actually run', 'Rated maximum power is not necessarily the power at your usual speed. Use the manufacturer’s speed-specific input data if available, or measure a suitable plug-in fan over a complete session. For fixed ceiling fans, use documentation or advice from a qualified electrician; do not access wiring to take a measurement. Lights attached to the fan and standby outside the chosen hours are separate loads unless already included.'),
('Estimate hours without inventing a saving', 'Enter the hours when the fan is used and the applicable cents/kWh. The two blocks are non-overlapping periods within one day, not two separate fans. If you compare with air conditioning, compare the same occupied period and whether both options actually provide acceptable conditions. A lower running cost is not evidence of equivalent cooling or safe indoor temperatures.'),
('Personal comfort and room temperature differ', 'Moving air can help a person feel cooler, but a fan does not refrigerate the room. Do not leave it running in an empty room solely to lower the air temperature. During severe heat, follow current health advice and arrange a cooler location if needed. People with health conditions or limited mobility may need extra support; a cost calculator is not a heat-safety assessment.'),
('Before buying another fan', 'Check stability, controls, placement, cleaning access and noise information at the speed you plan to use. Keep cables out of walkways and follow instructions around children and moisture. A ceiling fan is a fixed electrical installation: confirm permission and qualified installation rather than treating it like a plug-in desk fan. First test whether repositioning an existing fan improves comfort.')],faq=[('Does a fan lower the room temperature?', 'It does not refrigerate the room. Air movement can improve personal comfort, so cost alone cannot establish equivalent cooling to an air conditioner.'),('Is the default tariff a current Australian average?', 'No. All prefilled values are illustrative. Enter the usage rates and time windows from your own plan.')]),
'evaporative-cooler-or-portable-ac':dict(title='Evaporative cooler or portable AC in Australia?',desc='Compare evaporative coolers, fans and portable refrigerated air conditioners by humidity, exhaust needs and room conditions before buying in Australia.',lead='A water tank is not a substitute for a refrigerant circuit. Identify the cooling method before comparing a cheap “air cooler” with an air conditioner.',sources=['evap','ac','health'],body=[
('Start with humidity where you actually live', 'An evaporative cooler passes air over water and adds moisture. Its usefulness depends on how readily water can evaporate; humid conditions limit that process. CHOICE identifies dry climates as the suitable setting and warns about moisture build-up without ventilation. Do not treat an entire state or the whole country as one climate: coastal humidity and inland conditions can differ, and conditions change through the season.'),
('Three methods, three different jobs', 'A fan moves air for personal comfort without refrigeration. An evaporative cooler uses water evaporation and needs the ventilation specified by its maker. A portable refrigerated air conditioner removes heat using a refrigerant system and must reject that heat outside for room cooling. For common hose models, that means a window or another approved exhaust arrangement. Neither a water tank nor an ice compartment proves room-air-conditioning performance.'),
('Check what the room permits', 'Can you fit a compatible exhaust panel while keeping security, drainage and daily window use workable? Use the window-kit checklist for sliding, awning or casement openings and flyscreens. If no safe permitted exhaust path exists, do not buy a hose unit expecting it to cool the room with its exhaust left indoors. Do not seal required ventilation or combustion-air openings.'),
('Compare the whole decision', 'Include purchase, accessories, water management, cleaning, noise at the actual setting and energy use. CHOICE notes the limitations of single-duct portable units compared with fixed split systems. A renter may still value reversibility, but that is a practical trade-off, not proof of better efficiency. Check installation permissions and local electrical compatibility. During severe heat, access to a reliably cooler place can matter more than owning a particular product.')],faq=[('Is a no-hose water cooler the same as a portable AC?', 'No. Evaporative cooling adds moisture and depends on conditions. Refrigerated room cooling must reject heat outside.'),('Is an evaporative cooler automatically suitable anywhere in Australia?', 'No. Check actual humidity, ventilation and manufacturer guidance rather than relying on a country-wide recommendation.')]),
'rental-window-shade':dict(title='Window shade for Australian rentals',desc='Plan shade around sun direction, window access and rental permissions. Compare curtains and removable options without blocking ventilation or exits.',lead='First identify when direct sun reaches the room. Choose a reversible response that suits the window, the building and the permission you actually have.',sources=['health','ac'],body=[
('Observe the window over a day', 'Record which windows receive direct sun and at what time the room becomes uncomfortable. In Australia, afternoon sun on west-facing glass can be an important problem, but surrounding buildings, trees and orientation change the picture. Take notes at the time you use the room rather than selecting a product only from compass direction or an area estimate.'),
('Use what is already available', 'Close suitable blinds or curtains before direct sun heats the room. Keep required ventilation and clear exits. Check for gaps at the sides and whether a curtain obstructs an air conditioner, heater or window handle. An internal covering may improve comfort, but it is not a measured guarantee of a particular temperature drop or percentage saving.'),
('Treat external shade as an installation', 'External shading can intercept sun before it reaches the glass, but a sail, awning or screen needs appropriate anchors, wind limits, dimensions and access. A removable label does not prove safe attachment. Never improvise fixings at height or secure a shade to a flyscreen. Ask the landlord, building manager or owners corporation about permissions where relevant; rules differ by state and property.'),
('Check film and temporary panels carefully', 'For window film, confirm compatibility with the exact glass and glazing warranty. Some combinations create thermal-stress concerns; do not assume every reflective film suits every pane. Temporary panels must preserve necessary ventilation, security, drainage and emergency access. Compare a permitted low-impact trial with the full cost of an alteration, and use the window-fit guide when sharing an opening with an AC hose.')],faq=[('Does “removable” mean I do not need permission?', 'No. Check the lease, building requirements and local rules for the proposed fixing and appearance.'),('Can shade replace cooling during every heat event?', 'No. It can reduce direct solar exposure, but safe conditions depend on the building and weather. Have a plan for a cooler place if the home remains too hot.')]),
'cool-bedroom-at-night':dict(title='Cool a bedroom at night in Australia',desc='Plan bedroom cooling around outdoor conditions, security, noise and heat advice. Compare ventilation, fans and air conditioning without unsafe promises.',lead='Open windows only when the outside conditions and the home make it useful and safe. A hot, humid or smoky night needs a different plan from a cool evening.',sources=['health','ac','tariff'],body=[
('Prepare before the evening', 'Limit direct sun using suitable existing coverings and reduce avoidable indoor heat where practical. Decide which room is the coolest usable space and whether there is a safe place to go if the home cannot be kept comfortable. Keep water accessible and follow personal medical advice where fluid intake is restricted. This guide is household planning, not individual medical advice.'),
('Make ventilation conditional', 'Compare inside and outside conditions before opening up. Cooler outdoor air can be useful, but smoke, poor air quality, rain, pests and security may make open windows unsuitable. Keep child-safety devices and insect screens in mind. Cross-ventilation needs a path through the home; do not assume one small opening will reliably remove the heat stored in walls and furnishings.'),
('Set up equipment for the actual sleeping space', 'Position a fan for the person without creating cable hazards, and follow its instructions for unattended use. A fan does not lower room temperature. For a portable AC, confirm exhaust sealing, condensate handling, noise at the intended mode and whether the window can remain secure. Do not move a unit into a closed room and leave its hot exhaust indoors.'),
('Use timers without making a safety promise', 'A timer controls hours, not whether indoor conditions remain safe after switch-off. Try a schedule while awake and adjust to observed conditions. Use the cost calculators with your actual overnight rates rather than assuming all night-time electricity is cheap. If someone is unwell in the heat, follow Healthdirect guidance; suspected heatstroke or a life-threatening emergency requires triple zero (000). Cost saving must not delay help.')],faq=[('Should windows always stay open overnight?', 'No. Temperature, humidity, smoke, weather, security and the occupants’ needs determine whether it is useful and safe.'),('Is a fan enough during severe heat?', 'Not necessarily. It does not refrigerate the room. Follow heat-health advice and arrange access to a cooler environment when needed.')])}
FIELDS=[('watts','Average electrical input (W)',1000,0,10000),('hours1','Hours per day at rate 1',4,0,24),('cents1','Rate 1 (Australian cents/kWh)',40,0,500),('hours2','Hours per day at rate 2',2,0,24),('cents2','Rate 2 (Australian cents/kWh)',25,0,500),('days','Number of days',30,1,366)]
def calculator(kind):
 fields=''.join(f'<label>{label}<input required name="{name}" type="number" inputmode="decimal" step="any" min="{lo}" max="{hi}" value="{50 if kind=="fan" and name=="watts" else value}"></label>' for name,label,value,lo,hi in FIELDS)
 return f'''<section id="calculator" class="winter-calculator" data-au-cost><h2>Calculate your usage cost in AUD</h2><p>Invented example values, not current tariffs or product measurements. Enter electrical input watts and non-overlapping hours; both time blocks together must be at most 24 hours per day. Rates are in Australian cents per kWh, not dollars.</p><form><div class="winter-fields">{fields}</div><label class="winter-confirm"><input type="checkbox" name="own"> I have checked these inputs for my own appliance and electricity plan.</label><button type="submit">Calculate AUD cost</button></form><p data-error role="alert"></p><div data-result hidden tabindex="-1" aria-live="polite"></div><button type="button" data-export hidden>Download calculation as text</button><p class="winter-note">Inputs stay in this browser. After analytics consent, only fixed start, confirmed completion and export actions may be counted. No input values are sent. Your downloaded file contains the inputs.</p><noscript><p>For a personal calculation, enable JavaScript. You can still use the formula and example below.</p></noscript></section><h2>Formula and example</h2><p>Daily kWh = watts ÷ 1,000 × (hours 1 + hours 2). Daily AUD = watts ÷ 1,000 × (hours 1 × cents 1 + hours 2 × cents 2) ÷ 100. Multiply by days for the period. An illustrative {'50 W fan uses 0.30 kWh and costs AUD 0.105 per day, or AUD 3.15 over 30 days' if kind=='fan' else '1,000 W input uses 6 kWh and costs AUD 2.10 per day, or AUD 63.00 over 30 days'}, using four hours at 40 c/kWh and two at 25 c/kWh. Neither example is a tested device or tariff recommendation.</p>'''
def cards():return '<nav class="winter-grid" aria-label="Australian cooling guides">'+''.join(f'<a href="/au/{slug}.html"><strong>{e(p["title"])}</strong><span>{e(p["lead"])}</span></a>' for slug,p in PAGES.items())+'</nav>'
def page(slug,p):
 url=BASE+'/au/'+slug+'.html';faq=p['faq'];graph=[{'@type':'Article','headline':p['title'],'description':p['desc'],'url':url,'inLanguage':'en-AU','datePublished':DATE,'dateModified':DATE,'author':{'@type':'Organization','name':'EcoBack'},'publisher':{'@id':BASE+'/#org'}},{'@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in faq]}]
 version=hashlib.sha256((SITE/'assets/au-cooling.mjs').read_bytes()+(SITE/'assets/au-cooling-math.mjs').read_bytes()).hexdigest()[:12]
 body=(calculator(p['tool']) if p.get('tool') else '')+''.join(f'<h2>{e(h)}</h2><p>{e(t)}</p>' for h,t in p['body'])
 return f'''<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{e(p['title'])} | EcoBack</title><meta name="description" content="{e(p['desc'])}"><link rel="canonical" href="{url}">
<link rel="alternate" hreflang="en-AU" href="{url}">
<meta property="og:type" content="article"><meta property="og:title" content="{e(p['title'])}"><meta property="og:description" content="{e(p['desc'])}"><meta property="og:url" content="{url}"><link rel="stylesheet" href="/assets/winter.css"><script type="application/ld+json">{json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False)}</script>{f'<script type="module" src="/assets/au-cooling.mjs?v={version}"></script>' if p.get('tool') else ''}</head><body class="winter-page"><main class="winter-wrap"><nav aria-label="Breadcrumb"><a href="/au/home-comfort.html">Australia · Home comfort</a> / Cooling guide</nav><header class="winter-hero"><p class="winter-kicker">EcoBack · Australia · Cooling decisions</p><h1>{e(p['title'])}</h1><p class="winter-lead">{e(p['lead'])}</p><p class="winter-note">Editorial guidance · 4 October 2026 · No hands-on product tests</p><a class="winter-button" href="{'#calculator' if p.get('tool') else '#guide'}">{'Calculate with my values' if p.get('tool') else 'Find my next step'} ↓</a></header><article id="guide">{body}<h2>Common questions</h2>{''.join(f'<details><summary>{e(q)}</summary><p>{e(a)}</p></details>' for q,a in faq)}<h2>Sources and scope</h2><p>The following public Australian sources were read on 4 October 2026. Calculations and checklists are editorial work, not independent appliance tests. Local installation, rental and safety requirements vary; check the actual system and location.</p><ul>{''.join(f'<li><a href="{SOURCES[k][1]}">{e(SOURCES[k][0])}</a></li>' for k in p['sources'])}</ul><nav class="winter-next"><h2>Plan the rest of your cooling setup</h2><p><a href="/au/home-comfort.html">All Australian home-comfort topics</a> · <a href="/au/portable-air-conditioner-window-kit.html">Window kit and flyscreen checklist</a></p>{cards()}</nav><p class="winter-note"><a href="/en/how-we-recommend.html">Our editorial method</a> · <a href="/datenschutz.html">Privacy (German)</a></p></article></main></body></html>'''
def add_block(path,body):
 p=SITE/path;s=p.read_text();s=re.sub(r'<!--EB_AU_COOLING-->.*?<!--/EB_AU_COOLING-->','',s,flags=re.S)
 marker=re.search(r'</header>',s) or re.search(r'<main[^>]*>',s) or re.search(r'<body[^>]*>',s)
 if not marker:raise ValueError(path)
 block='<!--EB_AU_COOLING-->'+body+'<!--/EB_AU_COOLING-->'
 p.write_text(s[:marker.end()]+block+s[marker.end():])
def main():
 for slug,p in PAGES.items():(SITE/'au'/f'{slug}.html').write_text(page(slug,p))
 add_block('au/home-comfort.html','<section class="au-cooling-entry" style="max-width:1100px;margin:24px auto;padding:24px;background:#edf3e6;color:#203a32"><h2>Plan your warmer-weather setup</h2><p>Five practical decisions, two AUD calculators. Use your own climate, window and tariff.</p><ul>'+''.join(f'<li><a href="/au/{slug}.html">{e(p["title"])}</a></li>' for slug,p in PAGES.items())+'</ul></section>')
 for path in ['au/portable-air-conditioner-window-kit.html','en/index.html','index.html']:
  de=path=='index.html';title='Australien: Kühlung und Stromkosten planen' if de else 'Australia: plan cooling and electricity costs'
  desc='Fünf lokale Leitfäden und zwei Kostenrechner in AUD.' if de else 'Five local guides and two AUD calculators, with window-fit and climate checks.'
  add_block(path,f'<aside style="max-width:1000px;margin:24px auto;padding:20px;background:#edf3e6;color:#203a32"><h2><a href="/au/home-comfort.html" lang="en-AU">{title}</a></h2><p>{desc}</p><a href="/au/portable-air-conditioner-running-cost.html">{"Klimaanlagenkosten in AUD (Englisch)" if de else "Calculate portable AC usage cost in AUD"} →</a></aside>')
 print('Built 5 Australian cooling guides, 2 AUD calculators and 4 entry links.')
if __name__=='__main__':main()
