import test from 'node:test';import assert from 'node:assert/strict';
import {defaults,validate,evaluate,shareURL,parseShare} from '../site/assets/home-fit-model.mjs';
test('unknowns never become a fit verdict',()=>{for(const mode of ['robot','laundry','ac','floor'])assert(evaluate(defaults(mode)).unknown.length>0);});
test('single high step and compound step take different paths',()=>{const s=defaults();s.answers.threshold='high';assert(evaluate(s).messages.includes('rHigh'));s.answers.threshold='double';assert(evaluate(s).messages.includes('rDouble'));assert(!evaluate(s).messages.includes('rLow'));});
test('dock free space and preparation remain independent',()=>{const s=defaults();s.answers.threshold='low';s.answers.dock='no';s.answers.prep='yes';assert.deepEqual(evaluate(s).messages,['rLow','rDock','rPrep']);});
test('no forced heater or new appliance for laundry',()=>{const s=defaults('laundry');s.answers.temp='warm';s.answers.air='clear';s.answers.stop='no';assert.deepEqual(evaluate(s).messages,['lBaseline']);});
test('support confirmation does not remove shutter constraints',()=>{const s=defaults('ac');s.answers.support='yes';s.answers.shutter='yes';s.answers.window='tilt';assert.deepEqual(evaluate(s).messages,['aWindow','aShutter']);});
test('time saving includes cleanup and can be negative',()=>{const s=defaults('floor');assert.equal(evaluate(s).hours,13);assert.equal(evaluate(s).cleanupLimit,10);s.times.cleanup=20;assert.equal(evaluate(s).hours,-26);s.times.frequency=0;assert.equal(evaluate(s).hours,0);});
test('share roundtrip omits query and rejects data not in schema',()=>{const s=defaults('floor');const u=new URL(shareURL('https://getecoback.com/fr/calculateur.html?__probe=1',s));assert.equal(u.search,'');assert.deepEqual(parseShare(u.hash),s);for(const bad of [{...s,extra:'secret'},{...s,mode:'constructor'},{...s,times:{...s.times,manual:null}},{...s,times:{...s.times,frequency:22}}])assert.throws(()=>validate(bad));assert.throws(()=>parseShare('#eco-fit-v1=%XX'));assert.throws(()=>parseShare('#eco-fit-v1='+ 'x'.repeat(3501)));});
