"""Authored EN/IT winter decision content; language is not a country claim."""
CONTENT = {
'en': [
('smart-radiator-valves-worth-it', 'Are smart radiator valves worth it?', 'Check radiator valve compatibility, routines and total costs. Calculate simple payback using your own savings assumptions before buying smart controls.', 'Scheduling may avoid heating empty rooms. A smart valve does not make heat cheaper; its value depends on what changes in your daily routine.', [
('Start with your existing routine', 'If you already turn heating down when appropriate, the extra saving may be small. A basic programmable head can suit fixed hours; remote control may help with irregular attendance. Thermostat numbers represent target temperatures, not fixed power. Turning a valve to maximum does not necessarily warm a room faster. Keep the sensor clear of curtains and furniture.'),
('Check the system before ordering', 'This guide covers thermostatic heads on water-filled radiators. Underfloor heating, electric radiators and boiler controls need different solutions. Identify the valve connection and any adapter from the installation instructions. Include every head, hub, adapter, battery and required subscription in the cost. Check whether schedules still work without internet access.'),
('Use the part of the bill you can influence', 'Exclude hot water, fixed charges and other homes from the heating cost base. Shared-building billing can change how reduced heat use affects your own bill. The savings percentage below is an assumption, not a measured product claim. A milder winter alone does not prove that a new control works. Keep records for comparable use and weather.'),
('In a rented home', 'Check your lease and the local responsibility for changes, keep original heads and follow the maker’s instructions. Do not loosen the water-carrying valve body. Ask the landlord or a qualified installer when compatibility is uncertain.')], [('Is a 20% saving guaranteed?', 'No. Savings depend on the previous settings, occupancy, building and billing method. Include a zero-saving scenario.'), ('Does any smart head fit any radiator?', 'No. Check valve type, connector, adapter and the control system before buying.')]),
('radiator-not-heating', 'Radiator not heating: what to check first', 'One cold radiator or a whole cold home? Check settings, timing and warning signs before bleeding radiators or buying new heating equipment.', 'Separate a settings problem from a system fault before touching the radiator.', [
('One radiator or the whole home?', 'Confirm that heating is scheduled on, that the room needs heat and that the room thermostat is requesting it. A radiator can correctly cool down once its target is reached. If several radiators stay cold, check the permitted user controls and report the pattern; a new radiator head will not repair a boiler or circulation fault.'),
('Describe the pattern', 'A cold top with gurgling can suggest trapped air, but the symptom alone is not a diagnosis. A cold bottom can involve flow or deposits. Compare rooms and record when the issue occurs. Avoid assuming that every uneven surface temperature is a fault: some temperature drop is normal during heat transfer.'),
('Know the safe boundary', 'Bleed only when your system instructions and responsibilities permit it. Hot water can escape and system pressure may change. Do not open gas equipment, dismantle valves, force a pin or repeatedly refill a leaking system. Shared buildings may require the caretaker to manage pressure. Visible leaks, fault codes or repeated pressure loss belong with a qualified professional.'),
('Report useful information', 'Send the responsible maintenance service the rooms affected, settings, timing, sounds and visible warning codes. Do not wait on this checklist if there is a gas smell, a carbon monoxide alarm or an immediate hazard: leave the unsafe area and use local emergency guidance. Portable heaters do not resolve the underlying fault.')], [('Should every cold radiator be bled?', 'No. Check demand and timing first. Bleeding is useful only for an appropriate system and symptom.'), ('Will a smart thermostat fix this?', 'It cannot fix a circulation, boiler or water-system fault. Establish the cause before buying controls.')]),
('draughty-windows-rented-home', 'Draughty windows in a rented home', 'Find out whether cold air comes through a gap or off a cold pane. Check seals, ventilation and repair responsibilities before buying draught-proofing.', 'A cold feeling near glass is not always a leaking window. The cause determines the next step.', [
('Find the source without a flame', 'With the window shut, observe movement of a light tissue near the frame on a windy day. This is only a rough indication, not an airtightness test. Cold air moving down a cold pane can feel like a draught even with intact seals. Check visible damage and whether the sash closes correctly; do not force the hardware.'),
('Keep designed ventilation open', 'Do not block trickle vents, combustion-air openings or mechanical ventilation. Airtightness and planned ventilation are different tasks. A loose or damaged seal may need the correct replacement profile, not another thick adhesive layer. The wrong strip can prevent closing or damage fittings.'),
('Agree the repair first', 'In a rental, document the gap or damage and check local rules and the lease before altering frames or fittings. This is general technical guidance, not German rental law applied abroad. Do not attempt external work at height. Ask the responsible repair service to assess misaligned windows.'),
('Use curtains with care', 'A curtain may improve perceived comfort but does not repair a leak. Leave radiator valves and heat flow unobstructed; watch for condensation hidden behind fabric. Measure humidity and inspect cold surfaces after changes. If the frame is sound, compare comfort and ventilation before buying more materials.')], [('Does cold glass mean the seal leaks?', 'No. Cold glass can create downward air movement without a gap in the seal.'), ('Can I seal every opening?', 'No. Intended ventilation and combustion-air openings must remain functional.')]),
('heating-night-setback', 'Should you turn heating down at night?', 'Assess night-time heating setbacks by building, controls and heating type. Balance warm-up time, comfort and moisture instead of using a universal setting.', 'A lower temperature can reduce heat loss, but the useful schedule depends on the home and the heating system.', [
('Check how quickly the home responds', 'A radiator system in a responsive room behaves differently from slow underfloor heating. A well-insulated home may lose little temperature overnight, so a deep setback can add little benefit. Heat pumps and weather-compensated systems can lose efficiency if recovery needs much hotter water. Follow the installer’s control guidance rather than imposing one schedule on every system.'),
('Lower is not the same as off', 'Keep frost protection and necessary room temperatures. Take extra care with vulnerable occupants, cold outside walls and moisture problems. Warmer air can hold more moisture; as air cools, relative humidity rises even without added water. A dry-looking room is not proof that hidden cold surfaces are safe.'),
('Run a small, reversible comparison', 'Record evening and morning temperatures, humidity, comfort and the heating meter over several comparable days. Note occupancy and outdoor weather. Change one setting at a time. Do not interpret a lower bill during warmer weather as proof of savings from the schedule.'),
('Morning recovery matters', 'If rooms take too long to recover, adjust start time or reduce the setback. Avoid using an expensive portable heater to compensate for an unsuitable schedule. Central and room controls should work together; check the manual or ask an installer if they seem to fight each other.')], [('Is one night temperature right for all homes?', 'No. Building fabric, moisture, occupants and heating response matter.'), ('Should a heat pump always switch off overnight?', 'No. Efficient operation can favour steadier settings. Follow system-specific advice and measure the result.')]),
('shower-cost-calculator', 'Shower cost and water-saving calculator', 'Estimate shower water and energy costs using measured flow, duration and your tariff. Compare a lower-flow showerhead and check compatibility first.', 'Measure flow before replacing hardware. Shorter showers and lower flow affect both water use and the energy needed to heat it.', [
('Measure what comes out', 'If safe, collect water at your normal shower setting for a timed interval. Litres collected divided by seconds, multiplied by 60, gives litres per minute. Avoid burns and slippery floors. Repeat the measurement: supply pressure and settings affect it. A nominal product flow is not necessarily the flow in your bathroom.'),
('Use the right energy factor', 'Heat demand equals litres × temperature rise × 0.001163 kWh. Divide by useful heat delivered per unit of input energy. A factor of 1 is an illustrative direct-heating case, not a measured system efficiency. Use an appropriate factor for the actual equipment; hot-water heat-pump performance is not necessarily its space-heating rating. Distribution and storage losses are excluded.'),
('Check compatibility before reducing flow', 'Some instantaneous water heaters require minimum flow, and low-pressure arrangements may restrict which fittings can be used. Read both showerhead and heater instructions. Do not lower stored-water temperature or alter hygiene cycles because this calculator uses a lower mixed shower temperature; those are different settings.'),
('Compare variable costs honestly', 'Enter only the variable water, wastewater and energy rates in one currency. Standing charges remain outside the calculation. Equal duration and mixed-water temperature are assumed. If a lower flow makes you shower longer, update the minutes too. Payback does not include installation, maintenance or financing.')], [('Does mixed shower temperature set the storage tank?', 'No. Mixed outlet temperature and safe hot-water storage are different. Follow system hygiene requirements.'), ('Can a water-saving head fit any heater?', 'No. Minimum-flow and fitting requirements must be checked for the actual system.')]),
('keep-warm-working-from-home', 'Keep warm while working from home', 'Compare personal warmth and room heating for home working. Calculate electricity from actual use and keep ventilation, moisture and safety in view.', 'Keeping a person warm and heating the fabric of a room are different jobs. A low-wattage product does not automatically do both.', [
('Start with the workspace', 'Move away from a cold pane or a draught where possible. Add clothing and floor insulation under your feet without blocking vents or creating trip hazards. Check the existing heating schedule and whether furniture obstructs a radiator. These reversible changes can improve comfort before another appliance is needed.'),
('Compare equal tasks', 'A heated throw warms a person; a fan heater warms air. Comparing rated watts alone does not establish equal comfort. An illustrative 100 W for four hours at 0.35 per kWh costs 0.14 in the chosen currency; 2,000 W for the same time costs 2.80. A thermostatic heater may cycle, so measured whole-session kWh is better than assuming full power throughout.'),
('Keep the room healthy', 'Personal warmth does not prevent cold walls, condensation or frost damage. Maintain suitable room conditions, ventilate appropriately and monitor humidity, especially in occupied rooms. A blanket must not conceal a heating fault that needs repair. Needs differ for people with limited movement or heat sensitivity.'),
('Use electrical warmth safely', 'Follow the specific product’s instructions on folding, moisture, cleaning, unattended use and placement. Do not use damaged cables or improvise repairs. Check local electrical compatibility and safety instructions before buying. For people with reduced temperature sensation, establish suitability rather than simply choosing a hotter setting.')], [('Can a heated blanket replace all room heating?', 'No. Personal warmth does not adequately heat cold building surfaces or provide frost protection.'), ('Is a lower wattage always cheaper?', 'At equal run time it uses less electricity, but it may provide a different service. Compare the task and actual use.')]),
('fairy-lights-electricity-cost', 'Fairy lights and timer electricity costs', 'Calculate seasonal lighting costs from watts and hours. Include timer standby consumption and check whether shorter lighting hours actually save money.', 'Count the power of the whole set, not just the number of lamps. A timer has its own energy cost.', [
('Find the actual input power', 'The maximum output rating on a power supply is not necessarily the consumption of the connected lights. Use the maker’s input-power specification or a meter suitable for small loads. A full-day measurement captures both lighting and standby. Do not add power twice if a measurement already includes an integrated timer.'),
('Include the timer', 'This calculator compares the same lights with and without an added timer. It assumes the timer consumes its stated power continuously for 24 hours a day. Savings can be negative when little lighting time is avoided. The timer purchase price is not deducted; recovering it needs enough positive savings over the intended use.'),
('Keep or replace?', 'LEDs often use less power than old filament lights for a similar purpose, but a purchase decision needs both sets’ actual consumption and the full replacement cost. A tiny seasonal saving alone may not justify replacing working lights. Changing hours can be the more direct first step.'),
('Indoor and outdoor ratings', 'The lights, power supply, connectors and timer must all be approved for their intended location. An outdoor string does not make its indoor power supply weatherproof. Follow instructions for water exposure, mounting and distance from combustible materials. Replace damaged equipment; a timer does not make an unsafe installation safe.')], [('Does a timer always save electricity?', 'No. Its additional consumption can exceed the energy saved by switching the lights off sooner.'), ('Is the power-supply maximum the actual consumption?', 'Not necessarily. Use actual set input power or a suitable measurement.')])],
'it': [
('valvole-termostatiche-smart-convengono', 'Valvole termostatiche smart: convengono?', 'Verifica attacco, abitudini e costo totale delle valvole smart. Calcola il tempo di recupero con ipotesi personali, senza percentuali di risparmio garantite.', 'La programmazione può evitare di scaldare stanze vuote. Una testina smart non produce calore a minor costo: conta ciò che cambia nelle tue abitudini.', [
('Prima le abitudini, poi la connessione', 'Se regoli già il riscaldamento in base alla presenza, il beneficio aggiuntivo può essere limitato. Per orari fissi può bastare una testina programmabile senza app. Il controllo remoto può servire con orari variabili. I numeri della valvola indicano una temperatura obiettivo, non una potenza fissa: il massimo non scalda necessariamente più in fretta. Lascia libero il sensore da tende e mobili.'),
('Controlla impianto e attacco', 'Questa guida riguarda radiatori ad acqua con valvola termostatica. Pavimento radiante, radiatori elettrici e regolazione della caldaia richiedono soluzioni diverse. Identifica attacco e adattatore dai documenti di montaggio. Somma testine, centralina, adattatori, batterie e servizi obbligatori. Verifica se la programmazione funziona anche senza internet.'),
('Usa solo i costi influenzabili', 'Escludi acqua calda, quote fisse e consumi di altri alloggi dalla base di costo. Nel riscaldamento centralizzato il criterio di ripartizione può modificare il beneficio in bolletta. La percentuale di risparmio è una tua ipotesi, non un dato del prodotto. Un inverno mite non dimostra da solo che il dispositivo faccia risparmiare: confronta periodi e condizioni simili.'),
('Se sei in affitto', 'Verifica contratto e responsabilità locali, conserva le testine originali e segui le istruzioni. Non allentare il corpo della valvola attraversato dall’acqua. In caso di dubbio su compatibilità o intervento, rivolgiti al responsabile dell’immobile o a un tecnico.')], [('Il risparmio del 20% è garantito?', 'No. Dipende da regolazione precedente, presenza, edificio e ripartizione dei costi. Considera anche uno scenario senza risparmio.'), ('Ogni testina smart va bene per ogni radiatore?', 'No. Verifica tipo di valvola, attacco, adattatore e sistema di controllo.')]),
('termosifone-non-scalda', 'Termosifone freddo: cosa controllare prima', 'Un solo termosifone freddo o tutta la casa? Controlla orari, richiesta di calore e segnali di guasto prima di sfiatare o acquistare altri apparecchi.', 'Distingui una regolazione errata da un guasto dell’impianto prima di intervenire sul radiatore.', [
('Un radiatore o tutta la casa?', 'Controlla che il riscaldamento sia attivo nell’orario previsto e che il termostato richieda calore. Un radiatore può raffreddarsi correttamente quando la temperatura obiettivo è raggiunta. Se più radiatori rimangono freddi, verifica soltanto i comandi consentiti e segnala il problema: una testina nuova non ripara caldaia o circolazione.'),
('Descrivi il comportamento', 'Parte superiore fredda e gorgoglii possono suggerire aria, ma non costituiscono una diagnosi. Una parte inferiore fredda può dipendere da flusso o depositi. Confronta le stanze e annota quando accade. Una differenza di temperatura sulla superficie può essere normale durante lo scambio termico.'),
('Limiti dell’intervento domestico', 'Sfiata solo se istruzioni e responsabilità dell’impianto lo consentono. Può uscire acqua calda e la pressione può cambiare. Non aprire apparecchi a gas, smontare valvole, forzare perni o rabboccare ripetutamente un circuito che perde. Negli impianti condivisi la pressione può essere gestita dal manutentore. Perdite, errori e cali ripetuti di pressione richiedono un tecnico.'),
('Prepara una segnalazione utile', 'Annota stanze interessate, impostazioni, orari, rumori e codici visibili. Odore di gas, allarme monossido o pericolo immediato richiedono di allontanarsi e seguire le indicazioni locali di emergenza, senza aspettare questa verifica. Un termoventilatore non risolve la causa del guasto.')], [('Bisogna sfiatare ogni radiatore freddo?', 'No. Verifica prima richiesta di calore e orari. Lo sfiato va valutato per quel sistema e quel sintomo.'), ('Una valvola smart risolve il problema?', 'Non ripara guasti a caldaia, circolazione o circuito idraulico. Individua prima la causa.')]),
('spifferi-finestre-casa-affitto', 'Spifferi dalle finestre in affitto', 'Distingui gli spifferi da una superficie vetrata fredda. Controlla guarnizioni, ventilazione e responsabilità prima di applicare materiali isolanti.', 'Sentire freddo vicino al vetro non dimostra che la guarnizione perda. La causa determina il rimedio.', [
('Individua la provenienza senza fiamme', 'A finestra chiusa, osserva un fazzoletto leggero vicino al telaio in una giornata ventosa. È solo un indizio, non una prova di tenuta. L’aria raffreddata dal vetro può scendere e sembrare uno spiffero anche con guarnizioni integre. Cerca danni visibili e verifica la chiusura senza forzare la ferramenta.'),
('Non chiudere le aperture previste', 'Prese d’aria, aperture per la combustione e ventilazione meccanica devono restare funzionanti. Tenuta delle finestre e ricambio d’aria sono due compiti diversi. Una guarnizione danneggiata può richiedere il profilo corretto, non uno strato adesivo più spesso. Il materiale sbagliato può impedire la chiusura o danneggiare i meccanismi.'),
('Concorda prima la riparazione', 'In affitto documenta danni e fessure e verifica contratto e norme locali prima di modificare telai o ferramenta. Non si applicano automaticamente all’Italia le regole tedesche delle fonti. Evita lavori esterni in altezza. Una finestra fuori allineamento va valutata da chi è responsabile della manutenzione.'),
('Tende: comfort e umidità', 'Una tenda può migliorare il comfort percepito, ma non ripara una perdita. Non coprire valvole o ostacolare il calore del radiatore. Controlla la condensa nascosta dietro il tessuto. Misura l’umidità e osserva le superfici fredde dopo le modifiche, prima di aggiungere altri materiali.')], [('Il vetro freddo dimostra una perdita?', 'No. Il vetro può raffreddare l’aria e creare una corrente discendente senza una fessura.'), ('Posso sigillare tutte le aperture?', 'No. Ventilazione prevista e aperture per la combustione devono rimanere funzionanti.')]),
('abbassare-riscaldamento-notte', 'Abbassare il riscaldamento di notte?', 'Valuta la riduzione notturna in base a edificio e impianto. Considera tempi di ripresa, comfort e umidità invece di scegliere una temperatura universale.', 'Una temperatura inferiore può ridurre le dispersioni, ma l’orario utile dipende dall’abitazione e dall’impianto.', [
('Quanto reagisce velocemente la casa?', 'I radiatori in una stanza reattiva si comportano diversamente da un pavimento radiante lento. Una casa ben isolata può raffreddarsi poco durante la notte, limitando il vantaggio di una forte riduzione. Pompe di calore e regolazioni climatiche possono perdere efficienza se la ripresa richiede acqua molto più calda. Segui le indicazioni dell’installatore.'),
('Ridurre non significa spegnere tutto', 'Mantieni protezione antigelo e condizioni adatte agli occupanti. Considera persone vulnerabili, pareti esterne fredde e problemi di umidità. Quando l’aria si raffredda, l’umidità relativa aumenta anche senza aggiungere acqua. Una stanza apparentemente asciutta non dimostra che le superfici nascoste siano al sicuro.'),
('Confronta con piccoli cambiamenti', 'Registra temperatura serale e mattutina, umidità, comfort e consumi per giorni confrontabili. Annota presenza e clima esterno. Modifica un parametro alla volta. Una bolletta inferiore in giornate più miti non dimostra l’effetto della programmazione.'),
('Controlla la ripresa mattutina', 'Se la stanza torna confortevole troppo lentamente, anticipa l’avvio o riduci l’abbassamento. Evita di compensare un programma inadatto con un apparecchio elettrico costoso. Regolazione centrale e comandi di stanza devono collaborare: consulta le istruzioni se sembrano contrastarsi.')], [('Esiste una temperatura notturna giusta per tutti?', 'No. Contano edificio, umidità, occupanti e velocità di risposta dell’impianto.'), ('Una pompa di calore va sempre spenta di notte?', 'No. Impostazioni più stabili possono essere efficienti. Segui indicazioni specifiche e misura il risultato.')]),
('costo-doccia-calcolatore', 'Quanto costa una doccia? Calcolatore', 'Calcola acqua ed energia della doccia con portata, durata e tariffa personali. Confronta un soffione a basso flusso e verifica prima la compatibilità.', 'Misura la portata prima di cambiare accessori. Durata e flusso influenzano sia l’acqua utilizzata sia l’energia per scaldarla.', [
('Misura la portata reale', 'Se puoi farlo in sicurezza, raccogli acqua alla normale regolazione per un intervallo misurato. Litri raccolti divisi per secondi, moltiplicati per 60, danno litri al minuto. Evita ustioni e pavimenti scivolosi. Ripeti: pressione e regolazioni possono cambiare il valore. La portata dichiarata non è necessariamente quella del tuo bagno.'),
('Scegli il fattore energetico corretto', 'Il calore richiesto è litri × aumento di temperatura × 0,001163 kWh. Dividi per il calore utile fornito per unità di energia acquistata. Il fattore 1 è un esempio di riscaldamento diretto, non un rendimento misurato. La prestazione di una pompa di calore per acqua calda non coincide necessariamente con quella per riscaldamento. Perdite di distribuzione e accumulo sono escluse.'),
('Verifica scaldacqua e soffione', 'Alcuni scaldacqua istantanei richiedono una portata minima; sistemi a bassa pressione possono limitare gli accessori utilizzabili. Leggi entrambe le istruzioni. Non abbassare la temperatura dell’accumulo né modificare cicli igienici perché il calcolatore usa una temperatura inferiore dell’acqua miscelata: sono impostazioni diverse.'),
('Confronta le quote variabili', 'Inserisci tariffe variabili di acqua, scarico ed energia nella stessa valuta. Le quote fisse non cambiano e sono escluse. Si presume uguale durata e temperatura miscelata. Se con meno flusso fai una doccia più lunga, aggiorna i minuti. Il recupero del costo non include installazione, manutenzione o finanziamento.')], [('La temperatura della doccia vale per il serbatoio?', 'No. Acqua miscelata in uscita e accumulo igienicamente sicuro sono diversi. Rispetta le prescrizioni dell’impianto.'), ('Un soffione a basso flusso va bene con ogni scaldacqua?', 'No. Verifica portata minima e requisiti degli accessori del sistema effettivo.')]),
('stare-caldi-lavoro-da-casa', 'Stare al caldo lavorando da casa', 'Confronta calore personale e riscaldamento della stanza. Stima i consumi reali senza dimenticare ventilazione, umidità e uso sicuro degli apparecchi.', 'Scaldare una persona e scaldare le superfici della stanza sono compiti diversi. Un prodotto poco potente non svolge automaticamente entrambi.', [
('Comincia dalla postazione', 'Se possibile allontanati da vetri freddi e correnti. Aggiungi strati di abbigliamento e isolamento sotto i piedi senza coprire prese d’aria o creare ostacoli. Verifica programma di riscaldamento e mobili davanti ai radiatori. Questi interventi reversibili possono migliorare il comfort prima di un acquisto.'),
('Confronta compiti equivalenti', 'Una coperta riscaldata scalda la persona; un termoventilatore scalda l’aria. I watt nominali non dimostrano comfort equivalente. Esempio ipotetico: 100 W per quattro ore a 0,35 per kWh costano 0,14 nella valuta scelta; 2.000 W per lo stesso tempo costano 2,80. Un apparecchio termostatato può funzionare a cicli: meglio misurare i kWh dell’intera sessione.'),
('Mantieni condizioni sane nella stanza', 'Il calore personale non evita pareti fredde, condensa o danni da gelo. Mantieni condizioni adatte, ventila correttamente e controlla l’umidità nelle stanze occupate. Una coperta non deve nascondere un guasto al riscaldamento. Le esigenze cambiano per chi si muove poco o percepisce meno il calore.'),
('Segui le istruzioni di sicurezza', 'Rispetta le indicazioni su pieghe, umidità, pulizia, uso senza sorveglianza e posizione. Non usare cavi danneggiati né improvvisare riparazioni. Prima di comprare controlla compatibilità elettrica e istruzioni locali. Per chi ha sensibilità termica ridotta verifica l’idoneità, senza scegliere semplicemente una temperatura più alta.')], [('Una coperta elettrica sostituisce tutto il riscaldamento?', 'No. Non scalda adeguatamente le superfici fredde né garantisce protezione antigelo.'), ('Meno watt significa sempre meno spesa?', 'A parità di durata consuma meno elettricità, ma può offrire un servizio diverso. Confronta uso e obiettivo.')]),
('consumo-luci-natalizie-timer', 'Luci natalizie: consumi e timer', 'Calcola il costo delle luci da watt e ore. Includi il consumo del timer e verifica se ridurre la durata di accensione fa davvero risparmiare energia.', 'Conta la potenza dell’intera catena, non il numero di lampadine. Anche un timer consuma energia.', [
('Trova la potenza effettiva', 'La potenza massima in uscita dall’alimentatore non coincide necessariamente con il consumo delle luci collegate. Usa la potenza assorbita dichiarata o un misuratore adatto a piccoli carichi. Una misura sull’intera giornata include accensione e standby. Non sommare due volte il timer integrato se la misura lo comprende già.'),
('Includi il timer aggiuntivo', 'Il calcolatore confronta le stesse luci con e senza un timer aggiuntivo. Presume che il timer assorba la potenza indicata per tutte le 24 ore. Il risparmio può essere negativo se le ore evitate sono poche. Il prezzo del timer non è sottratto: per recuperarlo servono risparmi positivi sufficienti nel periodo di utilizzo.'),
('Tenere o sostituire?', 'I LED spesso consumano meno delle vecchie lampadine per un uso simile, ma servono consumi reali e prezzo completo della sostituzione. Un piccolo risparmio stagionale non giustifica automaticamente eliminare luci funzionanti. Ridurre le ore può essere il primo intervento più diretto.'),
('Interno ed esterno', 'Luci, alimentatore, connessioni e timer devono essere approvati per il luogo di utilizzo. Una catena da esterno non rende impermeabile un alimentatore da interno. Segui istruzioni su acqua, fissaggio e distanza da materiali combustibili. Sostituisci apparecchi danneggiati: un timer non rende sicuro un impianto inadatto.')], [('Il timer fa sempre risparmiare?', 'No. Il consumo aggiuntivo può superare l’energia risparmiata spegnendo prima le luci.'), ('La potenza massima dell’alimentatore è il consumo?', 'Non necessariamente. Usa la potenza assorbita dall’insieme o una misura adeguata.')])]
}
