import {products,href} from './catalog.mjs';
import {engines,csvOut,puzzle,csv} from './core.mjs';
import {projects} from './projects.mjs';
import {translator,displayNumber,pageURL} from './i18n.mjs';
const language=document.body.dataset.locale||'en';
const dictionary=await fetch(new URL('./locales/'+language+'.json',import.meta.url)).then(r=>{if(!r.ok)throw Error('Language pack unavailable');return r.json();});
const t=translator(dictionary,language);
const product=products.find(p=>p.id===document.body.dataset.product);
const $=id=>document.getElementById(id);
const el=(tag,text,attrs={})=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=t(text);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,['aria-label','placeholder'].includes(k)?t(v):v);return n;};
const button=(text,fn)=>{const b=el('button',text,{type:'button'});b.onclick=fn;return b;};
let latest=null;let protectedValues=new Set();
function message(text,error=false){$('status').textContent=t(text);$('status').className=error?'error':'notice';}
function download(name,content,mime='text/plain'){const blob=new Blob([content],{type:mime+';charset=utf-8'}),a=el('a',undefined,{href:URL.createObjectURL(blob),download:name});a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function table(columns,rows,parent){parent.append(el('small','Scroll horizontally to see all columns.',{class:'scroll-hint'}));const wrap=el('div',undefined,{class:'table-scroll',tabindex:'0'}),tableNode=el('table'),head=el('thead'),tr=el('tr');columns.forEach(c=>tr.append(el('th',c,{scope:'col'})));head.append(tr);tableNode.append(head);const body=el('tbody');rows.forEach(r=>{const row=el('tr');r.forEach(c=>{const cell=el('td');const raw=String(c??'');cell.textContent=displayNumber(protectedValues.has(raw)?c:t(raw),language);row.append(cell);});body.append(row);});tableNode.append(body);wrap.append(tableNode);parent.append(wrap);}
function render(r){latest=r;protectedValues=new Set();for(const f of product.fields){const value=$('field-'+f.key)?.value;if(value){protectedValues.add(value);if(f.type==='csv')try{csv(value).forEach(row=>Object.values(row).forEach(v=>protectedValues.add(v)));}catch{}}}const out=$('output');out.replaceChildren(el('h2',r.title));if(r.columns)table(r.columns,r.rows,out);if(r.text)out.append(el('pre',r.text,{class:'prose-output'}));for(const note of r.notes||[])out.append(el('p',note,{class:'method'}));for(const [label,url]of r.links||[])out.append(el('a',label,{href:product.id==='launchdesk'&&language==='en'?'https://baipiaoji.com/en/advertise':url,class:'text-link'}));const actions=el('div',undefined,{class:'actions no-print'});if(r.columns)actions.append(button('Export CSV',()=>download(product.id+'.csv',csvOut([r.columns.map(t),...r.rows.map(row=>row.map(v=>protectedValues.has(String(v))?v:t(v)))]),'text/csv')));actions.append(button('Export report',()=>download(product.id+'.json',JSON.stringify({...r,language,title:t(r.title),columns:r.columns?.map(t),rows:r.rows?.map(row=>row.map(v=>protectedValues.has(String(v))?v:t(v))),notes:r.notes?.map(t),text:t(r.text)},null,2),'application/json')),button('Print',()=>window.print()));if(r.download)actions.append(button('Download calendar (.ics)',()=>download(r.download.name,r.download.content,r.download.mime)));out.append(actions);message('Result ready. Review assumptions before using it.');}
const inputs=()=>Object.fromEntries(product.fields.map(f=>[f.key,$('field-'+f.key).value]));
function fill(values){for(const f of product.fields)if(typeof values[f.key]==='string')$('field-'+f.key).value=values[f.key];}
function forms(){const form=$('input-form');form.replaceChildren();for(const f of product.fields){const label=el('label',f.label,{for:'field-'+f.key}),group=el('div',undefined,{class:'field'});let input;if(f.type==='select'){input=el('select');f.options.forEach(([v,t])=>input.append(el('option',t,{value:v})));}else if(['csv','textarea'].includes(f.type)){input=el('textarea',undefined,{rows:f.type==='csv'?'7':'4',spellcheck:'false'});}else{input=el('input',undefined,{type:f.type,step:'any'});}input.id='field-'+f.key;input.name=f.key;input.value=f.value;group.append(label,input);if(f.type==='csv'){const upload=el('input',undefined,{type:'file',accept:'.csv,text/csv','aria-label':'Import '+f.label});upload.onchange=async()=>{try{const file=upload.files[0];if(file.size>300000)throw Error('CSV must be smaller than 300 KB.');input.value=await file.text();message('CSV loaded into this browser. Check its column names before running.');}catch(e){message(e.message,true);}};group.append(el('small','Keep the exact column headers shown in the example. Up to 1,500 rows.'),upload);}form.append(group);}const run=el('button','Generate result',{type:'submit',class:'primary'});form.append(run);form.onsubmit=e=>{e.preventDefault();try{render(engines[product.id](inputs()));}catch(err){message(err.message,true);}};form.append(button('Load fictional example',()=>{fill(Object.fromEntries(product.fields.map(f=>[f.key,f.value])));message('Fictional example loaded. It is not verified market data.');}));workspace();}
function workspace(){const box=$('workspace'),key='task-workbench:v1:'+product.id;const read=()=>{const data=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(data)?data:[];};const name=el('input',undefined,{placeholder:'e.g. September quote round','aria-label':'Saved version name',maxlength:'80'}),list=el('select',undefined,{'aria-label':'Saved versions'});const refresh=()=>{list.replaceChildren(el('option','Choose a saved version',{value:''}));try{read().forEach((x,i)=>list.append(el('option',x.name+' · '+x.at.slice(0,10),{value:String(i)})));}catch{message('Local storage is unavailable. Use Export inputs instead.');}};box.append(el('h2','Versions on this device'),el('p','Save explicitly; nothing is uploaded. Browser storage can be cleared. Keep a JSON backup.'),name,button('Save version',()=>{try{if(!name.value.trim())throw Error('Name this version first.');const versions=read();versions.unshift({name:name.value.trim(),at:new Date().toISOString(),values:inputs()});localStorage.setItem(key,JSON.stringify(versions.slice(0,20)));refresh();message('Saved on this device (up to 20 versions).');}catch(e){message(e.message,true);}}),list,button('Load version',()=>{try{const entry=read()[Number(list.value)];if(list.value===''||!entry)throw Error('Choose a saved version.');fill(entry.values);message('Saved inputs loaded. Generate a fresh result to review them.');}catch(e){message(e.message,true);}}),button('Export inputs',()=>download(product.id+'-inputs.json',JSON.stringify({version:1,product:product.id,values:inputs()},null,2),'application/json')));
const file=el('input',undefined,{type:'file',accept:'.json,application/json','aria-label':'Restore exported inputs'});file.onchange=async()=>{try{if(file.files[0].size>2000000)throw Error('Backup is too large.');const data=JSON.parse(await file.files[0].text());if(data.version!==1||data.product!==product.id||!data.values||typeof data.values!=='object')throw Error('Choose an input backup exported by this tool.');fill(data.values);message('Backup restored into the form; save explicitly to keep it.');}catch(e){message(e.message,true);}};box.append(file,button('Clear saved versions',()=>{if(window.confirm('Remove this tool’s saved versions from this browser?')){try{localStorage.removeItem(key);refresh();message('Local saved versions cleared.');}catch(e){message(e.message,true);}}}));refresh();}
function board(p,parent,editable=true){const grid=el('div',undefined,{class:'puzzle-grid',role:'group','aria-label':'4 by 4 number puzzle'});p.grid.forEach((v,i)=>{const input=el('input',undefined,{'aria-label':`Row ${Math.floor(i/4)+1}, column ${i%4+1}`,inputmode:'numeric',maxlength:'1',pattern:'[1-4]'});input.value=v||'';input.readOnly=Boolean(v)||!editable;if(v)input.className='given';grid.append(input);});parent.append(grid);return grid;}
function puzzles(){const form=$('input-form'),out=$('output');$('workspace').hidden=true;const seed=el('input',undefined,{id:'seed','aria-label':'Puzzle seed',maxlength:'80'});seed.value=new Date().toISOString().slice(0,10);form.append(el('label','Puzzle date or custom seed',{for:'seed'}),seed,el('p','Use digits 1–4 once in each row, column and 2 × 2 box. Every generated puzzle has one solution.'));
if(product.kind==='puzzle'){let current,grid,start;const generate=()=>{current=puzzle(seed.value||'daily');out.replaceChildren(el('h2','Your daily puzzle'));grid=board(current,out);start=Date.now();out.append(button('Check my solution',()=>{const complete=[...grid.querySelectorAll('input')].every((x,i)=>Number(x.value)===current.solution[i]);message(complete?'Solved! '+Math.floor((Date.now()-start)/1000)+' seconds.':'Keep going: some cells are empty or incorrect.',!complete);}),button('Copy result',async()=>{const solved=[...grid.querySelectorAll('input')].every((x,i)=>Number(x.value)===current.solution[i]);const text=`PuzzleClub · ${current.seed} · ${solved?'Solved':'In progress'}\n${pageURL(product,language)}`;try{await navigator.clipboard.writeText(text);message('Result copied.');}catch{download('puzzle-result.txt',text);}}));};form.append(button('Start puzzle',generate));generate();}
if(product.kind==='classroom'){const count=el('input',undefined,{type:'number',min:'1',max:'12',value:'4',id:'count'});form.append(el('label','Number of puzzles (1–12)',{for:'count'}),count);const generate=()=>{const n=Number(count.value);if(!Number.isInteger(n)||n<1||n>12)return message('Choose 1–12 puzzles.',true);out.replaceChildren(el('h2','Number puzzle worksheet'),el('p','Name: ____________________    Date: ______________'));const sheets=el('div',undefined,{class:'worksheet'}),answers=el('section',undefined,{class:'answer-sheet'});answers.append(el('h2','Teacher answer sheet'));const answergrid=el('div',undefined,{class:'worksheet'});for(let i=0;i<n;i++){const p=puzzle(seed.value+'-'+i),item=el('section'),answer=el('section');item.append(el('h3','Puzzle '+(i+1)));board(p,item,false);answer.append(el('h3','Answer '+(i+1)));board({...p,grid:p.solution},answer,false);sheets.append(item);answergrid.append(answer);}answers.append(answergrid);out.append(sheets,answers,el('p','Original generated worksheets. Permission: print, adapt and distribute these generated puzzles for personal and classroom use, including paid teaching. No third-party artwork is included.'),button('Print worksheet and answers',()=>window.print()));message('Worksheet ready. The answer sheet starts on a new printed page.');};form.append(button('Generate worksheet',generate));generate();}
if(product.kind==='embed'){const title=el('input',undefined,{value:t('Daily number puzzle'),id:'embed-title',maxlength:'60'});form.append(el('label','Embed title',{for:'embed-title'}),title);form.append(button('Build embed',()=>{const p=puzzle(seed.value),safe=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const page=`<!doctype html><html lang="${language==='zh'?'zh-Hans':language}"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${safe(title.value)}</title><style>body{font:16px system-ui;padding:18px;color:#182440}#g{display:grid;grid-template-columns:repeat(4,48px);gap:3px}input{width:44px;height:44px;text-align:center;font:22px system-ui}button{margin-top:15px;padding:10px}</style><h2>${safe(title.value)}</h2><p>${safe(t('Use 1–4 once per row, column and 2×2 box.'))}</p><div id="g">${p.grid.map((v,i)=>`<input aria-label="Row ${Math.floor(i/4)+1} column ${i%4+1}" inputmode="numeric" maxlength="1" ${v?`value="${v}" readonly`:''}>`).join('')}</div><button id="check">${safe(t('Check'))}</button><p id="status" aria-live="polite"></p><script>document.getElementById('check').onclick=()=>{const a=${JSON.stringify(p.solution)};document.getElementById('status').textContent=[...document.querySelectorAll('input')].every((x,i)=>Number(x.value)===a[i])?${JSON.stringify(t('Solved!'))}:${JSON.stringify(t('Keep going.'))}};<\/script></html>`;const code=`<iframe title="${safe(title.value)}" sandbox="allow-scripts" style="width:100%;max-width:420px;height:460px;border:1px solid #ddd" srcdoc="${safe(page)}"></iframe>`;out.replaceChildren(el('h2','Working embed'));const preview=el('iframe',undefined,{title:'Puzzle preview',sandbox:'allow-scripts',class:'embed-preview'});preview.srcdoc=page;out.append(preview,el('textarea',code,{rows:'8',readonly:'', 'aria-label':'Copyable iframe code'}),button('Download embed code',()=>download('puzzle-embed.html',code,'text/html')),el('p','Self-contained HTML: no tracking, subscription, host callback or library dependency. You may use and adapt this original generated embed on commercial websites. Your CMS must allow sandboxed iframes; test after pasting. Answers are in the code, so this is not an exam security system.'));message('Embed ready. Copy or download the iframe code.');}));}
}
function sql(){const form=$('input-form');$('workspace').hidden=true;const pick=el('select',undefined,{id:'project'});projects.forEach((p,i)=>pick.append(el('option',p.name,{value:i})));const brief=el('p'),schema=el('p',undefined,{class:'method'}),query=el('textarea',undefined,{rows:'10',id:'query',spellcheck:'false'});form.append(el('label','Project',{for:'project'}),pick,brief,schema,el('label','Your SQLite query',{for:'query'}),query);const load=()=>{const p=projects[pick.value];brief.textContent=t(p.brief);schema.textContent=p.schema;query.value=p.starter;};pick.onchange=load;load();form.append(button('Run query',()=>{if(query.value.length>20000)return message('Keep SQL below 20,000 characters.',true);const p=projects[pick.value],worker=new Worker(new URL('./sql-worker.js',import.meta.url));const timer=setTimeout(()=>{worker.terminate();message('Query stopped after 5 seconds. Simplify it and try again.',true);},5000);message('Running SQLite locally…');worker.onerror=()=>{clearTimeout(timer);worker.terminate();message('SQLite could not load. Reload the page and try again.',true);};worker.onmessage=({data})=>{clearTimeout(timer);worker.terminate();if(!data.ok)return message(data.error,true);const last=data.result.at(-1);if(!last)return message('Query returned no result table.',true);const equal=JSON.stringify(data.result)===JSON.stringify(data.expected);render({title:equal?'Project passed':'Query result',columns:last.columns,rows:last.values,notes:[equal?'Your columns, row order and values match the expected result.':'Result does not yet match the expected columns, row order and values. Check the project brief.','Each run starts a fresh fictional SQLite database. No query is sent to a server. Passing these fixtures does not prove correctness for all possible data.']});};worker.postMessage({setup:p.setup,answer:p.answer,query:query.value});}),button('Show explained solution',()=>{const p=projects[pick.value];render({title:'Explained solution',text:p.answer,notes:[p.explanation]});}),button('Export query',()=>download('querysprint-'+projects[pick.value].id+'.sql',query.value,'text/plain')));}
if(product){try{if(product.kind==='sql')sql();else if(product.kind)puzzles();else forms();}catch(e){message('Could not initialize: '+e.message,true);}}

function sharing(){const link=$('copy-page');if(link)link.onclick=async()=>{try{await navigator.clipboard.writeText(pageURL(product,language));message('Link copied.');}catch{download('tool-link.txt',pageURL(product,language));}};const widget=$('create-widget');if(widget)widget.onclick=async()=>{try{const r=await fetch(new URL('./widgets/'+language+'/'+product.id+'.txt',import.meta.url));if(!r.ok)throw Error('Widget download unavailable');const html=await r.text();const safe=v=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const code='<iframe title="'+safe(product.name)+'" sandbox="allow-scripts allow-downloads" style="width:100%;height:700px;border:1px solid #ccc" srcdoc="'+safe(html)+'"></iframe>';const holder=$('widget-code');holder.replaceChildren(el('textarea',code,{rows:'6',readonly:'','aria-label':'Copyable embed code'}),button('Download standalone tool',()=>download(product.id+'-'+language+'.html',html,'text/html')));message('Embed code ready.');}catch(e){message(e.message,true);}};}
if(product)sharing();
