import {chromium} from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import http from 'node:http';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {products,sites} from './catalog.mjs';
import {siteLanguages,route,translator} from './i18n.mjs';
import {puzzle} from './core.mjs';
import {projects} from './projects.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),root=fs.mkdtempSync(path.join(os.tmpdir(),'workbench-test-'));
for(const site of Object.keys(sites))execFileSync(process.execPath,[path.join(here,'build.mjs'),'--site',site,'--out',path.join(root,site)]);
let current='agi';
const server=http.createServer((req,res)=>{try{let pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(!path.extname(pathname))pathname+='.html';const file=path.resolve(root,current,'.'+pathname);if(!file.startsWith(path.resolve(root,current)+path.sep))throw Error('Bad path');const ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.wasm':'application/wasm'})[ext]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('Not found');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;let browser;
try{browser=await chromium.launch({headless:true,...(process.env.WORKBENCH_CHROMIUM?{executablePath:process.env.WORKBENCH_CHROMIUM,args:["--no-sandbox","--disable-dev-shm-usage","--single-process"]}:{})});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const p of products)for(const lang of siteLanguages[p.site]){current=p.site;const s=sites[p.site];const t=translator(JSON.parse(fs.readFileSync(path.join(here,'locales',lang+'.json'))),lang);await page.goto(origin+route(p.site,lang,p.id));await page.waitForSelector('#input-form button');if(!p.kind){await page.getByRole('button',{name:t('Generate result'),exact:true}).click();await page.waitForSelector('#output table, #status.error');if(await page.locator('#status.error').count())throw Error(p.id+' '+lang+': '+await page.locator('#status').textContent());assert.equal(await page.locator('#status.error').count(),0,p.id);const name=page.getByRole('textbox',{name:t('Saved version name')});await name.fill('Test version');await page.getByRole('button',{name:t('Save version'),exact:true}).click();assert.equal(await page.locator('#status').textContent(),t('Saved on this device (up to 20 versions).'));const download=page.waitForEvent('download');await page.getByRole('button',{name:t('Export CSV'),exact:true}).click();assert.ok((await download).suggestedFilename().endsWith('.csv'));}
else if(p.kind==='sql'){for(let i=0;i<projects.length;i++){await page.locator('#project').selectOption(String(i));await page.locator('#query').fill(projects[i].answer);await page.getByRole('button',{name:t('Run query'),exact:true}).click();await page.waitForFunction(expected=>document.querySelector('#output h2')?.textContent===expected,t('Project passed'));await page.locator('#output h2').evaluate(n=>n.textContent='Ready');}}
else if(p.kind==='puzzle'){const seed=await page.locator('#seed').inputValue(),solution=puzzle(seed).solution;const inputs=page.locator('.puzzle-grid input');for(let i=0;i<16;i++)if(await inputs.nth(i).getAttribute('readonly')===null)await inputs.nth(i).fill(String(solution[i]));await page.getByRole('button',{name:t('Check my solution')}).click();assert.match(await page.locator('#status').textContent(),lang==='zh'?/完成！/:/Solved!/);}
else if(p.kind==='classroom'){assert.equal(await page.locator('.worksheet .puzzle-grid').count(),8);}
else if(p.kind==='embed'){await page.getByRole('button',{name:t('Build embed')}).click();const frame=page.frameLocator('iframe');await frame.getByRole('button',{name:t('Check'),exact:true}).click();assert.equal(await frame.locator('#status').textContent(),t('Keep going.'));assert.match(await page.locator('#output textarea').inputValue(),/sandbox="allow-scripts"/);}
await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile overflow: '+p.id);await page.setViewportSize({width:1280,height:900});console.log('UI OK '+lang+' '+p.id);}
assert.deepEqual(errors,[]);
for(const [site,lang,id]of [['bpj','zh','quotawatch-pro'],['eco','de','billlens'],['eco','it','appliancepayback'],['tds','de','displayfit']]){current=site;const t=translator(JSON.parse(fs.readFileSync(path.join(here,'locales',lang+'.json'))),lang);await page.goto(origin+route(site,lang,id));await page.getByRole('button',{name:t('Generate result'),exact:true}).click();await page.getByRole('button',{name:t('Create embed code'),exact:true}).click();const code=await page.locator('#widget-code textarea').inputValue();assert.match(code,/sandbox="allow-scripts allow-downloads"/);await page.evaluate(code=>{const holder=document.createElement('div');holder.id='widget-test';holder.innerHTML=code;document.body.append(holder);},code);const frame=page.frameLocator('#widget-test iframe');await frame.getByRole('button',{name:t('Generate result'),exact:true}).click();await frame.locator('#out').filter({hasText:/./}).waitFor();assert.equal(await frame.locator('#out table').count(),1,'Embed failed: '+await frame.locator('#out').textContent());if(site==='eco'&&id==='billlens'){assert.match(await page.locator('#output table').textContent(),/1\.004,00/);await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'billlens-de-mobile.png'),fullPage:true});console.log('Screenshot: '+path.join(root,'billlens-de-mobile.png'));await page.setViewportSize({width:1280,height:900});}console.log('EMBED OK '+lang+' '+id);}
assert.deepEqual(errors,[]);console.log('All 51 localized browser flows and 4 standalone embeds passed.');
}finally{await browser?.close();await new Promise(r=>server.close(r));}
