import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {products,sites,groups,href} from './catalog.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));
const args=process.argv.slice(2),site=args[args.indexOf('--site')+1],out=path.resolve(args[args.indexOf('--out')+1]||'');
if(!sites[site]||!args.includes('--out'))throw Error('Usage: node build.mjs --site bpj|agi|eco|tds --out OUTPUT');
const s=sites[site],esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset='/workbench-assets';
fs.mkdirSync(path.join(out,asset),{recursive:true});
for(const f of ['core.mjs','catalog.mjs','projects.mjs','app.mjs','style.css','sql-worker.js'])fs.copyFileSync(path.join(here,f),path.join(out,asset,f));
fs.mkdirSync(path.join(out,asset,'vendor'),{recursive:true});
for(const f of ['sql-wasm.js','sql-wasm.wasm'])fs.copyFileSync(path.join(here,'node_modules/sql.js/dist',f),path.join(out,asset,'vendor',f));
const hub=s.origin+s.prefix+s.suffix;
const shell=(title,description,url,body,id='')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | ${s.name}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${url}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta property="og:type" content="website"><link rel="stylesheet" href="${asset}/style.css">${id?`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"WebApplication",name:title,url,description,applicationCategory:"UtilitiesApplication",operatingSystem:"Web browser",isAccessibleForFree:true,offers:{"@type":"Offer",price:0,priceCurrency:"USD"},featureList:[description,"Exportable browser results"],isPartOf:{"@type":"WebSite",url:hub}}).replace(/</g,"\\u003c")}</script>`:''}</head><body data-site="${site}" data-product="${id}" style="--accent:${s.color}"><a class="skip" href="#main">Skip to content</a><header><a href="${s.origin}/">${s.name}</a><a href="${hub}">Tool workbench</a></header><main id="main">${body}</main><footer>${site==='tds'?'Independent collector tools. Not affiliated with POP MART. ':''}Browser-based tools · Your inputs stay in this browser. No account, cloud backup or paid membership is provided. <a href="${s.origin}/">Back to ${s.name}</a></footer>${id?`<script type="module" src="${asset}/app.mjs"></script>`:''}</body></html>`;
const urls=[];
function write(route,html){const file=path.join(out,route.replace(/^\//,'')+(route.endsWith('.html')?'':'.html'));fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,html);urls.push(s.origin+route);}
for(const p of products.filter(p=>p.site===site)){const body=`<p class="eyebrow">${esc(groups[p.group])} / Working edition 01</p><h1>${esc(p.name)}</h1><p class="intro">${esc(p.description)}</p><p class="scope">${esc(p.commercial||'Free working edition. Named workspaces and exports are local to your device. Team sync, automatic source monitoring and paid memberships are not available.')}</p><p class="scope">All prefilled business examples are fictional. Replace them with your own checked inputs.</p><noscript>This tool needs JavaScript to process data locally. Enable JavaScript to use it.</noscript><p id="status" role="status" aria-live="polite" class="notice">Ready. Choose your inputs and generate a result.</p><div class="layout"><section id="input-panel" class="panel" aria-label="Tool inputs"><h2>${p.kind==='sql'?'Project desk':p.kind?'Create & play':'Your inputs'}</h2><form id="input-form"></form></section><section class="panel" id="output" aria-label="Tool results"><h2>Your result</h2><p>Run the tool to see its output here. You can inspect, export or print the result.</p></section></div><section id="workspace" class="panel"></section><nav class="related" aria-label="Related tools"><h2>Continue your workflow</h2>${products.filter(x=>x.group===p.group&&x.id!==p.id).map(x=>`<a href="${href(x)}">${esc(x.name)}</a>`).join('')}<a href="https://agiscorecard.com/workbench">All 24 tools</a></nav>`;write(s.prefix+'/'+p.id+s.suffix,shell(p.name,p.description,href(p),body,p.id));}
const listed=site==='agi'?products:products.filter(p=>p.site===site);
const list=groups.map((g,i)=>{const entries=listed.filter(p=>p.group===i);return entries.length?`<section class="group-section"><h2>${esc(g)}</h2><ul class="product-list">${entries.map(p=>`<li><a href="${href(p)}">${esc(p.name)}</a><p>${esc(p.description)}</p></li>`).join('')}</ul></section>`:'';}).join('');
write(s.prefix+s.suffix,shell('Useful work. Inspectable results.','Practical browser tools for research, operations, energy, collecting and learning.',hub,`<p class="eyebrow">${site==='agi'?'8 directions / 24 tools':s.name+' / Tool workbench'}</p><h1>Useful work.<br>Inspectable results.</h1><p class="intro">Bring a real task. Compare inputs, check assumptions, and leave with a result you can use.</p><p class="scope">Free browser tools, original puzzles and an existing sponsored-placement checkout. Local versions are not cloud accounts. Only LaunchDesk currently offers a paid placement; no membership is on sale.</p>${list}<p><a href="https://agiscorecard.com/workbench">Explore all 24 tools across the four sites</a></p>`));
// Preserve existing sitemap entries; repeat builds do not accumulate duplicate URLs.
const sitemap=path.join(out,'sitemap.xml');let xml=fs.existsSync(sitemap)?fs.readFileSync(sitemap,'utf8'):'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>';
if(xml.includes('</urlset>')){const add=urls.filter(u=>!xml.includes('<loc>'+u+'</loc>')).map(u=>`<url><loc>${u}</loc></url>`).join('\n');fs.writeFileSync(sitemap,xml.replace('</urlset>',add+'\n</urlset>'));}else throw Error('Expected a URL sitemap at '+sitemap);
// Home entry is generated after each site's normal build so rebuilds retain discovery.
for(const home of site==='eco'?['index.html','en/index.html']:['index.html']){const file=path.join(out,home);if(fs.existsSync(file)){let html=fs.readFileSync(file,'utf8');html=html.replace(/<!-- task-workbench:start -->[\s\S]*?<!-- task-workbench:end -->/g,'');const entry=`<!-- task-workbench:start --><aside style="padding:24px;max-width:1100px;margin:24px auto;border-top:1px solid #ccc" aria-label="Practical tools"><a href="${hub}">Explore ${products.filter(p=>p.site===site).length} practical tools: ${products.filter(p=>p.site===site).slice(0,3).map(p=>esc(p.name)).join(', ')}${site==='agi'?' and more':''}</a><p>Browser tools with exportable results. Free working editions.</p></aside><!-- task-workbench:end -->`;html=html.replace(/<\/body>/i,entry+'</body>');fs.writeFileSync(file,html);}}
for(const fileName of ['llms.txt','llms-full.txt']){const file=path.join(out,fileName);let text=fs.existsSync(file)?fs.readFileSync(file,'utf8'):'';text=text.replace(/\n<!-- workbench:start -->[\s\S]*?<!-- workbench:end -->/g,'');text+='\n<!-- workbench:start -->\n## Practical browser tools\n'+products.filter(p=>p.site===site).map(p=>`- [${p.name}](${href(p)}): ${p.description}`).join('\n')+'\n<!-- workbench:end -->\n';fs.writeFileSync(file,text);}
if(site==='agi')for(const relative of ['ai-tools.html','zh/ai-tools.html']){const file=path.join(out,relative);if(fs.existsSync(file)){let html=fs.readFileSync(file,'utf8').replace(/<!-- studio-hub:start -->[\s\S]*?<!-- studio-hub:end -->/g,'');const block='<!-- studio-hub:start --><section style="padding:24px;max-width:1100px;margin:auto"><h2>Research, operations and learning workbench (English)</h2><ul>'+listed.filter(p=>p.site==='agi').map(p=>`<li><a href="${href(p)}">${esc(p.name)}</a> — ${esc(p.description)}</li>`).join('')+'</ul></section><!-- studio-hub:end -->';fs.writeFileSync(file,html.replace(/<\/body>/i,block+'</body>'));}}
fs.writeFileSync(path.join(out,asset,'manifest.json'),JSON.stringify({edition:1,site,urls},null,2));
console.log(`Built ${urls.length-1} tools and a hub for ${site}`);
