import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {products,sites,groups} from './catalog.mjs';
import {engines} from './core.mjs';
import {projects} from './projects.mjs';
import {languages,siteLanguages,route,pageURL,hubURL,translator,displayNumber} from './i18n.mjs';
import {formulas,referenceLinks} from './methods.mjs';
import {widgetHTML,escapeHTML as esc} from './widgets.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),args=process.argv.slice(2),site=args[args.indexOf('--site')+1];
if(!sites[site]||!args.includes('--out'))throw Error('Usage: node build.mjs --site bpj|agi|eco|tds --out OUTPUT');
const out=path.resolve(args[args.indexOf('--out')+1]),s=sites[site],asset='/workbench-assets',version='2026-09-19.2';
const dicts=Object.fromEntries(Object.keys(languages).map(l=>[l,JSON.parse(fs.readFileSync(path.join(here,'locales',l+'.json'),'utf8'))]));
const own=products.filter(p=>p.site===site),listed=site==='agi'?products:own,urls=[],records=[];
function put(rel,content){const file=path.join(out,rel.replace(/^\//,''));fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,content);}
for(const f of ['core.mjs','catalog.mjs','projects.mjs','i18n.mjs','app.mjs','style.css','sql-worker.js'])put(asset+'/'+f,fs.readFileSync(path.join(here,f)));
for(const l of Object.keys(languages))put(asset+'/locales/'+l+'.json',JSON.stringify(dicts[l]));
for(const f of ['sql-wasm.js','sql-wasm.wasm'])put(asset+'/vendor/'+f,fs.readFileSync(path.join(here,'node_modules/sql.js/dist',f)));
put(asset+'/vendor/sqljs-LICENSE.txt',fs.readFileSync(path.join(here,'node_modules/sql.js/LICENSE')));
const core=fs.readFileSync(path.join(here,'core.mjs'),'utf8');
const titleFor=(p,lang)=>dicts[lang]['title:'+p.id]||dicts.en['title:'+p.id];
const actualLang=(p,lang)=>siteLanguages[p.site].includes(lang)?lang:'en';
function related(p){const ids={'creatorops':['localebatch-qa'],'quotawatch-pro':['workflowcost'],'workflowcost':['quotawatch-pro'],'job-evidence':['querysprint-projects'],'evidencebrief':['agentfit'],'classroompuzzles':['puzzleclub'],'displayfit':['collectorledger']};return products.filter(x=>x.id!==p.id&&(x.group===p.group||(ids[p.id]||[]).includes(x.id)));}
function reference(p){return p.id==='dropcalendar'||p.id==='evidencewatch'?referenceLinks.calendar:p.kind==='sql'?referenceLinks.sql:p.kind?referenceLinks.embed:referenceLinks.csv;}
function table(r,lang,t){return `<small class="scroll-hint">${t('Scroll horizontally to see all columns.')}</small><div class="table-scroll" tabindex="0"><table><thead><tr>${r.columns.map(c=>`<th scope="col">${esc(t(c))}</th>`).join('')}</tr></thead><tbody>${r.rows.map(row=>`<tr>${row.map(c=>`<td>${esc(displayNumber(t(String(c??'')),lang))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function schema(p,lang,url,title,description,hub){const webpage={'@type':'WebPage','@id':url+'#page',url,name:title,description,inLanguage:languages[lang].tag,isPartOf:{'@type':'WebSite',name:s.name,url:s.origin}};const result=[webpage];if(p)result.push({'@type':'WebApplication','@id':url+'#tool',name:p.name,alternateName:title,url,description,inLanguage:languages[lang].tag,applicationCategory:p.kind?'EducationalApplication':'UtilitiesApplication',operatingSystem:'Web browser',isAccessibleForFree:true,offers:{'@type':'Offer',price:0,priceCurrency:'USD'},featureList:[description],softwareVersion:version,mainEntityOfPage:{'@id':url+'#page'}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:s.name,item:s.origin+'/'},{'@type':'ListItem',position:2,name:translator(dicts[lang],lang)('Tool workbench'),item:hub},{'@type':'ListItem',position:3,name:p.name,item:url}]});else result.push({'@type':'ItemList',itemListElement:listed.map((x,i)=>({'@type':'ListItem',position:i+1,name:x.name,url:pageURL(x,actualLang(x,lang))}))});return JSON.stringify({'@context':'https://schema.org','@graph':result}).replace(/</g,'\\u003c');}
function shell(p,lang,title,description,body){const t=translator(dicts[lang],lang),id=p?.id||'',url=s.origin+route(site,lang,id),hub=hubURL(site,lang),titleTag=p?((title+' | '+p.name).length<=74?title+' | '+p.name:title):title+' | '+s.name;const alternatives=siteLanguages[site].map(l=>`<link rel="alternate" hreflang="${languages[l].tag}" href="${s.origin+route(site,l,id)}">`).join('\n')+`\n<link rel="alternate" hreflang="x-default" href="${s.origin+route(site,siteLanguages[site][0],id)}">`;const nav=siteLanguages[site].map(l=>`<a href="${s.origin+route(site,l,id)}" lang="${languages[l].tag}" hreflang="${languages[l].tag}" ${l===lang?'aria-current="page"':''}>${languages[l].label}</a>`).join(' ');return `<!doctype html><html lang="${languages[lang].tag}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(titleTag)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${url}">\n${alternatives}\n<meta property="og:title" content="${esc(titleTag)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta property="og:type" content="website"><meta property="og:locale" content="${{zh:'zh_CN',en:'en_US',de:'de_DE',it:'it_IT'}[lang]}"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="${asset}/style.css?v=${version}">${p?`<link rel="alternate" type="text/markdown" href="${url.replace(/\.html$/,'')}.md" title="${esc(t('Read the text version'))}">`:''}<script type="application/ld+json">${schema(p,lang,url,title,description,hub)}</script></head><body data-site="${site}" data-product="${id}" data-locale="${lang}" data-edition="${version}" style="--accent:${s.color}"><a class="skip" href="#main">${t('Skip to content')}</a><header><a href="${s.origin+(site==='bpj'&&lang==='en'?'/en/':site==='eco'&&lang==='en'?'/en/':'/')}">${s.name}</a><a href="${hub}">${t('Tool workbench')}</a><nav class="language-nav" aria-label="${t('Language')}">${nav}</nav></header><main id="main">${body}</main><footer>${site==='tds'?esc(t('Independent collector tools. Not affiliated with POP MART.'))+' ':''}${esc(t('Browser-based tools · Your inputs stay in this browser. No account, cloud backup or paid membership is provided.'))}</footer>${p?`<script type="module" src="${asset}/app.mjs?v=${version}"></script>`:''}</body></html>`;}
function write(p,lang,title,description,body){const r=route(site,lang,p?.id||''),url=s.origin+r;put(r+(r.endsWith('.html')?'':'.html'),shell(p,lang,title,description,body));urls.push(url);records.push({id:p?.id||'hub',lang,url,title,description});}
for(const lang of siteLanguages[site]){const t=translator(dicts[lang],lang);for(const p of own){const title=titleFor(p,lang),description=t(p.description),url=pageURL(p,lang),sample=Object.fromEntries(p.fields.map(f=>[f.key,f.value])),r=p.kind?null:engines[p.id](sample),notes=r?.notes||[];const ref=reference(p);const method=`<section class="method-section" id="method"><h2>${t('How this tool works')}</h2><p>${esc(t(formulas[p.id]))}</p><p class="scope">${t('Method version')}: ${version}</p>${p.fields.length?`<h3>${t('Input format')}</h3><p>${esc(t('No automatic currency conversion. CSV headers remain English; use decimal points and ISO dates (YYYY-MM-DD).'))}</p><dl class="input-schema">${p.fields.map(f=>`<dt>${esc(t(f.label))}</dt><dd><code>${esc(f.type==='csv'?f.value.split('\n')[0]:f.key)}</code></dd>`).join('')}</dl>`:''}<h3>${t('Reproducible example')}</h3><p>${esc(t('All prefilled business examples are fictional. Replace them with your own checked inputs.'))}</p>${r?table(r,lang,t):p.kind==='sql'?projects.map(q=>`<details><summary>${esc(t(q.name))}</summary><p>${esc(t(q.brief))}</p><pre>${esc(q.answer)}</pre><p>${esc(t(q.explanation))}</p></details>`).join(''):`<p>${esc(t(formulas[p.id]))}</p>`}${notes.length?`<h3>${t('Limits and assumptions')}</h3>${notes.map(n=>`<p>${esc(t(n))}</p>`).join('')}`:''}<h3>${t('Sources and specifications')}</h3><a href="${ref[1]}" rel="noopener">${esc(ref[0])}</a><p><a href="${url.replace(/\.html$/,'')}.md">${t('Read the text version')}</a>${p.fields.length?` · <a href="${asset}/samples/${p.id}.json" download>${t('Download example inputs')}</a>`:''}</p></section>`;
const sharing=`<section class="method-section" id="sharing"><h2>${t('Cite or embed this tool')}</h2><p>${esc(t('A link is enough to cite this tool. Embedding is optional; any attribution is voluntary. No ranking or traffic is promised.'))}</p><p><a href="${url}">${esc(p.name)} — ${esc(title)}</a></p><div class="actions"><button type="button" id="copy-page">${t('Copy page link')}</button>${!p.kind?`<button type="button" id="create-widget">${t('Create embed code')}</button>`:''}</div><div id="widget-code"></div></section>`;
const body=`<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="${s.origin}/">${s.name}</a> / <a href="${hubURL(site,lang)}">${t('Tool workbench')}</a> / <span>${p.name}</span></nav><p class="eyebrow">${esc(t(groups[p.group]))} / ${p.name}</p><h1>${esc(title)}</h1><p class="intro">${esc(description)}</p><p class="scope">${esc(t(p.commercial||'Free working edition. Named workspaces and exports are local to your device. Team sync, automatic source monitoring and paid memberships are not available.'))}</p><p class="scope">${esc(t('All prefilled business examples are fictional. Replace them with your own checked inputs.'))}</p><noscript>${esc(t('This tool needs JavaScript to process data locally. Enable JavaScript to use it.'))}</noscript><p id="status" role="status" aria-live="polite" class="notice">${t('Ready. Choose your inputs and generate a result.')}</p><div class="layout"><section id="input-panel" class="panel" aria-label="${t('Your inputs')}"><h2>${t(p.kind==='sql'?'Project desk':p.kind?'Create & play':'Your inputs')}</h2><form id="input-form"></form></section><section class="panel" id="output" aria-label="${t('Your result')}"><h2>${t('Your result')}</h2><p>${t('Run the tool to see its output here. You can inspect, export or print the result.')}</p></section></div><section id="workspace" class="panel"></section>${method}${sharing}<nav class="related" aria-label="${t('Continue your workflow')}"><h2>${t('Continue your workflow')}</h2>${related(p).map(x=>`<a href="${pageURL(x,actualLang(x,lang))}">${esc(x.name)} — ${esc(titleFor(x,actualLang(x,lang)))}</a>`).join('')}<a href="${hubURL('agi',lang==='zh'?'zh':'en')}">${t('All 24 tools')}</a></nav>`;
write(p,lang,title,description,body);
const markdown=`# ${title} — ${p.name}\n\nCanonical: ${url}\nLanguage: ${languages[lang].tag}\n${t('Method version')}: ${version}\n\n${description}\n\n## ${t('How this tool works')}\n\n${t(formulas[p.id])}\n\n## ${t('Input format')}\n\n${p.fields.map(f=>'- '+t(f.label)+': `'+(f.type==='csv'?f.value.split('\n')[0]:f.key)+'`').join('\n')}\n\n## ${t('Reproducible example')}\n\n${t('All prefilled business examples are fictional. Replace them with your own checked inputs.')}\n\n${r?'```json\n'+JSON.stringify({columns:r.columns.map(t),rows:r.rows},null,2)+'\n```':t(formulas[p.id])}\n\n## ${t('Limits and assumptions')}\n\n${notes.map(t).join('\n\n')}\n\n${t('Browser-based tools · Your inputs stay in this browser. No account, cloud backup or paid membership is provided.')}\n\n[${ref[0]}](${ref[1]})\n`;
put(new URL(url).pathname.replace(/\.html$/,'')+'.md',markdown);if(p.fields.length){put(asset+'/samples/'+p.id+'.json',JSON.stringify({version:1,product:p.id,values:sample},null,2));put(asset+'/widgets/'+lang+'/'+p.id+'.txt',widgetHTML(p,lang,dicts[lang],core));}
}
const list=groups.map((g,i)=>{const entries=listed.filter(p=>p.group===i);return entries.length?`<section class="group-section"><h2>${esc(t(g))}</h2><ul class="product-list">${entries.map(p=>{const l=actualLang(p,lang);return `<li><a href="${pageURL(p,l)}">${esc(p.name)}</a><p>${esc(translator(dicts[l],l)(p.description))}${l!==lang?` <span lang="en">(English)</span>`:''}</p></li>`;}).join('')}</ul></section>`:'';}).join('');
write(null,lang,t('Useful work. Inspectable results.'),t('Practical browser tools for research, operations, energy, collecting and learning.'),`<p class="eyebrow">${s.name} / ${listed.length}</p><h1>${t('Useful work. Inspectable results.')}</h1><p class="intro">${t('Bring a real task. Compare inputs, check assumptions, and leave with a result you can use.')}</p><p class="scope">${t('Free browser tools, original puzzles and an existing sponsored-placement checkout. Local versions are not cloud accounts. Only LaunchDesk currently offers a paid placement; no membership is on sale.')}</p>${list}`);
}
// Preserve old entries. Every localized canonical is listed once, with no fabricated freshness date.
const sitemap=path.join(out,'sitemap.xml');let xml=fs.existsSync(sitemap)?fs.readFileSync(sitemap,'utf8'):'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>';
if(!xml.includes('</urlset>'))throw Error('Expected URL sitemap');for(const url of urls)if(!xml.includes('<loc>'+url+'</loc>'))xml=xml.replace('</urlset>',`<url><loc>${url}</loc></url>\n</urlset>`);fs.writeFileSync(sitemap,xml);
// Wire corresponding-language home pages and existing task pages. Skip absent pages; never invent links.
const homes={bpj:[['index.html','zh'],['en/index.html','en']],agi:[['index.html','en'],['zh/index.html','zh'],['ai-tools.html','en'],['zh/ai-tools.html','zh']],eco:[['index.html','de'],['en/index.html','en'],['it/index.html','it']],tds:[['index.html','en'],['de/index.html','de']]};
const context={bpj:[['llm-api-calculator.html','zh','quotawatch-pro'],['en/llm-api-calculator.html','en','quotawatch-pro'],['video-quota-planner.html','zh','creatorops'],['en/video-quota-planner.html','en','creatorops']],eco:[['guide/stromkosten-rechner.html','de','billlens'],['guide/heizluefter-stromsparend.html','de','appliancepayback'],['en/guide/portable-ac-running-cost.html','en','appliancepayback']],tds:[['rarity.html','en','collectorledger'],['de/rarity.html','de','collectorledger'],['where-to-buy.html','en','displayfit'],['de/where-to-buy.html','de','displayfit']],agi:[['ai-job-risk-check.html','en','job-evidence'],['invest.html','en','filinglens-workspace'],['zh/invest.html','zh','filinglens-workspace']]};
const wired=[];for(const [relative,lang,id]of [...homes[site],...context[site]]){const file=path.join(out,relative);if(!fs.existsSync(file))continue;const t=translator(dicts[lang],lang);let html=fs.readFileSync(file,'utf8').replace(/<!-- task-workbench:start -->[\s\S]*?<!-- task-workbench:end -->/g,'').replace(/<!-- studio-hub:start -->[\s\S]*?<!-- studio-hub:end -->/g,'');const p=own.find(x=>x.id===id);const entries=p?[p]:own;const block=`<!-- task-workbench:start --><aside class="workbench-discovery" style="padding:24px;max-width:1100px;margin:24px auto;border-top:1px solid #ccc" aria-label="${t('Tool workbench')}"><h2><a href="${hubURL(site,lang)}">${t('Tool workbench')}</a></h2><ul>${entries.map(p=>`<li><a href="${pageURL(p,lang)}">${p.name} — ${esc(titleFor(p,lang))}</a></li>`).join('')}</ul></aside><!-- task-workbench:end -->`;html=html.replace(/<\/body>/i,block+'</body>');fs.writeFileSync(file,html);wired.push(relative);}
for(const fileName of ['llms.txt','llms-full.txt']){const file=path.join(out,fileName);let text=fs.existsSync(file)?fs.readFileSync(file,'utf8'):'';text=text.replace(/\n<!-- workbench:start -->[\s\S]*?<!-- workbench:end -->/g,'');text+='\n<!-- workbench:start -->\n## Practical browser tools — localized methods and examples\n'+records.filter(r=>r.id!=='hub').map(r=>`- [${r.title}](${r.url}) [${r.lang}]: ${r.description} Text: ${r.url.replace(/\.html$/,'')}.md`).join('\n')+'\n<!-- workbench:end -->\n';fs.writeFileSync(file,text);}
put(asset+'/manifest.json',JSON.stringify({edition:version,site,urls,records,wired},null,2));
console.log(`Built ${own.length} tools in ${siteLanguages[site].length} languages (${urls.length} pages) for ${site}; ${wired.length} discovery entries.`);
