export const sites={bpj:{name:'BPJ',origin:'https://baipiaoji.com',prefix:'/workbench',suffix:'',color:'#214dc5'},agi:{name:'AGI Scorecard',origin:'https://agiscorecard.com',prefix:'/workbench',suffix:'',color:'#2547af'},eco:{name:'EcoBack',origin:'https://getecoback.com',prefix:'/en/workbench',suffix:'.html',color:'#236147'},tds:{name:'The Doll Scout',origin:'https://thedollscout.com',prefix:'/workbench',suffix:'',color:'#e4002b'}};
export const groups=['AI tools & creators','Research & evidence','Home energy','Collectors','Trade & localization','Business operations','Learning & careers','Puzzles & education'];
const f=(key,label,value,type='text',options)=>({key,label,value,type,options});
const table=(key,label,value)=>f(key,label,value,'csv');
const n=(key,label,value)=>f(key,label,String(value),'number');
const select=(key,label,value,options)=>f(key,label,value,'select',options);
const p=(id,name,site,group,description,fields,extra={})=>({id,name,site,group,description,fields,...extra});
export const products=[
p('launchdesk','LaunchDesk','bpj',0,'Prepare a sponsored tool placement, then check live inventory and pay through BPJ.',[f('name','Tool name','Sample editor'),f('website','Tool website','https://example.com'),f('category','Audience / category','Video creators'),f('pitch','One-sentence pitch','Turn a recorded tutorial into an editable clip brief.'),n('budget','Placement budget (USDT)',49)],{commercial:'Paid placement available through the existing BPJ checkout; no guaranteed reach.'}),
p('quotawatch-pro','QuotaWatch Pro','bpj',0,'Compare two verified quota snapshots without mistaking a unit change for a better deal.',[table('before','Previous snapshot','tool,limit,unit,period,source\nSample tool,20,exports,month,https://example.com/pricing'),table('after','New snapshot','tool,limit,unit,period,source\nSample tool,15,exports,month,https://example.com/pricing')]),
p('creatorops','CreatorOps','bpj',0,'Turn clip timings, evidence and rights notes into a production handoff.',[f('audience','Intended audience','Independent course creators'),f('action','Desired viewer action','Try the walkthrough'),table('clips','Clip plan','start_seconds,end_seconds,hook,claim,evidence,rights\n10,35,Show the result,Three steps in this demo,Screen recording at 00:18,owned\n50,75,Explain the limitation,Needs a clean transcript,Demo transcript,review')]),
p('evidencewatch','EvidenceWatch','agi',1,'Keep claim-level source references and export due dates to your calendar.',[f('today','Review as of','2026-09-19','date'),table('claims','Claims to review','claim,source,checked_at,review_days\nSample plan includes exports,https://example.com/pricing,2026-09-01,14')]),
p('agentfit','AgentFit','agi',1,'Choose an execution pattern and write testable acceptance criteria before deploying an agent.',[f('task','Task steps, one per line','Read three approved sources\nDraft a cited comparison\nAsk the operator to review','textarea'),select('structure','Can the steps be specified in advance?','fixed',[['fixed','Yes: fixed sequence'],['adaptive','No: adaptive search']]),select('actions','External permissions','read',[['read','Read only'],['write','Write or purchase']]),select('data','Data sensitivity','public',[['public','Public'],['private','Private / restricted']])]),
p('filinglens-workspace','FilingLens Workspace','agi',1,'Preserve same-period research inputs, source URLs and calculated changes.',[table('facts','Comparable reported metrics','company,metric,period,unit,prior,current,source\nExample Co,revenue,Q2 year over year,USD million,100,112,https://example.com/report')]),
p('billlens','BillLens','eco',2,'Compare first-year and recurring electricity costs using your actual tariff inputs.',[n('kwh','Annual electricity use (kWh)',3200),table('tariffs','Tariffs, one currency','tariff,currency,unit_price,monthly_fee,one_time_credit\nSample A,EUR,0.30,12,100\nSample B,EUR,0.27,16,0')]),
p('appliancepayback','AppliancePayback','eco',2,'Estimate replacement payback under three energy-price assumptions.',[n('oldwatts','Current average power (W)',120),n('newwatts','Replacement average power (W)',65),n('hours','Operating hours per day',8),n('days','Operating days per year',300),n('price','Extra purchase cost (your currency)',180),n('rate','Electricity cost per kWh (same currency)',0.30),n('life','Comparison period (years)',8)]),
p('homeenergy-log','HomeEnergy Log','eco',2,'Turn cumulative meter readings into interval use and daily averages.',[table('readings','Meter readings','date,meter,reading_kwh\n2026-08-01,Main,12000\n2026-09-01,Main,12220\n2026-09-19,Main,12360')]),
p('collectorledger','CollectorLedger','tds',3,'Count owned figures and duplicates while preserving recorded purchase costs.',[table('items','Collection records','series,figure,variant,quantity,paid_each,currency\nSample Forest,Moss,Standard,2,18,EUR\nSample Forest,Rain,Standard,1,22,EUR')]),
p('dropcalendar','DropCalendar','tds',3,'Convert entered official release announcements into timezone-safe calendar reminders.',[table('events','Your verified release announcements','title,time_with_offset,official_source,region\nFictional sample release,2026-10-01T18:00:00+02:00,https://example.com/announcement,EU')]),
p('displayfit','DisplayFit','tds',3,'Check display capacity and visible front-row space before buying a cabinet.',[n('width','Internal shelf width (mm)',600),n('height','Clear height per shelf (mm)',220),n('depth','Internal shelf depth (mm)',250),n('figurewidth','Figure bounding width (mm)',95),n('figureheight','Figure bounding height (mm)',175),n('figuredepth','Figure bounding depth (mm)',80),n('gap','Gap between figures (mm)',15),n('shelves','Usable shelf levels',3)]),
p('tradecheck-team','TradeCheck Team','agi',4,'Compare invoice lines to purchase orders and flag duplicate invoice IDs.',[table('invoices','Invoice lines','vendor,invoice,po,quantity,unit_price,currency\nSample vendor,INV-1,PO-1,10,12,USD'),table('orders','Purchase order lines','vendor,po,quantity,unit_price,currency\nSample vendor,PO-1,10,10,USD'),table('history','Previously recorded invoices (optional)','vendor,invoice\nSample vendor,INV-0'),n('tolerance','Allowed amount difference',0.01)]),
p('localebatch-qa','LocaleBatch QA','agi',4,'Find missing translations, changed placeholders and import-field duplicates.',[table('translations','Normalized translation fields','id,field,locale,source,target\n101,title,de,Hello {name},Hallo {name}\n101,body,de,Pack of 3,Packung mit 2')]),
p('rfq-roundbook','RFQ Roundbook','agi',4,'Compare one-currency quote rounds and save the assumptions behind each decision.',[table('quotes','Supplier quotes','supplier,currency,quantity,unit_price,freight,discount,lead_days,terms\nSample A,USD,100,5,80,0,14,Tax excluded\nSample B,USD,100,5.4,20,10,9,Tax excluded')]),
p('evidencebrief','EvidenceBrief','agi',5,'Build a sourced opportunity memo with alternatives, counterevidence and a stop condition.',[f('buyer','Specific buyer','Small exporter operations manager'),f('task','Repeated task','Compare three supplier revisions'),f('alternative','Current alternative','Spreadsheet and email'),f('test','Next measurable test','Observe five quote comparisons with permission'),f('stop','Stop condition','No repeated error or time cost found'),table('evidence','Evidence register','claim,source,type,stance,observation\nManual comparison takes time,https://example.com/interview,customer,supports,Fictional interview example\nSpreadsheet may be sufficient,https://example.com/template,primary,contradicts,Fictional template example')]),
p('modelmeter-reconcile','ModelMeter Reconcile','agi',5,'Reconcile normalized expected AI costs against billing entries without connecting an account.',[table('bills','Normalized billing entries','id,provider,period,currency,expected,billed\nLINE-1,Sample provider,2026-08,USD,80,82\nLINE-2,Sample provider,2026-08,USD,15,15'),n('tolerance','Allowed difference per entry',0.05)]),
p('workflowcost','WorkflowCost','agi',5,'Model retries, human review and fixed costs before quoting an automated workflow.',[n('runs','Submitted runs per month',1000),n('input','Input tokens per attempt',3000),n('output','Output tokens per attempt',700),n('inputrate','Price per million input tokens',2),n('outputrate','Price per million output tokens',8),n('other','Other execution cost per attempt',0.01),n('failure','Failure probability per attempt (0–0.99)',0.1),n('retries','Maximum retries',2),n('minutes','Human review minutes per submitted run',0.5),n('hourly','Human review cost per hour',30),n('fixed','Fixed monthly cost',20)]),
p('querysprint-projects','QuerySprint Projects','agi',6,'Run original SQLite projects in your browser and compare results with explained solutions.',[],{kind:'sql'}),
p('job-evidence','JobEvidence','agi',6,'Map role requirements to real projects, sources and observed results.',[f('role','Target role','Junior operations analyst'),table('mapping','Requirement evidence map','requirement,evidence,source,result\nSQL joins,Original order analysis,portfolio/orders.sql,Found three unmatched orders\nStakeholder communication,,,')]),
p('scamchecklist','ScamChecklist','agi',6,'Create a verification checklist from observable warning signals.',[['urgency','Artificial urgency'],['payment','Unusual payment demand'],['secret','Requests for passwords or codes'],['link','Unexpected links or attachments'],['identity','Unverified sender identity'],['remote','Remote-access request']].map(([k,l])=>select(k,l,k==='urgency'?'yes':'no',[['yes','Present'],['no','Not reported']]))),
p('puzzleclub','PuzzleClub','agi',7,'Play an original daily 4 × 4 puzzle with one verified solution and share your result.',[],{kind:'puzzle'}),
p('classroompuzzles','ClassroomPuzzles','agi',7,'Generate original printable number puzzles and a separate answer sheet for your class.',[],{kind:'classroom'}),
p('embedpuzzles','EmbedPuzzles','agi',7,'Generate a self-contained interactive puzzle embed for a website or classroom page.',[],{kind:'embed'})
];
export function href(product){const s=sites[product.site];return s.origin+s.prefix+'/'+product.id+s.suffix;}
