// Browser-only task engines. No network, credentials or hidden model calls.
export const LIMIT=1500;
export function csv(text){
 if(typeof text!=='string'||text.length>300000)throw Error('Use a CSV smaller than 300 KB.');
 const rows=[];let row=[],cell='',quoted=false;
 text=text.replace(/^\uFEFF/,'');
 for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(!quoted&&cell==='')quoted=true;else if(quoted)quoted=false;else throw Error('Unexpected quote in CSV.');}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}
 if(quoted)throw Error('Close the quoted CSV field.');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);
 if(rows.length<2)throw Error('Include a header and at least one data row.');
 const heads=rows.shift().map(x=>x.trim());if(new Set(heads).size!==heads.length||heads.some(x=>!x||['__proto__','constructor','prototype'].includes(x)))throw Error('Use unique, non-empty CSV column names.');
 if(rows.length>LIMIT)throw Error(`Use at most ${LIMIT} data rows.`);
 return rows.map((r,i)=>{if(r.length!==heads.length)throw Error(`Row ${i+2}: expected ${heads.length} columns, found ${r.length}.`);return Object.fromEntries(heads.map((h,j)=>[h,r[j].trim()]));});
}
export function requireCols(rows,cols){for(const c of cols)if(!(c in rows[0]))throw Error('Missing CSV column: '+c);return rows;}
export function num(v,label='Number',min=0,max=1e12){if(String(v).trim()===''||!Number.isFinite(Number(v))||Number(v)<min||Number(v)>max)throw Error(`${label}: enter a number from ${min} to ${max}.`);return Number(v);}
export const money=v=>Number(v).toFixed(2);
export const csvOut=rows=>rows.map(r=>r.map(x=>'"'+String(x??'').replace(/^[=+@\t\r-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');
export function url(v){try{const u=new URL(v);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error();return u.href;}catch{throw Error('Use a complete http(s) source URL without credentials.');}}
export function day(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v+'T00:00:00Z'))||new Date(v+'T00:00:00Z').toISOString().slice(0,10)!==v)throw Error('Use a valid date: YYYY-MM-DD.');return Date.parse(v+'T00:00:00Z');}
const report=(title,columns,rows,notes=[],extra={})=>({title,columns,rows,notes,...extra});
const records=(v,cols)=>requireCols(csv(v),cols);
const groups=rows=>{const out=new Map();for(const r of rows){const key=r.currency||'unspecified';out.set(key,(out.get(key)||0)+r.value);}return [...out].map(([c,v])=>`${c} ${money(v)}`).join('; ');};
const multiset=v=>[...v].sort().join('|');
export function ics(events){const esc=v=>String(v).replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');const stamp=v=>new Date(v).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');
 const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Task Workbench//EN','CALSCALE:GREGORIAN'];
 for(const [i,e] of events.entries()){const start=Date.parse(e.when);if(!Number.isFinite(start)||!/(Z|[+-]\d{2}:\d{2})$/.test(e.when))throw Error('Event times need an explicit UTC offset, e.g. 2026-10-01T18:00:00+02:00.');const source=url(e.source);const end=start+3600000;const id=Array.from(e.title+e.when+source).reduce((a,c)=>Math.imul(a^c.codePointAt(0),16777619)>>>0,2166136261);lines.push('BEGIN:VEVENT',`UID:${id}-${i}@task-workbench`, 'DTSTAMP:'+stamp(Date.now()),'DTSTART:'+stamp(start),'DTEND:'+stamp(end),'SUMMARY:'+esc(e.title),'DESCRIPTION:'+esc('Source: '+source+'\n'+(e.note||'')),'URL:'+source,'BEGIN:VALARM','TRIGGER:-PT30M','ACTION:DISPLAY','DESCRIPTION:'+esc(e.title),'END:VALARM','END:VEVENT');}
 lines.push('END:VCALENDAR');return lines.map(line=>{let result='',part='';for(const c of line){if(new TextEncoder().encode(part+c).length>73){result+=part+'\r\n ';part='';}part+=c;}return result+part;}).join('\r\n')+'\r\n';
}
export const engines={
 'launchdesk':d=>{url(d.website);if(d.pitch.length>160)throw Error('Keep the pitch within 160 characters.');return report('Campaign readiness',['Check','Result'],[['Tool',d.name],['Destination',d.website],['Audience',d.category],['Pitch',d.pitch],['Budget',money(num(d.budget))+' USDT'],['Inventory','3 sponsored lanes per category; queue when full']],[ 'Buyers see live reach and the exact payment quote at checkout. Natural directory ranking is not for sale.','A 30-day placement is 49 USDT plus a unique matching fraction below 0.01 USDT. No traffic or sales guarantee.'],{links:[['See live inventory and buy a placement','https://baipiaoji.com/advertise']]});},
 'quotawatch-pro':d=>{const cols=['tool','limit','unit','period','source'];const old=records(d.before,cols),now=records(d.after,cols);const key=r=>r.tool.toLowerCase()+'|'+r.unit+'|'+r.period;for(const list of [old,now]){if(new Set(list.map(key)).size!==list.length)throw Error('Use one row per tool / unit / period.');list.forEach(r=>{url(r.source);num(r.limit,'Limit');});}const index=new Map(old.map(r=>[key(r),r]));const rows=now.map(r=>{const p=index.get(key(r));index.delete(key(r));return[r.tool,p?.limit??'Not recorded',r.limit,r.unit,r.period,p?(p.limit===r.limit?'Unchanged':'Changed'):'New / incomparable',r.source];});for(const p of index.values())rows.push([p.tool,p.limit,'Not in new snapshot',p.unit,p.period,'Removed / review',p.source]);return report('Quota snapshot comparison',['Tool','Before','After','Unit','Period','Review','Source'],rows,['No live website is fetched. Add a newly verified snapshot to compare changes. Unit or reset-period changes are not treated as numeric increases.','Save named snapshots on this device; JSON exports can be moved to another browser.']);},
 'creatorops':d=>{const rows=records(d.clips,['start_seconds','end_seconds','hook','claim','evidence','rights']);return report('Production brief',['Clip','In','Out','Seconds','Hook','Claim / evidence','Rights check'],rows.map((r,i)=>{const start=num(r.start_seconds),end=num(r.end_seconds);if(end<=start)throw Error(`Clip ${i+1}: end must follow start.`);return[i+1,start,end,end-start,r.hook,`${r.claim}\nEvidence: ${r.evidence}`,r.rights==='owned'||r.rights==='licensed'?'Record supporting permission':'Review before publishing'];}),['Use footage and audio you own or are permitted to reuse. This creates an edit brief; it does not edit video or verify ownership.'],{text:`Audience: ${d.audience}\nAction: ${d.action}\nDeliverables: one problem clip, one demonstration, one explanation.\nReview: captions, factual claim, evidence frame, rights, safe crop, final CTA.`});},
 'evidencewatch':d=>{const today=day(d.today),rows=records(d.claims,['claim','source','checked_at','review_days']);const events=[];const result=rows.map((r,i)=>{const checked=day(r.checked_at),days=num(r.review_days,'Review interval',1,365);url(r.source);const due=checked+days*86400000;events.push({title:'Review: '+r.claim,when:new Date(due).toISOString(),source:r.source,note:'Manually check the primary source; this is not a detected change.'});return[i+1,r.claim,r.source,r.checked_at,new Date(due).toISOString().slice(0,10),due<=today?'Due for review':'Scheduled'];});return report('Evidence review queue',['#','Claim','Source','Last checked','Review date','Status'],result,['Dates schedule a manual source review, not automatic evidence monitoring. Export the calendar to get reminders in your calendar app.'],{download:{name:'evidence-reviews.ics',mime:'text/calendar',content:ics(events)}});},
 'agentfit':d=>{const stages=d.task.split('\n').map(x=>x.trim()).filter(Boolean);if(!stages.length)throw Error('Describe at least one task step.');const autonomous=d.actions==='write';const pattern=d.structure==='fixed'?'Deterministic workflow with explicit steps':autonomous?'Assisted agent with approval before each external write':'Read-only agent with bounded tools';return report('Deployment and acceptance brief',['Area','Decision'],[['Architecture',pattern],['Data boundary',d.data==='private'?'Use an approved private runtime; do not paste secrets into prompts.':'Document source access and retention.'],['Execution permissions',autonomous?'Approval + idempotency key + rollback before writes':'Allowlist read endpoints; block mutations'],['Traceability','Log source references and tool outcomes, excluding secrets'],['Stop rule','Stop at budget limit, missing source or conflicting evidence']],['This selects an execution pattern, not a tested vendor winner. No credentials or external actions are requested.'],{text:stages.map((s,i)=>`Test ${i+1}: ${s}\nInput fixture: [supply your sample]\nExpected output: [define acceptance]\nFailure fixture: missing source / denied permission\n`).join('\n')+'\nRelease checklist: replay twice, deny a permission, interrupt execution, validate cost and redaction.'});},
 'filinglens-workspace':d=>{const rows=records(d.facts,['company','metric','period','unit','prior','current','source']);return report('Same-period fact workbook',['Company','Metric','Period','Unit','Prior','Current','Change','Change %','Source'],rows.map(r=>{url(r.source);const a=num(r.prior,'Prior',-1e15,1e15),b=num(r.current,'Current',-1e15,1e15);return[r.company,r.metric,r.period,r.unit,a,b,b-a,a===0?'Undefined':((b-a)/Math.abs(a)*100).toFixed(2)+'%',r.source];}),['Each row must use the same company, metric definition, period, unit and scale. You supply those matches; this workbook cannot establish comparability or explain restatements.','Local versions preserve source references. This is research arithmetic, not an investment recommendation.'],{links:[['Retrieve and compare SEC facts','https://filinglens.agiscorecard.com/']]});},
 'billlens':d=>{const kwh=num(d.kwh,'Annual consumption',0,1e7);const rows=records(d.tariffs,['tariff','currency','unit_price','monthly_fee','one_time_credit']);if(new Set(rows.map(r=>r.currency)).size>1)throw Error('Compare tariffs in one currency; convert using your documented rate first.');return report('Annual tariff comparison',['Tariff','Currency','Energy','Standing fees','One-time credit','First year','Following year'],rows.map(r=>{const energy=kwh*num(r.unit_price),fees=12*num(r.monthly_fee),credit=num(r.one_time_credit);return[r.tariff,r.currency,money(energy),money(fees),money(credit),money(energy+fees-credit),money(energy+fees)];}).sort((a,b)=>Number(a[5])-Number(b[5])),['Unit price is currency per kWh, not cents. Monthly standing fees are multiplied by 12. One-time credits apply only in year one.','Taxes must already be included in your inputs. This does not model tiered tariffs, eligibility or cancellation fees. No supplier switching occurs.']);},
 'appliancepayback':d=>{const old=num(d.oldwatts),fresh=num(d.newwatts),hours=num(d.hours,'Hours per day',0,24),days=num(d.days,'Days per year',1,366),cost=num(d.price,'Extra purchase cost'),rate=num(d.rate,'Electricity per kWh'),life=num(d.life,'Comparison years',1,30);const saved=(old-fresh)*hours*days/1000;return report('Replacement cost scenarios',['Energy-price scenario','Price / kWh','Annual energy saved (kWh)','Annual saving','Payback years','Net after comparison period'],[0.75,1,1.25].map((f,i)=>{const saving=saved*rate*f;return[['Lower price','Your price','Higher price'][i],(rate*f).toFixed(4),saved.toFixed(2),money(saving),saving>0?(cost/saving).toFixed(1):'No energy payback',money(saving*life-cost)];}),['Power is an average draw, not necessarily the label maximum. Operating hours and appliance lifetime are user assumptions. No inflation, financing or maintenance difference is included.','Negative savings mean the new appliance consumes more under these inputs.']);},
 'homeenergy-log':d=>{const rows=records(d.readings,['date','meter','reading_kwh']).map(r=>({...r,time:day(r.date),value:num(r.reading_kwh)})).sort((a,b)=>a.time-b.time);const prev=new Map(),seen=new Set();const result=rows.map(r=>{const key=r.meter+'|'+r.date;if(seen.has(key))throw Error('Use one reading per meter per day.');seen.add(key);const p=prev.get(r.meter);prev.set(r.meter,r);const delta=p?r.value-p.value:null;const elapsed=p?(r.time-p.time)/86400000:null;return[r.date,r.meter,r.value,delta===null?'Baseline':delta<0?'Reset / review':delta.toFixed(3),delta!==null&&delta>=0?(delta/elapsed).toFixed(3):'Not comparable'];});return report('Meter usage intervals',['Date','Meter','Cumulative kWh','Interval kWh','kWh / day'],result,['A decreasing reading is a reset or data error, never negative consumption. First reading is a baseline. Intervals are normalized by elapsed days, not compared as equal-length months.','Records stay on this device only when you choose Save. Export a backup before clearing browser storage.']);},
 'collectorledger':d=>{const rows=records(d.items,['series','figure','variant','quantity','paid_each','currency']);const index=new Map();for(const r of rows){const key=[r.series,r.figure,r.variant].map(x=>x.toLowerCase()).join('|');const n=num(r.quantity,'Quantity',1,100000);if(!Number.isInteger(n))throw Error('Quantity must be a whole number.');num(r.paid_each);const old=index.get(key);if(old&&old.currency!==r.currency)throw Error('For the same collectible, keep one currency or split the variant.');if(old){old.quantity+=n;old.paid+=n*Number(r.paid_each);}else index.set(key,{...r,quantity:n,paid:n*Number(r.paid_each)});}const values=[...index.values()];return report('Collection and duplicates',['Series','Figure','Variant','Owned','Duplicates','Recorded cost','Currency'],values.map(r=>[r.series,r.figure,r.variant,r.quantity,Math.max(0,r.quantity-1),money(r.paid),r.currency]),['Recorded purchase costs: '+groups(values.map(r=>({currency:r.currency,value:r.paid}))), 'Purchase cost is not resale value or rarity. No price feed, authenticity certification or cloud backup is provided.']);},
 'dropcalendar':d=>{const rows=records(d.events,['title','time_with_offset','official_source','region']);const events=rows.map(r=>({title:r.title,when:r.time_with_offset,source:r.official_source,note:'Region: '+r.region+'; verify the official announcement before purchase.'}));const content=ics(events);return report('Release calendar',['Release','UTC time','Region','Official source'],events.map((e,i)=>[e.title,new Date(e.when).toISOString(),rows[i].region,e.source]),['These are your entered announcements, not a live release feed. Confirm the region and seller. Calendar import adds a 30-minute reminder; later source changes are not synced automatically.'],{download:{name:'official-release-reminders.ics',mime:'text/calendar',content}});},
 'displayfit':d=>{const w=num(d.width,'Internal width',1,10000),h=num(d.height,'Internal height',1,10000),depth=num(d.depth,'Internal depth',1,10000),fw=num(d.figurewidth,'Figure width',1,10000),fh=num(d.figureheight,'Figure height',1,10000),fd=num(d.figuredepth,'Figure depth',1,10000),gap=num(d.gap,'Clearance',0,1000),shelves=num(d.shelves,'Shelf levels',1,30);if(!Number.isInteger(shelves))throw Error('Shelf levels must be a whole number.');const rows=[[fw,fd,'Facing forward'],[fd,fw,'Turned sideways']].map(([a,b,label])=>{const cols=Math.floor((w+gap)/(a+gap)),layers=Math.floor((depth+gap)/(b+gap)),levels=fh<=h?shelves:0;return[label,cols,layers,levels,cols*layers*levels,cols*levels];});return report('Display capacity',['Orientation','Across','Depth rows','Usable shelf levels','Total fit','Visible front row'],rows,['All dimensions are millimetres. Height is clear height per shelf, excluding risers. Bounding boxes ignore irregular poses and doors.','This checks space only, not shelf strength, weight limits or safe installation. Depth rows may hide collectibles.']);},
 'tradecheck-team':d=>{const invoices=records(d.invoices,['vendor','invoice','po','quantity','unit_price','currency']),orders=records(d.orders,['vendor','po','quantity','unit_price','currency']);const history=d.history.trim()?records(d.history,['vendor','invoice']):[];const done=new Set(history.map(r=>r.vendor+'|'+r.invoice)),seen=new Set();const pmap=new Map();for(const p of orders){const k=p.vendor+'|'+p.po;if(pmap.has(k))throw Error('This version requires one PO line per vendor / PO.');pmap.set(k,p);}const tol=num(d.tolerance,'Amount tolerance');return report('Invoice review exceptions',['Vendor','Invoice','PO','Invoiced','Expected','Currency','Review'],invoices.map(r=>{const k=r.vendor+'|'+r.invoice,p=pmap.get(r.vendor+'|'+r.po),actual=num(r.quantity)*num(r.unit_price),expected=p?num(p.quantity)*num(p.unit_price):null;const flags=[];if(done.has(k))flags.push('Previously recorded invoice');if(seen.has(k))flags.push('Duplicate in this batch');seen.add(k);if(!p)flags.push('PO not found');else if(p.currency!==r.currency)flags.push('Currency mismatch');else if(Math.abs(actual-expected)>tol)flags.push('Amount mismatch');if(!history.length)flags.push('Historical duplicate check unavailable');return[r.vendor,r.invoice,r.po,money(actual),expected===null?'Unknown':money(expected),r.currency,flags.join('; ')||'No selected-rule exceptions'];}),['Single-line PO / invoice comparison; split invoices and tax/freight need manual review. No OCR, ERP connection, payment approval or fraud guarantee.'],{links:[['Use mapped PO/invoice tables and the MCP package','https://rfqdesk.agiscorecard.com/agent']]});},
 'localebatch-qa':d=>{const rows=records(d.translations,['id','field','locale','source','target']);const seen=new Set();const result=rows.map((r,i)=>{const k=r.id+'|'+r.field+'|'+r.locale,flags=[];if(seen.has(k))flags.push('Duplicate target field');seen.add(k);if(!r.target)flags.push('Missing translation');const tokens=t=>t.match(/\{\{[^}]+\}\}|\{[A-Za-z_][\w.]*\}|%[sd]/g)||[];if(multiset(tokens(r.source))!==multiset(tokens(r.target)))flags.push('Placeholder mismatch');const nums=t=>t.match(/\d+(?:[.,]\d+)*/g)||[];if(multiset(nums(r.source))!==multiset(nums(r.target)))flags.push('Number formatting or value changed; review');const tags=t=>t.match(/<\/?[a-z][^>]*>/gi)||[];if(multiset(tags(r.source))!==multiset(tags(r.target)))flags.push('HTML structure or attributes changed');return[i+2,r.id,r.field,r.locale,flags.join('; ')||'No selected-rule exceptions'];});return report('Translation field QA',['Row','ID','Field','Locale','Review'],result,['These checks do not establish translation fluency or correctness. Number localization can be valid and still needs review.','No automatic translation or store import runs here. Keep an original CSV backup.'],{links:[['Check Shopify translation import structure','https://localebatch.agiscorecard.com/']]});},
 'rfq-roundbook':d=>{const rows=records(d.quotes,['supplier','currency','quantity','unit_price','freight','discount','lead_days','terms']);if(new Set(rows.map(r=>r.currency)).size>1)throw Error('Use one comparison currency.');if(new Set(rows.map(r=>r.quantity)).size>1)throw Error('Compare the same requested quantity.');return report('Comparable quote round',['Supplier','Currency','Units','Goods','Freight','Discount','Total','Lead days','Terms'],rows.map(r=>{const q=num(r.quantity,'Quantity',1),goods=q*num(r.unit_price),freight=num(r.freight),discount=num(r.discount);if(discount>goods+freight)throw Error('Discount cannot exceed quoted total.');return[r.supplier,r.currency,q,money(goods),money(freight),money(discount),money(goods+freight-discount),num(r.lead_days),r.terms];}).sort((a,b)=>Number(a[6])-Number(b[6])),['Compare Incoterms, tax, warranty and delivery scope before choosing. Lowest entered total is not a supplier recommendation.','Save named rounds locally and export JSON to preserve source inputs; no shared approval workspace is provided.']);},
 'evidencebrief':d=>{const rows=records(d.evidence,['claim','source','type','stance','observation']);const allowed=['primary','customer','vendor','secondary'];rows.forEach(r=>{url(r.source);if(!allowed.includes(r.type))throw Error('Evidence type: primary, customer, vendor or secondary.');if(!['supports','contradicts','unknown'].includes(r.stance))throw Error('Stance: supports, contradicts or unknown.');});const contra=rows.filter(r=>r.stance==='contradicts').length;return report('Opportunity evidence brief',['Claim','Source','Evidence type','Stance','Observation'],rows.map(r=>[r.claim,r.source,r.type,r.stance,r.observation]),['A vendor claim or launch vote is not payment evidence. Customer entries are your records, not independently verified interviews.',contra?'Counterevidence recorded: '+contra:'No counterevidence entered; actively look for alternatives and failed attempts.'],{text:`Buyer: ${d.buyer}\nRepeated task: ${d.task}\nCurrent alternative: ${d.alternative}\nNext test: ${d.test}\nStop condition: ${d.stop}\n\nUnknown until measured: reachable demand, paid conversion, support cost and repeat purchase.`});},
 'modelmeter-reconcile':d=>{const rows=records(d.bills,['id','provider','period','currency','expected','billed']),seen=new Set(),tol=num(d.tolerance,'Tolerance');return report('AI billing reconciliation',['Entry','Provider','Period','Currency','Expected','Billed','Difference','Review'],rows.map(r=>{const a=num(r.expected,'Expected',-1e12),b=num(r.billed,'Billed',-1e12),key=r.provider+'|'+r.period+'|'+r.id,flags=[];if(seen.has(key))flags.push('Duplicate entry');seen.add(key);if(Math.abs(b-a)>tol)flags.push('Outside tolerance');if(a<0||b<0)flags.push('Credit / adjustment');return[r.id,r.provider,r.period,r.currency,money(a),money(b),money(b-a),flags.join('; ')||'Within tolerance'];}),['Expected spend must come from your own normalized usage calculation. No provider account is accessed. Differences may reflect tax, credits, currency or billing-period cutoffs.','Duplicate entries are flagged; totals must not be approved until duplicates are resolved.']);},
 'workflowcost':d=>{const runs=num(d.runs,'Monthly runs',1,1e8),base=num(d.input)/1e6*num(d.inputrate)+num(d.output)/1e6*num(d.outputrate)+num(d.other),p=num(d.failure,'Failure probability',0,0.99),retry=num(d.retries,'Retries',0,10);if(!Number.isInteger(retry))throw Error('Retries must be a whole number.');const attempts=Array.from({length:retry+1},(_,i)=>p**i).reduce((a,b)=>a+b,0),success=1-p**(retry+1),labor=num(d.minutes)/60*num(d.hourly),fixed=num(d.fixed);const total=runs*(base*attempts+labor)+fixed;return report('Workflow delivery cost',['Measure','Value'],[['One attempt cost',money(base)],['Expected attempts per run',attempts.toFixed(4)],['Completion probability',(success*100).toFixed(2)+'%'],['Monthly execution cost',money(runs*base*attempts)],['Monthly human review cost',money(runs*labor)],['Fixed monthly cost',money(fixed)],['Monthly total',money(total)],['Cost per expected completed run',money(total/(runs*success))]],['All money inputs must use the same currency. Failure probability is assumed constant and independent per attempt; correlated outages violate that assumption.','Human review minutes apply once per submitted run. Provider prices are your inputs, not a maintained price feed.']);},
 'job-evidence':d=>{const rows=records(d.mapping,['requirement','evidence','source','result']);return report('Application evidence map',['Requirement','Your evidence','Source / file reference','Observed result','Next action'],rows.map(r=>[r.requirement,r.evidence,r.source,r.result,!r.evidence?'Find a real project or acknowledge the gap':!r.source?'Attach a checkable artifact':!r.result?'Describe what you actually delivered':'Review wording for accuracy']),['No experience, qualifications, hiring probabilities or employer endorsements are generated. Local file references need not be public.'],{text:`Target role: ${d.role}\nPortfolio cover note: Select two relevant artifacts, explain your personal contribution, show the original result and name its limitations. Do not attach confidential employer data.`});},
 'scamchecklist':d=>{const checks=[['urgency','Artificial urgency','Pause; contact the organization through a independently known channel.'],['payment','Unusual payment demand','Do not send money based solely on this message. Verify through an established channel.'],['secret','Request for codes or secrets','Do not share one-time codes, passwords or wallet recovery phrases.'],['link','Unexpected link or attachment','Use a saved official address or phone number instead of the supplied link.'],['identity','Unverified identity','Verify who is asking using contact information you already trust.'],['remote','Remote-access request','Do not install remote-access software on an unsolicited request.']];const flagged=checks.filter(([k])=>d[k]==='yes');return report('Verification checklist',['Signal','Your response','Next step'],checks.map(([k,n,a])=>[n,d[k]==='yes'?'Present':'Not reported',d[k]==='yes'?a:'Absence of this signal does not establish safety.']),[`${flagged.length} selected warning signals. This is a checklist, not a verdict that a message is safe or fraudulent.`,'If you already disclosed information or paid, contact the account provider using its official channel and report the incident.'],{links:[['FTC: Recognize and avoid phishing','https://consumer.ftc.gov/articles/how-recognize-and-avoid-phishing-scams']]});}
};
// Original 4x4 Latin/Sudoku-style puzzles with 2x2 boxes and a verified unique solution.
export function solutions(grid,limit=2){let count=0;function solve(a){const p=a.indexOf(0);if(p<0){count++;return;}const r=p>>2,c=p%4;for(let v=1;v<=4&&count<limit;v++){if(a.some((x,i)=>x===v&&((i>>2)===r||i%4===c||((i>>2)>>1)===(r>>1)&&((i%4)>>1)===(c>>1))))continue;a[p]=v;solve(a);a[p]=0;}}solve([...grid]);return count;}
export function puzzle(seed){let state=Array.from(String(seed)).reduce((n,c)=>Math.imul(n^c.charCodeAt(0),16777619)>>>0,2166136261);const random=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/4294967296;};const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};const digits=shuffle([1,2,3,4]);const bands=shuffle([0,1]);const rows=bands.flatMap(b=>shuffle([b*2,b*2+1]));const stacks=shuffle([0,1]);const cols=stacks.flatMap(b=>shuffle([b*2,b*2+1]));const solution=rows.flatMap(r=>cols.map(c=>digits[(r*2+Math.floor(r/2)+c)%4]));const grid=[...solution];for(const i of shuffle([...Array(16).keys()])){const previous=grid[i];grid[i]=0;if(solutions(grid)!==1)grid[i]=previous;}return {seed:String(seed),grid,solution};}
