import {test} from 'node:test';
import assert from 'node:assert/strict';
import {csv,csvOut,day,ics,engines,puzzle,solutions} from './core.mjs';
import {products,href} from './catalog.mjs';
import {projects} from './projects.mjs';
import init from 'sql.js';
const sample=id=>Object.fromEntries(products.find(p=>p.id===id).fields.map(f=>[f.key,f.value]));
test('all 24 products have unique destinations and runnable engines or interactive modes',()=>{assert.equal(products.length,24);assert.equal(new Set(products.map(href)).size,24);for(const p of products){if(!p.kind){const r=engines[p.id](sample(p.id));assert.ok(r.rows.length>0,p.id);assert.ok(r.notes.length>0,p.id);}}});
test('CSV roundtrips quoted newlines and protects spreadsheet formulas',()=>{assert.deepEqual(csv('a,b\n"one,two","line\nnext"'),[{a:'one,two',b:'line\nnext'}]);assert.throws(()=>csv('a,a\n1,2'));assert.throws(()=>csv('__proto__,b\n1,2'));assert.throws(()=>csv('a,b\n1'));assert.match(csvOut([['=1+1','-cmd','@SUM(A1)']]),/"'=1\+1"/);assert.match(csvOut([['-cmd']]),/'-cmd/);});
test('annual tariff arithmetic and mixed-currency rejection',()=>{const d=sample('billlens'),r=engines.billlens(d);assert.deepEqual(r.rows.map(x=>x[5]),['1004.00','1056.00']);assert.throws(()=>engines.billlens({...d,tariffs:d.tariffs.replace('B,EUR','B,USD')}));});
test('meter reset and unequal intervals are not negative consumption',()=>{const r=engines['homeenergy-log']({readings:'date,meter,reading_kwh\n2026-01-01,A,100\n2026-01-11,A,130\n2026-01-12,A,2'});assert.equal(r.rows[1][4],'3.000');assert.equal(r.rows[2][3],'Reset / review');assert.throws(()=>day('2026-02-30'));});
test('invoice historical gaps and changed currencies do not pass silently',()=>{const d=sample('tradecheck-team');const r=engines['tradecheck-team']({...d,history:'',orders:d.orders.replace('USD','EUR')});assert.match(r.rows[0][6],/Currency mismatch/);assert.match(r.rows[0][6],/unavailable/);});
test('calendar offsets convert and calendar text cannot inject properties',()=>{const out=ics([{title:'A\nEND:VEVENT',when:'2026-10-01T18:00:00+02:00',source:'https://example.com'}]);assert.match(out,/DTSTART:20261001T160000Z/);assert.match(out,/SUMMARY:A\\nEND:VEVENT/);assert.throws(()=>ics([{title:'A',when:'2026-10-01T18:00:00',source:'https://example.com'}]));});
test('translation placeholders cannot disappear unnoticed',()=>{const r=engines['localebatch-qa']({translations:'id,field,locale,source,target\n1,title,de,Hello {name},Hallo'});assert.match(r.rows[0][4],/Placeholder mismatch/);});
test('original puzzle seeds produce valid uniquely solvable boards',()=>{for(let i=0;i<100;i++){const p=puzzle('test-'+i);assert.equal(solutions(p.grid),1);for(let r=0;r<4;r++)assert.equal(new Set(p.solution.slice(r*4,r*4+4)).size,4);for(let c=0;c<4;c++)assert.equal(new Set([0,1,2,3].map(r=>p.solution[r*4+c])).size,4);}assert.deepEqual(puzzle('same'),puzzle('same'));});
test('SQL projects execute and catch their intended join/grouping edge cases',async()=>{const SQL=await init();const expected=[[['Aster',80],['Birch',60],['Dune',30],['Cedar',0]],[['A-10',9,12],['D-40',0,3]],[['Alto','001',2,200],['Boreal','003',3,90]]];projects.forEach((p,i)=>{const db=new SQL.Database();db.run(p.setup);assert.deepEqual(db.exec(p.answer)[0].values,expected[i]);db.close();});});

test('localized product metadata, labels, methods and report notes are translated',async()=>{const fs=await import('node:fs');const {siteLanguages,translator,route}=await import('./i18n.mjs');const {formulas}=await import('./methods.mjs');let count=0;for(const p of products)for(const lang of siteLanguages[p.site]){count++;assert.ok(route(p.site,lang,p.id).includes(p.id));if(lang==='en')continue;const d=JSON.parse(fs.readFileSync(new URL('./locales/'+lang+'.json',import.meta.url))),t=translator(d,lang);assert.ok(d['title:'+p.id],lang+' title '+p.id);for(const key of [p.description,formulas[p.id],...p.fields.map(f=>f.label),...p.fields.flatMap(f=>(f.options||[]).map(o=>o[1]))])assert.ok(d[key],lang+' '+key);if(!p.kind){const r=engines[p.id](sample(p.id));for(const key of [r.title,...r.columns,...r.notes])if(key!=='#'&&!Object.hasOwn(d,key))assert.notEqual(t(key),key,lang+' '+key);}}assert.equal(count,51);});
test('language paths and visible numbers use the correct locale without changing units',async()=>{const {route,displayNumber,translator}=await import('./i18n.mjs');assert.equal(route('bpj','zh','creatorops'),'/workbench/creatorops');assert.equal(route('bpj','en','creatorops'),'/en/workbench/creatorops');assert.equal(route('eco','de','billlens'),'/workbench/billlens.html');assert.equal(displayNumber('1004.00','de'),'1.004,00');assert.equal(displayNumber('1004.00','en'),'1,004.00');assert.equal(displayNumber('2026-09-19','de'),'2026-09-19');assert.equal(translator({},'de')('Missing CSV column: meter'),'Fehlende CSV-Spalte: meter');const r=engines.appliancepayback(sample('appliancepayback'));assert.equal(r.rows[0][1],'0.2250');assert.equal(r.rows[0][3],'29.70');});
