import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {products,sites} from './catalog.mjs';
import {siteLanguages,languages,route,translator} from './i18n.mjs';
const args=process.argv.slice(2),site=args[args.indexOf('--site')+1],s=sites[site],live=args.includes('--live'),out=args.includes('--out')?path.resolve(args[args.indexOf('--out')+1]):null;
assert.ok(s,'Choose a site');const own=products.filter(p=>p.site===site),expected=siteLanguages[site].flatMap(lang=>[null,...own].map(p=>({url:s.origin+route(site,lang,p?.id||''),p,lang})));
async function get(url,html=true){if(!live){let route=new URL(url).pathname.replace(/^\//,'');if(html&&!route.endsWith('.html'))route+='.html';return fs.readFileSync(path.join(out,route),'utf8');}let error;for(let i=0;i<5;i++){try{const r=await fetch(url,{signal:AbortSignal.timeout(20000),headers:{'User-Agent':'workbench-release-check/2.0'}});if(!r.ok)throw Error(`${r.status}: ${url}`);return await r.text();}catch(e){error=e;if(i<4)await new Promise(r=>setTimeout(r,4000));}}throw error;}
const pages=new Map();for(const item of expected){const html=await get(item.url);pages.set(item.url,html);assert.ok(html.includes(`data-product="${item.p?.id||''}"`),`Wrong page: ${item.url}`);assert.ok(html.includes('data-edition="2026-09-19.2"'),'Old build: '+item.url);assert.ok(html.includes(`lang="${languages[item.lang].tag}"`),'Wrong language');assert.ok(html.includes(`rel="canonical" href="${item.url}"`),`Canonical mismatch ${item.url}`);assert.ok(!html.includes('noindex'),'Unexpected noindex');for(const l of siteLanguages[site])assert.ok(html.includes(`hreflang="${languages[l].tag}" href="${s.origin+route(site,l,item.p?.id||'')}"`),'Incomplete hreflang mesh: '+item.url);assert.ok(html.includes('hreflang="x-default"'));if(item.p){assert.ok(html.includes('id="method"'),'Missing static method');assert.ok(html.includes('id="sharing"'));assert.ok(html.includes('application/ld+json'));const md=await get(item.url.replace(/\.html$/,'')+'.md',false);assert.ok(md.includes('Canonical: '+item.url),'Missing Markdown provenance');}console.log('OK '+item.lang+' '+item.url);}
const sitemap=await get(s.origin+'/sitemap.xml',false);for(const item of expected)assert.ok(sitemap.includes('<loc>'+item.url+'</loc>'),'Missing sitemap entry');
for(const asset of ['app.mjs','core.mjs','catalog.mjs','projects.mjs','i18n.mjs','style.css','sql-worker.js','vendor/sql-wasm.js','vendor/sql-wasm.wasm',...siteLanguages[site].map(l=>'locales/'+l+'.json')]){if(live){const r=await fetch(s.origin+'/workbench-assets/'+asset,{signal:AbortSignal.timeout(20000)});assert.equal(r.status,200,asset);assert.ok(!(r.headers.get('content-type')||'').includes('text/html'),'Asset returned HTML: '+asset);assert.ok((await r.arrayBuffer()).byteLength>100,asset);}else assert.ok(fs.statSync(path.join(out,'workbench-assets',asset)).size>100,asset);}
console.log(`${site}: ${own.length} tools / ${expected.length} localized pages, reciprocal hreflang, text mirrors, sitemap and runtime assets passed (${live?'production':'build'}).`);
