import {execFile} from 'node:child_process';import {promisify} from 'node:util';import os from 'node:os';
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(require.resolve('playwright',{paths:[path.resolve('tools/revenue-studio/node_modules'),process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES].filter(Boolean)}));const root=path.resolve('sites/agiscorecard');
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');let file=path.join(root,url.pathname);if(!path.extname(file))file+='.html';if(!file.startsWith(root+path.sep))return res.writeHead(403).end();try{const data=fs.readFileSync(file);res.writeHead(200,{'Content-Type':({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.png':'image/png'})[path.extname(file)]||'text/plain'});res.end(data);}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
let launch={headless:true};if(process.env.EARN_CHROMIUM){const mod=require(process.env.EARN_CHROMIUM),c=mod.default||mod;launch={headless:true,args:c.args.filter(a=>!['--disable-web-security','--single-process'].includes(a)),executablePath:process.env.EARN_EXECUTABLE||await c.executablePath()};}const browser=await chromium.launch(launch);
try{for(const lang of ['en','zh']){const prefix=lang==='zh'?'/zh':'',context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{if(r.request().url().startsWith(base))return r.continue();external.push(r.request().url());return r.abort();});
await page.goto(base+prefix+'/earn');await page.waitForFunction(()=>document.querySelector('#result-count').textContent.length>0);assert.equal(await page.locator('.case-card:visible').count(),9);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(external,[]);await page.screenshot({path:'/tmp/earn-'+lang+'-mobile.png',fullPage:true});
await page.locator('#platform').selectOption('tiktok');assert.equal(await page.locator('.case-card:visible').count(),2);await page.locator('#platform').selectOption('all');await page.locator('#search').fill('n8n');assert.equal(await page.locator('.case-card:visible').count(),1);await page.locator('#search').fill('');await page.locator('[data-save="clip-service"]').click();await page.locator('#saved-only').click();assert.equal(await page.locator('.case-card:visible').count(),1);await page.reload();await page.locator('#saved-only').click();assert.equal(await page.locator('.case-card:visible').count(),1);
await page.locator('#video-url').fill('https://www.tiktok.com/@scout2015/video/6718335390845095173');await page.locator('#video-form button').click();assert.equal(await page.locator('.private-video').count(),1);assert.deepEqual(external,[]);await page.locator('.private-video button').first().click();const frame=page.locator('.private-video iframe');assert.match(await frame.getAttribute('src'),/^https:\/\/www.tiktok.com\/player\/v1\/6718335390845095173\?autoplay=0/);await page.locator('.private-video button').last().click();assert.equal(await page.locator('.private-video').count(),0);
await page.goto(base+prefix+'/earn/cases/clip-service');await page.waitForFunction(()=>document.querySelector('.result-main'));assert.equal(await page.locator('iframe').count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#load-example').click();await page.locator('[name=buyer]').fill(lang==='zh'?'测试买家':'Test buyer');await page.locator('[name=price]').fill('100');assert.ok(await page.locator('.negative').count());await page.locator('[name=gate0]').check();await page.locator('#save-project').click();await page.reload();assert.equal(await page.locator('[name=buyer]').inputValue(),lang==='zh'?'测试买家':'Test buyer');assert.equal(await page.locator('[name=gate0]').isChecked(),true);
const [backup]=await Promise.all([page.waitForEvent('download'),page.locator('#export-backup').click()]);const data=JSON.parse(fs.readFileSync(await backup.path(),'utf8'));assert.equal(data.inputs.price,'100');assert.equal(data.inputs.gate0,true);const [plan]=await Promise.all([page.waitForEvent('download'),page.locator('#export-plan').click()]);const text=fs.readFileSync(await plan.path(),'utf8');assert.ok(text.includes('100'));assert.ok(text.includes('Kevin Stratvert'));assert.ok(text.includes('https://agiscorecard.com'));assert.ok(text.includes(lang==='zh'?'测试买家':'Test buyer'));
await page.locator('[name=fee]').fill('80');await page.locator('[name=margin]').fill('30');assert.equal(await page.locator('.result-main').count(),0);page.once('dialog',d=>d.accept());await page.locator('#import-backup').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.waitForFunction(()=>document.querySelector('.result-main'));assert.equal(await page.locator('[name=fee]').inputValue(),'3');await page.screenshot({path:'/tmp/earn-case-'+lang+'-mobile.png',fullPage:true});
await page.locator('.load-video').click();assert.match(await page.locator('.watch iframe').getAttribute('src'),/youtube-nocookie.com\/embed\/Dk1TxDKzb68\?autoplay=0/);assert.equal(await page.locator('.watch iframe').getAttribute('referrerpolicy'),'strict-origin-when-cross-origin');
await page.goto(base+prefix+'/earn/cases/clip-service?embed=1');await page.waitForFunction(()=>document.body.classList.contains('embed'));assert.equal(await page.locator('header').isVisible(),false);assert.equal(await page.locator('#project').isVisible(),true);assert.equal(await page.locator('.watch').isVisible(),false);
await page.goto(base+prefix+'/earn');await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:'/tmp/earn-'+lang+'-desktop.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);
if(process.env.EARN_RENDER_CARDS){await page.setViewportSize({width:1200,height:630});await page.setContent(`<html lang="${lang}"><head><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;background:${lang==='zh'?'#ffffff':'#0a0a0b'};color:${lang==='zh'?'#1b2030':'#eeeef4'};font-family:Arial,'Noto Sans CJK SC',sans-serif;padding:60px 72px}p{font-size:26px;color:${lang==='zh'?'#002fa7':'#a69bff'}}h1{font-size:64px;line-height:1.18;max-width:990px;margin:35px 0}footer{margin-top:44px;border-top:2px solid #777;padding-top:30px;font-size:27px}.brand{font-size:22px}span{display:inline-block;margin-right:25px;padding:12px 22px;border:1px solid #777;border-radius:8px}</style></head><body><div class="brand">AGI Scorecard / ${lang==='zh'?'用 AI 赚钱':'Earn with AI'}</div><h1>${lang==='zh'?'看懂 AI 案例，<br>做出值得付费的成果。':'Turn an AI tutorial<br>into a useful client project.'}</h1><p>${lang==='zh'?'精选视频 · 原创项目方案 · 真实成本测算':'Sourced videos · Original briefs · Real delivery costs'}</p><footer><span>${lang==='zh'?'免费观看':'Watch free'}</span><span>${lang==='zh'?'制定计划':'Plan a delivery'}</span><span>${lang==='zh'?'导出成果':'Export your plan'}</span></footer></body></html>`);await page.screenshot({path:path.join(root,'earn-assets/share-'+lang+'.png')});}
await page.goto(base+prefix+'/earn');await page.locator('#platform').selectOption('github');assert.equal(await page.locator('.case-card:visible').count(),3);
await page.goto(base+prefix+'/earn/open-source');assert.equal(await page.locator('tbody tr').count(),10);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
external.length=0;await page.goto(base+prefix+'/earn/delivery-lab');await page.locator('#check-example').click();await page.locator('#run-check').click();assert.ok((await page.locator('#check-results').textContent()).includes(lang==='zh'?'重叠':'Overlapping'));const [findings]=await Promise.all([page.waitForEvent('download'),page.locator('#download-check').click()]);assert.ok(fs.readFileSync(await findings.path(),'utf8').includes(lang==='zh'?'结构性':'structural'));await page.locator('#save-check').click();assert.equal(await page.locator('#check-history li').count(),1);const stored=await page.evaluate(()=>localStorage.getItem('agi-delivery-history-v1'));assert.ok(!stored.includes('Hello')&&!stored.includes('issues'));await page.reload();assert.equal(await page.locator('#check-history li').count(),1);await page.locator('#check-input').fill('1\n00:00:01,000 --> 00:00:02,000\nHello\n\n2\n00:00:03,000 --> 00:00:04,000\nWorld');await page.locator('#run-check').click();await page.locator('#save-check').click();await page.locator('#compare-checks').click();assert.ok((await page.locator('#comparison-results').textContent()).includes('→'));await page.locator('#check-cps').fill('30');assert.equal(await page.locator('#save-check').isDisabled(),true);await page.locator('#run-check').click();await page.locator('#save-check').click();await page.locator('#compare-checks').click();assert.ok((await page.locator('#comparison-results').textContent()).includes(lang==='zh'?'不可对比':'Not comparable'));const [summaries]=await Promise.all([page.waitForEvent('download'),page.locator('#backup-checks').click()]);const summaryText=fs.readFileSync(await summaries.path(),'utf8');assert.ok(!summaryText.includes('World'));await page.locator('#import-checks').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{}')});assert.equal(await page.locator('#check-history li').count(),3);page.once('dialog',d=>d.accept());await page.locator('#clear-checks').click();assert.equal(await page.locator('#check-history li').count(),0);await page.locator('#import-checks').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(summaryText)});await page.waitForFunction(()=>document.querySelectorAll('#check-history li').length===3);assert.equal(await page.locator('#check-history li').count(),3);await page.reload();assert.equal(await page.locator('#check-history li').count(),3);
await page.locator('#check-input').fill('<script>alert(1)</script>');assert.equal(await page.locator('#download-check').isDisabled(),true);await page.locator('#run-check').click();assert.equal(await page.locator('#check-results script').count(),0);
await page.locator('#check-mode').selectOption('workflow');await page.locator('#check-example').click();await page.locator('#run-check').click();assert.ok((await page.locator('#check-results').textContent()).includes(lang==='zh'?'重复':'Duplicate'));await page.locator('#check-expected').fill('2');assert.equal(await page.locator('#download-check').isDisabled(),true);await page.locator('#run-check').click();assert.ok((await page.locator('#check-results').textContent()).includes(lang==='zh'?'低于预期':'Fewer'));await page.locator('#check-input').fill('wrong,headers');await page.locator('#run-check').click();assert.equal(await page.locator('#download-check').isDisabled(),true);assert.deepEqual(external,[]);await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/earn-lab-'+lang+'.png',fullPage:true});assert.deepEqual(errors,[]);
await context.close();console.log(lang+': responsive layout, filters, persistent saves, private TikTok embed, quote math, restore, exports, click-only video and embed mode passed');}
const auditDir=fs.mkdtempSync(path.join(os.tmpdir(),'earn-audit-fixture-'));const run=await promisify(execFile)(process.execPath,[path.join(root,'earn-assets/launch-audit.mjs'),'--authorized',base,'/earn'],{cwd:auditDir,env:{...process.env,EARN_PLAYWRIGHT:require.resolve('playwright',{paths:[path.resolve('tools/revenue-studio/node_modules'),process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES].filter(Boolean)})}});const out=run.stdout.trim().replace('Local report: ','');const baseline=JSON.parse(fs.readFileSync(out,'utf8'));assert.equal(baseline.pages.length,2);assert.ok(baseline.pages.every(x=>x.status===200&&!x.error&&x.screenshot&&x.checks.title));console.log('Website CLI: actual phone/desktop fixture navigation, screenshots and JSON report passed.');
}finally{await browser.close();server.close();}
