import {createRequire} from 'node:module';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {createRoute} from './server.mjs';import {ensure} from './store.mjs';import {sample} from '../../create-assets/core.mjs';import {database} from './test-support.mjs';
const require=createRequire(import.meta.url),{chromium}=require(require.resolve('playwright',{paths:[path.resolve('tools/revenue-studio/node_modules'),process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES].filter(Boolean)}));
const root=path.resolve('sites/agiscorecard'),db=database();let ipIndex=0;await ensure(db);
function asset(req){const u=new URL(req.url);let p=path.join(root,u.pathname);if(!path.extname(p))p+='.html';if(!p.startsWith(root+path.sep))return new Response('',{status:403});try{return new Response(fs.readFileSync(p),{headers:{'Content-Type':({'.html':'text/html','.css':'text/css','.mjs':'text/javascript','.png':'image/png'})[path.extname(p)]||'text/plain'}});}catch{return new Response('',{status:404});}}
const env={EVENTS:db,MEMBER_WATCH_SECRET:'local-test-fixture',AI:{run:async(_m,b)=>({response:sample(b.messages[0].content.includes('Chinese')?'zh':'en','cafe')})},ASSETS:{fetch:asset}};
const server=http.createServer(async(req,res)=>{try{const chunks=[];for await(const c of req)chunks.push(c);const headers={...req.headers,'CF-Connecting-IP':'browser-'+ipIndex};const r=new Request('http://127.0.0.1:'+server.address().port+req.url,{method:req.method,headers,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(chunks)}:{})});const out=await createRoute(r,env)||asset(r);res.writeHead(out.status,Object.fromEntries(out.headers));res.end(Buffer.from(await out.arrayBuffer()));}catch(e){console.error(e);res.writeHead(500).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
let launch={headless:true};if(process.env.RELAY_CHROMIUM){const module=require(process.env.RELAY_CHROMIUM),c=module.default||module;launch={headless:true,args:c.args.filter(a=>!["--disable-web-security","--single-process"].includes(a)),executablePath:await c.executablePath()};}
const browser=await chromium.launch(launch);
try{for(const lang of ['en','zh']){ipIndex++;const before=db.sqlite.prepare('SELECT COUNT(*) n FROM relay_events').get().n;const ctx=await browser.newContext({viewport:{width:390,height:844}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());const p=(lang==='zh'?'/zh':'')+'/create';await page.goto(base+p);await page.waitForFunction(()=>document.querySelector('#story-title').textContent.length>0);
assert.ok(await page.locator('#story-title').textContent());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.screenshot({path:'/tmp/relay-'+lang+'-mobile.png',fullPage:true});await page.locator('#start').click();for(let i=0;i<3;i++){await page.locator('#game .choice').nth(i%2).click();await page.locator('#game > .primary').click();}assert.equal(await page.locator('.result-title').count(),1);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM relay_events').get().n,before);
await page.locator('#remix').click();await page.locator('#title').fill(lang==='zh'?'我的月球冒险':'My moon adventure');await page.locator('#author').fill('Creator QA');await page.locator('#save').click();await page.reload();await page.waitForFunction(()=>!document.querySelector('#create-panel').hidden);assert.equal(await page.locator('#title').inputValue(),lang==='zh'?'我的月球冒险':'My moon adventure');
await page.locator('#preview').click();assert.equal(await page.locator('#share').isVisible(),false);await page.locator('#tab-create').click();await page.locator('#publish-consent').check();await page.locator('#publish').click();await page.waitForFunction(()=>!document.querySelector('#published').hidden||document.querySelector('#status').classList.contains('error'));assert.equal(await page.locator('#published').isVisible(),true,await page.locator('#status').textContent());const link=await page.locator('#published-link').getAttribute('href');assert.ok(/\/create\/[a-f0-9]{32}$/.test(link));
const visitor=await browser.newContext({viewport:{width:390,height:844}}),v=await visitor.newPage();await v.goto(link);await v.waitForFunction(()=>!document.querySelector('#start').disabled);assert.match(await v.locator('#story-title').textContent(),lang==='zh'?/月球/:/moon/);await v.locator('#tab-create').click();await v.locator('#title').fill(lang==='zh'?'朋友的月球冒险':'Friend’s moon adventure');await v.locator('#author').fill('Friend QA');await v.locator('#preview').click();await v.locator('#tab-create').click();await v.locator('#publish-consent').check();await v.locator('#publish').click();await v.waitForFunction(()=>!document.querySelector('#published').hidden);const remixLink=await v.locator('#published-link').getAttribute('href');await v.goto(remixLink);await v.waitForFunction(()=>document.querySelector('#lineage a'));assert.equal(await v.locator('#lineage a').getAttribute('href'),link);assert.ok(!await v.locator('#measure').isChecked());await v.locator('#measure').check();await v.locator('#start').click();for(let i=0;i<3;i++){await v.locator('#game .choice').first().click();await v.locator('#game > .primary').click();}await v.waitForTimeout(100);assert.ok(db.sqlite.prepare('SELECT COUNT(*) n FROM relay_events').get().n>0);
await page.locator('.saved summary').click();page.once('dialog',d=>d.accept());await page.locator('.saved-row button').first().click();await page.waitForFunction(()=>document.querySelectorAll('.saved-row').length===0);const gone=await page.request.get(link);assert.equal(gone.status(),404);await v.reload();await v.waitForFunction(()=>document.querySelector('#lineage').textContent.length>0);assert.equal(await v.locator('#lineage a').count(),0);await visitor.close();
await page.goto(base+p);await page.locator('#prompt').fill('Two friends discover a robot café on the moon');await page.locator('#ai-consent').check();await page.locator('#generate').click();await page.waitForFunction(()=>document.querySelector('#title').value.includes('café')||document.querySelector('#title').value.includes('咖啡'));assert.ok(!await page.locator('#generate').isDisabled());
await page.setViewportSize({width:1365,height:1000});await page.locator('#tab-play').click();await page.screenshot({path:'/tmp/relay-'+lang+'-desktop.png',fullPage:true});assert.deepEqual(errors,[]);await ctx.close();console.log(lang+': full play, edit, persisted draft, AI fixture, publish, fresh visitor, remix provenance after preview, opt-in telemetry and owner deletion passed');}
}finally{await browser.close();server.close();db.sqlite.close();}
