from pathlib import Path
import json, html
ROOT=Path(__file__).resolve().parents[2]
COPY=json.loads((ROOT.parent.parent/'tools/marketing/relay-friends-01/content.json').read_text())
def section(lang):
 t=COPY[lang]; p='/zh' if lang=='zh' else ''
 return f'''<section class="story-guide" aria-labelledby="guide-title"><h2 id="guide-title">{t['how']}</h2><p class="capsule">{t['capsule']}</p><ol>{''.join('<li>'+s+'</li>' for s in t['steps'])}</ol><p><a href="{p}/relay-demo">{t['watch']}</a></p><h2>{'常见问题' if p else 'Frequently asked questions'}</h2>{''.join('<div class="faq-q">'+q+'</div><p>'+a+'</p>' for q,a in t['faq'])}<div class="updated">{'核对日期：2026年9月30日' if p else 'Reviewed: September 30, 2026'}</div></section>'''
def app_schema(lang,path):
 t=COPY[lang]
 return {'@context':'https://schema.org','@type':'WebApplication','name':'接力' if lang=='zh' else 'Relay','url':'https://agiscorecard.com'+path,'description':t['capsule'],'applicationCategory':'EntertainmentApplication','operatingSystem':'Web browser','inLanguage':lang,'isAccessibleForFree':True}
def build_watch():
 for lang,t in COPY.items():
  zh=lang=='zh';pre='/zh' if zh else '';url='https://agiscorecard.com'+pre+'/relay-demo';asset='/create-assets/media/relay-'+lang
  schema={'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'接力' if zh else 'Relay','item':'https://agiscorecard.com'+pre+'/create'},{'@type':'ListItem','position':2,'name':t['watch'],'item':url}]}
  page=f'''<!doctype html><html lang="{'zh-Hans' if zh else 'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{t['watchTitle']}</title><meta name="description" content="{t['watchDesc']}"><link rel="canonical" href="{url}"><link rel="alternate" hreflang="en" href="https://agiscorecard.com/relay-demo"><link rel="alternate" hreflang="zh-Hans" href="https://agiscorecard.com/zh/relay-demo"><link rel="alternate" hreflang="x-default" href="https://agiscorecard.com/relay-demo"><meta property="og:title" content="{t['watchTitle']}"><meta property="og:description" content="{t['watchDesc']}"><meta property="og:image" content="https://agiscorecard.com{asset}-poster.jpg"><meta property="og:url" content="{url}"><meta property="og:type" content="website"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/create-assets/style.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head><body><header><a class="brand" href="{pre}/create">{'接力' if zh else 'Relay'}</a><nav><a href="{'/cn' if zh else '/'}">{'AGI 首页' if zh else 'AGI Scorecard'}</a><a href="{'/relay-demo' if zh else '/zh/relay-demo'}">{'English' if zh else '中文'}</a></nav></header><main class="watch-page"><h1>{t['watchTitle']}</h1><div class="watch-layout"><img src="{asset}-poster.jpg" alt="{t['sceneTitles'][0]}" width="720" height="1280" style="max-width:100%;height:auto"><div><p class="capsule">{t['watchDesc']}</p><p><a class="video-cta" href="{pre}/create?starter=cafe&amp;utm_source=demo&amp;utm_medium=owned_video&amp;utm_campaign=relay-friends-01">{t['cta']}</a></p><p><a href="{pre}/create#guide-title">{t['guide']}</a></p></div></div><section class="story-guide"><h2>{t['transcript']}</h2>{''.join('<div class="faq-q">'+title+'</div><p>'+caption+'</p>' for title,caption in zip(t['sceneTitles'],t['captions']))}<p>{'AI 每个网络每日最多 3 次，全站滚动 24 小时最多 12 次；失败也计入。作品不进入公开列表，但获得链接的人均可读取与复制。' if zh else 'AI: up to 3 requests per network per UTC day and 12 sitewide in a rolling 24 hours, including failures. Links are unlisted; anyone with one can read and copy the story.'}</p><div class="updated">{'核对日期：2026年9月30日' if zh else 'Reviewed: September 30, 2026'}</div></section></main><footer><a href="https://agiscorecard.beehiiv.com/subscribe">{'订阅 AGI 周报' if zh else 'AGI newsletter'}</a><a href="/privacy">{'隐私政策' if zh else 'Privacy'}</a></footer></body></html>'''
  (ROOT/(pre.strip('/')+'/' if pre else '')/'relay-demo.html').write_text(page)
if __name__=='__main__':build_watch()
