import test from 'node:test';
import assert from 'node:assert/strict';
import {createRoute} from './server.mjs';
import {sample,validateStory,outcome} from '../../create-assets/core.mjs';
import {database} from './test-support.mjs';
import {hash} from './store.mjs';
const origin='https://agiscorecard.com',key='ab'.repeat(32),nonce='cd'.repeat(16);
function env(){return {EVENTS:database(),MEMBER_WATCH_SECRET:'test-only-not-a-credential',AI:{run:async()=>({response:sample('en')})},ASSETS:{fetch:async()=>new Response('<html>Relay</html>',{headers:{'Content-Type':'text/html'}})}};}
async function call(e,b,opts={}){const r=await createRoute(new Request(origin+'/api/create',{method:'POST',headers:{'Content-Type':'application/json','Origin':opts.origin||origin,'CF-Connecting-IP':opts.ip||'test-ip',...opts.headers},body:JSON.stringify(b)}),e);return {status:r.status,data:await r.json()};}
const publish=(e,extra={},opts={})=>call(e,{action:'publish',story:sample('en'),owner:key,nonce,consent:true,...extra},opts);
test('both languages, two editorial starters and all eight paths have valid outcomes',()=>{for(const l of ['en','zh'])for(const theme of ['island','cafe']){const s=sample(l,theme);for(let n=0;n<8;n++)assert.ok(outcome(s,[n&1,(n>>1)&1,(n>>2)&1]).text);assert.throws(()=>outcome(s,[0,0]));assert.throws(()=>validateStory({...s,title:'<script>alert(1)</script>'}));assert.throws(()=>validateStory({...s,rounds:[s.rounds[0]]}));}});
test('publication is persistent, idempotent, unlisted, owner-only deletion; lineage survives safely',async()=>{const e=env(),a=await publish(e);assert.equal(a.status,200);assert.equal((await publish(e)).data.id,a.data.id);const b=await publish(e,{parent:a.data.id,nonce:'ef'.repeat(16),story:{...sample('zh'),author:'My remix'}});assert.equal(b.status,200);let read=await createRoute(new Request(origin+'/api/create?id='+b.data.id),e),data=await read.json();assert.equal(data.parent.author,'Relay editors');assert.equal(data.depth,1);assert.equal(data.story.lang,'zh');assert.ok(!JSON.stringify(data).includes(key));assert.ok(!JSON.stringify(data).includes('owner_hash'));assert.equal(read.headers.get('X-Robots-Tag'),'noindex');assert.equal((await call(e,{action:'delete',id:a.data.id,owner:'ff'.repeat(32)})).status,403);assert.equal((await call(e,{action:'delete',id:a.data.id,owner:key})).status,200);read=await createRoute(new Request(origin+'/api/create?id='+b.data.id),e);data=await read.json();assert.equal(data.parent,null);assert.equal(data.parent_unavailable,true);assert.equal((await publish(e)).data.code,'deleted');assert.equal((await createRoute(new Request(origin+'/create/'+a.data.id),e)).status,404);assert.equal((await createRoute(new Request(origin+'/create/'+b.data.id),e)).headers.get('X-Robots-Tag'),'noindex, nofollow');e.EVENTS.sqlite.close();});
test('consent, method, origin, size, parent and content checks reject bad input',async()=>{const e=env();assert.equal((await publish(e,{consent:false})).status,400);assert.equal((await publish(e,{}, {origin:'https://attacker.invalid'})).status,403);assert.equal((await publish(e,{parent:'ab'.repeat(16)})).data.code,'parent_unavailable');assert.equal((await publish(e,{story:{...sample(),intro:'x'.repeat(241)}})).status,400);assert.equal((await call(e,{action:'publish',padding:'x'.repeat(18000)})).status,413);assert.equal((await createRoute(new Request(origin+'/api/create',{method:'DELETE'}),e)).status,405);assert.equal((await createRoute(new Request('https://bad.invalid/api/create'),e)).status,403);e.EVENTS.sqlite.close();});
test('AI quota is enforced before inference, invalid model output cannot replace draft',async()=>{const e=env();let calls=0;e.AI.run=async()=>{calls++;return {response:sample('en')};};const b={action:'generate',prompt:'Friendly robots exploring the moon',lang:'en',consent:true};for(let i=0;i<3;i++)assert.equal((await call(e,b)).status,200);assert.equal((await call(e,b)).status,429);assert.equal(calls,3);e.AI.run=async()=>({response:'invalid json'});assert.equal((await call(e,b,{ip:'another'})).data.code,'ai_failed');assert.equal((await call(e,{...b,consent:false},{ip:'another'})).status,400);e.EVENTS.sqlite.close();});
test('global generation quota applies across IPs including failures',async()=>{const e=env();for(let i=0;i<12;i++)assert.equal((await call(e,{action:'generate',prompt:'A friendly robot café',lang:'en',consent:true},{ip:'ip-'+i})).status,200);assert.equal((await call(e,{action:'generate',prompt:'A friendly robot café',lang:'en',consent:true},{ip:'one-more'})).status,429);e.EVENTS.sqlite.close();});
test('telemetry requires consent and deduplicates browser/story/day; reports and admin stay private',async()=>{const e=env(),a=(await publish(e)).data;const event={action:'event',id:a.id,event:'complete',actor:'dd'.repeat(16)};assert.equal((await call(e,event)).status,400);await call(e,{...event,consent:true});await call(e,{...event,consent:true});assert.equal(e.EVENTS.sqlite.prepare('SELECT COUNT(*) n FROM relay_events').get().n,1);assert.equal((await call(e,{action:'report',id:a.id,reason:'privacy'})).status,200);assert.equal((await call(e,{action:'admin'})).status,403);const auth={headers:{Authorization:'Bearer '+await hash(e.MEMBER_WATCH_SECRET+':relay-admin:v1')}};assert.equal((await call(e,{action:'admin',operation:'queue'},auth)).data.reports.length,1);assert.equal((await call(e,{action:'admin',operation:'remove',id:a.id},auth)).status,200);assert.equal((await createRoute(new Request(origin+'/api/create?id='+a.id),e)).status,404);e.EVENTS.sqlite.close();});
