import {PRODUCT,defaults,normalize,stress,dca,leverage} from './core.mjs';
const $=id=>document.getElementById(id),zh=document.body.dataset.language==='zh',t=(en,cn)=>zh?cn:en;
const slot='agi-portfolio-research-v1',colors={basket:'#e0a951',SPY:'#68c9c2',QQQ:'#909bff',TQQQ:'#ed91b4'};
let snapshot=null,cloudContext=null,cloudHandler=null;
const pct=v=>(v>=0?'+':'')+v.toFixed(2)+'%',money=v=>new Intl.NumberFormat(zh?'zh-CN':'en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
const event=action=>{if(new URLSearchParams(location.search).has('__qa'))return;window.dispatchEvent(new CustomEvent('fleet:business',{detail:{name:'portfolio_'+action}}));};
const status=s=>$('status').textContent=s;
function protect(fn){return async(...args)=>{try{await fn(...args);}catch{status(t('Check the numeric ranges, date or record format. Your current record has not been replaced. Export a backup if browser storage is unavailable.','请检查数值范围、日期或记录格式。当前记录未被替换；若本机存储不可用，可导出备份。'));}};}
function record(){return normalize({version:1,product:PRODUCT,values:Object.fromEntries(Object.keys(defaults).map(k=>[k,$(k).value]))});}
function restore(raw){const r=normalize(raw);for(const [k,v]of Object.entries(r.values))$(k).value=v;for(const id of ['stress-result','dca-result','leverage-result'])$(id).textContent='';status(t('Record restored. These are user assumptions, not forecasts.','记录已恢复。这些是用户假设，不是预测。'));}
function download(name,data,type){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('calc-stress').onclick=protect(()=>{const r=stress($('capital').value,$('weight').value,$('shock').value,$('rest').value);$('stress-result').textContent=t('Portfolio shock: ','组合冲击：')+pct(r.returnPct)+'\n'+t('P/L: ','损益：')+money(r.loss)+'\n'+t('Remaining: ','剩余：')+money(r.remaining)+'\n'+t('Gain to recover: ','回本所需涨幅：')+(r.recovery===null?t('No finite gain after total loss','全部损失后无法用有限涨幅回本'):pct(r.recovery));event('stress');});
$('calc-dca').onclick=protect(()=>{const annual=Number($('annual').value);const own=dca($('capital').value,$('monthly').value,$('annual').value,$('years').value);const rows=[annual,0,-5].filter((v,i,a)=>a.indexOf(v)===i).map(v=>{const r=dca($('capital').value,$('monthly').value,v,$('years').value);return v+'% / '+t('year','年')+': '+money(r.balance);});$('dca-result').textContent=t('Total contributed: ','累计投入：')+money(own.contributed)+'\n'+rows.join('\n')+'\n'+t('Scenarios only; none is a predicted outcome.','仅为情景，没有一条是预测结果。');event('dca');});
$('calc-leverage').onclick=protect(()=>{const r=leverage($('path').value);$('leverage-result').textContent=t('Index: ','指数：')+pct(r.index)+'\n'+t('Ideal daily 3×: ','理想每日 3 倍：')+pct(r.levered)+'\n'+t('3 × cumulative index return: ','指数累计回报直接乘 3：')+pct(r.naive);event('leverage');});
for(const k of Object.keys(defaults))$(k).addEventListener('input',()=>{status(t('Unsaved changes in this tab.','当前标签页存在未保存的修改。'));if(!['thesis','counter','review'].includes(k))for(const id of ['stress-result','dca-result','leverage-result'])$(id).textContent='';});
$('save-local').onclick=protect(()=>{localStorage.setItem(slot,JSON.stringify(record()));status(t('Saved in this browser. Shared-device users can read this copy.','已保存在本浏览器，共用设备的使用者可以读取此副本。'));event('save_local');});
$('restore-local').onclick=protect(()=>{const raw=localStorage.getItem(slot);if(!raw){status(t('No local copy yet.','尚无本机副本。'));return;}restore(JSON.parse(raw));cloudContext=null;});
$('erase-local').onclick=protect(()=>{localStorage.removeItem(slot);status(t('Local copy deleted. The open form, downloaded files and cloud records remain.','本机副本已删除；当前表单、已下载文件及云端记录仍保留。'));});
$('export-json').onclick=protect(()=>{download('portfolio-research.json',JSON.stringify(record(),null,2),'application/json');event('export');});
$('import-json').onchange=protect(async e=>{const f=e.target.files[0];try{if(!f)return;if(f.size>60000)throw Error('size');restore(JSON.parse(await f.text()));cloudContext=null;}finally{e.target.value='';}});
$('share').onclick=protect(async()=>{const url=location.origin+(zh?'/zh':'')+'/portfolio-tracker';await navigator.clipboard.writeText(url);$('share').textContent=t('Link copied','链接已复制');event('share');});
$('export-performance').onclick=protect(()=>{if(!snapshot?.dates.length){status(t('No completed entry session yet. The registered rules are available to download.','尚无完整建仓日记录，可下载已登记规则。'));return;}const keys=Object.keys(snapshot.series),rows=['date,'+keys.map(k=>k+'_normalized_100').join(',')];snapshot.dates.forEach((d,i)=>rows.push(d+','+keys.map(k=>snapshot.series[k][i]).join(',')));download('portfolio-gross-normalized.csv',rows.join('\n'),'text/csv');event('performance_export');});
function draw(){const dates=snapshot.dates;if(dates.length<2)return;const svg=$('chart'),ns='http://www.w3.org/2000/svg',keys=Object.keys(colors),values=keys.flatMap(k=>snapshot.series[k]);const min=Math.min(100,...values),max=Math.max(100,...values),pad=Math.max((max-min)*.1,1),lo=min-pad,hi=max+pad;
 function node(tag,attrs,text){const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text)e.textContent=text;svg.append(e);return e;}
 svg.replaceChildren();for(let i=0;i<4;i++){const v=lo+(hi-lo)*i/3,y=250-i*220/3;node('line',{x1:50,x2:885,y1:y,y2:y,stroke:'#616975','stroke-opacity':'.25'});node('text',{x:42,y:y+4,'text-anchor':'end','font-size':12},v.toFixed(1));}
 for(const k of keys){const points=snapshot.series[k].map((v,i)=>(50+i/(dates.length-1)*835)+','+(250-(v-lo)/(hi-lo)*220)).join(' ');node('polyline',{points,fill:'none',stroke:colors[k],'stroke-width':2.5});}
 svg.removeAttribute('hidden');$('chart-empty').hidden=true;$('chart-dates').textContent=dates[0]+' → '+dates.at(-1)+' · '+t('regular-session closes, normalized to 100','正常交易时段收盘，起点归一为 100');}
function render(){const s=snapshot;if(s.version!==1||s.cohort!=='social-basket-2026-10-03'||!Array.isArray(s.dates))throw Error('snapshot');const awaiting=s.status==='awaiting_entry';const overdue=s.as_of&&(Date.now()-Date.parse(s.as_of)>5*86400000);const labels={awaiting_entry:t('Registered. Awaiting the October 5, 2026 entry close (New York). Returns are not available yet.','已登记，等待纽约时间 2026 年 10 月 5 日建仓收盘。目前尚无收益。'),tracking:t('Tracking completed daily closes.','正在追踪已完成交易日的收盘。'),data_unavailable:t('Complete entry data is unavailable. No returns have been created.','完整建仓行情不可用，尚未生成收益。'),stale:t('Refresh failed or data is incomplete. Showing the last complete record.','刷新失败或行情不完整，显示上次完整记录。')};$('data-status').textContent=(labels[s.status]||t('Data unavailable.','数据不可用。'))+(overdue?' '+t('Prices are overdue.','行情已逾期。'):'')+(s.as_of?' '+t('Valuation date: ','估值日期：')+s.as_of:'')+' '+t('Attempted: ','尝试更新：')+s.attempted_at.replace('T',' ').slice(0,19)+' UTC'+(s.errors?.length?' · '+t('Unavailable: ','未获取：')+s.errors.join(', '):'');
 if(awaiting||!s.dates.length)return;
 for(const k of Object.keys(colors)){const m=s.metrics[k];if(!m||!Number.isFinite(m.return_pct))throw Error('metrics');$('metric-'+k).textContent=pct(m.return_pct);$('risk-'+k).textContent=t('Max drawdown ','最大回撤 ')+pct(m.max_drawdown_pct)+' / '+t('vs SPY ','相对 SPY ')+(m.excess_spy_pp>=0?'+':'')+m.excess_spy_pp.toFixed(2)+' pp';}
 for(const el of document.querySelectorAll('[data-return]'))el.textContent=pct(s.metrics[el.dataset.return].return_pct);
 for(const el of document.querySelectorAll('[data-drawdown]'))el.textContent=pct(s.metrics[el.dataset.drawdown].max_drawdown_pct);draw();}
$('save-cloud').onclick=protect(()=>{
 const data=record(),json=JSON.stringify(data),handoff=[...crypto.getRandomValues(new Uint8Array(16))].map(x=>x.toString(16).padStart(2,'0')).join('');
 if(cloudHandler)window.removeEventListener('message',cloudHandler);const target=new URL((zh?'/zh':'')+'/members',location.origin);target.searchParams.set('tool',PRODUCT);target.searchParams.set('from',location.origin);if(new URLSearchParams(location.search).has('__qa'))target.searchParams.set('__qa','1');
 const win=window.open(target.href,'_blank');if(!win){status(t('Allow the member page to open, or export JSON and import it there.','请允许打开会员页，或导出 JSON 后到会员页导入。'));return;}let delivered=false;
 cloudHandler=e=>{if(e.origin!==location.origin||e.source!==win)return;if(e.data?.kind==='workbench-member-ready'&&!delivered){win.postMessage({kind:'workbench-save',data,handoff,context:cloudContext},location.origin);delivered=true;status(t('Draft opened on the member page. Choose Save there to upload.','草稿已交给会员页，请在那里主动点击保存后上传。'));}if(e.data?.kind==='workbench-saved'&&e.data.handoff===handoff&&e.data.product===PRODUCT){cloudContext=e.data.context;status(e.data.same&&JSON.stringify(record())===json?t('This record was saved to your cloud workspace.','此记录已保存到云端工作区。'):t('A cloud version was saved. Later edits may remain unsaved.','一个云端版本已保存，后续修改可能仍未保存。'));}};
 window.addEventListener('message',cloudHandler);const handler=cloudHandler;setTimeout(()=>window.removeEventListener('message',handler),120000);event('cloud_intent');
});
const params=new URLSearchParams(location.search);if(params.get('embed')==='1')document.documentElement.classList.add('embed');
if(params.get('restore')==='1'&&window.opener){const handler=e=>{if(e.source!==window.opener||e.origin!==location.origin||e.data?.kind!=='workbench-restore')return;try{restore(e.data.data);cloudContext=e.data.context;}catch{status(t('Cloud record could not be restored.','云端记录无法恢复。'));}window.removeEventListener('message',handler);};window.addEventListener('message',handler);window.opener.postMessage({kind:'workbench-ready'},location.origin);setTimeout(()=>window.removeEventListener('message',handler),120000);}
try{const r=await fetch('/portfolio-assets/snapshot.json',{cache:'no-cache'});if(!r.ok)throw Error('fetch');snapshot=await r.json();render();}catch{$('data-status').textContent=t('Could not load the public record. Check the downloadable snapshot or try again later. Calculators remain available.','公开记录加载失败，请查看数据文件或稍后再试。计算器仍可使用。');}
