import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
import {database} from '../create/test-support.mjs';import {hash,ensure as ensureRelay} from '../create/store.mjs';import {mentorRoute,ensure as ensureMentor} from '../mentor/server.mjs';import {createRoute} from '../create/server.mjs';import {communityRoute} from '../community/server.mjs';import {ensure as ensureCommunity} from '../community/store.mjs';
import {memberRoute} from '../../../../tools/member-studio/server.mjs';import {validateMemberStatus,checkMemberReleaseHealth} from '../member-release-health.mjs';
const origin='https://agiscorecard.com',secret='release-test-only-secret-not-production',uid='1'.repeat(64),wrong='2'.repeat(64);
function fixture(t){const db=database(),queries=[],native=db.prepare.bind(db);db.prepare=sql=>{queries.push(sql);return native(sql);};t.after(()=>db.sqlite.close());return {db,queries,env:{EVENTS:db,MEMBER_WATCH_SECRET:secret,MEMBERS_ENABLED:'true',MEMBER_WALLET:'0x'+'2'.repeat(40),AI:{run(){throw Error('Unexpected inference');}},ASSETS:{fetch:async()=>new Response('not found',{status:404})}}};}
const request=(path,body,token='',headers={})=>new Request(origin+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'synthetic-release-fixture',...(token?{Authorization:'Bearer '+token}:{}),...headers},body:JSON.stringify(body)});
const noDelete=queries=>assert.ok(!queries.some(q=>/^\s*(?:DELETE|DROP|TRUNCATE)\b/i.test(q)),queries.join('\n'));
const valid=()=>({ok:true,ready:true,site:'agi',chain:'bsc',token:'USDT',auto_renew:false,plan:{id:'agi-workbench-30',site:'agi',price_units:9000000,quote_base:9010000,days:30,workspaces:50,versions:10,max_bytes:65536,total_bytes:5242880,grace_days:30}});
const routes=[{name:'mentor',route:mentorRoute,path:'/api/mentor',read:{action:'admin_readonly'},legacy:{action:'admin'},suffix:':mentor-admin:v1',ensure:ensureMentor,seed:"INSERT INTO mentor_feedback VALUES(date('now','-91 days'),'fixture','other')",table:'mentor_feedback'},
 {name:'create',route:createRoute,path:'/api/create',read:{action:'inspect_stats',operation:'stats'},legacy:{action:'admin',operation:'stats'},suffix:':relay-admin:v1',ensure:ensureRelay,seed:"INSERT INTO relay_events VALUES(date('now','-91 days'),'fixture','fixture','open')",table:'relay_events'},
 {name:'community',route:communityRoute,path:'/api/discuss/admin',read:{action:'stats_readonly'},legacy:{action:'stats'},suffix:':community-moderator:v1',ensure:ensureCommunity,seed:"INSERT INTO discuss_visits VALUES(date('now','-91 days'),'fixture','en','direct')",table:'discuss_visits'}];

test('fixed AGI readiness rejects missing, wrong-type and altered site/rail/plan fields',()=>{
 assert.equal(validateMemberStatus(valid()).ready,true);for(const k of Object.keys(valid())){const d=valid();delete d[k];assert.throws(()=>validateMemberStatus(d));}for(const k of Object.keys(valid().plan)){const d=valid();delete d.plan[k];assert.throws(()=>validateMemberStatus(d));}
 for(const patch of [{ready:false},{ready:'true'},{site:'eco'},{chain:'base-sepolia'},{token:'USDC'},{auto_renew:true}])assert.throws(()=>validateMemberStatus({...valid(),...patch}));for(const k of Object.keys(valid().plan)){const d=valid();d.plan[k]=null;assert.throws(()=>validateMemberStatus(d));}
});
test('membership release probe uses only one fixed GET and rejects redirects/failures/unknown readiness',async()=>{
 const calls=[];const result=await checkMemberReleaseHealth(async(url,options)=>{calls.push({url,options});return Response.json(valid());});assert.equal(calls.length,1);assert.equal(calls[0].url,origin+'/api/member');assert.equal(calls[0].options.method,'GET');assert.equal(calls[0].options.redirect,'manual');assert.equal(calls[0].options.credentials,'omit');assert.equal(calls[0].options.body,undefined);assert.equal(calls[0].options.headers,undefined);assert.equal(result.freshChainProbe,false);assert.equal(result.watchKeyAuthentication,false);assert.equal(result.ordersProcessed,false);
 for(const response of [()=>{throw Error('offline');},()=>new Response('',{status:302,headers:{Location:origin+'/api/member-watch'}}),()=>new Response('{}',{status:503}),()=>new Response('not JSON'),()=>Response.json({...valid(),ready:false})])await assert.rejects(()=>checkMemberReleaseHealth(async()=>response()));
});
test('actual membership GET does not delete, process orders or refresh missing/stale health; 401 precedes database',async t=>{
 const {db,env,queries}=fixture(t),before=globalThis.fetch;globalThis.fetch=async()=>{throw Error('unexpected network');};t.after(()=>globalThis.fetch=before);
 const get=async()=>{queries.length=0;const r=await memberRoute(new Request(origin+'/api/member'),env,'agi');assert.equal(r.status,200);assert.ok(queries.every(q=>/^(CREATE|SELECT)\b/.test(q)));return r.json();};assert.equal((await get()).ready,false);
 const now=Math.floor(Date.now()/1000);db.sqlite.prepare('INSERT INTO wb_health VALUES(1,?)').run(now-14401);assert.equal((await get()).ready,false);assert.equal(db.sqlite.prepare('SELECT checked_at FROM wb_health').get().checked_at,now-14401);
 db.sqlite.prepare('UPDATE wb_health SET checked_at=?').run(now-60);assert.equal(validateMemberStatus(await get()).ready,true);assert.equal(db.sqlite.prepare('SELECT checked_at FROM wb_health').get().checked_at,now-60);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM wb_orders').get().n,0);
 for(const path of ['/api/member','/api/member-watch','/api/member-admin']){queries.length=0;const r=await memberRoute(request(path,{action:'list'}),env,'agi');assert.equal(r.status,401);assert.equal(queries.length,0);}
});
for(const c of routes){
 test(c.name+' read-only action preserves authentication, aggregate payload and legacy cleanup',async t=>{
  const {db,env,queries}=fixture(t);await c.ensure(db);db.sqlite.exec(c.seed);const token=await hash(secret+c.suffix);
  for(const k of ['',wrong]){queries.length=0;const r=await c.route(request(c.path,c.read,k),env);assert.ok([401,403].includes(r.status));assert.doesNotMatch(await r.text(),/member_id|token_hash|handle|browser_days/);noDelete(queries);}
  queries.length=0;const r=await c.route(request(c.path,c.read,token),env);assert.equal(r.status,200);const read=await r.json();assert.equal(read.ok,true);noDelete(queries);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM '+c.table).get().n,1);
  queries.length=0;const legacy=await c.route(request(c.path,c.legacy,token),env);assert.equal(legacy.status,200);assert.deepEqual(await legacy.json(),read);assert.ok(queries.some(q=>/^DELETE\b/.test(q)));assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM '+c.table).get().n,0);
 });
}
test('Relay read-only action cannot be turned into remove or queue with extra operation fields',async t=>{
 const {db,env,queries}=fixture(t);await ensureRelay(db);const token=await hash(secret+':relay-admin:v1');db.sqlite.exec("INSERT INTO relay_stories VALUES('"+'a'.repeat(32)+"','{}',NULL,'root',0,'owner',1,'unlisted',0)");
 for(const operation of ['remove','queue','unknown']){queries.length=0;const r=await createRoute(request('/api/create',{action:'inspect_stats',operation,id:'a'.repeat(32)},token),env);assert.equal(r.status,200);const data=await r.json();assert.ok(Array.isArray(data.stories));noDelete(queries);assert.ok(!queries.some(q=>/^UPDATE relay_stories/.test(q)));assert.equal(db.sqlite.prepare('SELECT status FROM relay_stories').get().status,'unlisted');}
});
async function seedIdentity(db,{suspended=0}={}){await ensureCommunity(db);db.sqlite.prepare('INSERT INTO wb_members VALUES(?,?,?,?,?)').run('fixture-member',await hash(uid),1,0,suspended);db.sqlite.prepare('INSERT INTO discuss_profiles VALUES(?,?,?,?,?)').run('fixture-member','Fixture reader','en','direct',1);db.sqlite.exec("INSERT INTO discuss_visits VALUES(date('now','-91 days'),'old','en','direct')");}
test('original Community status rejects missing/malformed/unknown/suspended identities before cleanup',async t=>{
 const {db,env,queries}=fixture(t);await seedIdentity(db);
 for(const token of ['', 'bad',wrong]){queries.length=0;const r=await communityRoute(request('/api/discuss',{action:'status'},token),env);assert.equal(r.status,401);noDelete(queries);assert.ok(queries.some(q=>q.startsWith('INSERT INTO discuss_limits')));}
 db.sqlite.exec('UPDATE wb_members SET suspended=1');queries.length=0;const r=await communityRoute(request('/api/discuss',{action:'status'},uid),env);assert.equal(r.status,403);noDelete(queries);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM discuss_visits').get().n,1);
});
test('original valid status still returns private data, records activity and performs existing maintenance',async t=>{
 const {db,env,queries}=fixture(t);await seedIdentity(db);queries.length=0;const r=await communityRoute(request('/api/discuss',{action:'status'},uid),env);assert.equal(r.status,200);const data=await r.json();assert.equal(data.profile.handle,'Fixture reader');assert.ok(Array.isArray(data.posts)&&Array.isArray(data.follows));assert.ok(queries.some(q=>/^DELETE\b/.test(q)));assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM discuss_activity').get().n,1);assert.ok(db.sqlite.prepare("SELECT n FROM discuss_limits WHERE k='member:fixture-member'").get().n>0);
});
test('new exact Community probe reuses status identity/IP limit but never reads posts or cleans data',async t=>{
 const {db,env,queries}=fixture(t);await seedIdentity(db);const path='/api/discuss/verify-status-access';
 for(const token of ['', 'bad',wrong]){queries.length=0;const r=await communityRoute(request(path,{action:'status'},token),env);assert.equal(r.status,401);assert.deepEqual(await r.json(),{ok:false,code:'unauthorized'});noDelete(queries);assert.ok(!queries.some(q=>q.includes('FROM discuss_posts')));}
 queries.length=0;let r=await communityRoute(request(path,{action:'status'},uid),env);assert.equal(r.status,200);assert.deepEqual(await r.json(),{ok:true,contract:'status-access-no-cleanup-v1'});noDelete(queries);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM discuss_visits').get().n,1);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM discuss_activity').get().n,0);
 db.sqlite.exec('UPDATE wb_members SET suspended=1');r=await communityRoute(request(path,{action:'status'},uid),env);assert.equal(r.status,403);
 for(const body of [{action:'register'},{action:'status',extra:true}])assert.equal((await communityRoute(request(path,body),env)).status,400);
 assert.equal((await communityRoute(new Request(origin+path),env)).status,405);assert.equal((await communityRoute(request(path,{action:'status'},'',{Origin:'https://wrong.example'}),env)).status,403);
 const ip=await hash(secret+':discuss:'+new Date().toISOString().slice(0,10)+':synthetic-release-fixture');db.sqlite.prepare('UPDATE discuss_limits SET n=90 WHERE k=?').run('ip:'+ip);assert.equal((await communityRoute(request(path,{action:'status'}),env)).status,429);assert.equal((await communityRoute(request('/api/discuss',{action:'status'}),env)).status,429);
});
// Frozen routers are the actual pre-change main files, not simplified mock branches.
const hashes={mentor:'30c5032809c0ecd0c213ae87aee5785bb0cdcfb522e2e54ffb9909a795fa69ab',create:'22bbe31f380ec716463339b65ed971ee075e1690d8929b6c8eb3a69eba0c65f0',community:'54911581accad81adf26852f86a3275e8d0a5663e40ac3c6bdbd02d22f48489f'};
function importsAt(source,url){return source.replace(/from\s+(['"])(\.\.?\/[^'"]+)\1/g,(_,quote,p)=>'from '+quote+new URL(p,url).href+quote);}
async function oldModule(name){const raw=fs.readFileSync(new URL('./fixtures/'+name+'-server-before.mjs.txt',import.meta.url),'utf8');assert.equal(createHash('sha256').update(raw).digest('hex'),hashes[name]);const text=importsAt(raw,new URL('../'+name+'/server.mjs',import.meta.url));return import('data:text/javascript;base64,'+Buffer.from(text).toString('base64'));}
for(const c of routes)test(c.name+' old real router rejects the new action before any cleanup',async t=>{
 const {db,env,queries}=fixture(t);await c.ensure(db);db.sqlite.exec(c.seed);const old=await oldModule(c.name),route=old[c.name==='mentor'?'mentorRoute':c.name==='create'?'createRoute':'communityRoute'];queries.length=0;const r=await route(request(c.path,c.read,await hash(secret+c.suffix)),env);assert.ok(r.status>=400);noDelete(queries);assert.equal(db.sqlite.prepare('SELECT COUNT(*) n FROM '+c.table).get().n,1);
});
test('old Community route and worker fallback reject the new probe without legacy-status fallback or cleanup',async t=>{
 const {env,queries}=fixture(t),raw=fs.readFileSync(new URL('./fixtures/community-server-before.mjs.txt',import.meta.url),'utf8');const oldURL='data:text/javascript;base64,'+Buffer.from(importsAt(raw,new URL('../community/server.mjs',import.meta.url))).toString('base64');const old=await import(oldURL);assert.equal(await old.communityRoute(request('/api/discuss/verify-status-access',{action:'status'}),env),null);assert.equal(queries.length,0);
 let worker=fs.readFileSync(new URL('../analytics-worker/index.js',import.meta.url),'utf8');worker=importsAt(worker,new URL('../analytics-worker/index.js',import.meta.url));const currentURL=new URL('../community/server.mjs',import.meta.url).href;assert.ok(worker.includes(currentURL));worker=worker.replace(currentURL,oldURL);const module=await import('data:text/javascript;base64,'+Buffer.from(worker).toString('base64'));const pending=[];queries.length=0;const r=await module.default.fetch(request('/api/discuss/verify-status-access',{action:'status'}),env,{waitUntil:p=>pending.push(p)});await Promise.all(pending);assert.ok([404,405].includes(r.status));noDelete(queries);
});
test('read-only CLI requests use new actions and manual redirects with no legacy retry',()=>{
 const cases=[['mentor/metrics.mjs',['--read-only'],'admin_readonly'],['create/ops.mjs',['stats','--read-only'],'inspect_stats'],['community/ops.mjs',['stats','--read-only'],'stats_readonly']];
 for(const [path,args,action]of cases){const url=new URL('../'+path,import.meta.url).href;const script=`process.env.ADS_WATCH_SECRET='fixture-only-secret-at-least-32-characters';process.argv=['node',${JSON.stringify(url)},...${JSON.stringify(args)}];globalThis.fetch=async(u,o)=>{const b=JSON.parse(o.body);if(b.action!==${JSON.stringify(action)}||o.redirect!=='manual')throw Error('wrong request');console.log('REQUEST_OK');return new Response('old server',{status:400});};await import(${JSON.stringify(url)}).then(()=>process.exit(90),()=>{});`;const text=execFileSync(process.execPath,['--input-type=module','-e',script],{encoding:'utf8'});assert.equal(text.trim(),'REQUEST_OK');}
});
test('live community verifier probes the new path, rejects redirects and checks unauthorized JSON',()=>{
 const source=fs.readFileSync(new URL('../community/verify.mjs',import.meta.url),'utf8');assert.ok(source.includes("['/api/discuss/verify-status-access',{action:'status'}]"));assert.ok(!source.includes("['/api/discuss',{action:'status'}]"));assert.ok(source.includes("redirect:'manual'"));assert.ok(source.includes("denial.code,'unauthorized'"));assert.ok(source.includes('Original status-handler behavior is covered by offline fixtures'));
});
test('push split keeps original non-push maintenance and known safety checks without adding schedules or credentials',()=>{
 const workflow=fs.readFileSync(new URL('../../../../.github/workflows/deploy-agiscorecard.yml',import.meta.url),'utf8');const push=workflow.match(/- name: Verify non-destructive membership readiness after push([\s\S]*?)(?=\n      - name:)/)[1],legacy=workflow.match(/- name: Verify independent membership after deployment([\s\S]*?)(?=\n      - name:)/)[1];assert.ok(push.includes("if: github.event_name == 'push'"));assert.ok(push.includes('member-release-health.mjs')&&push.includes('member-studio/verify.mjs --site agi --live'));assert.ok(!push.includes('ops.mjs watch')&&!push.includes('ADS_WATCH_SECRET')&&!push.includes('continue-on-error'));assert.ok(legacy.includes("if: github.event_name != 'push'")&&legacy.includes('ops.mjs watch agi'));for(const command of ['mentor/metrics.mjs','create/ops.mjs stats','community/ops.mjs stats'])assert.ok(workflow.includes(command+' --read-only'));
 for(const command of ['jarvis/ops.mjs verify','jarvis/ops.mjs verify-sources','community/verify.mjs','member-studio/ops.mjs configure agi'])assert.ok(workflow.includes(command));assert.ok(!/jarvis\/ops\.mjs run|tick\(/.test(workflow));assert.match(workflow,/cron: "50 2 \* \* \*"/);assert.ok(workflow.includes("github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.check_relay_ai == true)"));
});
