// Reproducible, code-rendered social preview. No customer data or stock imagery.
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require('../revenue-studio/node_modules/playwright'));}
const browser=await chromium.launch({headless:true,executablePath:process.env.QUOTE_STUDIO_CHROMIUM||undefined,args:['--no-sandbox']});
try{
 for(const lang of ['zh','en']){
  const zh=lang==='zh',page=await browser.newPage({viewport:{width:1200,height:630},deviceScaleFactor:1});
  await page.setContent(`<!doctype html><html lang="${zh?'zh-CN':'en'}"><head><meta charset="UTF-8"><style>*{box-sizing:border-box}body{margin:0;width:1200px;height:630px;background:#f6f8fc;color:#17243b;font-family:'Segoe UI',Arial,'Noto Sans CJK SC',sans-serif;padding:48px 56px}.brand{font-size:20px;font-weight:700;letter-spacing:2px;color:#2453d4;display:flex;justify-content:space-between;border-bottom:1px solid #dce3ee;padding-bottom:22px}.brand{align-items:center}.brand-name{display:flex;align-items:center;gap:14px;letter-spacing:0}.symbol{display:grid;place-items:center;width:44px;height:44px;border-radius:12px;background:#2453d4;color:#fff;font-size:34px;line-height:1;font-weight:800}.brand>span:last-child{font-size:15px;letter-spacing:0;font-weight:500}.body{display:grid;grid-template-columns:1.4fr 1fr;gap:52px;margin-top:40px;align-items:center}h1{font-size:${zh?58:62}px;line-height:1.16;letter-spacing:-1.5px;margin:0 0 25px}.copy p{font-size:23px;line-height:1.5;margin:0;color:#47566d}.badge{display:inline-block;background:#2453d4;color:white;padding:12px 21px;margin-top:28px;font-size:18px;font-weight:600;border-radius:8px}.quote{background:#fff;border:1px solid #dce3ee;border-top:6px solid #2453d4;padding:28px;border-radius:12px;box-shadow:0 12px 32px #283c3010}.quote h2{font-size:19px;margin:0 0 24px}.line{display:flex;justify-content:space-between;padding:12px 0;border-top:1px solid #dce3ee;font-size:16px}.line strong{font-size:19px}.total{background:#edf2ff;margin:16px -28px -28px;padding:23px 28px}.total span{font-size:14px;display:block}.total strong{font-size:42px;line-height:1.4}.foot{position:absolute;bottom:29px;font-size:14px;color:#47566d;left:56px;right:56px;display:flex;justify-content:space-between}</style></head><body><div class="brand"><span class="brand-name"><b class="symbol">b.</b>${zh?'白嫖计 · 报价工坊':'BPJ · Quote Studio'}</span><span>${zh?'免费 · 无需注册':'FREE · NO SIGNUP'}</span></div><div class="body"><div class="copy"><h1>${zh?'客户改范围，<br>报价跟着算。':'Let clients<br>choose the scope.'}</h1><p>${zh?'你的服务与单价。<br>客户自己选，明细说清楚。':'Your services. Your rates.<br>A clear estimate clients can adjust.'}</p><span class="badge">${zh?'先试客户报价页 →':'Try the client quote →'}</span></div><div class="quote"><h2>${zh?'视频剪辑 · 互动示例':'Video editing · interactive sample'}</h2><div class="line"><span>${zh?'剪辑数量':'Video edits'}</span><strong>3 → 5</strong></div><div class="line"><span>${zh?'额外画幅':'Extra format'}</span><strong>1</strong></div><div class="total"><span>${zh?'预估合计 · CNY':'Estimated total · USD'}</span><strong>${zh?'¥':'$'}390 → ${zh?'¥':'$'}630</strong></div></div></div><div class="foot"><span>baipiaoji.com</span><span>${zh?'虚构示例价格，非市场指导价':'Fictional sample rates, not market benchmarks'}</span></div></body></html>`);
  await page.screenshot({path:new URL(`../../sites/baipiaoji/assets/studio/quote-social-${lang}.png`,import.meta.url).pathname});
  await page.close();
 }
}finally{await browser.close();}
