import assert from 'node:assert/strict';
import {mkdirSync,readFileSync} from 'node:fs';
import {dirname,join} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {calculate,parseMoney,validateConfig,template,encodeConfig,decodeConfig,safeJSON} from './core.mjs';
const root=dirname(fileURLToPath(import.meta.url)), out=join(root,'test-output');
mkdirSync(out,{recursive:true});
const config=template();
assert.equal(parseMoney('0.29'),29);
assert.equal(parseMoney('00012.3'),1230);
for(const bad of ['','-1','Infinity','NaN','1e2','1.001','10000000'])assert.throws(()=>parseMoney(bad));
assert.equal(calculate(config,[3,1,0]).total,39000);
assert.equal(calculate(config,[3,1,0]).deposit,11700);
assert.equal(calculate({...config,base:1,deposit:50},[0,0,0]).deposit,1);
assert.equal(calculate({...config,base:1,deposit:50},[0,0,0]).balance,0);
for(const bad of [[1],[1,-1,0],[1,0.1,0],[1,1001,0],[1,NaN,0]])assert.throws(()=>calculate(config,bad));
assert.throws(()=>validateConfig({...config,currency:'JPY'}));
assert.throws(()=>validateConfig({...config,items:Array(7).fill(config.items[0])}));
assert.deepEqual(decodeConfig(encodeConfig(config)),config);
assert.throws(()=>decodeConfig('!bad'));
assert.throws(()=>decodeConfig('a'.repeat(14001)));
assert(!safeJSON({value:'</script><img onerror=alert(1)>'}).includes('<'));
console.log('Core: money precision, scope totals, invalid values, schema and Unicode round trip passed.');
const require=createRequire(import.meta.url);
let chromium;try{({chromium}=require('playwright'));}catch{({chromium}=require('../revenue-studio/node_modules/playwright'));}
const browser=await chromium.launch({headless:true,executablePath:process.env.QUOTE_STUDIO_CHROMIUM||undefined,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:1360,height:1000},acceptDownloads:true});
const page=await context.newPage();
const errors=[];page.on('pageerror',error=>errors.push(error.message));
const url=pathToFileURL(join(root,'dist','quote-studio-zh.html')).href;
try{
 await page.goto(url);await page.locator('#quote-preview .quote').waitFor();
 assert.equal(await page.locator('#total').textContent(),'¥390.00');
 assert(await page.getByRole('button',{name:'下载客户报价页',exact:true}).isDisabled());
 await page.locator('[name="brand"]').fill('北河视频工作室');
 await page.locator('[name="price-0"]').fill('199.99');
 await page.locator('[name="confirmed"]').check();
 assert.equal(await page.locator('#total').textContent(),'¥629.97');
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:join(out,'desktop.png'),fullPage:true});
 const dl=page.waitForEvent('download');await page.getByRole('button',{name:'下载客户报价页',exact:true}).click();
 const download=await dl;await download.saveAs(join(out,'client-quote.html'));
 const customer=await context.newPage();customer.on('pageerror',error=>errors.push(error.message));
 await customer.goto(pathToFileURL(join(out,'client-quote.html')).href);
 assert.equal(await customer.locator('#editor').count(),0);
 assert.equal(await customer.locator('.seller').textContent(),'北河视频工作室');
 await customer.locator('[data-qty="0"]').fill('2');assert.equal(await customer.locator('#total').textContent(),'¥429.98');
 await customer.locator('[data-qty="0"]').fill('-1');assert.equal(await customer.locator('#total').textContent(),'—');
 assert(await customer.getByRole('button',{name:'下载我的需求摘要'}).isDisabled());
 await customer.locator('[data-qty="0"]').fill('2');
 await customer.getByRole('button',{name:'English',exact:true}).click();
 assert.equal(await customer.locator('[data-qty="0"]').inputValue(),'2');
 assert.equal(await customer.locator('#total').textContent(),'CN¥429.98');
 const sd=customer.waitForEvent('download');await customer.getByRole('button',{name:'Download my scope summary'}).click();
 await (await sd).saveAs(join(out,'quote-request.txt'));
 const summary=readFileSync(join(out,'quote-request.txt'),'utf8');
 assert(summary.includes('429.98')&&summary.includes('not an order'));
 await customer.setViewportSize({width:390,height:844});await customer.screenshot({path:join(out,'customer-mobile.png'),fullPage:true});
 assert(await customer.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 customer.once('dialog',dialog=>dialog.accept());await customer.getByRole('button',{name:'Create my own quote tool from this template'}).click();
 assert.equal(await customer.locator('[name="brand"]').inputValue(),'Your studio');
 assert(!(await customer.locator('[name="confirmed"]').isChecked()));
 await page.locator('[name="price-0"]').fill('0.001');
 assert(await page.getByRole('button',{name:'下载客户报价页',exact:true}).isDisabled());
 assert((await page.locator('#quote-preview').textContent()).includes('请先修正输入'));
 await page.locator('[name="price-0"]').fill('120');
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:join(out,'builder-mobile.png'),fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 const malicious={...template('video','en'),confirmed:true,brand:'</script><img src=x onerror="window.pwned=1">',note:'<svg onload="window.pwned=2">'};
 await page.goto(url+'#quote='+encodeConfig(malicious));
 assert.equal(await page.locator('.seller').textContent(),malicious.brand);
 assert.equal(await page.locator('.seller img').count(),0);
 assert.equal(await page.evaluate(()=>window.pwned),undefined);
 await page.goto(url+'#quote=!broken');await page.waitForFunction(()=>/无效|invalid/i.test(document.querySelector('#status')?.textContent||''));
 await page.goto(pathToFileURL(join(root,'dist','quote-studio-en.html')).href);
 assert(!(await page.locator('#app').textContent()).match(/[\u4e00-\u9fff]/g)?.filter(c=>!['中','文'].includes(c)).length);
 await page.getByRole('button',{name:'Save, restore and back up'}).count();
 await page.locator('.secondary summary').click();
 await page.getByRole('button',{name:'Save local draft',exact:true}).click();
 assert((await page.locator('#status').textContent()).includes('saved'));
 await page.getByRole('button',{name:'Import JSON',exact:true}).click().catch(()=>{});
 await page.locator('#import-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});
 await page.waitForFunction(()=>document.querySelector('#status')?.textContent.includes('Import failed'));
 assert.deepEqual(errors,[]);
 console.log('Browser: desktop/mobile, exported offline tool, exact totals, customer summary, invalid input, bilingual UI, local save, invalid import and XSS rendering passed.');
 console.log('Screenshots and functional export: tools/quote-page-lab/test-output/');
}finally{await browser.close();}
