const l=document.body.dataset.lang==='zh'?'zh':'en',t=(en,zh)=>l==='zh'?zh:en,$=id=>document.getElementById(id),base=l==='zh'?'/zh/discuss':'/discuss',slot='workbench-member-key:agi',thread=document.body.dataset.thread||'';
const random=n=>[...crypto.getRandomValues(new Uint8Array(n))].map(x=>x.toString(16).padStart(2,'0')).join('');
const read=k=>{try{return sessionStorage.getItem(k)||'';}catch{return '';}};
const save=(k,v)=>{try{v?sessionStorage.setItem(k,v):sessionStorage.removeItem(k);}catch{}};
let key=read(slot),profile=null,savedKey=false,modKey='',myPage=1;
const errors={unauthorized:t('Sign in with your AGI key, or create a free account.','请使用 AGI 密钥登录，或创建免费账号。'),profile_required:t('Choose a display name to finish joining.','请选择昵称，完成注册。'),bad_handle:t('Use 3–30 letters, numbers, spaces, hyphens or underscores. Official names are reserved.','昵称限 3–30 个字母、汉字、数字、空格、连字符或下划线；官方名称不可使用。'),handle_taken:t('That display name is taken. Choose another.','此昵称已被使用，请换一个。'),consent_required:t('Save your key and accept the rules before continuing.','请保存密钥并同意规则后继续。'),rate_limited:t('Too many attempts. Please try again later.','操作过于频繁，请稍后再试。'),bad_source:t('Use a complete HTTPS source URL without login credentials.','请使用完整的 HTTPS 来源网址，不要包含登录信息。'),bad_content:t('Check the title and text lengths, and remove private login keys.','请检查标题与正文长度，并移除私有登录密钥。'),follow_limit:t('You can follow up to 50 topics. Remove one first.','最多关注 50 个话题，请先取消部分关注。'),suspended:t('This account is suspended.','此账号已被暂停。'),not_found:t('That contribution is no longer available.','该投稿已不可用。'),unavailable:t('The service is temporarily unavailable. Your draft is kept in this tab; try again later.','服务暂时不可用。草稿保留在当前标签页，请稍后再试。')};
const notice=(s,error=false)=>{const n=$('notice');n.textContent=s;n.className=error?'error':'success';n.scrollIntoView({block:'nearest',behavior:'smooth'});};
function el(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;}
function link(label,path){const a=el('a',label);a.href=path;return a;}
async function api(action,extra={},admin=false){const r=await fetch('/api/discuss'+(admin?'/admin':'')+'?lang='+l,{method:'POST',headers:{'Content-Type':'application/json',...((admin?modKey:key)?{Authorization:'Bearer '+(admin?modKey:key)}:{})},body:JSON.stringify({action,...extra}),signal:AbortSignal.timeout(20000)});let j;try{j=await r.json();}catch{throw Error(errors.unavailable);}if(!r.ok||!j.ok)throw Error(errors[j.code]||errors.unavailable);return j;}
function attach(form,fn){if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button[type="submit"],button:not([type])');if(button?.disabled)return;if(button)button.disabled=true;try{await fn(new FormData(form));}catch(err){notice(err.message,true);}finally{if(button)button.disabled=false;}});}
function button(label,fn,cls='secondary'){const b=el('button',label);b.type='button';b.className=cls;b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{b.disabled=false;}};return b;}
function backup(){if(!key)key=random(32);save(slot,key);const a=el('a');a.download='agi-access-key.json';a.href=URL.createObjectURL(new Blob([JSON.stringify({service:'agi-workbench',version:1,key},null,2)],{type:'application/json'}));a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);savedKey=true;notice(t('Key file downloaded. Store it privately before creating your account.','密钥文件已下载。请私下保存，再创建账号。'));}
const currentSource=()=>{const s=new URL(location.href).searchParams.get('utm_source');if(['reddit','hackernews','x','linkedin','share'].includes(s))return s;let h='';try{h=new URL(document.referrer).hostname;}catch{}return h===location.hostname?'internal':/reddit/.test(h)?'reddit':/ycombinator/.test(h)?'hackernews':/google|bing|duckduckgo|baidu/.test(h)?'search':h?'other':'direct';};
const acquisition=read('agi-discuss-source')||currentSource();save('agi-discuss-source',acquisition);
let sid=read('agi-discuss-tab');if(!/^[a-f0-9]{32}$/.test(sid)){sid=random(16);save('agi-discuss-tab',sid);}if(!location.pathname.endsWith('/moderate'))api('visit',{sid,source:acquisition}).catch(()=>{});
async function requireProfile(){if(!profile&&key)try{await refresh();}catch{}if(profile)return true;save('agi-discuss-return',location.pathname);location.href=base+'/account';return false;}
function resume(){const path=read('agi-discuss-return');save('agi-discuss-return','');if(/^\/(?:zh\/)?discuss\/(?!account|moderate|rules)[a-z0-9-]+$/.test(path)){location.href=path;return true;}return false;}
async function refresh(){if(!key)return;const j=await api('status',{page:myPage});profile=j.profile;if(!profile){if($('signed-out'))$('signed-out').hidden=false;return;}
 if($('account-data')){$('account-data').hidden=false;$('signed-out').hidden=true;$('account-name').textContent=t('Welcome, ','欢迎，')+profile.handle;const f=$('following');f.replaceChildren();for(const item of j.follows){const box=el('article');box.className='account-row';box.append(item.available?link(item.title,base+'/'+item.thread):el('span',t('Discussion unavailable','话题不可用')),el('small',item.unread?' '+item.unread+' '+t('new replies','条新回复'):t(' No new replies',' 暂无新回复')),button(t('Unfollow','取消关注'),async()=>{await api('unfollow',{id:item.thread});await refresh();}));f.append(box);}if(!j.follows.length)f.append(el('p',t('Follow a discussion to find it here when you return.','关注一个话题，回访时可在这里找到。')));
 const posts=$('contributions');posts.replaceChildren();for(const p of j.posts){const box=el('article');box.className='account-row';const states={pending:t('Pending review','待审核'),public:t('Published','已公开'),rejected:t('Not accepted','未通过'),deleted:t('Deleted','已删除')};box.append(el('strong',(states[p.status]||p.status)+' · '+(p.title||t('Reply','回复'))),el('p',p.body));if(p.status==='public')box.append(link(t('View discussion','查看讨论'),base+'/'+(p.parent||p.id)+(p.parent?'#reply-'+p.id:'')));if(p.status!=='deleted')box.append(button(t('Delete contribution','删除投稿'),async()=>{if(confirm(t('Delete this contribution? This cannot be undone.','删除此投稿？此操作不可撤销。'))){await api('delete',{id:p.id});await refresh();}}));posts.append(box);}if(!j.posts.length)posts.append(el('p',t('Your submitted contributions and review status will appear here.','提交的内容与审核状态将在这里显示。')));if(myPage>1)posts.append(button(t('Previous','上一页'),async()=>{myPage--;await refresh();}));if(j.more)posts.append(button(t('More contributions','更多投稿'),async()=>{myPage++;await refresh();}));}
 if(thread&&$('follow')){const following=j.follows.some(f=>f.thread===thread);$('follow').textContent=following?t('Unfollow discussion','取消关注'):t('Follow this discussion','关注此话题');$('follow').dataset.following=String(following);if(following)await api('seen',{id:thread,revision:Number(document.body.dataset.seen)||0});}
}
if($('backup-key'))$('backup-key').onclick=backup;
if($('backup-again'))$('backup-again').onclick=backup;
attach($('join-form'),async f=>{if(!savedKey)throw Error(t('Download your login key first.','请先下载登录密钥。'));await api('register',{handle:f.get('handle'),key_saved:f.get('key_saved')==='on',agree:f.get('key_saved')==='on',website:f.get('website'),source:acquisition});await refresh();if(!resume())notice(t('Your free account is ready. Choose a discussion to join.','免费账号已创建，选择一个话题开始参与。'));});
if($('import-key'))$('import-key').onchange=async()=>{try{const file=$('import-key').files[0];if(!file||file.size>4096)throw Error();const d=JSON.parse(await file.text());if(d.service!=='agi-workbench'||d.version!==1||!/^[a-f0-9]{64}$/.test(d.key))throw Error();$('login-key').value=d.key;}catch{notice(t('Choose a valid AGI login key file. Keys from other sites do not work here.','请选择有效的 AGI 密钥文件，其他站点的密钥不能在此使用。'),true);}};
attach($('login-form'),async()=>{const previous=key;key=$('login-key').value.trim();if(!/^[a-f0-9]{64}$/.test(key)){key=previous;throw Error(errors.unauthorized);}try{await refresh();save(slot,key);if(!profile)notice(t('Your AGI key is valid. Choose a display name and back up the key to join discussions.','AGI 密钥有效。请选择昵称并备份密钥，即可加入讨论。'));else if(!resume())notice(t('Signed in.','已登录。'));}catch(e){key=previous;throw e;}});
if($('signout'))$('signout').onclick=()=>{key='';profile=null;save(slot,'');location.reload();};
if($('close-profile'))$('close-profile').onclick=async()=>{if(confirm(t('Delete all your community contributions and follows? Paid membership is retained.','删除全部社区投稿和关注？付费会员将保留。')))try{await api('close_profile',{confirm:true});location.reload();}catch(e){notice(e.message,true);}};
const form=$('post-form'),draftSlot='agi-discuss-draft:'+l+':'+(thread||'new');let nonce=random(16);
if(form){try{const d=JSON.parse(read(draftSlot)||'null');if(d)for(const k of ['title','body','source','disclosure','category'])if(form.elements[k]&&typeof d[k]==='string')form.elements[k].value=d[k];}catch{}
 form.addEventListener('input',()=>{const f=new FormData(form);save(draftSlot,JSON.stringify(Object.fromEntries(['title','body','source','disclosure','category'].map(k=>[k,f.get(k)||'']))));nonce=random(16);});
 attach(form,async f=>{if(!await requireProfile())return;await api('submit',{parent:thread||undefined,title:f.get('title')||'',category:f.get('category'),body:f.get('body'),source:f.get('source'),disclosure:f.get('disclosure'),website:f.get('website'),agree:f.get('agree')==='on',nonce});save(draftSlot,'');form.reset();nonce=random(16);notice(t('Submitted for review. You can see the status in My discussions.','已提交审核。可前往「我的讨论」查看状态。'));});}
if($('follow'))$('follow').onclick=async()=>{if(!await requireProfile())return;try{await api($('follow').dataset.following==='true'?'unfollow':'follow',{id:thread});await refresh();notice(t('Your following list is updated.','关注列表已更新。'));}catch(e){notice(e.message,true);}};
const sharedURL=()=>{const u=new URL(location.pathname,location.origin);u.searchParams.set('utm_source','share');u.searchParams.set('utm_medium','community');return u.href;};
async function copyLink(){try{await navigator.clipboard.writeText(sharedURL());notice(t('Link copied. Check the destination community’s rules before posting.','链接已复制。发布前请检查目标社区规则。'));}catch{prompt(t('Copy this link','请复制此链接'),sharedURL());}api('share_intent',{source:'share'}).catch(()=>{});}
if($('copy-link'))$('copy-link').onclick=copyLink;
if($('share'))$('share').onclick=async()=>{if(navigator.share){try{await navigator.share({title:document.querySelector('h1').textContent,url:sharedURL()});api('share_intent',{source:'share'}).catch(()=>{});}catch(e){if(e.name!=='AbortError')await copyLink();}}else await copyLink();};
document.querySelectorAll('[data-report]').forEach(b=>b.onclick=async()=>{if(!await requireProfile())return;const dialog=el('dialog'),f=el('form'),label=el('label',t('Reason for reporting','举报原因')),select=el('select');for(const [value,en,zh]of [['spam','Spam','垃圾推广'],['abuse','Abuse','骚扰攻击'],['privacy','Private information','私人信息'],['misleading','Misleading content','误导内容']]){const o=el('option',t(en,zh));o.value=value;select.append(o);}label.append(select);f.append(label,button(t('Report for review','提交举报'),async()=>{await api('report',{id:b.dataset.report,reason:select.value});dialog.close();dialog.remove();notice(t('Report received for review.','举报已收到，等待审核。'));}),button(t('Cancel','取消'),async()=>{dialog.close();dialog.remove();}));dialog.append(f);document.body.append(dialog);dialog.showModal();});
async function loadQueue(){const j=await api('queue',{},true),area=$('moderation');area.replaceChildren(el('p',t('Pending: ','待审核：')+j.posts.length));for(const p of j.posts){const box=el('article');box.className='reply';box.append(el('small',p.id+' · '+p.handle+' · '+p.lang),el('h2',p.title||t('Reply','回复')),el('p',p.body));if(p.source){const a=link(p.source,p.source);a.rel='nofollow noopener noreferrer';a.target='_blank';box.append(a);}if(p.disclosure)box.append(el('p',p.disclosure));if(p.parent)box.append(link(t('Parent topic','所属话题'),base+'/'+p.parent));for(const [status,en,zh]of [['public','Approve','通过'],['rejected','Reject','拒绝']])box.append(button(t(en,zh),async()=>{await api('moderate',{id:p.id,status},true);await loadQueue();}));area.append(box);}area.append(el('h2',t('Reports','举报')));for(const r of j.reports){const box=el('article');box.className='reply';box.append(el('strong',r.reason),el('p',r.title),el('p',r.body),button(t('Remove content','移除内容'),async()=>{await api('moderate',{id:r.post,status:'deleted'},true);await loadQueue();}),button(t('Dismiss report','关闭举报'),async()=>{await api('dismiss_report',{id:r.post},true);await loadQueue();}));area.append(box);}if(j.posts.length===50)area.append(el('p',t('More submissions may be waiting. Review these to load the next batch.','可能还有更多投稿，请处理当前队列后继续加载。')));}
attach($('moderator-login'),async()=>{modKey=$('moderator-key').value.trim();$('moderator-key').value='';await loadQueue();});
if(key&&!location.pathname.endsWith('/moderate'))refresh().catch(()=>{if($('login-panel'))$('login-panel').open=true;});
