import test from 'node:test';import assert from 'node:assert/strict';
import {parseTicker,parseFeed,feeds,state,marketMarkup,briefsMarkup,rss,snapshot} from '../market.mjs';
import {impact} from '../public/impact.mjs';import {attribution} from '../public/attribution.mjs';
import {measurement,eventShape} from '../measurement.mjs';
const tick={error:[],result:Object.fromEntries(['XXBTZUSD','XETHZUSD','USDCUSD','USDTZUSD'].map(k=>[k,{c:['1.002','1'],o:'1',l:['0.99','0.98'],h:['1.003','1.01']}]))};
test('ticker uses last price, midnight UTC change and signed stablecoin basis points',()=>{const q=parseTicker(tick);assert.equal(q[0].symbol,'BTC');assert.equal(q[2].price,1.002);assert.ok(Math.abs(q[2].deviationBps-20)<1e-9);assert.ok(Math.abs(q[0].changeUtcPct-.2)<1e-9);assert.equal(q[0].deviationBps,null);assert.equal(q[0].low24h,.98);assert.throws(()=>parseTicker({error:['Unavailable']}));const bad=structuredClone(tick);bad.result.USDCUSD.c[0]='Infinity';assert.throws(()=>parseTicker(bad));delete bad.result.USDCUSD;assert.throws(()=>parseTicker(bad));});
test('age is computed at read time; failed or old data never becomes fresh',()=>{const now=Date.parse('2026-09-19T12:00:00Z'),s={retrievedAt:'2026-09-19T11:59:00Z',quotes:[{price:1}]};assert.equal(state(s,'market',now).status,'fresh');assert.equal(state(s,'market',now,true).status,'stale');assert.equal(state(s,'market',now+301000).status,'stale');assert.equal(state(s,'market',now+86400000).quotes.length,0);assert.equal(state({...s,retrievedAt:'2026-09-20T00:00:00Z'},'market',now).status,'unavailable');assert.equal(state(null,'market',now).retrievedAt,null);});
test('feed parser preserves original dates, rejects hostile links, future records and XML entities',()=>{const item=(link,date,title='Review &amp; test')=>`<item><title>${title}</title><link>${link}</link><pubDate>${date}</pubDate></item>`;const xml='<rss>'+item('https://blog.ethereum.org/en/2026/09/18/test','2026-09-18T00:00:00Z')+item('javascript:alert(1)','2026-09-18')+item('https://evil.test/','2026-09-18')+item('https://blog.ethereum.org/future','2027-01-01')+'</rss>';const rows=parseFeed(xml,feeds[0],Date.parse('2026-09-19'));assert.equal(rows.length,1);assert.equal(rows[0].publishedAt,'2026-09-18T00:00:00.000Z');assert.equal(rows[0].title,'Review & test');assert.throws(()=>parseFeed('<!DOCTYPE rss [<!ENTITY x SYSTEM "file:/etc/passwd">]><rss/>',feeds[0]));assert.match(briefsMarkup({status:'fresh',items:[{...rows[0],title:'<script>bad</script>'}]}),/&lt;script&gt;/);assert.ok(!rss({status:'fresh',items:[{...rows[0],title:'<script>'}]}).includes('<script>'));});
test('commits are not releases and source identity cannot escape its project',()=>{const s=feeds[1],r={commit:{message:'Fix behavior\nprivate body not used',committer:{date:'2026-09-18T00:00:00Z'}},html_url:'https://github.com/coinbase/x402/commit/abc'};const rows=parseFeed([r,{...r,html_url:'https://github.com/evil/repo/commit/abc'}],s,Date.parse('2026-09-19'));assert.equal(rows.length,1);assert.equal(rows[0].kind,'commits');assert.equal(rows[0].title,'Fix behavior');assert.match(briefsMarkup({status:'fresh',items:rows}),/Code change, not a released feature/);});
test('gas arithmetic and stablecoin impact preserve units and reject invalid prices',()=>{const r=impact({amount:1000,price:.998,gas:21000,feeGwei:10,ethUsd:2000});assert.equal(r.value,998);assert.ok(Math.abs(r.difference+2)<1e-10);assert.ok(Math.abs(r.gasUsd-.42)<1e-12);assert.throws(()=>impact({amount:1,price:0,gas:1,feeGwei:1,ethUsd:1}));assert.throws(()=>impact({amount:1,price:1,gas:Infinity,feeGwei:1,ethUsd:1}));});
test('attribution stores coarse allowlisted categories, never search queries or full URLs',()=>{const a=attribution('https://web3.agiscorecard.com/market.html?via=gas&channel=ai&email=private','https://google.com/search?q=private');assert.deepEqual(a,{channel:'ai',campaign:'gas'});assert.deepEqual(attribution('https://x.test/?via=secret&channel=person','https://chatgpt.com/c/private'),{channel:'ai',campaign:'none'});assert.equal(attribution('https://x.test','https://google.com.evil.test/').channel,'external');assert.equal(attribution('https://x.test','https://bing.com/search?q=private').channel,'search');});
const value={id:'a8e04aaa-4000-4000-8000-000000000001',page:'market',channel:'ai',campaign:'gas',event:'cost_check',qa:true,consent:true};
function fake(){const writes=[],rows=new Map();return {writes,rows,env:{MEASURE_LIMIT:{limit:async()=>({success:true})},DB:{prepare(sql){let args=[];return {bind(...a){args=a;return this;},async run(){writes.push({sql,args});if(sql.startsWith('INSERT'))rows.set(args[0],args);return {};},async all(){return{results:[...rows.values()].filter(r=>r[6]===args[0]&&(!args[1]||r[1]===args[1])).map(r=>({site:r[1],page:r[2],channel:r[3],campaign:r[4],event:r[5],events:1}))};}};}}}};}
const req=(v,origin='https://web3.agiscorecard.com')=>new Request('https://web3.agiscorecard.com/api/event',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','User-Agent':'Web3-smoke'},body:JSON.stringify(v)});
test('measurement requires explicit opt-in and a strict non-PII contract',async()=>{assert.ok(eventShape(value));assert.ok(!eventShape({...value,consent:false}));assert.ok(!eventShape({...value,input:'private'}));assert.ok(!eventShape({...value,event:'payment'}));const f=fake();assert.equal((await measurement(req({...value,input:'private'}),f.env,'hub')).status,400);assert.equal((await measurement(req(value,'https://evil.test'),f.env,'hub')).status,403);assert.equal(f.writes.length,0);f.env.MEASURE_LIMIT.limit=async()=>({success:false});assert.equal((await measurement(req(value),f.env,'hub')).status,429);});
test('QA replay deduplicates, public counters exclude it and writes stay namespaced',async()=>{const f=fake();for(let i=0;i<2;i++)assert.equal((await measurement(req(value),f.env,'hub')).status,200);assert.equal(f.rows.size,1);assert.ok(f.writes.every(x=>x.sql.includes('web3_studio_events')));const get=p=>measurement(new Request('https://web3.agiscorecard.com/api/growth'+p),f.env,'hub');assert.equal((await(await get('')).json()).groups.length,0);assert.equal((await(await get('?qa=1')).json()).groups[0].events,1);assert.equal((await(await get('')).json()).outcomes.revenue,null);assert.equal((await get('?qa=1&qa=0')).status,400);const r=await measurement(req({...value,qa:false}),f.env,'hub');assert.equal((await r.json()).accepted,false);});
test('fresh cache reuses receipt time without upstream fetch or user data',async t=>{const now=new Date().toISOString();t.mock.method(globalThis,'fetch',async()=>{throw Error('Unexpected upstream');});const r=await snapshot('market',{match:async()=>new Response(JSON.stringify({retrievedAt:now,quotes:parseTicker(tick)}))});assert.equal(r.retrievedAt,now);assert.equal(r.status,'fresh');assert.match(marketMarkup(r),/Since 00:00 UTC/);});
