import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {Client,StreamableHTTPClientTransport} from '@modelcontextprotocol/client';
import {Client as LegacyClient} from '@modelcontextprotocol/sdk/client/index.js';
import {StreamableHTTPClientTransport as LegacyTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import worker from '../worker.mjs';import {sites,hubHost} from '../public/catalog.mjs';import {scenarios} from '../public/experience.mjs';import {run} from '../public/engine.mjs';import {toolNames,publicResources} from '../mcp.mjs';
const env={MCP_LIMIT:{limit:async()=>({success:true})},ASSETS:{fetch:async r=>{try{return new Response(await readFile('dist'+new URL(r.url).pathname));}catch{return new Response('missing',{status:404});}}}};
async function connect(host=hubHost,legacy=false){const trace=[];const C=legacy?LegacyClient:Client,T=legacy?LegacyTransport:StreamableHTTPClientTransport;const client=new C({name:'web3-test-client',version:'1.0.0'},legacy?{}:{versionNegotiation:{mode:{pin:'2026-07-28'}}});const transport=new T(new URL('https://'+host+'/mcp'),{fetch:async(url,init)=>{const request=new Request(url,init);let body;try{body=await request.clone().json();}catch{}trace.push({method:body?.method,version:request.headers.get('MCP-Protocol-Version')});return worker.fetch(request,env);}});await client.connect(transport);return {client,trace};}
test('official current MCP client discovers all tools, reads sources and computes every published scenario',async()=>{const {client,trace}=await connect();try{const list=(await client.listTools()).tools;assert.deepEqual(list.map(t=>t.name),['search','fetch',...sites.map(s=>toolNames[s.id])]);assert.ok(list.every(t=>t.annotations.readOnlyHint&&t.annotations.destructiveHint===false&&t.annotations.openWorldHint===false));const resources=(await client.listResources()).resources;assert.deepEqual(resources.map(r=>r.uri),publicResources('hub').map(r=>r.uri));const search=await client.callTool({name:'search',arguments:{query:'GPU'}});assert.equal(search.structuredContent.results[0].id,'compute');const reference=await client.callTool({name:'fetch',arguments:{id:'compute'}});assert.equal(reference.structuredContent.url,'https://compute.agiscorecard.com/guide.html');assert.match(reference.structuredContent.text,/Remote calculator inputs/);for(const s of sites){for(const c of scenarios(s.id)){const result=await client.callTool({name:toolNames[s.id],arguments:c.input});assert.ok(!result.isError,JSON.stringify(result));assert.deepEqual(result.structuredContent.report,run(s.id,c.input));assert.equal(result.structuredContent.citation.methodUrl,'https://'+s.host+'/guide.html');assert.ok(result.content.some(c=>c.type==='resource_link'));}const read=await client.readResource({uri:'https://'+s.host+'/examples/'+scenarios(s.id)[0].key+'.json'});assert.deepEqual(JSON.parse(read.contents[0].text),scenarios(s.id)[0].input);}assert.equal(trace[0].method,'server/discover');assert.ok(trace.filter(t=>t.method).every(t=>t.version==='2026-07-28')); }finally{await client.close();}});
test('2025-era SDK clients interoperate with the same calculations and citation structure',async()=>{const {client}=await connect(hubHost,true);try{assert.ok((await client.listTools()).tools.some(t=>t.name===toolNames.calls));for(const s of sites){const r=await client.callTool({name:toolNames[s.id],arguments:s.sample});assert.ok(!r.isError,JSON.stringify(r));assert.deepEqual(r.structuredContent.report,run(s.id,s.sample));}}finally{await client.close();}});
test('single-tool endpoints cannot call or read sibling tools; fetch IDs are not arbitrary URLs',async()=>{for(const s of sites){const {client}=await connect(s.host);try{assert.deepEqual((await client.listTools()).tools.map(t=>t.name),['search','fetch',toolNames[s.id]]);const sibling=sites.find(x=>x.id!==s.id);await assert.rejects(()=>client.readResource({uri:'https://'+sibling.host+'/guide.md'}));const wrong=await client.callTool({name:'fetch',arguments:{id:'https://internal.invalid/secrets'}}).catch(e=>({isError:true}));assert.equal(wrong.isError,true);const call=await client.callTool({name:toolNames[sibling.id],arguments:sibling.sample}).catch(e=>({isError:true}));assert.equal(call.isError,true);}finally{await client.close();}}});
test('engine errors remain visible; unknown fields and unsafe money never become successful reports',async()=>{const {client}=await connect();try{for(const input of [{...sites[0].sample,extra:'untrusted'}, {...sites[0].sample,invoices:[{...sites[0].sample.invoices[0],amount:5}]}]){const r=await client.callTool({name:toolNames.reconcile,arguments:input}).catch(()=>({isError:true}));assert.equal(r.isError,true);}const invalid=structuredClone(sites[0].sample);invalid.transfers[0].amount='1e9';const r=await client.callTool({name:toolNames.reconcile,arguments:invalid});assert.equal(r.isError,true);assert.equal(r.structuredContent,undefined);}finally{await client.close();}});
const request=(body,headers={},method='POST')=>new Request('https://'+hubHost+'/mcp',{method,headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream',...headers},...(method==='POST'?{body:typeof body==='string'?body:JSON.stringify(body)}:{})});
test('MCP perimeter validates origin, methods, body size, content type and rate limits without storing records',async()=>{let writes=0;const e={...env,DB:{prepare(){writes++;throw Error('MCP must not use D1');}}};const rpc={jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-11-25',capabilities:{},clientInfo:{name:'test',version:'1'}}};const ok=await worker.fetch(request(rpc),e);assert.equal(ok.status,200);assert.equal(ok.headers.get('Cache-Control'),'no-store');assert.equal(writes,0);assert.equal((await worker.fetch(request(rpc,{Origin:'https://evil.example'}),e)).status,403);assert.equal((await worker.fetch(request(rpc,{Origin:'null'}),e)).status,403);assert.equal((await worker.fetch(request(rpc,{'Content-Type':'text/plain'}),e)).status,415);assert.equal((await worker.fetch(request('x'.repeat(131073)),e)).status,413);assert.equal((await worker.fetch(request('{bad'),e)).status,400);assert.equal((await worker.fetch(request({jsonrpc:'2.0',id:1,method:'ping',params:{number:9007199254740992}}),e)).status,400);assert.equal((await worker.fetch(request(null,{},'GET'),e)).status,405);assert.equal((await worker.fetch(request(null,{},'DELETE'),e)).status,405);const cors=await worker.fetch(request(null,{Origin:'https://chatgpt.com'},'OPTIONS'),e);assert.equal(cors.status,204);assert.equal(cors.headers.get('Access-Control-Allow-Origin'),'https://chatgpt.com');const limited=await worker.fetch(request(rpc),{...env,MCP_LIMIT:{limit:async()=>({success:false})}});assert.equal(limited.status,429);assert.equal(limited.headers.get('Retry-After'),'60');assert.equal((await worker.fetch(request(rpc),{ASSETS:env.ASSETS})).status,503);});
