import test from 'node:test';import assert from 'node:assert/strict';
import {assets,parseResearchPrices,parseHistory,changeFrom,makeBaseline,readBaseline,compareBaseline,reviewValue,reviewMarkdown} from '../public/research-core.mjs';
import {sourceState,researchResult,researchMarkup} from '../research.mjs';
import {webcrypto} from 'node:crypto';import {mineResearchProof,verifyResearchProof,encodeProof,decodeProof} from '../public/proof-core.mjs';
import {calculateFinanceScenario,decodeFinanceShare,financeShareUrl} from '../public/finance-core.mjs';
globalThis.crypto??=webcrypto;
const now=Date.parse('2026-09-20T01:00:00Z');
const prices=()=>({coins:Object.fromEntries(assets.map(a=>['coingecko:'+a.id,{symbol:a.symbol,price:100,timestamp:now/1000-60}]))});
const history=()=>({coins:Object.fromEntries(assets.map(a=>['coingecko:'+a.id,{symbol:a.symbol,prices:Array.from({length:8},(_,i)=>({timestamp:now/1000-(7-i)*86400,price:50+i*5}))}]))});
test('one stale or malformed asset is labelled without fabricating or hiding other prices',()=>{const p=prices();p.coins['coingecko:akash-network'].timestamp-=1500;p.coins['coingecko:render-token'].price='100';p.coins['coingecko:fetch-ai'].symbol='FAKE';const q=parseResearchPrices(p,now);assert.equal(q.find(x=>x.symbol==='AKT').status,'stale');assert.equal(q.find(x=>x.symbol==='RENDER').price,null);assert.equal(q.find(x=>x.symbol==='FET').price,null);assert.equal(q[0].status,'fresh');assert.throws(()=>parseResearchPrices({}));});
test('history rejects non-monotonic, future and hostile values while retaining valid assets',()=>{const r=history();r.coins['coingecko:bitcoin'].prices[1].timestamp=r.coins['coingecko:bitcoin'].prices[0].timestamp;r.coins['coingecko:ethereum'].prices[2].price=Infinity;const h=parseHistory(r,now);assert.equal(h[0].points.length,0);assert.equal(h[1].points.length,0);assert.equal(h[2].points.length,8);});
test('sampled comparisons disclose actual endpoints and reject stale or distant reference values',()=>{const q=parseResearchPrices(prices(),now)[0],p=parseHistory(history(),now)[0].points;const day=changeFrom(q,p,1);assert.equal(day.percent,25);assert.equal(day.from,p[6].at);assert.equal(day.to,q.sourceUpdatedAt);assert.equal(changeFrom({...q,status:'stale'},p,1),null);assert.equal(changeFrom(q,p.slice(0,4),1),null);assert.equal(changeFrom(q,[],7),null);});
test('expired source caches and fresh receipts cannot disguise stale provider data',()=>{const p={rows:parseResearchPrices(prices(),now),retrievedAt:new Date(now).toISOString()},h={rows:parseHistory(history(),now),retrievedAt:new Date(now).toISOString()};assert.equal(sourceState(p,'prices',now+301000).status,'stale');assert.equal(sourceState(p,'prices',now+86401000).rows.length,0);const d=researchResult({...p,status:'fresh'},{...h,status:'fresh'},now+1000000);assert.ok(d.quotes.every(q=>q.status==='stale'&&q.day===null));const fallback=researchResult({...p,status:'fresh'},{rows:[],status:'unavailable'},now);assert.equal(fallback.quotes[0].price,100);assert.equal(fallback.quotes[0].day,null);});
test('saved baseline validates age, types, duplicates and chronology before returning deltas',()=>{const q=parseResearchPrices(prices(),now),saved=makeBaseline(q,['BTC','FAKE'],now);assert.equal(saved.quotes.length,1);assert.deepEqual(readBaseline(JSON.stringify(saved),now),saved);assert.equal(readBaseline(JSON.stringify(saved),now+31*86400000),null);assert.equal(readBaseline(JSON.stringify({...saved,quotes:[...saved.quotes,...saved.quotes]}),now),null);assert.throws(()=>makeBaseline(q,['FAKE'],now));assert.equal(compareBaseline(saved,q,now)[0].percent,null);const changed=q.map(x=>({...x,price:110,sourceUpdatedAt:new Date(now).toISOString()}));assert.ok(Math.abs(compareBaseline(saved,changed,now)[0].percent-10)<1e-9);assert.equal(compareBaseline(saved,changed,now+901000)[0].percent,null);});
test('research notes require counterevidence and an actual calendar date; exports are user-authored',()=>{const v={claim:'Test claim',evidence:'Original source',counter:'Unknown adoption',invalidate:'Measured repeat use falls',reviewDate:'2026-10-01'};assert.deepEqual(reviewValue(v),v);assert.throws(()=>reviewValue({...v,counter:''}));assert.throws(()=>reviewValue({...v,reviewDate:'2026-02-31'}));assert.match(reviewMarkdown(v,[],new Date(now).toISOString()),/User-authored note/);assert.match(reviewMarkdown(v),/What would change my mind/);});
test('rendered research remains source-stamped, escaped and explicit about missing history',()=>{const p={rows:parseResearchPrices(prices(),now),status:'fresh',retrievedAt:new Date(now).toISOString(),url:'https://coins.llama.fi/'},d=researchResult(p,{status:'unavailable',rows:[]},now);d.updates={status:'fresh',items:[{title:'<script>alert(1)</script>',url:'https://blog.ethereum.org/',source:'EF',publishedAt:'2026-09-19',kind:'rss'}]};const html=researchMarkup(d);assert.match(html,/History unavailable/);assert.ok(!html.includes('<script>alert'));assert.match(html,/&lt;script&gt;/);assert.match(html,/not an explanation of token-price moves/);assert.equal((html.match(/data-asset=/g)||[]).length,assets.length);});

test('research proof is a verifiable non-transferable hash commitment without private note contents',async()=>{const note={claim:'AI usage rose',evidence:'https://example.test/source',counter:'Price movement is not adoption',invalidate:'Paid workload falls',reviewDate:'2026-10-01'};const proof=await mineResearchProof({note,symbol:'TAO',createdAt:'2026-09-20T01:00:00.000Z',difficulty:2});assert.match(proof.digest,/^00/);assert.equal((await verifyResearchProof(proof)).valid,true);assert.equal((await verifyResearchProof(proof,note)).valid,true);assert.equal((await verifyResearchProof(proof,{...note,claim:'changed'})).valid,false);assert.deepEqual(decodeProof(encodeProof(proof)),proof);});

test('finance scenario cards calculate assumptions and round-trip share links without private text',()=>{const s=calculateFinanceScenario({asset:'USDC',amount:1000,fixedFee:.3,percentFee:.4,fxSpread:.2,retryRate:1,settlementFee:.05});assert.equal(s.total.toFixed(2),'1016.41');const url=financeShareUrl('https://web3.agiscorecard.com',s);assert.match(url,/finance=/);const decoded=decodeFinanceShare(new URL(url).searchParams.get('finance'));assert.deepEqual(decoded,{asset:'USDC',amount:1000,fixedFee:.3,percentFee:.4,fxSpread:.2,retryRate:1,settlementFee:.05});assert.equal(url.includes('private'),false);});

