import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import worker,{feedbackShape} from '../worker.mjs';import {sites,hubHost} from '../public/catalog.mjs';
const assetCalls=[];const env={ASSETS:{fetch:async request=>{const p=new URL(request.url).pathname;assetCalls.push(p);try{return new Response(await readFile('dist'+p));}catch{return new Response('Missing',{status:404});}}}};
globalThis.caches={default:{match:async key=>new Response(JSON.stringify({retrievedAt:new Date().toISOString(),quotes:[],items:[],sources:[],rows:[]}))}};
const get=(host,path='/',method='GET')=>worker.fetch(new Request('https://'+host+path,{method}),env);
test('all hostnames serve their own page and never a sibling page',async()=>{for(const s of sites){const r=await get(s.host);assert.equal(r.status,200);assert.ok((await r.text()).includes('data-site="'+s.id+'"'));assert.equal((await get(s.host,'/evidence/index.html')).status,404);}assert.equal((await get(hubHost)).status,200);assert.equal((await get('unknown.example.org')).status,404);});
test('shared modules, guides and examples resolve without redirects',async()=>{for(const path of ['/engine.mjs','/guide.html','/examples/input.json','/offline-tools.zip']){const r=await get(sites[0].host,path);assert.equal(r.status,200);assert.equal(r.headers.get('Location'),null);}assert.equal((await get(hubHost,'/examples/input.json')).status,404);});
test('security headers, missing paths and read-only methods',async()=>{const r=await get(sites[0].host);assert.match(r.headers.get('Content-Security-Policy'),/default-src 'none'/);assert.equal(r.headers.get('X-Content-Type-Options'),'nosniff');assert.equal((await get(sites[0].host,'/missing')).status,404);assert.equal((await get(sites[0].host,'/','POST')).status,405);assert.equal(await(await get(sites[0].host,'/','HEAD')).text(),'');});
test('profiles API filters, describes provenance, and rejects unsupported input',async()=>{const host='protocol.agiscorecard.com';const r=await get(host,'/api/v1/profiles?purpose=payment');assert.equal(r.status,200);assert.equal(r.headers.get('Access-Control-Allow-Origin'),'*');const v=await r.json();assert.equal(v.profiles.length,1);assert.ok(v.profiles[0].source.startsWith('https://'));assert.equal(v.checkedAt,'2026-09-19');assert.equal((await get(host,'/api/v1/profiles?purpose=bad')).status,400);assert.equal((await get(host,'/api/v1/profiles?wallet=private')).status,400);assert.equal((await get(host,'/api/v1/profiles?purpose=token&purpose=payment')).status,400);assert.equal((await get(host,'/api/v1/profiles/no-record')).status,404);assert.equal((await get(host,'/api/v1/profiles/erc-20')).status,200);assert.equal((await get(host,'/openapi.json')).status,200);assert.equal((await get(sites[0].host,'/api/v1/profiles')).status,404);});
const base={id:'a8e04aaa-4000-4000-8000-000000000001',frequency:'zero',usefulness:'sample',interest:'no',ownCompleted:false,qa:true};
test('feedback whitelist excludes raw input and misleading enum coercions',()=>{assert.equal(feedbackShape(base),true);assert.equal(feedbackShape({...base,input:'private'}),false);assert.equal(feedbackShape({...base,ownCompleted:'yes'}),false);assert.equal(feedbackShape({...base,frequency:'paid'}),false);});
test('feedback rejects cross-origin and unavailable storage',async()=>{const url='https://'+sites[0].host+'/api/feedback';const make=origin=>new Request(url,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(base)});assert.equal((await worker.fetch(make('https://evil.example'),env)).status,403);assert.equal((await worker.fetch(make('https://'+sites[0].host),env)).status,503);});
test('feedback is size-bounded and writes only its isolated table',async()=>{const queries=[],db={prepare:sql=>({run:async()=>{queries.push(sql);return {};},bind:(...args)=>({run:async()=>{queries.push(sql);assert.equal(args.length,7);assert.equal(args[6],1);return {};}})})};const e={...env,DB:db,EVENT_LIMIT:{limit:async()=>({success:true})}},url='https://'+sites[0].host+'/api/feedback',make=body=>new Request(url,{method:'POST',headers:{Origin:'https://'+sites[0].host,'Content-Type':'application/json'},body});assert.equal((await worker.fetch(make(JSON.stringify(base)),e)).status,200);assert.ok(queries.every(q=>q.includes('web3_studio_feedback')));assert.equal((await worker.fetch(make(' '.repeat(1500)),e)).status,400);e.EVENT_LIMIT.limit=async()=>({success:false});assert.equal((await worker.fetch(make(JSON.stringify(base)),e)).status,429);});
test('new discoverability assets preserve per-host boundaries and canonical HTML paths',async()=>{for(const s of sites){for(const path of ['/examples.html','/guide.md','/input.schema.json','/tool.json','/llms-full.txt','/share.png'])assert.equal((await get(s.host,path)).status,200,s.id+path);assert.equal((await get(s.host,'/publish.html')).status,404);assert.equal((await get(s.host,'/examples/arbitrary.json')).status,404);assert.equal((await get(s.host,'/index.html?scenario=demo')).headers.get('Location'),'https://'+s.host+'/?scenario=demo');const md=await get(s.host,'/guide.md');assert.equal(md.headers.get('X-Robots-Tag'),'noindex');assert.match(md.headers.get('Content-Type'),/text\/markdown/);const meta=await(await get(s.host,'/tool.json')).json();assert.equal(meta.url,'https://'+s.host+'/');for(const c of meta.examples)assert.equal((await get(s.host,new URL(c.input).pathname)).status,200);}
 assert.equal((await get(hubHost,'/publish.html')).status,200);assert.equal((await get(hubHost,'/tools.json')).status,200);assert.equal((await get(hubHost,'/examples.html')).status,404);assert.equal((await get(hubHost,'/tool.json')).status,404);
 for(const host of [hubHost,...sites.map(s=>s.host)])assert.equal(await(await get(host,'/16507d8e1997c4be371f5fbaf7ac1985.txt')).text(),'16507d8e1997c4be371f5fbaf7ac1985');
});

test('deployment manifest covers every canonical page and has resolvable normalized routes',async()=>{const manifest=JSON.parse(await readFile('asset-manifest.generated.json','utf8'));for(const [host,files]of Object.entries(manifest)){for(const path of ['/','/guide.html','/privacy.html','/share.png','/sitemap.xml'])assert.ok(files[path],host+path);for(const [path,local]of Object.entries(files)){assert.ok(!path.includes('//'),path);assert.ok(!local.includes('//'),local);assert.equal((await get(host,path)).status,200,host+path);}}});

test('research context is read-only, scoped and rejects arbitrary source URLs',async()=>{for(const path of ['/api/research?url=https://evil.test','/api/research?format=json','/api/research?format=html&format=html'])assert.equal((await get(hubHost,path)).status,400);assert.equal((await get(hubHost,'/api/research','POST')).status,405);assert.equal((await get(sites[0].host,'/api/research')).status,404);const r=await get(hubHost,'/api/research');assert.equal(r.status,200);assert.equal(r.headers.get('X-Robots-Tag'),'noindex');const body=await r.json();assert.ok(body.quotes.every(q=>q.price===null&&q.day===null));});
