import {lessons,hubCopy} from './learning.mjs';
import {planningCopy,planningHTML} from './planning-pages.mjs';
export const extraSlugs=['brands','collector-tools','collecting','collecting/budget','collecting/duplicates',...lessons.map(x=>x.slug),'editorial'];
export function expansionParagraphs(lang,route,origin){return [...lessons.map(x=>x[lang].title+'\n'+x[lang].intro+'\n'+origin+route(lang,x.slug)),planningCopy[lang].budgetTitle+'\n'+origin+route(lang,'collecting/budget'),planningCopy[lang].progressTitle+'\n'+origin+route(lang,'collecting/duplicates')];}
export function readingLinks(lang,route){const c=hubCopy[lang];return `<section class="reading-section"><h2>${c.learn}</h2><p>${c.learnIntro}</p><div class="reading-list">${lessons.map(x=>`<a href="${route(lang,x.slug)}"><strong>${x[lang].title}</strong><span>${x[lang].intro}</span></a>`).join('')}</div></section>`;}
export function relatedPlanning(lang,route){const c=planningCopy[lang];return `<aside class="related-planning"><h2>${c.related}</h2><div class="actions"><a class="button" href="${route(lang,'collecting/budget')}">${c.budgetLink}</a><a class="button" href="${route(lang,'collecting/duplicates')}">${c.progressLink}</a><a class="button" href="${route(lang,'collecting/check-retailers')}">${lessons[1][lang].title}</a></div></aside>`;}
export function buildExpansion({brands,locales,origin,updated,write,emit,route,esc,art,copy}){
 const entries=[];
 for(const lang of Object.keys(locales)){
 const c=hubCopy[lang],p=planningCopy[lang],base=copy[lang],hero=(title,intro)=>`<section class="field-hero"><p class="breadcrumb"><a href="/">${base.home}</a> / <a href="${route(lang,'collecting')}">${c.learn}</a></p><h1>${title}</h1><p class="brand-lead">${intro}</p></section>`,byline=`<p class="editorial-byline"><a href="${route(lang,'editorial')}">${c.byline}</a> · ${c.checked}: <time datetime="${updated}">${updated}</time></p>`;
 const brandRows=brands.map(b=>`<article class="brand-directory-row"><div class="directory-art" data-brand="${b.id}">${art(b.art)}</div><div><h2><a href="${route(lang,'brands/'+b.id)}">${esc(b.name)}</a></h2><p>${b[lang].intro}</p><a href="${b[lang].tool}">${b[lang].cta}</a></div></article>`).join('');
 emit(lang,'brands',c.brands,c.brandsIntro,hero(c.brands,c.brandsIntro)+brandRows,[c.brandsIntro,...brands.map(b=>b.name+': '+b[lang].intro+'\n'+origin+route(lang,'brands/'+b.id))],[{'@type':'ItemList',name:c.brands,itemListElement:brands.map((b,i)=>({'@type':'ListItem',position:i+1,name:b.name,url:origin+route(lang,'brands/'+b.id)}))}]);
 const tools=[{title:p.budgetTitle,intro:p.budgetIntro,slug:'collecting/budget',symbol:'$'},{title:p.progressTitle,intro:p.progressIntro,slug:'collecting/duplicates',symbol:'+'},{title:base.taskNames[0],intro:base.taskDescriptions[0],slug:'brands/labubu#style-probability',symbol:'%'},{title:base.taskNames[1],intro:base.taskDescriptions[1],slug:'brands/jellycat#display-fit',symbol:'↔'},{title:base.taskNames[2]+(lang==='zh'?'（英文）':''),intro:base.taskDescriptions[2],href:(lang==='de'?'/de':'')+'/collection-tracker',symbol:'✓'}];
 emit(lang,'collector-tools',c.tools,c.toolsIntro,hero(c.tools,c.toolsIntro)+`<div class="tool-directory">${tools.map(t=>`<article><span class="task-symbol" aria-hidden="true">${t.symbol}</span><div><h2><a href="${t.href||route(lang,t.slug)}">${t.title}</a></h2><p>${t.intro}</p></div></article>`).join('')}</div>`+relatedPlanning(lang,route),[c.toolsIntro,...tools.map(t=>t.title+'\n'+t.intro+'\n'+origin+(t.href||route(lang,t.slug)))],[{'@type':'ItemList',name:c.tools,itemListElement:tools.map((t,i)=>({'@type':'ListItem',position:i+1,name:t.title,url:origin+(t.href||route(lang,t.slug))}))}]);
 emit(lang,'collecting',c.learn,c.learnIntro,hero(c.learn,c.learnIntro)+readingLinks(lang,route)+relatedPlanning(lang,route),[c.learnIntro,...lessons.map(l=>l[lang].title+'\n'+l[lang].intro+'\n'+origin+route(lang,l.slug)),p.budgetTitle+'\n'+origin+route(lang,'collecting/budget'),p.progressTitle+'\n'+origin+route(lang,'collecting/duplicates')]);
 for(const lesson of lessons){const d=lesson[lang],sources=d.sources||lesson.sources,url=origin+route(lang,lesson.slug),paragraphs=[d.intro,...d.sections.map(s=>s.join('\n')),...sources.map(s=>s.join(': '))];
 const body=hero(d.title,d.intro)+byline+`<article class="field-article">${d.sections.map(([title,text])=>`<section><h2>${title}</h2><p>${text}</p></section>`).join('')}<section class="article-sources"><h2>${c.source}</h2><ul>${sources.map(([name,url])=>`<li><a href="${url}">${esc(name)}</a></li>`).join('')}</ul></section></article>`+relatedPlanning(lang,route)+readingLinks(lang,route);
 emit(lang,lesson.slug,d.title,d.intro,body,paragraphs,[{'@type':'Article',headline:d.title,description:d.intro,mainEntityOfPage:url,dateModified:updated,author:{'@id':origin+'/#publisher'},publisher:{'@id':origin+'/#publisher'},citation:sources.map(s=>s[1])}]);entries.push({language:lang,url,title:d.title,intro:d.intro,sections:d.sections,sources,reviewed:updated});
 }
 for(const kind of ['budget','duplicates']){const title=kind==='budget'?p.budgetTitle:p.progressTitle,intro=kind==='budget'?p.budgetIntro:p.progressIntro,slug='collecting/'+kind;
 emit(lang,slug,title,intro,hero(title,intro)+byline+planningHTML(lang,kind)+relatedPlanning(lang,route)+readingLinks(lang,route),[intro,p.exampleNote,...(kind==='budget'?[p.money,p.budgetMethod,p.budgetExample]:[p.progressMethod,p.progressExample]),p.limit],[{'@type':'WebApplication',name:title,description:intro,url:origin+route(lang,slug),applicationCategory:'UtilitiesApplication',operatingSystem:'Web browser',isAccessibleForFree:true}]);}
 emit(lang,'editorial',c.editorial,c.editorialIntro,hero(c.editorial,c.editorialIntro)+`<article class="field-article">${c.methodSections.map(([t,p])=>`<section><h2>${t}</h2><p>${p}</p></section>`).join('')}<p><a href="https://github.com/f-tiger/agi-site/issues/new">${lang==='zh'?'提交公开纠错（GitHub）':lang==='de'?'Öffentliche Korrektur melden (GitHub)':'Report a public correction (GitHub)'}</a></p><p><a href="/legal/affiliate-disclosure">${base.affiliates}</a> · <a href="/legal/privacy">${base.privacy}</a></p></article>`,[c.editorialIntro,...c.methodSections.map(s=>s.join('\n')),'https://github.com/f-tiger/agi-site/issues/new']);
 }
 write('collector-assets/learning-guides.json',JSON.stringify({updated,guides:entries,limitations:'Published independent guidance; no live stock, seller certification or search visibility guarantee.'},null,2)+'\n');
}
