import fs from 'node:fs';import assert from 'node:assert/strict';
import {SERVER,REGISTRY_NAME} from '../../collector-assets/mcp-contract.mjs';
const manifest=JSON.parse(fs.readFileSync(new URL('../../mcp/server.json',import.meta.url),'utf8'));
assert.equal(manifest.name,REGISTRY_NAME);assert.equal(manifest.version,SERVER.version);assert.ok(manifest.description.length<=100);assert.equal(manifest.remotes[0].url,'https://thedollscout.com/mcp');
// Use the documented exact-name endpoint rather than the registry-wide search.
// Transient network errors are retried; an unavailable registry is never called absent.
const check=async()=>{let last;for(let attempt=0;attempt<3;attempt++){try{const r=await fetch('https://registry.modelcontextprotocol.io/v0.1/servers/'+encodeURIComponent(REGISTRY_NAME)+'/versions/latest',{signal:AbortSignal.timeout(30000)});if(r.status===404)return false;assert.equal(r.status,200);const j=await r.json();assert.equal(j.server?.name,REGISTRY_NAME);const hit=j.server.version===SERVER.version&&j._meta?.['io.modelcontextprotocol.registry/official']?.isLatest;if(hit)assert.equal(j.server.remotes[0].url,manifest.remotes[0].url);return Boolean(hit);}catch(e){last=e;if(attempt<2)await new Promise(r=>setTimeout(r,2000));}}throw last;};
if(process.argv.includes('--pre')){const present=await check();if(process.env.GITHUB_OUTPUT)fs.appendFileSync(process.env.GITHUB_OUTPUT,'present='+present+'\n');console.log(JSON.stringify({registered:present,name:REGISTRY_NAME,version:SERVER.version}));}
else {let found=false;for(let i=0;i<6;i++){if(await check()){found=true;break;}if(i<5)await new Promise(r=>setTimeout(r,10000));}assert.ok(found,'Registry does not show the expected latest version');console.log(JSON.stringify({registered:true,name:REGISTRY_NAME,version:SERVER.version,endpoint:manifest.remotes[0].url}));}
