import {readState} from './daily.mjs';
export const seriesState=readState();
export const seriesSlugs=['series',...seriesState.series.map(s=>'series/'+s.id)];
const copy={
 en:{title:'Find your next series',intro:'Official names. Your checklist. A clearer plan before the next box.',tag:'THE SERIES DESK',names:'Build your checklist',check:'Select the styles you already own. This checklist stays in this tab and resets when you leave.',count:'owned',left:'still to collect',odds:'One style. What are your chances?',method:'Enter the probability printed for the exact style on your package. A list of names does not establish equal odds. This calculator assumes independent boxes with an unchanged probability; sealed no-repeat cases and boxes with hints need another model.',p:'Printed probability per box (%)',n:'Independent boxes',calculate:'Calculate probability',pending:'Add the printed probability and a box count to calculate.',hit:'Chance of at least one',miss:'Chance of none',error:'Use a probability from 0 to 100 and a whole box count from 1 to 100,000.',source:'Check the official series',verified:'Source checked',modified:'Checklist updated',unknown:'Prices, availability, dimensions and secret odds are not verified here. Names stay in the official source language. This is an independent checklist, not an official brand page.',plan:'Continue your collection plan',budget:'Set a budget',display:'Measure display space',all:'All series',status:'Daily source desk',statusText:'Checked automatically each day. At most two new series are added per day, with at least six named styles and a working checklist. No eligible change means no new page. Source-check dates are not product release dates.',ok:'All configured sources checked',partial:'Some sources unavailable; last verified entries retained',failed:'Sources unavailable; last verified entries retained',latest:'Latest check',scope:'Automatic series coverage: SMISKI figures and Sonny Angel regular-series galleries. Other brand guides remain separately curated.',assumptions:'Model and limits',result:'Your result',download:'Copy checklist',copied:'Checklist copied',copyFail:'Copy unavailable; select the names above.',selected:'Owned',missing:'Missing',empty:'No verified series yet. The next successful daily source check will add eligible entries.'},
 de:{title:'Ihre nächste Serie entdecken',intro:'Offizielle Namen. Ihre Checkliste. Ein klarer Plan vor der nächsten Box.',tag:'DAS SERIENREGAL',names:'Ihre Checkliste',check:'Bereits vorhandene Figuren auswählen. Die Liste bleibt in diesem Tab und wird beim Verlassen zurückgesetzt.',count:'vorhanden',left:'fehlen noch',odds:'Eine Figur. Wie stehen die Chancen?',method:'Die auf der Verpackung angegebene Chance für genau diese Figur eingeben. Figurennamen belegen keine gleichen Chancen. Das Modell gilt für unabhängige Boxen mit unveränderter Wahrscheinlichkeit, nicht für versiegelte Sets ohne Wiederholungen oder Boxen mit Hinweisen.',p:'Angegebene Chance pro Box (%)',n:'Unabhängige Boxen',calculate:'Wahrscheinlichkeit berechnen',pending:'Angegebene Chance und Boxenzahl eingeben.',hit:'Chance auf mindestens einen Treffer',miss:'Chance auf keinen Treffer',error:'Wahrscheinlichkeit von 0 bis 100 und ganze Boxenzahl von 1 bis 100.000 eingeben.',source:'Offizielle Serie prüfen',verified:'Quelle geprüft',modified:'Checkliste aktualisiert',unknown:'Preise, Verfügbarkeit, Maße und Secret-Chancen sind hier nicht verifiziert. Namen bleiben in der Sprache der offiziellen Quelle. Diese unabhängige Checkliste ist keine offizielle Markenseite.',plan:'Sammlung weiter planen',budget:'Budget planen',display:'Ausstellungsplatz messen',all:'Alle Serien',status:'Täglicher Quellencheck',statusText:'Tägliche automatische Prüfung. Höchstens zwei neue Serien pro Tag mit mindestens sechs benannten Figuren und einer nutzbaren Checkliste. Ohne geeignete Änderung keine neue Seite. Das Prüfdatum ist kein Erscheinungsdatum.',ok:'Alle eingerichteten Quellen geprüft',partial:'Einige Quellen nicht erreichbar; letzte geprüfte Einträge bleiben erhalten',failed:'Quellen nicht erreichbar; letzte geprüfte Einträge bleiben erhalten',latest:'Letzte Prüfung',scope:'Automatische Serien: SMISKI-Figuren und Sonny-Angel-Standardserien. Andere Markenratgeber werden separat gepflegt.',assumptions:'Modell und Grenzen',result:'Ihr Ergebnis',download:'Checkliste kopieren',copied:'Checkliste kopiert',copyFail:'Kopieren nicht verfügbar; Namen oben auswählen.',selected:'Vorhanden',missing:'Fehlend',empty:'Noch keine geprüften Serien. Der nächste erfolgreiche Quellencheck ergänzt geeignete Einträge.'},
 zh:{title:'下一套，先做功课',intro:'官方款式清单，加上你的收藏进度。开下一盒前，先有计划。',tag:'SERIES DESK / 系列情报',names:'建立你的收藏清单',check:'勾选已经拥有的款式。清单仅保留在当前页面，离开或刷新后重置。',count:'款已拥有',left:'款待收集',odds:'想抽中这一款，机会多大？',method:'请填写包装标注的这一个款式的概率。款式数量不能证明等概率。本工具只计算概率固定的独立抽盒；整箱不重复配货、带提示的剩余盒等情况不能直接套用。',p:'包装标注的单款概率（%）',n:'独立抽取盒数',calculate:'计算抽中概率',pending:'填写包装概率和盒数后计算。',hit:'至少抽中一次',miss:'一次也没抽中',error:'概率需在 0 至 100 之间，盒数需为 1 至 100,000 的整数。',source:'核对官方系列资料',verified:'来源核对日期',modified:'清单更新日期',unknown:'此处未核实售价、库存、尺寸或隐藏款概率。款式名称保留官方来源原文。本页为独立收藏清单，并非品牌官方网站。',plan:'继续规划你的收藏',budget:'设定预算',display:'测量展示空间',all:'全部系列',status:'每日来源检查',statusText:'每天自动检查官方资料，每日最多新增两个具备至少六个明确款式名称和可用清单的系列。没有合格更新就不新增页面。核对日期不代表新品发布日期。',ok:'已检查全部已配置来源',partial:'部分来源不可用，保留上次核实内容',failed:'来源暂不可用，保留上次核实内容',latest:'最近检查',scope:'自动系列范围：SMISKI 手办与 Sonny Angel 常规系列图册。其他品牌指南单独维护。',assumptions:'计算模型与边界',result:'计算结果',download:'复制清单',copied:'清单已复制',copyFail:'暂时无法复制，请选取上方名称。',selected:'已拥有',missing:'待收集',empty:'暂未取得合格系列资料；下次成功检查后会新增符合要求的条目。'}
};
export function seriesLinks(lang,route,esc,brand){const list=seriesState.series.filter(s=>!brand||s.brand===brand),c=copy[lang];if(!list.length)return '';return `<section class="series-preview"><div class="section-heading"><div><p class="eyebrow">${c.tag}</p><h2>${c.title}</h2></div><a href="${route(lang,'series')}">${c.all} →</a></div><div class="series-grid">${list.slice(-4).reverse().map(s=>`<article class="series-card" data-brand="${s.brand}"><span class="series-number" aria-hidden="true">${s.names.length}</span><h3><a href="${route(lang,'series/'+s.id)}">${esc(s.title)}</a></h3><p>${esc(s.names.slice(0,3).join(' · '))}</p><a href="${route(lang,'series/'+s.id)}#checklist">${c.names} →</a></article>`).join('')}</div></section>`;}
export function buildSeries({emit,write,route,esc,origin,locales,brands}){
 const records=seriesState.series,run=seriesState.lastRun;
 for(const lang of Object.keys(locales)){const c=copy[lang],day=run?.date||'2026-10-02';
 const desk=`<aside class="series-desk"><h2>${c.status}</h2><p>${c.statusText}</p><p>${c.scope}</p>${run?`<p>${c.latest}: <time datetime="${run.date}">${run.date}</time> · ${c[run.status]}</p>`:''}<a href="/collector-assets/series-catalog.json">JSON · ${records.length}</a> · <a href="https://github.com/f-tiger/agi-site/actions/workflows/deploy-thedollscout.yml">GitHub Actions</a></aside>`;
 const intro=`<section class="field-hero"><p class="eyebrow">${c.tag}</p><h1>${c.title}</h1><p class="brand-lead">${c.intro}</p></section>`;
 const rows=records.map(s=>`<article class="series-directory-row" data-brand="${s.brand}"><span class="series-number" aria-hidden="true">${s.names.length}</span><div><h2><a href="${route(lang,'series/'+s.id)}">${esc(s.title)}</a></h2><p>${esc(s.names.slice(0,3).join(' · '))}</p><p class="small">${c.verified}: ${s.checked}</p></div><a class="button" href="${route(lang,'series/'+s.id)}#checklist">${c.names}</a></article>`).join('');
 emit(lang,'series',c.title,c.intro,intro+(rows||`<p>${c.empty}</p>`)+desk,[c.intro,c.scope,c.statusText,...records.map(s=>s.title+'\n'+origin+route(lang,'series/'+s.id))],[{'@type':'ItemList',name:c.title,itemListElement:records.map((s,i)=>({'@type':'ListItem',position:i+1,name:s.title,url:origin+route(lang,'series/'+s.id)}))}],day);
 for(const s of records){const brand=brands.find(b=>b.id===s.brand),url=origin+route(lang,'series/'+s.id),desc=s.title+' — '+c.intro;
 const body=`<section class="field-hero series-hero" data-brand="${s.brand}"><p class="breadcrumb"><a href="${route(lang,'series')}">${c.all}</a> / <a href="${route(lang,'brands/'+s.brand)}">${esc(brand.name)}</a></p><p class="eyebrow">${c.tag}</p><h1>${esc(s.title)}</h1><p class="brand-lead">${c.intro}</p><div class="actions"><a class="button primary" href="#checklist">${c.names}</a><a class="button" href="#series-odds">${c.calculate}</a></div></section><p class="small">${c.verified}: <time datetime="${s.checked}">${s.checked}</time> · ${c.modified}: ${s.modified}</p><section id="checklist" class="series-checklist" data-series-checklist><h2>${c.names}</h2><p>${c.check}</p><div class="checklist-grid">${s.names.map(n=>`<label><input type="checkbox"><span>${esc(n)}</span></label>`).join('')}</div><p class="checklist-total" role="status"><strong data-owned>0</strong> ${c.count} · <strong data-missing>${s.names.length}</strong> ${c.left}</p><button type="button" class="button" data-checklist-copy>${c.download}</button><p class="small" data-copy-status role="status"></p><script type="application/json" data-checklist-labels>${JSON.stringify({title:s.title,selected:c.selected,missing:c.missing,copied:c.copied,copyFail:c.copyFail}).replace(/</g,'\\u003c')}</script></section><section id="series-odds" class="series-odds" data-series-odds><h2>${c.odds}</h2><form><label>${c.p}<input name="probability" type="number" min="0" max="100" step="any" required inputmode="decimal"></label><label>${c.n}<input name="boxes" type="number" min="1" max="100000" step="1" required inputmode="numeric"></label><button class="button primary" type="submit">${c.calculate}</button></form><div class="series-result" data-series-result aria-live="polite">${c.pending}</div><p role="alert" data-series-error></p><details open><summary>${c.assumptions}</summary><p>${c.method}</p></details><script type="application/json" data-series-labels>${JSON.stringify({hit:c.hit,miss:c.miss,error:c.error}).replace(/</g,'\\u003c')}</script></section><section class="official-panel"><div><h2>${c.source}</h2><p>${c.unknown}</p></div><a class="button" href="${s.source}" rel="noopener">${esc(s.title)}</a></section><aside class="related-planning"><h2>${c.plan}</h2><div class="actions"><a class="button" href="${route(lang,'collecting/budget')}">${c.budget}</a><a class="button" href="${route(lang,'brands/'+s.brand)}#display-fit">${c.display}</a></div></aside>`;
 emit(lang,'series/'+s.id,s.title+' — '+c.names,desc,body,[c.intro,c.names+': '+s.names.join(', '),c.check,c.method,c.unknown,c.verified+': '+s.checked,c.source+': '+s.source,origin+route(lang,'collecting/budget')],[{'@type':'WebApplication',name:s.title+' — '+c.names,url,applicationCategory:'UtilitiesApplication',operatingSystem:'Web browser',isAccessibleForFree:true,citation:s.source}],s.modified);
 }
 }
 write('collector-assets/series-catalog.json',JSON.stringify({schema:1,lastRun:run,scope:'Official named checklists only; not stock, release dates, prices or probabilities.',series:records.map(({hash,...s})=>({...s,urls:Object.fromEntries(Object.keys(locales).map(l=>[l,origin+route(l,'series/'+s.id)])),mcpProbabilityTool:'calculate_style_probability',probabilityInput:'User supplies the probability printed for the exact style; no inferred odds.'}))},null,2)+'\n');
}
