export const styleNames=['Dada','Hehe','Baba','Sisi','Zizi','Ququ'];
export const styleSource='https://www.popmart.com/us/products/1372/the-monsters-have-a-seat-vinyl-plush-blind-box';
export const styleCopy={
 en:{title:'Which one are you hoping for?',intro:'Calculate the chance of your chosen style before opening another box.',series:'Series',other:'Other series',target:'What are you trying to pull?',targets:['One regular style','The secret style','Enter a known per-style probability'],style:'Choose your regular style',count:'Number of regular styles',secret:'Secret odds · 1 in N',percent:'Single-box probability (%)',boxes:'Independent boxes to open',submit:'Calculate my chances',label:'Chance of at least one',single:'In one box',none:'Chance of none',expected:'Expected number',milestones:'Boxes for 50% / 90%',example:'Editable example, not official odds. Start with your package.',assumption:'The regular-style model assumes the secret replaces a regular style and every regular style has the same chance: p = (1 − 1/N) ÷ K. The example uses K = 6 and N = 72. The official source confirms style names; it does not establish these model assumptions.',limit:'Independent draws only. A sealed no-repeat case or a POP NOW box with hints needs different information. Missing a style earlier does not make the next box luckier. Set a budget before buying.',known:'If your package states a probability for the exact style, choose “Enter a known per-style probability”.',source:'Check Have a Seat style names at POP MART',reference:'Open the secret-odds reference',error:'Check the highlighted fields. Box counts and odds denominators must be whole numbers; probability must be between 0 and 100.',method:'Model and limits',static:'Example: 12 independent boxes at secret odds of 1:72 give a 15.45% chance of at least one secret.',noscript:'Enable JavaScript to change the inputs and calculate. The worked example and assumptions are available without it.'},
 de:{title:'Welche Figur wünschen Sie sich?',intro:'Die Chance auf eine bestimmte Figur berechnen, bevor Sie weitere Boxen öffnen.',series:'Serie',other:'Andere Serie',target:'Welche Variante suchen Sie?',targets:['Eine bestimmte Standardfigur','Die Secret-Figur','Bekannte Einzelwahrscheinlichkeit eingeben'],style:'Standardfigur auswählen',count:'Anzahl der Standardfiguren',secret:'Secret-Chance · 1 zu N',percent:'Wahrscheinlichkeit pro Box (%)',boxes:'Anzahl unabhängiger Boxen',submit:'Chancen berechnen',label:'Chance auf mindestens eine',single:'In einer Box',none:'Chance auf keinen Treffer',expected:'Erwartete Anzahl',milestones:'Boxen für 50% / 90%',example:'Änderbares Beispiel, keine offiziellen Chancen. Verpackung prüfen.',assumption:'Das Standardmodell nimmt an: Ein Secret ersetzt eine Standardfigur, alle Standardfiguren sind gleich wahrscheinlich. p = (1 − 1/N) ÷ K. Das Beispiel nutzt K = 6 und N = 72. Die offizielle Quelle bestätigt Figurennamen, nicht diese Modellannahmen.',limit:'Nur unabhängige Ziehungen. Ein versiegeltes Set ohne Wiederholungen oder eine POP-NOW-Box mit Hinweisen benötigt andere Angaben. Frühere Fehlversuche erhöhen die nächste Chance nicht. Vor dem Kauf ein Budget setzen.',known:'Steht auf der Verpackung eine Chance für die genaue Figur, „Bekannte Einzelwahrscheinlichkeit eingeben“ wählen.',source:'Have-a-Seat-Figurennamen bei POP MART prüfen',reference:'Secret-Chancen und Quellen öffnen',error:'Markierte Felder prüfen. Boxenzahl und Chancen-Nenner müssen ganze Zahlen sein; Wahrscheinlichkeit zwischen 0 und 100.',method:'Modell und Grenzen',static:'Beispiel: 12 unabhängige Boxen bei 1:72 ergeben eine Chance von 15,45% auf mindestens ein Secret.',noscript:'JavaScript aktivieren, um Eingaben zu ändern und zu rechnen. Beispiel und Annahmen bleiben ohne JavaScript lesbar.'},
 zh:{title:'你想抽中哪一款？',intro:'常规款、隐藏款，先算清楚，再决定要不要开下一盒。',series:'选择系列',other:'其他系列',target:'想计算哪一种概率？',targets:['指定常规款','隐藏款','输入包装标注的单款概率'],style:'选择想要的常规款',count:'常规款总数',secret:'隐藏款概率 · 1/N 中的 N',percent:'单盒抽中该款的概率（%）',boxes:'计划独立抽取的盒数',submit:'计算我的概率',label:'至少抽中一次的概率',single:'单盒抽中概率',none:'一次也没抽中的概率',expected:'期望抽中数量',milestones:'达到 50% / 90% 所需盒数',example:'下方为可修改示例，并非官方概率，请按包装核对。',assumption:'常规款模型假设：隐藏款会替换常规款，所有常规款等概率，p = (1 − 1/N) ÷ K。示例取 K = 6、N = 72。官方来源用于核对款式名称，不代表上述模型假设已经得到官方确认。',limit:'只适用于概率不变的独立抽盒。整箱不重复配货、POP NOW 提示或剩余盒排除，需要另外的信息。之前没抽中不会提高下一盒概率，购买前先设预算。',known:'若包装直接标注某一款的概率，请选“输入包装标注的单款概率”。',source:'在 POP MART 核对 Have a Seat 款式',reference:'查看隐藏款概率参考与来源',error:'请检查标记的输入项。盒数和概率分母必须为整数，百分比需在 0 到 100 之间。',method:'计算假设与适用范围',static:'示例：单盒隐藏款概率为 1:72 时，独立抽 12 盒，至少抽中一次的概率约为 15.45%。',noscript:'启用 JavaScript 后即可修改输入并计算；不启用时仍可阅读示例和计算假设。'}
};
export const styleProfiles={
 labubu:{name:'LABUBU',preset:'have-a-seat',series:'Have a Seat',names:styleNames,secretName:'Duoduo',source:styleSource},
 skullpanda:{name:'SKULLPANDA',preset:'image-of-reality',series:'Image Of Reality',names:['The Timelapse','The Paradox','The Pivot','The Merchant','The Soar','The Constraint','The Duality (White)','The Duality (Black)','The Philosophy','The Imagination','The Disguise','The Antigravity'],secretName:'The Onlooker',source:'https://www.popmart.com/us/products/953'},
 'sonny-angel':{name:'SONNY ANGEL',preset:'fruit-series',series:'Fruit Series',names:['Raspberry','Peach','Orange','Pear','Strawberry','Grape','Watermelon','Melon','Durian','DragonFruit','Pineapple','Apple'],secretName:null,source:'https://www.sonnyangel.com/en/products/'}
};
const generic={
 en:{assumption:'Regular-style mode assumes one secret replaces a regular style and all K regular styles have equal probability: p = (1 − 1/N) ÷ K. Enter K and the printed secret denominator N. This assumption is not a verified brand rate. For several secret variants, use the exact per-style percentage instead of a combined secret rate. Use the exact per-style percentage when available.',source:'Check the official series information',static:'Worked example, not brand odds: a 5% per-box chance gives 26.49% across 6 independent boxes.',pending:'Enter the odds from your exact series to see your result.',tryExample:'Try a 5% example',other:'Other series',intro:'Choose your target and enter the odds for the exact series. No brand probability is prefilled.'},
 de:{assumption:'Das Standardmodell nimmt an: Ein Secret ersetzt eine Standardfigur und alle K Standardfiguren sind gleich wahrscheinlich: p = (1 − 1/N) ÷ K. K und den angegebenen Secret-Nenner N eingeben. Das ist keine bestätigte Markenwahrscheinlichkeit. Bei mehreren Secret-Varianten die genaue Einzelwahrscheinlichkeit statt einer gemeinsamen Secret-Chance verwenden. Wenn vorhanden, die genaue Einzelwahrscheinlichkeit verwenden.',source:'Offizielle Serienangaben prüfen',static:'Rechenbeispiel, keine Markenchance: 5% pro Box ergeben bei 6 unabhängigen Boxen 26,49%.',pending:'Die Chancen Ihrer konkreten Serie eingeben, um das Ergebnis zu sehen.',tryExample:'5%-Beispiel ausprobieren',other:'Andere Serie',intro:'Ziel auswählen und die Chancen der genauen Serie eingeben. Keine Markenwahrscheinlichkeit ist vorausgefüllt.'},
 zh:{assumption:'常规款模式假设：一个隐藏款替换一个常规款，K 个常规款等概率，p = (1 − 1/N) ÷ K。请填写 K 与包装上的隐藏款分母 N。这个模型不代表官方确认的品牌概率；多个隐藏款不能将合计概率当作某一个隐藏款的概率；有单款百分比时请直接输入。',source:'核对官方系列信息',static:'演算示例，非品牌概率：单盒概率为 5% 时，独立抽 6 盒至少抽中一次的概率为 26.49%。',pending:'填写对应系列的真实概率后，这里会显示你的结果。',tryExample:'试算一个 5% 的例子',other:'其他系列',intro:'先选目标，再填这一系列的概率。本站不预填未经核实的品牌概率。'}
};
export const getStyleCopy=(lang,brand='labubu')=>brand==='labubu'?styleCopy[lang]:{...styleCopy[lang],...generic[lang]};
export function styleOddsHTML(lang,brand='labubu'){
 const c=getStyleCopy(lang,brand),p=styleProfiles[brand],lab=brand==='labubu',preset=!!p.preset,target='regular';
 return `<section class="style-odds" id="style-probability" data-style-tool data-brand="${brand}"><div class="section-heading"><div><p class="eyebrow">${p.name} / ${lang==='zh'?'概率工具':lang==='de'?'CHANCEN':'STYLE ODDS'}</p><h2>${c.title}</h2><p>${c.intro}</p></div></div><p class="odds-example">${c.example}</p><div class="odds-layout"><form data-style-form><div class="odds-fields"><label>${c.series}<select name="series">${preset?`<option value="${p.preset}">${p.series}</option>`:''}<option value="custom">${c.other}</option></select></label><label>${c.target}<select name="target">${['regular','secret','printed'].map((v,i)=>`<option value="${v}"${v===target?' selected':''}>${c.targets[i]}</option>`).join('')}</select></label><label data-field="style"${preset?'':' hidden'}>${c.style}<select name="style"${preset?'':' disabled'}>${(p.names||[]).map(n=>`<option>${n}</option>`).join('')}</select></label><label data-field="regularStyles" hidden>${c.count}<input name="regularStyles" type="number" min="1" max="1000" step="1" value="${lab?6:''}" required disabled></label><label data-field="secretOddsN"${target==='printed'?' hidden':''}>${c.secret}<input name="secretOddsN" type="number" min="2" max="100000" step="1" value="${lab?72:''}" required${target==='printed'?' disabled':''}></label><label data-field="probabilityPercent"${target!=='printed'?' hidden':''}>${c.percent}<input name="probabilityPercent" type="number" min="0" max="100" step="any" value="${lab?16.6667:''}" required${target!=='printed'?' disabled':''}></label><label>${c.boxes}<input name="boxes" type="number" min="1" max="100000" step="1" value="${lab?12:6}" required></label></div><div class="actions"><button class="button primary" type="submit">${c.submit}</button>${lab?'':`<button class="button" type="button" data-style-example hidden>${c.tryExample}</button>`}</div><p data-style-error role="alert" data-message="${c.error}"></p></form><div class="odds-result" data-style-result aria-live="polite" aria-atomic="true"><p>${c.static}</p><noscript><p>${c.noscript}</p></noscript></div></div><details class="odds-method" open><summary>${c.method}</summary><p>${c.assumption}</p><p>${c.known}</p><p>${c.limit}</p>${lab?'':`<p>${c.static}</p>`}<a href="${p.source}" rel="noopener">${c.source}</a>${lab?` · <a href="${lang==='de'?'/de':''}/rarity#calc">${c.reference}</a>`:''}</details><script type="application/json" data-style-labels>${JSON.stringify({label:c.label,single:c.single,none:c.none,expected:c.expected,milestones:c.milestones,targets:c.targets,preset:p.preset||null,regularStyles:p.names?.length||null,secretName:p.secretName||null,pending:c.pending||c.error}).replace(/</g,'\\u003c')}</script></section>`;
}
export function styleParagraphs(lang,brand='labubu'){const c=getStyleCopy(lang,brand),p=styleProfiles[brand];return [c.title,c.intro,...(p.names?[p.series+': '+p.names.join(', ')]:[]),c.static,c.assumption,c.known,c.limit,c.source+': '+styleProfiles[brand].source];}
