// IDs, authors and embed availability verified through YouTube oEmbed 2026-10-02.
// Editorial picks, not a live popularity ranking or sponsored endorsements.
export const videos=[
 {id:'xtvGm3qH1sc',brand:'labubu',label:'LABUBU',title:'POP MART Labubu Have A Seat Blind Box FULL SET Unboxing',author:"Lorien’s Toy Box",authorUrl:'https://www.youtube.com/@LoriensToyBox',en:['Meet the Have a Seat lineup','See the named styles in an unboxing, then calculate your own single-box chances. The video’s case result is not a probability estimate.','Calculate a style’s odds'],de:['Die Have-a-Seat-Serie kennenlernen','Figuren im Unboxing ansehen, danach eigene Einzelbox-Chancen berechnen. Das Ergebnis eines Sets ist keine Wahrscheinlichkeitsmessung.','Chancen einer Figur berechnen'],zh:['先看 Have a Seat 有哪些款','看看开箱中的各个款式，再计算自己的独立抽盒概率。视频里一整箱的结果不代表单盒概率。','计算想要款式的概率']},
 {id:'yS-JAOeq2i8',brand:'skullpanda',label:'SKULLPANDA',title:'Pop Mart: Skullpanda "Image of Reality" Series FULL CASE UNBOXING! ~Mysterious & Beautiful Figures~',author:'Toy Chat',authorUrl:'https://www.youtube.com/@ToyChat',en:['A closer look at Image of Reality','Use the series unboxing to compare designs, then read the source-linked buying guide.','Explore the series guide'],de:['Image of Reality genauer ansehen','Designs beim Unboxing vergleichen und anschließend den Ratgeber mit Quellen lesen.','Serienratgeber öffnen'],zh:['近距离看看 Image of Reality','通过系列开箱比较造型，再用有来源的购买指南核对产品。','查看系列购买指南']},
 {id:'wZF5TygoARs',brand:'jellycat',label:'JELLYCAT',title:'my 100+ jellycat collection tour!🧸🧺',author:'Vic In The Meadow',authorUrl:'https://www.youtube.com/@vicinthemeadow',en:['A shelf full of personality','Browse a creator’s collection tour for inspiration, then plan around your own space and measurements.','Plan my display space'],de:['Ein Regal voller Charakter','Inspiration beim Sammlungsrundgang finden, danach den eigenen Platz mit echten Maßen planen.','Ausstellungsplatz planen'],zh:['把收藏摆成自己喜欢的样子','从创作者的收藏展示中找灵感，再按自己的空间和实际尺寸做规划。','规划我的展示空间']}
];
export const videoCopy={
 en:{title:'Press play. Find your favourite.',intro:'Three creator videos to explore real collections. Watch, then use a tool to make your own plan.',load:'Load YouTube player',close:'Close player',watch:'Watch on YouTube',privacy:'Preview images come from YouTube. Loading a player connects to YouTube/Google; no video starts automatically. Captions and regional availability depend on the original video.',fallback:'If the embedded player is unavailable, use “Watch on YouTube”.',original:'Original video',by:'By'},
 de:{title:'Play drücken. Lieblingsstücke finden.',intro:'Drei Creator-Videos zeigen echte Sammlungen. Anschauen und danach mit einem Werkzeug selbst planen.',load:'YouTube-Player laden',close:'Player schließen',watch:'Auf YouTube ansehen',privacy:'Vorschaubilder stammen von YouTube. Beim Laden des Players wird eine Verbindung zu YouTube/Google hergestellt; kein Video startet automatisch. Untertitel und regionale Verfügbarkeit hängen vom Originalvideo ab.',fallback:'Ist der Player nicht verfügbar, „Auf YouTube ansehen“ nutzen.',original:'Originalvideo',by:'Von'},
 zh:{title:'点开看看，找到你的心头好。',intro:'三条创作者视频，看看真实收藏；看完就用工具，为自己的收藏做个计划。',load:'加载 YouTube 播放器',close:'关闭播放器',watch:'去 YouTube 观看',privacy:'预览图来自 YouTube。加载播放器会连接 YouTube/Google，视频不会自动播放。字幕与地区可用性以原视频为准。',fallback:'若站内播放器无法使用，可点“去 YouTube 观看”。',original:'原视频',by:'创作者'}
};
export function videoTarget(v,lang,route){return v.brand==='labubu'?route(lang,'brands/labubu')+'#style-probability':v.brand==='jellycat'?(lang==='de'?'/de':'')+'/display-calculator':route(lang,'brands/'+v.brand);}
export function videosHTML(lang,route,esc){const c=videoCopy[lang];return `<section class="watch-section" id="watch"><div class="section-heading"><div><p class="eyebrow">WATCH / DISCOVER / COLLECT</p><h2>${c.title}</h2><p>${c.intro}</p></div></div><p class="small video-privacy">${c.privacy}</p><div class="watch-grid">${videos.map(v=>`<article class="watch-card" data-video="${v.id}"><div class="video-stage"><div class="video-fallback" aria-hidden="true"><span>${v.label}</span><strong>${v[lang][0]}</strong></div><img src="https://i.ytimg.com/vi/${v.id}/hqdefault.jpg" width="480" height="360" loading="lazy" referrerpolicy="no-referrer" alt="${esc(v.title)}" class="video-poster"><button class="video-load" type="button" data-video-load data-title="${esc(v.title)}" aria-label="${c.load}: ${esc(v.title)}" hidden><span class="play-mark" aria-hidden="true">▶</span><span>${c.load}</span></button></div><div class="watch-copy"><p class="eyebrow">${v.label}</p><h3>${v[lang][0]}</h3><p>${v[lang][1]}</p><p class="video-byline">${c.by} <a href="${v.authorUrl}" rel="noopener">${v.author}</a></p><details class="video-original"><summary>${c.original}</summary><p lang="en">${esc(v.title)}</p></details><div class="watch-links"><a href="https://www.youtube.com/watch?v=${v.id}" target="_blank" rel="noopener noreferrer">${c.watch} ↗</a><button type="button" data-video-close hidden>${c.close}</button></div><a class="video-next" href="${videoTarget(v,lang,route)}">${v[lang][2]}${lang==='zh'&&v.brand==='jellycat'?'（英文）':''} →</a></div></article>`).join('')}</div><p class="small">${c.fallback}</p></section>`;}
export function videoParagraphs(lang,route,origin){return [videoCopy[lang].title,videoCopy[lang].intro,...videos.map(v=>`${v[lang][0]} — ${v.author}\n${v.title}\nhttps://www.youtube.com/watch?v=${v.id}\n${v[lang][1]}\n${origin+videoTarget(v,lang,route)}`),videoCopy[lang].privacy];}
export function videoSchema(lang){return {'@type':'ItemList',name:videoCopy[lang].title,itemListElement:videos.map((v,i)=>({'@type':'ListItem',position:i+1,item:{'@type':'CreativeWork',name:v.title,url:'https://www.youtube.com/watch?v='+v.id,creator:{'@type':'Person',name:v.author,url:v.authorUrl}}}))};}
