import {PRODUCT,DAY,fields,blankState,restore,makeCase,grade,progress,comparison,csv,record,sourceOf} from './core.mjs';
const $=id=>document.getElementById(id),zh=document.body.dataset.lang==='zh',t=(a,b)=>zh?b:a,slot='agi-work-mentor-v1',params=new URLSearchParams(location.search),qa=params.has('__qa'),origin=location.origin;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const random=()=>[...crypto.getRandomValues(new Uint8Array(16))].map(v=>v.toString(16).padStart(2,'0')).join('');
let state=blankState(),actor=random(),cloudContext=null,cloudHandler=null,lastResult=null,timerStart=performance.now(),activeMs=0,timing=true,busy=false;
state.seed=2+crypto.getRandomValues(new Uint32Array(1))[0]%900000;
try{const stored=localStorage.getItem(slot);if(stored)state=restore(JSON.parse(stored));const id=localStorage.getItem(slot+':actor');if(/^[a-f0-9]{32}$/.test(id||''))actor=id;else localStorage.setItem(slot+':actor',actor);}catch{$('status').textContent=t('Local storage is unavailable or the old record is invalid. Export a backup before leaving.','本机存储不可用，或旧记录无效。离开前请导出备份。');}
const attribution=sourceOf(location.href,document.referrer),labels={orders:t('Paid orders','已支付订单'),revenue:t('Net revenue','净收入'),channel:t('Leading channel','最高收入渠道'),growth:t('Weekly growth','环比增长'),claim:t('Evidence for the claim','结论的证据')};
const hints={orders:t('Filter to current week and paid status before counting. A cancelled row is not an order to include.','先筛选本周和已支付状态，再数订单；取消订单不计入。'),revenue:t('For current paid rows, add gross amounts and subtract their refunds. Leave the cancelled row out.','只看本周已支付行：金额相加，再减去这些行的退款，排除取消订单。'),channel:t('For each channel, total current paid amounts minus refunds. Compare those three totals.','分别汇总三个渠道本周的已支付金额减退款，再比较净收入。'),growth:t('Calculate previous-week net revenue first. Use (current − previous) / previous × 100 and round to one decimal.','先计算上周净收入，再用（本周 − 上周）/ 上周 × 100，保留一位小数。'),claim:t('A change between two weeks shows what happened. It does not isolate why it happened or what would have happened without ads.','两周的变化说明发生了什么，但不能排除其他原因，也没有说明不投广告会怎样。'),transfer:t('Use a new case with the same allowed tools. Submit before asking the mentor for hints.','保持相同工具条件，换一个新案例；在向导师索取提示前先提交。')};
const stageName=()=>({baseline:t('Baseline','起点测评'),practice:t('Guided practice','带练'),transfer:t('New-data check','新数据检验')}[state.stage]);
function status(message){$('status').textContent=message;}
function save(){try{localStorage.setItem(slot,JSON.stringify(record(state)));}catch{status(t('Could not save on this device. Export a backup to keep your progress.','无法保存到本机，请导出备份保留记录。'));}}
function draft(){return Object.fromEntries(fields.map(k=>[k,$(k).value]));}
function capture(){state.draft=draft();state.minutes=Number($('minutes').value);state.tools=$('tools').value;state.applied=$('applied').checked;save();}
function elapsed(){return Math.min(86400,Math.round((activeMs+(timing&&!document.hidden?performance.now()-timerStart:0))/1000));}
function restartClock(){activeMs=0;timerStart=performance.now();timing=true;}
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(timing)activeMs+=performance.now()-timerStart;}else timerStart=performance.now();});
setInterval(()=>{$('timer').textContent=t('Active time this visit: ','本次活跃计时：')+Math.floor(elapsed()/60)+':'+String(elapsed()%60).padStart(2,'0');},1000);
async function post(body){const abort=new AbortController(),timeout=setTimeout(()=>abort.abort(),65000);try{const r=await fetch('/api/mentor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:abort.signal}),j=await r.json();if(!r.ok)throw Error(j.code||'unavailable');return j;}finally{clearTimeout(timeout);}}
async function event(event){if(!$('measure').checked||qa)return;try{await post({action:'event',consent:true,actor,lang:zh?'zh':'en',event,...attribution});}catch{/* optional measurement must never block learning */}}
function renderProgress(){const p=progress(state),names=[t('Find your starting point','找到起点'),t('A complete report','完成一份周报'),t('Independent transfer','独立迁移'),t('Delayed recheck passed','通过延迟复核')];$('level').textContent='L'+p.level;$('level-label').textContent=names[p.level];document.querySelectorAll('.level-track i').forEach((v,i)=>v.classList.toggle('on',i<=p.level));$('completed').textContent=String(p.completed);$('review-time').textContent=p.dueAt?new Intl.DateTimeFormat(zh?'zh-CN':'en',{month:'short',day:'numeric'}).format(p.dueAt):'—';$('review-label').textContent=p.level===3?t('Passed with the same tool choice','已以相同工具条件通过'):p.due?t('Ready: attempt a new case','现在可以换题复核'):p.dueAt?t('Calendar reminder is optional','可自行添加日历提醒'):t('After your first independent pass','首次独立通过后安排');
const c=comparison(state);$('comparison').textContent=c?t('First baseline: ','首次测评：')+c.before+'/5 · '+t('Latest submission: ','最近提交：')+c.after+'/5 · '+(c.assisted?t('mentor-assisted','有导师辅助'):t('without mentor hints','无导师提示'))+'. '+(c.sameTools?t('Same allowed tools. Different cases may differ in difficulty; this is a practice record, not proof of a productivity gain.','允许的工具相同。不同案例难度可能不同，这只是练习记录，不能证明效率提高。'):t('Tool choices changed, so these results are not directly comparable.','工具条件不同，结果不能直接比较。')):t('Your first submission establishes a starting point. No improvement is claimed before you have a comparison.','第一次提交会留下起点记录。有对比记录后再观察变化，不预设你已经进步。');
$('history').replaceChildren();if(!state.attempts.length){const row=el('tr'),td=el('td',t('No submissions yet. Start with the five decisions above.','尚无提交。先完成上面的五个判断。'));td.colSpan=5;row.append(td);$('history').append(row);}else state.attempts.slice(-8).reverse().forEach((a,i)=>{const r=el('tr');[String(state.attempts.length-i),'#'+a.seed,a.result.passed+'/5',a.assisted?t('Used','使用过'):t('None recorded','未记录使用'),a.tools==='spreadsheet-ai'?t('Sheet + AI','表格 + AI'):t('Sheet','表格')].forEach(x=>r.append(el('td',x)));$('history').append(r);});$('applied').checked=state.applied;$('calendar').disabled=!p.dueAt;}
function coach(){const key=lastResult?.next||'orders';$('coach-heading').textContent=lastResult?.pass?t('Ready for a new case','可以换题验证了'):lastResult?t('Focus on one correction','先解决一个薄弱点'):t('Begin with the order boundary','先确定订单范围');$('coach-action').textContent=lastResult?hints[key]:t('Download the CSV or read the rows. Make your first attempt using your selected tools. Ask for help only when you need it.','下载 CSV 或直接查看数据，先用你选择的工具独立尝试；需要时再向导师求助。');}
function renderCase(){const c=makeCase(state.seed);$('case-label').textContent=stageName()+' · #'+state.seed;$('minutes').value=String(state.minutes);$('tools').value=state.tools;$('data-rows').replaceChildren();for(const r of c.rows){const tr=el('tr',undefined,r.status==='cancelled'?'cancelled':'');const values=[r.id,r.week==='current'?t('Current','本周'):t('Previous','上周'),({email:t('Email','邮件'),social:t('Social','社交'),referral:t('Referral','推荐')})[r.channel],r.status==='paid'?t('Paid','已支付'):t('Cancelled','已取消'),(r.amount/100).toFixed(2),(r.refund/100).toFixed(2)];values.forEach((v,i)=>tr.append(el('td',v,i>3?'number':'')));$('data-rows').append(tr);}fields.forEach(k=>$(k).value=state.draft[k]||'');lastResult=null;$('result').hidden=true;$('hint-text').textContent='';$('ai-reply').textContent='';$('ai-status').textContent='';coach();renderProgress();}
function showResult(r){lastResult=r;$('result').hidden=false;$('score').textContent=r.passed+' / 5';$('result-label').textContent=r.pass?t('Every check passed on this submission.','这次提交的五项检查全部通过。'):t('A concrete next step: fix the first unchecked decision.','下一步很明确：先修正第一项未通过的判断。');$('checks').replaceChildren();for(const k of fields)$('checks').append(el('li',(r.checks[k]?'✓ ':'○ ')+labels[k]+' · '+(r.checks[k]?t('Passed','通过'):t('Check again','待检查')),r.checks[k]?'pass':'fail'));$('next-action').textContent=hints[r.next];$('next-case').hidden=!r.pass;$('export-report').hidden=!r.pass;coach();}
$('report').addEventListener('submit',e=>{e.preventDefault();capture();const r=grade(state.seed,state.draft);const a={seed:state.seed,stage:state.stage,at:Date.now(),elapsed:elapsed(),assisted:state.assisted,tools:state.tools,answers:{...state.draft},result:r};state.attempts.push(a);if(state.attempts.length>40)state.attempts.shift();if(!r.pass)state.assisted=true;save();showResult(r);renderProgress();event('check');if(r.pass)event('pass');status(t('Saved on this device. Back up your records before clearing browser storage.','已保存到本机。清理浏览器数据前请备份记录。'));});
$('hint').onclick=()=>{capture();state.assisted=true;save();const r=grade(state.seed,state.draft);$('hint-text').textContent=hints[r.next]+t(' This attempt is now marked as mentor-assisted.',' 本次练习已标记为导师辅助。');};
$('next-case').onclick=()=>{capture();state.seed=state.seed>=999999?2:state.seed+1;while(state.attempts.some(a=>a.seed===state.seed))state.seed=state.seed>=999999?2:state.seed+1;state.stage='transfer';state.assisted=false;state.draft=Object.fromEntries(fields.map(k=>[k,'']));save();restartClock();renderCase();$('practice').scrollIntoView({behavior:'smooth'});status(t('New data loaded. Use the same allowed tools and submit before asking for hints.','已换新数据。请保持工具条件一致，先提交，再查看提示。'));event('start');};
function edited(){state.draft=draft();save();if(lastResult){lastResult=null;$('result').hidden=true;coach();status(t('Answers changed. Check this version before using or exporting the result.','答案已更改，请重新检查当前版本，再使用或导出结果。'));}}
for(const id of [...fields,'minutes','tools','applied'])$(id).addEventListener('change',capture);
for(const id of fields){$(id).addEventListener('input',edited);$(id).addEventListener('change',edited);}
$('hero-start').onclick=()=>event('start');
function download(name,value,type='application/json'){const url=URL.createObjectURL(new Blob([value],{type})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),15000);}
$('download-csv').onclick=()=>{download('work-mentor-'+state.seed+'.csv',csv(state.seed),'text/csv;charset=utf-8');event('start');};
$('export').onclick=()=>{capture();download('work-mentor-backup.json',JSON.stringify(record(state),null,2));status(t('Backup downloaded. Import it on another device or open cloud membership below.','已下载备份。可在另一台设备导入，或使用下方云端会员。'));event('export');};
$('export-report').onclick=()=>{capture();const r=grade(state.seed,state.draft);if(!r.pass){status(t('Recheck your edited answers before exporting a passed report.','答案已更改，请重新检查后再导出通过的周报。'));return;}const a=state.draft,lines=[t('Ecommerce weekly report — fictional practice','电商周报——虚构练习'),'Case #'+state.seed,...fields.map(k=>labels[k]+': '+(k==='claim'?t('The comparison alone cannot establish causation.','仅凭对比无法证明因果关系。'):a[k]+(k==='growth'?'%':''))),t('Practice policy: paid orders less their refunds, grouped by order week; cancelled orders excluded. Discounts, tax, shipping, fees and cross-period refunds are not modeled.','练习口径：按订单所属周汇总已支付金额并扣除退款，排除取消订单；未建模优惠、税费、运费、手续费和跨期退款。'),t('Five deterministic checks passed; not a verified workplace assessment.','五项规则检查通过，不代表经验证的职业能力测评。'),origin+(zh?'/zh':'')+'/mentor'];download('work-mentor-report-'+state.seed+'.txt',lines.join('\n'),'text/plain;charset=utf-8');event('export');};
$('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>65536)throw Error();const imported=restore(JSON.parse(await f.text()));if(state.attempts.length&&!confirm(t('Replace the practice records on this device with this backup?','用这份备份替换本机练习记录？')))return;state=imported;cloudContext=null;save();restartClock();renderCase();status(t('Backup imported; all scores were recalculated from its answers.','已导入备份，并根据答案重新计算全部检查结果。'));}catch{status(t('This backup is invalid or larger than 64 KB. Existing records were kept.','备份格式无效或超过 64 KB，原有记录已保留。'));}finally{e.target.value='';}};
$('clear').onclick=()=>{if(!confirm(t('Clear practice records on this device? Export a backup first if you need them.','清除本机练习记录？需要保留时请先导出备份。')))return;state=blankState();state.seed=2+crypto.getRandomValues(new Uint32Array(1))[0]%900000;cloudContext=null;save();restartClock();renderCase();status(t('Local practice records cleared. Existing cloud backups were not deleted.','已清除本机练习记录，已有云端备份未删除。'));};
$('calendar').onclick=()=>{const p=progress(state);if(!p.dueAt)return;const date=new Date(Math.max(p.dueAt,Date.now())).toISOString().slice(0,10).replaceAll('-',''),end=new Date(Math.max(p.dueAt,Date.now())+DAY).toISOString().slice(0,10).replaceAll('-','');download('work-mentor-recheck.ics',['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//AGI Scorecard//Work Mentor//EN','BEGIN:VEVENT','UID:'+random()+'@agiscorecard.com','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),'DTSTART;VALUE=DATE:'+date,'DTEND;VALUE=DATE:'+end,'SUMMARY:'+t('Ecommerce reporting: try a fresh case','电商周报导师：换一组数据复核'),'DESCRIPTION:'+origin+(zh?'/zh':'')+'/mentor','END:VEVENT','END:VCALENDAR'].join('\r\n'),'text/calendar;charset=utf-8');status(t('Calendar file downloaded. Import it to choose your reminder; this site will not send a message.','日历文件已下载，导入后可设置提醒；本站不会主动发送消息。'));};
$('ask').onclick=async()=>{if(busy)return;if(!$('ai-consent').checked){$('ai-status').textContent=t('Choose whether to send the question by checking the consent box.','请先勾选授权，确认发送问题。');return;}const question=$('question').value.trim();if(question.length<3){$('ai-status').textContent=t('Add a specific question of at least three characters.','请填写至少三个字符的具体问题。');return;}capture();state.assisted=true;save();busy=true;$('ask').disabled=true;$('ai-reply').textContent='';$('ai-status').textContent=t('Preparing one next step…','正在准备下一步建议…');const seed=state.seed;
try{const j=await post({action:'coach',consent:true,lang:zh?'zh':'en',seed,answers:state.draft,question});if(state.seed!==seed)return;$('ai-reply').textContent=j.reply;$('ai-status').textContent=t('AI explanation — verify it against the rows. This attempt is marked as assisted.','AI 解释——请对照数据核实。本次练习已标记为导师辅助。');}catch(e){const errors={rate_limited:t('The shared preview quota is used up. Retry after the 24-hour window resets. Free checks and targeted hints still work.','共享预览额度已用完，请在 24 小时计数窗口重置后重试。免费规则检查和针对性提示仍可使用。'),ai_failed:t('The model did not return a usable response. This attempt used quota. Try the targeted hint for now.','模型未返回可用回复，本次尝试已计入额度。你可以先使用针对性提示。')};$('ai-status').textContent=errors[e.message]||t('AI is temporarily unavailable. Use the targeted hint and local checks; your records are retained.','AI 暂时不可用。可继续使用针对性提示与本机检查，记录会保留。');}finally{busy=false;$('ask').disabled=false;}};
$('save-cloud').onclick=()=>{capture();const data=record(state),snapshot=JSON.stringify(data),handoff=random();if(cloudHandler)window.removeEventListener('message',cloudHandler);const target=new URL((zh?'/zh':'')+'/members',origin);target.searchParams.set('tool',PRODUCT);target.searchParams.set('from',origin);if(qa)target.searchParams.set('__qa','1');const win=window.open(target.href,'_blank');event('checkout_intent');if(!win){status(t('Allow the member page to open, or export a backup and import it there.','请允许打开会员页，或导出备份后在会员页导入。'));return;}let delivered=false;cloudHandler=e=>{if(e.origin!==origin||e.source!==win)return;if(e.data?.kind==='workbench-member-ready'&&!delivered){win.postMessage({kind:'workbench-save',data,handoff,context:cloudContext},origin);delivered=true;status(t('Draft opened in the member page. Choose Save there to upload it.','草稿已在会员页打开，在那里点击保存后才会上传。'));}if(e.data?.kind==='workbench-saved'&&e.data.handoff===handoff&&e.data.product===PRODUCT){cloudContext=e.data.context;status(e.data.same&&JSON.stringify(record(state))===snapshot?t('This version was saved to the cloud.','此版本已保存到云端。'):t('A cloud version was saved. This tab may contain newer changes.','已保存一个云端版本，当前标签页可能还有更新。'));event('cloud_saved');}};window.addEventListener('message',cloudHandler);const handler=cloudHandler;setTimeout(()=>window.removeEventListener('message',handler),120000);};
$('measure').onchange=()=>{if($('measure').checked)event('visit');};
$('send-feedback').onclick=async()=>{$('send-feedback').disabled=true;try{await post({action:'feedback',consent:true,actor,lang:zh?'zh':'en',reason:$('feedback').value,qa});$('feedback-status').textContent=t('Your choice was received. Thank you.','已收到你的反馈，谢谢。');}catch{$('feedback-status').textContent=t('Feedback could not be sent. Please retry later.','反馈未能发送，请稍后重试。');}finally{$('send-feedback').disabled=false;}};
if(params.get('embed')==='1')document.documentElement.classList.add('embed');renderCase();
if(window.opener&&params.get('restore')==='1'){const handler=e=>{if(e.origin!==origin||e.source!==window.opener||e.data?.kind!=='workbench-restore')return;try{state=restore(e.data.data);cloudContext=e.data.context||null;save();restartClock();renderCase();status(t('Cloud record restored and scores recalculated.','云端记录已恢复，检查结果已重新计算。'));}catch{status(t('Invalid cloud record. Your local records were retained.','云端记录无效，本机记录已保留。'));}window.removeEventListener('message',handler);};window.addEventListener('message',handler);window.opener.postMessage({kind:'workbench-ready'},origin);setTimeout(()=>window.removeEventListener('message',handler),120000);}
