// Copy the existing source untouched; the only wrapper is a local isolation notice.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {pathToFileURL} from 'node:url';
const [repo, dest, fixture='none']=process.argv.slice(2);if(!repo||!dest)throw Error('repo and dest required');
const src=path.join(repo,'sites/baipiaoji/assets/studio');fs.mkdirSync(path.join(dest,'source/vendor'),{recursive:true});
const lock=JSON.parse(fs.readFileSync(new URL('./source-lock.json',import.meta.url)));const source=[];for(const name of ['deck-core.mjs','deck-view.mjs','deck-app.mjs','deck-export.mjs','deck.css','vendor/pptxgenjs-4.0.1.js','vendor/pptxgenjs-LICENSE.txt']){const b=fs.readFileSync(path.join(src,name));const blob=crypto.createHash('sha1').update(Buffer.from('blob '+b.length+'\0')).update(b).digest('hex');if(lock.files.find(x=>x.path==='sites/baipiaoji/assets/studio/'+name)?.git_blob_sha!==blob)throw Error('SOURCE_LOCK_MISMATCH:'+name);fs.writeFileSync(path.join(dest,'source',name),b);source.push({path:'sites/baipiaoji/assets/studio/'+name,sha256:crypto.createHash('sha256').update(b).digest('hex')});}
const {deckWorkspace}=await import(pathToFileURL(path.join(dest,'source/deck-view.mjs')));let workspace=deckWorkspace('en','/en');
if(fixture==='missing-export'){workspace=workspace.replace('id="dk-export"','id="dk-export-disabled-local-fixture"');if(workspace.includes('id="dk-export"'))throw Error('fixture failed');}
else if(fixture!=='none')throw Error('unsupported fixture');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self'; object-src 'none'; frame-src 'none'"><title>ProposalDeck | local demo</title><link rel="stylesheet" href="/source/deck.css"><style>body{margin:0;background:#fff;font-family:Arial,sans-serif;color:#172e4c}.local-disclosure{background:#102b4b;color:white;font-size:12px;padding:10px 20px;letter-spacing:.03em}</style></head><body><div class="local-disclosure">LOCAL DEMO · Fictional input · ${fixture==='none'?'No account or cloud upload':'TEST FIXTURE: EXPORT SELECTOR DISABLED'}</div><main class="deck-main">${workspace}</main><script type="module" src="/source/deck-app.mjs"></script></body></html>`;
fs.writeFileSync(path.join(dest,'index.html'),html);fs.writeFileSync(path.join(dest,'source.json'),JSON.stringify({fixture,source_commit:lock.source_commit,source,html_sha256:crypto.createHash('sha256').update(html).digest('hex')},null,2));
