// Source review dates are editorial records, not automatic freshness stamps.
export const reviewed = '2026-10-03';
import {recentInterviews,recentClaims} from './recent.mjs';
export const goals = [
  {id:'understand',en:['Understand the change','What is happening, and what is still a prediction?','Compare one claim with its original source. Write down what would change your mind.','Inspect the evidence','/progress-index'],zh:['看懂趋势','哪些已经发生，哪些还只是预测？','核对一条观点的原始出处，写下什么新证据会让你改变判断。','查看证据台账','/zh/progress-index']},
  {id:'work',en:['Adapt my work','Which parts of my work could change first?','Choose one repetitive task. Compare a manual attempt and an AI-assisted attempt, including review time and errors.','Explore work evidence','/ai-and-your-job'],zh:['应对工作变化','我的哪些工作环节可能先改变？','选一项重复任务，对比人工与 AI 辅助两次完成的结果，计入检查时间和错误。','查看工作变化证据','/zh/ai-and-your-job']},
  {id:'learn',en:['Choose what to learn','Which skill can I put into practice?','Choose a small task you can finish this week. Explain the result without AI before adding another course.','Browse practical tools','/ai-tools'],zh:['找到学习方向','学什么，才能真正用得上？','选一个本周能完成的小任务，尝试在不用 AI 的情况下解释结果，再决定是否继续学。','寻找练习工具','/zh/ai-tools']},
  {id:'earn',en:['Explore income ideas','What useful result could someone pay for?','Define one deliverable and a possible buyer. Check whether they already solve the problem before building.','Plan a useful delivery','/earn'],zh:['探索收入机会','我能做出什么值得付费的成果？','写清一个可交付的成果和可能的买家，先了解他们现在如何解决问题，再决定做不做。','制定交付方案','/zh/earn']},
  {id:'family',en:['Think about education','How can we use AI without skipping learning?','Discuss one explanation together. Ask the learner to show their reasoning and check one source independently.','Read the learning perspective','/future-guide/learning-with-ai'],zh:['思考家庭教育','怎样用 AI，又不跳过真正的学习？','一起讨论一个解释，让学习者说出推理过程，并独立核对一个来源。','查看学习观点','/zh/future-guide/learning-with-ai']},
  {id:'forecast',en:['Test my judgment','What do I believe, and what would change it?','Record your view, one counterargument and a review date. Revisit the evidence before changing your position.','Join the AGI timeline poll','/#vote'],zh:['检验我的判断','我相信什么，又会因什么改变？','记录你的立场、一条反对理由和复查日期，下一次用新证据检验自己的判断。','参与 AGI 时间投票','/cn#vote']}
];
export const interviews = {
  jev:{speaker:'Diogo Almeida',publisher:'Latent Space',date:'2026-09-21',source:'https://www.latent.space/p/jev',video:'cFx9Z3ZXca0',en:'TypeSafe founder · discussing his own product',zh:'TypeSafe 创始人 · 涉及自家产品'},
  karpathy:{speaker:'Andrej Karpathy',publisher:'Dwarkesh Podcast',date:'2025-10-17',source:'https://www.dwarkesh.com/p/andrej-karpathy',video:'lXUZvyajciY',en:'AI researcher · discussing agents and education',zh:'AI 研究者 · 讨论智能体与教育'},
  dario:{speaker:'Dario Amodei',publisher:'Dwarkesh Podcast',date:'2026-02-13',source:'https://www.dwarkesh.com/p/dario-amodei-2',video:'n1E9IZfvGMA',en:'Anthropic co-founder · an industry participant',zh:'Anthropic 联合创始人 · 行业参与者'}
};
export const claims = [
  {id:'software-judgment',interview:'jev',start:4708,stamp:'01:18:28',goals:['understand','work','earn'],related:'agents-take-time',en:{title:'What if AI improves the software you already use?',short:'AI inside everyday work',summary:'Almeida argues that AI can strengthen existing software by becoming a small, programmable part of it.',question:'Which decision inside my workflow needs better judgment?',limit:'A product thesis does not establish adoption, reliability or an advantage for every software business.',test:'Measure end-to-end success, review time and cost on a real task. A fast model response alone is not enough.',scenario:'If reliable small decisions become cheap, familiar tools may absorb more work. If errors remain costly, review and exception handling stay important.'},zh:{title:'AI 会让你正在用的软件变得更有用吗？',short:'藏在日常工作里的 AI',summary:'Almeida 认为，AI 可以成为软件中可编程的小部件，增强已有软件的能力。',question:'我的工作流程中，哪一步最需要判断力？',limit:'产品方向并不能证明已经普及、足够可靠，或对每一家软件公司都有利。',test:'在真实任务上比较完整流程的成功率、复核时间和成本；不能只看模型回答得多快。',scenario:'如果小型判断变得便宜且可靠，熟悉的软件可能承接更多工作；如果错误代价仍高，复核和异常处理依然重要。'}},
  {id:'agents-take-time',interview:'karpathy',start:0,stamp:'00:00:00',goals:['understand','work','learn','forecast'],related:'fast-ai-progress',en:{title:'Why might dependable AI coworkers take longer?',short:'Capability is not reliability',summary:'Karpathy describes agents as a decade-long engineering effort, pointing to gaps including continual learning.',question:'What would make me trust an agent with this task?',limit:'This is a view recorded in October 2025, not a current capability test or a resolved AGI deadline.',test:'Try an unfamiliar task with explicit acceptance criteria. Record where a person still needs to intervene.',scenario:'If reliability improves slowly, supervised workflows remain useful. If agents handle unfamiliar tasks well, your test should reveal that change.'},zh:{title:'可靠的 AI 同事，为什么可能还需要时间？',short:'能力与可靠性之间',summary:'Karpathy 将智能体描述为一项可能持续十年的工程，提到持续学习等尚待解决的问题。',question:'满足什么条件，我才会把这项任务交给智能体？',limit:'这是 2025 年 10 月的观点，不是当前能力测评，也不是已经裁决的 AGI 时间表。',test:'用一项陌生任务和明确验收标准做测试，记录人仍需介入的地方。',scenario:'如果可靠性提升较慢，人机协作仍有用；如果智能体已能完成陌生任务，你的测试应该能观察到变化。'}},
  {id:'fast-ai-progress',interview:'dario',start:756,stamp:'00:12:36',goals:['understand','work','earn','forecast'],related:'agents-take-time',en:{title:'How should we prepare if powerful AI arrives sooner?',short:'A faster path is a scenario',summary:'Amodei expects very powerful AI within a few years and discusses how capability may spread through the economy.',question:'Which small step is useful under both fast and slow progress?',limit:'A lab leader’s expectation is not independent confirmation. Technical capability and widespread adoption are different questions.',test:'Track task performance and deployment evidence separately. Define what would weaken the faster-progress scenario.',scenario:'Under faster progress, transferable skills and short experiments may help adaptation. Under slower progress, choose work that remains useful today.'},zh:{title:'如果强大 AI 更早到来，我该做什么准备？',short:'把快速发展当成一种情景',summary:'Amodei 预期未来几年会出现非常强大的 AI，并讨论能力如何扩散到经济活动中。',question:'无论进展快慢，哪一步小行动都有价值？',limit:'实验室负责人的预期不是独立验证；技术能力与大规模采用是两个不同的问题。',test:'分别追踪任务表现与实际部署证据，预先写下什么会削弱“更快发展”的情景。',scenario:'进展快时，可迁移技能和短周期实验可能有助于适应；进展慢时，所做的工作也应在当下有用。'}},
  {id:'learning-with-ai',interview:'karpathy',start:6980,stamp:'01:56:20',goals:['learn','family'],related:'agents-take-time',en:{title:'Does getting an answer mean I have learned?',short:'Learning beyond the answer',summary:'Karpathy contrasts answering questions with a tutor who understands a learner and chooses an appropriate challenge.',question:'Can I explain and apply the idea without the assistant?',limit:'An educational vision is not evidence of learning gains for a particular child, course or AI tool.',test:'Use a new example after practice. Check the explanation and independent attempt, not just the polished final answer.',scenario:'If AI adapts well, it may make useful practice easier to find. If it supplies answers too early, independent understanding needs a separate check.'},zh:{title:'AI 给出了答案，是否意味着我已经学会？',short:'从得到答案，到真正理解',summary:'Karpathy 区分了回答问题与理解学习者、提供合适挑战的辅导体验。',question:'离开助手，我还能解释和运用这个知识吗？',limit:'教育愿景不能证明某个孩子、课程或 AI 工具已经取得学习效果。',test:'练习后换一个新例子，检查独立解释与尝试的过程，而不只看漂亮的最终答案。',scenario:'如果 AI 能恰当适配学习者，寻找有效练习可能更容易；如果太早给出答案，仍需单独检查是否真正理解。'}}
];
Object.assign(interviews,recentInterviews);
claims.push(...recentClaims);
for(const [id,i] of Object.entries(interviews)){
  i.kind ||= 'video';
  i.label ||= ({jev:'Jev',karpathy:'Karpathy',dario:'Dario'})[id] || i.speaker;
  i.title ||= {en:({jev:'Programmable judgment in everyday software',karpathy:'Agents, learning and the path to AGI',dario:'Powerful AI and economic change'})[id],zh:({jev:'日常软件中的可编程判断',karpathy:'智能体、学习与 AGI 之路',dario:'强大 AI 与经济变化'})[id]};
}
