import {claims,interviews,goals} from './catalog.mjs';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=u=>{try{const v=new URL(u);return v.protocol==='https:'&&!v.username&&!v.password?escape(v.href):'#';}catch{return '#';}};
const text=(lang,en,zh)=>lang==='zh'?zh:en;
export function discoveryStatus(data,lang,now=Date.now()){
 const ok=data.sources.filter(s=>s.status==='ok').length,stale=!data.checkedAt||now-Date.parse(data.checkedAt)>36*3600000;
 const state=stale?text(lang,'Update overdue','更新已延迟'):ok===data.sources.length?text(lang,'Sources checked','来源检查完成'):text(lang,'Some sources unavailable','部分来源暂不可用');
 return `${state} · ${ok}/${data.sources.length} · ${text(lang,'Last check: ','最近检查：')}${data.checkedAt?.replace('T',' ').replace('Z',' UTC')||'—'}`;
}
export function selectedItems(data,{category='all',language='all',goal='all',query=''}={}){
 const sources=new Map(data.sources.map(s=>[s.id,s]));
 return data.items.filter(x=>{const s=sources.get(x.sourceId);return s&&(category==='all'||s.category===category)&&(language==='all'||s.language===language)&&(goal==='all'||x.goals.includes(goal))&&(x.title+' '+s.name).toLowerCase().includes(query.trim().toLowerCase());});
}
export function discoveryCards(data,lang,options={},limit=6){
 const sources=new Map(data.sources.map(s=>[s.id,s]));
 return selectedItems(data,options).slice(0,limit).map(item=>{
  const source=sources.get(item.sourceId),parent=Object.entries(interviews).find(([,i])=>i.source===item.url),views=parent?claims.filter(c=>c.interview===parent[0]):[];
  const media={video:['Video','视频'],audio:['Audio / podcast','音频 / 播客'],text:['Article','文章']}[item.medium]||['Source','来源'];
  const title=parent?parent[1].title[lang]:item.title;
  return `<article class="discovery-card" data-discovery-card="${escape(item.id)}"><p class="meta">${escape(source.name)} · ${text(lang,...media)}</p><h3><a href="${safe(item.url)}" target="_blank" rel="noopener" data-track="source">${escape(title)} ↗</a></h3><p class="meta">${text(lang,'Published ','发布于 ')}<time datetime="${escape(item.publishedAt)}">${escape(item.publishedAt.slice(0,10))}</time> · ${text(lang,source.language==='zh'?'Chinese':'English',source.language==='zh'?'中文':'英文')}</p><div class="topic-tags">${item.goals.slice(0,3).map(id=>`<span>${escape(goals.find(g=>g.id===id)?.[lang][0]||id)}</span>`).join('')}</div><p class="discovery-state">${views.length?`<a href="${lang==='zh'?'/zh':''}/future-guide/${views[0].id}">${text(lang,views.length+' reviewed views',views.length+' 条已核对观点')} →</a>`:text(lang,'Newly discovered · interpretation pending','自动发现 · 观点待核对')}</p></article>`;
 }).join('');
}
export function sourceHealth(data,lang){return data.sources.map(s=>`<li><a href="${safe(s.home)}" target="_blank" rel="noopener">${escape(s.name)}</a><span>${s.status==='ok'?text(lang,'Checked','已检查'):text(lang,'Unavailable; last good content retained','暂不可用，保留上次内容')} · ${text(lang,'Last success: ','最近成功：')}${escape(s.lastSuccessAt?.slice(0,16).replace('T',' ')||'—')} UTC</span></li>`).join('');}
export function discoverySection(data,lang){const t=(a,b)=>text(lang,a,b);return `<section id="fresh" class="fresh-section"><div class="section-head"><div><p class="kicker">${t('A reason to come back','每天回来，都能继续发现')}</p><h2>${t('New voices. New episodes.','最新视频、播客与访谈')}</h2><p>${t('Follow interviews and creator commentary from '+data.sources.length+' sources. Checked daily; original titles and dates are retained.',`持续关注 ${data.sources.length} 个访谈与科技创作者来源，每日检查更新，保留原始标题与发布日期。`)}</p></div><a class="quiet-link" href="#perspectives">${t('Reviewed views','看已核对观点')} ↓</a></div><p id="feed-status" class="meta">${escape(discoveryStatus(data,lang))}</p><div class="feed-filters"><label>${t('Format','内容类型')}<select id="feed-category"><option value="all">${t('All creators','全部来源')}</option><option value="interview">${t('Interviews & podcasts','访谈与播客')}</option><option value="commentary">${t('Creator videos & commentary','博主视频与解说')}</option></select></label><label>${t('Language','内容语言')}<select id="feed-language"><option value="all">${t('All languages','全部语言')}</option><option value="zh">${t('Chinese','中文')}</option><option value="en">English</option></select></label><label>${t('My question','我的需求')}<select id="feed-goal"><option value="all">${t('All topics','全部方向')}</option>${goals.map(g=>`<option value="${g.id}">${escape(g[lang][0])}</option>`).join('')}</select></label><label class="search">${t('Find a creator or topic','搜索创作者或主题')}<input id="feed-search" type="search" placeholder="Lex, Fireship, AI, 硅谷…"></label></div><p id="feed-count" class="meta">${data.items.length} ${t('items in the current feed','条动态内容')}</p><div id="fresh-feed" class="discovery-grid">${discoveryCards(data,lang)}</div><p id="feed-empty" hidden>${t('No match. Try another source, language or topic.','没有匹配内容，请换一个来源、语言或方向。')}</p><button id="feed-more" ${data.items.length<=6?'hidden':''}>${t('Show more','查看更多')}</button><p class="meta">${t('Automatic discovery and topic tags are based on publisher feeds; they are not fact checks or AI-generated forecasts. Updates depend on source availability and the scheduled run.','自动发现与方向标签依据出版方公开订阅源，不等于事实核查或 AI 预测。更新取决于来源可用性与定时任务执行。')}</p><details class="source-health"><summary>${t('Monitored sources & update status','监控来源与更新状态')}</summary><ul id="source-health">${sourceHealth(data,lang)}</ul></details><script type="application/json" id="discovery-data">${JSON.stringify(data).replace(/</g,'\\u003c')}</script></section>`;}
export function initDiscovery(){
 const node=document.getElementById('discovery-data');if(!node)return;
 const lang=document.body.dataset.lang,$=id=>document.getElementById(id);let data=JSON.parse(node.textContent),limit=6,lastFetch=Date.now();
 const options=()=>({category:$('feed-category').value,language:$('feed-language').value,goal:$('feed-goal').value,query:$('feed-search').value});
 function render(){const selected=selectedItems(data,options());$('fresh-feed').innerHTML=discoveryCards(data,lang,options(),limit);$('feed-count').textContent=selected.length+text(lang,' matching items · newest first',' 条匹配内容 · 按原始发布时间排序');$('feed-empty').hidden=!!selected.length;$('feed-more').hidden=selected.length<=limit;$('feed-status').textContent=discoveryStatus(data,lang);$('source-health').innerHTML=sourceHealth(data,lang);}
 for(const id of ['feed-category','feed-language','feed-goal','feed-search'])$(id).addEventListener(id==='feed-search'?'input':'change',()=>{limit=6;render();});
 $('feed-more').onclick=()=>{limit+=6;render();};
 async function refresh(){if(document.hidden||Date.now()-lastFetch<300000)return;lastFetch=Date.now();try{const r=await fetch('/foresight-assets/discovery.json',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('network');const next=await r.json();if(next.version!==1||!Array.isArray(next.items)||!Array.isArray(next.sources))throw Error('schema');data=next;render();}catch{$('feed-status').textContent=discoveryStatus(data,lang)+' · '+text(lang,'Could not reload; showing the last snapshot','刷新未完成，展示上次快照');}}
 document.addEventListener('visibilitychange',refresh);setInterval(refresh,300000);render();
}
