import {contentItems,topics} from './discovery.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function siteHeader(lang,{slug='',current='home'}={}){
 const zh=lang==='zh',t=(en,cn)=>zh?cn:en,p=zh?'/zh':'',home=zh?'/cn':'/',alternate=slug?(zh?'':'/zh')+'/'+slug:(zh?'/':'/cn');
 return `<header class="agi-header"><div class="agi-header-inner"><a class="agi-brand" href="${home}" aria-label="${t('AGI Scorecard home','AGI 记分牌首页')}"><span aria-hidden="true">A</span>${t('AGI Scorecard','AGI 记分牌')}</a><nav aria-label="${t('Main navigation','主导航')}"><a href="${home}" ${current==='home'?'aria-current="page"':''}>${t('Home','首页')}</a><a href="${p}/future-guide" data-home-action="library" ${current==='videos'?'aria-current="page"':''}>${t('Videos & ideas','视频与观点')}</a><a href="${p}/progress-index">${t('Evidence','证据')}</a><a href="${p}/jarvis">${t('Jarvis','贾维斯')}</a><a class="agi-nav-extra" href="${p}/ai-tools">${t('Tools','工具')}</a><a class="agi-nav-extra" href="${p}/invest">${t('Invest','投资')}</a></nav><a class="agi-language" id="language" href="${alternate}" lang="${zh?'en':'zh-Hans'}" aria-label="${zh?'Switch to English':'切换到中文'}">${zh?'EN':'中文'}</a></div></header>`;
}
export function homeSnapshot(data){
 const items=contentItems(data),videos=items.filter(i=>i.medium==='video'),feature=videos.find(i=>i.video&&i.views.length);
 if(!feature)throw Error('Homepage requires a sourced, reviewed video');
 const counts={videos:videos.length,audio:items.filter(i=>i.medium==='audio').length,views:items.reduce((n,i)=>n+i.views.length,0),sources:data.sources.length};
 const locales={};
 for(const lang of ['en','zh']){
  const zh=lang==='zh',t=(en,cn)=>zh?cn:en,hub=(zh?'/zh':'')+'/future-guide',view=feature.views[0],d=view[lang];
  const latest=videos.filter(i=>i.video&&i.language===lang).slice(0,4);
  const stat=`<span><strong>${counts.videos}</strong> ${t('videos','条视频')}</span><a href="${hub}?media=audio#fresh" data-home-action="audio"><strong>${counts.audio}</strong> ${t('audio episodes','条音频')}</a><span><strong>${counts.views}</strong> ${t('reviewed views','条已核对观点')}</span>`;
  const featured=`<article class="home-feature" data-home-feature="${feature.video}"><div class="home-poster"><div class="home-poster-fallback" aria-hidden="true"><span>${esc(feature.publisher)}</span><strong>${esc(feature.posterLabel||feature.publisher)}</strong><small>${esc(feature.speaker)}</small></div><img src="https://i.ytimg.com/vi/${feature.video}/hqdefault.jpg" width="480" height="360" alt="" decoding="async" referrerpolicy="no-referrer"><button type="button" data-home-video="${feature.video}" data-player-title="${esc(feature.title[lang])}" aria-label="${esc(t('Watch: ','观看：')+feature.title[lang])}"><span aria-hidden="true">▶</span>${t('Watch here','直接观看')}</button></div><div class="home-feature-copy"><p class="home-eyebrow">${t('Featured perspective','精选观点')} <span>${t('English original','英文原片')} · ${feature.date}</span></p><h2><a href="${hub}/${view.id}" data-home-action="view">${esc(d.title)}</a></h2><p>${esc(d.summary)}</p><div class="home-feature-actions"><a href="${hub}/${view.id}" data-home-action="view">${t('Read takeaways & evidence','看观点与证据')} ↗</a><a href="${esc(feature.watch)}" target="_blank" rel="noopener">${t('Original video','原视频')} ↗</a></div></div></article>`;
  const topicLinks=topics.filter(g=>g.id!=='all').map(g=>`<a href="${hub}?topic=${g.id}#fresh" data-home-action="topic">${esc(g[lang])}<span>${videos.filter(i=>i.goals.includes(g.id)).length}</span></a>`).join('');
  const latestCards=latest.map(i=>`<article class="home-latest-card"><a class="home-thumb" href="${hub}?watch=${i.video}#fresh" data-home-action="latest"><span class="home-thumb-fallback">${esc(i.publisher)}</span><img src="https://i.ytimg.com/vi/${i.video}/hqdefault.jpg" loading="lazy" width="480" height="360" alt="" referrerpolicy="no-referrer"><span class="home-thumb-play" aria-hidden="true">▶</span></a><p class="home-video-meta">${esc(i.publisher)} <time datetime="${i.date}">${i.date}</time></p><h3><a href="${hub}?watch=${i.video}#fresh" data-home-action="latest">${esc(typeof i.title==='string'?i.title:i.title[lang])}</a></h3><p class="home-review-label">${i.views.length?t('Reviewed takeaways','已有观点总结'):t('Summary pending review','观点总结待核对')}</p></article>`).join('');
  const feed=`<section class="focus-future" id="home-videos" data-release="agi-home-library-20261003" aria-labelledby="home-videos-heading"><div class="home-section-heading"><div><h2 id="home-videos-heading">${t('Follow the questions that matter to you.','从你关心的问题，看见下一步。')}</h2><p>${t('Interviews, creator videos and research. Choose a perspective.','访谈、博主视频与研究解说，按观点主题持续整理。')}</p></div><a href="${hub}" data-home-action="library">${t('Browse all videos','浏览全部视频')} ↗</a></div><nav class="home-topics" aria-label="${t('Browse video topics','按观点主题浏览视频')}">${topicLinks}</nav><div class="home-section-heading home-latest-heading"><h3>${t('Latest English videos','最新中文视频')}</h3><a href="${hub}?lang=${lang}&order=newest#fresh" data-home-action="latest">${t('See more','查看更多')} ↗</a></div><div class="home-latest-grid">${latestCards}</div><p class="home-sync-note">${t('Checked ','最近检查 ')}<time datetime="${esc(data.checkedAt)}">${esc(data.checkedAt?.replace('T',' ').replace('Z',' UTC'))}</time> · ${t('Daily source checks; reviewed summaries are published separately.','每日检查来源；观点总结经核对后另行发布。')}</p></section>`;
  locales[lang]={header:siteHeader(lang),stats:stat,feature:featured,feed};
 }
 return {version:1,checkedAt:data.checkedAt,counts,locales};
}
