#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""GEO rules/answer pages for the games portal (2026-08-24, owner: 游戏方向
快速 GEO 扩展). One page per real search query — definition/rules type, the
page family AI answer engines actually cite. Every number on these pages is
first-party (generator acceptance data, baked daily counts); rules text is
taken from the live game pages, not paraphrased from other sites."""
import json, html, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = os.path.join(ROOT, "site")
TODAY = "2026-08-24"
BASE = "https://play.agiscorecard.com"

PAGES = [
 dict(slug="futoshiki-rules", game="futoshiki", icon="≶", play="/futoshiki",
  title="Futoshiki Rules: How to Play and Solve Without Guessing",
  h1="Futoshiki Rules — and How to Solve One",
  desc="Futoshiki rules in one paragraph: fill 1–5 so each row and column has every number once, and every inequality sign holds. Plus three core solving techniques and a verified daily puzzle.",
  capsule="<strong>Futoshiki is Latin-square-plus-inequalities.</strong> Fill the grid with the numbers 1–5 (one of each per row and column) so that every inequality sign between two cells is true — the arrow always points at the smaller number. That is the whole rule set: two constraints, no arithmetic. What makes a board hard is how few starting numbers you get; a well-made futoshiki needs no guessing at all.",
  rules=[("Latin square","Every row and every column contains each number exactly once — no repeats."),
         ("Inequalities","Every ‹ › ∧ ∨ sign between two adjacent cells must hold; the sign points at the smaller number."),
         ("Givens","Some cells start filled. On a verified board these plus the signs force a unique solution.")],
  tech=[("Follow the chains","A run of linked inequalities a ‹ b ‹ c pins the extremes: the small end of a 4-cell chain can only be 1 or 2 on a 5×5. Mark chain minimums and maximums first."),
        ("Place the 1s and 5s","A cell that is 'greater' in several signs cannot be 1; a cell that is 'smaller' anywhere cannot be 5. Scan each row for the only cell allowed to hold each extreme."),
        ("Candidate elimination","When a number lands, remove it from the row and column and re-check every touching inequality — one placement usually cascades through two or three signs.")],
  data="Every daily board here is generated by a solver-in-the-loop: sparse random clue sets are almost never unique, so the generator starts from a full set of edges and minimizes while re-proving uniqueness at every step. 450 daily 5×5 boards (from 2026-08-24) plus 320 free-play boards in three difficulties are pre-verified — exactly one solution, reachable by pure deduction.",
  faqs=[("What are the rules of futoshiki?","Fill the grid so every row and column contains each number exactly once (1–5 on a 5×5), and every inequality sign between adjacent cells is satisfied — the sign always points at the smaller number. Some cells are pre-filled as givens."),
        ("Can futoshiki be solved without guessing?","A properly constructed futoshiki can. Every puzzle on this site is machine-verified before publication to have exactly one solution reachable by pure deduction. Randomly generated boards without that check frequently require trial and error."),
        ("What is the best first move in futoshiki?","Follow the longest chain of inequalities: its ends are forced toward 1 and the maximum number. On a 5×5, the small end of a four-cell chain can only be 1 or 2 — that is usually the strongest opening deduction.")]),
 dict(slug="kropki-sudoku-rules", game="kropki", icon="⚫", play="/kropki",
  title="Kropki Sudoku Rules: What Black and White Dots Mean",
  h1="Kropki Rules — Black Dots, White Dots, and the Missing Dot",
  desc="Kropki rules: white dot = the two cells differ by exactly 1; black dot = one is double the other; no dot = neither relation holds. The absence of a dot is half the puzzle.",
  capsule="<strong>Kropki has exactly three signals.</strong> A <strong>white dot</strong> between two cells means they differ by exactly 1 (like 3·4). A <strong>black dot</strong> means one is double the other (like 2·4). And <strong>no dot means neither relation holds</strong> — the missing dot is a real constraint, not an absence of information. A 1-2 pair satisfies both relations; by convention it is marked with a black dot. Rows and columns still contain each number once, like any Latin square.",
  rules=[("Latin square","Every row and every column contains each number exactly once."),
         ("White dot","The two cells differ by exactly 1 — consecutive numbers in either order."),
         ("Black dot","One cell is exactly double the other (1·2, 2·4 on a 5×5)."),
         ("No dot","Neither relation holds — this negative constraint eliminates as many candidates as the dots do."),
         ("1-2 convention","1 and 2 both differ by one and double — the pair is marked black by convention.")],
  tech=[("Start from the black dots","On a 5×5 only 1·2 and 2·4 can sit under a black dot, so every black dot forces a 2 into one of its two cells. A chain of two black dots is even stronger: it must be 1-2-4."),
        ("Use the silence","A cell next to a 3 with no dot between them cannot be 2, 4, or 6. On boards with few or zero givens — most dailies here start empty — the dotless edges do most of the work."),
        ("Parity walks","White-dot chains alternate odd/even. Trace a chain from any placed number and half the candidates disappear along the whole chain.")],
  data="Most daily kropki boards here start with zero given digits — the dot pattern alone determines a unique solution, and the client enforces the negative constraint too (many sites don't). 450 daily 5×5 boards plus 320 free-play boards, each machine-verified for a unique deduction-reachable solution before publication.",
  faqs=[("What do the dots mean in kropki sudoku?","A white dot between two cells means the numbers differ by exactly 1. A black dot means one number is exactly double the other. If there is no dot, neither relation holds — that negative constraint is a full part of the rules."),
        ("What about 1 and 2 in kropki — black or white dot?","1 and 2 satisfy both relations (they differ by 1, and 2 is double 1). The standard convention, used here, is to mark a 1-2 pair with a black dot."),
        ("Can a kropki puzzle have no given numbers at all?","Yes. The dot and no-dot pattern can force a unique solution on its own — most daily boards on this site start completely empty and are machine-verified to be solvable by pure deduction.")]),
 dict(slug="sandwich-sudoku-rules", game="sandwich", icon="🥪", play="/sandwich",
  title="Sandwich Sudoku Rules: How the Outside Sums Work",
  h1="Sandwich Rules — What the Outside Numbers Mean",
  desc="Sandwich rules: each outside clue is the sum of the numbers between 1 and the largest number in that row or column. A 0 means 1 and the max are adjacent. Techniques and a verified daily.",
  capsule="<strong>Each outside clue sums the 'filling'.</strong> In every row and column, find where 1 and the largest number (5 on a 5×5) sit — the clue on the outside is the sum of everything strictly between them. A clue of <strong>0</strong> means 1 and 5 are adjacent; the maximum clue (2+3+4 = 9 on a 5×5) means they sit at opposite ends. Rows and columns still contain each number exactly once.",
  rules=[("Latin square","Every row and every column contains each number exactly once."),
         ("Sandwich sum","The outside clue equals the sum of the numbers strictly between 1 and the largest number in that line."),
         ("All clues shown","This site shows all 2n clues (classic presentation) and minimizes the given digits instead.")],
  tech=[("Read the extremes first","0 ⇒ 1 and 5 are adjacent somewhere in the line. 9 (on 5×5) ⇒ they are the two ends. Both cases cut the possible 1/5 positions to a handful."),
        ("Count the filling size","A sum of 2 can only be the single cell {2}; a sum of 5 can be {5}? No — 5 is the bread. It must be {2,3}. Each sum value maps to very few multisets; list them."),
        ("Cross the crusts","Once 1 or 5 lands in one line, it constrains the crossing line's sandwich too — the crusts are shared between row and column reads.")],
  data="450 daily 5×5 boards (from 2026-08-24) plus 320 free-play boards. The generator keeps every sandwich clue visible and minimizes given digits only, re-verifying at each removal that exactly one solution remains reachable by deduction.",
  faqs=[("How do sandwich sudoku clues work?","Each clue outside the grid is the sum of the numbers that sit strictly between 1 and the largest number in that row or column. The 1 and the maximum are the 'bread'; the clue sums the filling."),
        ("What does a 0 clue mean in sandwich sudoku?","A 0 means there is nothing between 1 and the largest number — they are adjacent in that row or column. It is one of the strongest clues in the puzzle."),
        ("Is sandwich sudoku harder than regular sudoku?","It trades box constraints for arithmetic on positions, so it feels harder at first: the information is indirect. On a verified board the difficulty is bounded — every daily here is machine-checked to need no guessing.")]),
 dict(slug="skyscraper-puzzle-rules", game="towers", icon="🏙", play="/towers",
  title="Skyscraper Puzzle Rules: How the Edge Clues Work",
  h1="Skyscraper Rules — Counting Towers You Can See",
  desc="Skyscraper puzzle rules: fill heights 1–5 so rows and columns have no repeats, and each edge clue counts the towers visible from that side — taller towers hide shorter ones.",
  capsule="<strong>Every edge clue is a line of sight.</strong> Fill the grid with tower heights 1–5, one of each per row and column. An observer at each edge clue looks down that line: a tower is visible only if it is taller than everything before it, so the clue equals the number of visible towers. A clue of <strong>1</strong> means the tallest tower stands right at that edge; a clue of <strong>5</strong> means the heights ascend all the way (1-2-3-4-5).",
  rules=[("Latin square","Every row and every column contains each height exactly once."),
         ("Visibility count","Each edge clue equals the number of towers visible from that side; taller towers hide all shorter towers behind them."),
         ("Classic presentation","All edge clues are shown; the given digits inside the grid are minimized instead.")],
  tech=[("1s and ns first","Clue 1 ⇒ the tallest tower (5) is adjacent to that clue. Clue 5 ⇒ the whole line ascends 1-2-3-4-5. Fill every forced cell these produce before anything else."),
        ("Opposite-edge sum","For the same line seen from both ends, clue_a + clue_b ≤ n + 1. Pairs that hit the bound (like 2 and 4 on a 5×5) sharply limit where the 5 can stand."),
        ("Ban the tall early","A clue of k means the first k−1 cells cannot hold the tallest tower — cross 5 out of them immediately, then re-apply the row/column no-repeat rule.")],
  data="450 daily 5×5 boards (from 2026-08-24) plus 320 free-play boards, all edge clues kept visible in the classic style. Interior givens are minimized with the solver re-proving a unique, deduction-reachable solution after every removal.",
  faqs=[("What are the rules of a skyscraper puzzle?","Fill the grid with tower heights (1–5 on a 5×5) so every row and column contains each height once. Each clue on the edge counts how many towers are visible looking down that row or column from the clue's position — taller towers hide shorter ones behind them."),
        ("What does a 1 clue mean in skyscraper puzzles?","A 1 means only one tower is visible from that edge, which forces the tallest tower (5 on a 5×5) to stand immediately next to that clue."),
        ("What is the opposite-clue trick in skyscraper puzzles?","For any line, the two clues at its opposite ends satisfy a + b ≤ n + 1, where n is the grid size. Clue pairs near that bound pin down the position of the tallest tower quickly.")]),
 dict(slug="star-battle-rules", game="starbattle", icon="⭐", play="/starbattle",
  title="Star Battle Rules: How to Play the Two-Star Puzzle",
  h1="Star Battle Rules — Two Stars Everywhere, None Touching",
  desc="Star battle rules: place stars so every row, column, and colored region holds exactly the star count (2 on a 10×10), and no two stars touch, even diagonally. Techniques included.",
  capsule="<strong>Three 'exactly' constraints and one 'never'.</strong> Place stars so that every row, every column, and every colored region ends with exactly the required number of stars — <strong>2★ on the daily 10×10</strong>, 1★ on easy 8×8 boards — and no two stars ever touch, not even diagonally. No arithmetic, no numbers: pure placement logic.",
  rules=[("Rows & columns","Every row and every column contains exactly the required number of stars (2 on the daily)."),
         ("Regions","Every colored region also contains exactly that many stars."),
         ("No touching","No two stars are adjacent — horizontally, vertically, or diagonally."),
         ("Notes","The × mark is a player note for 'no star here'; the client uses it for bookkeeping only.")],
  tech=[("Count regions against rows","If k regions fit entirely inside m rows and k×stars = m×stars, those regions own all of those rows' stars — every cell of other regions in those rows is ×."),
        ("Squeeze small regions","A 2-cell or 3-cell region with 2★... cannot exist; a small region often has only one legal star layout once adjacency is applied. Solve tight regions first."),
        ("Ring the placed star","Every placed star immediately ×-es its eight neighbors, and a completed row/column/region ×-es all its remaining cells — cascade these before searching anything.")],
  data="The generator works placement-first: stars are placed, regions are grown around them, then the board is accepted only if a solver proves the solution unique. Acceptance is brutal — about 0.2% of candidate 8×8 1★ boards survive — which is why every one of the 450 daily 10×10 2★ boards (from 2026-08-24) needs no guessing.",
  faqs=[("What are the rules of star battle?","Place stars so every row, every column, and every colored region contains exactly the required number of stars (two on a standard 10×10), and no two stars touch each other, not even diagonally."),
        ("How many stars go in each row in star battle?","On the daily 10×10 puzzle here: exactly two per row, two per column, and two per region. Easy 8×8 boards use one star. The count is always printed with the puzzle."),
        ("Is star battle the same as the LinkedIn Queens game?","They are the same puzzle family — Queens is a one-star star battle with crown symbols. The classic name for the type, used by puzzle books and championships, is star battle; this site's daily is the harder two-star form.")]),
 dict(slug="thermometer-puzzle-rules", game="thermo", icon="🌡", play="/thermo",
  title="Thermometer Puzzle Rules: How the Mercury Fills",
  h1="Thermometer Puzzle Rules — Fill From the Bulb",
  desc="Thermometer puzzle rules: mercury fills each thermometer from the bulb along the tube with no gaps; edge clues count filled cells per row and column. With solving techniques.",
  capsule="<strong>Two rules, one physical metaphor.</strong> Every thermometer fills from its bulb (●) along the tube — a cell can be filled only if everything between it and the bulb is filled, never with gaps. The clues outside the grid say how many cells in that row or column end up filled. That's it: no numbers inside the grid at all.",
  rules=[("Mercury","Each thermometer fills from the bulb along its tube — contiguously, possibly not at all, possibly fully."),
         ("Row/column counts","Each outside clue equals the number of filled cells in that row or column."),
         ("Interaction","Thermometers bend across rows and columns, so one fill decision feeds several counts.")],
  tech=[("Extremes first","A clue equal to the number of thermometer cells in that line fills them all; a 0 empties them all. Both cascade along tubes into neighboring lines."),
        ("Min-max each tube","For every thermometer, ask: how few cells CAN it contribute to this line, how many at most? If the minimum already meets the clue, everything optional is empty — and vice versa."),
        ("Follow the bends","Filling one cell fills everything bulb-ward on the same tube — including cells in other rows. Always propagate along the tube before reading the next clue.")],
  data="450 daily 6×6 boards (from 2026-08-24) plus 320 free-play boards. The solver uses suffix-bound pruning to prove each published board has exactly one solution reachable by deduction — the same check as every other game on this site.",
  faqs=[("What are the rules of a thermometer puzzle?","Fill thermometers with mercury starting from the bulb, continuously along the tube with no gaps. Numbers outside the grid tell how many cells are filled in each row and column."),
        ("Can part of a thermometer be filled?","Yes — a thermometer can be empty, partly filled, or full, as long as the filled part starts at the bulb and is contiguous. What it cannot have is a gap."),
        ("What is the best way to start a thermometer puzzle?","Do the extremes: any row or column whose clue equals its total thermometer cells is fully filled; any 0 line is fully empty. Both propagate along bent tubes into other lines and usually unlock the middle of the board.")]),
 dict(slug="nonogram-rules", game="nonogram", icon="▦", play="/nonogram",
  title="Nonogram Rules for Beginners: Reading the Number Clues",
  h1="Nonogram Rules — What the Numbers Actually Say",
  desc="Nonogram rules: each clue lists the lengths of filled runs in that row or column, in order, with at least one gap between runs. Core techniques: overlap, edge anchoring, and × marks.",
  capsule="<strong>Each clue describes runs, in order.</strong> A row clue of <strong>3 1</strong> means: somewhere in this row there is a run of 3 filled cells, then — after at least one empty cell — a run of 1, in that order. Solve by intersecting what the row clues and the column clues both allow. Filled cells reveal a picture; a well-made board never needs a guess.",
  rules=[("Run lengths","Each clue lists the lengths of the filled runs in its row or column, left-to-right or top-to-bottom."),
         ("Gaps","Between two runs there is at least one empty cell; before the first and after the last there may be any number."),
         ("× marks","Marking a cell × ('definitely empty') is bookkeeping for you — it is how the overlap logic becomes visible.")],
  tech=[("Overlap (the workhorse)","If a run is longer than half its free space, its middle cells are filled in every legal position. A 7-clue in a 10-wide row fills cells 4–7 immediately — start every board this way."),
        ("Anchor the edges","A filled cell touching the border pins its whole run: clue 4 with a filled corner cell fills four cells and ×-es the fifth."),
        ("Punctuate with ×","Completed runs get × on both ends. Those × cells shrink the free space for every crossing column clue — the cascade is where nonograms are actually solved.")],
  data="Every daily board here passes a stronger check than unique-solution: <a href=\"/nonogram-no-guessing\">line-solvability</a> — iterating row/column constraint intersection to a fixpoint must complete the whole grid. In our published measurement, only 43% of random 20×20 boards pass that bar, which is why unverified nonograms so often force guessing. 450 daily 10×10 boards (from 2026-08-24), all verified.",
  faqs=[("How do you read nonogram clues?","Each number is the length of a consecutive filled run in that row or column. Multiple numbers appear in order, separated by at least one empty cell. '3 1' means a run of three, a gap of one or more, then a single filled cell."),
        ("Do nonogram runs have to be in order?","Yes — the clue order matches the order of the runs in the line, reading left-to-right for rows and top-to-bottom for columns. Only the gap sizes are unknown."),
        ("What is the overlap technique in nonograms?","Slide a run to its leftmost and rightmost legal positions; any cells filled in both extremes are filled in every solution. It is the single most productive nonogram deduction and the standard way to open a board.")]),
 dict(slug="6x6-sudoku-rules", game="minisudoku", icon="🔢", play="/minisudoku",
  title="6x6 Sudoku Rules: How the 2×3 Boxes Work",
  h1="6×6 Sudoku Rules — Small Grid, Same Logic",
  desc="6x6 sudoku rules: place 1–6 once per row, column, and outlined 2×3 box. Why the rectangular boxes change the logic, and a machine-verified daily mini sudoku.",
  capsule="<strong>Standard sudoku, one size down.</strong> Fill the 6×6 grid with the numbers 1–6 so every row, every column, and every outlined <strong>2×3 box</strong> contains each number exactly once. The rectangular boxes are the twist: each box spans only two rows but three columns, so box-line interactions fire differently than in the 9×9 you know.",
  rules=[("Rows & columns","Every row and every column contains 1–6 exactly once."),
         ("2×3 boxes","Each outlined box (two rows × three columns) also contains 1–6 exactly once."),
         ("Givens","Pre-filled cells; the daily board is minimized while keeping a unique deduction-reachable solution.")],
  tech=[("Box-row claiming","A box covers three cells of a row. If a number's only spots in the box sit in one row, that number is banned from the rest of the row — this fires constantly on 2×3 boxes."),
        ("Pair up the six","With only six values, a row missing three numbers over three cells is a tiny puzzle on its own. Naked pairs and triples appear early and often — look for them before scanning."),
        ("Two-box bands","Each band of two boxes spans two rows exactly. A number placed in one box of a band forces its row within the neighbor box — the 6×6's version of pointing pairs.")],
  data="450 daily 6×6 boards (from 2026-08-24) plus 320 free-play boards in three difficulties. Each board's givens are minimized by a solver that re-proves after every removal that exactly one solution remains, reachable by pure logic — no guessing, no notes required.",
  faqs=[("What are the rules of 6x6 sudoku?","Fill the grid with numbers 1–6 so that every row, every column, and every outlined 2×3 box contains each number exactly once. It is standard sudoku logic on a smaller grid."),
        ("How are the boxes shaped in 6x6 sudoku?","Each box is a rectangle of two rows by three columns; the grid holds six of them. The rectangular shape makes box-and-row interactions more frequent than in 9×9 sudoku."),
        ("Is 6x6 sudoku good for beginners?","Yes — the full rule set of sudoku with a search space small enough to finish in a few minutes. The daily boards here are verified to need no guessing, which makes them reliable practice for the core techniques.")]),
 dict(slug="binary-puzzle-rules", game="balance", icon="🌙", play="/balance",
  title="Binary Puzzle Rules: Balance, Never Three in a Row",
  h1="Binary Puzzle Rules — Two Symbols, Two Constraints",
  desc="Binary puzzle (Binairo/Tango family) rules: equal counts of the two symbols per row and column, and never three identical symbols adjacent. Techniques and a verified daily.",
  capsule="<strong>Two symbols, two rules.</strong> Fill the 6×6 grid with suns and moons so that every row and every column ends with exactly <strong>three of each</strong>, and <strong>never three of the same symbol in a row</strong> — horizontally or vertically. This is the classic binary-puzzle family (also seen as Binairo, Takuzu, or LinkedIn's Tango): trivially stated, surprisingly deep.",
  rules=[("Equal counts","Every row and every column contains exactly three suns and three moons (on 6×6)."),
         ("No triples","Three identical symbols never sit consecutively, in any row or column."),
         ("Unique solution","Each published board is machine-verified: one solution, reachable by deduction alone.")],
  tech=[("Split the pairs","Two identical symbols side by side must be capped on both ends by the opposite symbol — ☀☀ forces 🌙☀☀🌙. This is the fastest-firing rule in the family."),
        ("Fill the middle of X_X","A gap between two identical symbols must hold the opposite one: ☀_☀ forces a moon in the middle, or three-in-a-row appears."),
        ("Count to three","The moment a row holds its third sun, every empty cell in it is a moon. Combine with the no-triples check to finish lines in one sweep.")],
  data="450 daily 6×6 boards (from 2026-08-24) plus 440 free-play boards in three difficulties, all with the same verification contract as every game on this site: exactly one solution, provably reachable without guessing, checked by machine before publication.",
  faqs=[("What are the rules of a binary puzzle?","Fill the grid with two symbols so that each row and column contains an equal number of both, and no three identical symbols are adjacent horizontally or vertically. Some versions also forbid duplicate rows; this site's boards are uniquely solvable from the two core rules and the givens."),
        ("Is this the same as Tango or Binairo?","Same family. Binairo/Takuzu use 0s and 1s, LinkedIn's Tango uses suns and moons with extra = and × edge hints. The two core constraints — balanced counts and no three in a row — are shared across all of them."),
        ("What is the fastest deduction in binary puzzles?","Cap every adjacent pair: two identical symbols in a row force the opposite symbol on both ends. Together with filling the middle of an X_X gap, these two moves solve most of a 6×6 before counting is even needed.")]),
 dict(slug="games-like-linkedin-queens", game=None, icon="🧩", play="/",
  title="Games Like LinkedIn Queens: 11 Free Daily Logic Puzzles",
  h1="Games Like LinkedIn Queens — 11 Free Dailies, No Account",
  desc="Looking for games like LinkedIn Queens or Tango? 11 free daily logic puzzles — star battle, binary balance, futoshiki, nonogram and more. No account, no ads, machine-verified no-guess boards.",
  capsule="<strong>If you like LinkedIn Queens, the classic name for that puzzle family is star battle</strong> — and it lives here as a harder daily 2★ 10×10, next to ten sibling games in the same spirit: one new board a day, pure logic, no account, no ads. Every board on this site is machine-verified before publication to have exactly one solution you can reach without guessing — the property that makes the LinkedIn games feel fair, guaranteed here across all 11 games.",
  rules=None,
  table_head=("Daily game","Puzzle family","If you liked…"),
  table_rows=[
   ("<a href=\"/starbattle\">Star Battle</a> ⭐","Star placement, 2★ 10×10","LinkedIn Queens (same family, harder form)"),
   ("<a href=\"/balance\">Balance</a> 🌙","Binary balance (Binairo/Takuzu)","LinkedIn Tango"),
   ("<a href=\"/trail\">Trail</a> 🐾","One-line path through ordered waypoints","LinkedIn's path-drawing daily"),
   ("<a href=\"/\">Gridlings</a> 🦊","Double Latin square + adjacency","Sudoku with a twist; our original flagship"),
   ("<a href=\"/futoshiki\">Futoshiki</a> ≶","Latin square + inequalities","Classic Japanese newspaper puzzle"),
   ("<a href=\"/towers\">Towers</a> 🏙","Skyscraper visibility counts","Futoshiki, with line-of-sight logic"),
   ("<a href=\"/minisudoku\">Mini Sudoku</a> 🔢","6×6 sudoku, 2×3 boxes","A five-minute sudoku fix"),
   ("<a href=\"/kropki\">Kropki</a> ⚫","Dot-constraint Latin square","Sudoku variants; most dailies start empty"),
   ("<a href=\"/sandwich\">Sandwich</a> 🥪","Sum-between-1-and-max clues","Cracking-the-Cryptic-style variants"),
   ("<a href=\"/thermo\">Thermometers</a> 🌡","Fill-count picture logic","Picture logic without number entry"),
   ("<a href=\"/nonogram\">Nonogram</a> ▦","Picture logic from run clues","Picross-style picture reveals")],
  tech=[("One habit, eleven boards","All 11 games drop a new board at 00:00 UTC with streaks and a Daily Sweep counter (finish all 11 for the day). The <a href=\"/archive\">archive</a> keeps every past daily playable."),
        ("Verified no-guess boards","The LinkedIn games feel fair because they never force a guess. Here that property is machine-verified per board — including a <a href=\"/nonogram-no-guessing\">published measurement</a> of how often random puzzles fail it."),
        ("Embed or study them","Every game embeds in an iframe (add ?embed=1), and researchers can use the <a href=\"/bench\">1,100-puzzle open benchmark</a> (CC BY 4.0) built from the same generators.")],
  data="All 11 games: free, browser-based, mobile-ready (installable as an app), no account, no ads, bilingual (English / 中文). 450 pre-baked dailies per game from 2026-08-24 plus ~320 free-play boards each — every one verified for a unique, deduction-reachable solution.",
  faqs=[("What is the LinkedIn Queens game actually called?","The puzzle type is star battle, a placement puzzle from the international puzzle-championship scene. Queens is a one-star variant with crown symbols; the classic form, playable here daily, uses two stars per row, column, and region."),
        ("Are there free alternatives to LinkedIn's daily games?","Yes — this site runs 11 free daily logic puzzles covering the same families (star placement, binary balance, path drawing) plus classics like futoshiki, nonogram, and skyscrapers. No account or app is required."),
        ("Do these puzzles ever require guessing?","No. Every board is checked by machine before publication to have exactly one solution reachable by pure deduction — the same fairness property the LinkedIn games are known for, verified rather than assumed.")]),
]

def faq_ld(faqs):
    ents = [{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in faqs]
    return json.dumps({"@context":"https://schema.org","@type":"FAQPage","mainEntity":ents}, ensure_ascii=False)

def art_ld(p):
    return json.dumps({"@context":"https://schema.org","@type":"Article","headline":p["title"],
      "datePublished":TODAY,"dateModified":TODAY,"inLanguage":"en",
      "author":{"@type":"Organization","name":"Gridlings (AGI Scorecard)","url":"https://agiscorecard.com/about"},
      "publisher":{"@type":"Organization","name":"Gridlings","url":BASE+"/"},
      "description":p["desc"]}, ensure_ascii=False)

def crumb_ld(p):
    return json.dumps({"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[
      {"@type":"ListItem","position":1,"name":"Gridlings","item":BASE+"/"},
      {"@type":"ListItem","position":2,"name":p["h1"],"item":BASE+"/"+p["slug"]}]}, ensure_ascii=False)

def build(p):
    rows = ""
    if p.get("rules"):
        head = "<tr><th style=\"text-align:left;padding:6px 8px;border-bottom:1px solid var(--line)\">Rule</th><th style=\"text-align:left;padding:6px 8px;border-bottom:1px solid var(--line)\">What it means</th></tr>"
        for k,v in p["rules"]:
            rows += f"<tr><td style=\"padding:6px 8px;white-space:nowrap\"><strong>{k}</strong></td><td style=\"padding:6px 8px\">{v}</td></tr>"
    else:
        th = p["table_head"]
        head = "<tr>" + "".join(f"<th style=\"text-align:left;padding:6px 8px;border-bottom:1px solid var(--line)\">{h}</th>" for h in th) + "</tr>"
        for r in p["table_rows"]:
            rows += "<tr>" + "".join(f"<td style=\"padding:6px 8px\">{c}</td>" for c in r) + "</tr>"
    tech = "".join(f"<h2>{t}</h2><p>{b}</p>" for t,b in p["tech"])
    faqs_html = "".join(f"<h3 style=\"font-size:.98rem;margin:10px 0 2px\">{html.escape(q)}</h3><p style=\"margin:0 0 6px\">{html.escape(a)}</p>" for q,a in p["faqs"])
    live = ""
    if p["game"]:
        jsonf = ("puzzles" if p["game"]=="puzzles" else p["game"]) + "-daily.json"
        live = f"""<p id=\"live\" style=\"border:1px solid var(--line);border-radius:10px;background:var(--bg2);padding:10px 12px;font-size:.95rem\">Today's verified daily is live — <a href=\"{p['play']}\">play it now</a>.</p>
<script>fetch("/{jsonf}").then(r=>r.json()).then(d=>{{var e=new Date(d.epoch+"T00:00:00Z"),n=Math.floor((Date.now()-e)/864e5)+1;if(n>0)document.getElementById("live").innerHTML='Daily board <strong>#'+n+'</strong> is live now (a new one at 00:00 UTC) — <a href="{p['play']}">play it</a>, or browse the <a href="/archive">archive</a>.';}}).catch(()=>{{}});</script>"""
    else:
        live = f"""<p style=\"border:1px solid var(--line);border-radius:10px;background:var(--bg2);padding:10px 12px;font-size:.95rem\">All 11 dailies refresh at 00:00 UTC — <a href=\"/\">start the Daily Sweep</a>.</p>"""
    related = " · ".join(f"<a href=\"/{q['slug']}\">{q['icon']} {q['slug'].replace('-',' ')}</a>" for q in PAGES if q["slug"] != p["slug"])
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
<title>{html.escape(p['title'])}</title>
<meta name="description" content="{html.escape(p['desc'])}">
<link rel="canonical" href="{BASE}/{p['slug']}">
<link rel="stylesheet" href="style.css">
<link rel="manifest" href="/manifest.webmanifest">
<meta name="theme-color" content="#002FA7">
<meta property="og:title" content="{html.escape(p['title'])}">
<meta property="og:description" content="{html.escape(p['desc'])}">
<meta property="og:url" content="{BASE}/{p['slug']}">
<meta property="og:type" content="article">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>{p['icon']}</text></svg>">
<script type="application/ld+json">{art_ld(p)}</script>
<script type="application/ld+json">{faq_ld(p['faqs'])}</script>
<script type="application/ld+json">{crumb_ld(p)}</script>
</head>
<body>
<div class="wrap">
<header>
  <h1 style="font-size:1.3rem"><a href="/{p['slug']}">{p['h1']}</a></h1>
</header>

<div class="rules" style="border-top:0;padding-top:6px">
  <p style="font-size:1.02rem">{p['capsule']}</p>
  {live}
  <h2>{'The rules' if p.get('rules') else 'The 11 daily games'}</h2>
  <table style="width:100%;border-collapse:collapse;font-variant-numeric:tabular-nums">
    <thead>{head}</thead>
    <tbody>{rows}</tbody>
  </table>
  {tech}
  <h2>Verified, not promised</h2>
  <p>{p['data']}</p>
</div>

<div class="rules">
  <h2>FAQ</h2>
  {faqs_html}
</div>

<div class="rules" style="font-size:.9rem;color:var(--mut)">
  <p>More rules guides: {related}</p>
  <p>By the team behind <a href="https://agiscorecard.com/about">AGI Scorecard</a> · <a href="{p['play']}">Play</a> · <a href="/archive">Archive</a> · <a href="/bench">Research benchmark</a></p>
</div>
</div>
</body>
</html>
"""

for p in PAGES:
    path = os.path.join(SITE, p["slug"] + ".html")
    open(path, "w").write(build(p))
    print("wrote", p["slug"] + ".html")
