/* AUTO-GENERATED by scripts/fetch-photos.mjs — do not edit by hand. */
Object.assign(window.DS_CONFIG.productPhotos, {
  "torso": "https://www.yourdoll.com/wp-content/uploads/2026/08/FWT010-29-600x900.jpg",
  "compact-tpe": "https://www.yourdoll.com/wp-content/uploads/2025/08/cld159-9-600x900.jpg",
  "first-timer-home": "https://www.yourdoll.com/wp-content/uploads/2025/08/cld159-25-600x900.jpg",
  "silicone": "https://www.yourdoll.com/wp-content/uploads/2026/06/yed030-1-600x900.jpg",
  "brand": "https://www.yourdoll.com/wp-content/uploads/2021/11/wmd795-09-600x900.jpg",
  "male": "https://www.yourdoll.com/wp-content/uploads/2022/10/SPD057-019-600x900.jpg",
  "accessories": "https://www.yourdoll.com/wp-content/uploads/2025/08/mlw-jiusheng-accessories-600x900.png",
  "banner": "https://www.yourdoll.com/wp-content/uploads/2026/06/yed040-12-600x900.jpg"
});
window.DS_CONFIG.hotPicks = [
  {
    "title": "163cm (5ft4) H-cup Sex Doll Jasmine, Head #198",
    "url": "https://www.yourdoll.com/product/sex-doll-wmd014/",
    "img": "https://www.yourdoll.com/wp-content/uploads/2018/11/wmd014-08-600x900.jpg",
    "price": "$1,799.00"
  },
  {
    "title": "150cm (4ft11) Best Elf Spirit Sex Doll Samantha.C, Head #022",
    "url": "https://www.yourdoll.com/product/sex-doll-sed026/",
    "img": "https://www.yourdoll.com/wp-content/uploads/2020/03/sed026-04-600x900.jpg",
    "price": "$1,499.00"
  },
  {
    "title": "53cm (20.9”) Page Male Masturbator Sex Doll Torso In Stock",
    "url": "https://www.yourdoll.com/product/sex-doll-xsd034/",
    "img": "https://www.yourdoll.com/wp-content/uploads/2023/05/xsd034-011-600x900.jpg",
    "price": "$299.00"
  },
  {
    "title": "108cm (3ft7) J-Cup SLE Sex Doll Torso, Head ZXE201-4, Only for USA",
    "url": "https://www.yourdoll.com/product/sex-doll-wax316/",
    "img": "https://www.yourdoll.com/wp-content/uploads/2024/10/WAX316-011-600x899.jpg",
    "price": "$890.00"
  },
  {
    "title": "166cm (5ft5) C-cup Sex Doll Charlie, Head #273",
    "url": "https://www.yourdoll.com/product/sex-doll-wmd387/",
    "img": "https://www.yourdoll.com/wp-content/uploads/2018/12/wmd387-03-600x900.jpg",
    "price": "$1,749.00"
  },
  {
    "title": "173cm (5ft8″) H-cup Sex Doll Jolene, Head #70",
    "url": "https://www.yourdoll.com/product/sex-doll-wmd586/",
    "img": "https://www.yourdoll.com/wp-content/uploads/2019/11/wmd586-12-600x900.jpg",
    "price": "$2,099.00"
  },
  {
    "title": "170cm (5ft7) C-Cup Silicone Doll Scarlett, Head GE95-1",
    "url": "https://www.yourdoll.com/product/sex-doll-wax135/",
    "img": "https://www.yourdoll.com/wp-content/uploads/2022/09/WAX135-012-600x899.jpg",
    "price": "$2,249.00 Original price was: $2,249.00."
  },
  {
    "title": "53cm (20.9”) Brown Skin Color Sex Doll Torso In Stock Page",
    "url": "https://www.yourdoll.com/product/sex-doll-xsd036/",
    "img": "https://www.yourdoll.com/wp-content/uploads/2023/05/xsd036-01-600x900.jpg",
    "price": "$299.00"
  }
];
