import {chromium} from '../../../../tools/revenue-studio/node_modules/playwright/index.mjs';
import {selectClaims} from '../../foresight-assets/core.mjs';
import {claims} from '../../foresight-assets/catalog.mjs';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve('sites/agiscorecard'),out=process.env.FUTURE_ARTIFACT_DIR||'/tmp';fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');let f=path.join(root,decodeURIComponent(u.pathname));if(u.pathname==='/')f=path.join(root,'index.html');else if(!path.extname(f))f+='.html';if(!f.startsWith(root+path.sep))return res.writeHead(403).end();try{res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png'})[path.extname(f)]||'text/plain');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
let opts={headless:true};if(process.env.AGI_CHROMIUM_MODULE){const c=(await import(process.env.AGI_CHROMIUM_MODULE)).default;opts={headless:true,args:c.args.filter(a=>!['--disable-web-security','--single-process'].includes(a)),executablePath:await c.executablePath()};}
const browser=await chromium.launch(opts);
try{for(const lang of ['en','zh']){
 const prefix=lang==='zh'?'/zh':'',ctx=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true}),page=await ctx.newPage(),errors=[],external=[],uploads=[];
 page.on('pageerror',e=>errors.push(e.message));ctx.on('request',r=>{if(r.url().includes('/api/member')&&r.method()==='POST')uploads.push(r);});
 await ctx.route('**/*',r=>{if(!r.request().url().startsWith(base)){if(!r.request().url().startsWith('https://i.ytimg.com/'))external.push(r.request().url());return r.abort();}if(r.request().url().includes('/member-assets/products.json')){const products=JSON.parse(fs.readFileSync(path.join(root,'member-assets/products.json')));for(const product of products)for(const k of Object.keys(product.urls))product.urls[k]=product.urls[k].replace('https://agiscorecard.com',base);return r.fulfill({json:products});}if(r.request().url().includes('/api/member'))return r.fulfill({json:{ok:true,ready:false}});return r.continue();});
 await page.goto(base+prefix+'/future-guide?__qa=1');await page.waitForFunction(()=>document.body.dataset.ready==='true');
 assert.equal(await page.locator('[data-discovery-card]').count(),4);
 assert.equal(await page.locator('[data-media-tab=video]').getAttribute('aria-pressed'),'true');
 assert.equal(await page.locator('#fresh-feed [data-medium]:not([data-medium=video])').count(),0);
 assert.equal(await page.locator('.media-feature .view-summary li').count(),2);
 assert.equal(await page.locator('#perspectives').getAttribute('open'),null);
 assert.equal(await page.locator('iframe,audio').count(),0);assert.deepEqual(external,[]);
 await page.locator('.media-feature [data-play-video]').click();assert.match(await page.locator('.media-feature iframe').getAttribute('src'),/youtube-nocookie.com\/embed\/z9OkBD2-MDU\?autoplay=1/);
 await page.locator('[data-media-tab=audio]').click();assert.equal(await page.locator('iframe').count(),0);assert.equal(await page.locator('#fresh-feed [data-medium]:not([data-medium=audio])').count(),0);assert.equal(await page.locator('.media-feature .view-summary li').count(),2);assert.equal(await page.locator('#fresh-feed .media-poster').count(),0);
 await page.locator('[data-play-audio]').first().click();assert.equal(await page.locator('audio[controls]').count(),1);assert.match(await page.locator('audio').getAttribute('src'),/^https:/);
 await page.locator('[data-topic=family]').click();assert.ok(await page.locator('[data-discovery-card]').count()>0);assert.equal(await page.locator('audio').count(),0);
 await page.locator('[data-media-tab=text]').click();await page.locator('[data-topic=all]').click();assert.equal(await page.locator('#fresh-feed [data-medium]:not([data-medium=text])').count(),0);
 await page.locator('[data-media-tab=video]').click();await page.locator('.more-filters summary').click();await page.locator('#feed-category').selectOption('commentary');assert.ok(await page.locator('[data-discovery-card]').count()>0);
 await page.locator('#feed-language').selectOption('zh');assert.ok(await page.locator('[data-discovery-card]').count()>0);await page.locator('#feed-language').selectOption('all');await page.locator('#feed-category').selectOption('all');
 await page.locator('#feed-creator').selectOption('Matt Wolfe');assert.ok(await page.locator('[data-discovery-card]').count()>0);assert.match(await page.locator('#fresh-feed').textContent(),/Matt Wolfe/);assert.match(page.url(),/creator=Matt/);
 const discoveredVideo=await page.locator('[data-play-video]').first().getAttribute('data-play-video');await page.locator('[data-play-video]').first().click();assert.ok((await page.locator('#fresh-feed iframe').getAttribute('src')).includes('/embed/'+discoveredVideo));
 await page.setViewportSize({width:360,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'expanded creator filters fit mobile');await page.setViewportSize({width:1440,height:1100});
 await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');assert.equal(await page.locator('#feed-creator').inputValue(),'Matt Wolfe');await page.locator('.more-filters summary').click();await page.locator('#feed-creator').selectOption('all');
 await page.locator('#feed-search').fill('Fireship');assert.ok(await page.locator('[data-discovery-card]').count()>0);assert.match(await page.locator('#fresh-feed').textContent(),/Fireship/);
 await page.locator('#feed-search').fill('no matching thing');assert.equal(await page.locator('#feed-empty').isVisible(),true);await page.locator('#feed-reset').click();
 await page.locator('#feed-more').click();assert.equal(await page.locator('[data-discovery-card]').count(),10);
 await page.locator('#feed-window').selectOption('archive');assert.ok(await page.locator('[data-discovery-card]').count()>0);await page.locator('#feed-window').selectOption('all');await page.locator('.more-filters summary').click();
 await page.evaluate(()=>{document.activeElement?.blur();scrollTo({top:0,behavior:'instant'});});await page.screenshot({path:path.join(out,'agi-future-guide-'+lang+'-desktop.png'),fullPage:true});
 for(const width of [390,360]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'media hub overflow '+width);}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'agi-future-guide-'+lang+'-mobile.png'),fullPage:true});
 await page.locator('[data-media-tab=audio]').click();assert.match(page.url(),/media=audio/);await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');assert.equal(await page.locator('[data-media-tab=audio]').getAttribute('aria-pressed'),'true');
 await page.locator('[data-media-tab=video]').click();await page.locator('#perspectives > summary').click();
 assert.equal(await page.locator('[data-card]:visible').count(),Math.min(6,selectClaims('work').length));

 for(const [goal,count]of ['family','learn','earn','forecast','understand','work'].map(goal=>[goal,selectClaims(goal).length])){await page.locator('[data-goal='+goal+']').click();assert.equal(await page.locator('[data-card]:visible').count(),Math.min(6,count));}
 await page.locator('#all-views').click();await page.locator('#search').fill('Diogo');assert.equal(await page.locator('[data-card]:visible').count(),1);
 await page.locator('#search').fill('no matching thing');assert.equal(await page.locator('#empty').isVisible(),true);await page.locator('#reset-filters').click();assert.equal(await page.locator('[data-card]:visible').count(),6);
 await page.locator('#views-more').click();assert.equal(await page.locator('[data-card]:visible').count(),12);await page.locator('#time-window').selectOption('30');assert.equal(await page.locator('[data-card]:visible').count(),Math.min(6,selectClaims('all','',null,{window:'30'}).length));
 await page.locator('#time-window').selectOption('archive');assert.equal(await page.locator('[data-card]:visible').count(),3);
 await page.locator('#time-window').selectOption('all');await page.locator('.interview-directory summary').click();await page.locator('[data-interview=airbnb]').click();assert.equal(await page.locator('[data-card]:visible').count(),2);await page.locator('.interview-directory summary').click();
 await page.locator('[data-goal=work]').click();assert.equal(await page.locator('[data-card]:visible').first().getAttribute('data-card'),selectClaims('work')[0].id);
 await page.locator('#search').fill('Diogo');await page.locator('[data-save=software-judgment]').click();await page.locator('#saved-only').click();assert.equal(await page.locator('[data-card]:visible').count(),1);await page.reload();assert.equal(await page.locator('[data-save=software-judgment]').getAttribute('aria-pressed'),'true');
 await page.goto(base+prefix+'/future-guide/software-judgment?goal=work&__qa=1');assert.equal(await page.locator('iframe').count(),0);await page.screenshot({path:path.join(out,'agi-future-view-'+lang+'-mobile.png'),fullPage:true});
 await page.locator('[data-stance=agree]').click();await page.locator('#note-task').fill('Fictional QA task <script>');await page.locator('#use-suggestion').click();await page.locator('#note-counter').fill('Fictional counterexample');await page.locator('#note-review').fill('2026-11-01');await page.locator('#plan-form [type=submit]').click();await page.reload();assert.equal(await page.locator('#note-task').inputValue(),'Fictional QA task <script>');assert.equal(await page.locator('[data-stance=agree]').getAttribute('aria-pressed'),'true');
 const exportPromise=page.waitForEvent('download');await page.locator('#export-plan').click();const exported=await exportPromise;assert.match(fs.readFileSync(await exported.path(),'utf8'),/latent.space/);
 const calendarPromise=page.waitForEvent('download');await page.locator('#export-calendar').click();const calendar=await calendarPromise;assert.match(fs.readFileSync(await calendar.path(),'utf8'),/DTSTART;VALUE=DATE:20261101/);
 const popupPromise=page.waitForEvent('popup');await page.locator('[data-cloud]').click();const popup=await popupPromise;await popup.waitForFunction(()=>document.getElementById('payload')?.value.includes('future-guide'));assert.match(await popup.locator('#payload').inputValue(),/Fictional QA task/);assert.equal(uploads.length,0);
 await page.evaluate(()=>localStorage.removeItem('agi-future-guide-v1'));const restorePromise=popup.waitForEvent('popup');await popup.locator('#restore').click();const restored=await restorePromise;await restored.waitForLoadState('domcontentloaded');await restored.waitForFunction(()=>localStorage.getItem('agi-future-guide-v1')?.includes('Fictional QA task'));assert.match(await restored.locator('#saved-list').textContent(),/AI/);await restored.reload();assert.equal(await restored.locator('.saved-row').count(),1);await restored.close();await popup.close();
 await page.locator('#load-video').click();assert.match(await page.locator('#video-stage iframe').getAttribute('src'),/youtube-nocookie.com\/embed\/cFx9Z3ZXca0\?autoplay=0&start=4708/);
 await page.goto(base+prefix+'/future-guide/software-judgment?embed=1&__qa=1');assert.equal(await page.locator('header').isVisible(),false);assert.equal(await page.locator('#plan').isVisible(),true);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.goto(base+prefix+'/future-guide?__qa=1#notebook');const backupPromise=page.waitForEvent('download');await page.locator('#export-backup').click();const backup=await backupPromise,data=JSON.parse(fs.readFileSync(await backup.path(),'utf8'));assert.equal(data.product,'future-guide');
 const old=await page.evaluate(()=>localStorage.getItem('agi-future-guide-v1'));await page.locator('#import-backup').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":1}')});assert.equal(await page.evaluate(()=>localStorage.getItem('agi-future-guide-v1')),old);
 page.once('dialog',d=>d.accept());await page.locator('#clear-local').click();assert.equal(await page.evaluate(()=>localStorage.getItem('agi-future-guide-v1')),null);
 await page.locator('#import-backup').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.waitForFunction(()=>localStorage.getItem('agi-future-guide-v1')?.includes('Fictional QA task'));assert.equal(await page.locator('#saved-list script').count(),0);
 for(const route of [...claims.map(c=>'/future-guide/'+c.id),'/future-guide/method']){await page.goto(base+prefix+route+'?__qa=1');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,route);assert.ok(await page.locator('h1').textContent());}
 await page.goto(base+prefix+'/future-guide/prototype-together?__qa=1');assert.equal(await page.locator('#load-video').count(),0);await page.waitForFunction(()=>document.body.dataset.ready==='true');await page.locator('#note-action').fill('Review an example');const textExport=page.waitForEvent('download');await page.locator('#export-plan').click();const txt=await textExport;const body=fs.readFileSync(await txt.path(),'utf8');assert.match(body,/latent.space\/p\/airbnb/);assert.ok(!body.includes('youtube.com')&&!body.includes('undefined'));
 await page.goto(base+prefix+'/future-guide/learning-needs-people?__qa=1');assert.equal(await page.locator('#load-video').count(),0);assert.match(await page.locator('.source-note').textContent(),/14/);
 // New home entry must not displace the owner's first-viewport countdown.
 await page.goto(base+(lang==='zh'?'/cn':'/')+'?__qa=1');const countdown=await page.locator('#milestones').boundingBox();assert.ok(countdown.y+countdown.height<844,'countdown in first viewport');assert.equal(await page.locator('.focus-future a').count(),7);
 assert.deepEqual(errors,[]);await ctx.close();console.log(lang+': video-first media tabs, one-click inline video, audio takeaways/playback, topic/search filters, deduplication, URL persistence, collapsed research drawers, daily discovery, pagination, publication order, all reviewed routes, text/audio source exports, needs, search, local judgment, plan persistence, exports, calendar, import validation, real member handoff (no upload), click-only video, responsive pages, embed and home countdown passed.');
}
if(process.env.FUTURE_RENDER_SHARE){for(const lang of ['en','zh']){const page=await browser.newPage({viewport:{width:1200,height:630}});await page.setContent(`<html lang="${lang}"><head><meta charset="utf-8"><style>body{margin:0;padding:65px 76px;background:#f7f7f8;color:#182033;font-family:'Noto Sans SC',sans-serif}small{font-size:25px;color:#002fa7}h1{font-size:65px;line-height:1.3;letter-spacing:-2px;margin:42px 0 30px}p{font-size:27px;color:#586174}footer{border-top:1px solid #c8ccda;padding-top:26px;margin-top:42px;font-size:21px}</style></head><body><small>AGI / ${lang==='zh'?'未来导航':'Future guide'}</small><h1>${lang==='zh'?'看见 AI 的变化，<br>找到你的下一步。':'Understand the shift.<br>Find your next step.'}</h1><p>${lang==='zh'?'原始访谈 · 多方观点 · 我的行动计划':'Original interviews · Different views · My next step'}</p><footer>agiscorecard.com${lang==='zh'?'/zh':''}/future-guide</footer></body></html>`);await page.screenshot({path:path.join(root,'foresight-assets/share-'+lang+'.png')});await page.close();}}
}finally{await browser.close();server.close();}
