import {chromium} from '../../../../tools/revenue-studio/node_modules/playwright/index.mjs';
import {jarvisRoute} from './server.mjs';import {database} from '../create/test-support.mjs';
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';
const root=path.resolve('sites/agiscorecard'),out=process.env.JARVIS_ARTIFACT_DIR||'/tmp';
const env={EVENTS:database(),MEMBER_WATCH_SECRET:'local-browser-fixture',AI:{async run(model,p){const zh=p.messages[0].content.includes('Simplified Chinese');const isPlan=p.messages[0].content.includes('Plan useful');return {response:JSON.stringify(isPlan?{approach:'Compare a small task.',actions:[{tool:'calculate',query:'3*60'}]}:{summary:zh?'每周三小时足够开展一次小规模工作流程实验。':'Three hours can support one small workflow experiment.',findings:[{text:zh?'三小时等于 180 分钟。':'Three hours equals 180 minutes.',sourceIds:['calc-3*60']}],nextActions:[{action:zh?'对比一项周报任务。':'Compare one weekly reporting task.',doneWhen:zh?'记录耗时与错误。':'Record time and errors.'}],uncertainties:[zh?'尚未证明生产力提升。':'Productivity improvement is unproven.']})};}}};
let base;const pending=[];
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,base);if(u.pathname.startsWith('/api/jarvis')){const parts=[];for await(const p of req)parts.push(p);const init={method:req.method,headers:req.headers};if(req.method==='POST')init.body=Buffer.concat(parts);const r=await jarvisRoute(new Request(u,init),env,{waitUntil:p=>pending.push(p)});res.writeHead(r.status,Object.fromEntries(r.headers));return res.end(await r.text());}
 let f=path.resolve(root,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(root+path.sep))return res.writeHead(403).end();if(!path.extname(f))f+='.html';try{res.setHeader('Content-Type',({'.mjs':'text/javascript','.js':'text/javascript','.html':'text/html','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[path.extname(f)]||'text/plain');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}}catch(e){res.writeHead(500).end('fixture server error');}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;
let options={headless:true};if(process.env.JARVIS_CHROMIUM)options={headless:true,executablePath:process.env.JARVIS_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage']};
const browser=await chromium.launch(options);
try{for(const lang of ['en','zh']){if(lang==='zh')env.EVENTS.sqlite.exec('DELETE FROM relay_limits');const ctx=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true}),page=await ctx.newPage(),errors=[],leaks=[];page.on('pageerror',e=>errors.push(e.message));await ctx.route('**/*',r=>{if(!r.request().url().startsWith(base)){leaks.push(r.request().url());return r.abort();}return r.continue();});
 await page.goto(base+(lang==='zh'?'/zh':'')+'/jarvis?__qa=1');await page.waitForFunction(()=>document.body.dataset.ready==='true');assert.equal(await page.locator('#task-list .mission-item').count(),0);assert.deepEqual(leaks,[]);
 await page.screenshot({path:path.join(out,'jarvis-'+lang+'-desktop.png'),fullPage:true});
 await page.locator('#memory-panel summary').click();await page.locator('#memory').fill('I have three hours a week.\n<script>window.attack=1</script>');await page.locator('#save-memory').click();await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');assert.equal(await page.locator('#memory').inputValue(),'I have three hours a week.\n<script>window.attack=1</script>');assert.equal(await page.evaluate(()=>window.attack),undefined);
 await page.locator('[data-example="0"]').click();await page.locator('[data-memory]').first().check();await page.locator('#cloud-consent').check();await page.locator('#cadence').selectOption('daily');await page.locator('#start').click();await page.locator('#task-detail').waitFor();await Promise.all(pending);await page.getByRole('button',{name:lang==='zh'?'刷新':'Refresh',exact:true}).click();await page.locator('.report-summary').waitFor();assert.match(await page.locator('.report-summary').textContent(),lang==='zh'?/三小时/:/Three hours/);
 assert.equal(await page.evaluate(()=>window.attack),undefined);assert.equal(await page.locator('#task-list .mission-item').count(),1);
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:lang==='zh'?'导出结果':'Export result',exact:true}).click();const download=await downloadPromise;const content=fs.readFileSync(await download.path(),'utf8');assert.match(content,/180/);assert.ok(!content.includes('Bearer'));
 await page.getByRole('button',{name:lang==='zh'?'暂停':'Pause',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.status-pill').textContent.match(/Paused|已暂停/));await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='true');await page.locator('.mission-item').click();assert.match(await page.locator('.status-pill').textContent(),/Paused|已暂停/);
 for(const width of [390,360]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'no horizontal overflow '+lang+' '+width);}
 await page.screenshot({path:path.join(out,'jarvis-'+lang+'-mobile.png'),fullPage:true});
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:lang==='zh'?'删除任务':'Delete task',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#task-detail').hidden);assert.equal(await page.locator('.mission-item').count(),0);assert.deepEqual(errors,[]);assert.deepEqual(leaks,[]);await ctx.close();}
console.log('Jarvis browser: EN/ZH create → real local API/SQLite/runner → report → export → pause → reload → delete; editable memory, XSS, private requests and 360px layout verified. Model responses are fixtures, not a live quality evaluation.');
}finally{await Promise.all(pending);await browser.close();server.close();env.EVENTS.sqlite.close();}
