import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {VERSION} from '../../jarvis-assets/core.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url)),origin='https://agiscorecard.com';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
for(const lang of ['en','zh']){
 const zh=lang==='zh',p=zh?'/zh':'',t=(en,cn)=>zh?cn:en,url=origin+p+'/jarvis';
 const title=t('Jarvis — turn an AI goal into a useful next step','贾维斯 — 把 AI 时代的目标推进一步');
 const desc=t('Give Jarvis a research goal. Get source-linked findings, practical next steps and a private task history. Free limited pilot.','交给贾维斯一个研究目标，获得有出处的发现、可检验的行动和私有任务记录。免费限量试用。');
 const faq=[
  [t('What can Jarvis do today?','现在可以做什么？'),t('Research AI work, learning and product ideas using our editorial catalog. With your choice, it can search GitHub and Hacker News metadata. It can calculate, compare findings and draft concrete next steps. It cannot control your computer, access your accounts, send messages or buy things.','可以检索站内 AI 工作、学习与产品观点；经你选择后，可检索 GitHub 和 Hacker News 的公开元数据。支持算术、比较发现与制定下一步。当前不能控制电脑、访问你的账户、发消息或购买商品。')],
  [t('Does it continue when I leave?','关闭网页后会继续吗？'),t('Submitted tasks are stored on the server. A background runner checks the queue every 15 minutes. Daily watch runs up to seven times over seven days; results appear here, with no email or push notifications. You can pause or delete a task.','提交的任务会保存到服务器，后台每 15 分钟检查队列。每日跟踪最多运行 7 次，持续 7 天；结果在这里查看，暂无邮件或推送通知。你可以暂停或删除任务。')],
  [t('What happens when AI is unavailable?','AI 额度不足时怎么办？'),t('You get the matching source pack and an explicit limited status. No preset is passed off as AI output. Each run uses at most two model calls, sharing the existing site allowance of 12 attempts per 24-hour window and 3 per IP window. Failed attempts count too.','保留匹配的资料包，并明确标记受限状态，不把预设文案冒充 AI 输出。每次运行最多调用模型两次，与站点共享现有每 24 小时窗口 12 次、每 IP 窗口 3 次的额度；失败也计数。')],
  [t('Where are my goals and memories stored?','目标与记忆保存在哪里？'),t('Editable memories stay in this browser; only the relevant memories you select are sent with a task. Submitted tasks and their selected context are stored in Cloudflare D1 for 30 days and sent to Workers AI for inference. Enabled public searches send only your explicit public search keywords to GitHub or Hacker News. A secret browser key protects access; clearing browser storage loses access. Do not submit sensitive data. Delete a task to remove it from our active store.','可编辑的记忆保存在本浏览器，只把你勾选的相关记忆随任务发送。提交的目标和所选上下文在 Cloudflare D1 保存 30 天，并发送给 Workers AI 推理。开启公开搜索只会向 GitHub 或 Hacker News 发送你明确填写的公开关键词。本浏览器的秘密访问密钥保护记录；清理浏览器数据会失去访问权限。请勿提交敏感资料。删除任务会移除活动数据库中的记录。')],
  [t('Is this AGI, and is it a paid product?','这是 AGI 吗，需要付费吗？'),t('No AGI capability has been established. This is a free, bounded research-agent pilot. No Jarvis subscription is sold. Existing AGI membership is separate and does not unlock extra model quota. We are testing whether people find these results useful and return with real tasks.','尚未证明具备 AGI 能力。这是免费的、有边界的研究 Agent 试用版，不售卖贾维斯订阅。现有 AGI 会员是独立服务，不增加模型额度。我们正在检验这些成果是否有用，以及用户是否会带着真实任务回来。')]
 ];
 const schema={'@context':'https://schema.org','@graph':[{'@type':'WebApplication',name:'Jarvis',url,description:desc,applicationCategory:'ProductivityApplication',operatingSystem:'Modern web browser',inLanguage:zh?'zh-Hans':'en',offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'AGI Scorecard',item:origin+(zh?'/cn':'/')},{'@type':'ListItem',position:2,name:t('Jarvis','贾维斯'),item:url}]},{'@type':'FAQPage',mainEntity:faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]};
 const html=`<!doctype html><html lang="${zh?'zh-Hans':'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>${title}</title><meta name="description" content="${desc}"><link rel="canonical" href="${url}"><link rel="alternate" hreflang="en" href="${origin}/jarvis"><link rel="alternate" hreflang="zh-Hans" href="${origin}/zh/jarvis"><link rel="alternate" hreflang="x-default" href="${origin}/jarvis"><link rel="alternate" type="text/markdown" href="${url}.md"><meta property="og:title" content="${title}"><meta property="og:description" content="${desc}"><meta property="og:url" content="${url}"><meta property="og:type" content="website"><meta property="og:image" content="${origin}/jarvis-assets/share.svg"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="/jarvis-assets/style.css?v=${VERSION}"><script type="module" src="/jarvis-assets/app.mjs?v=${VERSION}"></script><script type="application/ld+json">${JSON.stringify(schema)}</script></head><body data-lang="${lang}" data-version="${VERSION}">
<a class="skip" href="#main">${t('Skip to workspace','跳到工作台')}</a><header><a class="brand" href="${zh?'/cn':'/'}"><span class="brand-symbol" aria-hidden="true">A</span>AGI Scorecard</a><nav><a href="${p}/future-guide">${t('Future guide','未来导航')}</a><a href="#how">${t('How it works','如何工作')}</a><a href="${zh?'':'/zh'}/jarvis" lang="${zh?'en':'zh-Hans'}">${t('中文','English')}</a></nav></header>
<main id="main"><section class="intro"><div class="agent-name"><span class="signal" aria-hidden="true"></span><span>${t('Jarvis','贾维斯')}</span><span class="pilot">${t('Research pilot','研究试用版')}</span></div><h1>${t('One goal. A useful next step.','一个目标，向前一步。')}</h1><p>${t('Find the evidence, work through the trade-offs, and leave with something you can act on. Your next visit starts where you left off.','找到证据，理清取舍，带走可以执行的下一步。下次回来，从已有进展继续。')}</p></section>
<div class="workspace"><aside class="mission-panel"><div class="panel-heading"><h2>${t('Your missions','我的任务')}</h2><button id="new-task" class="text-button">＋ ${t('New','新建')}</button></div><div id="task-list"><p class="quiet">${t('Your submitted tasks will appear here.','提交的任务会显示在这里。')}</p></div><details id="memory-panel"><summary>${t('What Jarvis should remember','让贾维斯记住')}</summary><p class="quiet">${t('One preference per line, up to 8. Stored on this device. Choose relevant memories before each run.','每行一条偏好，最多 8 条，保存在本机。每次运行前选择要使用的相关记忆。')}</p><label for="memory">${t('My preferences','我的偏好')}</label><textarea id="memory" rows="5" maxlength="2400" placeholder="${t('I have 3 hours a week for experiments.','我每周有 3 小时用于尝试新工具。')}"></textarea><button id="save-memory" class="secondary">${t('Save memories','保存记忆')}</button></details><p class="quiet small">${t('Private browser key • 30-day task history','浏览器私有密钥 · 30 天任务历史')}</p></aside>
<section class="work-panel" aria-label="${t('Mission workspace','任务工作台')}"><div id="compose"><h2>${t('What would you like to move forward?','你想推进什么？')}</h2><div class="starters"><button data-example="0">${t('Find an AI workflow','找到 AI 工作流程')}</button><button data-example="1">${t('Explore a product idea','探索一个产品想法')}</button><button data-example="2">${t('Build a learning plan','制定学习计划')}</button></div><form id="task-form"><label for="goal">${t('Your goal and what a useful result looks like','你的目标，以及怎样的成果才算有用')}</label><textarea id="goal" rows="5" required minlength="8" maxlength="1200" placeholder="${t('I spend two hours preparing a weekly report. Help me find a practical AI workflow and a small test I can run this week.','每周整理工作报告要花两小时。帮我研究可以采用的 AI 工作流程，并设计一个本周能做的小测试。')}"></textarea><div id="selected-memories"></div><div class="form-options"><label for="cadence">${t('Run','执行方式')}<select id="cadence"><option value="once">${t('Once','运行一次')}</option><option value="daily">${t('Daily for 7 days','每天跟踪，持续 7 天')}</option></select></label><label class="check"><input type="checkbox" id="web">${t('Search public GitHub & Hacker News','搜索公开 GitHub 与 Hacker News')}</label></div><label id="public-query-label" for="public-query" hidden>${t('Public search keywords (sent exactly as written)','公开搜索关键词（原样发送给搜索服务）')}<input id="public-query" type="text" maxlength="160" placeholder="AI agents"></label><label class="check consent"><input type="checkbox" id="cloud-consent" required>${t('Run in the cloud using this goal and the memories I selected.','使用此目标与我选中的记忆，在云端执行。')}</label><p class="quiet small">${t('Optional public searches send keywords to those services. Do not include sensitive data.','可选的公开搜索会向相应服务发送关键词，请勿填写敏感资料。')}</p><div class="submit-row"><button type="submit" id="start">${t('Start my mission','开始我的任务')} <span aria-hidden="true">↗</span></button><span class="quiet small">${t('Free pilot · shared AI limits','免费试用 · 共享 AI 额度')}</span></div></form></div>
<div id="task-detail" hidden></div><p id="status" role="status" aria-live="polite"></p></section></div>
<section id="how" class="how"><h2>${t('Progress you can inspect.','每一步，都看得见。')}</h2><ol><li><strong>${t('A clear goal','明确目标')}</strong><p>${t('Bring a real task and choose the context that matters.','带来一项真实任务，选出本次需要的上下文。')}</p></li><li><strong>${t('Work with evidence','依据证据工作')}</strong><p>${t('Jarvis chooses from bounded tools and records what actually ran.','贾维斯从限定工具中选择，并记录实际执行过程。')}</p></li><li><strong>${t('A testable next step','可以检验的下一步')}</strong><p>${t('Read the sources, export the result, and tell us whether it helped.','查阅来源，导出成果，并反馈是否真正有用。')}</p></li></ol><div class="scope"><p>${t('Built for AI work, learning and product research. Current tools return editorial records, public metadata and arithmetic; they do not read entire linked articles or execute your action plan.','适用于 AI 工作、学习与产品研究。当前工具获取编辑记录、公开元数据与算术结果，不读取链接全文，也不会替你执行行动计划。')}</p><a href="${p}/future-guide">${t('Explore the source library','浏览来源库')}</a></div></section>
<section id="faq" class="faq"><h2>${t('Before you hand over a goal','开始之前，了解这些')}</h2>${faq.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</section><section class="subscribe"><p>${t('Follow what changes in the AI era.','持续关注 AI 时代的变化。')}</p><a href="https://agiscorecard.beehiiv.com/subscribe">${t('Subscribe to AGI Scorecard','订阅 AGI Scorecard')}</a></section></main><footer><span>AGI Scorecard · ${t('Jarvis research pilot','贾维斯研究试用版')}</span><a href="/privacy">${t('Privacy','隐私说明（英文）')}</a></footer><noscript><p>${t('JavaScript is needed for the private task workspace. The source library and FAQ remain readable.','私有任务工作台需要 JavaScript；来源库与常见问题仍可阅读。')}</p></noscript></body></html>`;
 fs.mkdirSync(path.join(root,zh?'zh':'.'),{recursive:true});fs.writeFileSync(path.join(root,zh?'zh/jarvis.html':'jarvis.html'),html);
 fs.writeFileSync(path.join(root,zh?'zh/jarvis.md':'jarvis.md'),`# ${title}\n\n${desc}\n\n${url}\n\n`+faq.map(([q,a])=>`## ${q}\n\n${a}\n`).join('\n'));
}
const sm=path.join(root,'sitemap.xml');let s=fs.readFileSync(sm,'utf8');for(const p of ['/jarvis','/zh/jarvis'])if(!s.includes('<loc>'+origin+p+'</loc>'))s=s.replace('</urlset>',`<url><loc>${origin+p}</loc><lastmod>2026-10-03</lastmod></url>\n</urlset>`);fs.writeFileSync(sm,s);
const llms=path.join(root,'llms.txt');let l=fs.readFileSync(llms,'utf8').replace(/\n<!-- jarvis:start -->[\s\S]*?<!-- jarvis:end -->/g,'');l+='\n<!-- jarvis:start -->\n## Jarvis research agent pilot\n- https://agiscorecard.com/jarvis — Free bounded research agent with private tasks, editable device memory, source-linked findings, arithmetic, optional public GitHub/Hacker News metadata search, and seven-day daily watches. Shared model limits; source-pack fallback is explicitly labeled. No established AGI capability, computer control, external messaging, paid AI plan or guaranteed results.\n- https://agiscorecard.com/zh/jarvis — 中文贾维斯研究助手。\n<!-- jarvis:end -->\n';fs.writeFileSync(llms,l);
console.log('Jarvis bilingual pages, sitemap and discovery generated:',VERSION);
