import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {VERSION} from '../../jarvis-assets/core.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url)),origin='https://agiscorecard.com';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
for(const lang of ['en','zh']){
 const zh=lang==='zh',p=zh?'/zh':'',t=(en,cn)=>zh?cn:en,url=origin+p+'/jarvis';
 const title=t('Jarvis — turn an AI goal into a useful next step','贾维斯 — 把 AI 时代的目标推进一步');
 const desc=t('Give Jarvis a research goal. Get source-linked findings, practical next steps and a private task history. Try one task free, then register a free AGI account to continue. Shared usage limits apply.','交给贾维斯一个研究目标，获得有出处的发现、可检验的行动和私有任务记录。先免费试用一次，再注册免费 AGI 账号继续使用，受共享额度限制。');
 const faq=[
  [t('How does the free trial work?','免费试用与注册有什么限制？'),t('Guests can submit one task, then register a free AGI account to continue. A saved task uses the trial even when AI is unavailable. Reading, exporting and deleting its result remain available. An interrupted first run can resume saved work, but a new run or daily watch needs an account. One trial is recorded per browser key; the same IP can start at most one guest trial in 24 hours. This is abuse prevention, not verified identity: shared networks may need to register sooner. Registration uses the existing AGI display name and private login-key backup, with no email, payment or extra model quota.','访客可提交一个任务，之后免费注册 AGI 账号继续。保存任务即占用试用机会，AI 不可用也计数；已有结果仍可查看、导出和删除。首次任务中断可接续已保存步骤，新一轮运行或每日跟踪需要注册。每个浏览器密钥记录一次试用，同 IP 每 24 小时最多开始一次访客试用；这是防滥用措施，并非实名识别，共享网络可能需要提前注册。注册复用 AGI 昵称与私有登录密钥备份，无需邮箱或付款，不增加模型额度。')],
  [t('What can Jarvis do today?','现在可以做什么？'),t('Research AI work, learning and product ideas using our editorial catalog. With your choice, it can search GitHub and Hacker News metadata. It can calculate, compare findings and draft concrete next steps. It cannot control your computer, access your accounts, send messages or buy things.','可以检索站内 AI 工作、学习与产品观点；经你选择后，可检索 GitHub 和 Hacker News 的公开元数据。支持算术、比较发现与制定下一步。当前不能控制电脑、访问你的账户、发消息或购买商品。')],
  [t('Does it continue when I leave?','关闭网页后会继续吗？'),t('Submitted tasks are stored on the server. A background runner checks the queue about every two hours; scheduled checks can be delayed. After free registration, daily watch runs up to seven times over seven days; results appear here, with no email or push notifications. You can pause or delete a task. Resuming an interrupted run reuses saved steps; a model call with an unknown outcome is not silently repeated. The guest trial can finish in the background; further runs need free registration, not a paid membership. Previously paused tasks need an explicit resume.','提交的任务会保存到服务器，后台约每两小时检查队列，调度可能延迟。免费注册后，每日跟踪最多运行 7 次，持续 7 天；结果在这里查看，暂无邮件或推送通知。你可以暂停或删除任务。中断后恢复会复用已保存步骤，结果未知的模型调用不会自动重试。访客试用可在后台完成，后续运行需要免费注册，不要求付费会员；此前暂停的任务需要你主动恢复。')],
  [t('What happens when AI is unavailable?','AI 额度不足时怎么办？'),t('You get the matching source pack and an explicit limited status. No preset is passed off as AI output. A new run gathers evidence with code and uses one synthesis call; an older checkpoint can total two calls. It shares the existing site allowance of 12 attempts per 24-hour window and 3 per IP window. Failed attempts count too.','保留匹配的资料包，并明确标记受限状态，不把预设文案冒充 AI 输出。新任务由代码取证，只调用模型综合一次；旧版检查点续跑累计最多两次。与站点共享现有每 24 小时窗口 12 次、每 IP 窗口 3 次的额度；失败也计数。')],
  [t('Where are my goals and memories stored?','目标与记忆保存在哪里？'),t('Editable memories stay in this browser; only the relevant memories you select are sent with a task. Submitted tasks and their selected context are stored in Cloudflare D1 for 30 days and sent to Workers AI for inference. Enabled public searches send only your explicit public search keywords to GitHub or Hacker News. A private key saved in this browser protects task access; clearing it can lose access. Existing member keys still open their original task history, even after membership expiry. Device memories are separated by workspace. Do not submit sensitive data. Delete a task to remove it from our active store. A separate minimal trial receipt (workspace hash, task identifier and date, without task text) is retained to prevent resetting the trial by deletion or expiry. Network-limit records stop counting after 24 hours and are removed during bounded maintenance. Network digests attached to a task are removed with that task, at deletion or 30-day expiry. Choosing registration and continuation links this browser’s trial history to your account; device memories can move with it. It does not publish tasks to the discussion room.','可编辑的记忆保存在本浏览器，只把你勾选的相关记忆随任务发送。提交的目标和所选上下文在 Cloudflare D1 保存 30 天，并发送给 Workers AI 推理。开启公开搜索只会向 GitHub 或 Hacker News 发送你明确填写的公开关键词。本浏览器保存的私有密钥保护任务访问，清除密钥可能失去访问。原会员密钥仍可打开原任务历史，会员到期也不影响使用。本机记忆按工作区分别保存。请勿提交敏感资料。删除任务会移除活动数据库中的记录。独立的最小试用凭据仅保留工作区摘要、任务编号和日期，不含正文，用于防止删除或到期重置试用。网络限额记录 24 小时后失效，并由有界维护清理。任务附带的网络摘要随任务删除或 30 天到期清理。选择注册并接续时，会将本浏览器试用历史关联到你的账号，本机记忆也可随之迁移；任务不会发布到讨论区。')],
  [t('Is this AGI, and is it a paid product?','这是 AGI 吗，需要付费吗？'),t('No AGI capability has been established. This bounded research-agent pilot is free, with one guest trial followed by free account registration. No paid membership is required. There is no separate Jarvis plan. Shared model and search limits still apply, and availability is not guaranteed. We are testing whether people find these results useful and return with real tasks.','尚未证明具备 AGI 能力。这是有边界的研究 Agent 试用版，提供一次访客免费试用，之后需注册免费账号继续，不要求付费会员。不另售贾维斯套餐，仍受共享模型与检索额度限制，不保证随时可用。我们正在检验这些成果是否有用，以及用户是否会带着真实任务回来。')]
 ];
 const schema={'@context':'https://schema.org','@graph':[{'@type':'WebApplication',name:'Jarvis',url,description:desc,applicationCategory:'ProductivityApplication',operatingSystem:'Modern web browser',inLanguage:zh?'zh-Hans':'en',isAccessibleForFree:true},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'AGI Scorecard',item:origin+(zh?'/cn':'/')},{'@type':'ListItem',position:2,name:t('Jarvis','贾维斯'),item:url}]},{'@type':'FAQPage',mainEntity:faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]};
 const html=`<!doctype html><html lang="${zh?'zh-Hans':'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>${title}</title><meta name="description" content="${desc}"><link rel="canonical" href="${url}"><link rel="alternate" hreflang="en" href="${origin}/jarvis"><link rel="alternate" hreflang="zh-Hans" href="${origin}/zh/jarvis"><link rel="alternate" hreflang="x-default" href="${origin}/jarvis"><link rel="alternate" type="text/markdown" href="${url}.md"><meta property="og:title" content="${title}"><meta property="og:description" content="${desc}"><meta property="og:url" content="${url}"><meta property="og:type" content="website"><meta property="og:image" content="${origin}/jarvis-assets/share.svg"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="/jarvis-assets/style.css?v=${VERSION}"><script type="module" src="/jarvis-assets/app.mjs?v=${VERSION}"></script><script type="application/ld+json">${JSON.stringify(schema)}</script></head><body data-lang="${lang}" data-version="${VERSION}">
<a class="skip" href="#main">${t('Skip to workspace','跳到工作台')}</a><header><a class="brand" href="${zh?'/cn':'/'}"><span class="brand-symbol" aria-hidden="true">A</span>AGI Scorecard</a><nav><a href="${p}/future-guide">${t('Future guide','未来导航')}</a><a href="#how">${t('How it works','如何工作')}</a><a href="${zh?'':'/zh'}/jarvis" lang="${zh?'en':'zh-Hans'}">${t('中文','English')}</a></nav></header>
<main id="main"><section class="intro"><div class="agent-name"><span class="signal" aria-hidden="true"></span><span>${t('Jarvis','贾维斯')}</span><span class="pilot">${t('Research pilot','研究试用版')}</span></div><h1>${t('One goal. A useful next step.','一个目标，向前一步。')}</h1><p>${t('Find the evidence, work through the trade-offs, and leave with something you can act on. Your next visit starts where you left off.','找到证据，理清取舍，带走可以执行的下一步。下次回来，从已有进展继续。')}</p></section>
<section id="member-gate" class="member-gate" aria-labelledby="member-title"><h2 id="member-title">${t('Your private workspace','你的私有工作区')}</h2><p>${t('Try one task free, then register to continue. A private browser key keeps your tasks separate.','先免费试用一个任务，再注册继续。浏览器私有密钥让你的任务与他人隔离。')}</p><button id="continue-free" type="button">${t('Continue free in this browser','使用本浏览器免费继续')}</button><p><a id="gate-register" href="${p}/discuss/account?from=jarvis">${t('Register or sign in free','免费注册或登录')}</a></p><details><summary>${t('Restore another workspace (optional)','恢复其他工作区（可选）')}</summary><form id="member-form"><label for="member-key">${t('Saved private key or existing AGI member key','已保存的私有密钥或原 AGI 会员密钥')}</label><input id="member-key" type="password" autocomplete="off" spellcheck="false" required pattern="[a-f0-9]{64}" minlength="64" maxlength="64"><button id="member-login" type="submit">${t('Open saved workspace','打开已保存的工作区')}</button></form></details><p id="member-status" role="status" aria-live="polite"></p></section><div id="member-bar" class="member-bar" hidden><span id="member-until"></span><button id="restore-workspace" class="text-button">${t('Switch workspace','切换工作区')}</button><a id="member-open" href="${p}/discuss/account?from=jarvis">${t('Register / sign in free','免费注册 / 登录')}</a><button id="member-logout" class="text-button" type="button">${t('Sign out','退出')}</button></div><section id="trial-notice" class="notice trial-notice" hidden aria-label="${t('Free trial','免费试用')}"><p id="trial-message"></p><a id="register-open" href="${p}/discuss/account?from=jarvis">${t('Register free and continue these tasks','免费注册并接续这些任务')}</a></section><div id="workspace" class="workspace" hidden><aside class="mission-panel"><div class="panel-heading"><h2>${t('Your missions','我的任务')}</h2><button id="new-task" class="text-button">＋ ${t('New','新建')}</button></div><div id="task-list"><p class="quiet">${t('Your submitted tasks will appear here.','提交的任务会显示在这里。')}</p></div><details id="memory-panel"><summary>${t('What Jarvis should remember','让贾维斯记住')}</summary><p class="quiet">${t('One preference per line, up to 8. Stored on this device. Choose relevant memories before each run.','每行一条偏好，最多 8 条，保存在本机。每次运行前选择要使用的相关记忆。')}</p><label for="memory">${t('My preferences','我的偏好')}</label><textarea id="memory" rows="5" maxlength="2400" placeholder="${t('I have 3 hours a week for experiments.','我每周有 3 小时用于尝试新工具。')}"></textarea><button id="save-memory" class="secondary">${t('Save memories','保存记忆')}</button></details><p class="quiet small">${t('1 guest trial • 30-day task history','访客试用一次 · 30 天任务历史')}</p></aside>
<section class="work-panel" aria-label="${t('Mission workspace','任务工作台')}"><div id="compose"><h2>${t('What would you like to move forward?','你想推进什么？')}</h2><div class="starters"><button data-example="0">${t('Find an AI workflow','找到 AI 工作流程')}</button><button data-example="1">${t('Explore a product idea','探索一个产品想法')}</button><button data-example="2">${t('Build a learning plan','制定学习计划')}</button></div><form id="task-form"><label for="goal">${t('Your goal and what a useful result looks like','你的目标，以及怎样的成果才算有用')}</label><textarea id="goal" rows="5" required minlength="8" maxlength="1200" placeholder="${t('I spend two hours preparing a weekly report. Help me find a practical AI workflow and a small test I can run this week.','每周整理工作报告要花两小时。帮我研究可以采用的 AI 工作流程，并设计一个本周能做的小测试。')}"></textarea><div id="selected-memories"></div><div class="form-options"><label for="cadence">${t('Run','执行方式')}<select id="cadence"><option value="once">${t('Once','运行一次')}</option><option value="daily">${t('Daily for 7 days','每天跟踪，持续 7 天')}</option></select></label><label class="check"><input type="checkbox" id="web">${t('Search public GitHub & Hacker News','搜索公开 GitHub 与 Hacker News')}</label></div><label id="public-query-label" for="public-query" hidden>${t('Public search keywords (sent exactly as written)','公开搜索关键词（原样发送给搜索服务）')}<input id="public-query" type="text" maxlength="160" placeholder="AI agents"></label><label class="check consent"><input type="checkbox" id="cloud-consent" required>${t('Run in the cloud using this goal and the memories I selected.','使用此目标与我选中的记忆，在云端执行。')}</label><p class="quiet small">${t('Optional public searches send keywords to those services. Do not include sensitive data.','可选的公开搜索会向相应服务发送关键词，请勿填写敏感资料。')}</p><div class="submit-row"><button type="submit" id="start">${t('Start my mission','开始我的任务')} <span aria-hidden="true">↗</span></button><span class="quiet small">${t('1 guest trial · free registration after','访客试用一次 · 之后免费注册')}</span></div></form></div>
<div id="task-detail" hidden></div><p id="status" role="status" aria-live="polite"></p></section></div>
<section id="how" class="how"><h2>${t('Progress you can inspect.','每一步，都看得见。')}</h2><ol><li><strong>${t('A clear goal','明确目标')}</strong><p>${t('Bring a real task and choose the context that matters.','带来一项真实任务，选出本次需要的上下文。')}</p></li><li><strong>${t('Work with evidence','依据证据工作')}</strong><p>${t('Jarvis runs a fixed evidence workflow and records what actually ran.','贾维斯按固定流程取证，并记录实际执行过程。')}</p></li><li><strong>${t('A testable next step','可以检验的下一步')}</strong><p>${t('Read the sources, export the result, or identify what failed and edit a corrected attempt.','查阅来源、导出成果；若结果无用，可指出问题并编辑一次修正尝试。')}</p></li></ol><div class="scope"><p>${t('Built for AI work, learning and product research. Current tools return editorial records, public metadata and arithmetic; they do not read entire linked articles or execute your action plan.','适用于 AI 工作、学习与产品研究。当前工具获取编辑记录、公开元数据与算术结果，不读取链接全文，也不会替你执行行动计划。')}</p><a href="${p}/future-guide">${t('Explore the source library','浏览来源库')}</a></div></section>
<section id="faq" class="faq"><h2>${t('Before you hand over a goal','开始之前，了解这些')}</h2>${faq.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</section><section class="subscribe"><p>${t('Follow what changes in the AI era.','持续关注 AI 时代的变化。')}</p><a href="https://agiscorecard.beehiiv.com/subscribe">${t('Subscribe to AGI Scorecard','订阅 AGI Scorecard')}</a></section></main><footer><span>AGI Scorecard · ${t('Jarvis research pilot','贾维斯研究试用版')}</span><a href="/privacy">${t('Privacy','隐私说明（英文）')}</a></footer><noscript><p>${t('JavaScript is needed for the private task workspace. The source library and FAQ remain readable.','私有任务工作台需要 JavaScript；来源库与常见问题仍可阅读。')}</p></noscript></body></html>`;
 fs.mkdirSync(path.join(root,zh?'zh':'.'),{recursive:true});fs.writeFileSync(path.join(root,zh?'zh/jarvis.html':'jarvis.html'),html);
 fs.writeFileSync(path.join(root,zh?'zh/jarvis.md':'jarvis.md'),`# ${title}\n\n${desc}\n\n${url}\n\n`+faq.map(([q,a])=>`## ${q}\n\n${a}\n`).join('\n'));
}
const sm=path.join(root,'sitemap.xml');let s=fs.readFileSync(sm,'utf8');for(const p of ['/jarvis','/zh/jarvis'])if(!s.includes('<loc>'+origin+p+'</loc>'))s=s.replace('</urlset>',`<url><loc>${origin+p}</loc><lastmod>2026-10-03</lastmod></url>\n</urlset>`);fs.writeFileSync(sm,s);
const llms=path.join(root,'llms.txt');let l=fs.readFileSync(llms,'utf8').replace(/\n<!-- jarvis:start -->[\s\S]*?<!-- jarvis:end -->/g,'');l+='\n<!-- jarvis:start -->\n## Jarvis research agent pilot\n- https://agiscorecard.com/jarvis — Bounded research agent: one free guest task, then free AGI account registration (no paid membership). Private tasks, editable device memory, source-linked findings, arithmetic, optional public GitHub/Hacker News metadata search, and seven-day daily watches after registration. Shared model limits; source-pack fallback is explicitly labeled. No established AGI capability, computer control, external messaging, separate Jarvis plan or guaranteed results.\n- https://agiscorecard.com/zh/jarvis — 中文贾维斯研究助手。\n<!-- jarvis:end -->\n';fs.writeFileSync(llms,l);
console.log('Jarvis bilingual pages, sitemap and discovery generated:',VERSION);
