import test from 'node:test';import assert from 'node:assert/strict';
import {jarvisRoute} from './server.mjs';import {execute,tick} from './engine.mjs';import {ensure} from './store.mjs';import {runTool,boundedJSON} from './sources.mjs';
import {inputOf,calculate,planOf,reportOf,rank,safeURL} from '../../jarvis-assets/core.mjs';import {database} from './test-support.mjs';import {limit,now,hash} from '../create/store.mjs';import {evidencePlan} from './plan.mjs';import {modelOutput} from './model.mjs';import {businessEvent} from '../../../../tools/fleet-analytics/business.mjs';
const key='1'.repeat(64),other='2'.repeat(64),origin='https://agiscorecard.com';
const body=(extra={})=>({action:'create',goal:'Help me research AI agents and convert 3 hours to minutes',lang:'en',cadence:'once',web:false,publicQuery:'AI agents',consent:true,memory:[],nonce:crypto.randomUUID().replaceAll('-',''),...extra});
function env(){return {EVENTS:database(),MEMBER_WATCH_SECRET:'test-only-secret',AI:{async run(){return {response:JSON.stringify({summary:'Start with one measured weekly task.',findings:[{text:'Three hours is 180 minutes.',sourceIds:['calc-3*60']}],nextActions:[{action:'Run a comparison on one weekly report.',doneWhen:'Record time and errors for both attempts.'}],uncertainties:['This does not demonstrate reliable autonomous work.']}),usage:{total_tokens:123}};}}};}
async function call(e,b=null,token=key,extra={}){const r=await jarvisRoute(new Request(origin+(b?'/api/jarvis':'/api/jarvis/tasks'),{method:b?'POST':'GET',headers:{origin,'content-type':'application/json',authorization:'Bearer '+token,'CF-Connecting-IP':'test-ip',...extra},...(b?{body:JSON.stringify(b)}:{})}),e);return {status:r.status,data:await r.json(),headers:r.headers};}
test('bounded input validates language, consent, cadence and memory',()=>{assert.equal(inputOf(body()).lang,'en');for(const x of [{consent:false},{cadence:'forever'},{memory:['x'.repeat(301)]},{nonce:'bad'},{goal:'tiny'},{lang:'unknown'}])assert.throws(()=>inputOf(body(x)));});
test('arithmetic is parsed without eval and rejects code, infinity and excessive nesting',()=>{assert.equal(calculate('(100-20)*3/2').value,120);assert.equal(calculate('20%*100').value,20);for(const s of ['process.exit()','1/0','2**300','1;fetch(1)','('.repeat(17)+'1'+')'.repeat(17),'1 2','..2','1e999'])assert.throws(()=>calculate(s));});
test('model cannot add tools or forge citations',()=>{for(const a of [{tool:'shell',query:'ls'},{tool:'github_search',query:'secret'}])assert.throws(()=>planOf(JSON.stringify({approach:'a',actions:[a]}),false));assert.throws(()=>reportOf(JSON.stringify({summary:'Some result',findings:[{text:'False source',sourceIds:['invented']}],nextActions:[{action:'a',doneWhen:'b'}],uncertainties:['unknown']}),[],'en'));});
test('link and retrieval handling rejects executable links and preserves no-match',()=>{for(const s of ['javascript:alert(1)','http://example.com','https://127.0.0.1/','https://localhost/','https://u:p@example.com','https://[::1]/'])assert.equal(safeURL(s),null);assert.equal(safeURL('https://github.com/a/b'),'https://github.com/a/b');assert.deepEqual(rank('unfindabletoken',[{title:'AI research'}]),[]);});
test('private endpoints reject missing keys, cross-origin writes and unknown owners',async()=>{const e=env();assert.equal((await call(e,body(),'')).status,401);assert.equal((await call(e,body(),key,{origin:'https://evil.example'})).status,403);const c=await call(e,body());assert.equal(c.status,202);assert.equal((await call(e,null,other)).data.tasks.length,0);assert.equal((await call(e,{action:'delete',id:c.data.task.id},other)).status,404);assert.equal(c.headers.get('cache-control'),'no-store');e.EVENTS.sqlite.close();});
test('idempotent submit creates only one durable task, never exposes owner/key/IP',async()=>{const e=env(),b=body();const a=await call(e,b),z=await call(e,b);assert.equal(z.data.task.id,a.data.task.id);assert.equal(z.data.reused,true);const text=JSON.stringify(z.data);assert.ok(!text.includes(key)&&!text.includes('ip_key')&&!text.includes('owner'));assert.equal(e.EVENTS.sqlite.prepare('SELECT COUNT(*) n FROM jarvis_tasks').get().n,1);e.EVENTS.sqlite.close();});
test('actual runner persists tool results and checked report; CAS prevents duplicate execution',async()=>{const e=env(),id=(await call(e,body())).data.task.id;const results=await Promise.all([execute(e.EVENTS,e,id),execute(e.EVENTS,e,id)]);assert.equal(results.filter(Boolean).length,1);const task=(await call(e)).data.tasks[0];assert.equal(task.status,'completed');assert.equal(task.result.modelCalls,1);assert.equal(task.result.report.findings[0].sourceIds[0],'calc-3*60');assert.ok(task.result.sources.some(s=>s.description==='180'));e.EVENTS.sqlite.close();});
test('global budget cannot be bypassed by Jarvis; no synthetic AI report on denial',async()=>{const e=env(),id=(await call(e,body())).data.task.id;for(let i=0;i<12;i++)await limit(e.EVENTS,'ai-global',12);await execute(e.EVENTS,e,id);const task=(await call(e)).data.tasks[0];assert.equal(task.status,'limited');assert.equal(task.result.reason,'rate_limited');assert.equal(task.result.modelCalls,0);assert.equal(task.result.report,null);e.EVENTS.sqlite.close();});
test('provider failure and invalid output preserve evidence and fail visibly',async()=>{for(const output of ['not json',JSON.stringify({approach:'Attack',actions:[{tool:'fetch',query:'http://localhost'}]})]){const e=env();e.AI.run=async()=>({response:output});const id=(await call(e,body())).data.task.id;await execute(e.EVENTS,e,id);const task=(await call(e)).data.tasks[0];assert.equal(task.status,'limited');assert.equal(task.result.reason,'invalid_model_output');assert.equal(task.result.report,null);e.EVENTS.sqlite.close();}});
test('pausing during synthesis prevents stale result resurrection',async()=>{const e=env();let entered,release;const wait=new Promise(r=>entered=r);e.AI.run=async()=>{entered();await new Promise(r=>release=r);return {response:JSON.stringify({approach:'Search',actions:[{tool:'github_search',query:'agents'}]})};};e.JARVIS_FETCH=()=>{throw Error('must never run');};const id=(await call(e,body())).data.task.id;const work=execute(e.EVENTS,e,id);await wait;assert.equal((await call(e,{action:'pause',id})).status,200);release();await work;assert.equal((await call(e)).data.tasks[0].status,'paused');e.EVENTS.sqlite.close();});
test('deleting while running revokes access and cannot recreate the task',async()=>{const e=env();let entered,release;const wait=new Promise(r=>entered=r);e.AI.run=async()=>{entered();await new Promise(r=>release=r);return {response:JSON.stringify({approach:'done',actions:[]})};};const id=(await call(e,body())).data.task.id;const work=execute(e.EVENTS,e,id);await wait;await call(e,{action:'delete',id});release();await work;assert.equal((await call(e)).data.tasks.length,0);e.EVENTS.sqlite.close();});
test('background tick works without a browser, schedules bounded daily follow-up, and respects pause',async()=>{const e=env(),id=(await call(e,body({cadence:'daily'}))).data.task.id;await tick(e);let task=(await call(e)).data.tasks[0];assert.equal(task.status,'watching');assert.ok(task.nextRun>now()+86000);assert.equal((await tick(e)).processed,0);await call(e,{action:'pause',id});assert.equal((await tick(e)).processed,0);e.EVENTS.sqlite.close();});
test('retention purge and expired leases are explicit',async()=>{const e=env(),id=(await call(e,body())).data.task.id;e.EVENTS.sqlite.prepare("UPDATE jarvis_tasks SET status='running',lease_until=0 WHERE id=?").run(id);await tick(e);assert.equal((await call(e)).data.tasks[0].stage,'interrupted');e.EVENTS.sqlite.prepare('UPDATE jarvis_tasks SET expires=0 WHERE id=?').run(id);await tick(e);assert.equal(e.EVENTS.sqlite.prepare('SELECT COUNT(*) n FROM jarvis_tasks').get().n,0);e.EVENTS.sqlite.close();});
test('external search uses fixed hosts, bounded bodies, and refuses redirects',async()=>{let seen;const fetcher=async(url,opts)=>{seen={url:String(url),opts};return Response.json({items:[{id:1,full_name:'a/b',description:'test',html_url:'https://github.com/a/b',stargazers_count:1,updated_at:'2026-10-01'}]});};const rows=await runTool({tool:'github_search',query:'secret-memory'},{web:true,publicQuery:'explicit public words'},fetcher);assert.equal(rows.length,1);assert.equal(new URL(seen.url).hostname,'api.github.com');assert.equal(seen.opts.redirect,'manual');assert.match(new URL(seen.url).searchParams.get('q'),/explicit public words/);assert.ok(!seen.url.includes('secret-memory'));await assert.rejects(()=>runTool({tool:'github_search',query:'a'},{web:false},fetcher));await assert.rejects(()=>boundedJSON('https://example.com',async()=>new Response('x'.repeat(350001))));});
test('GA4 accepts only fixed Jarvis actions and never user content',()=>{assert.deepEqual(businessEvent('agiscorecard.com','/zh/jarvis',{name:'jarvis_report_ready'}),{name:'jarvis_report_ready',tool_id:'jarvis',repeat:true});assert.deepEqual(businessEvent('agiscorecard.com','/jarvis',{name:'jarvis_registration_open'}),{name:'jarvis_registration_open',tool_id:'jarvis',repeat:true});assert.equal(businessEvent('agiscorecard.com','/jarvis',{name:'jarvis_registration_open',key:'PRIVATE'}),null);for(const d of [{name:'jarvis_start',goal:'PRIVATE'},{name:'jarvis_PRIVATE'},{name:'purchase'}])assert.equal(businessEvent('agiscorecard.com','/jarvis',d),null);});
test('HTTP background deadline creates a durable checkpoint and cron resumes without a browser',async()=>{const e=env(),id=(await call(e,body())).data.task.id;await execute(e.EVENTS,e,id,{interactive:true,budgetMs:0});let task=(await call(e)).data.tasks[0];assert.equal(task.status,'queued');assert.equal(task.result.continuation,true);assert.equal(task.result.modelCalls,0);await tick(e);task=(await call(e)).data.tasks[0];assert.equal(task.status,'completed');assert.equal(task.result.modelCalls,1);e.EVENTS.sqlite.close();});
test('a persisted tool checkpoint does not repeat already executed tools or planning calls',async()=>{const e=env(),id=(await call(e,body())).data.task.id;e.AI.run=async()=>({response:JSON.stringify({summary:'A verified arithmetic result.',findings:[{text:'Three hours is 180 minutes.',sourceIds:['calc-3*60']}],nextActions:[{action:'Check a task.',doneWhen:'Record observations.'}],uncertainties:['No real task has been executed.']})});const checkpoint={continuation:true,plan:{approach:'Already planned',actions:[{tool:'calculate',query:'1/0'}]},toolIndex:1,sources:[{id:'calc-3*60',title:'3*60',description:'180'}],modelCalls:1,usage:[null],log:[],checkedAt:new Date().toISOString()};e.EVENTS.sqlite.prepare('UPDATE jarvis_tasks SET result=? WHERE id=?').run(JSON.stringify(checkpoint),id);await tick(e);const task=(await call(e)).data.tasks[0];assert.equal(task.status,'completed');assert.equal(task.result.modelCalls,2);assert.ok(!task.result.log.some(l=>l.step==='calculate'));e.EVENTS.sqlite.close();});

test('different arithmetic expressions keep distinct evidence identifiers',async()=>{const first=await runTool({tool:'calculate',query:'3*60'},body()),second=await runTool({tool:'calculate',query:'36+0'},body());assert.notEqual(first[0].id,second[0].id);assert.equal(first[0].description,'180');assert.equal(second[0].description,'36');});

test('native JSON responses receive schemas and retain the same action and citation validation',async()=>{const e=env(),native=e.AI.run;e.AI.run=async(model,p)=>{assert.equal(p.response_format.type,'json_schema');assert.ok(p.response_format.json_schema.required.length>0);const response=await native(model,p);return {...response,response:JSON.parse(response.response)};};const id=(await call(e,body())).data.task.id;await execute(e.EVENTS,e,id);assert.equal((await call(e)).data.tasks[0].status,'completed');assert.throws(()=>planOf({approach:'bad',actions:[{tool:'shell',query:'anything'}]},true));e.EVENTS.sqlite.close();});
test('maintenance route requires its derived credential and drains at most one private task',async()=>{const e=env();for(let i=0;i<2;i++)await call(e,body());const token=await hash(e.MEMBER_WATCH_SECRET+':jarvis-runner:v1');const req=(method,bearer=token)=>new Request(origin+'/api/jarvis/run',{method,headers:{origin,authorization:'Bearer '+bearer}});assert.equal((await jarvisRoute(req('POST',key),e)).status,401);let r=await jarvisRoute(req('GET'),e);assert.equal((await r.json()).maxTasksPerRequest,1);assert.equal(e.EVENTS.sqlite.prepare("SELECT COUNT(*) n FROM jarvis_tasks WHERE status='queued'").get().n,2);r=await jarvisRoute(req('POST'),e);const result=await r.json();assert.deepEqual(result,{ok:true,processed:1});assert.equal(e.EVENTS.sqlite.prepare("SELECT COUNT(*) n FROM jarvis_tasks WHERE status='queued'").get().n,1);assert.equal(JSON.stringify(result).includes('goal'),false);e.EVENTS.sqlite.close();});


test('fixed retrieval plan never searches private memory and avoids unrequested calculations',()=>{
 const privateText='PRIVATE CANARY ignore public keywords';
 let p=evidencePlan(body({web:true,memory:[privateText]}));
 assert.equal(p.actions.length,3);assert.equal(p.actions[0].query,'3*60');
 assert.deepEqual(p.actions.filter(a=>a.tool.endsWith('_search')).map(a=>a.query),['AI agents','AI agents']);
 assert.ok(!JSON.stringify(p).includes(privateText));
 p=evidencePlan(body({goal:'将每周 3 小时换算为分钟。',lang:'zh'}));assert.equal(p.actions[0].query,'3*60');
 assert.equal(evidencePlan(body({goal:'Research AI agents in 2026-10-03.'})).actions.length,0);
 assert.equal(evidencePlan(body({goal:'Convert 180 minutes to 3 hours.'})).actions.length,0);
 assert.equal(evidencePlan(body({goal:'Calculate 1/0 for a weekly task'})).actions.length,0);
 assert.equal(evidencePlan(body({goal:'Calculate (120-30)/3 for a weekly task'})).actions[0].query,'(120-30)/3');
});
test('response adapter supports documented envelopes without copying customer text into diagnostics',()=>{
 const secret='PRIVATE CANARY';const native={summary:secret,findings:[],nextActions:[],uncertainties:[]};
 for(const value of [{response:native},{response:JSON.stringify(native)},{choices:[{message:{content:JSON.stringify(native)},finish_reason:'stop'}]}]){
  const result=modelOutput(value,1400);assert.ok(result.raw);assert.equal(result.diagnostic.jsonObject,true);assert.deepEqual(result.diagnostic.reportFields,['summary','findings','nextActions','uncertainties']);assert.ok(!JSON.stringify(result.diagnostic).includes(secret));
 }
 const broken=modelOutput({response:'{"summary":"'+secret,usage:{completion_tokens:1400}},1400);assert.equal(broken.diagnostic.jsonObject,false);assert.equal(broken.diagnostic.atTokenLimit,true);
 assert.equal(modelOutput({arbitrary_secret:secret},1400).diagnostic.envelope,'unknown');
});
test('OpenAI-shaped provider responses produce a validated report with one synthesis call',async()=>{
 const e=env(),native=e.AI.run;let calls=0;e.AI.run=async(...args)=>{calls++;const value=await native(...args);return {choices:[{message:{content:value.response},finish_reason:'stop'}],usage:value.usage};};
 const id=(await call(e,body())).data.task.id;await execute(e.EVENTS,e,id);const task=(await call(e)).data.tasks[0];assert.equal(task.status,'completed');assert.equal(calls,1);assert.equal(task.result.diagnostics[0].envelope,'choices');e.EVENTS.sqlite.close();
});
test('pausing inside the first public tool prevents later tools and inference',async()=>{
 const e=env();let entered,release,fetches=0,modelCalls=0;const wait=new Promise(r=>entered=r);
 e.JARVIS_FETCH=async()=>{fetches++;entered();await new Promise(r=>release=r);return Response.json({items:[]});};e.AI.run=async()=>{modelCalls++;throw Error('must not infer');};
 const id=(await call(e,body({web:true}))).data.task.id;const work=execute(e.EVENTS,e,id);await wait;await call(e,{action:'pause',id});release();await work;
 assert.equal(fetches,1);assert.equal(modelCalls,0);assert.equal((await call(e)).data.tasks[0].status,'paused');e.EVENTS.sqlite.close();
});


test('manual redirect handling rejects every redirect without following it',async()=>{
 let calls=0;await assert.rejects(()=>boundedJSON('https://api.github.com/search/repositories',async(_url,opts)=>{calls++;assert.equal(opts.redirect,'manual');return new Response('',{status:302,headers:{location:'https://example.com/private'}});}),/source_redirect_blocked/);assert.equal(calls,1);
});
test('missing requested public evidence blocks synthesis even with matching catalog records',async()=>{
 const e=env();let calls=0;e.AI.run=async()=>{calls++;throw Error('must not synthesize');};e.JARVIS_FETCH=async()=>new Response('',{status:503});
 const id=(await call(e,body({web:true,goal:'Compare GitHub AI agents and convert 3 hours to minutes'}))).data.task.id;await execute(e.EVENTS,e,id);const task=(await call(e)).data.tasks[0];assert.equal(task.status,'limited');assert.equal(task.result.reason,'evidence_unavailable');assert.equal(task.result.report,null);assert.equal(calls,0);assert.ok(task.result.sources.some(s=>s.id==='calc-3*60'));assert.ok(task.result.log.some(l=>l.outcome.includes('source_http_503')));e.EVENTS.sqlite.close();
});
test('authenticated source health check uses fixed public words, no customer data or inference',async()=>{
 const e=env();let calls=0;e.AI.run=async()=>{throw Error('must not infer');};e.JARVIS_FETCH=async(url)=>{calls++;assert.ok(String(url).includes('AI+agents'));return Response.json(String(url).includes('api.github')?{items:[{id:1,full_name:'test/agent',description:'fixture',html_url:'https://github.com/test/agent'}]}:{hits:[{objectID:'1',title:'fixture'}]});};
 const token=await hash(e.MEMBER_WATCH_SECRET+':jarvis-runner:v1');const response=await jarvisRoute(new Request(origin+'/api/jarvis/run',{method:'POST',headers:{origin,authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify({action:'verify_sources'})}),e);const result=await response.json();assert.equal(result.modelCalls,0);assert.equal(calls,2);assert.ok(result.checks.every(c=>c.ok));assert.ok(!JSON.stringify(result).includes('fixture'));assert.equal(e.EVENTS.sqlite.prepare('SELECT COUNT(*) n FROM jarvis_tasks').get().n,0);e.EVENTS.sqlite.close();
});

// Frozen recovery cases (2026-10-04): synthetic SQLite/provider fixtures only.
const recoveryCheckpoint=()=>({version:'jarvis-20261003-6',continuation:false,plan:{approach:'Saved evidence',actions:[{tool:'calculate',query:'1/0'}]},toolIndex:1,sources:[{id:'calc-3*60',title:'3*60',description:'180',kind:'calculation'}],modelCalls:0,usage:[],log:[],checkedAt:'2026-10-03T12:00:00Z',report:null,reason:null});
for(const stage of ['paused','interrupted'])test(`resume ${stage} keeps completed tools instead of starting over`,async()=>{const e=env(),id=(await call(e,body())).data.task.id;const cp=recoveryCheckpoint();e.EVENTS.sqlite.prepare('UPDATE jarvis_tasks SET status=?,stage=?,result=? WHERE id=?').run(stage==='paused'?'paused':'limited',stage,JSON.stringify(cp),id);assert.equal((await call(e,{action:'resume',id})).status,202);await execute(e.EVENTS,e,id);const task=(await call(e)).data.tasks[0];assert.equal(task.status,'completed');assert.equal(task.result.checkedAt,cp.checkedAt);assert.equal(task.result.log.some(l=>l.step==='calculate'),false);assert.equal(task.runs,1);e.EVENTS.sqlite.close();});
test('uncertain interrupted inference never silently repeats or resets recorded attempts',async()=>{const e=env(),id=(await call(e,body())).data.task.id;let calls=0;e.AI.run=async()=>{calls++;throw Error('must not repeat');};const cp={...recoveryCheckpoint(),continuation:true,modelCalls:1,synthesisStarted:true};e.EVENTS.sqlite.prepare("UPDATE jarvis_tasks SET status='limited',stage='interrupted',result=? WHERE id=?").run(JSON.stringify(cp),id);await call(e,{action:'resume',id});await execute(e.EVENTS,e,id);const task=(await call(e)).data.tasks[0];assert.equal(calls,0);assert.equal(task.result.modelCalls,1);assert.equal(task.result.reason,'model_interrupted');assert.equal(task.status,'limited');assert.equal(task.runs,1);e.EVENTS.sqlite.close();});
test('a verified report checkpoint finalizes without another inference',async()=>{const e=env(),id=(await call(e,body())).data.task.id;let calls=0;const response=await e.AI.run();e.AI.run=async()=>{calls++;throw Error('must not repeat');};const cp={...recoveryCheckpoint(),continuation:true,modelCalls:1,synthesisStarted:true,report:JSON.parse(response.response)};e.EVENTS.sqlite.prepare("UPDATE jarvis_tasks SET status='limited',stage='interrupted',result=? WHERE id=?").run(JSON.stringify(cp),id);await call(e,{action:'resume',id});await execute(e.EVENTS,e,id);const task=(await call(e)).data.tasks[0];assert.equal(calls,0);assert.equal(task.status,'completed');assert.equal(task.result.continuation,false);assert.equal(task.runs,1);e.EVENTS.sqlite.close();});
test('daily context survives a yielded checkpoint and next occurrence still gets fresh work',async()=>{const e=env(),id=(await call(e,body({cadence:'daily'}))).data.task.id;await execute(e.EVENTS,e,id);const prior=(await call(e)).data.tasks[0].result;let previous;e.AI.run=async(_m,p)=>{previous=JSON.parse(p.messages[1].content).previous_summary;return {response:JSON.stringify(prior.report)};};e.EVENTS.sqlite.prepare('UPDATE jarvis_tasks SET next_run=0 WHERE id=?').run(id);await execute(e.EVENTS,e,id,{interactive:true,budgetMs:0});await execute(e.EVENTS,e,id);const task=(await call(e)).data.tasks[0];assert.equal(previous,prior.report.summary);assert.equal(task.previous.summary,prior.report.summary);assert.equal(task.result.modelCalls,1);assert.equal(task.runs,2);assert.equal(task.result.log.filter(l=>l.step==='calculate').length,1);e.EVENTS.sqlite.close();});
test('pause during a public read reuses the preceding durable tool result and search reservation',async()=>{const e=env(),id=(await call(e,body({web:true,goal:'Research GitHub AI agents using public metadata'}))).data.task.id;let github=0,hn=0;e.JARVIS_FETCH=async url=>{if(String(url).includes('api.github.com')){github++;return Response.json({items:[{id:7,full_name:'fixture/agent',description:'Synthetic metadata',html_url:'https://github.com/fixture/agent'}]});}hn++;if(hn===1)await call(e,{action:'pause',id});return Response.json({hits:[]});};e.AI.run=async()=>({response:{summary:'Only metadata was checked.',findings:[],nextActions:[{action:'Review the project.',doneWhen:'Inspect its tests.'}],uncertainties:['Quality is unverified.']}});await execute(e.EVENTS,e,id);let task=(await call(e)).data.tasks[0];assert.equal(task.status,'paused');assert.equal(task.result.continuation,true);assert.equal(task.result.toolIndex,1);await call(e,{action:'resume',id});await execute(e.EVENTS,e,id);task=(await call(e)).data.tasks[0];assert.equal(task.status,'completed');assert.equal(github,1);assert.equal(hn,2);assert.equal(task.result.modelCalls,1);assert.equal(e.EVENTS.sqlite.prepare("SELECT n FROM relay_limits WHERE k='jarvis-search-global'").get().n,1);e.EVENTS.sqlite.close();});
test('an actual pause during synthesis leaves an attempt marker that recovery will not replay',async()=>{const e=env(),id=(await call(e,body())).data.task.id;let entered,release,calls=0;const ready=new Promise(r=>entered=r),held=new Promise(r=>release=r),original=e.AI.run;e.AI.run=async()=>{calls++;entered();await held;return original();};const work=execute(e.EVENTS,e,id);await ready;await call(e,{action:'pause',id});release();await work;let task=(await call(e)).data.tasks[0];assert.equal(task.result.synthesisStarted,true);assert.equal(task.result.modelCalls,1);assert.equal(task.result.report,null);await call(e,{action:'resume',id});await execute(e.EVENTS,e,id);task=(await call(e)).data.tasks[0];assert.equal(calls,1);assert.equal(task.result.reason,'model_interrupted');assert.equal(task.result.report,null);assert.equal(task.runs,1);e.EVENTS.sqlite.close();});
