import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
import {routes,companies,reviewed,revision,changeLog} from '../../roadmap-assets/catalog.mjs';
import {claims,interviews} from '../../foresight-assets/catalog.mjs';
import {candidates} from '../../roadmap-assets/core.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const discovery=JSON.parse(fs.readFileSync(root+'/foresight-assets/discovery.json','utf8'));
const needed=new Set(routes.flatMap(r=>r.claims));
const views=claims.filter(c=>needed.has(c.id)).map(c=>({id:c.id,summary:{en:c.en.summary,zh:c.zh.summary},speaker:interviews[c.interview].speaker,date:interviews[c.interview].date,url:interviews[c.interview].source,video:interviews[c.interview].video??null,start:c.start??null,limit:{en:c.en.limit,zh:c.zh.limit}}));
for(const id of needed)if(!views.find(c=>c.id===id))throw Error('Unknown claim '+id);
const d={schema_version:1,revision,reviewed_at:reviewed,review_due:'2026-11-03',routes,companies,views,changes:changeLog,discovery:{checked_at:discovery.checkedAt,status:discovery.status,candidates:candidates(discovery,routes,interviews)},limitations:['Stock mappings are editorial hypotheses, not speaker endorsements.','Watch priority is not expected return or a recommendation to buy at the current price.','Discovery is metadata only and cannot change an investment judgment.','Local watchlists do not configure the private owner Telegram channel.']};
d.editorial_hash=crypto.createHash('sha256').update(JSON.stringify({revision,reviewed_at:d.reviewed_at,review_due:d.review_due,routes,companies,views})).digest('hex');
fs.writeFileSync(root+'/roadmap-assets/roadmap.json',JSON.stringify(d,null,2)+'\n');
const e=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
for(const lang of ['en','zh']){
 const zh=lang==='zh',t=(en,cn)=>zh?cn:en,p=zh?'/zh':'',url='https://agiscorecard.com'+p+'/invest';
 const stage={demand:t('Demand evidenced · valuation open','需求有证据 · 估值待核对'),adoption:t('Paid adoption to verify','验证付费采用'),exploration:t('Longer-term research','远期研究观察')};
 const tier={focus:t('Priority research','重点研究'),confirm:t('Wait for confirmation','等待确认'),explore:t('Explore','远期观察')};
 const title=t('AI investment roadmap | Views, evidence & US stocks','AI 投资路线图｜视频观点、产业证据与美股观察');
 const desc=t('Five AI industry routes from reviewed interviews to US-listed watch candidates. Check business evidence, failure conditions, model returns and SunWatch updates in one investment hub.','把已核对的视频观点汇总成五条 AI 产业路线，关联美股、商业证据与失效条件，在同一投资页面查看组合收益和 SunWatch 更新。');
 const link=(href,text,cls='')=>`<a ${cls?`class="${cls}"`:''} href="${e(href)}">${e(text)}</a>`;
 const row=r=>`<section id="route-${r.id}" class="rm-route" data-route="${r.id}" aria-labelledby="route-title-${r.id}"><div class="rm-route-heading"><div><p class="rm-status">${stage[r.maturity]}</p><h3 id="route-title-${r.id}">${e(r.name[lang])}</h3></div><p>${r.tickers.join(' · ')}</p></div><p class="rm-thesis">${e(r.thesis[lang])}</p><div class="rm-chain">${e(r.bottleneck[lang])}</div><div class="rm-conditions"><div><h4>${t('What would strengthen it','什么会加强判断')}</h4><p>${e(r.confirm[lang])}</p></div><div><h4>${t('What would weaken it','什么会推翻判断')}</h4><p>${e(r.invalidate[lang])}</p></div></div><p class="rm-scenario" data-scenario="${r.id}">${e(r.scenarios.base[lang])}</p><details class="rm-sources"><summary>${t('Inspect the original views','展开原始观点')} (${r.claims.length})</summary>${r.claims.map(id=>{const c=views.find(v=>v.id===id);return `<div class="rm-view"><strong>${e(c.speaker)}</strong> <span>${c.date}</span><p>${e(c.summary[lang])}</p><p class="rm-small">${e(c.limit[lang])}</p>${link(p+'/future-guide/'+id,t('Reviewed view','已核对观点'))} · ${link(c.video?'https://www.youtube.com/watch?v='+c.video+(c.start!==null?'&t='+c.start+'s':''):c.url,t(c.video?'Watch source video':'Read original interview',c.video?'打开视频出处':'打开访谈原文'))}</div>`;}).join('')}</details><div class="rm-stock-grid">${r.tickers.map(ticker=>{const c=companies.find(c=>c.ticker===ticker);return `<div class="rm-stock"><div class="rm-stock-top"><h4>${c.ticker} <span>${e(c.name)}</span></h4><span>${tier[c.tier]}</span></div><p>${e(c.role[lang])}</p><p class="rm-small">${e(c.fact[lang])}</p><p><strong>${t('Next check: ','下次核对：')}</strong>${e(c.check[lang])}</p><p class="rm-small">${t('Downside: ','反证：')}${e(c.risk[lang])}</p><p class="rm-small">${e(c.period)} · ${link(c.source,t('Issuer source','公司原始资料'))}</p><button type="button" data-watch="${c.ticker}" aria-pressed="false">${t('Add to local watchlist','加入本机观察')}</button></div>`;}).join('')}</div></section>`;
 const body=`<section class="rm" id="ai-roadmap" data-lang="${lang}"><div class="rm-hero"><p class="rm-kicker">${t('Your investment research, in one place','投资研究，从这里开始')}</p><h1>${t('Follow the AI roadmap.','看清 AI 路线，再研究美股。')}</h1><p class="rm-lead">${t('From expert views to business evidence. See who could benefit, what must happen next, and what would change the thesis.','从大神观点走到产业证据：看谁可能受益、下一步验证什么，以及什么会改变判断。')}</p><p class="rm-small">${t('Editorial review','观点复核')} ${reviewed} · ${t('Next review due','下次复核期限')} ${d.review_due}</p><nav class="rm-subnav" aria-label="${t('Investment sections','投资分区')}"><a href="#route-map">${t('Routes','路线推演')}</a><a href="#rm-watchlist">${t('My watchlist','我的观察')}</a><a href="#rm-returns">${t('12-stock record','12 股追踪')}</a><a href="#rm-monitor">${t('Evidence & alerts','证据与提醒')}</a><a href="#research-workbench">${t('Valuation worksheet','估值工作台')}</a></nav></div>
<div class="rm-verdict"><strong>${t('Research priority: compute and power; confirm software monetization; observe world models.','当前研究顺序：算力与电力优先，软件验证变现，世界模型远期观察。')}</strong><p>${t('A route can succeed while its stocks lose money. These are conditional watch candidates: current valuation, your risk budget and existing exposure still need review. No automatic trades.','产业路线正确，股票仍可能亏损。这里给出有条件的观察标的；当前估值、你的风险预算和已有敞口仍需核对，不自动交易。')}</p><p id="rm-review-status" role="status"></p></div>
<section id="route-map"><div class="rm-section-head"><h2>${t('Five routes, three validation stages','五条路线，三层验证')}</h2><label>${t('Explore a scenario','切换推演情景')}<select id="rm-scenario"><option value="base">${t('Gradual adoption','渐进采用')}</option><option value="fast">${t('Faster deployment','加速部署')}</option><option value="slow">${t('Slower monetization','变现放缓')}</option></select></label></div><p class="rm-small">${t('Stages describe dependencies, not promised dates or assigned probabilities. Routes can develop together.','阶段表示依赖条件，不是承诺发生的年份或预测概率；各路线可能并行发展。')}</p><div class="rm-map">${[0,1,2].map((phase,i)=>`<div class="rm-lane"><h3>${t(['Infrastructure','Paid deployment','Real-world transfer'][i],['基础设施','付费部署','现实迁移'][i])}</h3>${routes.filter(r=>r.phase===phase).map(r=>`<button type="button" data-select-route="${r.id}" aria-pressed="${r.id==='compute'}"><span>${e(r.name[lang])}</span><small>${r.tickers.join(' / ')}</small></button>`).join('')}</div>`).join('')}</div><div id="rm-routes">${routes.map(row).join('')}</div></section>
<section id="rm-watchlist"><h2>${t('Keep only the stocks you want to follow','把想跟踪的股票放到一起')}</h2><p>${t('Add a candidate above. Your selection stays in this browser; it does not alter the fixed 12-stock portfolio or configure Telegram alerts.','点击上方股票的“加入本机观察”。选择仅保存在当前浏览器，不改变固定 12 股组合，也不会设置 Telegram 通知。')}</p><div id="rm-saved"></div><div class="rm-actions"><button id="rm-export" type="button">${t('Export research checklist','导出研究清单')}</button><button id="rm-clear" type="button">${t('Clear local watchlist','清空本机观察')}</button></div><p id="rm-action-status" role="status" aria-live="polite"></p></section>
<section id="rm-returns"><div class="rm-section-head"><h2>${t('Your existing 12-stock experiment','现有 12 股组合追踪')}</h2>${link(p+'/portfolio-tracker',t('Open returns and tools','打开完整收益与工具'))}</div><p id="rm-return-state" role="status">${t('Loading the latest complete published valuation…','正在读取最近完整的已发布估值…')}</p><div id="rm-return-values" class="rm-return-values"></div><p class="rm-small">${t('Fixed October 2, 2026 NY-close entry; equal-weight model, not actual holdings. SPY is an S&P 500 ETF proxy. TQQQ targets daily 3× exposure. The roadmap does not rebalance this record.','固定 2026-10-02 纽约收盘起点；等权模型，不是实际持仓。SPY 是标普 ETF 代理，TQQQ 为每日 3 倍目标。路线图不会重新分配这个组合。')}</p></section>
<section id="rm-monitor"><h2>${t('Evidence that could change the route','哪些新证据可能改变路线')}</h2><div class="rm-monitor-grid"><div><h3>SunWatch</h3><p>${t('The existing private owner channel checks roadmap revisions every 30 minutes. Related company disclosures remain in the disclosure monitor. New video titles are review leads, not investment verdicts.','现有站主私有通道每 30 分钟检查路线修订。相关公司公告继续由披露监控处理；新视频标题只进入待核对队列，不自动变成投资结论。')}</p><p><code>/roadmap</code> · <code>/roadmap_pause</code> · <code>/roadmap_resume</code></p><p class="rm-small">${t('Owner integration only. Public visitors do not receive these alerts by opening the bot or saving a local watchlist.','仅站主专用集成；公开访客打开机器人或本机收藏，不会获得这些提醒。')}</p>${link('https://t.me/sunwatchBot',t('Open SunWatch bot','打开 SunWatch 机器人'),'rm-button')} <p id="rm-alert-state" class="rm-small"></p></div><div><h3>${t('Company announcements','公司公告')}</h3><p>${t('Open original releases, read what changed, then compare the route’s confirmation and failure conditions. Announcement metadata alone does not establish better earnings.','打开原始公告，核对发生了什么，再对照路线的确认与失效条件。公告元数据本身不能证明业绩变好。')}</p>${link('https://invest.agiscorecard.com/'+(zh?'':'en/')+'research',t('Open SunWatch evidence monitor','打开 SunWatch 证据监控'))}<p class="rm-small">${t('NVDA, MU, MSFT, NOW, PANW and GOOGL use the existing company monitor. AVGO, VRT and ETN have direct issuer links here; automatic company-release coverage is not yet connected.','NVDA、MU、MSFT、NOW、PANW、GOOGL 复用现有公司监控；AVGO、VRT、ETN 提供原始公告链接，尚未接通公司公告自动监控。')}</p></div></div><details class="rm-candidates"><summary>${t('New videos to review','新发现、待核对的视频')} (${d.discovery.candidates.length})</summary><p class="rm-small">${t('Matched by title only. No transcript judgment or automatic stock recommendation. Publisher language is retained.','仅按标题匹配，尚未依据正文形成判断，也不自动推荐股票；标题保留发布者原语言。')} ${t('Source check','来源检查')}: ${e(d.discovery.checked_at??'unknown')}</p>${d.discovery.candidates.slice(0,12).map(c=>`<p>${link(c.url,c.title)} <span class="rm-small">${c.published_at.slice(0,10)}</span></p>`).join('')}<p>${link(p+'/future-guide',t('Browse the full video library','查看完整视频库'))}</p></details></section>
<section class="rm-tools"><h2>${t('One route, the right tool for each question','围绕路线使用现有工具')}</h2><div>${[[p+'/ai-infrastructure',t('Check company financial evidence','核对公司财务证据')],[p+'/ai-stock-exposure',t('Inspect AI concentration','检查 AI 敞口')],['https://gushen.agiscorecard.com/'+(zh?'zh':'en')+'/',t('Compare portfolio risk','比较组合风险')],['https://compass.agiscorecard.com/'+(zh?'zh':'en')+'/track-record',t('Inspect historical 13F research','查看历史 13F 研究')],['#research-workbench',t('Test valuation assumptions','测算估值假设')]].map(x=>link(x[0],x[1],'rm-tool-link')).join('')}</div></section>
<details class="rm-method"><summary>${t('Method and revision history','方法与修订记录')}</summary><p>${t('Interview summaries retain attribution and dates. We infer industry dependencies, then link them to issuer evidence and stocks. Speaker agreement is not independent confirmation. Research priority is editorial, not a numerical probability or a forecast return. No price target is fabricated from a video.','访谈摘要保留归属与日期；本站推演产业依赖，再关联公司证据与股票。嘉宾观点相似不等于独立验证。研究优先级是编辑判断，不是数字概率或收益预测，也不从视频虚构目标价。')}</p><p>${t('New video metadata refreshes through the existing daily site job; reviewed theses change only after source review. Failed checks keep their original dates. The owner receives revisions and bounded new-review leads, not automatic buy/sell orders.','新视频元数据随现有站点每日任务刷新；已复核路线仅在核对来源后修订。检查失败保留原日期。站主收到修订与有限的新复核线索，不是自动买卖指令。')}</p>${changeLog.map(x=>`<p>${x.date} · ${x.revision}: ${e(x[lang])}</p>`).join('')}${link('/roadmap-assets/roadmap.json',t('Machine-readable evidence and route map','机器可读的证据与路线图'))}</details><noscript>${t('All routes and evidence remain readable. Enable JavaScript for filtering, local watchlists and the latest return summary.','所有路线和证据仍可阅读；启用 JavaScript 后可切换路线、本机收藏和读取最新收益。')}</noscript></section>`;
 const f=root+p+'/invest.html';let h=fs.readFileSync(f,'utf8');
 h=h.replace(/<title>[\s\S]*?<\/title>/,`<title>${e(title)}</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${e(desc)}">`).replace(/<meta property="og:title" content="[^"]*">/,`<meta property="og:title" content="${e(title)}">`).replace(/<meta property="og:description" content="[^"]*">/,`<meta property="og:description" content="${e(desc)}">`);
 const head=`<!-- roadmap-head:start -->\n<link rel="stylesheet" href="/roadmap-assets/style.css"><script type="module" src="/roadmap-assets/app.mjs"></script>\n<script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'CollectionPage',name:title,url,description:desc,dateModified:reviewed,hasPart:routes.map(r=>({'@type':'CreativeWork',name:r.name[lang],url:url+'#route-'+r.id}))})}</script>\n<!-- roadmap-head:end -->`;
 h=h.includes('<!-- roadmap-head:start -->')?h.replace(/<!-- roadmap-head:start -->[\s\S]*?<!-- roadmap-head:end -->/,()=>head):h.replace('</head>',head+'\n</head>');
 const block='<!-- roadmap-body:start -->\n'+body+'\n<!-- roadmap-body:end -->';
 if(h.includes('<!-- roadmap-body:start -->'))h=h.replace(/<!-- roadmap-body:start -->[\s\S]*?<!-- roadmap-body:end -->/,()=>block);
 else{
  h=h.replace(/<article>([\s\S]*?)<\/article>/,(_,old)=>{
   const work=old.match(/<!-- invest-research-body:start -->[\s\S]*?<!-- invest-research-body:end -->/)?.[0]??'';
   const archive=old.replace(work,'').replace(/<h1>/g,'<h2>').replace(/<\/h1>/g,'</h2>');
   return '<article>'+block+'\n'+work+'\n<details id="invest-archive"><summary>'+t('Historical investor holdings and background','历史投资人持仓与背景资料')+'</summary>'+archive+'</details></article>';
  });
 }
 fs.writeFileSync(f,h);
}
console.log('Built investment hub: 5 routes, 9 stocks, '+views.length+' sourced views; homepage untouched');
