#!/usr/bin/env python3
from pathlib import Path
import html,json
ROOT=Path(__file__).resolve().parents[2]
for zh in (False,True):
 def t(en,cn):return cn if zh else en
 lang='zh' if zh else 'en';prefix='/zh' if zh else ''
 title=t('AI infrastructure research','AI 算力产业链研究')
 desc=t('Compare annual SEC financial facts across twenty AI infrastructure companies. Trace each number, keep a falsifiable thesis and revisit changes.','核对 20 家 AI 产业链公司的 SEC 年度财务数据，追溯每个数字，记录可证伪假设并复查变化。')
 url='https://agiscorecard.com'+prefix+'/ai-infrastructure'
 schema=[{'@context':'https://schema.org','@type':'WebApplication','name':title,'url':url,'applicationCategory':'FinanceApplication','operatingSystem':'Web','isAccessibleForFree':True,'offers':{'@type':'Offer','price':'0','priceCurrency':'USD'},'featureList':['SEC annual financial facts','Source-linked AI research questions with limited availability','Local watchlist and research notes','JSON and Markdown export'],'isPartOf':{'@type':'CollectionPage','url':'https://agiscorecard.com'+prefix+'/ai-tools'}},
 {'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'AGI Scorecard','item':'https://agiscorecard.com/'+('cn' if zh else '')},{'@type':'ListItem','position':2,'name':t('Invest','投资'),'item':'https://agiscorecard.com'+prefix+'/invest'},{'@type':'ListItem','position':3,'name':title,'item':url}]}]
 schemas_html=''.join('<script type="application/ld+json">'+json.dumps(x,ensure_ascii=False)+'</script>' for x in schema)
 fields=''.join(f'<label for="note-{k}">{label}<'+(f'input type="date" id="note-{k}">' if k=='review' else f'textarea id="note-{k}" rows="3" maxlength="2000"></textarea>')+'</label>' for k,label in [('thesis',t('What must be true?','什么条件必须成立？')),('counter',t('Counterevidence or unknowns','反面证据或未知项')),('trigger',t('What would change your mind?','什么会改变你的判断？')),('review',t('Next review date','下次复查日期'))])
 page=f'''<!doctype html>
<html lang="{lang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title} | AGI Scorecard</title><meta name="description" content="{desc}"><link rel="canonical" href="{url}">
<link rel="alternate" hreflang="en" href="https://agiscorecard.com/ai-infrastructure"><link rel="alternate" hreflang="zh-Hans" href="https://agiscorecard.com/zh/ai-infrastructure"><link rel="alternate" hreflang="x-default" href="https://agiscorecard.com/ai-infrastructure">
<meta property="og:title" content="{title}"><meta property="og:description" content="{desc}"><meta property="og:url" content="{url}"><meta property="og:type" content="website">
<script async src="https://www.googletagmanager.com/gtag/js?id=G-FZXLMBB5QB"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments);}}gtag('js',new Date());gtag('config','G-FZXLMBB5QB');</script>
<link rel="stylesheet" href="/infrastructure-assets/style.css"><script type="module" src="/infrastructure-assets/app.mjs"></script>
{schemas_html}</head>
<body data-language="{lang}"><a class="skip" href="#workspace">{t('Skip to research','跳至研究区')}</a>
<header><a class="brand" href="{'/cn' if zh else '/'}">AGI Scorecard <span>/ {t('Invest','投资')}</span></a><nav aria-label="{t('Navigation','导航')}"><a href="{prefix}/invest">{t('Investment hub','投资板块')}</a><a href="{prefix}/members?tool=ai-infrastructure">{t('My workspace','我的工作区')}</a><a id="language" href="{'/ai-infrastructure' if zh else '/zh/ai-infrastructure'}" lang="{'en' if zh else 'zh'}">{'English' if zh else '中文'}</a></nav></header>
<main><section class="intro"><div><p class="eyebrow">{t('AI infrastructure · Evidence notebook','AI 产业链 · 证据笔记')}</p><h1>{t('Follow the investment.<br>Check the evidence.','AI 的增长，<br>落到哪张财报？')}</h1><p class="lede">{desc}</p></div><aside><b>20</b><span>{t('companies · six business layers','家公司 · 六个业务层')}</span><p>{t('Annual company-wide figures. No stock prices or segment-level AI revenue.','年度公司整体口径，不含股价或 AI 分部收入。')}</p><a href="#method">{t('Read the data method','查看数据方法')} ↗</a></aside></section>
<div class="freshness" id="data-status" role="status">{t('Loading dated SEC snapshot…','正在载入带日期的 SEC 数据…')}</div>
<section id="workspace" class="workspace" aria-label="{t('Research workspace','研究工作台')}">
<div class="directory"><h2>{t('Start with a company','从一家公司开始')}</h2><label for="search">{t('Company or ticker','公司或股票代码')}</label><input id="search" type="search" placeholder="NVIDIA, MU, Microsoft…" autocomplete="off"><label for="layer">{t('Business layer','业务层')}</label><select id="layer"><option value="all">{t('All layers','全部业务层')}</option></select><label class="check"><input id="watched-only" type="checkbox">{t('Only my watchlist','只看我的关注列表')}</label><p class="small" id="company-count"></p><div class="company-list" id="companies" aria-label="{t('Companies','公司列表')}"></div><p class="small">{t('Editorial coverage, not a ranking. Watch at least two to compare. Stars are stored only when you save.','编辑选取的覆盖范围，不是排名。关注至少两家可并排比较。关注标记需点击保存才会保留。')}</p></div>
<div class="research"><div class="company-heading"><div><p class="eyebrow" id="company-layer"></p><h2 id="company-name">—</h2></div><button id="watch" type="button" aria-pressed="false">☆ {t('Watch','关注')}</button></div><p class="small" id="company-date"></p><p id="changes" class="notice" hidden></p>
<div class="scroll"><table><caption>{t('Company-wide financial facts · USD billions','公司整体财务数据 · 十亿美元 USD')}</caption><thead><tr><th scope="col">{t('Metric / source','指标 / 来源')}</th><th scope="col">{t('Value','数值')}</th><th scope="col">{t('Period / filed','期间 / 披露')}</th></tr></thead><tbody id="facts"></tbody></table></div>
<p class="small">{t('Fiscal calendars differ across companies. Missing standard tags stay missing. Cash property capex excludes finance leases and acquisitions; inventory is a point-in-time balance.','公司财年各不相同。未找到标准标签的指标留空。固定资产现金支出不含融资租赁与收购；存货为时点余额。')}</p>
<section class="ai-review" aria-labelledby="ai-title"><h3 id="ai-title">{t('What should I challenge next?','接下来，应该质疑什么？')}</h3><p>{t('AI turns these public facts into source-linked research questions. Questions are unverified hypotheses; original filings remain the authority.','AI 根据这些公开数据提出带来源的研究问题。问题是待核实假设，结论仍需回到原始文件检查。')}</p><label class="check"><input type="checkbox" id="ai-consent">{t('Use the hosted AI model on this company’s public facts. My notes are not sent.','同意调用托管 AI 模型处理该公司的公开数据；不会发送我的笔记。')}</label><div class="actions"><button class="primary" id="ai-run" type="button">{t('Generate research questions','生成研究问题')}</button><span id="ai-status" role="status" aria-live="polite"></span></div><div id="ai-result"></div><p class="small">{t('Free beta: at most two attempts per IP window and twelve sitewide, each over twenty-four hours. Failed requests use quota. Membership does not increase AI limits.','免费试用：每个 IP 的 24 小时计数窗口最多 2 次，全站最多 12 次；失败调用也计入。会员不增加 AI 额度。')}</p></section>
<section class="notebook"><h3>{t('Write a thesis you can revisit','写下可复查的判断')}</h3><p class="small">{t('Notes stay in this tab until you choose local or cloud saving. No automatic notifications are sent.','笔记在主动保存前仅保留在当前标签页，不会发送自动提醒。')}</p><div class="note-fields">{fields}</div><div class="actions"><button id="baseline" type="button">{t('Mark these facts reviewed','将这些数据标记为已复查')}</button><a href="{prefix}/invest#research-workbench">{t('Test valuation assumptions','测算估值假设')} ↗</a></div><p id="review-status" class="small"></p></section></div></section>
<section class="comparison" id="comparison" hidden><h2>{t('Compare your watchlist','对照关注公司')}</h2><p class="small">{t('Fiscal year-ends differ. These company-wide values are not a same-calendar-period comparison or a stock ranking. Open any value to read its filing.','各公司财年截至日不同，下表并非相同日历期间的比较或股票排名。点击数值可打开披露原文。')}</p><div class="scroll"><table><thead id="compare-head"></thead><tbody id="compare-body"></tbody></table></div></section>
<section class="save-panel"><div><h2>{t('Keep your work. Revisit the changes.','留下判断，下次核对变化。')}</h2><p>{t('Save a watchlist and notes, then return after a new filing. Changes are compared with your last reviewed values, not with a predicted stock return.','保存关注列表和笔记，待新财报后返回。变化与上次复查的数据比较，不预测股价回报。')}</p></div><div class="actions"><button id="save-local" class="primary" type="button">{t('Save locally','保存到本机')}</button><button id="restore-local" type="button">{t('Restore local copy','恢复本机记录')}</button><button id="export-json" type="button">{t('Export JSON','导出 JSON')}</button><button id="export-md" type="button">{t('Export research brief','导出研究文档')}</button><label class="file-button">{t('Import JSON','导入 JSON')}<input type="file" id="import-json" accept=".json,application/json"></label><button id="erase-local" type="button">{t('Delete local copies','删除本机副本')}</button></div><div class="history-row"><label for="local-history">{t('Local versions (latest ten)','本机历史版本（最近 10 版）')}</label><select id="local-history"><option value="">—</option></select><button type="button" id="restore-version">{t('Restore version','恢复该版')}</button></div><p id="status" class="status" role="status" aria-live="polite"></p></section>
<section class="membership"><div><p class="eyebrow">{t('Continue on another device','换一台设备继续研究')}</p><h2>{t('Cloud workspace','云端研究工作区')}</h2><p>{t('Save your watchlist and thesis versions to your existing AGI Scorecard membership. Fifty workspaces; ten cloud versions per workspace.','使用现有 AGI 记分牌会员保存关注列表和研究版本。50 个工作区，每个保留最近 10 版。')}</p></div><div><p class="price">9 USDT <span>/ {t('30 days','30 天')}</span></p><p class="small">{t('Exact order fraction and network fee are extra. No automatic renewal. Cloud storage is not end-to-end encrypted; AI limits and free data access are unchanged.','另加订单唯一尾数及网络费，不自动续费。云端存储非端到端加密；AI 额度和免费数据访问不变。')}</p><button id="save-cloud" class="primary" type="button">{t('Open cloud save','打开云端保存')}</button><p class="small">{t('Review the record in the member page, then explicitly save. Checkout availability is checked there.','在会员页审阅记录后再主动保存，付款可用性以该页检查为准。')}</p></div></section>
<section id="method"><h2>{t('Know exactly what you are reading','知道你正在读什么')}</h2><div class="method-grid"><div><h3>{t('Primary-source facts','一手来源数据')}</h3><p>{t('SEC companyfacts, standard US GAAP tags, USD, annual periods of roughly one year from Form 10-K and amendments. Metrics must match the latest eligible annual period; older tags are withheld, including inventory. New quarterly results are outside this view.','采用 SEC companyfacts 的 US GAAP 标准标签、USD 币种、10-K 及修订文件中约一年的年度期间。各指标必须匹配最近可用年度期间；过旧标签不展示，存货也须同一年度截至。此视图不包含最新季报。')}</p><p>{t('Later comparative disclosures can change a prior period. We show the latest eligible filing, original disclosure date and a revision flag. A revision flag does not explain its cause. Same-day conflicts are withheld.','后续披露的比较数据可能修改以前的期间。显示最新合格披露、首次披露日期及数值修订标记；标记不说明修订原因。同日有冲突的数值不展示。')}</p></div><div><h3>{t('Freshness and limits','更新时间与限制')}</h3><p>{t('The daily deployment attempts a refresh. Each company retains its own actual check time; failures keep the last good data. A failed refresh or a snapshot older than three days is flagged. Filing dates have day precision, not executable trading timestamps.','每日部署尝试刷新，各公司保留实际核对时间；获取失败时保留上次成功数据。失败或超过三天未核对会显示提示。披露日期只有日期精度，不能当作可交易的时间戳。')}</p><p>{t('These are company-wide facts, not standalone AI revenue, a ranking or personalized investment advice. AI generates questions, not verified conclusions. Sources and calculations may need further reconciliation.','这里是公司整体数据，不是独立 AI 收入、股票排名或个性化投资建议。AI 生成的是问题，不是已核验结论；来源与计算仍需进一步核对。')}</p></div></div><p><a href="https://www.sec.gov/search-filings/edgar-application-programming-interfaces" rel="noopener" target="_blank">SEC EDGAR API ↗</a> · <a href="/infrastructure-assets/snapshot.json">{t('Dated source snapshot (JSON)','带日期的数据快照（JSON）')}</a> · <a href="/privacy">{t('Privacy','隐私')}</a></p><p class="small">{t('AI abuse protection keeps a keyed hash of the request IP with an expiry; no plaintext IP or personal notes are stored by the review endpoint. Local storage is readable by others using this browser.','AI 防滥用计数使用带有效期的 IP 密钥哈希；复核接口不保存明文 IP 或个人笔记。共用浏览器的其他使用者可以读取本机保存。')}</p><details><summary>{t('Embed the free tool','嵌入免费工具')}</summary><pre>{html.escape('<iframe src="'+url+'?embed=1" title="'+title+'" width="100%" height="1000" loading="lazy"></iframe>')}</pre></details></section>
<noscript><p>{t('Enable JavaScript for the interactive workbench. The method and downloadable source snapshot remain available.','互动研究需要 JavaScript；数据方法及可下载来源快照仍可读取。')}</p></noscript></main>
<footer>AGI Scorecard · <a href="{prefix}/invest">{t('Investment research','投资研究')}</a> · <a href="/about">{t('Contact','联系')}</a></footer></body></html>'''
 (ROOT/(('zh/' if zh else '')+'ai-infrastructure.html')).write_text(page)
print('Built bilingual AI infrastructure workbench')
