import {test} from 'node:test';import assert from 'node:assert/strict';
import {auditCSV,parseCSV,serializeCSV,applyResults,checkTranslation,HEADERS} from '../site/core.mjs';
export function csv(overrides={},extra=[]){return serializeCSV(HEADERS,[{Type:'PRODUCT',Identification:'90071992547409931234',Field:'title',Locale:'de',Market:'',Status:'','Default content':'Cedar bottle 750 ml','Translated content':'',...overrides},...extra]);}
test('CSV quoted commas, line breaks, BOM and long IDs round trip exactly',()=>{const text=csv({'Default content':'Cedar, "bottle"\n750 ml'});const doc=parseCSV('\uFEFF'+text);assert.equal(doc.rows[0].Identification,'90071992547409931234');assert.equal(serializeCSV(doc.headers,doc.rows),text);});
test('unsupported HTML and existing translations are never sent for translation',()=>{assert.equal(auditCSV(csv({Field:'body_html'})).eligible,0);assert.equal(auditCSV(csv({'Translated content':'Reviewed text'})).eligible,0);assert.equal(auditCSV(csv({Type:'SHOP_POLICY'})).eligible,0);assert.equal(auditCSV(csv({Locale:'unknown'})).eligible,0);});
test('duplicate keys, missing identities, oversized fields, bad CSV and formulas do not pass silently',()=>{const d=parseCSV(csv());assert.throws(()=>auditCSV(serializeCSV(HEADERS,[d.rows[0],d.rows[0]])),/Duplicate/);assert.throws(()=>auditCSV(csv({Identification:''})),/identity/);assert.equal(auditCSV(csv({'Default content':'x'.repeat(501)})).eligible,0);assert.throws(()=>parseCSV('"unclosed'),/Unclosed/);assert.equal(auditCSV(csv({'Default content':' =IMPORTXML("x")'})).eligible,0);assert.throws(()=>parseCSV(csv()+'a,b'),/columns/);});
test('missing numbers, new numeric claims, missing brand, empty/unsafe output are blocked',()=>{const e=auditCSV(csv(),['Cedar']).entries[0];assert.deepEqual(checkTranslation(e,'Cedar Flasche 750 ml'),[]);for(const s of ['Cedar Flasche','Cedar Flasche 750 ml 100%','Flasche 750 ml','<b>Cedar 750</b>','', '=Cedar 750'])assert.ok(checkTranslation(e,s).length,s);});
test('placeholder is protected and blocked results cannot corrupt exports',()=>{const d=auditCSV(csv({'Default content':'Cedar {{ product.name }} 750 ml'}),['Cedar']);const rows=applyResults(d,[{index:0,status:'accepted',output:'Cedar 750 ml'}]);assert.equal(rows[0]['Translated content'],'');assert.ok(checkTranslation(d.entries[0],'Cedar 750 ml').some(x=>x.includes('{{')));});
test('approved result changes only Translated content; spreadsheet review is a separate file',()=>{const d=auditCSV(csv(),['Cedar']);const rows=applyResults(d,[{index:0,status:'accepted',output:'Cedar Flasche 750 ml'}]);for(const h of HEADERS.filter(x=>x!=='Translated content'))assert.equal(rows[0][h],d.rows[0][h]);assert.match(serializeCSV(['x'],[{x:'=1+1'}],{spreadsheetSafe:true}),/'=1\+1/);assert.doesNotMatch(serializeCSV(['x'],[{x:'=1+1'}]),/'=1/);});
test('protected term and input bounds reject malformed requests',()=>{assert.throws(()=>auditCSV(csv(),['x'.repeat(81)]),/protected/);assert.throws(()=>auditCSV(csv(),[false]),/protected/);assert.throws(()=>parseCSV('x'.repeat(700001)),/700 KB/);});
