import {test} from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import worker,{fulfill,verifySignature,processOne,readiness,provider} from '../src/worker.mjs';
import {auditCSV,serializeCSV,HEADERS} from '../site/core.mjs';
const csv=serializeCSV(HEADERS,[{Type:'PRODUCT',Identification:'123',Field:'title',Locale:'de',Market:'',Status:'','Default content':'Cedar bottle 750 ml','Translated content':''}]);
// Real SQLite exercises the SQL, constraints and atomic batches, not a string-
// matching fake. Cloudflare deployment itself still requires staging verification.
function setup(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../migrations/0001.sql',import.meta.url),'utf8'));const queue=[];const wrap=(sql,args=[])=>({bind(...values){return wrap(sql,values);},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return {meta:db.prepare(sql).run(...args)};}});const env={DB:{prepare:sql=>wrap(sql),async batch(queries){db.exec('BEGIN');try{const r=[];for(const q of queries)r.push(await q.run());db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}},WORK:{async send(v){queue.push(v);}},INPUT_USD_PER_M:'1',OUTPUT_USD_PER_M:'3',JOB_BUDGET_USD:'3'};return {db,env,queue};}
function seed(db,{state='paid',id='12345678-1234-1234-1234-123456789abc',secret='a'.repeat(64)}={}){db.prepare('INSERT INTO jobs(id,token_hash,input,state,created_at,expires_at,session_id) VALUES(?,?,?,?,?,?,?)').run(id,secret,JSON.stringify({csv,glossary:['Cedar']}),state,Date.now(),Date.now()+86400000,'cs_test');db.prepare('INSERT INTO items(job_id,idx) VALUES(?,0)').run(id);return id;}
function session(id,overrides={}){return {id:'cs_test',mode:'payment',payment_status:'paid',currency:'eur',amount_subtotal:1900,amount_total:2261,payment_intent:'pi_test',metadata:{product:'localebatch',job_id:id},...overrides};}
test('missing configuration closes checkout without accepting catalog data or calling providers',async()=>{assert.equal(readiness({}).ready,false);const res=await worker.fetch(new Request('https://test.local/api/jobs',{method:'POST',headers:{Origin:'https://test.local','Content-Type':'application/json'},body:JSON.stringify({csv,consent:true})}),{});assert.equal(res.status,503);});
test('cross-origin mutation is rejected even when payment settings are absent',async()=>{const res=await worker.fetch(new Request('https://test.local/api/jobs',{method:'POST',headers:{Origin:'https://evil.test'}}),{});assert.equal(res.status,403);});
test('unpaid, wrong product/currency/amount/session cannot unlock a batch',async()=>{const {db,env}=setup(),id=seed(db,{state:'awaiting_payment'});for(const delta of [{payment_status:'unpaid'},{currency:'usd'},{amount_subtotal:1},{amount_total:0},{id:'cs_other'},{metadata:{product:'ad',job_id:id}}])assert.equal(await fulfill(env,session(id,delta)),false);assert.equal(db.prepare('SELECT state FROM jobs').get().state,'awaiting_payment');});
test('paid checkout is idempotent; duplicate deliveries do not repeat accepted work',async()=>{const {db,env}=setup(),id=seed(db,{state:'awaiting_payment'});assert.equal(await fulfill(env,session(id)),true);await fulfill(env,session(id));let calls=0;const translate=async()=>{calls++;return {output:'Cedar Flasche 750 ml',cost:.0001};};await processOne(env,id,translate);await processOne(env,id,translate);await processOne(env,id,translate);assert.equal(calls,1);assert.equal(db.prepare('SELECT state FROM jobs').get().state,'completed');});
test('two provider failures consume reservations and stop; no infinite retries',async()=>{const {db,env}=setup(),id=seed(db);let calls=0;const translate=async()=>{calls++;throw Error('timeout');};await processOne(env,id,translate);await processOne(env,id,translate);await processOne(env,id,translate);assert.equal(calls,2);const row=db.prepare('SELECT * FROM items').get();assert.equal(row.attempts,2);assert.equal(row.status,'blocked');assert.ok(db.prepare('SELECT reserved_usd FROM jobs').get().reserved_usd>0);});
test('failed quality checks never become an accepted result',async()=>{const {db,env}=setup(),id=seed(db);for(let i=0;i<3;i++)await processOne(env,id,async()=>({output:'Cedar Flasche',cost:0}));const item=db.prepare('SELECT * FROM items').get();assert.equal(item.status,'blocked');assert.equal(item.output,null);});
test('budget exhaustion blocks before making an upstream call',async()=>{const {db,env}=setup(),id=seed(db);env.JOB_BUDGET_USD='.000001';let calls=0;await processOne(env,id,async()=>{calls++;});assert.equal(calls,0);assert.equal(db.prepare('SELECT status FROM items').get().status,'blocked');});
test('expired lease consumes the interrupted attempt and permits only one further try',async()=>{const {db,env}=setup(),id=seed(db);db.prepare("UPDATE items SET status='running',attempts=1").run();await processOne(env,id,async()=>{throw Error('fail');});assert.equal(db.prepare('SELECT attempts FROM items').get().attempts,2);assert.equal(db.prepare('SELECT status FROM items').get().status,'blocked');});
test('active lease excludes concurrent work; refunds exclude new work',async()=>{const {db,env}=setup(),id=seed(db);db.prepare('UPDATE jobs SET lease_until=?').run(Date.now()+90000);let calls=0;const fn=async()=>{calls++;};assert.equal(await processOne(env,id,fn),'idle');db.prepare("UPDATE jobs SET lease_until=0,refund_state='requested'").run();assert.equal(await processOne(env,id,fn),'idle');assert.equal(calls,0);});
test('signed raw body is required; tampering and stale signatures fail',async()=>{const raw='{"type":"test"}',secret='whsec_test',ts=Math.floor(Date.now()/1000),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(ts+'.'+raw))).toString('hex');const h=`t=${ts},v1=${sig}`;assert.equal(await verifySignature(raw,h,secret),true);assert.equal(await verifySignature(raw+' ',h,secret),false);assert.equal(await verifySignature(raw,h,secret,Date.now()+600000),false);});
test('another recovery key cannot read a paid catalog',async()=>{const {db,env}=setup(),id=seed(db);const res=await worker.fetch(new Request('https://test.local/api/jobs/'+id,{headers:{Authorization:'Bearer '+'b'.repeat(64)}}),env);assert.equal(res.status,404);assert.doesNotMatch(await res.text(),/Cedar/);});
test('live provider adapter uses a fixed host, bounded completion and no tool calls',async()=>{const previous=globalThis.fetch;let captured;globalThis.fetch=async(url,options)=>{captured={url,...JSON.parse(options.body)};return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({translation:'Cedar Flasche 750 ml'})}}],usage:{cost:.0001}}));};try{const {env}=setup();const result=await provider(auditCSV(csv,['Cedar']).entries[0],{...env,OPENROUTER_API_KEY:'test-only',MODEL_ID:'fixture/model'});assert.equal(result.output,'Cedar Flasche 750 ml');assert.equal(captured.url,'https://openrouter.ai/api/v1/chat/completions');assert.equal(captured.max_tokens,768);assert.equal(captured.tools,undefined);assert.equal(captured.provider.allow_fallbacks,false);}finally{globalThis.fetch=previous;}});
test('complete simulated purchase → verified payment → queued delivery → repeated refund',async()=>{
 const {db,env,queue}=setup();Object.assign(env,{SALES_ENABLED:'true',QUALITY_REVIEWED:'true',CLEANUP_ENABLED:'true',STRIPE_SECRET_KEY:'test-only',STRIPE_WEBHOOK_SECRET:'test-only',STRIPE_PRICE_ID:'price_lb',OPENROUTER_API_KEY:'test-only',MODEL_ID:'fixture/model',SITE_ORIGIN:'https://test.local',SUPPORT_EMAIL:'test@example.invalid',SELLER_NAME:'Test fixture',RATE_SALT:'test-only'});
 const original=globalThis.fetch;let createdSession,refundCalls=0;
 globalThis.fetch=async(url,options={})=>{
  if(url.endsWith('/prices/price_lb'))return Response.json({active:true,currency:'eur',unit_amount:1900,type:'one_time',tax_behavior:'exclusive'});
  if(url.endsWith('/checkout/sessions')){const p=new URLSearchParams(options.body);assert.equal(p.get('line_items[0][price]'),'price_lb');assert.equal(p.get('automatic_tax[enabled]'),'true');createdSession=session(p.get('metadata[job_id]'),{url:'https://checkout.stripe.com/c/test',status:'open'});return Response.json(createdSession);}
  if(url.endsWith('/checkout/sessions/cs_test'))return Response.json(createdSession);
  if(url.endsWith('/refunds')){refundCalls++;assert.ok(options.headers['Idempotency-Key']);return Response.json({id:'re_test',status:'succeeded'});}
  throw Error('Unexpected external call: '+url);
 };
 const req=(path,{method='POST',payload,secret}={})=>new Request('https://test.local'+path,{method,headers:{Origin:'https://test.local','Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1',...(secret?{Authorization:'Bearer '+secret}:{})},...(payload?{body:JSON.stringify(payload)}:{})});
 try{
  const created=await worker.fetch(req('/api/jobs',{payload:{csv,glossary:['Cedar'],consent:true,price:1}}),env);assert.equal(created.status,201);const j=await created.json();assert.equal(j.eligible,1);
  const checkout=await worker.fetch(req(`/api/jobs/${j.id}/checkout`,{secret:j.token}),env);assert.equal(checkout.status,200);assert.equal(db.prepare('SELECT state FROM jobs').get().state,'awaiting_payment');
  assert.equal((await worker.fetch(req(`/api/jobs/${j.id}/sync`,{secret:j.token}),env)).status,200);assert.equal(queue.length,1);
  await processOne(env,j.id,async()=>({output:'Cedar Flasche 750 ml',cost:.0001}));await processOne(env,j.id,async()=>{throw Error('No second call');});
  const result=await (await worker.fetch(req(`/api/jobs/${j.id}`,{method:'GET',secret:j.token}),env)).json();assert.equal(result.state,'completed');assert.equal(result.results[0].output,'Cedar Flasche 750 ml');
  for(let i=0;i<2;i++){const r=await worker.fetch(req(`/api/jobs/${j.id}/refund`,{secret:j.token}),env);assert.equal(r.status,200);assert.equal((await r.json()).refund,'succeeded');}
  assert.equal(refundCalls,1);assert.equal(db.prepare('SELECT state FROM jobs').get().state,'refunded');
 }finally{globalThis.fetch=original;}
});
test('queue duplicate during an active lease is retried rather than silently dropped',async()=>{const {db,env}=setup(),id=seed(db);db.prepare('UPDATE jobs SET lease_until=?').run(Date.now()+90000);let retried=false,acked=false;await worker.queue({messages:[{body:{job_id:id},ack(){acked=true;},retry(){retried=true;}}]},env);assert.equal(retried,true);assert.equal(acked,false);});
test('daily cleanup deletes expired catalogs and rate buckets but retains current jobs',async()=>{const {db,env}=setup(),id=seed(db);db.prepare('UPDATE jobs SET expires_at=?').run(Date.now()-1000);db.prepare('INSERT INTO rate_limits VALUES(?,?,?)').run('old',1,0);await worker.scheduled({},env);assert.equal(db.prepare('SELECT count(*) AS n FROM jobs').get().n,0);assert.equal(db.prepare('SELECT count(*) AS n FROM items').get().n,0);assert.equal(db.prepare('SELECT count(*) AS n FROM rate_limits').get().n,0);});
test('missing usage cost remains unknown rather than zero-cost delivery',async()=>{const {db,env}=setup(),id=seed(db);await processOne(env,id,async()=>({output:'Cedar Flasche 750 ml',cost:null}));const row=db.prepare('SELECT * FROM jobs').get();assert.equal(row.cost_unknown_attempts,1);assert.equal(row.observed_usd,0);assert.ok(row.reserved_usd>0);});
