import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import worker from '../worker.mjs';
function environment(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync('migrations/0001.sql','utf8'));const wrap=(sql,args=[])=>({bind(...a){return wrap(sql,a);},async run(){return sqlite.prepare(sql).run(...args);},async first(){return sqlite.prepare(sql).get(...args);},async all(){return {results:sqlite.prepare(sql).all(...args)};}});return {sqlite,DB:{prepare:wrap,exec:async sql=>sqlite.exec(sql),batch:async statements=>{const results=[];for(const s of statements)results.push(await s.run());return results;}},EVENT_LIMIT:{limit:async()=>({success:true})},ASSETS:{fetch:async r=>new Response(new URL(r.url).pathname)}};}
const origin='https://rfqdesk.agiscorecard.com';const data={event:'complete',mode:'qa',source:'direct',session:'12345678-1234-1234-1234-123456789012',consent:true};const req=(d=data,o=origin)=>new Request(origin+'/api/event',{method:'POST',headers:{Origin:o,'Content-Type':'application/json'},body:JSON.stringify(d)});
test('production collector persists once with real SQLite, separating QA',async()=>{const e=environment();for(let i=0;i<2;i++)assert.equal((await worker.fetch(req(),e)).status,200);assert.equal(e.sqlite.prepare('SELECT COUNT(*) AS n FROM venture_events').get().n,1);assert.equal(e.sqlite.prepare("SELECT COUNT(*) AS n FROM venture_events WHERE mode != 'qa'").get().n,0);e.sqlite.close();});
test('collector rejects cross-origin, unconsented, content and oversized payloads',async()=>{const e=environment();assert.equal((await worker.fetch(req(data,'https://example.com'),e)).status,403);for(const d of [{...data,consent:false},{...data,csv:'secret catalog'},{...data,event:'payment'}, {...data,session:'x'.repeat(1000)}])assert.equal((await worker.fetch(req(d),e)).status,400);assert.equal(e.sqlite.prepare('SELECT COUNT(*) AS n FROM venture_events').get().n,0);e.sqlite.close();});
test('missing DB or denied rate never reports recorded success',async()=>{assert.equal((await worker.fetch(req(),{})).status,503);const e=environment();e.EVENT_LIMIT.limit=async()=>({success:false});assert.equal((await worker.fetch(req(),e)).status,429);e.sqlite.close();});
test('host routing serves the right brand and blocks arbitrary assets',async()=>{const e=environment();assert.equal(await(await worker.fetch(new Request(origin+'/guide'),e)).text(),'/rfqdesk/guide.html');assert.equal((await worker.fetch(new Request(origin+'/modelmeter/index.html'),e)).status,404);assert.equal((await worker.fetch(new Request('https://unknown.example/'),e)).status,404);assert.equal((await worker.fetch(new Request(origin+'/guide.html'),e)).headers.get('location'),origin+'/guide');e.sqlite.close();});
test('scheduled retention deletes expired events and keeps recent events',async()=>{const e=environment();e.sqlite.exec("CREATE TABLE existing_site_data (value TEXT); INSERT INTO existing_site_data VALUES ('keep');");await worker.fetch(req(),e);e.sqlite.exec("INSERT INTO venture_events VALUES ('2000-01-01','rfqdesk','visit','own','direct','old')");await worker.scheduled({},e);assert.equal(e.sqlite.prepare('SELECT value FROM existing_site_data').get().value,'keep');assert.equal(e.sqlite.prepare('SELECT COUNT(*) AS n FROM venture_events').get().n,1);e.sqlite.close();});

test('runtime bootstrap creates only its prefixed schema and public pulse excludes QA and identities',async()=>{const e=environment();e.sqlite.exec('DROP TABLE venture_events; CREATE TABLE owner_table (value TEXT); INSERT INTO owner_table VALUES ("keep")'.replace('"keep"',"'keep'"));await worker.fetch(req(),e);await worker.fetch(req({...data,mode:'own'}),e);const r=await worker.fetch(new Request(origin+'/api/pulse'),e);assert.equal(r.status,200);const d=await r.json();assert.equal(d.rows.length,1);assert.equal(d.rows[0].mode,'own');assert.equal(d.rows[0].visit_events,1);assert.equal(JSON.stringify(d).includes(data.session),false);assert.equal(e.sqlite.prepare('SELECT value FROM owner_table').get().value,'keep');e.sqlite.close();});

test('FilingLens uses an additive isolated table and keeps other site measurements intact',async()=>{const e=environment();await worker.fetch(req({...data,mode:'own'}),e);const host='https://filinglens.agiscorecard.com';const r=await worker.fetch(new Request(host+'/api/event',{method:'POST',headers:{Origin:host,'Content-Type':'application/json'},body:JSON.stringify({...data,mode:'own'})}),e);assert.equal(r.status,200);assert.equal(e.sqlite.prepare('SELECT COUNT(*) AS n FROM venture_events').get().n,1);assert.equal(e.sqlite.prepare('SELECT COUNT(*) AS n FROM filinglens_events').get().n,1);const pulse=await(await worker.fetch(new Request(host+'/api/pulse'),e)).json();assert.equal(pulse.site,'filinglens');assert.equal(pulse.rows[0].visit_events,1);assert.equal((await worker.fetch(new Request(origin+'/api/sec-concept?cik=320193&tag=Assets'),e)).status,404);e.sqlite.close();});
