import {cases} from './catalog.mjs';import {parseVideo,quote,safeFilename} from './core.mjs';
const zh=document.body.dataset.lang==='zh',lang=zh?'zh':'en',t=(a,b)=>zh?b:a,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],key='agi-earn-v1';
const status=$('#status');let toast;
function say(s){status.textContent=s;clearTimeout(toast);toast=setTimeout(()=>status.textContent='',7000);}
function read(k,fallback){try{return JSON.parse(localStorage.getItem(key+k))??fallback;}catch{return fallback;}}
function save(k,v){try{localStorage.setItem(key+k,JSON.stringify(v));return true;}catch{say(t('Storage is unavailable. Export a backup instead.','无法使用本地存储，请导出备份。'));return false;}}
function event(action,id=''){if(new URLSearchParams(location.search).get('ci')==='1')return;window.gtag?.('event',action==='calculate'?'calc_use':action==='share'?'challenge_share':'tool_click',{location:'earn_'+action,label:cases.some(c=>c.id===id)?id:''});}
function node(tag,text){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;return el;}
function download(name,value,type){const a=node('a');a.href=URL.createObjectURL(new Blob([value],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
let saved=read(':saved',[]);if(!Array.isArray(saved))saved=[];saved=saved.filter(id=>cases.some(c=>c.id===id));
function buttons(){$$('[data-save]').forEach(b=>{const on=saved.includes(b.dataset.save);b.setAttribute('aria-pressed',String(on));b.textContent=on?t('Saved','已收藏'):t('Save','收藏');});}
$$('[data-save]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.save;const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];if(save(':saved',next)){saved=next;buttons();filter();event('save',id);}}));buttons();
let onlySaved=false;
function filter(){if(!$('#search'))return;const q=$('#search').value.toLowerCase().trim(),category=$('#category').value,platform=$('#platform').value;let count=0;$$('.case-card').forEach(c=>{const visible=(!q||c.dataset.search.includes(q))&&(category==='all'||category===c.dataset.category)&&(platform==='all'||platform===c.dataset.platform)&&(!onlySaved||saved.includes(c.dataset.id));c.hidden=!visible;if(visible)count++;});$('#result-count').textContent=zh?`${count} 个项目（视频与指南分别标注）`:`${count} projects · videos and guides labeled separately`;$('#empty').hidden=count!==0;}
['#search','#category','#platform'].forEach(s=>$(s)?.addEventListener('input',filter));$('#saved-only')?.addEventListener('click',e=>{onlySaved=!onlySaved;e.currentTarget.setAttribute('aria-pressed',String(onlySaved));filter();});filter();
function loadPlayer(container,url){const info=parseVideo(url);if(!info)return say(t('Use a full public YouTube or TikTok video link.','请使用完整的 YouTube 或 TikTok 公开视频链接。'));const iframe=node('iframe');iframe.src=info.embed;iframe.title=t('Original video on ','原视频：')+(info.platform==='youtube'?'YouTube':'TikTok');iframe.allow='encrypted-media; fullscreen; picture-in-picture';iframe.referrerPolicy='strict-origin-when-cross-origin';iframe.allowFullscreen=true;if(info.platform==='tiktok')iframe.classList.add('tiktok-frame');container.replaceChildren(iframe);const note=node('p',t('If playback is unavailable, open the original link below.','如无法播放，请打开下方原站链接。'));note.className='quiet';container.append(note);const a=node('a',t('Open original','打开原视频'));a.href=info.url;a.target='_blank';a.rel='noopener';container.append(a);event('player_request');
 if(info.platform==='tiktok'){const handler=e=>{if(e.source!==iframe.contentWindow||e.origin!=='https://www.tiktok.com'||e.data?.['x-tiktok-player']!==true)return;if(e.data.type==='onPlayerError')note.textContent=t('TikTok could not play this video. Open the original or remove this saved link.','TikTok 无法播放此视频。请查看原站或删除收藏链接。');};window.addEventListener('message',handler);}
}
$$('.load-video').forEach(b=>b.addEventListener('click',()=>loadPlayer(b.parentElement,b.dataset.url)));
if($('#saved-projects')){const host=$('#saved-projects');let count=0;for(const c of cases){const b=read(':project:'+c.id,null);if(b?.schema!=='agi-earn-project-v1'||b.case!==c.id)continue;const a=node('a',c[lang].title);a.href=(zh?'/zh':'')+'/earn/cases/'+c.id+'#project';const row=node('p');row.append(a);host.append(row);count++;}if(!count)host.append(node('p',t('No saved project plans yet. Open a case and choose Save on this device.','尚无保存的项目计划。打开案例后点击“保存到本机”。')));}
let videos=read(':videos',[]);if(!Array.isArray(videos))videos=[];videos=videos.filter(v=>typeof v==='string'&&parseVideo(v)).slice(0,20);
function renderVideos(){const host=$('#private-videos');if(!host)return;host.replaceChildren();if(!videos.length){host.append(node('p',t('No saved links yet.','尚未保存视频链接。')));return;}videos.forEach(url=>{const info=parseVideo(url),item=node('div');item.className='private-video';const a=node('a',(info.platform==='tiktok'?'TikTok '+info.creator:'YouTube')+' / '+info.id);a.href=info.url;a.target='_blank';a.rel='noopener';item.append(a);const bar=node('div');bar.className='actions';const play=node('button',t('Load official player','加载官方播放器')),remove=node('button',t('Remove','移除'));play.type=remove.type='button';const player=node('div');play.onclick=()=>{loadPlayer(player,url);play.hidden=true;};remove.onclick=()=>{const next=videos.filter(v=>v!==url);if(save(':videos',next)){videos=next;renderVideos();}};bar.append(play,remove);item.append(bar,node('p',t('Unreviewed personal reference. Loading shares device/network data with the video platform.','未经编辑核验的私人参考。加载会向视频平台发送设备及网络数据。')),player);host.append(item);});}
renderVideos();$('#video-form')?.addEventListener('submit',e=>{e.preventDefault();const info=parseVideo($('#video-url').value);if(!info)return say(t('Use https://www.tiktok.com/@creator/video/ID or a YouTube video URL. Short links and other hosts are not supported.','请输入完整 TikTok 作者视频地址或 YouTube 视频地址，不支持短跳转及其他网站。'));if(videos.includes(info.url))return say(t('Already saved.','该视频已保存。'));if(videos.length>=20)return say(t('This notebook holds 20 links. Remove one before adding another.','最多保存 20 个链接，请先移除一个。'));if(save(':videos',[info.url,...videos])){videos=[info.url,...videos];$('#video-url').value='';renderVideos();say(t('Saved on this device only.','已仅保存到当前设备。'));}});
$$('[data-event]').forEach(a=>a.addEventListener('click',()=>event(a.dataset.event,$('#project')?.dataset.project)));
const project=$('#project');if(project){const id=project.dataset.project,c=cases.find(c=>c.id===id),d=c[lang],form=$('#project-form');
 const textFields=['buyer','deliverable','test','notes'],numbers=['hours','revisions','rate','tools','fee','margin','price'];
 function values(){const data=Object.fromEntries(new FormData(form));for(let i=0;i<4;i++)data['gate'+i]=form.elements['gate'+i].checked;return data;}
 function normalize(data){if(!data||typeof data!=='object'||Array.isArray(data))throw Error('invalid');const out={};for(const k of textFields){if(typeof data[k]!=='string'||data[k].length>2000)throw Error('invalid');out[k]=data[k];}for(const k of numbers)out[k]=data[k];quote(out);if(!['USD','CNY','EUR','GBP'].includes(data.currency))throw Error('invalid');out.currency=data.currency;for(let i=0;i<4;i++){if(typeof data['gate'+i]!=='boolean')throw Error('invalid');out['gate'+i]=data['gate'+i];}return out;}
 function apply(data){const v=normalize(data);for(const [k,x]of Object.entries(v)){if(k.startsWith('gate'))form.elements[k].checked=x;else form.elements[k].value=x;}renderQuote();}
 function bundle(){return {schema:'agi-earn-project-v1',case:id,language:lang,savedAt:new Date().toISOString(),inputs:normalize(values())};}
 const money=(n,currency)=>new Intl.NumberFormat(zh?'zh-CN':'en-US',{style:'currency',currency}).format(n);
 function renderQuote(){const host=$('#quote-result');host.replaceChildren();const n=[0,1,2,3].filter(i=>form.elements['gate'+i].checked).length;$('#readiness').textContent=zh?`${n}/4 项已自查；不是认证或收入保证。`:`${n}/4 self-checks complete; not certification or an income guarantee.`;try{const v=values(),r=quote(v),title=node('p',t('Price for your target margin','达到目标贡献率的报价')),main=node('div',money(r.target,v.currency));main.className='result-main';const dl=node('dl');for(const [label,value]of [[t('Entered delivery cost','输入的交付成本'),r.cost],[t('Break-even price','盈亏平衡报价'),r.floor],[t('Contribution at your price','拟报价下的贡献额'),r.contribution]]){dl.append(node('dt',label),node('dd',money(value,v.currency)));}if(r.contribution<0)dl.lastElementChild.className='negative';host.append(title,main,dl);}catch{host.append(node('p',t('Enter finite, non-negative values. Fee plus margin must be below 100%.','请输入有效非负数字；费率加目标贡献率必须小于 100%。')));}}
 try{const old=read(':project:'+id,null);if(old?.schema==='agi-earn-project-v1'&&old.case===id)apply(old.inputs);}catch{say(t('Saved data could not be restored. Use a valid backup or start again.','保存的数据无法恢复，请导入有效备份或重新开始。'));}
 renderQuote();let calculated=false;form.addEventListener('input',()=>{renderQuote();if(!calculated){event('calculate',id);calculated=true;}});form.addEventListener('submit',e=>e.preventDefault());
 $('#load-example').onclick=()=>{if(textFields.some(k=>form.elements[k].value)&&!confirm(t('Replace the written fields with this case? Cost inputs stay as entered.','用本案例替换文字字段？成本输入保持不变。')))return;form.elements.buyer.value=d.buyer;form.elements.deliverable.value=d.deliverable;form.elements.test.value=d.test;form.elements.notes.value=d.gate;say(t('Example loaded. Replace it with your own project details.','已填入案例示例，请替换成你的真实项目。'));};
 $('#save-project').onclick=()=>{try{if(save(':project:'+id,bundle())){say(t('Project saved on this device.','项目已保存到当前设备。'));event('project_save',id);}}catch{say(t('Fix the cost inputs before saving.','请先修正成本输入。'));}};
 $('#export-backup').onclick=()=>{try{download(safeFilename(id)+'-backup.json',JSON.stringify(bundle(),null,2),'application/json');event('backup_export',id);}catch{say(t('Fix the cost inputs before exporting.','请先修正成本输入。'));}};
 $('#import-backup').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>30000)throw Error();const data=JSON.parse(await file.text());if(data.schema!=='agi-earn-project-v1'||data.case!==id)throw Error();const input=normalize(data.inputs);if(!confirm(t('Replace the current plan with this backup?','用备份替换当前计划？')))return;apply(input);say(t('Backup loaded. Save explicitly to keep it on this device.','已载入备份；如需保留到本机，请点击保存。'));}catch{say(t('Invalid backup or a different case. Open the matching case before restoring.','备份无效或属于其他案例，请在对应案例中恢复。'));}finally{e.target.value='';}};
 $('#clear-project').onclick=()=>{if(!confirm(t('Delete this plan from this browser and reset the form? Exported files are unchanged.','删除本浏览器中的计划并重置表单？已导出的文件不受影响。')))return;try{localStorage.removeItem(key+':project:'+id);form.reset();renderQuote();say(t('Local plan deleted.','本地计划已删除。'));}catch{say(t('Could not access local storage.','无法访问本地存储。'));}};
 $('#export-plan').onclick=()=>{try{const v=normalize(values()),r=quote(v),unchecked=t('Not completed','未完成'),checked=t('Self-reported complete','自报完成');const text=`# ${d.title}\n\n${t('Original AGI project plan. All prices are your assumptions, not income forecasts.','AGI 原创项目计划。报价均为你的假设，不是营收预测。')}\n\n${t('Source','来源')}: ${c.source}\n${t('Creator','作者')}: ${c.creator}\n${t('Evidence','证据状态')}: ${t('Published source description reviewed; workflow and earnings not independently verified.','已查阅公开来源说明；工作流及营收未独立验证。')}\n\n## ${t('Your brief','你的方案')}\n\n${t('Buyer','买家')}: ${v.buyer||t('Not entered','未填写')}\n\n${t('Delivery','交付')}: ${v.deliverable||t('Not entered','未填写')}\n\n${t('Demand test','需求验证')}: ${v.test||t('Not entered','未填写')}\n\n${t('Notes','备注')}: ${v.notes||t('Not entered','未填写')}\n\n## ${t('Cost assumptions','成本假设')}\n\n${numbers.map(k=>`${form.elements[k].parentElement.childNodes[0].textContent}: ${v[k]}`).join('\n')}\n${t('Currency','币种')}: ${v.currency}\n\n${t('Delivery cost','交付成本')}: ${money(r.cost,v.currency)}\n${t('Break-even price','盈亏平衡报价')}: ${money(r.floor,v.currency)}\n${t('Target quote','目标报价')}: ${money(r.target,v.currency)}\n${t('Contribution at entered quote','输入报价下的贡献额')}: ${money(r.contribution,v.currency)}\n${t('Excludes tax and overhead you did not enter.','不含税及未输入的管理费用。')}\n\n## ${t('Delivery checklist','交付检查')}\n\n${d.steps.map(s=>'- [ ] '+s).join('\n')}\n\n${[0,1,2,3].map(i=>`- ${form.elements['gate'+i].parentElement.textContent}: ${v['gate'+i]?checked:unchecked}`).join('\n')}\n\n${t('Acceptance gate','验收门槛')}: ${d.gate}\n\n${originLink()}\n`;download(safeFilename(id)+'-plan-'+lang+'.md',text,'text/markdown;charset=utf-8');event('plan_export',id);say(t('Plan downloaded. An export is not evidence of a completed project.','计划已下载。导出不代表项目已完成。'));}catch{say(t('Fix the cost inputs before exporting.','请先修正成本输入。'));}};
 function originLink(){return 'https://agiscorecard.com'+(zh?'/zh':'')+'/earn/cases/'+id;}
 async function copy(text){try{await navigator.clipboard.writeText(text);say(t('Copied.','已复制。'));return true;}catch{prompt(t('Copy this text:','请复制以下内容：'),text);return false;}}
 $('#share').onclick=async()=>{const url=originLink();if(navigator.share){try{await navigator.share({title:d.title,url});event('share',id);}catch(e){if(e.name!=='AbortError')await copy(url);}}else if(await copy(url))event('share',id);};
 $('#copy-embed').onclick=async()=>{if(await copy($('.embed-code').textContent))event('embed_copy',id);};
 if(new URLSearchParams(location.search).get('embed')==='1'){document.body.classList.add('embed');const a=node('a',t('Free project planner by AGI Scorecard','AGI Scorecard 免费项目规划器'));a.href=originLink();a.target='_blank';a.rel='noopener';a.className='embed-brand';project.prepend(a);}
}
