// Editorial sources, not scraped transcripts. No earnings or playback claims.
import {extraCases} from './extra-cases.mjs';
export const reviewed='2026-09-30';
export const cases=[
...extraCases,
{id:'clip-service',category:'video',platform:'youtube',video:'Dk1TxDKzb68',creator:'Kevin Stratvert / David DeWinter',source:'https://kevinstratvert.com/2024/07/31/descript-tutorial-master-ai-video-editing-in-15-minutes/',original:'Descript Tutorial: Master AI Video Editing in 15 Minutes!',tool:'https://www.descript.com/',level:'beginner',
en:{title:'Turn one client recording into three useful clips',summary:'Learn the editing workflow, then scope a small repurposing service around material the client already owns.',buyer:'A consultant or podcast team with existing recordings and no regular editing capacity.',deliverable:'Three captioned vertical clips, one revision round and a source-to-clip timecode sheet.',edge:'Select a complete idea and preserve its context. Automatic highlight selection alone is not the service.',risk:'The client may already have a capable editor. Revisions, caption correction and finding usable moments can consume the margin.',test:'Prepare one permissioned sample. Ask a relevant buyer whether they would pay for the defined three-clip delivery, and record the reason if not.',steps:['Confirm rights to the source, speakers, music and distribution channels.','Choose three self-contained ideas and record their source timecodes.','Edit the clips; check names, subtitles, framing and audio on a phone.','Agree revision limits and deliver exports with the source mapping.'],gate:'Pass only when all three clips preserve the meaning and the buyer accepts the scope. Views are not evidence of a sale.'},
zh:{title:'把客户的一段长视频做成三条有用的短片',summary:'从剪辑教程出发，为已有素材的客户设计一个范围清楚的小型交付服务。',buyer:'手里已有录制素材、缺少固定剪辑能力的顾问或播客团队。',deliverable:'三条带字幕的竖屏短片、一轮修改、原片与成片时间码对照表。',edge:'选择完整观点并保留上下文；自动截取精彩片段只是制作环节。',risk:'客户可能已有剪辑人员。找片段、修字幕和反复修改，都会吃掉利润。',test:'用获准素材做一个样片，向匹配的买家核实是否愿为约定的三条交付付费，并记录拒绝原因。',steps:['确认原片、人物、音乐和发布渠道的使用权。','选三个可独立理解的观点，记录原片时间码。','剪辑后在手机上检查专名、字幕、构图与声音。','约定修改上限，交付成片和时间码对照表。'],gate:'三条短片不歪曲原意，买家接受交付范围后才进入下一步。播放量不是成交证据。'}},
{id:'tutorial-production',category:'video',platform:'youtube',video:'6RQfGsc8PIA',creator:'Descript',source:'https://www.youtube.com/watch?v=6RQfGsc8PIA',original:'How to create engaging tutorial videos—fast | Descript',tool:'https://www.descript.com/',level:'beginner',
en:{title:'Make a product tutorial a customer can follow',summary:'Use a vendor tutorial as a learning reference; sell a clear walkthrough of a real customer task.',buyer:'A small software team repeatedly explaining the same setup to customers.',deliverable:'One short task walkthrough, corrected captions and a version/date note.',edge:'Choose the task from a real support question. Show the exact clicks and the final result in the current product.',risk:'A polished video about an unimportant task solves little. Product changes can make recordings obsolete.',test:'Give the draft to someone unfamiliar with the task. Count where they get stuck before offering a larger tutorial package.',steps:['Choose one repeated support question and obtain demo-account permission.','Write a short outline from the starting screen to the completed task.','Record actual actions and edit pauses without hiding errors.','Have a new user follow it; correct unclear steps and name a review date.'],gate:'A new user completes the task with the tutorial. Do not label a vendor demo as our independently tested result.'},
zh:{title:'做一条客户真的能跟着完成操作的产品教程',summary:'参考厂商教程，把真实客户任务做成清晰的操作视频。',buyer:'反复向客户解释同一个设置流程的小型软件团队。',deliverable:'一条单任务操作教程、校对字幕、产品版本与录制日期说明。',edge:'从真实客服问题选题，展示当前产品的实际操作和最终结果。',risk:'题目不重要，视频再漂亮也难以收费。产品更新后还需要维护内容。',test:'请一位不熟悉流程的人跟着做，记录卡住的位置，再考虑扩大教程包。',steps:['选一个重复客服问题，获得演示账号使用许可。','写出从起始界面到任务完成的简短提纲。','录制真实操作，剪去停顿，但不隐藏关键错误。','让新手试做，修正不清楚的步骤，并确定复核日期。'],gate:'新手能按教程完成任务才算通过。厂商演示不标成本站独立实测。'}},
{id:'faq-automation',category:'automation',platform:'youtube',video:'GuaKeDS6UKU',creator:'n8n',source:'https://www.youtube.com/watch?v=GuaKeDS6UKU',original:'n8n Quick Start Tutorial: Build Your First AI Agent [2026]',tool:'https://n8n.io/',level:'intermediate',
en:{title:'Prototype a narrowly scoped FAQ assistant',summary:'Start with the official n8n introduction, then test one bounded support task with a human fallback.',buyer:'An operations team with repetitive questions and an approved answer library.',deliverable:'A sandbox prototype, test-question register, failure log and handover instructions.',edge:'The useful work is defining what it must refuse, which sources it can use, and how a person takes over.',risk:'A successful demo does not establish production reliability. Permissions, retries, monitoring and maintenance are separate work.',test:'Use 20 representative test questions, including missing answers and hostile instructions. Record accuracy and escalation; do not auto-send customer replies.',steps:['Collect approved example questions and answers without customer personal data.','Build a sandbox workflow with read-only access and a manual review step.','Test known, ambiguous, unsupported and adversarial questions.','Calculate execution and review cost, document failures and define ownership.'],gate:'Publish the test set and its actual results to the client. Quote production support separately; no autonomous-revenue claim.'},
zh:{title:'为一个明确场景做 FAQ 助手原型',summary:'从 n8n 官方入门开始，围绕有限的客服问题做测试，并保留人工接管。',buyer:'有重复问题和已审核答案库的运营团队。',deliverable:'沙箱原型、测试问题表、失败记录、交接说明。',edge:'真正需要设计的是拒答边界、可用资料和人工接管流程。',risk:'演示成功不等于生产可靠。权限、重试、监控和维护都需要单独计价。',test:'准备 20 个代表性测试问题，加入无答案与恶意指令，记录准确情况和转人工情况，不自动给客户发回复。',steps:['收集获准的问题与答案示例，不放客户个人信息。','搭建只读沙箱流程，加入人工审核。','测试已知、模糊、无依据和对抗性问题。','计算调用及审核成本，记录失败并明确维护责任。'],gate:'向客户提供真实测试集和结果。生产维护单独报价，不宣称自动赚钱。'}},
{id:'product-visuals',category:'commerce',platform:'youtube',video:'a8WXQK841NM',creator:'Business Automated',source:'https://www.business-automated.com/tutorials/ai-product-packshots-airtable-openai',original:'AI Product Packshots with Airtable + OpenAI',tool:'https://www.make.com/',level:'intermediate',
en:{title:'Deliver a checked set of product-image variations',summary:'A creator’s workflow connects Airtable, Make and image generation. Our project brief adds product-accuracy checks and a bounded delivery scope.',buyer:'A small shop needing secondary lifestyle images for existing products.',deliverable:'Three approved variations for one SKU, a source register and a rejection log.',edge:'Preserve the actual product. Check labels, proportions, texture and included accessories against the source photograph.',risk:'Generation may alter product facts. Tool costs rise with rejected outputs; beautiful but inaccurate images are not acceptable delivery.',test:'Try one SKU using authorized images. Ask the buyer to compare each output with the physical item before approving any publication.',steps:['Obtain product images and brand permission; list facts that cannot change.','Produce a small batch, recording all attempts and paid generation costs.','Reject changed labels, dimensions, materials or misleading use scenes.','Deliver only approved assets with size specifications and usage notes.'],gate:'No factual product mismatch in delivered images. Review the destination marketplace’s current image rules before publishing.'},
zh:{title:'交付一组经过核对的商品场景图',summary:'作者展示了 Airtable、Make 与图像生成的流程；本站补充商品一致性检查和明确的交付范围。',buyer:'需要为现有商品补充生活场景图的小型店铺。',deliverable:'一个商品的三张审核通过图片、素材来源表和废片记录。',edge:'保护真实商品信息，对照原图检查标签、比例、材质和配件。',risk:'生成结果可能改变商品事实。废片会增加成本，好看但不真实的图不能作为合格交付。',test:'先用获准图片试一个商品，让买家对照实物逐张核对，再决定是否发布。',steps:['取得商品图片与品牌使用许可，列出不能改变的信息。','小批量生成，记录所有尝试及付费调用成本。','剔除标签、尺寸、材质错误及误导性使用场景。','只交付审核通过的图，并附尺寸和使用说明。'],gate:'交付图不能存在商品事实偏差，发布前复核目标商城当前图片规则。'}},
{id:'tiktok-ad-brief',category:'video',platform:'tiktok',video:null,creator:'TikTok for Business',source:'https://ads.tiktok.com/business/en-US/blog/canva-full-funnel-creative-tips',original:'From design to launch: How to create TikTok ads in Canva',tool:'https://www.canva.com/',level:'beginner',
en:{title:'Scope three TikTok ad concepts before production',summary:'TikTok’s official Canva guide is a source reference, not an embedded creator video. Use it to prepare a practical ad-production brief.',buyer:'A brand with an existing offer, approved product claims and usable source assets.',deliverable:'Three distinct concept briefs with hooks, shot lists, rights notes and one agreed next test.',edge:'Give each concept a different reason to buy; changing colors or captions is not a meaningful new angle.',risk:'Creative delivery does not guarantee ad approval or sales. Advertising spend, account access and campaign management are not included.',test:'Have the brand approve one concept and its claims before paying for production. Keep ad spend outside the production quote.',steps:['Record the actual offer, audience, landing page and approved claims.','Write three distinct hooks and map each to a proof shot.','Check music, likeness rights, AI disclosure and current platform policies.','Approve a production scope and define how the brand will assess the test.'],gate:'The client approves the claims, rights and scope. Platform eligibility and campaign performance remain unverified.'},
zh:{title:'先做三种 TikTok 广告创意，再决定制作',summary:'引用 TikTok 官方 Canva 指南作为资料；这是图文指南，不冒充已嵌入的博主视频。',buyer:'已有商品方案、批准的宣传主张和可用素材的品牌方。',deliverable:'三种不同创意的开场、镜头清单、授权说明及下一次测试安排。',edge:'每种创意提出不同的购买理由，改颜色或字幕不等于新的销售角度。',risk:'交付创意不保证广告审核或销量。广告费、账号权限和投放代运营不包含在制作报价中。',test:'先让品牌审核一种创意和宣传主张，再投入制作；把广告预算与制作报价分开。',steps:['记录真实商品方案、受众、落地页和获准宣传主张。','写三种开场，并为每一种安排证据镜头。','检查音乐、肖像权、AI 标识和当前平台规则。','确认制作范围，并约定品牌如何评估测试。'],gate:'客户批准宣传、授权和交付范围后才执行。平台资格及广告效果仍需单独验证。'}},
{id:'tiktok-effect-prototype',category:'design',platform:'tiktok',video:null,creator:'TikTok Effect House',source:'https://effecthouse.tiktok.com/learn/guides/ai-capabilities/ai-editor/create-an-ai-effect-using-ai-editor',original:'Create an AI Effect Using AI Editor',tool:'https://effecthouse.tiktok.com/',level:'intermediate',
en:{title:'Build a small AI effect prototype for a brand',summary:'Use the official Effect House guide to explore an effect concept. This is a guide reference, not a verified earnings case.',buyer:'A brand or creative studio with a specific interactive concept and a review contact.',deliverable:'One effect prototype, a device-test checklist and a handover note.',edge:'Match the effect to a concrete brand interaction and test whether a new user understands it without explanation.',risk:'Publication and reward eligibility are platform decisions. An effect can work technically and attract no buyers or usage.',test:'Get concept approval before building. Test on representative devices and confirm the brand wants the defined delivery.',steps:['Define one interaction and obtain permission for all brand assets.','Customize a small effect in Effect House; keep the first version narrow.','Test appearance, responsiveness and usability on real devices.','Document limitations and submission requirements before handing it over.'],gate:'The prototype passes agreed device tests. No reward amount, platform approval or audience size is promised.'},
zh:{title:'为品牌做一个小范围 AI 特效原型',summary:'参考 Effect House 官方指南探索交互创意。这是指南资料，不是已验证营收案例。',buyer:'有明确互动想法和审核负责人的品牌或创意工作室。',deliverable:'一个特效原型、设备测试清单和交接说明。',edge:'让特效服务一个具体品牌互动，测试新用户能否不经解释就理解。',risk:'能否发布和获得奖励由平台决定。技术可用不意味着有人使用或愿意购买。',test:'开发前先确认创意，在代表性设备上测试，再核实品牌是否需要这份交付。',steps:['定义一个交互，取得所有品牌素材使用许可。','在 Effect House 中制作范围有限的初版。','在真实设备检查显示、响应和易用性。','交接前记录限制和平台提交要求。'],gate:'原型通过约定设备测试。不承诺奖励金额、平台审核或观众数量。'}}
];
