import {subtitles,workflow,examples} from './checks.mjs';
const $=s=>document.querySelector(s),zh=document.body.dataset.lang==='zh',t=(a,b)=>zh?b:a;
const labels={invalid_timestamp:['Invalid timestamp / timezone','无效时间码或缺少时区'],nonpositive_duration:['End must follow start','结束时间必须晚于开始'],out_of_order:['Cues out of order','字幕顺序错误'],overlap:['Overlapping cues','字幕时间重叠'],empty_caption:['Empty caption','字幕为空'],many_lines:['More than two lines','超过两行'],long_line:['Line exceeds threshold','单行超过设定长度'],fast_reading:['Reading speed exceeds threshold','阅读速度超过设定值'],empty_input:['No records','没有可检查记录'],malformed_row:['Malformed CSV row','CSV 行结构错误'],missing_id:['Missing run ID','缺少执行编号'],duplicate_run:['Duplicate run ID','执行编号重复'],future_timestamp:['Time is in the future','执行时间晚于检查时间'],stale_run:['Run is older than the window','执行时间超过窗口'],unknown_status:['Unknown status','未知执行状态'],not_success:['Run not completed successfully','执行未成功完成'],invalid_count:['Invalid output count','无效输出数量'],empty_output:['Success returned no output','显示成功但输出为零'],missing_expected_runs:['Fewer unique recent successes than expected','近期唯一成功记录低于预期']};
let report=null;const mode=$('#check-mode'),input=$('#check-input');$('#check-now').value=new Date().toISOString();
function reset(){report=null;$('#download-check').disabled=true;$('#check-results').replaceChildren();}
mode.onchange=()=>{reset();$('#subtitle-settings').hidden=mode.value!=='subtitles';$('#workflow-settings').hidden=mode.value!=='workflow';input.value='';};input.addEventListener('input',reset);document.querySelectorAll('.check-settings input').forEach(x=>x.addEventListener('input',reset));
$('#check-example').onclick=()=>{reset();input.value=examples[mode.value];if(mode.value==='workflow')$('#check-now').value='2026-10-01T00:02:00Z';};
$('#check-file').onchange=async e=>{reset();const f=e.target.files[0];if(!f)return;if(f.size>500000){$('#check-results').textContent=t('File must be under 500 KB.','文件需小于 500 KB。');return;}input.value=await f.text();};
$('#run-check').onclick=()=>{reset();const host=$('#check-results');try{report=mode.value==='subtitles'?subtitles(input.value,{cps:+$('#check-cps').value,line:+$('#check-line').value}):workflow(input.value,{now:$('#check-now').value,staleHours:+$('#check-window').value,expected:+$('#check-expected').value});const p=document.createElement('p');p.textContent=t(`${report.count} records; ${report.issues.length} flags. No flags does not certify correctness.`,`${report.count} 条记录，${report.issues.length} 个检查标记。没有标记不代表质量认证。`);host.append(p);const list=document.createElement('ul');for(const issue of report.issues){const li=document.createElement('li');li.textContent=(issue.item?t('Item ','记录 ')+issue.item+': ':'')+(labels[issue.code]?.[zh?1:0]||issue.code);list.append(li);}host.append(list);$('#download-check').disabled=false;}catch{report=null;host.textContent=t('Check format and thresholds. CSV needs run_id,finished_at,status,output_count; times need Z or an explicit offset.','请核对格式和设定值。CSV 需含 run_id,finished_at,status,output_count；时间需含 Z 或明确偏移。');}};
$('#download-check').onclick=()=>{if(!report)return;const lines=report.issues.map(x=>`- ${x.item}: ${labels[x.code]?.[zh?1:0]||x.code}`);const text=[t('# Local delivery check','# 本地交付检查'),JSON.stringify(report.thresholds),t('Flags are structural heuristics. Translation meaning, real outputs and customer acceptance need separate review.','标记是结构性检查；翻译含义、真实业务输出与客户验收需要另行复核。'),...lines].join('\n\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));a.download='agi-delivery-check.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
