import {snapshot,decode,encode,compare} from './reports.mjs';
import {subtitles,workflow,examples} from './checks.mjs';
const $=s=>document.querySelector(s),zh=document.body.dataset.lang==='zh',t=(a,b)=>zh?b:a;
const labels={invalid_timestamp:['Invalid timestamp / timezone','无效时间码或缺少时区'],nonpositive_duration:['End must follow start','结束时间必须晚于开始'],out_of_order:['Cues out of order','字幕顺序错误'],overlap:['Overlapping cues','字幕时间重叠'],empty_caption:['Empty caption','字幕为空'],many_lines:['More than two lines','超过两行'],long_line:['Line exceeds threshold','单行超过设定长度'],fast_reading:['Reading speed exceeds threshold','阅读速度超过设定值'],empty_input:['No records','没有可检查记录'],malformed_row:['Malformed CSV row','CSV 行结构错误'],missing_id:['Missing run ID','缺少执行编号'],duplicate_run:['Duplicate run ID','执行编号重复'],future_timestamp:['Time is in the future','执行时间晚于检查时间'],stale_run:['Run is older than the window','执行时间超过窗口'],unknown_status:['Unknown status','未知执行状态'],not_success:['Run not completed successfully','执行未成功完成'],invalid_count:['Invalid output count','无效输出数量'],empty_output:['Success returned no output','显示成功但输出为零'],missing_expected_runs:['Fewer unique recent successes than expected','近期唯一成功记录低于预期']};
let report=null;const mode=$('#check-mode'),input=$('#check-input');$('#check-now').value=new Date().toISOString();
function reset(){report=null;$('#download-check').disabled=true;$('#save-check').disabled=true;$('#check-results').replaceChildren();}
mode.onchange=()=>{reset();$('#subtitle-settings').hidden=mode.value!=='subtitles';$('#workflow-settings').hidden=mode.value!=='workflow';input.value='';};input.addEventListener('input',reset);document.querySelectorAll('.check-settings input').forEach(x=>x.addEventListener('input',reset));
$('#check-example').onclick=()=>{reset();input.value=examples[mode.value];if(mode.value==='workflow')$('#check-now').value='2026-10-01T00:02:00Z';};
$('#check-file').onchange=async e=>{reset();const f=e.target.files[0];if(!f)return;if(f.size>500000){$('#check-results').textContent=t('File must be under 500 KB.','文件需小于 500 KB。');return;}input.value=await f.text();};
$('#run-check').onclick=()=>{reset();const host=$('#check-results');try{report=mode.value==='subtitles'?subtitles(input.value,{cps:+$('#check-cps').value,line:+$('#check-line').value}):workflow(input.value,{now:$('#check-now').value,staleHours:+$('#check-window').value,expected:+$('#check-expected').value});const p=document.createElement('p');p.textContent=t(`${report.count} records; ${report.issues.length} flags. No flags does not certify correctness.`,`${report.count} 条记录，${report.issues.length} 个检查标记。没有标记不代表质量认证。`);host.append(p);const list=document.createElement('ul');for(const issue of report.issues){const li=document.createElement('li');li.textContent=(issue.item?t('Item ','记录 ')+issue.item+': ':'')+(labels[issue.code]?.[zh?1:0]||issue.code);list.append(li);}host.append(list);$('#download-check').disabled=false;$('#save-check').disabled=false;}catch{report=null;host.textContent=t('Check format and thresholds. CSV needs run_id,finished_at,status,output_count; times need Z or an explicit offset.','请核对格式和设定值。CSV 需含 run_id,finished_at,status,output_count；时间需含 Z 或明确偏移。');}};
$('#download-check').onclick=()=>{if(!report)return;const lines=report.issues.map(x=>`- ${x.item}: ${labels[x.code]?.[zh?1:0]||x.code}`);const text=[t('# Local delivery check','# 本地交付检查'),JSON.stringify(report.thresholds),t('Flags are structural heuristics. Translation meaning, real outputs and customer acceptance need separate review.','标记是结构性检查；翻译含义、真实业务输出与客户验收需要另行复核。'),...lines].join('\n\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));a.download='agi-delivery-check.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};

const historyKey='agi-delivery-history-v1';let history=[],storageBroken=false;
const notice=message=>$('#history-status').textContent=message;
function renderHistory(){
 $('#check-history').replaceChildren();for(const id of ['#baseline-check','#retest-check'])$(id).replaceChildren();$('#comparison-results').replaceChildren();
 for(const r of history){const label=`${r.createdAt} · ${r.kind==='subtitles'?t('Subtitles','字幕'):t('Workflow','工作流')} · ${r.count} · ${Object.values(r.flags).reduce((a,b)=>a+b,0)} ${t('flags','个标记')}`;
 const li=document.createElement('li'),span=document.createElement('span'),button=document.createElement('button');span.textContent=label;button.textContent=t('Delete','删除');button.onclick=()=>persist(history.filter(x=>x.id!==r.id));li.append(span,' ',button);$('#check-history').append(li);
 for(const id of ['#baseline-check','#retest-check']){const option=document.createElement('option');option.value=r.id;option.textContent=label;$(id).append(option);}}
 if(history.length>1)$('#retest-check').selectedIndex=history.length-1;
 $('#compare-checks').disabled=history.length<2;$('#backup-checks').disabled=!history.length;
}
function persist(next){try{localStorage.setItem(historyKey,encode(next));history=next;storageBroken=false;renderHistory();notice(t('Saved on this browser.','已保存到此浏览器。'));return true;}catch{notice(t('Could not save. Browser storage may be unavailable or full. Existing records remain.','保存失败：浏览器存储不可用或已满，已有记录保持不变。'));return false;}}
try{const saved=localStorage.getItem(historyKey);if(saved)history=decode(saved);}catch{storageBroken=true;notice(t('Stored backup is invalid or storage is unavailable. Delete local summaries to reset before saving.','本地备份无效或存储不可用，请先删除本地摘要再重新保存。'));}renderHistory();
$('#save-check').onclick=()=>{if(!report)return;if(storageBroken){notice(t('Reset invalid local storage first.','请先清除无效的本地存储。'));return;}if(history.length>=20){notice(t('20-summary limit reached. Export and delete a record first.','已达 20 份上限，请先备份并删除一份记录。'));return;}if(persist([...history,snapshot(report,crypto.randomUUID())]))$('#save-check').disabled=true;};
function downloadBackup(text,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('#backup-checks').onclick=()=>downloadBackup(encode(history),'agi-delivery-summaries.json');
$('#clear-checks').onclick=()=>{if(!confirm(t('Delete all saved summaries in this browser? Download a backup first if needed.','删除此浏览器全部摘要？需要留存时请先下载备份。')))return;try{localStorage.removeItem(historyKey);history=[];storageBroken=false;renderHistory();notice(t('Local summaries deleted.','本地摘要已删除。'));}catch{notice(t('Storage unavailable.','存储不可用。'));}};
$('#import-checks').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>100000||storageBroken)throw Error();const imported=decode(await file.text()),ids=new Set(history.map(r=>r.id));const next=[...history,...imported.filter(r=>!ids.has(r.id))];if(next.length>20)throw Error();persist(next);}catch{notice(t('Import rejected. Use a valid summary backup within 100 KB and the 20-record limit. Existing records remain.','导入被拒绝：需有效摘要备份、小于 100 KB 且总计不超过 20 份。已有记录保持不变。'));}finally{e.target.value='';}};
for(const id of ['#baseline-check','#retest-check'])$(id).onchange=()=>$('#comparison-results').replaceChildren();
$('#compare-checks').onclick=()=>{const host=$('#comparison-results');host.replaceChildren();const a=history.find(r=>r.id===$('#baseline-check').value),b=history.find(r=>r.id===$('#retest-check').value);if(!a||!b||a.id===b.id){host.textContent=t('Choose two different summaries.','请选择两份不同摘要。');return;}const result=compare(a,b);if(result.blocked){host.textContent=t('Not comparable: task type, thresholds, review time or record count differs. Align the scope and rerun.','不可对比：检查类型、阈值、检查时间或记录数不同。请统一范围后重新检查。');return;}const p=document.createElement('p');p.textContent=t('Flag-count changes only. Fewer flags do not prove a fix; verify the original delivery.','仅对比标记数量。减少不等于修复，请复核原始交付。');host.append(p);const list=document.createElement('ul');for(const row of result.rows){const li=document.createElement('li');li.textContent=`${labels[row.code]?.[zh?1:0]||row.code}: ${row.before} → ${row.after} (${row.delta>0?'+':''}${row.delta})`;list.append(li);}host.append(list);if(!result.rows.length)host.append(document.createTextNode(t('Neither check has structural flags.','两次检查均未发现结构标记。')));};
