// Original AGI baseline. Requires separately installed Playwright (Apache-2.0).
// No form submissions or link crawling. Run only against an authorized staging site.
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';
const args=process.argv.slice(2);if(args[0]!=='--authorized'||!args[1]){console.error('Usage: node launch-audit.mjs --authorized https://YOUR-STAGING-DOMAIN / /pricing');process.exit(2);}
const origin=new URL(args[1]);if((origin.protocol!=='https:'&&!(origin.protocol==='http:'&&['127.0.0.1','localhost','[::1]'].includes(origin.hostname)))||origin.username||origin.password||origin.pathname!=='/'||origin.search||origin.hash)throw Error('Supply an HTTPS origin without credentials or path.');
const routes=args.slice(2).length?args.slice(2):['/'];if(routes.length>5)throw Error('Limit: five pages.');for(const r of routes){if(!r.startsWith('/')||new URL(r,origin).origin!==origin.origin)throw Error('Only same-origin paths.');}
const require=createRequire(import.meta.url);const {chromium}=require(process.env.EARN_PLAYWRIGHT||require.resolve('playwright',{paths:[process.cwd(),process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES].filter(Boolean)}));const launch={headless:true};if(process.env.EARN_EXECUTABLE)launch.executablePath=process.env.EARN_EXECUTABLE;if(process.env.EARN_CHROMIUM)launch.args=require(process.env.EARN_CHROMIUM).args.filter(x=>!['--disable-web-security','--single-process'].includes(x));
const browser=await chromium.launch(launch),out=path.resolve('agi-launch-audit-'+Date.now());fs.mkdirSync(out);const report={schema:'agi-launch-baseline-v1',createdAt:new Date().toISOString(),origin:origin.origin,scope:'Read-only navigation baseline; no security certification, full accessibility review or business-journey acceptance.',pages:[]};
try{for(const [label,width,height]of [['phone',390,844],['desktop',1440,1000]]){const context=await browser.newContext({viewport:{width,height},serviceWorkers:'block'});for(let i=0;i<routes.length;i++){const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message.slice(0,500)));await page.route('**/*',route=>{if(route.request().isNavigationRequest()&&new URL(route.request().url()).origin!==origin.origin)return route.abort();return route.continue();});const row={route:routes[i],viewport:label};try{const response=await page.goto(new URL(routes[i],origin).href,{waitUntil:'domcontentloaded',timeout:20000});row.status=response?.status()??null;row.finalUrl=page.url();row.checks=await page.evaluate(()=>({title:document.title,overflow:document.documentElement.scrollWidth>innerWidth,imagesMissingAlt:document.querySelectorAll('img:not([alt])').length,emptyLinks:[...document.querySelectorAll('a')].filter(a=>!a.textContent.trim()&&!a.getAttribute('aria-label')&&!a.querySelector('img[alt]')).length}));row.screenshot=`${i}-${label}.png`;await page.screenshot({path:path.join(out,row.screenshot),fullPage:false});}catch(e){row.error=e.message.slice(0,500);}row.browserErrors=errors;report.pages.push(row);await page.close();}await context.close();}}
finally{await browser.close();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}
console.log('Local report: '+path.join(out,'report.json'));if(report.pages.some(x=>x.error||!x.status||x.status>=400))process.exitCode=1;
