import runpy,re
from pathlib import Path
ctx=runpy.run_path('scripts/pages.py');sites=ctx['sites'];wrap=ctx['wrap']
visuals={
'rfqdesk':'''<div class="quote-scene" aria-label="Fictional quote comparison"><div class="sheet-back"><span>Quote A</span><strong>$2.10 / unit</strong><p>Minimum order: 500</p></div><div class="quote-sheet"><div class="sheet-top"><span>Order comparison</span><b>300 units needed</b></div><div class="quote-line"><span>Sample A <small>500 units + freight & setup</small></span><strong>$1,350</strong></div><div class="quote-line selected"><span>Sample B <small>300 units + freight</small></span><strong>$825</strong></div><div class="quote-line"><span>Sample C <small>1,000 units + freight & setup</small></span><strong>$2,330</strong></div><p class="visual-caption">Lowest unit price ≠ lowest order cost.</p></div><div class="scene-note">Fictional quotes. Real calculation.</div></div>''',
'modelmeter':'''<div class="cost-scene" aria-label="Illustrative AI cost review"><div class="console-top"><span><i></i> Project cost review</span><span>Fictional sample</span></div><div class="cost-total"><span>Billed over 14 days</span><strong>$140<span>.00</span></strong></div><div class="cost-row"><span>Research</span><strong>$86</strong></div><div class="bar"><span class="bar-research"></span></div><div class="cost-row"><span>Support</span><strong>$54</strong></div><div class="bar"><span class="bar-support"></span></div><div class="run-rate"><span>At the same pace, over 30 days</span><strong>$300</strong></div><div class="console-bottom">Your file → project totals → a review you can share</div></div>''',
'querysprint':'''<div class="learning-scene" aria-label="Your three-part learning path"><div class="lesson-ticket"><span class="lesson-symbol" aria-hidden="true">{ }</span><div><small>Your first data project</small><strong>The little shop report</strong></div><span class="ticket-tag">Free</span></div><div class="lesson-route"><div class="route-item"><span>1</span><div><strong>Find the right orders</strong><small>SELECT · WHERE</small></div></div><div class="route-item"><span>2</span><div><strong>Account for refunds</strong><small>SUM · calculated values</small></div></div><div class="route-item"><span>3</span><div><strong>Tell the country story</strong><small>GROUP BY · ORDER BY</small></div></div></div><div class="code-note"><code>SELECT country, SUM(revenue - refund)</code><span>Build it. Run it. Explain it.</span></div></div>'''}
intro={
'rfqdesk':('The lowest price<br>isn’t the whole quote.','Compare supplier quotes with minimum orders, freight and setup included. Know how much cash the order actually needs.','Compare an example','I have my own quotes'),
'modelmeter':('Make sense of<br>your AI bill.','See which projects drive your API spend. Turn a usage file into a clear cost breakdown, without connecting your keys.','Explore a cost report','Analyze my own file'),
'querysprint':('Don’t just learn SQL.<br>Finish a small project.','Turn six shop orders into a useful report. Three connected exercises, instant feedback, and SQL you can take with you.','Start my first project','Walk me through it')}
steps={
'rfqdesk':[('Start with an example','See how a lower unit price can require a larger order.'),('Bring comparable quotes','Use one product, one currency and the same freight scope.'),('Take the result with you','Export the comparison or prepare your supplier RFQ.')],
'modelmeter':[('Explore a sample bill','See how $140 splits across two projects.'),('Prepare your usage file','Match the columns and use amounts actually billed.'),('Review the monthly pace','Check assumptions, then download a cost breakdown.')],
'querysprint':[('Meet your dataset','Explore the fictional orders and the business question.'),('Write, run, learn','Try a query. Get a hint when you need one.'),('Build your report','Complete all three steps and export your SQL.')]}
for slug,d in sites.items():
 title,desc,primary,secondary=intro[slug]
 own='href="#workbench"' if slug!='querysprint' else 'href="#learn" data-tour="start"'
 primary_button=f'<button class="button" data-primary="start">{primary}<span aria-hidden="true">↗</span></button>'
 hero=f'''<section class="hero hero-{slug}"><div class="hero-copy"><p class="availability"><span></span>Free workbench · no account needed</p><h1>{title}</h1><p class="lead">{desc}</p><div class="actions">{primary_button}<a class="text-link" {own}>{secondary}</a></div><p class="privacy-note"><span aria-hidden="true">◈</span> Working data stays in your browser.</p></div><div class="product-visual">{visuals[slug]}</div></section>'''
 cards=''.join(f'<li><span class="step-number">{i+1}</span><div><h3>{t}</h3><p>{b}</p></div></li>' for i,(t,b) in enumerate(steps[slug]))
 onboarding=f'''<section class="first-run" id="learn"><div class="intro-row"><div><p class="section-label">New here?</p><h2>Your first result, one step at a time.</h2></div><button class="secondary" data-tour="start">Show me how</button></div><ol class="first-steps">{cards}</ol><div id="tour" class="tour" hidden><div class="tour-top"><span id="tour-count"></span><button id="tour-close" class="text-button">Close tutorial</button></div><h3 id="tour-title"></h3><p id="tour-body"></p><div class="actions"><button id="tour-action">Load the example</button><button id="tour-prev" class="secondary">Previous step</button><button id="tour-next" class="secondary">Next step</button></div><p class="quiet" id="tour-feedback" role="status"></p></div></section>'''
 sample='<button id="sample" class="secondary">Load example data</button>' if slug!='querysprint' else '<span class="pill">3 connected exercises</span>'
 inputs=ctx[dict(rfqdesk='rfq',modelmeter='model',querysprint='sql')[slug]]
 if slug=='rfqdesk':
  inputs=inputs.replace('<label for="quotes">','<details class="csv-help"><summary>New to CSV? See a filled example</summary><p>A CSV is a plain-text table. Each line is one supplier. Keep the first line as column names and enter costs in one currency.</p><pre>supplier,unit_price,moq,pack_size,freight,setup,lead_days\nYour supplier,2.45,200,50,90,0,14</pre><p>MOQ is the minimum quantity you must buy. Pack size is the order increment.</p></details><label for="quotes">')
 if slug=='modelmeter':
  inputs=inputs.replace('<label for="file">','<details class="csv-help"><summary>How do I prepare my provider export?</summary><p>Make a copy. Rename or map columns to the headers shown below. Each row can be one request or a non-overlapping total. Enter the actual billed amount in USD, including the charges you want to review.</p><pre>project,provider,model,requests,input_tokens,output_tokens,billed_usd\nSupport,Example,Model A,100,20000,5000,0.45</pre><p>The current tool does not automatically map provider-specific exports. Remove API keys, prompts and personal data.</p></details><label for="file">')
 extra='<div class="stats"><div><strong id="spent">—</strong><span>Billed in your file</span></div><div><strong id="projected">—</strong><span>Monthly pace</span></div><div><strong id="percustomer">—</strong><span>Pace / customer</span></div></div>' if slug=='modelmeter' else '<p class="progress-label" id="progress">0 / 3 completed</p>' if slug=='querysprint' else ''
 work=f'''<section id="workbench" class="workbench"><div class="section-head"><div><p class="section-label">{d['name']} workbench</p><h2>{dict(rfqdesk='Put your quotes side by side.',modelmeter='From usage file to cost review.',querysprint='The little shop report.')[slug]}</h2></div>{sample}</div><div class="editor"><div class="inputs">{inputs}</div><div class="output">{extra}<div id="status" role="status" class="status">{dict(rfqdesk='No quotes yet. Load the example to see a complete comparison, or paste your own data.',modelmeter='No report yet. Explore the example first, or import your normalized usage file.',querysprint='Choose the first exercise and run the starter query. The dataset is ready.')[slug]}</div><div class="table-wrap"><table id="results" aria-label="Results"></table></div><div id="next-help" class="result-next" hidden><h3>What to do with this result</h3><p>{dict(rfqdesk='Compare cash outlay and extra stock. Check that specifications and freight scope match before choosing a supplier.',modelmeter='Start with the largest project. Check whether the period is complete and the budget reflects your actual plan.',querysprint='Explain why the filter and calculation work. Then select the next exercise, or download your completed SQL.')[slug]}</p></div><div class="actions"><button id="export" disabled>Download my result</button></div><label class="consent"><input type="checkbox" id="measurement">Share anonymous usage steps to improve the tool. Your working data is never included. Optional.</label></div></div></section>'''
 questions={
 'rfqdesk':'In the past 30 days, how many times did you compare supplier quotes for a real purchase?',
 'modelmeter':'In the past 30 days, how many times did you reconcile AI bills across more than one provider?',
 'querysprint':'In the past 30 days, how many SQL reports did you finish outside a tutorial?'}
 research=f'''<section class="research-question"><p class="section-label">One optional question</p><h3>{questions[slug]}</h3><div class="actions"><button class="secondary" data-research="research_none">None</button><button class="secondary" data-research="research_once">Once</button><button class="secondary" data-research="research_repeat">Twice or more</button></div><p class="quiet">Clicking sends only your anonymous choice. You can skip this and keep using the tool.</p><p id="research-status" role="status"></p></section>'''
 offer=f''' <section id="offer" class="offer" hidden><div><p class="section-label">Help shape what comes next</p><h2>{d['model']}</h2><p>{d['offer']}</p></div><div class="offer-action"><span class="pill">Proposed · not for sale</span><p class="price">{d['price']}</p><button id="interest">This would be useful at this price</button><p class="quiet">Sends anonymous interest only. No purchase or signup.</p><p id="interest-status" role="status"></p></div></section>'''
 faq='<section class="faq"><h2>Before you begin.</h2>'+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in d['faq'])+'</section>'
 body=f'<main id="main">{hero}{onboarding}{work}{research}{offer}{faq}</main><script type="module" src="/app.mjs"></script><script type="module" src="/onboarding.mjs"></script>'
 page=wrap(slug,d['seo'],desc,body).replace('<link rel="stylesheet"','<link rel="preload" href="/fonts/manrope-latin-wght-normal.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet"')
 page=page.replace('<a href="/guide">Guide</a>','<a href="/#learn">Quick start</a><a href="/guide">Guide</a>')
 page=page.replace('Free tool / early product experiment','Independent tool · Free beta')
 (Path('site')/slug/'index.html').write_text(page)

# Buyer-matched distribution to the vertical Agent experiment.
p=Path('site/rfqdesk/index.html');text=p.read_text()
text=text.replace('<a href="/guide">Guide</a>','<a href="/guide">Guide</a><a href="/agent">Invoice Agent</a>')
text=text.replace('<section class="faq">','<section class="agent-entry"><p class="section-label">After the order</p><h2>Does the supplier invoice match?</h2><p>Review the PO, invoice and earlier billed quantities with TradeCheck. Try a fictional example or install the local MCP in your AI assistant.</p><a class="button" href="/agent">Try the invoice review Agent →</a></section><section class="faq">')
text=text.replace('<link rel="stylesheet" href="/styles.css">','<link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/agent.css">')
p.write_text(text)
