import assert from 'node:assert/strict';import specs from '../experiments.json' with {type:'json'};
async function get(url){let failure;for(let i=0;i<6;i++){try{const r=await fetch(url,{signal:AbortSignal.timeout(10000)});if(r.ok)return r;failure=r.status;}catch(e){failure=e.message;}await new Promise(r=>setTimeout(r,4000));}throw Error('Public check failed '+url+': '+failure);}
for(const [site,s] of Object.entries(specs)){const origin='https://'+s.host;for(const path of ['/','/guide','/privacy','/app.mjs','/ui.mjs','/core.mjs','/onboarding.mjs','/styles.css','/fonts/manrope-latin-wght-normal.woff2','/robots.txt','/sitemap.xml']){const r=await get(origin+path);assert.ok((await r.arrayBuffer()).byteLength>20);}
const pulse=await(await get(origin+'/api/pulse')).json();assert.equal(pulse.site,site);assert.ok(pulse.rows.every(r=>r.mode!=='qa'&&!('session' in r)));
const config=await(await get(origin+'/api/config')).json();assert.equal(config.site,site);assert.equal(config.sales_enabled,false);assert.equal(config.measurement,true);assert.equal((await fetch(origin+'/missing-page')).status,404);
const payload={event:'complete',mode:'qa',source:'direct',session:crypto.randomUUID(),consent:true};const options={method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(payload)};
for(let n=0;n<2;n++){const r=await fetch(origin+'/api/event',options);assert.equal(r.status,200);assert.equal((await r.json()).recorded,true);}const denied=await fetch(origin+'/api/event',{...options,headers:{Origin:'https://example.com','Content-Type':'application/json'}});assert.equal(denied.status,403);console.log('PASS public pages, isolated host, closed sales and QA measurement: '+site);}
const wasm=await get('https://querysprint.agiscorecard.com/vendor/sql-wasm.wasm');assert.equal(wasm.headers.get('content-type')?.split(';')[0],'application/wasm');console.log('PASS SQLite WebAssembly asset');
const agentOrigin='https://rfqdesk.agiscorecard.com';for(const path of ['/agent','/agent-guide','/agent-app.mjs','/agent.css','/tradecheck.js','/agent-example.json','/tradecheck-NOTICES.txt','/downloads/tradecheck-mcp-0.2.0.tar.gz','/downloads/SHA256SUMS'])await get(agentOrigin+path);
const archive=await(await get(agentOrigin+'/downloads/tradecheck-mcp-0.2.0.tar.gz')).arrayBuffer();const hash=await crypto.subtle.digest('SHA-256',archive);const actual=Array.from(new Uint8Array(hash),x=>x.toString(16).padStart(2,'0')).join('');const sums=await(await get(agentOrigin+'/downloads/SHA256SUMS')).text();assert.equal(sums.split(' ')[0],actual);console.log('PASS TradeCheck public pages, packaged download and checksum');

for(const p of ["/filing-engine.mjs","/filing.css","/filinglens-NOTICES.txt","/downloads/filinglens-mcp-0.1.0.tar.gz"])await get("https://filinglens.agiscorecard.com"+p);
const sec=await get("https://filinglens.agiscorecard.com/api/sec-concept?cik=320193&tag=Assets");const live=await sec.json();assert.equal(Number(live.data.cik),320193);assert.equal(live.data.tag,"Assets");console.log("PASS FilingLens official SEC data lookup");
