import {compareBlindBoxBudget,estimateCollectionProgress} from './planning-core.mjs';
export function initPlanning(el,record){
 const form=el.querySelector('form'),result=el.querySelector('[data-planning-result]'),error=el.querySelector('[data-planning-error]'),c=JSON.parse(el.querySelector('[data-planning-copy]').textContent),budget=el.dataset.planning==='budget';
 const num=new Intl.NumberFormat(document.documentElement.lang,{maximumFractionDigits:2}),percent=n=>num.format(n*100)+'%';let example=false;
 const pending=()=>{result.textContent=c.pending;error.textContent='';};
 form.addEventListener('input',()=>{example=false;pending();});form.addEventListener('invalid',()=>{pending();error.textContent=c.error;},true);
 function calculate(){if(!form.reportValidity())return;try{const a=Object.fromEntries([...new FormData(form)].map(([k,v])=>[k,v.trim()===''?NaN:Number(v)])),r=(budget?compareBlindBoxBudget:estimateCollectionProgress)(a),labels=budget?c.budgetResults:c.progressResults,values=budget?[r.boxes,num.format(r.maxSpend),percent(r.probabilityAtLeastOne),percent(r.probabilityNoTarget),num.format(r.expectedSpendIfStoppingAtFirstTarget),num.format(r.confirmedCost),r.confirmedWithinBudget?c.yes:c.no]:[num.format(r.expectedNewRegularStyles),num.format(r.expectedRepeatedRegularDraws),num.format(r.expectedUniqueRegularStyles),num.format(r.expectedSecretDraws),percent(r.probabilityAtLeastOneNewRegular)];result.replaceChildren();if(example){const p=document.createElement('p');p.textContent=c.exampleNote;result.append(p);}const dl=document.createElement('dl');labels.forEach((label,i)=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=values[i];dl.append(dt,dd);});result.append(dl);error.textContent='';if(!example)record(budget?'collector_budget_calc':'collector_progress_calc');}catch{pending();error.textContent=c.error;}}
 form.addEventListener('submit',e=>{e.preventDefault();calculate();});const button=el.querySelector('[data-planning-example]');button.hidden=false;button.addEventListener('click',()=>{const sample=budget?{budget:100,boxCost:15,fixedCost:10,confirmedCost:80,probabilityPercent:5}:{regularStyles:6,ownedStyles:4,boxes:6,secretPercent:0};for(const[k,v]of Object.entries(sample))form.elements[k].value=v;example=true;calculate();});
}
