import fs from 'node:fs';
import {aiCopy,aiSources,AI_MODELS,SUMMARY_SAMPLE,aiExampleCopy} from './ai-copy.mjs';
const evaluation=JSON.parse(fs.readFileSync(new URL('../../document-assets/ai-evaluation.json',import.meta.url),'utf8'));
export function aiText(lang,task){const c=aiCopy[lang],t=c.tools[task],m=AI_MODELS[task];return [t.intro,t.limits,t.how,c.privacy,c.download,`${m.id} · ${m.revision} · q8 · Apache-2.0 · ${m.weights} bytes of weights`,...t.faq.flat(),...(task==='summary'?[aiExampleCopy[lang].body,SUMMARY_SAMPLE,...evaluation.summary.selected.map(r=>`[${r.sentence}] ${r.text}`)]:[])];}
export function aiPage(lang,task,esc){const c=aiCopy[lang],t=c.tools[task],u=c.ui,m=AI_MODELS[task];
 const input=task==='summary'?`<label for="ai-text">${esc(u.text)}</label><textarea id="ai-text" rows="9" maxlength="12000" spellcheck="false" required></textarea><label for="ai-count">${esc(u.count)}</label><select id="ai-count"><option value="3">3</option><option value="5">5</option></select><button type="button" id="ai-sample">${esc(u.sample)}</button>`:`<label class="ai-file-label" for="ai-file">${esc(u.file)}<input type="file" id="ai-file" accept="${task==='portrait'?'image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp':'.wav,.mp3,audio/wav,audio/mpeg'}"></label><p id="ai-selected">${esc(u.empty)}</p>${task==='speech'?`<button type="button" id="ai-audio-sample">${esc(u.audioSample)}</button>`:''}`;
 const x=aiExampleCopy[lang],example=task==='summary'?`<section class="section" id="worked-example"><h2>${esc(x.title)}</h2><p>${esc(x.body)}</p><details><summary>${esc(x.input)}</summary><p>${esc(SUMMARY_SAMPLE)}</p></details><h3>${esc(x.output)}</h3><ol>${evaluation.summary.selected.map(r=>`<li>[${r.sentence}] ${esc(r.text)}</li>`).join('')}</ol><a href="/document-assets/ai-evaluation.json">${esc(x.record)}</a></section>`:'';
 return `<div class="tool-heading"><p class="eyebrow">${esc(c.category)} · ${esc(t.badge)}</p><h1>${esc(t.name)}</h1><p>${esc(t.intro)}</p></div><section class="ai-notice"><h2>${esc(c.limits)}</h2><p>${esc(t.limits)}</p><p>${esc(c.download)}</p></section><section class="work-panel" id="ai-panel" aria-busy="false"><p>${esc(u.model)}: <strong>${Math.ceil(m.weights/1000000)} MB</strong> · ${esc(m.id)}</p><p class="small">${esc(c.privacy)}</p><div class="actions"><button class="primary" id="ai-load">${esc(u.load)}</button><button id="ai-stop" disabled>${esc(u.stop)}</button></div><form id="ai-form">${input}<div class="actions"><button class="primary" id="ai-run" type="submit" disabled>${esc(u.run)}</button></div></form><button id="ai-clear" class="text-button">${esc(u.clear)}</button><p id="ai-status" class="status-line" role="status" aria-live="polite">${esc(u.ready)}</p><noscript>JavaScript / WebAssembly</noscript></section><section id="ai-result" class="ai-result section" tabindex="-1" hidden></section><section class="section" id="ai-method"><h2>${esc(c.method)}</h2><p>${esc(t.how)}</p><p class="editorial-meta">TDS · 2026-09-27</p><p class="small ai-model-ref">${esc(m.id)} · ${esc(m.revision)} · q8 · Apache-2.0</p><h3>${esc(c.sources)}</h3><ul>${aiSources(task).map(([title,url])=>`<li><a href="${url}" rel="noopener noreferrer">${esc(title)}</a></li>`).join('')}</ul></section>${example}<section class="section faq"><h2>${esc(c.faqTitle)}</h2>${t.faq.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</section><script id="ai-copy" type="application/json">${JSON.stringify({task,ui:u,errors:c.errors}).replace(/</g,'\\u003c')}</script><script type="module" src="/document-assets/ai-app.mjs?v=2026-10-02.1"></script>`;
}
