import test from 'node:test';import assert from 'node:assert/strict';
import {AI_TOOLS,AI_MODELS,SUMMARY_SAMPLE,sentencesForSummary,selectHighlights,speechHasSignal,subtitleFile} from '../../document-assets/ai-core.mjs';
import {onRequestPost} from '../../functions/api/doc-events.js';import {aggregateDocuments} from '../../functions/api/document-stats.js';
test('summary keeps exact source sentences and never expands the source',()=>{const s=sentencesForSummary(SUMMARY_SAMPLE);const v=s.map((_,i)=>[1,i*.1,1-i*.01]);for(const count of [3,5]){const out=selectHighlights(s,v,count);assert.equal(out.length,count);for(const row of out)assert.equal(row.text,s[row.sentence-1]);assert.ok(out.every((r,i)=>i===0||r.sentence>out[i-1].sentence));}assert.equal(selectHighlights(s.slice(0,3),v.slice(0,3),5).length,2);});
test('summary rejects unsupported sizes and unusable vectors instead of inventing output',()=>{for(const s of ['', 'a'.repeat(12001),'A long sentence without a full stop '.repeat(10)])assert.throws(()=>sentencesForSummary(s));assert.throws(()=>selectHighlights(['a','b','c'],[[0,0],[1,0],[0,1]],3));assert.throws(()=>selectHighlights(['a'],[[NaN]],3));assert.throws(()=>selectHighlights(['a','b'],[[1],[1]],99));});
test('silent and non-finite audio are rejected',()=>{assert.equal(speechHasSignal(new Float32Array(16000)),false);assert.equal(speechHasSignal(new Float32Array(16000).fill(.2)),true);assert.equal(speechHasSignal(new Float32Array([NaN])),false);});
test('SRT bounds timestamps and supplies an end for the final segment',()=>{const srt=subtitleFile([{text:' Hello\nworld ',timestamp:[0,1.25]},{text:'End',timestamp:[1.25,null]}],2.5);assert.match(srt,/00:00:00,000 --> 00:00:01,250\nHello world/);assert.match(srt,/00:00:01,250 --> 00:00:02,500/);assert.equal(subtitleFile([{text:'bad',timestamp:[NaN,2]}],5),'');});
test('AI model definitions pin actual weights and revisions',()=>{for(const m of Object.values(AI_MODELS)){assert.match(m.revision,/^[a-f0-9]{40}$/);assert.ok(m.weights>6000000);assert.equal(m.dtype,'q8');}});
test('AI events cannot carry private input or use a different tool path; samples excluded',async()=>{const inserted=[];const env={HITS:{prepare:()=>({bind:(...args)=>({run:async()=>inserted.push(args)})})}};const send=body=>onRequestPost({env,request:new Request('https://thedollscout.com/api/doc-events',{method:'POST',headers:{origin:'https://thedollscout.com'},body:JSON.stringify(body)})});
 for(const [task,slug] of Object.entries(AI_TOOLS))for(const action of ['complete','sample','export']){const e=`doc_ai_${task}_${action}`;assert.equal((await send({p:'/zh/'+slug,e})).status,204);assert.equal((await send({p:'/json-compare',e})).status,400);assert.equal((await send({p:'/'+slug,e,text:'private'})).status,400);}
 const report=aggregateDocuments(Object.keys(AI_TOOLS).flatMap(task=>[{d:'2026-09-27',path:'/'+AI_TOOLS[task],ref:'',n:2,ev:`doc_ai_${task}_sample`},{d:'2026-09-27',path:'/'+AI_TOOLS[task],ref:'',n:1,ev:`doc_ai_${task}_complete`}]));assert.equal(Object.keys(report.excluded).length,3);assert.equal(Object.keys(report.events).length,3);
});
