// Shared product language: the visible page, discovery files and share UI use
// the same claims. These are capabilities, not a promise of certification.
export const experience = {
  en: {
    eyebrow: 'Your PDF handover toolkit', heroLines: ['Catch PDF issues', 'before you share.'],
    benefits: ['Free to use', 'No file upload', 'No account needed'],
    overview: 'At a glance', forLabel: 'When to use it', outputLabel: 'What you get', limitLabel: 'What to check yourself',
    useCases: ['Before publishing a report, handout or client deliverable.', 'When a team needs one review list for several PDF deliverables.', 'When you need to reuse existing PDF text or check whether text extraction works.', 'When a revised PDF arrives and you need to find text changes.'],
    outputs: ['Page-level findings, manual review prompts, and CSV or JSON exports.', 'One combined findings list for up to 10 PDFs, with partial inspections labelled.', 'Readable text grouped by page, with a local TXT download.', 'Aligned text pages and changed, added, removed or unknown pages.'],
    limitations: ['Reading order, image descriptions and the accuracy of tags require human review. This tool does not certify conformance.', 'Each PDF is limited to 20 MB and 200 inspected pages; each batch to 100 MB and 600 inspected pages.', 'Image-only pages need a separate OCR workflow. Extracted text may have an incorrect reading order.', 'Images, layout and annotations are not compared. Suggested page pairings need review.'],
    toolSeoTitles: ['Free PDF accessibility checker — local preflight', 'Batch PDF audit — review up to 10 files', 'PDF to text — free extraction without upload', 'Compare PDF text — find changes between versions'],
    relatedGuides: 'Understand the next step', reviewed: 'Updated', maintained: 'Published by TDS Document Scout',
    plainText: 'Plain-text version', capabilityIndex: 'Tool capabilities (JSON)', citeTitle: 'Use or cite this guide', citeBody: 'Link to this page for the method and its limitations. Check the update date when reusing the guidance.',
    shareTitle: 'Useful to someone else?', shareBody: 'Share this page with your team. The link opens the tool or guide, with an empty workspace.',
    sharePage: 'Share page', copyPage: 'Copy link', shareUrl: 'Page link', shareCopied: 'Link copied. Your files and results are not included.',
    shareUnavailable: 'Select and copy the text below. Sharing is unavailable in this browser.', shareOpened: 'Share request handed to your device. You choose where it goes.',
    shareSummary: 'Share a redacted summary', summaryIntro: 'Preview exactly what will be shared: counts and limitations only. No filenames, document titles, extracted text or review notes.',
    summaryLabel: 'Summary preview', copySummary: 'Copy summary', nativeSummary: 'Share summary', summaryCopied: 'Summary copied. Check the preview before sending it to someone.',
    summaryTitle: 'TDS Document Scout · preflight summary', summarySample: 'EXAMPLE — fictional sample files', summaryComplete: 'Inspected within tool limits', summaryPartial: 'Partial inspection — unchecked content remains unknown',
    summaryFailures: 'Files not inspected', summaryUnknown: 'Unknown items', summaryDiff: 'Text comparison', summaryChanges: 'Changed / added / removed / unknown pages',
    sharePrivacy: 'Sharing a page sends only its public link. Sharing a summary sends the previewed counts and limitations to the destination you choose, or copies them to your clipboard. It does not include filenames, titles, document text or manual notes. Downloaded full reports have different contents, described above.',
  },
  de: {
    eyebrow: 'Werkzeuge für Ihre PDF-Übergabe', heroLines: ['PDFs prüfen.', 'Probleme früh erkennen.'],
    benefits: ['Kostenlos', 'Kein Datei-Upload', 'Ohne Konto'],
    overview: 'Auf einen Blick', forLabel: 'Wann es hilft', outputLabel: 'Ihr Ergebnis', limitLabel: 'Was Sie selbst prüfen müssen',
    useCases: ['Vor der Veröffentlichung eines Berichts, Handouts oder Kundendokuments.', 'Wenn ein Team eine gemeinsame Prüfliste für mehrere PDFs benötigt.', 'Wenn Sie vorhandenen PDF-Text weiterverwenden oder die Textextraktion prüfen möchten.', 'Wenn eine neue PDF-Version vorliegt und Sie Textänderungen finden müssen.'],
    outputs: ['Seitenbezogene Hinweise, manuelle Prüfpunkte und CSV- oder JSON-Exporte.', 'Eine gemeinsame Liste für bis zu 10 PDFs, mit gekennzeichneten Teilprüfungen.', 'Text nach Seiten gegliedert, als lokale TXT-Datei speicherbar.', 'Zugeordnete Textseiten und geänderte, hinzugefügte, entfernte oder unklare Seiten.'],
    limitations: ['Lesereihenfolge, Bildbeschreibungen und die Richtigkeit der Tags brauchen eine manuelle Prüfung. Keine Konformitätszertifizierung.', 'Je PDF höchstens 20 MB und 200 geprüfte Seiten; je Stapel 100 MB und 600 geprüfte Seiten.', 'Reine Bildseiten benötigen eine separate OCR-Lösung. Extrahierter Text kann eine falsche Lesereihenfolge haben.', 'Bilder, Layout und Anmerkungen werden nicht verglichen. Vorgeschlagene Seitenzuordnungen müssen geprüft werden.'],
    toolSeoTitles: ['PDF-Barrierefreiheit prüfen — kostenlos und lokal', 'PDF-Stapelprüfung — bis zu 10 Dateien prüfen', 'PDF in Text umwandeln — ohne Upload', 'PDF-Text vergleichen — Änderungen zwischen Versionen'],
    relatedGuides: 'Den nächsten Schritt verstehen', reviewed: 'Aktualisiert', maintained: 'Veröffentlicht von TDS Document Scout',
    plainText: 'Reine Textversion', capabilityIndex: 'Werkzeugfunktionen (JSON)', citeTitle: 'Diesen Ratgeber verwenden oder zitieren', citeBody: 'Verlinken Sie diese Seite für die Methode und ihre Grenzen. Beachten Sie bei der Weiterverwendung das Aktualisierungsdatum.',
    shareTitle: 'Auch für andere hilfreich?', shareBody: 'Teilen Sie diese Seite mit Ihrem Team. Der Link öffnet das Werkzeug oder den Ratgeber mit einem leeren Arbeitsbereich.',
    sharePage: 'Seite teilen', copyPage: 'Link kopieren', shareUrl: 'Seitenlink', shareCopied: 'Link kopiert. Ihre Dateien und Ergebnisse sind nicht enthalten.',
    shareUnavailable: 'Markieren und kopieren Sie den Text unten. Teilen ist in diesem Browser nicht verfügbar.', shareOpened: 'Teilanfrage an Ihr Gerät übergeben. Sie wählen das Ziel.',
    shareSummary: 'Zusammenfassung ohne Dokumentinhalte teilen', summaryIntro: 'Die Vorschau zeigt genau, was geteilt wird: nur Zähler und Grenzen. Keine Dateinamen, Dokumenttitel, extrahierten Texte oder Prüfnotizen.',
    summaryLabel: 'Vorschau der Zusammenfassung', copySummary: 'Zusammenfassung kopieren', nativeSummary: 'Zusammenfassung teilen', summaryCopied: 'Zusammenfassung kopiert. Prüfen Sie die Vorschau vor dem Versenden.',
    summaryTitle: 'TDS Document Scout · Prüfzusammenfassung', summarySample: 'BEISPIEL — fiktive Beispieldateien', summaryComplete: 'Innerhalb der Werkzeuggrenzen geprüft', summaryPartial: 'Teilprüfung — ungeprüfter Inhalt bleibt unklar',
    summaryFailures: 'Nicht geprüfte Dateien', summaryUnknown: 'Unklare Punkte', summaryDiff: 'Textvergleich', summaryChanges: 'Geänderte / hinzugefügte / entfernte / unklare Seiten',
    sharePrivacy: 'Beim Teilen einer Seite wird nur ihr öffentlicher Link weitergegeben. Beim Teilen einer Zusammenfassung werden die angezeigten Zähler und Grenzen an Ihr gewähltes Ziel übergeben oder in die Zwischenablage kopiert. Dateinamen, Titel, Dokumenttexte und Prüfnotizen sind nicht enthalten. Vollständige Downloads enthalten die oben beschriebenen Daten.',
  },
  zh: {
    eyebrow: '为 PDF 发布与交付而做', heroLines: ['把 PDF 问题', '留在发布之前。'],
    benefits: ['免费使用', '文件无需上传', '无需注册'],
    overview: '这个工具能帮你做什么', forLabel: '适用场景', outputLabel: '你会得到', limitLabel: '仍需确认',
    useCases: ['发布报告、讲义或向客户交付 PDF 之前。', '团队需要把多份待交付 PDF 汇总成一张处理清单时。', '需要复用 PDF 已有文字，或先判断能否提取文本时。', '收到修订版 PDF，需要找出文字变化时。'],
    outputs: ['按页定位的检查线索、人工复核提示，以及 CSV 或 JSON 报告。', '最多 10 份 PDF 的合并问题清单，明确标记未完成的检查。', '按页分组的可提取文字，以及保存在本地的 TXT 文件。', '对齐的文本页面，以及修改、新增、删除或无法比较的页面。'],
    limitations: ['阅读顺序、图片描述和标签的正确性仍需人工判断；本工具不提供合规认证。', '每份 PDF 最多 20 MB、检查 200 页；每批最多 100 MB、检查 600 页。', '纯图片页面需要另外使用 OCR；提取的文字顺序也可能需要修正。', '不比较图片、版式和批注；相似页面的配对结果需要复核。'],
    toolSeoTitles: ['免费 PDF 无障碍检查工具｜本地预检', 'PDF 批量检查工具｜一次审查 10 份文件', 'PDF 转文字工具｜免费提取，无需上传', 'PDF 文本对比工具｜查找两版文件的变化'],
    relatedGuides: '弄清楚下一步怎么做', reviewed: '更新日期', maintained: '由 TDS 文档侦察站发布',
    plainText: '纯文本版本', capabilityIndex: '工具能力说明（JSON）', citeTitle: '引用与转发这份指南', citeBody: '引用时请链接到本页，让读者同时看到方法与适用边界；再次使用时请核对更新日期。',
    shareTitle: '也让需要的人少走一步。', shareBody: '把工具或指南分享给同事。对方打开的是公开页面，工作区为空。',
    sharePage: '分享页面', copyPage: '复制链接', shareUrl: '页面链接', shareCopied: '链接已复制，不含你的文件和检查结果。',
    shareUnavailable: '此浏览器无法自动分享，请选中下方文字并复制。', shareOpened: '已交给设备的分享功能，请自行选择发送位置。',
    shareSummary: '分享不含文档内容的摘要', summaryIntro: '先确认下面的完整预览：只包含数量与检查边界，不含文件名、文档标题、提取正文或复核笔记。',
    summaryLabel: '待分享摘要预览', copySummary: '复制摘要', nativeSummary: '分享摘要', summaryCopied: '摘要已复制，发送前可再次核对预览。',
    summaryTitle: 'TDS 文档侦察站 · 发布前检查摘要', summarySample: '示例结果 — 使用虚构样本文件', summaryComplete: '已在工具范围内检查', summaryPartial: '部分检查 — 未检查的内容仍为未知',
    summaryFailures: '未能检查的文件', summaryUnknown: '未知项目', summaryDiff: '文本对比', summaryChanges: '修改 / 新增 / 删除 / 无法比较的页面',
    sharePrivacy: '分享页面只发送公开链接。分享摘要会把预览中的数量和边界说明交给你选择的目标应用，或复制到剪贴板，不包含文件名、标题、正文和人工笔记。完整下载报告包含的数据与此不同，见上方说明。',
  },
};
