export const growthCopy={
 en:{
  online:'Online tools',open:'Open-source tools',videos:'Video tutorials',kit:'Creator setup',all:'Explore all',read:'See the workflow',watch:'Watch & try',next:'Try the next step',official:'Official download / setup',source:'Source code',license:'License',docs:'Project documentation',review:'Sources checked',fit:'When it fits',limit:'Know before installing',steps:'A small first task',browser:'Continue in your browser',download:'Download task checklist',faq:'Common questions',
  intro:'Find the right open-source tool for a real task. Compare setup, limits and the next step before installing.',videoIntro:'Short introductions to image, audio and video tools, with creator credits and a practical task you can finish afterwards.',scope:'A curated directory of independent projects. External software has its own requirements and privacy practices. Listed licenses describe the upstream code; model weights, bundled components and hosted services may have different terms.',
  homeOpen:'Build your own toolkit.',homeOpenBody:'Six independent projects for local AI, images, recording and editing. See what each one needs before you install it.',homeVideo:'Watch. Then make something.',homeVideoBody:'Three YouTube introductions, paired with a short exercise and a useful next step.',portalBody:['Finish a task in your browser.','Choose software you can install.','Learn a workflow step by step.'],
  videoNote:'English-language video by the credited creator. TDS adds the task checklist below; we did not produce this video. Older interfaces may differ from current releases.',load:'Load YouTube player',privacy:'Loading connects your browser to YouTube and Google and sends connection information. Privacy-enhanced mode does not mean anonymous viewing. No autoplay.',outside:'Watch on YouTube',fallback:'If the player is unavailable in your region or embedding is disabled, use the YouTube link or the project documentation.',remove:'Close player',
  kitIntro:'Start with the computer and equipment you already own. Upgrade only when a recording or editing test reveals a specific problem.',disclosure:'As an Amazon Associate, TDS earns from qualifying purchases. The links below open Amazon search results, not a tested product ranking. Prices, compatibility and delivery must be checked on the retailer page. EN and ZH links use Amazon US; DE links use Amazon Germany.',shop:'Compare options on Amazon',skip:'Try this before buying',check:'Check before buying',
  kitCards:[['microphone','Clearer speech','Move closer to your existing microphone, reduce room noise and record a short sample in Audacity.','Check the connector, operating-system support, return policy and whether direct headphone monitoring is included. A microphone cannot guarantee accurate transcription.'],['light','More consistent portraits','Face a window and use a plain background. Try the portrait cutout with your existing photo first.','Check power supply, brightness control, stand inclusion and available space. Lighting is optional; the cutout tool does not require special equipment.'],['storage','Room for video projects','Remove disposable exports and check free disk space before adding another drive.','Check your computer’s ports, usable capacity and cable inclusion. Keep a separate backup; an external drive alone is not a backup plan.']],
  kitFaq:[['Do I need to buy equipment to use TDS?','No. TDS browser tools and these checklists are free. Equipment links are optional.'],['Does a purchase unlock AI features?','No. Equipment purchases are made with the retailer and do not unlock TDS features. The separate collector membership does not include paid AI tools.']],
  openFaq:[['Are these TDS tools?','No. These are independently maintained open-source projects. TDS supplies selection notes and links to the original maintainers; downloads and support come from those projects.'],['Does open source mean every model or cloud service is free?','No. Check the specific code license, model license and service terms. Ollama models can have separate licenses; Upscayl Desktop and Upscayl Cloud are different products.']],
  project:{
   upscayl:['Enlarge a small image with local AI.','Use it when you need a larger raster image, then compare the result at full size. Desktop processing needs a compatible Vulkan-capable GPU; a CPU alone is not the normal supported path. Upscayl Cloud is separate.','Upscaling estimates detail; it cannot recover an authoritative original. Faces, lettering and textures can change. Larger dimensions usually increase file size.',['Install from the official desktop download and check GPU support.','Keep the original and upscale a copy of one image.','Inspect faces and text at 100%; reject invented details.','Use TDS image compression to compare export size for the web.']],
   whisper:['Transcribe longer or multilingual audio locally.','Choose the Python project for its model choices and language coverage. Setup needs Python, FFmpeg and enough resources for the selected model. For a short English clip, the TDS browser tool has a smaller setup.','Transcription can hallucinate, especially with silence or background noise. Check language, names and times against the recording. TDS currently accepts English audio up to 60 seconds.',['Install using the upstream setup instructions.','Choose the audio language and a model that fits your hardware.','Test one clip with clear speech before a long job.','Review the transcript and timing against the original.']],
   ollama:['Run a selected language model on your own computer.','Useful when you want a local model workflow and can manage model downloads and memory use. Select a local model and check the current documentation; hosted/cloud features have separate behavior.','The runtime MIT license does not grant rights to every model. Check each model license and keep the service private unless you deliberately secure network access. Generated answers require verification.',['Install from the official download page.','Choose a local model whose license and size fit your task.','Test with public sample text before sensitive material.','If you only need source sentences, try the TDS extractive summarizer.']],
   obs:['Record a screen demonstration.','OBS Studio fits screen recording, scenes and audio sources. Start with its auto-configuration wizard and make a short recording on your actual computer. No streaming account is needed just to record.','Screen recording may capture notifications, private windows and other audio. Preview the frame and listen to the exported file before recording a full tutorial.',['Run the auto-configuration wizard for recording.','Add the intended screen/window and microphone sources.','Record 20 seconds and check framing, sound and file size.','Use an audio editor to export a short WAV/MP3 for transcription.']],
   audacity:['Record and edit speech before transcription.','Audacity is a desktop audio editor for recording, trimming and mixing. It is useful for preparing a short speech clip and listening closely to mistakes.','The linked tutorial was published in 2023; current controls can differ. Review current project documentation. Audacity’s distribution is GPLv3; individual files and components may have other licenses.',['Select the intended microphone and make a short recording.','Listen for clipping and room noise; adjust the source first.','Trim an English sample to 60 seconds or less and export WAV/MP3.','Try the TDS transcript and compare it with the recording.']],
   shotcut:['Edit a screen recording into a short tutorial.','Shotcut provides a desktop timeline for cutting clips, adding titles and exporting video. The selected introductory video is linked by Shotcut’s official tutorial page.','The tutorial is from 2019 and demonstrates fundamentals, not the latest interface. Check current documentation for menus and export options. TDS does not provide a browser video editor.',['Import a short recording and make a copy of the project.','Remove an unwanted beginning or ending on the timeline.','Add a clear title and test a short export.','Prepare a separate web thumbnail with the TDS image compressor.']]
  },
  videoTitles:{upscayl:'Upscayl: your first AI image upscale',audacity:'Audacity: record, edit and prepare speech',shotcut:'Shotcut: a first edit and export'},
  videoGoals:{upscayl:'Make one enlarged image, inspect the result, then prepare a smaller web export.',audacity:'Record a clear short clip and prepare it for an English transcript.',shotcut:'Turn one raw recording into a short edited tutorial and prepare its thumbnail.'}
 },
 de:{
  online:'Online-Werkzeuge',open:'Open Source',videos:'Video-Anleitungen',kit:'Creator-Ausrüstung',all:'Alle ansehen',read:'Ablauf ansehen',watch:'Ansehen & ausprobieren',next:'Nächsten Schritt ausprobieren',official:'Offizieller Download / Einrichtung',source:'Quellcode',license:'Lizenz',docs:'Projektdokumentation',review:'Quellen geprüft',fit:'Wann es passt',limit:'Vor der Installation beachten',steps:'Eine erste kleine Aufgabe',browser:'Im Browser weitermachen',download:'Aufgabenliste herunterladen',faq:'Häufige Fragen',
  intro:'Open-Source-Software für konkrete Aufgaben. Einrichtung, Grenzen und den nächsten Schritt vor der Installation vergleichen.',videoIntro:'Einführungen in Bild-, Audio- und Videowerkzeuge mit Urheberangaben und einer praktischen Folgeaufgabe.',scope:'Eine kuratierte Auswahl unabhängiger Projekte. Externe Software hat eigene Anforderungen und Datenschutzregeln. Die genannten Lizenzen betreffen den Projektcode; Modelle, Komponenten und Cloud-Dienste können andere Bedingungen haben.',
  homeOpen:'Das eigene Toolkit zusammenstellen.',homeOpenBody:'Sechs unabhängige Projekte für lokale KI, Bilder, Aufnahme und Schnitt. Anforderungen vor dem Download prüfen.',homeVideo:'Ansehen. Dann selbst machen.',homeVideoBody:'Drei YouTube-Einführungen mit einer kleinen Übung und einem passenden nächsten Schritt.',portalBody:['Eine Aufgabe im Browser erledigen.','Software zum Installieren auswählen.','Einen Ablauf Schritt für Schritt lernen.'],
  videoNote:'Englischsprachiges Video des genannten Urhebers. TDS ergänzt die Aufgabenliste; das Video stammt nicht von uns. Ältere Oberflächen können von aktuellen Versionen abweichen.',load:'YouTube-Player laden',privacy:'Beim Laden verbindet sich Ihr Browser mit YouTube und Google und übermittelt Verbindungsdaten. Der erweiterte Datenschutzmodus bedeutet keine anonyme Nutzung. Kein Autoplay.',outside:'Auf YouTube ansehen',fallback:'Ist der Player regional nicht verfügbar oder die Einbettung gesperrt, nutzen Sie den YouTube-Link oder die Projektdokumentation.',remove:'Player schließen',
  kitIntro:'Zuerst mit dem vorhandenen Computer und Zubehör arbeiten. Nur aufrüsten, wenn ein konkretes Problem bei einer Testaufnahme sichtbar wird.',disclosure:'Als Amazon-Partner verdient TDS an qualifizierten Verkäufen. Die Links öffnen Amazon-Suchergebnisse, keine getestete Produktrangliste. Preis, Kompatibilität und Lieferung beim Händler prüfen. DE verlinkt Amazon Deutschland; EN und ZH verlinken Amazon USA.',shop:'Optionen bei Amazon vergleichen',skip:'Vor dem Kauf ausprobieren',check:'Vor dem Kauf prüfen',
  kitCards:[['microphone','Verständlichere Sprache','Näher an das vorhandene Mikrofon gehen, Raumgeräusche reduzieren und eine kurze Audacity-Aufnahme prüfen.','Anschluss, Betriebssystem, Rückgabe und direktes Kopfhörer-Monitoring prüfen. Ein Mikrofon garantiert keine richtige Transkription.'],['light','Gleichmäßigere Porträts','Zum Fenster wenden, ruhigen Hintergrund wählen und zuerst ein vorhandenes Foto freistellen.','Stromversorgung, Helligkeitsregelung, Stativ und Platz prüfen. Spezielle Beleuchtung ist für das Freistellen nicht erforderlich.'],['storage','Platz für Videoprojekte','Entbehrliche Exporte entfernen und freien Speicher prüfen, bevor ein weiteres Laufwerk gekauft wird.','Anschlüsse, nutzbare Kapazität und Kabel prüfen. Eine separate Sicherung behalten; ein externes Laufwerk allein ist kein Sicherungsplan.']],
  kitFaq:[['Muss ich Zubehör kaufen, um TDS zu nutzen?','Nein. Browser-Werkzeuge und Aufgabenlisten sind kostenlos. Zubehörlinks sind optional.'],['Schaltet ein Kauf KI-Funktionen frei?','Nein. Der Kauf erfolgt beim Händler und schaltet keine TDS-Funktionen frei. Die getrennte Sammlermitgliedschaft enthält keine bezahlten KI-Werkzeuge.']],
  openFaq:[['Sind das TDS-Werkzeuge?','Nein. Die Open-Source-Projekte werden unabhängig gepflegt. TDS liefert Auswahlhinweise und Links; Downloads und Support kommen von den Projekten.'],['Sind alle Modelle und Cloud-Dienste ebenfalls frei?','Nein. Code-, Modell- und Dienstbedingungen getrennt prüfen. Ollama-Modelle können eigene Lizenzen haben. Upscayl Desktop und Upscayl Cloud sind verschiedene Produkte.']],
  project:{
   upscayl:['Ein kleines Bild mit lokaler KI vergrößern.','Für größere Rasterbilder mit anschließender Sichtprüfung. Desktop-Verarbeitung erfordert eine kompatible Vulkan-GPU; reine CPU-Verarbeitung ist kein regulärer unterstützter Weg. Upscayl Cloud ist separat.','Neue Details sind Schätzungen. Gesichter, Schrift und Texturen können verändert werden; größere Abmessungen erhöhen häufig die Dateigröße.',['Offiziellen Desktop-Download und GPU-Unterstützung prüfen.','Original behalten und eine Kopie vergrößern.','Gesichter und Schrift bei 100 % prüfen.','Mit der TDS-Bildkomprimierung die Exportgröße vergleichen.']],
   whisper:['Längere oder mehrsprachige Audiodateien lokal transkribieren.','Das Python-Projekt bietet verschiedene Modelle und Sprachen. Python, FFmpeg und passende Hardware sind nötig. Für einen kurzen englischen Clip ist das TDS-Browserwerkzeug einfacher.','Bei Stille und Störgeräuschen kann falscher Text entstehen. Namen, Sprache und Zeiten am Original prüfen. TDS verarbeitet derzeit maximal 60 Sekunden englische Sprache.',['Offizielle Einrichtungsanleitung befolgen.','Sprache und ein zur Hardware passendes Modell wählen.','Zunächst einen Clip mit klarer Sprache testen.','Text und Zeiten mit der Aufnahme vergleichen.']],
   ollama:['Ein gewähltes Sprachmodell auf dem eigenen Rechner ausführen.','Für lokale Modellabläufe mit eigener Verwaltung von Downloads und Speicher. Ein lokales Modell wählen und aktuelle Dokumentation lesen; Cloud-Funktionen verhalten sich anders.','Die MIT-Lizenz des Programms gilt nicht automatisch für Modelle. Modelllizenz prüfen und den Dienst nur mit bewusster Absicherung im Netzwerk freigeben. Antworten müssen geprüft werden.',['Offizielle Installation nutzen.','Ein passendes lokales Modell nach Lizenz und Größe wählen.','Zunächst öffentliche Beispieltexte testen.','Für reine Originalsatz-Auswahl den TDS-Zusammenfasser ausprobieren.']],
   obs:['Eine Bildschirmvorführung aufzeichnen.','OBS Studio bietet Bildschirmaufnahme, Szenen und Audioquellen. Mit dem Assistenten und einer kurzen Aufnahme auf dem eigenen Rechner beginnen. Für lokale Aufnahmen ist kein Streaming-Konto nötig.','Benachrichtigungen, private Fenster und weitere Tonquellen können mitgeschnitten werden. Vor einer langen Aufnahme Bild und exportierten Ton prüfen.',['Assistenten für Aufnahme ausführen.','Gewünschtes Fenster und Mikrofon hinzufügen.','20 Sekunden aufnehmen und Bild, Ton und Größe prüfen.','Im Audioeditor einen kurzen WAV/MP3-Ausschnitt für die Transkription exportieren.']],
   audacity:['Sprache vor der Transkription aufnehmen und schneiden.','Desktop-Audioeditor zum Aufnehmen, Kürzen und Mischen. Gut zum Vorbereiten eines kurzen Sprachclips und zum genauen Abhören.','Das Video erschien 2023; aktuelle Bedienelemente können abweichen. Dokumentation beachten. Die Distribution ist GPLv3; einzelne Dateien und Komponenten können andere Lizenzen haben.',['Mikrofon auswählen und kurz aufnehmen.','Auf Übersteuerung und Raumgeräusche hören.','Englischen Ausschnitt auf höchstens 60 Sekunden kürzen und WAV/MP3 exportieren.','TDS-Transkript mit dem Original vergleichen.']],
   shotcut:['Eine Aufnahme zu einem kurzen Tutorial schneiden.','Desktop-Zeitleiste für Schnitt, Titel und Videoexport. Das ausgewählte Einführungsvideo wird auf der offiziellen Tutorial-Seite verlinkt.','Das Video von 2019 zeigt Grundlagen, nicht die aktuelle Oberfläche. Aktuelle Menüs in der Dokumentation prüfen. TDS bietet keinen Browser-Videoschnitt.',['Kurze Aufnahme importieren und Projektkopie erstellen.','Ungewünschten Anfang oder Schluss entfernen.','Titel ergänzen und kurzen Test exportieren.','Ein separates Vorschaubild mit TDS für das Web vorbereiten.']]
  },videoTitles:{upscayl:'Upscayl: das erste Bild mit KI vergrößern',audacity:'Audacity: Sprache aufnehmen und vorbereiten',shotcut:'Shotcut: erster Schnitt und Export'},videoGoals:{upscayl:'Ein Bild vergrößern, Details prüfen und einen kleineren Webexport vorbereiten.',audacity:'Einen klaren Sprachclip für ein englisches Transkript vorbereiten.',shotcut:'Eine Aufnahme zu einem kurzen Tutorial schneiden und ein Vorschaubild vorbereiten.'}
 },
 zh:{
  online:'在线工具',open:'开源工具',videos:'视频教程',kit:'创作设备指南',all:'查看全部',read:'查看使用路线',watch:'观看并练习',next:'动手做下一步',official:'官方下载／安装',source:'源代码',license:'许可证',docs:'项目文档',review:'来源核验日期',fit:'适合什么任务',limit:'安装前要知道',steps:'先完成一个小任务',browser:'回到浏览器继续处理',download:'下载任务清单',faq:'常见问题',
  intro:'按具体任务选择开源工具。先看安装要求、适用范围和下一步，再决定是否下载。',videoIntro:'精选图片、音频与视频工具的 YouTube 入门介绍，保留作者署名，并配上看完就能做的练习。',scope:'这里收录独立维护的开源项目。外部软件有自己的设备要求与隐私规则；所列许可证针对项目代码，模型权重、组件及云服务可能另有条款。',
  homeOpen:'搭建自己的工具箱。',homeOpenBody:'六个独立开源项目，覆盖本地 AI、图片、录音与视频剪辑，下载前先了解要求。',homeVideo:'看懂，再动手。',homeVideoBody:'三个真实 YouTube 入门教程，配有练习清单和下一步工具。',portalBody:['直接在浏览器完成任务。','选择适合安装的软件。','跟着教程学习具体操作。'],
  videoNote:'视频为英文，版权与内容归署名创作者所有；TDS 提供下方练习清单，并非视频制作方。较早的视频界面可能与新版不同。',load:'加载 YouTube 播放器',privacy:'加载后，浏览器会连接 YouTube 与 Google 并发送连接信息。增强隐私模式不代表匿名观看。不会自动播放。',outside:'在 YouTube 观看',fallback:'若所在地区无法播放，或作者关闭了嵌入，请使用 YouTube 链接或项目文档。',remove:'关闭播放器',
  kitIntro:'先用手边的电脑和设备做一次测试。只有录音或制作中出现了具体问题，再考虑购买。',disclosure:'TDS 作为 Amazon 联盟成员，从符合条件的购买中获得佣金。下方链接打开商品搜索结果，并非实测产品排名；请在商家页面核实价格、兼容性和配送。英文及中文链接指向美国 Amazon，德文链接指向德国 Amazon。',shop:'在 Amazon 比较选项',skip:'购买前先试试',check:'购买时核对',
  kitCards:[['microphone','更清楚的人声','靠近现有麦克风，减少房间噪声，用 Audacity 录一小段并试听。','核对接口、操作系统支持、退货条件和耳机实时监听。购买麦克风不能保证转录准确。'],['light','更稳定的人像光线','面对窗户，选择简单背景，先用现有照片试一次人像抠图。','核对供电、亮度调节、是否含支架及摆放空间。抠图工具不要求购买专用灯具。'],['storage','给视频项目留出空间','先清理不需要的导出副本，检查剩余空间，再决定是否增加硬盘。','核对电脑接口、可用容量和随附线材。保留另一份备份；单独一块移动硬盘不等于备份方案。']],
  kitFaq:[['使用 TDS 必须买设备吗？','不需要。浏览器工具和任务清单都免费，设备链接只是可选项。'],['购买会解锁 AI 功能吗？','不会。购买发生在商家平台，不解锁 TDS 功能；独立收藏品会员也不包含付费 AI 工具。']],
  openFaq:[['这些项目是 TDS 开发的吗？','不是。这些是独立维护的开源项目；TDS 提供选择说明和原作者链接，下载与支持由相应项目提供。'],['开源是否代表所有模型和云服务都免费？','不是。代码、模型与服务条款需要分别检查。Ollama 的模型可能另有许可证；Upscayl 桌面版与云服务是不同产品。']],
  project:{
   upscayl:['用本地 AI 放大小图片。','适合需要更大尺寸并愿意逐项检查结果的图片任务。桌面版需要兼容 Vulkan 的 GPU，只有 CPU 不是常规支持方式；Upscayl Cloud 为独立服务。','放大生成的是估计细节，不是恢复可靠原件。人脸、文字和纹理都可能变化；尺寸增大通常也会增加文件体积。',['通过官方下载桌面版，检查 GPU 支持。','保留原图，仅对副本进行放大。','按 100% 大小检查脸部与文字，舍弃虚构细节。','用 TDS 图片压缩比较适合网页的导出体积。']],
   whisper:['在本地转录较长或多语言音频。','Python 项目适合需要更多模型与语言选择的人。安装需 Python、FFmpeg 以及适配所选模型的硬件资源；短英文片段可以先用 TDS 浏览器工具。','静音或背景噪声可能导致虚构转录。请对照录音核实语言、人名与时间。TDS 当前仅处理最多 60 秒英文音频。',['按项目官方说明安装。','选择音频语言与适合设备的模型。','先用一段清晰语音测试，再跑长任务。','对照原音频复核文字与时间。']],
   ollama:['在自己的电脑上运行选定的语言模型。','适合愿意管理模型下载与内存用量的本地 AI 工作流。选择本地模型并参考当前文档；云模型等功能有不同的数据处理方式。','运行程序的 MIT 许可证不覆盖所有模型。分别核实模型许可证；不要在未配置安全措施时把服务暴露给网络。生成答案需要复核。',['从官方页面安装。','按许可证和大小选择合适的本地模型。','先用公开示例测试，再考虑敏感内容。','如果只需保留原句，可尝试 TDS 原文摘要。']],
   obs:['录制屏幕操作演示。','OBS Studio 可配置屏幕录制、场景和音频来源。先运行自动配置向导，再在自己的设备上试录；仅本地录制不需要直播账号。','录屏可能同时收进通知、私人窗口与其它声音。录完整教程之前，先检查画面范围并试听导出文件。',['运行面向录制的自动配置向导。','添加目标窗口及麦克风来源。','试录 20 秒，检查画面、声音和文件大小。','在音频编辑器导出一段 WAV/MP3，再进行转录。']],
   audacity:['录制并整理适合转录的人声。','桌面音频编辑器，可录音、裁剪与混音。适合制作一小段语音素材，并仔细试听错误。','所选教程发布于 2023 年，操作界面可能变化，请结合当前项目文档。发行版为 GPLv3，个别文件或组件可能有其它许可证。',['选择目标麦克风并录一小段。','试听削波与房间噪声，优先调整声源。','裁出不超过 60 秒的英文片段，导出 WAV/MP3。','在 TDS 转录后，对照原录音检查。']],
   shotcut:['把录屏剪成一段工具演示。','桌面时间线适合裁剪、加标题与导出视频。所选入门视频来自 Shotcut 官方教程页的推荐链接。','教程发布于 2019 年，用于学习基本流程，不代表新版界面；具体菜单请查当前文档。TDS 没有浏览器视频剪辑器。',['导入一段录屏并另存项目副本。','在时间线上去掉多余的开头或结尾。','加上清晰标题，先导出一小段测试。','另备一张缩略图，用 TDS 图片压缩处理网页体积。']]
  },videoTitles:{upscayl:'Upscayl：第一次用 AI 放大图片',audacity:'Audacity：录制、剪辑与准备人声',shotcut:'Shotcut：第一次剪辑与导出'},videoGoals:{upscayl:'放大一张图片，检查细节，再准备更小的网页导出版本。',audacity:'录制清楚的短片段，准备进行英文音频转文字。',shotcut:'把原始录屏剪成一段简短教程，并准备独立缩略图。'}
 }
};
