import {projects,videos,reviewed,affiliateUrl} from './growth-data.mjs';
import {growthCopy} from './growth-copy.mjs';
import {hubCopy} from './home-hub.mjs';
const url=(lang,slug)=>`${lang==='en'?'':'/'+lang}/${slug}`;
const event=(name)=>` data-growth-event="doc_${name}"`;
const out=(href,label,e,ev='')=>`<a href="${e(href)}" rel="noopener"${ev?event(ev):''}>${e(label)} ↗</a>`;
const faq=(rows,c,e)=>`<section class="section faq"><h2>${e(c.faq)}</h2>${rows.map(([q,a])=>`<details><summary>${e(q)}</summary><p>${e(a)}</p></details>`).join('')}</section>`;
export function growthTitle(lang,slug){const c=growthCopy[lang];if(slug==='open-source')return c.open;if(slug==='videos')return c.videos;if(slug==='creator-kit')return c.kit;const id=slug.split('/')[1];return slug.startsWith('videos/')?c.videoTitles[id]:`${projects.find(p=>p.id===id).name}: ${c.project[id][0]}`;}
export function growthDescription(lang,slug){const c=growthCopy[lang];if(slug==='open-source')return c.intro;if(slug==='videos')return c.videoIntro;if(slug==='creator-kit')return c.kitIntro;const id=slug.split('/')[1];return slug.startsWith('videos/')?c.videoGoals[id]:c.project[id][1];}
const toolName=(lang,slug)=>({'image-compressor':hubCopy[lang].entries.image[0],'ai-audio-to-text':hubCopy[lang].entries.speech[0],'ai-text-summarizer':hubCopy[lang].entries.summary[0]})[slug];
const card=(lang,p,e)=>{const c=growthCopy[lang];return `<article class="resource-card"><p class="resource-label">${e(p.kind==='ai'?'AI':p.kind.toUpperCase())} · ${e(p.license)}</p><h3><a href="${url(lang,'open-source/'+p.id)}">${e(p.name)}</a></h3><p>${e(c.project[p.id][0])}</p><p class="small">${e(p.platform)}</p><a class="resource-more" href="${url(lang,'open-source/'+p.id)}">${e(c.read)} →</a></article>`;};
const videoCard=(lang,v,e)=>{const c=growthCopy[lang];return `<article class="resource-card video-card"><a class="video-poster" href="${url(lang,'videos/'+v.id)}" aria-label="${e(c.videoTitles[v.id])}"><span class="play-mark" aria-hidden="true">▶</span><span>${e(projects.find(p=>p.id===v.id).name)}</span><small>${v.time} · EN</small></a><h3><a href="${url(lang,'videos/'+v.id)}">${e(c.videoTitles[v.id])}</a></h3><p>${e(c.videoGoals[v.id])}</p><p class="small">YouTube · ${e(v.author)} · ${v.date.slice(0,10)}</p><a href="${url(lang,'videos/'+v.id)}">${e(c.watch)} →</a></article>`;};
export function growthPortals(lang,e){const c=growthCopy[lang];return `<nav class="resource-portals" aria-label="TDS"><a href="#tools"><strong>01 / ${e(c.online)}</strong><span>${e(c.portalBody[0])}</span></a><a href="${url(lang,'open-source')}"${event('library_open_source')}><strong>02 / ${e(c.open)}</strong><span>${e(c.portalBody[1])}</span></a><a href="${url(lang,'videos')}"${event('library_videos')}><strong>03 / ${e(c.videos)}</strong><span>${e(c.portalBody[2])}</span></a></nav>`;}
export function growthHome(lang,e){const c=growthCopy[lang];return `<section class="section resource-section" id="open-source"><div class="resource-heading"><div><p class="eyebrow">${e(c.open)}</p><h2>${e(c.homeOpen)}</h2><p>${e(c.homeOpenBody)}</p></div><a href="${url(lang,'open-source')}"${event('library_open_source')}>${e(c.all)} →</a></div><div class="resource-grid">${projects.slice(0,3).map(p=>card(lang,p,e)).join('')}</div></section><section class="section resource-section" id="videos"><div class="resource-heading"><div><p class="eyebrow">YouTube</p><h2>${e(c.homeVideo)}</h2><p>${e(c.homeVideoBody)}</p></div><a href="${url(lang,'videos')}"${event('library_videos')}>${e(c.all)} →</a></div><div class="resource-grid">${videos.map(v=>videoCard(lang,v,e)).join('')}</div></section>`;}
const checklist=(lang,p,e)=>{const c=growthCopy[lang];return `<section class="section resource-checklist" data-checklist="${p.id}"><h2>${e(c.steps)}</h2><ol>${c.project[p.id][3].map(s=>`<li>${e(s)}</li>`).join('')}</ol><button type="button" data-checklist-download="${p.id}"${event('checklist_'+p.id)}>${e(c.download)} · TXT</button></section>`;};
const next=(lang,p,e,isVideo=false)=>{const c=growthCopy[lang];return `<aside class="resource-next"><div><p class="eyebrow">${e(c.browser)}</p><h2>${e(toolName(lang,p.tool))}</h2><p>${e(isVideo?c.videoGoals[p.id]:c.project[p.id][3].at(-1))}</p></div><a class="button primary" href="${url(lang,p.tool)}"${event((isVideo?'video_tool_':'project_tool_')+p.id)}>${e(c.next)}</a></aside>`;};
const kitLink=(lang,e)=>`<p class="small"><a href="${url(lang,'creator-kit')}"${event('kit_open')}>${e(growthCopy[lang].kit)}</a> · ${e(growthCopy[lang].kitIntro)}</p>`;
export function growthPage(lang,slug,e){const c=growthCopy[lang];const head=`<header class="resource-hero"><p class="eyebrow">TDS / ${e(slug.startsWith('videos')?'YouTube':slug.startsWith('open-source')?c.open:c.kit)}</p><h1>${e(growthTitle(lang,slug))}</h1><p class="answer-lead">${e(growthDescription(lang,slug))}</p></header>`;
 if(slug==='open-source')return head+`<p class="resource-note">${e(c.scope)}</p><div class="resource-grid">${projects.map(p=>card(lang,p,e)).join('')}</div>`+faq(c.openFaq,c,e);
 if(slug==='videos')return head+`<div class="resource-grid">${videos.map(v=>videoCard(lang,v,e)).join('')}</div><p class="resource-note">${e(c.videoNote)}</p>`+kitLink(lang,e);
 if(slug==='creator-kit')return head+`<p class="resource-note">${e(c.disclosure)}</p><div class="resource-grid">${c.kitCards.map(([id,title,free,buy],i)=>{const kind=['mic','light','storage'][i];return `<article class="resource-card"><p class="resource-label">0${i+1}</p><h2>${e(title)}</h2><h3>${e(c.skip)}</h3><p>${e(free)}</p><h3>${e(c.check)}</h3><p>${e(buy)}</p><a href="${e(affiliateUrl(lang,kind))}" rel="sponsored noopener"${event('gear_'+kind)}>${e(c.shop)} ↗</a></article>`;}).join('')}</div>`+faq(c.kitFaq,c,e);
 const id=slug.split('/')[1],p=projects.find(p=>p.id===id),v=videos.find(v=>v.id===id),details=c.project[id];
 if(slug.startsWith('videos/'))return head+`<section class="watch-player" aria-label="YouTube"><div class="player-frame" data-player="${v.id}" data-youtube="${v.youtube}" data-title="${e(v.title)}"><div class="player-placeholder"><span class="play-mark" aria-hidden="true">▶</span><strong>${e(v.title)}</strong><button type="button" class="primary" data-video-load="${v.id}"${event('video_load_'+v.id)}>${e(c.load)}</button></div></div><p class="small">${e(c.privacy)} <a href="https://policies.google.com/privacy" rel="noopener">Google Privacy</a></p><div class="actions"><a href="https://www.youtube.com/watch?v=${v.youtube}" rel="noopener"${event('video_watch_'+v.id)}>${e(c.outside)} ↗</a><button data-video-close="${v.id}" hidden>${e(c.remove)}</button></div></section><p class="editorial-meta">${out(v.channel,v.author,e)} · ${v.date.slice(0,10)} · ${v.time} · EN</p><p>${e(c.videoNote)}</p><p class="small">${e(c.fallback)} ${out(p.docs,c.docs,e)}</p>${checklist(lang,p,e)}${next(lang,p,e,true)}<p><a href="${url(lang,'open-source/'+id)}">${e(p.name)} · ${e(c.fit)}</a></p>${kitLink(lang,e)}`;
 return head+`<div class="resource-detail"><article><h2>${e(c.fit)}</h2><p>${e(details[1])}</p><h2>${e(c.limit)}</h2><p>${e(details[2])}</p></article><aside class="resource-card"><h2>${e(p.name)}</h2><dl><dt>${e(c.license)}</dt><dd>${out(p.licenseUrl,p.license,e)}</dd><dt>Platform</dt><dd>${e(p.platform)}</dd></dl><p>${out(p.site,c.official,e,'project_download_'+p.id)}</p><p>${out('https://github.com/'+p.repo,c.source,e)}</p><p>${out(p.docs,c.docs,e)}</p><p class="small">${e(c.review)}: <time datetime="${reviewed}">${reviewed}</time></p></aside></div>${checklist(lang,p,e)}${next(lang,p,e)}${v?`<p><a href="${url(lang,'videos/'+id)}">${e(c.videoTitles[id])} →</a></p>`:''}<p class="resource-note">${e(c.scope)}</p>`;
}
export function growthText(lang,slug){const c=growthCopy[lang];const p=projects.find(p=>'open-source/'+p.id===slug),v=videos.find(v=>'videos/'+v.id===slug);if(p)return [c.project[p.id][0],c.project[p.id][1],c.project[p.id][2],...c.project[p.id][3],p.platform,p.license,p.licenseUrl,p.site,p.docs,'https://github.com/'+p.repo,'https://thedollscout.com'+url(lang,p.tool),c.scope];if(v)return [c.videoGoals[v.id],v.title,v.author,v.channel,v.date,v.time,'https://www.youtube.com/watch?v='+v.youtube,c.videoNote,...c.project[v.id][3],'https://thedollscout.com'+url(lang,v.tool),c.privacy];if(slug==='creator-kit')return [c.kitIntro,c.disclosure,...c.kitCards.flatMap(a=>a.slice(1)),...c.kitFaq.flat()];return [growthDescription(lang,slug),...(slug==='videos'?videos.flatMap(v=>[c.videoTitles[v.id],c.videoGoals[v.id],v.author,'https://thedollscout.com'+url(lang,'videos/'+v.id)]):projects.flatMap(p=>[p.name,c.project[p.id][0],p.license,'https://thedollscout.com'+url(lang,'open-source/'+p.id)])),...(slug==='videos'?[c.videoNote]:[c.scope,...c.openFaq.flat()])];}
export function growthSchema(lang,slug){const c=growthCopy[lang],v=videos.find(v=>'videos/'+v.id===slug);if(v)return [{'@type':'VideoObject',name:v.title,description:c.videoGoals[v.id],thumbnailUrl:`https://i.ytimg.com/vi/${v.youtube}/hqdefault.jpg`,uploadDate:v.date,duration:v.duration,inLanguage:'en',embedUrl:`https://www.youtube-nocookie.com/embed/${v.youtube}`,url:`https://www.youtube.com/watch?v=${v.youtube}`,creator:{'@type':v.id==='upscayl'?'Organization':'Person',name:v.author,url:v.channel}}];if(slug==='open-source'||slug==='videos'){const rows=slug==='open-source'?projects:videos;return [{'@type':'ItemList',name:growthTitle(lang,slug),numberOfItems:rows.length,itemListElement:rows.map((r,i)=>({'@type':'ListItem',position:i+1,name:slug==='open-source'?r.name:c.videoTitles[r.id],url:'https://thedollscout.com'+url(lang,slug+'/'+r.id)}))},...(slug==='open-source'?[{'@type':'FAQPage',mainEntity:c.openFaq.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))}]:[])];}if(slug==='creator-kit')return [{'@type':'FAQPage',mainEntity:c.kitFaq.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))}];return [];}
