import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const response = await fetch('https://thedollscout.com/api/document-stats', { headers:{ 'User-Agent':'tds-document-probe/1.0', 'x-probe':'1' }, signal:AbortSignal.timeout(20000) });
if (!response.ok) throw new Error('Document metrics HTTP ' + response.status);
const data = await response.json();
if (data.ok !== true || data.since !== '2026-09-25' || !data.events || !data.excluded) throw new Error('Document measurement contract missing');
fs.writeFileSync(path.join(root, 'content/document-metrics.json'), JSON.stringify(data, null, 2) + '\n');
const report = 'Document Scout / 28-day action counts (not unique users): ' + JSON.stringify(data.events) + '\nExcluded CI and sample actions: ' + JSON.stringify(data.excluded) + '\n';
console.log(report);
if (process.env.GITHUB_STEP_SUMMARY) fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, report);
