import {utilityCopy,utilitySources,zones} from './utility-copy.mjs';
import {parseJSONExact,diffJSONExact,fitImage,planMeeting} from '../../document-assets/utility-core.mjs';
export const jsonExample={before:'{"id":9007199254740993,"enabled":false,"regions":["EU","US"]}',after:'{"regions":["EU","US","APAC"],"enabled":true,"id":9007199254740993}'};
export const meetingExample={local:'2026-10-15T09:00',zone:'America/New_York',duration:60,zones:['Europe/London','Europe/Berlin','Asia/Shanghai']};
export const utilityExamples={image:fitImage(1500,1000,1000,1000),json:diffJSONExact(parseJSONExact(jsonExample.before),parseJSONExact(jsonExample.after)),meeting:planMeeting(meetingExample)};
export function utilityText(lang,task){const c=utilityCopy[lang],t=c.tools[task];return [t.intro,c.privacy,t.limits,t.how,t.example,...(task==='json'?[jsonExample.before,jsonExample.after,JSON.stringify(utilityExamples.json)]:task==='meeting'?['2026-10-15T13:00:00Z → 2026-10-15T14:00:00Z']:['1500 × 1000 → 1000 × 667']),...t.faq.flat()];}
export function utilityPage(lang,task,esc,route){const c=utilityCopy[lang],t=c.tools[task],u=c.ui,index={en:1,de:2,zh:3}[lang],zoneNames=Object.fromEntries(zones.map(z=>[z[0],z[index]]));
 const options=zones.map(z=>`<option value="${z[0]}">${esc(z[index])} · ${z[0]}</option>`).join('');
 const field=(id,label,input)=>`<div class="utility-field"><label for="${id}">${esc(label)}</label>${input}</div>`;
 let controls='';
 if(task==='image')controls=`${field('utility-files',u.files,'<input id="utility-files" type="file" accept="image/jpeg,image/png,image/webp,.jpg,.jpeg,.png,.webp" multiple>')}<p id="utility-selected" class="small">${esc(u.empty)}</p><div class="utility-fields">${field('image-format',u.format,'<select id="image-format"><option value="image/webp">WebP</option><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option></select>')}${field('image-width',u.width,'<input id="image-width" type="number" min="1" max="4096" step="1" value="1600" required>')}${field('image-height',u.height,'<input id="image-height" type="number" min="1" max="4096" step="1" value="1600" required>')}${field('image-quality',u.quality,'<input id="image-quality" type="number" min="1" max="100" step="1" value="80" required>')}</div><div class="actions"><button class="primary" type="submit">${esc(u.convert)}</button></div>`;
 if(task==='json')controls=`<div class="utility-json-inputs">${[['before','left'],['after','right']].map(([key,label])=>`<div>${field('json-'+key,u[label],`<textarea id="json-${key}" rows="9" maxlength="524288" spellcheck="false" autocapitalize="off" autocorrect="off"></textarea>`)}${field('json-file-'+key,u.jsonFile,`<input id="json-file-${key}" type="file" accept=".json,.txt,application/json">`)}</div>`).join('')}</div><div class="utility-options"><label><input id="json-sort" type="checkbox" checked> ${esc(u.sort)}</label><label><input id="json-minify" type="checkbox"> ${esc(u.minify)}</label></div><div class="actions"><button class="primary" type="submit" name="operation" value="format">${esc(u.formatJSON)}</button><button type="submit" name="operation" value="compare">${esc(u.compareJSON)}</button></div>`;
 if(task==='meeting')controls=`<div class="utility-fields">${field('time-date',u.date,'<input id="time-date" type="datetime-local" min="1970-01-01T00:00" max="2100-12-31T23:59" required>')}${field('time-zone',u.sourceZone,`<select id="time-zone">${options}</select>`)}${field('time-duration',u.duration,'<input id="time-duration" type="number" min="5" max="480" step="1" value="60" required>')}${field('time-occurrence',u.occurrence,`<select id="time-occurrence"><option value="reject">${esc(u.reject)}</option><option value="earlier">${esc(u.earlier)}</option><option value="later">${esc(u.later)}</option></select>`)}</div>${field('time-title',u.title,'<input id="time-title" maxlength="120" required>')}${field('time-notes',u.notes,'<textarea id="time-notes" rows="2" maxlength="2000"></textarea>')}<fieldset class="utility-zones"><legend>${esc(u.compareZones)}</legend>${zones.map(z=>`<label><input type="checkbox" name="zone" value="${z[0]}"${['Europe/London','Europe/Berlin','Asia/Shanghai'].includes(z[0])?' checked':''}> ${esc(z[index])}</label>`).join('')}</fieldset><div class="actions"><button class="primary" type="submit">${esc(u.plan)}</button></div>`;
 const example=task==='json'?`<div class="utility-json-inputs"><pre>${esc(jsonExample.before)}</pre><pre>${esc(jsonExample.after)}</pre></div><pre>${esc(JSON.stringify(utilityExamples.json,null,2))}</pre>`:task==='image'?'<pre>1500 × 1000 → 1000 × 667</pre>':`<pre>2026-10-15T13:00:00Z → 2026-10-15T14:00:00Z</pre>`;
 return `<div class="tool-heading"><p class="eyebrow">TDS · ${esc(u.all)}</p><h1>${esc(t.name)}</h1><p>${esc(t.intro)}</p></div><form id="utility-form" class="utility-panel" data-utility="${task}"><p class="small">${esc(c.privacy)}</p>${controls}<div class="actions"><button id="utility-sample" type="button">${esc(u.sample)}</button><button id="utility-clear" type="button">${esc(u.clear)}</button></div><p id="utility-status" role="status" aria-live="polite">${esc(u.ready)}</p><p id="utility-sample-note" class="notice" hidden>${esc(u.sampleNote)}</p><noscript>${esc(c.privacy)} JavaScript</noscript></form><section id="utility-result" class="utility-result" tabindex="-1" hidden></section><section class="section prose"><h2>${esc(u.limits)}</h2><p>${esc(t.limits)}</p><h2>${esc(u.method)}</h2><p>${esc(t.how)}</p></section><section class="section prose" id="worked-example"><h2>${esc(u.exampleTitle)}</h2><p>${esc(t.example)}</p>${example}<h3>${esc(u.sources)}</h3><ul>${utilitySources[task].map(([label,url])=>`<li><a href="${url}" rel="noopener">${esc(label)}</a></li>`).join('')}</ul></section><section class="section faq" id="questions"><h2>${esc(u.questions)}</h2>${t.faq.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</section><script id="utility-copy" type="application/json">${JSON.stringify({...u,errors:c.errors,zoneNames,samples:{json:jsonExample,meeting:meetingExample}}).replace(/</g,'\\u003c')}</script><script type="module" src="/document-assets/utility-app.mjs?v=2026-09-27.2"></script>`;
}
