import {sample,validateStory,outcome,validID} from './core.mjs';
const $=id=>document.getElementById(id),lang=document.body.dataset.lang,zh=lang==='zh',t=(en,cn)=>zh?cn:en,base=zh?'/zh/create':'/create';
const hex=()=>crypto.randomUUID().replaceAll('-',''),storageKey='agi-relay-v1';
let state={links:[],measure:false,actor:hex()},story=sample(lang),currentID=null,parent=null,viewParent=null,picks=[],busy=false,lastLink=null;
try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved){state={...state,...saved};if(!Array.isArray(state.links))state.links=[];if(!validID(state.actor))state.actor=hex();}}catch{}
const persist=()=>{localStorage.setItem(storageKey,JSON.stringify(state));};
const status=(s,error=false)=>{$('status').textContent=s;$('status').classList.toggle('error',error);};
const errors={rate_limited:t('The beta limit is reached. Edit a starter now or try AI again tomorrow.','已达到实验期额度。可以直接改写示例，或明天再试 AI。'),ai_unavailable:t('AI is unavailable. Your draft is safe; you can edit it yourself.','AI 暂不可用。草稿保留，你可以继续手动编辑。'),ai_failed:t('AI did not return a valid story. Your draft was not changed. Try a simpler idea later.','AI 未返回完整有效的故事，原草稿未改变。稍后可以尝试更简单的想法。'),unavailable:t('The service is unavailable. Keep your draft and try again later.','服务暂不可用，请保存草稿后稍后再试。'),invalid_story:t('Check all story fields and their length. HTML and control characters are not allowed.','请检查所有故事字段及长度。不能包含 HTML 或控制字符。'),invalid_request:t('Check the required fields and consent boxes.','请检查必填内容及同意选项。'),parent_unavailable:t('The source story is unavailable. Choose a starter to make a new story.','原作已不可用，请选择示例开始新故事。'),unauthorized:t('The recovery key is missing or incorrect. Restore your original backup.','恢复密钥缺失或不正确，请恢复原来的备份。'),depth_limit:t('This relay reached its version limit. Start a new story from a starter.','这条接力已达到版本上限，请从示例开始新故事。'),deleted:t('This version was removed. Edit the story to create a new version.','这个版本已移除，修改故事后可以创建新版本。')};
async function api(body){const r=await fetch('/api/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let d;try{d=await r.json();}catch{throw Error('unavailable');}if(!r.ok||!d.ok)throw Error(d.code||'unavailable');return d;}
async function action(fn){if(busy)return;busy=true;const buttons=[...document.querySelectorAll('button')].filter(b=>!b.disabled);buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){status(errors[e.message]||t('Could not complete that action. Check your connection and device storage, then retry.','操作未完成。请检查网络及本机存储后重试。'),true);}finally{busy=false;buttons.forEach(b=>b.disabled=false);}}
function track(event,id=currentID){if(!state.measure||!id||new URLSearchParams(location.search).has('__qa'))return;api({action:'event',event,id,actor:state.actor,consent:true}).catch(()=>{});}
function showPanel(create){$('create-panel').hidden=!create;$('play-panel').hidden=create;$('tab-play').setAttribute('aria-pressed',String(!create));$('tab-create').setAttribute('aria-pressed',String(create));}
function fillEditor(s){$('title').value=s.title;$('intro').value=s.intro;$('author').value=s.author;for(let i=0;i<3;i++){const r=s.rounds[i];$('scene-'+i).value=r.scene;for(let j=0;j<2;j++){ $('label-'+i+'-'+j).value=r.choices[j].label;$('consequence-'+i+'-'+j).value=r.choices[j].consequence;}}for(let i=0;i<4;i++){$('end-title-'+i).value=s.endings[i].title;$('end-text-'+i).value=s.endings[i].text;} $('editor').dataset.storyLang=s.lang;}
function readEditor(){return validateStory({lang:$('editor').dataset.storyLang||lang,title:$('title').value,intro:$('intro').value,author:$('author').value,rounds:Array.from({length:3},(_,i)=>({scene:$('scene-'+i).value,choices:Array.from({length:2},(_,j)=>({label:$('label-'+i+'-'+j).value,consequence:$('consequence-'+i+'-'+j).value,points:j}))})),endings:Array.from({length:4},(_,i)=>({title:$('end-title-'+i).value,text:$('end-text-'+i).value}))});}
function el(tag,content,cls){const e=document.createElement(tag);if(content!==undefined)e.textContent=content;if(cls)e.className=cls;return e;}
function gameReset(){picks=[];$('story-title').textContent=story.title;$('story-intro').textContent=story.intro;$('byline').textContent=t('By ','作者：')+story.author;$('step-count').textContent='0 / 3';$('game').replaceChildren();$('start').hidden=false;$('start').textContent=t('Start the story','开始故事');$('share').hidden=!currentID;$('report-panel').hidden=!currentID;}
function drawRound(){const i=picks.length,g=$('game');g.replaceChildren();$('start').hidden=true;$('step-count').textContent=(i+1)+' / 3';g.append(el('p',story.rounds[i].scene,'scene'));story.rounds[i].choices.forEach((c,j)=>{const b=el('button',c.label,'choice');b.addEventListener('click',()=>{picks.push(j);g.querySelectorAll('button').forEach(x=>x.disabled=true);b.classList.add('selected');g.append(el('p',c.consequence,'consequence'));const next=el('button',i===2?t('See my ending','看看我的结局'):t('Next choice','下一个选择'),'primary');next.addEventListener('click',()=>{if(picks.length===3)drawEnding();else drawRound();});g.append(next);next.focus();});g.append(b);});g.focus();}
function drawEnding(){const e=outcome(story,picks);$('game').replaceChildren(el('p',t('Your ending','你的结局'),'result-label'),el('p',e.title,'result-title'),el('p',e.text));$('start').hidden=false;$('start').textContent=t('Play again','再玩一次');track('complete');$('game').focus();status(t('Your friend might choose differently. Share this story or change its rules.','朋友也许会做出不同选择。分享这个故事，或改写它的规则。'));}
function remix(){track('remix');parent=currentID||viewParent;fillEditor({...story,author:t('New creator','新作者')});showPanel(true);$('published').hidden=true;status(currentID?t('Your version will link back to the source. Change something and preview it.','你的版本会保留原作来源。改写内容后先试玩一下。'):t('Make the starter your own.','把示例改成你自己的故事。'));$('title').focus();}
function urlFor(id){return location.origin+base+'/'+id;}
function renderLinks(){const target=$('saved-links');target.replaceChildren();if(!state.links.length){target.append(el('p',t('No saved links on this device yet.','这台设备还没有保存作品链接。'),'quiet'));return;}
 for(const item of state.links){if(!validID(item.id))continue;const row=el('div',undefined,'saved-row'),a=el('a',item.title);a.href=urlFor(item.id);row.append(a);const b=el('button',t('Remove my link','移除我的链接'));b.addEventListener('click',()=>{if(!confirm(t('Remove this link? Other people’s remixes will remain.','移除这个链接？其他人已改编的作品会保留。')))return;action(async()=>{await api({action:'delete',id:item.id,owner:item.owner});state.links=state.links.filter(x=>x.id!==item.id);persist();if(currentID===item.id){currentID=null;$('share').hidden=true;$('report-panel').hidden=true;}if(lastLink===item.id){lastLink=null;$('published').hidden=true;}renderLinks();status(t('Link removed. Copies already made by others are not removed.','链接已移除；他人已保存或改编的副本不会被删除。'));});});row.append(b);target.append(row);}}
async function share(id){const url=id?urlFor(id):location.origin+base;if(id)track('share_intent',id);try{if(navigator.share){await navigator.share({title:story.title,text:t('Try my story. What would you choose?','来玩我的故事，你会怎么选？'),url});status(t('Share sheet completed. Delivery is not verified.','分享面板已完成，是否送达由目标应用决定。'));}else{await navigator.clipboard.writeText(url);status(t('Link copied. Send it to a friend.','链接已复制，可以发给朋友。'));}}catch(e){if(e.name==='AbortError'){status(t('Sharing cancelled.','已取消分享。'));return;}status(t('Copy this link: ','请复制这个链接：')+url);}}
$('start').addEventListener('click',()=>{picks=[];drawRound();});$('remix').addEventListener('click',remix);$('tab-create').addEventListener('click',()=>{if(!$('create-panel').hidden)return;if(currentID&&parent!==currentID)remix();else showPanel(true);});$('tab-play').addEventListener('click',()=>showPanel(false));$('back').addEventListener('click',()=>showPanel(false));$('share').addEventListener('click',()=>share(currentID));$('copy-link').addEventListener('click',()=>share(lastLink));
for(const b of document.querySelectorAll('[data-sample]'))b.addEventListener('click',()=>{story=sample(lang,b.dataset.sample);currentID=null;parent=null;viewParent=null;$('lineage').replaceChildren();document.querySelectorAll('.starter').forEach(x=>x.classList.toggle('active',x===b));gameReset();$('start').disabled=false;$('remix').disabled=false;$('tab-create').disabled=false;fillEditor(story);history.replaceState(null,'',base);$('language').href=zh?'/create':'/zh/create';status(t('Editorial example loaded.','已加载编辑示例。'));});
$('generate').addEventListener('click',()=>action(async()=>{if(!$('ai-consent').checked||$('prompt').value.trim().length<8)throw Error('invalid_request');status(t('AI is writing your story. This can take a moment…','AI 正在创作故事，请稍候……'));const d=await api({action:'generate',prompt:$('prompt').value,lang,consent:true});fillEditor(validateStory(d.story));state.draft={story:readEditor(),parent};persist();status(t('AI draft created. Review every choice and ending before sharing.','AI 草稿已生成，请检查每个选项和结局后再分享。'));}));
$('save').addEventListener('click',()=>action(async()=>{state.draft={story:readEditor(),parent};persist();status(t('Draft saved on this device.','草稿已保存到本机。'));}));
$('preview').addEventListener('click',()=>action(async()=>{story=readEditor();viewParent=parent;currentID=null;gameReset();showPanel(false);status(t('Local preview. Create a share link when you are ready.','这是本机预览。准备好后创建分享链接。'));}));
$('editor').addEventListener('submit',event=>{event.preventDefault();action(async()=>{
 if(!$('publish-consent').checked)throw Error('invalid_request');const nextStory=readEditor(),snapshot=JSON.stringify({story:nextStory,parent});
 if(!state.pending||state.pending.snapshot!==snapshot)state.pending={snapshot,nonce:hex(),owner:hex()+hex()};
 state.draft={story:nextStory,parent};persist(); // Recovery key exists on the device before a network write.
 status(t('Creating your share link…','正在创建分享链接……'));
 const d=await api({action:'publish',story:nextStory,parent,consent:true,nonce:state.pending.nonce,owner:state.pending.owner});
 if(!state.links.some(x=>x.id===d.id))state.links.unshift({id:d.id,title:nextStory.title,owner:state.pending.owner});persist();story=nextStory;currentID=d.id;lastLink=d.id;viewParent=null;gameReset();
 $('published-link').textContent=urlFor(d.id);$('published-link').href=urlFor(d.id);$('open-link').href=urlFor(d.id);$('published').hidden=false;renderLinks();track('publish');status(t('Link ready. Anyone with it can play and remix.','链接已创建，获得链接的人可以游玩和改编。'));$('published').scrollIntoView({block:'center'});
 });});
$('measure').checked=!!state.measure;$('measure').addEventListener('change',()=>{state.measure=$('measure').checked;try{persist();}catch{}if(state.measure)track('open');});
$('backup').addEventListener('click',()=>action(async()=>{state.draft={story:readEditor(),parent};const blob=new Blob([JSON.stringify({version:1,draft:state.draft,links:state.links,pending:state.pending},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='relay-private-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);status(t('Keep this backup private. It contains link removal keys.','请私密保管备份，其中含有移除作品链接的密钥。'));}));
$('restore').addEventListener('change',()=>action(async()=>{const f=$('restore').files[0];if(!f||f.size>1000000)throw Error('invalid_request');const b=JSON.parse(await f.text());if(b.version!==1||!Array.isArray(b.links)||b.links.length>200)throw Error('invalid_request');const links=b.links.map(x=>{if(!validID(x.id)||!/^[a-f0-9]{64}$/.test(x.owner)||typeof x.title!=='string'||x.title.length>70)throw Error('invalid_request');return {id:x.id,owner:x.owner,title:x.title};});const draft=b.draft?{story:validateStory(b.draft.story),parent:validID(b.draft.parent)?b.draft.parent:null}:null;const merged=new Map(state.links.map(x=>[x.id,x]));links.forEach(x=>merged.set(x.id,x));state.links=[...merged.values()];if(draft){state.draft=draft;parent=draft.parent;fillEditor(draft.story);showPanel(true);}state.pending=null;persist();renderLinks();status(t('Backup restored.','备份已恢复。'));}));
$('clear').addEventListener('click',()=>{if(!confirm(t('Clear the local draft? Saved link recovery keys will be kept.','清除本机草稿？已发布链接的恢复密钥会保留。')))return;state.draft=null;state.pending=null;parent=null;fillEditor(sample(lang));try{persist();status(t('Local draft cleared.','本机草稿已清除。'));}catch{status(t('Device storage is unavailable.','本机存储不可用。'),true);}});
$('report').addEventListener('click',()=>action(async()=>{await api({action:'report',id:currentID,reason:$('report-reason').value});status(t('Report received for review.','举报已收到，等待审核。'));}));
fillEditor(story);gameReset();renderLinks();
const id=location.pathname.match(/\/create\/([a-f0-9]{32})\/?$/)?.[1];
if(id){$('language').href=(zh?'/create/':'/zh/create/')+id;$('start').disabled=true;$('remix').disabled=true;$('tab-create').disabled=true;status(t('Loading story…','正在加载故事……'));
 fetch('/api/create?id='+id).then(async r=>{const d=await r.json();if(!r.ok||!d.ok)throw Error('not_found');story=validateStory(d.story);currentID=id;parent=null;fillEditor(story);gameReset();$('start').disabled=false;$('remix').disabled=false;$('tab-create').disabled=false;document.querySelectorAll('.starter').forEach(x=>x.classList.remove('active'));if(d.parent){const p=el('p',t('Remixed from ','改编自：')+d.parent.author+' / '),a=el('a',d.parent.title);a.href=urlFor(d.parent.id);p.append(a);$('lineage').append(p);}else if(d.parent_unavailable)$('lineage').textContent=t('The source story was removed.','原作已移除。');status(t('Shared story loaded. Story text stays in its original language.','已加载分享作品，作品保留原始语言。'));track('open');}).catch(()=>{status(t('This story is unavailable. Choose an editorial starter to continue.','这个故事已不可用，可以选择编辑示例继续。'),true);$('story-title').textContent=t('Story unavailable','作品不可用');$('story-intro').textContent='';});
}else if(state.draft){try{fillEditor(validateStory(state.draft.story));parent=validID(state.draft.parent)?state.draft.parent:null;showPanel(true);status(t('Your saved draft is ready to continue.','已恢复本机草稿，可以继续创作。'));}catch{}}
