import {DECK_VERSION} from '../assets/studio/deck-core.mjs';
import {DECK_COPY,deckWorkspace} from '../assets/studio/deck-view.mjs';
import {readFileSync,existsSync} from 'node:fs';
export function buildDeck({layout,railOf,BASE,LOCALE,site,write,pushPage,faqLd}){
 const lang=LOCALE.code==='zh'?'zh':'en',zh=lang==='zh',L=DECK_COPY[lang],path='/studio/proposal-deck',asset=site.base_url+'/studio-assets',guide=path+'/guide';
 // The homepage is already written at this build stage. Keep this small product
 // entry here so the standard final content hash includes the promotion.
 const homeFile=new URL('../dist/'+(zh?'':'en/')+'index.html',import.meta.url);
 if(existsSync(homeFile)){const original=readFileSync(homeFile,'utf8').replace(/<!-- deck-promotion:start -->[\s\S]*?<!-- deck-promotion:end -->/g,'');const promotion=`<!-- deck-promotion:start --><section class="bpj-journey-section" data-deck-promotion><h2><a href="${BASE}${path}?source=home">${zh?'客户提案，直接交付可编辑 PPT':'Deliver your client proposal as editable PowerPoint'}</a></h2><p>${L.intro}</p><p><a href="${BASE}${path}?source=home">${zh?'免费制作提案演示':'Create a proposal deck free'}</a> · <a href="${BASE}${guide}">${zh?'查看提案、复盘与月报示例':'See proposal, review and report examples'}</a></p></section><!-- deck-promotion:end -->`;write('index.html',original.replace('</main>',promotion+'</main>'));}
 const links=`<nav class="crumb"><a href="${BASE}/studio/">${zh?'BPJ 自研工具':'BPJ tools'}</a><span>/</span><a href="${BASE}${path}">ProposalDeck</a><a href="${BASE}${guide}">${zh?'使用说明与示例':'Guide and examples'}</a></nav>`;
 const shell=content=>`${railOf()}<link rel="stylesheet" href="${asset}/deck.css?v=${DECK_VERSION}"><main class="stage deck-main" id="main-content">${links}${content}</main>`;
 const faq=[{q:zh?'这是自动生成 PPT 的 AI Agent 吗？':'Does this automatically run an AI agent?',a:L.aiHint},{q:zh?'可以免费导出和继续修改吗？':'Are exports free and editable?',a:zh?'可以。文字、表格和图表以原生对象导出到 PPTX，讲稿进入演讲者备注。长正文和表格会分页。你可以在 PowerPoint 或兼容软件里继续修改，字体和排版可能随软件变化，请交付前检查。':'Yes. Text, tables and charts are native PPTX objects, with speaker notes. Long text and tables are paginated. Continue editing in PowerPoint or compatible software. Fonts and layout may vary, so review before delivery.'},{q:zh?'哪些功能收费？':'What is paid?',a:L.paid},{q:zh?'客户资料会上传吗？':'Does client material upload?',a:L.privacy}];
 const examples=`<section class="deck-guide"><h2>${zh?'从一份具体交付开始':'Start with a concrete deliverable'}</h2><div class="deck-examples">${[['proposal',L.proposal,zh?'范围、排期、费用与验收边界。':'Scope, schedule, fees and acceptance.'],['review',L.review,zh?'计划与实际、交付图表与下一步。':'Plan versus actual, delivery chart and next steps.'],['report',L.report,zh?'本月交付、客户待决事项与下一轮范围。':'Monthly delivery, client decisions and next scope.']].map(([id,title,desc])=>`<article><h3><a href="${BASE}${path}?example=${id}">${title}</a></h3><p>${desc}</p><small>${zh?'虚构示例，不代表真实客户或业绩':'Fictional example, not a customer or performance claim'}</small></article>`).join('')}</div></section>`;
 const body=shell(`<header class="deck-hero"><h1>${L.title}</h1><p>${L.intro}</p></header><noscript><p>${zh?'请启用 JavaScript 使用编辑和导出功能。下方使用说明无需 JavaScript。':'Enable JavaScript to edit and export. The guide below remains readable.'}</p></noscript>${deckWorkspace(lang,BASE)}${examples}<section class="deck-guide">${faq.map(f=>`<h2>${f.q}</h2><p>${f.a}</p>`).join('')}<p><a href="${BASE}/studio/quote-builder">${zh?'先整理服务报价':'Build a service quote first'}</a> · <a href="${BASE}/studio/video-variants">${zh?'继续制作商品视频':'Create product videos next'}</a></p></section>`)+`<script type="module" src="${asset}/deck-app.mjs?v=${DECK_VERSION}"></script>`;
 write('studio/proposal-deck.html',layout({title:L.title+' - BPJ ProposalDeck',description:L.intro,path,body,wide:true,schema:[{'@context':'https://schema.org','@type':'WebApplication',name:'BPJ ProposalDeck',url:BASE+path,description:L.intro,applicationCategory:'BusinessApplication',operatingSystem:'Web browser',inLanguage:lang,isAccessibleForFree:true,offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}},faqLd(faq)]}));pushPage(BASE+path+'.html','0.9');
 const title=zh?'从 AI 草稿到客户可修改的 PPT':'From an AI draft to an editable client deck';
 const copy=zh?`<h2>一次完整的交付</h2><ol><li>新建项目，填写客户、作者和实际需求。先明确范围与待确认事项。</li><li>已有 AI 草稿时直接导入。也可以复制 AI 改稿任务，交给自己的助手，再导入完整 JSON。Markdown 用 <code>## 标题</code> 分页，<code>Source:</code> 写来源，<code>Notes:</code> 写讲稿。</li><li>逐页核对标题、金额、排期、资料来源。表格和柱状图可在页面中编辑，密集内容建议拆页。</li><li>下载 PPTX 与讲稿，打开文件检查字体、排版与内容。再把项目备份留给自己，方便改稿。</li></ol><h2>什么时候值得用会员</h2><p>如果你只做一份提案，免费导出和本机备份足够。反复给多个客户改稿、需要跨设备恢复时，会员提供云项目与最近 10 个版本。云端只保存文字与结构，不运行 AI，不含自动设计或顾问服务。</p><h2>与其他方案怎么选</h2><table><thead><tr><th>方案</th><th>适合的需求</th><th>本工作台的侧重点</th></tr></thead><tbody><tr><td><a href="https://gamma.app/pricing" rel="noopener">Gamma</a></td><td>希望在一个产品里调用 AI 和设计演示</td><td>使用已有 AI 助手，明确整理客户交付与来源</td></tr><tr><td><a href="https://github.com/hugohe3/ppt-master" rel="noopener">PPT Master</a></td><td>愿意在自己的 Agent 环境里运行完整 PPT 工作流</td><td>浏览器直接编辑并导出，无需本地安装</td></tr><tr><td>PowerPoint / 现有模板</td><td>已经有固定模板与成熟流程</td><td>快速接收结构化 AI 草稿，整理讲稿与改稿版本</td></tr></tbody></table><p>这些是工作方式的差异，并不意味着本工具一定更快或更好。GitHub 星标代表关注度，不能证明客户付费意愿。</p>`:`<h2>A complete delivery</h2><ol><li>Create a project with your client, author and actual brief. Separate agreed scope from open questions.</li><li>Import an existing AI draft, or copy a revision brief to your own assistant and import its complete JSON response. Markdown uses <code>## headings</code> for slides, <code>Source:</code> for evidence and <code>Notes:</code> for speaker notes.</li><li>Review titles, fees, dates and sources. Edit tables and bar charts, and split dense pages.</li><li>Download the PPTX and notes. Open the file to check fonts, layout and content. Keep a project backup for revisions.</li></ol><h2>When membership helps</h2><p>For one proposal, free exports and local backups may be enough. If you revise work for multiple clients across devices, membership adds cloud projects and the latest 10 versions. It stores text and structure only. It does not run AI or include design consulting.</p><h2>Choosing a workflow</h2><table><thead><tr><th>Option</th><th>Useful when</th><th>This workbench focuses on</th></tr></thead><tbody><tr><td><a href="https://gamma.app/pricing" rel="noopener">Gamma</a></td><td>You want AI generation and design inside one product</td><td>Your existing AI assistant, with explicit client scope and sources</td></tr><tr><td><a href="https://github.com/hugohe3/ppt-master" rel="noopener">PPT Master</a></td><td>You run a full presentation workflow in your own agent environment</td><td>Browser editing and export without a local installation</td></tr><tr><td>PowerPoint / your templates</td><td>You already have an established design workflow</td><td>Structured AI draft intake, speaker notes and revision history</td></tr></tbody></table><p>These are workflow differences, not proof that this tool is faster or better. GitHub stars indicate attention, not willingness to pay.</p>`;
 write('studio/proposal-deck/guide.html',layout({title:title+' - BPJ',description:zh?'客户提案、项目复盘与月度报告示例，包含 AI 草稿导入、可编辑 PPTX 导出和云版本保存的真实边界。':'Client proposals, project reviews and monthly reports, with AI draft import, editable PPTX exports and clear cloud-saving limits.',path:guide,body:shell(`<header class="deck-hero"><h1>${title}</h1><p>${L.intro}</p><a href="${BASE}${path}">${zh?'打开工作台':'Open the workbench'}</a></header><section class="deck-guide">${copy}</section>${examples}`),wide:true}));pushPage(BASE+guide+'.html','0.75');
}
