import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
export const MANJU=JSON.parse(readFileSync(new URL('../data/manju.json',import.meta.url),'utf8'));
const ROOT='https://baipiaoji.com/manju/',esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const hash=f=>createHash('sha256').update(readFileSync(new URL('../assets/'+f,import.meta.url))).digest('hex').slice(0,12);
const types={collection:'官方片库',intro:'介绍／预告',search:'平台搜索'};
const itemURL=x=>ROOT+x.id;
const external=(url,label,action='source',id='catalog')=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer" data-mj-action="${action}" data-mj-id="${id}">${esc(label)} <span aria-hidden="true">↗</span></a>`;
const cover=(x,i,large=false)=>`<div class="mj-cover tone-${i%4}${large?' cover-large':''}" aria-hidden="true"><span>${esc(x.format)} / ${x.year}</span><b>${esc(x.title)}</b><small>${esc(x.caption)}</small><i>帧选原创排版 · 非官方海报</i></div>`;
const save=x=>`<button class="mj-save" data-save="${x.id}" aria-pressed="false" aria-label="收藏${esc(x.title)}">＋ 收藏</button>`;
function page({title,description,path='',body,schema=[]}) {
  const url=ROOT+path;
  return `<!doctype html><html lang="zh-Hans"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · 帧选</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#f7f5f0"><link rel="canonical" href="${url}"><link rel="alternate" hreflang="zh-Hans" href="${url}"><link rel="alternate" hreflang="x-default" href="${url}"><meta property="og:title" content="${esc(title)} · 帧选"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${url}"><meta property="og:locale" content="zh_CN"><meta name="twitter:card" content="summary"><link rel="alternate" type="application/rss+xml" title="帧选目录更新" href="${ROOT}feed.xml"><link rel="stylesheet" href="/manju.css?v=${hash('manju.css')}"><script src="/manju.js?v=${hash('manju.js')}" defer></script>${schema.map(s=>`<script type="application/ld+json">${JSON.stringify(s).replaceAll('<','\\u003c')}</script>`).join('')}</head><body><a class="mj-skip" href="#main">跳到内容</a><header class="mj-header"><a class="mj-brand" href="/manju/" aria-label="帧选首页"><span class="mj-mark" aria-hidden="true">帧</span><span>帧选<small>AI 影像与漫剧发现</small></span></a><nav aria-label="主导航"><a href="/manju/">找作品</a><a href="/manju/?saved=1">我的片单 <span data-save-count>0</span></a><a href="/manju/cooperate">创作者入口</a><a href="/">BPJ ↗</a></nav></header><main id="main" tabindex="-1">${body}</main><footer class="mj-footer"><div><strong>故事很多，先找到想看的。</strong><p>免费选片 · 原创整理 · 官方出处</p></div><nav aria-label="页脚"><a href="/manju/method">收录与隐私说明</a><a href="/manju/cooperate?kind=correction">纠错／权利反馈</a><a href="/manju/feed.xml" data-mj-action="feed">目录 RSS</a><a href="/manju/catalog.json">开放资料</a><a href="/account">BPJ 免费账户</a></nav><p>本站不播放或托管视频。当前作品链接无推广佣金，收录不代表平台合作。收藏仅保存在当前浏览器；BPJ 账户不会同步本片单。</p><p>资料核查：${MANJU.updatedAt}。目录更新订阅不是剧集追更通知。</p></footer><p id="mj-toast" role="status" aria-live="polite"></p></body></html>`;
}
function card(x,i){return `<article class="mj-card" data-item="${x.id}" data-genre="${x.genre}" data-format="${x.format}" data-platform="${x.platform}" data-link="${x.linkType}" data-search="${esc([x.title,x.genre,x.format,x.synopsis,x.caption].join(' ').toLowerCase())}"><a class="mj-cover-link" href="${itemURL(x)}" aria-label="查看${esc(x.title)}的选片资料">${cover(x,i)}</a><div class="mj-meta"><span>${x.genre} · ${x.platform}</span><span>${types[x.linkType]}</span></div><h2><a href="${itemURL(x)}">${esc(x.title)}</a></h2><p>${esc(x.synopsis)}</p><div class="mj-card-actions"><a class="mj-detail" href="${itemURL(x)}">选片资料 →</a>${save(x)}</div></article>`;}
export function manjuSearch(){return [{u:ROOT,n:'帧选：AI 影像与漫剧推荐',k:'选片目录',q:'帧选 ai 视频 漫剧 推荐 片单 官方 观看'},...MANJU.items.map(x=>({u:itemURL(x),n:x.title,k:x.format,q:[x.title,x.format,x.genre,x.synopsis].join(' ').toLowerCase()}))];}
export function manjuHome(){return `<section class="bpj-home-agent"><div><p class="bpj-eyebrow">AI 影像与漫剧</p><h2>想找故事？到帧选选一部</h2><p>按题材找作品，查看官方出处，收藏与分享自己的片单。</p></div><a href="/manju/">打开帧选 →</a></section>`;}
export function buildManju({write,pushPage}) {
  // Build manifest uses physical .html paths; the sitemap canonicalizer strips them.
  const publish=(path,html)=>{write('manju/'+(path||'index')+'.html',html);pushPage(ROOT+(path?path+'.html':''),'0.7');};
  const options=k=>[...new Set(MANJU.items.map(x=>x[k]))].map(v=>`<option value="${v}">${v}</option>`).join('');
  const intro=`<section class="mj-intro"><div><p class="mj-kicker">一份有出处的影像片单</p><h1>今晚，进入哪一个故事？</h1><p>从一首诗到一场冒险。按你喜欢的题材，发现 AI 影像与漫剧，找到官方出处。</p></div><aside><b>${String(MANJU.items.length).padStart(2,'0')}</b><span>部作品起步<br>按题材选，不做热度榜</span></aside></section>`;
  const filters=`<section class="mj-catalog" aria-label="作品目录" data-catalog><form class="mj-filters" role="search" onsubmit="return false"><label class="mj-search">找一个故事<input id="mj-query" type="search" placeholder="作品名、题材或情节" maxlength="80"></label><label>题材<select id="mj-genre"><option value="">全部题材</option>${options('genre')}</select></label><label>形态<select id="mj-format"><option value="">全部形态</option>${options('format')}</select></label><label>入口<select id="mj-link"><option value="">全部入口</option>${Object.entries(types).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><button type="button" id="mj-reset">重置</button></form><div class="mj-collection-bar"><div><button type="button" id="mj-saved" aria-pressed="false">只看我的收藏</button><span id="mj-count" role="status" aria-live="polite">${MANJU.items.length} 部作品</span></div><div><button type="button" id="mj-share">分享当前片单 ↗</button><button type="button" id="mj-export">导出收藏</button><button type="button" id="mj-clear">清空收藏</button></div></div><p class="mj-help" id="mj-share-note">收藏存在当前浏览器。分享会生成含公开作品编号的链接；不会带上你的搜索原文。</p><p class="mj-help" id="mj-shared" hidden>正在查看别人分享的片单；收藏后才会加入你的本机片单。</p><div class="mj-grid">${MANJU.items.map(card).join('')}</div><div class="mj-empty" id="mj-empty" hidden><h2>这份片单里还没有匹配的作品</h2><p>试试更短的关键词，或重置筛选。收藏为空时，先在作品上点“收藏”。</p><button type="button" data-reset>查看全部作品</button><a href="/manju/cooperate">推荐一部作品 →</a></div><noscript><p>浏览器未启用 JavaScript。你仍可浏览全部作品、阅读来源并打开官方入口；筛选与本机收藏需要 JavaScript。</p></noscript></section>`;
  const after=`<section class="mj-editorial"><div><p class="mj-kicker">选片小注</p><h2>先看故事，再看技术。</h2><p>这里同时收录 AI 动画、AI 短剧与 AI 漫剧，形态分别标注。选片角度基于公开资料整理，不是全片观后评分。作品的年代和资料出处都在详情里。</p><a href="/manju/method">了解我们如何整理 →</a></div><div><h3>入口也要讲清楚</h3><p>“官方片库”可前往节目合集；“介绍／预告”帮助了解作品；“平台搜索”还需要你核对发布账号。搜索结果可能包含转载，优先选择来源中列明的出品方或官方账号。</p><a href="/manju/cooperate">有一部值得发现的作品？→</a></div></section>`;
  publish('',page({title:'AI 漫剧与 AI 视频推荐：找作品、收藏片单、查看官方出处',description:'帧选整理有来源的中文 AI 漫剧、AI 短剧与动画。按题材筛选、收藏并分享片单，清楚区分官方片库、作品介绍与平台搜索入口。',body:intro+filters+after,schema:[{'@context':'https://schema.org','@type':'CollectionPage',name:'帧选：AI 影像与漫剧发现',url:ROOT,inLanguage:'zh-Hans',mainEntity:{'@type':'ItemList',itemListOrder:'https://schema.org/ItemListUnordered',itemListElement:MANJU.items.map((x,i)=>({'@type':'ListItem',position:i+1,name:x.title,url:itemURL(x)}))}}]}));
  for(const [i,x] of MANJU.items.entries()) {
    const related=MANJU.items.filter(y=>y.id!==x.id).sort((a,b)=>Number(b.genre===x.genre)-Number(a.genre===x.genre)).slice(0,3);
    const body=`<nav class="mj-crumb" aria-label="面包屑"><a href="/manju/">帧选</a><span>/</span><span>${esc(x.title)}</span></nav><article class="mj-work"><div>${cover(x,i,true)}</div><div class="mj-work-text"><p class="mj-kicker">${x.genre} · ${x.format} · ${x.year}</p><h1>${esc(x.title)}</h1><p class="mj-lead">${esc(x.synopsis)}</p><h2>从什么角度选它</h2><p>${esc(x.angle)}</p><div class="mj-go">${external(x.destination,x.cta,'open',x.id)}${save(x)}</div><p class="mj-help">${x.linkType==='search'?'此链接打开平台搜索，可能包含转载或同名内容；请核对发布者。不是已验证的全集直达链接。':x.linkType==='intro'?'此链接是介绍、报道或预告，不是全集播放页。':'已核对节目合集页面；登录、地区与播放条件以官方平台为准。'}</p><dl><div><dt>发行／入口平台</dt><dd>${x.platform}</dd></div><div><dt>入口性质</dt><dd>${types[x.linkType]}</dd></div><div><dt>进度与观看条件</dt><dd>${esc(x.status)}</dd></div></dl></div></article><section class="mj-evidence"><div><h2>AI 使用信息从哪里来</h2><p>${esc(x.aiEvidence)}</p><p>这些是公开资料中的表述，本站没有独立审计制作流程，也没有完整观看测评。AI 短剧与漫剧不是同一种制作形态；本条按来源标注为“${x.format}”。</p></div><div><h2>来源与核查记录</h2><p>${external(x.source,x.publisher,'source',x.id)}</p><p>来源日期：<time>${x.sourceDate}</time><br>资料核查：<time>${x.checkedAt}</time></p><p>核查指阅读来源与确认链接类型，不代表已核验实时更新、付费条件、播放成功或权利链。内容后续可能变化。</p><a href="/manju/cooperate?kind=correction&amp;work=${x.id}">补充官方链接／反馈问题 →</a></div></section><section class="mj-next"><h2>继续发现</h2><p>按题材关联的条目，不是热度或评分排名。</p><div class="mj-next-links">${related.map(y=>`<a href="${itemURL(y)}"><span>${y.genre}</span><b>${esc(y.title)}</b><small>查看资料 →</small></a>`).join('')}</div></section>`;
    publish(x.id,page({title:x.title+'：故事看点与官方出处',description:x.synopsis+' 帧选整理题材、AI 使用说明和来源，收藏作品并查看官方出处。',path:x.id,body,schema:[{'@context':'https://schema.org','@type':'WebPage',name:x.title+'：作品资料',url:itemURL(x),dateModified:x.checkedAt,inLanguage:'zh-Hans',mainEntity:{'@type':'CreativeWork',name:x.title,description:x.synopsis,genre:x.genre,citation:x.source}},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'帧选',item:ROOT},{'@type':'ListItem',position:2,name:x.title,item:itemURL(x)}]}]}));
  }
  publish('method',page({title:'收录、商业合作与隐私说明',path:'method',description:'了解帧选的资料来源、链接类型、赞助边界、本机收藏及提交信息处理方式。',body:`<article class="mj-prose"><a href="/manju/">← 回到片单</a><p class="mj-kicker">帧选的方法</p><h1>推荐的前提，是说清楚依据。</h1><h2>我们整理什么</h2><p>帧选面向中文观众，整理 AI 动画、AI 短剧与漫剧的公开资料、题材和官方出处。三种形态分别标注，收录不表示作品完全由 AI 制作。我们写的是基于资料的选片角度；没有全片观看证据时，不写“亲测好看”，也不发布评分、热度榜或虚构观众评价。</p><h2>如何辨认入口</h2><p>官方片库：指向节目官方合集页面。介绍／预告：指向官方说明或有明确署名的媒体报道，可能含预告，不能当作全集。平台搜索：在相应平台查询作品名称，结果可能含转载、二创或同名作品，需要核对发布者。作品是否仍可播放、是否收费、是否有地区限制，以官方平台为准。</p><h2>日期与更新</h2><p>来源日期是原始资料发布时间；核查日期是本站阅读资料的日期，不是观看测试时间或剧集更新日期。每日网站构建不会自动刷新核查日期。RSS 只提供目录条目更新，不自动监测剧集进度，也不发送追更邮件。</p><h2>收录和收入</h2><p>普通投稿免费，由编辑审核；提交不保证收录。当前目录没有付费赞助，外链没有佣金合同。未来若有专题推广，会单独标明“赞助／广告”，不出售编辑排名，不把付款当成品质认证。商业合作只接受意向，不在线收款、不承诺播放量或收益。</p><h2>内容和权利</h2><p>本站不托管、嵌入、下载或转发正片。封面是本站原创的文字排版，不是作品官方海报。作品名称用于指明资料对象，剧情简介为原创概述，作品及品牌权利归相应权利人。发现错误链接、冒名账号、权利争议或已下架内容，可通过创作者入口的纠错类型提交证据；相关内容将进入人工核查队列。</p><h2>收藏、分享和账户</h2><p>收藏仅保存在当前浏览器的本地存储，清除网站数据会丢失；可用“导出收藏”保留文本备份，也可清空。分享链接只包含公开作品编号和筛选信息，别人打开不会自动改动你的收藏。现有 BPJ 免费账户是独立服务，注册不会同步漫剧收藏，也不等于订阅营销邮件。</p><h2>统计与提交资料</h2><p>页面使用 BPJ 现有统计同意机制，Google Analytics 只有在同意后才启用，可通过页面提供的隐私控件撤回。第一方记录日期、固定操作和公开作品编号等汇总信息，不记录搜索文本、收藏清单、联系方式或唯一访客标识，并尊重 DNT/GPC 信号。操作次数不是独立用户数。</p><p>投稿表单会把作品名、公开链接、所选类型、说明、可选邮箱和提交日期存入网站的私有审核队列，用于处理该次投稿或合作；合作请求必须留下可回复邮箱。资料不会自动公开，不用于自动营销。请勿填写身份证件、支付信息或私人剧本。信息更正或删除请求可使用同一入口并注明原提交信息，由人工核验处理；本站不承诺固定回复时间。</p><a class="mj-button" href="/manju/cooperate">投稿、合作或纠错 →</a></article>`}));
  publish('cooperate',page({title:'作品投稿、推广合作与纠错',path:'cooperate',description:'向帧选提交公开作品资料、专题推广意向或来源纠错。免费收录与商业合作分开审核，不在线收款。',body:`<section class="mj-cooperate"><div><a href="/manju/">← 回到片单</a><p class="mj-kicker">与创作者一起，把故事说清楚</p><h1>让你的作品，<br>被合适的人发现。</h1><p class="mj-lead">提供可核对的作品来源，我们整理它适合怎样的观众。普通投稿免费，合作意向单独处理。</p><h2>三种联系理由</h2><p><b>作品投稿：</b>请给出官方发行链接、题材和 AI 使用说明；收录由编辑判断，不出售排名。</p><p><b>推广合作：</b>讨论清楚标明的专题赞助。请说明目标受众、发行计划和可用物料的权利。首版不在线收费，不承诺触达或播放结果。</p><p><b>纠错反馈：</b>提供有误条目与可核验的替代来源，或说明权利问题。提交进入私有审核队列，不自动公开。</p><p>本站目前没有已公开成交案例或可承诺的推广库存。提交合作意向不会创建订单、扣款或开通订阅。资料只用于处理本次请求；请阅读<a href="/manju/method">收录与隐私说明</a>。</p></div><form id="mj-inquiry"><h2>留下作品与需求</h2><label>联系类型<select name="kind" required><option value="submit">免费作品投稿</option><option value="cooperate">专题推广合作</option><option value="correction">资料纠错／权利反馈</option></select></label><label>作品／团队名称<input name="name" required maxlength="80" autocomplete="organization"></label><label>公开作品或来源链接<input name="url" type="url" required maxlength="600" placeholder="https://" autocomplete="url"></label><label>回复邮箱（合作必填）<input name="email" type="email" maxlength="254" autocomplete="email"></label><label>希望我们了解什么<textarea name="note" required maxlength="1500" rows="6" placeholder="例如：题材、官方发布账号、AI 使用范围，或需要更正的信息。"></textarea></label><div class="mj-honey" aria-hidden="true"><label>请留空<input name="website" tabindex="-1" autocomplete="off"></label></div><label class="mj-consent"><input type="checkbox" name="consent" required>我已阅读收录与隐私说明，同意为处理本次请求保存上述资料。</label><button class="mj-button" type="submit">提交审核</button><p id="mj-form-status" role="status" aria-live="polite">提交成功后会显示接收结果。没有保证收录或回复时间。</p><noscript>提交表单需要 JavaScript；作品目录与来源可直接浏览。</noscript></form></section>`}));
  const exported={...MANJU,notice:'Public-source editorial catalogue, not full-view reviews, streaming, playback verification or real-time episode updates. No sponsored entries or commission links.',items:MANJU.items.map(x=>({...x,url:itemURL(x)}))};
  write('manju/catalog.json',JSON.stringify(exported,null,2)+'\n');
  write('manju/catalog.md','# 帧选：AI 影像与漫剧目录\n\n资料核查 '+MANJU.updatedAt+'。基于公开资料，不是全片测评；非实时追更，不托管视频。\n\n'+MANJU.items.map(x=>`## ${x.title}\n\n${x.synopsis}\n\n形态：${x.format}；题材：${x.genre}；${x.status}\n\n${x.aiEvidence}\n\n来源：[${x.publisher}](${x.source})（${x.sourceDate}），核查：${x.checkedAt}\n\n入口类型：${types[x.linkType]}；[${x.cta}](${x.destination})\n\n[本站条目](${itemURL(x)})\n`).join('\n'));
  write('manju/feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>帧选目录更新</title><link>${ROOT}</link><description>作品条目的编辑更新，不是剧集追更通知。</description><language>zh-cn</language>${MANJU.items.map(x=>`<item><title>${esc(x.title)}</title><link>${itemURL(x)}</link><guid isPermaLink="false">${x.id}:${x.checkedAt}</guid><pubDate>${new Date(x.checkedAt+'T00:00:00Z').toUTCString()}</pubDate><description>${esc(x.synopsis+' 入口：'+types[x.linkType]+'。'+x.status)}</description></item>`).join('')}</channel></rss>`);
}
