import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {INSIGHTS,validateInsights,plotFor,previewFor,previewBlock,metricFor,number,buildInsights,insightSearch,insightsMarkdown} from './manju-insights.mjs';
import {hotCohorts,thumbnailMarkup} from './manju-thumbnails.mjs';
import {buildDiscovery,discoverySearch,genreLinks} from './manju-discovery.mjs';
import {validateManju} from './manju-catalog.mjs';
export const MANJU=JSON.parse(readFileSync(new URL('../data/manju.json',import.meta.url),'utf8'));
validateManju(MANJU);
validateInsights(INSIGHTS,MANJU);
export const MANJU_REVISION=createHash('sha256').update(JSON.stringify([MANJU,INSIGHTS])).digest('hex').slice(0,16);
// Controlled vocabulary: newly added records cannot silently invent navigation categories.
const taxonomy=MANJU.taxonomy;
let SYNC={status:'pending'};try{SYNC=JSON.parse(readFileSync(new URL('../data/manju-sync-status.json',import.meta.url),'utf8'));}catch{}
const currentRank=(title,kind)=>hotCohorts(INSIGHTS).find(c=>c.id.includes(kind))?.records.findIndex(r=>r.title===title)??-1;
const searchWorks=()=>MANJU.items.map(x=>({id:x.id,title:x.title,url:itemURL(x),genre:x.genre,category:x.category,channel:x.channel,tags:x.tags,seriesTitle:x.seriesTitle,firstSeenAt:x.firstSeenAt||x.checkedAt,aiRank:currentRank(x.title,'ai-drama'),comicRank:currentRank(x.title,'comic-drama'),search:[x.title,x.genre,...x.tags,x.format,plotFor(x.id)?.text||x.synopsis,x.caption].join(' ')}));
for(const x of MANJU.items){
  if(!['stories','culture'].includes(x.channel)||!taxonomy.genres.some(g=>g.id===x.category&&g.label===x.genre)||!Array.isArray(x.tags)||(x.recordType!=='discovery'&&!x.tags.length)||x.tags.some(t=>!taxonomy.tags.includes(t))||new Set(x.tags).size!==x.tags.length)throw Error('Invalid catalogue classification: '+x.id);
}
const ROOT='https://baipiaoji.com/manju/',esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const hash=f=>createHash('sha256').update(readFileSync(new URL('../assets/'+f,import.meta.url))).digest('hex').slice(0,12);
const types={collection:'官方片库',intro:'介绍／预告',search:'平台搜索'};
const itemURL=x=>x.recordType==='discovery'?ROOT+'#work-'+x.id:ROOT+x.id;
const external=(url,label,action='source',id='catalog')=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer" data-mj-action="${action}" data-mj-id="${id}">${esc(label)} <span aria-hidden="true">↗</span></a>`;
const cover=(x,i,large=false)=>`<div class="mj-cover tone-${i%4}${large?' cover-large':''}" aria-hidden="true"><span>${esc(x.format)} / ${x.year}</span><b>${esc(x.title)}</b><small>${esc(x.caption)}</small><i>帧选原创排版 · 非官方海报</i></div>`;
const save=x=>`<button class="mj-save" data-save="${x.id}" aria-pressed="false" aria-label="收藏${esc(x.title)}">＋ 收藏</button>`;
function page({title,description,path='',body,schema=[]}) {
  const url=ROOT+path;
  return `<!doctype html><html lang="zh-Hans"><head><meta charset="utf-8"><meta name="manju-catalog-revision" content="${MANJU_REVISION}"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · 帧选</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#f7f5f0"><link rel="canonical" href="${url}"><link rel="alternate" hreflang="zh-Hans" href="${url}"><link rel="alternate" hreflang="x-default" href="${url}"><meta property="og:title" content="${esc(title)} · 帧选"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${url}"><meta property="og:locale" content="zh_CN"><meta name="twitter:card" content="summary"><link rel="alternate" type="application/rss+xml" title="帧选目录更新" href="${ROOT}feed.xml"><link rel="stylesheet" href="/manju.css?v=${hash('manju.css')}">${path?'':`<link rel="stylesheet" href="/manju-home.css?v=${hash('manju-home.css')}">`}<script type="application/json" id="mj-works">${JSON.stringify(path?MANJU.items.map(x=>({id:x.id,title:x.title,url:itemURL(x)})):searchWorks()).replaceAll('<','\\u003c')}</script><script src="/manju-search.js?v=${hash('manju-search.js')}" defer></script><script src="/manju.js?v=${hash('manju.js')}" defer></script><script src="/manju-live-search.js?v=${hash('manju-live-search.js')}" defer></script><script src="/manju-insights.js?v=${hash('manju-insights.js')}" defer></script>${schema.map(s=>`<script type="application/ld+json">${JSON.stringify(s).replaceAll('<','\\u003c')}</script>`).join('')}</head><body${path?'':' class="mj-home"'}><a class="mj-skip" href="#main">跳到内容</a><header class="mj-header"><a class="mj-brand" href="/manju/" aria-label="帧选首页"><span class="mj-mark" aria-hidden="true">帧</span><span>帧选<small>AI 影像与漫剧发现</small></span></a><nav aria-label="主导航"><a href="/manju/">找作品</a><a href="/manju/rankings">数据榜单</a><a href="/manju/topics">选题助手</a><a href="/manju/?saved=1">我的片单 <span data-save-count>0</span></a><a href="/manju/cooperate">创作者入口</a><a href="/">BPJ ↗</a></nav></header><main id="main" tabindex="-1">${body}</main><footer class="mj-footer"><div><strong>故事很多，先找到想看的。</strong><p>免费选片 · 分类整理 · 可追溯来源</p></div><nav aria-label="页脚"><a href="/manju/guide">选剧与数据指南</a><a href="/manju/method">收录与隐私说明</a><a href="/manju/cooperate?kind=correction">纠错／权利反馈</a><a href="/manju/feed.xml" data-mj-action="feed">目录 RSS</a><a href="/manju/catalog.json">开放资料</a><a href="/account">BPJ 免费账户</a></nav><p>本站不播放或托管视频。当前作品链接无推广佣金，收录不代表平台合作。收藏与推荐偏好仅保存在当前浏览器；BPJ 账户不会同步本片单。</p><p>目录资料核查：${MANJU.updatedAt}；榜单资料核查：${INSIGHTS.reviewedAt}。目录更新订阅不是剧集追更通知。</p></footer><p id="mj-toast" role="status" aria-live="polite"></p></body></html>`;
}
function card(x,i){
  const official=INSIGHTS.cohorts.filter(c=>c.metric==='snapshot_heat').flatMap(c=>c.records).find(r=>r.title===x.title&&r.thumbnail)||(x.thumbnail?{url:x.destination,thumbnail:x.thumbnail,title:x.title}:null);
  const discovery=x.recordType==='discovery',plot=plotFor(x.id),preview=previewFor(x.id),metrics=metricFor(x.title),current=metrics.filter(m=>m.cohort.metric==='snapshot_heat');
  const poster=official?thumbnailMarkup(official,{eager:i<6}):`<span class="mj-poster-empty tone-${i%4}"><span>${esc(x.genre)}</span><b>${esc(x.title)}</b><small>未收录官方封面</small></span>`;
  const target=official?.url||(discovery?x.destination:itemURL(x));
  return `<article class="mj-card${discovery?' mj-discovery':''}" id="work-${x.id}" data-item="${x.id}" data-url="${itemURL(x)}" data-channel="${x.channel}" data-has-plot="${Boolean(plot||!discovery)}" data-has-preview="${Boolean(preview)}" data-category="${x.category}" data-tags="${x.tags.join(' ')}" data-genre="${x.genre}" data-format="${x.format}" data-platform="${x.platform}" data-evidence="${x.evidence?.sourceKind==='hongguo-ranking'?'official':discovery?'directory':'editorial'}" data-link="${x.linkType}" data-search="${esc([x.title,x.seriesTitle||'',x.genre,...x.tags,x.format,plot?.text||x.synopsis,x.caption].join(' ').toLowerCase())}">
  <a class="mj-catalog-thumb" href="${esc(target)}" ${target.startsWith(ROOT)?'':'target="_blank" rel="noopener noreferrer"'} data-mj-action="open" data-mj-id="${x.id}" aria-label="${esc(x.title)}，${official?'到红果查看':discovery?'查看来源入口':'查看选片资料'}">${poster}${current.map(m=>`<span class="mj-poster-rank" data-heat-kind="${m.cohort.id.includes('comic-drama')?'hot-comic':'hot-ai'}">${m.cohort.id.includes('comic-drama')?'漫剧':'AI 剧'} #${m.sourceRank||m.cohort.records.findIndex(r=>r.title===x.title)+1}</span>`).join('')}</a>
  <h2>${esc(x.title)}</h2><p class="mj-card-genre">${esc(x.tags.slice(0,2).join(' / ')||x.genre)}</p>
  <div class="mj-card-heat">${current.map(m=>`<a href="/manju/rankings?cohort=${m.cohort.id}" data-heat-kind="${m.cohort.id.includes('comic-drama')?'hot-comic':'hot-ai'}">${number(m.value)} <span>热度</span></a>`).join('')||`<span>${esc(x.format)}</span>`}</div>
  <div class="mj-card-actions">${save(x)}<button type="button" class="mj-save" data-related="${x.id}">找相似</button></div>
  <details class="mj-record"><summary>剧情与来源</summary><div class="mj-record-body"><p class="mj-meta">${esc(x.format)} · ${types[x.linkType]}</p>${plot?`<p>${esc(plot.text)}</p><p class="mj-help">${esc(plot.basis)} ${external(plot.source,'剧情资料来源','source',x.id)}</p>`:discovery?`<p>${esc(x.caption)}</p>`:`<p>${esc(x.synopsis)}</p>`}${preview?`<a class="mj-preview-link" href="/manju/${x.id}#preview">▶ ${preview.kind} · 到原站观看</a>`:''}<div class="mj-tags">${x.tags.map(t=>`<a href="/manju/?channel=${x.channel}&amp;genre=${x.category}&amp;tag=${encodeURIComponent(t)}">${esc(t)}</a>`).join('')}</div><p>${external(x.destination,x.cta||'查看观看入口','open',x.id)}</p><p>${esc(x.aiEvidence)}</p><p>${external(x.source,x.publisher,'source',x.id)}</p><p class="mj-help">资料核查：${x.checkedAt}。${esc(x.status)}</p>${metrics.filter(m=>m.cohort.metric!=='snapshot_heat').map(m=>`<a class="mj-metric-badge" href="/manju/rankings?cohort=${m.cohort.id}">${m.cohort.label}：${number(m.value)}${m.cohort.unit}</a>`).join('')}<a href="/manju/cooperate?kind=correction&amp;work=${x.id}">补充资料／权利反馈</a></div></details></article>`;
}
export function manjuSearch(){return [...insightSearch(),...discoverySearch(MANJU,INSIGHTS),{u:ROOT,n:'帧选：AI 影像与漫剧推荐',k:'选片目录',q:'帧选 ai 视频 漫剧 推荐 片单 官方 观看'},...MANJU.items.map(x=>({u:itemURL(x),n:x.title,k:x.format,genre:x.genre,tags:x.tags,q:[x.title,x.format,x.genre,...x.tags,plotFor(x.id)?.text||x.synopsis].join(' ').toLowerCase()}))];}
export function manjuHome(){return `<section class="bpj-home-agent"><div><p class="bpj-eyebrow">AI 影像与漫剧</p><h2>想找故事？到帧选选一部</h2><p>搜剧名、AI 漫剧或视频，按题材获取推荐；搜不到时自动补查公开资料。</p><form action="/manju/" method="get" role="search" class="bpj-manju-search"><label for="bpj-manju-query">搜索漫剧与视频</label><input id="bpj-manju-query" name="q" type="search" maxlength="60" placeholder="例如：推荐重生逆袭漫剧" required><button type="submit">搜索与推荐 →</button></form></div><div><a href="/manju/">按题材找剧 →</a> <a href="/manju/rankings">红果榜单 →</a> <a href="/manju/topics">选题助手 →</a></div></section>`;}
export function buildManju({write,pushPage}) {
  // Build manifest uses physical .html paths; the sitemap canonicalizer strips them.
  const publish=(path,html)=>{write('manju/'+(path||'index')+'.html',html);pushPage(ROOT+(path?path+'.html':''),'0.7');};
  const options=k=>[...new Set(MANJU.items.map(x=>x[k]))].map(v=>`<option value="${v}">${v}</option>`).join('');
  const channels=MANJU.taxonomy.channels.map(c=>`<button type="button" data-channel-choice="${c.id}" aria-pressed="${c.id==='stories'}"><strong>${c.label}</strong><span>${c.description}</span></button>`).join('');
  const genres=MANJU.taxonomy.genres.map(g=>`<button type="button" data-genre-choice="${g.id}" aria-pressed="false">${g.label}<small data-facet-count></small></button>`).join('');
  const tags=MANJU.taxonomy.tags.filter(t=>MANJU.items.some(x=>x.tags.includes(t))).map(t=>`<button type="button" data-tag-choice="${t}" aria-pressed="false">${t}<small data-facet-count></small></button>`).join('');
  const order=[...MANJU.items].sort((a,b)=>{const x=currentRank(a.title,'ai-drama'),y=currentRank(b.title,'ai-drama');return (x<0?1e9:x)-(y<0?1e9:y);});
  const body=`<section class="mj-browser" id="mj-full-directory" aria-label="搜索与发现">
  <div class="mj-discover-heading"><div><h1>今天，想看哪一部？</h1><p>AI 漫剧、短剧与视频，找到你的下一部。</p></div><a href="/manju/previews">官方视频入口</a></div>
  <form id="mj-search-form" class="mj-search-form" role="search"><label for="mj-query">搜索漫剧与视频</label><div><input id="mj-query" type="search" placeholder="搜剧名、题材，或让帧选推荐" maxlength="60" autocomplete="off" aria-describedby="mj-search-disclosure"><button class="mj-button" type="submit">搜索</button></div></form>
  <div class="mj-search-suggestions"><span>试试</span>${['AI漫剧','AI视频','重生 逆袭','修仙','甜宠'].map(q=>`<button type="button" data-mj-query="${q}">${q}</button>`).join('')}<details id="mj-search-disclosure"><summary>搜索说明</summary><p>搜不到时自动向公开资料来源查询关键词。请勿输入私人信息；只整理资料与观看入口，不托管视频。</p></details></div>
  <section class="mj-catalog" aria-label="作品目录" data-catalog>
  <div class="mj-browse-tabs" aria-label="浏览方式"><button type="button" data-browse="hot-ai" aria-pressed="true">AI 剧热榜</button><button type="button" data-browse="hot-comic" aria-pressed="false">漫剧热榜</button><button type="button" data-browse="all" aria-pressed="false">全部作品</button><button type="button" id="mj-saved" aria-pressed="false">我的片单 <span data-save-count>0</span></button><a href="/manju/rankings">完整榜单</a></div>
  <div class="mj-directory"><fieldset class="mj-facet"><legend>题材</legend><div class="mj-chips"><button type="button" data-genre-choice="" aria-pressed="true">全部题材<small data-facet-count></small></button>${genres}</div></fieldset>
  <div class="mj-secondary-filters"><details class="mj-plot"><summary>剧情标签 <span>重生、逆袭、甜宠……</span></summary><fieldset class="mj-facet"><legend>想看的情节</legend><div class="mj-chips"><button type="button" data-tag-choice="" aria-pressed="true">不限标签<small data-facet-count></small></button>${tags}</div></fieldset></details>
  <div class="mj-filter-tools"><details class="mj-more"><summary>频道与更多筛选</summary><div class="mj-more-fields"><nav class="mj-channels" aria-label="内容频道">${channels}</nav><label>内容形态<select id="mj-format"><option value="">不限形态</option>${options('format')}</select></label><label>入口平台<select id="mj-platform"><option value="">不限平台</option>${options('platform')}</select></label><label>资料来源<select id="mj-evidence"><option value="">全部来源</option><option value="editorial">官方／媒体资料</option><option value="directory">第三方目录资料</option><option value="official">红果官方榜单资料</option></select></label><label>观看入口<select id="mj-link"><option value="">不限入口</option>${Object.entries(types).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>资料完整度<select id="mj-content"><option value="">全部目录记录</option><option value="plot">有剧情概述（28 条）</option><option value="preview">有官方视频入口（4 条）</option></select></label></div></details><button type="button" id="mj-reset">重置</button></div></div></div>
  <div class="mj-results-bar"><div><h2 id="mj-result-heading">AI 剧热榜</h2><span id="mj-count" role="status" aria-live="polite">${MANJU.items.length} 条作品资料</span></div><label>排序<select id="mj-sort"><option value="relevance">相关性／目录顺序</option><option value="hot-ai" selected>AI 剧当前热度</option><option value="hot-comic">漫剧当前热度</option><option value="new">最近收录</option><option value="saved">按收藏偏好</option></select></label></div>
  <p id="mj-result-note" class="mj-help">红果官方热度快照；热度不是播放量。</p><p class="mj-help" id="mj-shared" hidden>正在查看分享片单，收藏后加入本机片单。</p>
  <section id="mj-search-results" hidden aria-label="搜索反馈与相关推荐"><p id="mj-search-status" role="status" aria-live="polite"></p><div id="mj-search-list" class="mj-recommend-list"></div><button type="button" id="mj-search-retry" hidden>重新查询公开资料</button></section>
  <section id="mj-recommendations" hidden aria-labelledby="mj-recommend-title"><div class="mj-recommend-heading"><h2 id="mj-recommend-title">为你继续找</h2><button type="button" id="mj-close-recommendations" aria-label="收起相似推荐">收起</button></div><p id="mj-recommend-note" class="mj-help"></p><div id="mj-recommend-list" class="mj-recommend-list"></div></section>
  <div class="mj-grid">${order.map(card).join('')}</div>
  <nav class="mj-pagination" id="mj-pagination" aria-label="目录分页" hidden><button type="button" id="mj-prev">上一页</button><span id="mj-page-state" role="status"></span><button type="button" id="mj-next">下一页</button></nav>
  <div class="mj-empty" id="mj-empty" hidden><h2>当前筛选没有匹配作品</h2><p>试试取消筛选，或输入完整剧名继续找。</p><button type="button" data-reset>查看全部剧集</button><a href="/manju/cooperate">推荐一部作品</a></div>
  <details class="mj-library-tools"><summary>管理片单与分享</summary><div class="mj-collection-bar"><button type="button" id="mj-share">分享当前片单</button><button type="button" id="mj-export">导出收藏</button><button type="button" id="mj-clear">清空收藏</button></div><p class="mj-help" id="mj-share-note">收藏存在当前浏览器。分享仅含公开作品编号，不含搜索原文。</p></details>
  <noscript><p>以下全部作品可直接阅读；启用 JavaScript 后可筛选、搜索与收藏。</p></noscript></section>
  <div class="mj-home-notes"><p>红果榜单 ${INSIGHTS.reviewedAt} 核查，每日自动检查更新。综合热度不是播放量，不同榜单分别排序。<a href="/manju/sync-status.json">更新状态</a></p><p>共 ${MANJU.items.length} 条作品记录（含分季）。封面引用红果公开图片；缺失时显示剧名。来源 AI 标注未逐部独立核验。<a href="/manju/method">收录说明</a></p><nav aria-label="更多发现">${genreLinks()}<a href="/manju/guide">选剧指南</a><a href="/manju/topics">创作者选题助手</a></nav></div></section>`;
  publish('',page({title:'AI漫剧与短剧推荐：热度榜、题材分类、搜索与选片',description:`从${MANJU.items.length}条 AI 漫剧、短剧与视频资料中找下一部。按红果官方热度快照或题材浏览，搜索剧名、获取相似推荐，未命中时自动补查公开来源。`,body,schema:[{'@context':'https://schema.org','@type':'CollectionPage',name:'帧选：AI 影像与漫剧发现',url:ROOT,inLanguage:'zh-Hans',mainEntity:{'@type':'ItemList',itemListOrder:'https://schema.org/ItemListUnordered',itemListElement:order.map((x,i)=>({'@type':'ListItem',position:i+1,name:x.title,url:itemURL(x)}))}}]}));
  for(const [i,x] of MANJU.items.entries()) {
    if(x.recordType==='discovery')continue;
    const related=MANJU.items.filter(y=>y.id!==x.id&&y.channel===x.channel).sort((a,b)=>(Number(b.category===x.category)*10+b.tags.filter(t=>x.tags.includes(t)).length)-(Number(a.category===x.category)*10+a.tags.filter(t=>x.tags.includes(t)).length)).slice(0,3);
    const body=`<nav class="mj-crumb" aria-label="面包屑"><a href="/manju/">帧选</a><span>/</span><span>${esc(x.title)}</span></nav><article class="mj-work"><div>${cover(x,i,true)}</div><div class="mj-work-text"><p class="mj-kicker">${x.genre} · ${x.format} · ${x.year}</p><h1>${esc(x.title)}</h1><nav class="mj-work-categories" aria-label="作品分类"><a href="/manju/?channel=${x.channel}">${x.channel==='culture'?'文化短片':'剧集'}</a><a href="/manju/?channel=${x.channel}&amp;genre=${x.category}">${x.genre}</a>${x.tags.map(t=>`<a href="/manju/?channel=${x.channel}&amp;genre=${x.category}&amp;tag=${encodeURIComponent(t)}">${esc(t)}</a>`).join('')}</nav><p class="mj-lead">${esc(x.synopsis)}</p><h2>从什么角度选它</h2><p>${esc(x.angle)}</p><div class="mj-go">${external(x.destination,x.cta,'open',x.id)}${save(x)}</div><p class="mj-help">${x.linkType==='search'?'此链接打开平台搜索，可能包含转载或同名内容；请核对发布者。不是已验证的全集直达链接。':x.linkType==='intro'?'此链接是介绍、报道或预告，不是全集播放页。':'已核对节目合集页面；登录、地区与播放条件以官方平台为准。'}</p><dl><div><dt>发行／入口平台</dt><dd>${x.platform}</dd></div><div><dt>入口性质</dt><dd>${types[x.linkType]}</dd></div><div><dt>进度与观看条件</dt><dd>${esc(x.status)}</dd></div></dl></div></article><div id="preview">${previewBlock(x,external)}</div><section class="mj-evidence"><div><h2>AI 使用信息从哪里来</h2><p>${esc(x.aiEvidence)}</p><p>这些是公开资料中的表述，本站没有独立审计制作流程，也没有完整观看测评。AI 短剧与漫剧不是同一种制作形态；本条按来源标注为“${x.format}”。</p></div><div><h2>来源与核查记录</h2><p>${external(x.source,x.publisher,'source',x.id)}</p><p>来源日期：<time>${x.sourceDate}</time><br>资料核查：<time>${x.checkedAt}</time></p><p>核查指阅读来源与确认链接类型，不代表已核验实时更新、付费条件、播放成功或权利链。内容后续可能变化。</p><a href="/manju/cooperate?kind=correction&amp;work=${x.id}">补充官方链接／反馈问题 →</a></div></section><section class="mj-next"><h2>继续发现</h2><p>优先同频道、同题材和相近剧情标签；不是热度或评分排名。</p><div class="mj-next-links">${related.map(y=>`<a href="${itemURL(y)}"><span>${y.genre}</span><b>${esc(y.title)}</b><small>查看资料 →</small></a>`).join('')}</div></section>`;
    publish(x.id,page({title:x.title+'：故事看点与资料出处',description:x.synopsis+' 帧选整理题材、AI 使用说明和来源，收藏作品并查看资料出处。',path:x.id,body,schema:[{'@context':'https://schema.org','@type':'WebPage',name:x.title+'：作品资料',url:itemURL(x),dateModified:x.checkedAt,inLanguage:'zh-Hans',mainEntity:{'@type':'CreativeWork',name:x.title,description:x.synopsis,genre:x.genre,citation:x.source}},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'帧选',item:ROOT},{'@type':'ListItem',position:2,name:x.title,item:itemURL(x)}]}]}));
  }
  publish('method',page({title:'收录、商业合作与隐私说明',path:'method',description:'了解帧选的资料来源、链接类型、赞助边界、本机收藏及提交信息处理方式。',body:`<article class="mj-prose"><a href="/manju/">← 回到片单</a><p class="mj-kicker">帧选的方法</p><h1>推荐的前提，是说清楚依据。</h1><h2>我们整理什么</h2><p>帧选面向中文观众，整理 AI 动画、AI 短剧与漫剧的公开资料、题材和公开出处。目录按“剧集／文化短片”分区，题材与剧情标签采用统一词表，恋爱、家庭、仙侠、末世等单独归类；剧情标签另列。一个作品有一个主题材，可以有多个剧情标签；内容形态、平台和入口不充当题材。只展示当前频道已有作品的分类，不以空目录或未经核实的“完结”标签吸引点击。三种形态分别标注，收录不表示作品完全由 AI 制作。我们写的是基于资料的选片角度；没有全片观看证据时，不写“亲测好看”，不发布无出处评分或虚构观众评价。数据榜单按报告的同平台、同周期指标展示历史快照，不能当作实时全网榜。</p><h2>目录扩容的依据与边界</h2><p>官方／媒体资料包含来源说明与编辑概述；第三方目录资料收录作品名、分类线索、来源记录和查找入口。其中 20 条另附基于第三方剧情资料撰写的简短概述，明确来源与核查范围；不复制他站完整简介或来历不明的评分；公开封面引用的来源与边界见下方“内容和权利”。热度数据单独引用有统计周期的 DataEye 报告及红果官方公开榜单快照，分别标明日期、来源与指标；不采用目录里口径不明的数字。9 月完整官方月榜尚未核实，不以当前值回填。第三方标注“AI漫剧”仅代表该来源的分类，不是本站审计制作流程、确认版权授权或已成功播放。暂缺官方出处的条目明确标注，基础目录记录不单独生成空泛的详情页。</p><p>按作品名去重，不同季明确分列；记录数包含分季，不等于独立 IP 数。首页两榜分别按当前热度降序；目录可选择相关性、分榜热度、最近收录或本机收藏偏好。资料核查时间、来源发布时间与来源报告的上线日期分开，不用上线日期冒充核查日期。已知下架或侵权争议记录进入排除清单，不作为选片推荐。</p><h2>如何辨认入口</h2><p>官方片库：指向节目官方合集或作品详情页。介绍／预告：指向官方说明或有明确署名的媒体报道，可能含预告，不能当作全集。平台搜索：在相应平台查询作品名称，结果可能含转载、二创或同名作品，需要核对发布者。作品是否仍可播放、是否收费、是否有地区限制，以官方平台为准。</p><h2>自动更新与推荐</h2><p>每天读取允许访问的红果公开 AI 剧与漫剧榜单，校验后更新热度、封面和新作品；失败保留上次有效资料，并在首页展示状态。离榜作品保留目录记录，不以旧热度参与当前排序。仅自动采集公开元数据，不下载视频，也不自动生成剧情或观看评价。</p><p>组合搜索要求各关键词匹配，支持部分题材别名，剧名优先于标签与描述。“找相似”根据同频道、题材、标签和系列名推荐并显示理由；收藏偏好仅在本机计算，收藏清单不上传。本站未命中时会将搜索关键词发送到本站补查接口，再查询短剧百科公开搜索页；不发送账户资料。接口仅缓存来源元数据、关键词哈希及短期限流标识，不保存原始 IP，用于限频、去重和每日目录同步，来源资料供最近七天的同步使用，过期缓存随后续请求清理。请勿输入私人信息。</p><h2>日期与更新</h2><p>榜单来源日期是原榜显示的观察日期；核查日期表示成功读取并校验资料，不是观看测试或剧集更新日期。原有编辑记录保留各自核查日期。最近收录按本站首次收录时间排列，不代表作品首播。RSS 提供目录资料更新，不自动监测剧集进度，也不发送追更邮件。</p><h2>收录和收入</h2><p>普通投稿免费，由编辑审核；提交不保证收录。当前目录没有付费赞助，外链没有佣金合同。未来若有专题推广，会单独标明“赞助／广告”，不出售编辑排名，不把付款当成品质认证。商业合作只接受意向，不在线收款、不承诺播放量或收益。</p><h2>内容和权利</h2><p>本站不托管、嵌入、下载或转发正片。热榜及准确匹配的目录记录引用红果公开榜单提供的封面图片地址，用于识别作品并链接官方详情；不在本站保存图片副本。图片权利归原权利人，公开可访问不代表本站取得再授权。未匹配或图片失效时保留文字排版。浏览器加载封面会向图片源站发送请求，设置不发送页面 Referer；这与分析统计开关独立。作品名称用于指明资料对象，剧情简介为原创概述，作品及品牌权利归相应权利人。发现错误链接、冒名账号、权利争议或已下架内容，可通过创作者入口的纠错类型提交证据；相关内容将进入人工核查队列。</p><h2>收藏、分享和账户</h2><p>收藏仅保存在当前浏览器的本地存储，清除网站数据会丢失；可用“导出收藏”保留文本备份，也可清空。分享链接只包含公开作品编号和筛选信息，别人打开不会自动改动你的收藏。现有 BPJ 免费账户是独立服务，注册不会同步漫剧收藏，也不等于订阅营销邮件。</p><h2>统计与提交资料</h2><p>公开页面默认启用 BPJ 现有 Google Analytics 统计，不显示同意弹窗；可通过页脚隐私控件关闭，已保存的拒绝选择继续生效。第一方记录日期、固定操作和公开作品编号等汇总信息，不记录搜索文本、收藏清单、联系方式或唯一访客标识，并尊重 DNT/GPC 信号。操作次数不是独立用户数。</p><p>投稿表单会把作品名、公开链接、所选类型、说明、可选邮箱和提交日期存入网站的私有审核队列，用于处理该次投稿或合作；合作请求必须留下可回复邮箱。资料不会自动公开，不用于自动营销。请勿填写身份证件、支付信息或私人剧本。信息更正或删除请求可使用同一入口并注明原提交信息，由人工核验处理；本站不承诺固定回复时间。</p><a class="mj-button" href="/manju/cooperate">投稿、合作或纠错 →</a></article>`}));
  publish('cooperate',page({title:'作品投稿、推广合作与纠错',path:'cooperate',description:'向帧选提交公开作品资料、专题推广意向或来源纠错。免费收录与商业合作分开审核，不在线收款。',body:`<section class="mj-cooperate"><div><a href="/manju/">← 回到片单</a><p class="mj-kicker">与创作者一起，把故事说清楚</p><h1>让你的作品，<br>被合适的人发现。</h1><p class="mj-lead">提供可核对的作品来源，我们整理它适合怎样的观众。普通投稿免费，合作意向单独处理。</p><h2>三种联系理由</h2><p><b>作品投稿：</b>请给出官方发行链接、题材和 AI 使用说明；收录由编辑判断，不出售排名。</p><p><b>推广合作：</b>讨论清楚标明的专题赞助。请说明目标受众、发行计划和可用物料的权利。首版不在线收费，不承诺触达或播放结果。</p><p><b>纠错反馈：</b>提供有误条目与可核验的替代来源，或说明权利问题。提交进入私有审核队列，不自动公开。</p><p>本站目前没有已公开成交案例或可承诺的推广库存。提交合作意向不会创建订单、扣款或开通订阅。资料只用于处理本次请求；请阅读<a href="/manju/guide">选剧与数据指南</a><a href="/manju/method">收录与隐私说明</a>。</p></div><form id="mj-inquiry"><h2>留下作品与需求</h2><label>联系类型<select name="kind" required><option value="submit">免费作品投稿</option><option value="cooperate">专题推广合作</option><option value="correction">资料纠错／权利反馈</option></select></label><label>作品／团队名称<input name="name" required maxlength="80" autocomplete="organization"></label><label>公开作品或来源链接<input name="url" type="url" required maxlength="600" placeholder="https://" autocomplete="url"></label><label>回复邮箱（合作必填）<input name="email" type="email" maxlength="254" autocomplete="email"></label><label>希望我们了解什么<textarea name="note" required maxlength="1500" rows="6" placeholder="例如：题材、官方发布账号、AI 使用范围，或需要更正的信息。"></textarea></label><div class="mj-honey" aria-hidden="true"><label>请留空<input name="website" tabindex="-1" autocomplete="off"></label></div><label class="mj-consent"><input type="checkbox" name="consent" required>我已阅读收录与隐私说明，同意为处理本次请求保存上述资料。</label><button class="mj-button" type="submit">提交审核</button><p id="mj-form-status" role="status" aria-live="polite">提交成功后会显示接收结果。没有保证收录或回复时间。</p><noscript>提交表单需要 JavaScript；作品目录与来源可直接浏览。</noscript></form></section>`}));
  buildDiscovery({publish,page,write,catalog:MANJU,insights:INSIGHTS,external,plotFor});
  buildInsights({publish,page,external,catalog:MANJU});
  write('manju/sync-status.json',JSON.stringify(SYNC,null,2)+'\n');
  write('manju/insights.json',JSON.stringify(INSIGHTS,null,2)+'\n');
  write('manju/insights.md',insightsMarkdown());
  const exported={...MANJU,insights:'https://baipiaoji.com/manju/insights.json',notice:'Public-source editorial catalogue, not full-view reviews, streaming, playback verification or real-time episode updates. No sponsored entries or commission links.',items:MANJU.items.map(x=>({...x,url:itemURL(x),plot:plotFor(x.id)||null,preview:previewFor(x.id)||null,metrics:metricFor(x.title)}))};
  write('manju/catalog.json',JSON.stringify(exported,null,2)+'\n');
  write('manju/catalog.md','# 帧选：AI 影像与漫剧目录\n\n资料核查 '+MANJU.updatedAt+'。基于公开资料，不是全片测评；非实时追更，不托管视频。\n\n'+MANJU.items.map(x=>`## ${x.title}\n\n${plotFor(x.id)?.text||x.synopsis}\n\n${plotFor(x.id)?.basis||'公开资料概述，非全片测评。'}\n\n频道：${x.channel==='culture'?'文化短片':'剧集'}；形态：${x.format}；题材：${x.genre}；标签：${x.tags.join('、')}；${x.status}\n\n${x.aiEvidence}\n\n来源：[${x.publisher}](${x.source})（${x.sourceDate}），核查：${x.checkedAt}\n\n入口类型：${types[x.linkType]}；[${x.cta}](${x.destination})\n\n[本站条目](${itemURL(x)})\n`).join('\n'));
  write('manju/feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>帧选目录更新</title><link>${ROOT}</link><description>作品条目的编辑更新，不是剧集追更通知。</description><language>zh-cn</language>${MANJU.items.map(x=>`<item><title>${esc(x.title)}</title><link>${itemURL(x)}</link><guid isPermaLink="false">${x.id}:${x.checkedAt}</guid><pubDate>${new Date(x.checkedAt+'T00:00:00Z').toUTCString()}</pubDate><description>${esc(x.synopsis+' 入口：'+types[x.linkType]+'。'+x.status)}</description></item>`).join('')}</channel></rss>`);
}
