import {videoEntry} from './video-business.mjs';
import {COPY} from '../assets/studio/quote-copy.mjs';
import {EDITION} from '../assets/studio/quote-core.mjs';
import {renderWorkspace} from '../assets/studio/quote-view.mjs';
import {buildVideo} from './video-pages.mjs';

// This registry is deliberately separate from data/tools.json (third-party listings).
export const STUDIO_TOOLS=[
  {path:'/work-plan',zh:'按岗位算 AI 方案',en:'AI work planner',zhDesc:'按工作量计算免费额度能否覆盖任务，输出可执行步骤与工具组合。',enDesc:'Check free-tier capacity against your workload, with tools and steps for each task.',zhOutput:'工具方案 · 容量核对 · 可恢复快照',enOutput:'Work plan · capacity check · restorable snapshot'},
  {path:'/studio/quote-compare',zh:'供应商报价比较台',en:'Supplier quote comparison',zhDesc:'核对箱规、起订量、税运费和交期，得到一份带来源与问题清单的比较表。',enDesc:'Check pack sizes, minimum orders, tax, freight and lead times. Export a comparison with sources and open issues.',zhOutput:'到货成本 · 异常提示 · 比较表',enOutput:'Delivered cost · exception review · comparison sheet'},
  {path:'/studio/video-variants',zh:'商品视频变体工作台',en:'Product video variants',zhDesc:'复用商品图和短视频，编辑三个开场、三种画幅，直接导出视频和字幕。',enDesc:'Reuse product images and clips across three openings and three frame sizes. Export videos and subtitles.',zhOutput:'真实成片 · 字幕 · AI 分镜交接包',enOutput:'Video files · subtitles · AI shot brief'},
  {path:'/llm-api-calculator',zh:'免费 API 额度计算器',en:'Free API capacity calculator',zhDesc:'输入调用量和 Token 用量，对照站内已核实的免费档。',enDesc:'Compare your call volume and token usage with the verified free-tier data.'},
  {path:'/subscription-audit',zh:'AI 订阅体检',en:'AI subscription audit',zhDesc:'按实际使用检查哪些订阅有必要保留。',enDesc:'Review which subscriptions fit the way you actually use AI.'},
  {path:'/publish-check',zh:'商用授权核查',en:'Commercial-use check',zhDesc:'依据已核实的条款，检查产出的使用条件。',enDesc:'Check output-use conditions against the verified licence records.'},
  {path:'/tokenizer',zh:'本地 Token 计数器',en:'Local token counter',zhDesc:'在浏览器内分词计数，文本不上传。',enDesc:'Count tokens in your browser without uploading the text.'},
  {path:'/stack-builder',zh:'免费工具栈组装器',en:'Free tool stack builder',zhDesc:'按任务组合工具，并按商用等约束筛选。',enDesc:'Assemble tools for your tasks and filter by constraints such as commercial use.'},
];
export function studioHome(BASE,zh){return `<section class="studio-home" id="studio"><h2><a href="${BASE}/studio/">${zh?'BPJ 自研工具':'Built by BPJ'}</a></h2><p>${zh?'由白嫖计自主设计和开发。输入你的工作要求，得到可以核对、计算和导出的结果。':'Designed and built by BPJ. Bring your work requirements and leave with a result you can inspect, calculate and export.'}</p><div class="studio-home-links">${STUDIO_TOOLS.slice(0,3).map(t=>`<a href="${BASE}${t.path}">${zh?t.zh:t.en}</a>`).join('')}<a href="${BASE}/studio/">${zh?'浏览自研工具':'Explore BPJ tools'}</a></div></section>`;}
export function studioSearch(BASE,zh){return [{u:BASE+'/video/',n:zh?'BPJ 视频工作室':'BPJ Video Studio',k:zh?'自研视频业务':'BPJ video studio',q:zh?'视频 商品 广告 接单 创作者 云项目 会员 字幕 分镜':'video product ads creator client cloud projects membership subtitles'}, {u:BASE+'/studio/',n:zh?'BPJ 自研工具':'Built by BPJ',k:zh?'自研工具':'BPJ tool',q:zh?'自研 原创 bpj 工作 自动化 计算 工具':'bpj first party built original work tools'},...STUDIO_TOOLS.filter(t=>t.path.startsWith('/studio/')).map(t=>({u:BASE+t.path,n:zh?t.zh:t.en,k:zh?'自研工具':'BPJ tool',q:t.path.includes('video')?(zh?'视频 商品 广告 素材 变体 字幕 分镜 导出 配音':'video product ads variant subtitles storyboard export audio'):(zh?'供应商 报价 比价 采购 税 运费 箱规 起订量 报价单 对比':'supplier quote comparison procurement tax freight moq pack size')}))];}
export function buildStudio({layout,railOf,esc,crumbLd,faqLd,BASE,NAME,LOCALE,site,write,pushPage}){
  const zh=LOCALE.code==='zh',lang=zh?'zh':'en',L=COPY[lang];
  const hub=BASE+'/studio/',asset=site.base_url+'/studio-assets';
  const tools=STUDIO_TOOLS.map(t=>({...t,title:zh?t.zh:t.en,desc:zh?t.zhDesc:t.enDesc}));
  const title=zh?'为你的实际工作做的工具':'Tools built for your actual work';
  const description=zh?'BPJ 自研工具：从岗位 AI 方案、报价比较到商品视频制作，输入实际工作要求，核对、计算并导出结果。':'First-party BPJ tools: plan AI work, compare supplier quotes and create product videos using your own requirements, with inspectable calculations and exports.';
  const ownership=zh?'BPJ 自主设计与开发':'Designed and built by BPJ';
  const body=`${railOf()}<link rel="stylesheet" href="${asset}/studio.css?v=${EDITION}"><main class="stage studio-main" id="main-content"><nav class="crumb"><a href="${BASE}/">${esc(NAME)}</a><i>/</i><span>${L.back}</span></nav>
    <header class="studio-hero"><span class="studio-sign">${ownership}</span><h1>${title}</h1><p>${description}</p><p>${zh?'这里的工具由 BPJ 开发与维护，可以直接完成具体任务。第三方产品的收录与评测，请看':'These tools are developed and maintained by BPJ to complete specific tasks. For listings and reviews of third-party products, visit the'} <a href="${BASE}/#chat">${zh?'外部工具目录':'external tool directory'}</a>${zh?'。':'.'}</p></header>
    ${videoEntry(BASE,zh,'studio')}<div class="studio-rows">${tools.slice(0,3).map(t=>`<article class="studio-product"><span class="studio-meta">${zh?'BPJ 自研 · 浏览器工具':'BPJ original · browser tool'}</span><h2><a href="${BASE}${t.path}">${esc(t.title)}</a></h2><p>${esc(t.desc)}</p><p class="quote-note">${esc(zh?t.zhOutput:t.enOutput)}</p><a class="studio-button primary" href="${BASE}${t.path}">${zh?'打开工具':'Open tool'}</a></article>`).join('')}</div>
    <section class="studio-tools"><h2>${zh?'更多自研工具':'More tools built by BPJ'}</h2><ul>${tools.slice(3).map(t=>`<li><a href="${BASE}${t.path}">${esc(t.title)}</a><p>${esc(t.desc)}</p></li>`).join('')}</ul></section>
    <section class="studio-info"><h2>${zh?'先完成工作，再决定是否需要进阶服务':'Finish a task, then decide what else you need'}</h2><p>${zh?'岗位方案计算、报价比较、商品视频制作与导出均可免费使用。岗位规划器和视频项目可通过现有 BPJ 会员保存到云端并保留版本；报价比较台目前提供免费本机保存。各工具会在操作前说明是否需要注册或会员。':'Work-plan calculations, quote comparison, product videos and exports are free. The planner and video projects support cloud saving and version history through existing BPJ membership; the quote tool currently offers free local drafts. Individual tools explain registration or membership requirements before use.'}</p><p>${zh?'自研表示工具的开发归属，不表示背书任何第三方产品，也不保证工作收入。':'First-party identifies who develops the tool. It does not endorse a third-party vendor or guarantee earnings.'}</p></section></main>`;
  write('studio/index.html',layout({title:`${zh?'BPJ 自研工具':'Built by BPJ'} - ${NAME}`,description,path:'/studio/',body,wide:true,schema:[crumbLd([{name:NAME,url:BASE+'/'},{name:L.back,url:hub}]),{'@context':'https://schema.org','@type':'CollectionPage',name:title,url:hub,description,mainEntity:{'@type':'ItemList',itemListElement:tools.map((t,i)=>({'@type':'ListItem',position:i+1,name:t.title,url:BASE+t.path}))}}]}));
  pushPage(hub,'0.9');
  const FAQ=[{q:L.scopeTitle,a:L.scope},{q:L.methodTitle,a:L.method},{q:L.freeTitle,a:L.free}];
  const qpath='/studio/quote-compare',url=BASE+qpath;
  const quoteBody=`${railOf()}<link rel="stylesheet" href="${asset}/studio.css?v=${EDITION}"><main class="stage studio-main" id="main-content"><nav class="crumb"><a href="${BASE}/">${esc(NAME)}</a><i>/</i><a href="${hub}">${L.back}</a><i>/</i><span>${L.title}</span></nav><header class="studio-hero"><span class="studio-sign">${ownership}</span><h1>${L.title}</h1><p>${L.intro}</p></header><noscript><p class="quote-notice">${zh?'请启用 JavaScript 进行本地计算。下方仍可阅读规则与适用范围。':'Enable JavaScript for local calculations. The rules and scope remain readable below.'}</p></noscript>${renderWorkspace(lang)}<section class="studio-info">${FAQ.map(f=>`<h2>${f.q}</h2><p>${f.a}</p>`).join('')}</section></main><script type="module" src="${asset}/quote-app.mjs?v=${EDITION}"></script>`;
  write('studio/quote-compare.html',layout({title:`${L.title} - BPJ ${zh?'自研工具':'original tools'}`,description:L.intro,path:qpath,body:quoteBody,wide:true,schema:[crumbLd([{name:NAME,url:BASE+'/'},{name:L.back,url:hub},{name:L.title,url}]),{'@context':'https://schema.org','@type':'WebApplication',name:L.title,url,description:L.intro,applicationCategory:'BusinessApplication',operatingSystem:'Web browser',inLanguage:lang,softwareVersion:EDITION,creator:{'@type':'Organization',name:'BPJ',url:site.base_url},isAccessibleForFree:true,offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}},faqLd(FAQ)]}));
  pushPage(url+'.html','0.9');
  buildVideo({layout,railOf,esc,crumbLd,faqLd,BASE,NAME,LOCALE,site,write,pushPage});
}
