import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
import {digest,seconds,fulfill} from '../lib/ad-commerce.js';
import {NETWORKS,ensureWeb3,web3Settings,web3Health,createWeb3Order,web3Order,web3Status,verifyTransfer,deliverWeb3,scanOrder,watchWeb3,formatUnits} from '../lib/ad-web3.js';
import {onRequestPost as endpoint} from '../functions/api/ad-web3.js';
import {onRequestPost as watchEndpoint} from '../functions/api/ad-web3-watch.js';
import {onRequestGet as ads} from '../functions/api/ads.js';
function db(){const sql=new DatabaseSync(':memory:');return {sql,failAt:null,prepare(query){return {args:[],bind(...a){this.args=a;return this;},async first(){return sql.prepare(query).get(...this.args)||null;},async all(){return {results:sql.prepare(query).all(...this.args)};},async run(){return {meta:{changes:sql.prepare(query).run(...this.args).changes}};},query};},async batch(items){sql.exec('BEGIN');try{const out=[];for(const [i,s]of items.entries()){if(i===this.failAt)throw Error('db failure');out.push({meta:{changes:sql.prepare(s.query).run(...s.args).changes}});}sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
const addr='0x'+'1'.repeat(40),TX='0x'+'a'.repeat(64),BH='0x'+'b'.repeat(64),topic='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef';
const envFor=HITS=>({HITS,ADS_WEB3_ENABLED:'true',ADS_WALLET_CHAIN:'bsc',ADS_WALLET:addr,ADS_WEB3_PRICE_USD:'49.00',ADS_WEB3_RPC_URL:'https://rpc.example.org',ADS_WATCH_SECRET:'s'.repeat(64),ADS_DAYS:'30'});
// Keep mocked block timestamps and order creation on one clock. Crossing a real
// second between setup() and order() otherwise invents a pre-order payment.
const realNow=Date.now,fixtureNow=realNow();Date.now=()=>fixtureNow;
let finalHeight=1000,blockTime=seconds(),receipt=null,logs=[],rpcError=false,chainId='0x38',precision=18;
const oldFetch=globalThis.fetch;
globalThis.fetch=async(url,opt)=>{const b=JSON.parse(opt.body);if(rpcError)return Response.json({error:{code:-1}});let result;
 if(b.method==='eth_chainId')result=chainId;
 else if(b.method==='eth_call')result='0x'+precision.toString(16);
 else if(b.method==='eth_getBlockByNumber')result={number:'0x'+finalHeight.toString(16),timestamp:'0x'+blockTime.toString(16),hash:BH};
 else if(b.method==='eth_getTransactionReceipt')result=receipt;
 else if(b.method==='eth_getLogs')result=logs;
 else throw Error('unexpected RPC '+b.method);
 return Response.json({jsonrpc:'2.0',id:1,result});
};
async function setup(extra={}){finalHeight=1000;blockTime=seconds();receipt=null;logs=[];rpcError=false;chainId='0x38';precision=18;const d=db(),env={...envFor(d),...extra};if(env.ADS_WALLET_CHAIN==='base-sepolia'){chainId='0x14a34';precision=6;}await ensureWeb3(d);await watchWeb3(env);return {d,env};}
const token=n=>n.toString(16).padStart(64,'0');
async function order(env,n=1){const t=token(n);await createWeb3Order(env,{name:'Tool '+n,url:'https://tool'+n+'.example.org',pitch:'A workflow tool',cat:'coding',lang:'en'},t,'ip'+n);return web3Order(env.HITS,(await digest(t)).slice(0,32));}
function receiptFor(row,change={}){const raw=BigInt(row.amount_units)*10n**BigInt(NETWORKS[row.chain].decimals-6);return {transactionHash:TX,status:'0x1',blockNumber:'0x3e8',blockHash:BH,logs:[{address:row.contract,transactionHash:TX,topics:[topic,'0x'+'0'.repeat(64),'0x'+row.recipient_hex.padStart(64,'0')],data:'0x'+raw.toString(16).padStart(64,'0')}],...change};}
async function verified(env,row,tx=TX){receipt=receiptFor(row,{transactionHash:tx});return verifyTransfer(env,row,tx);}
let passed=0;async function test(name,fn){await fn();passed++;console.log('PASS',name);}
try{
await test('BSC wallet needs complete config, enabled flag and fresh background health',async()=>{const{d,env}=await setup();assert.equal((await web3Health(env)).ready,true);for(const patch of [{ADS_WEB3_ENABLED:'false'},{ADS_WALLET_CHAIN:'ethereum'},{ADS_WALLET:'bad'},{ADS_WEB3_PRICE_USD:''},{ADS_WEB3_RPC_URL:'http://unsafe'},{ADS_WATCH_SECRET:'short'}])assert.equal((await web3Health({...env,...patch})).ready,false);d.sql.exec('UPDATE bpj_ad_web3_health SET checked_at=0');assert.equal((await web3Health(env)).ready,false);});
await test('server price snapshot and unique six-decimal quotes survive concurrent retries',async()=>{const{d,env}=await setup();const rows=await Promise.all([1,2,3,4].map(n=>order(env,n)));assert.equal(new Set(rows.map(r=>r.amount_units)).size,4);assert.deepEqual(rows.map(r=>r.amount_units).sort((a,b)=>a-b),[49000001,49000002,49000003,49000004]);for(const row of rows){assert.equal(formatUnits(row.amount_units),'49.'+String(row.amount_units-49000000).padStart(6,'0'));assert.equal(web3Status(row).payment.amount_raw,(BigInt(row.amount_units)*10n**12n).toString());}const again=await order(env,1);assert.equal(again.amount_units,rows[0].amount_units);assert.equal(d.sql.prepare('SELECT COUNT(*) n FROM bpj_ad_checkout').get().n,4);});
await test('BSC 18-decimal amount verifies exactly; 6-decimal raw and 1-wei errors fail',async()=>{const{env}=await setup(),row=await order(env);assert.equal((await verified(env,row)).code,'verified');for(const raw of [BigInt(row.amount_units),BigInt(row.amount_units)*10n**12n-1n,BigInt(row.amount_units)*10n**12n+1n]){receipt=receiptFor(row);receipt.logs[0].data='0x'+raw.toString(16).padStart(64,'0');assert.equal((await verifyTransfer(env,row,TX)).code,'payment_mismatch');}});
await test('wrong recipient, forged token, wrong event and removed logs never deliver',async()=>{const{env}=await setup(),row=await order(env);for(const patch of [{address:addr},{removed:true},{topics:[topic,'0x'+'0'.repeat(64),'0x'+'2'.repeat(64)]},{topics:['0x'+'0'.repeat(64),'0x'+'0'.repeat(64),'0x'+row.recipient_hex.padStart(64,'0')]}]){receipt=receiptFor(row);Object.assign(receipt.logs[0],patch);assert.equal((await verifyTransfer(env,row,TX)).code,'payment_mismatch');}});
await test('failed receipt, missing receipt, unfinalized and reorganized blocks fail closed',async()=>{const{env}=await setup(),row=await order(env);receipt=null;assert.equal((await verifyTransfer(env,row,TX)).code,'confirming');receipt=receiptFor(row,{status:'0x0'});assert.equal((await verifyTransfer(env,row,TX)).code,'payment_mismatch');receipt=receiptFor(row,{blockNumber:'0x3e9'});assert.equal((await verifyTransfer(env,row,TX)).code,'confirming');receipt=receiptFor(row,{blockHash:'0x'+'c'.repeat(64)});assert.equal((await verifyTransfer(env,row,TX)).code,'confirming');});
await test('wrong chain, precision or RPC outage never yields paid proof',async()=>{const{env}=await setup(),row=await order(env);receipt=receiptFor(row);chainId='0x1';await assert.rejects(()=>verifyTransfer(env,row,TX),/wrong_chain/);chainId='0x38';precision=6;await assert.rejects(()=>verifyTransfer(env,row,TX),/token_precision/);precision=18;rpcError=true;await assert.rejects(()=>verifyTransfer(env,row,TX),/chain_unavailable/);});
await test('pre-order and late transfers are rejected; window expiry never reuses the quote',async()=>{const{d,env}=await setup(),row=await order(env);receipt=receiptFor(row);blockTime=row.created-1;assert.equal((await verifyTransfer(env,row,TX)).code,'outside_payment_window');blockTime=seconds();row.expires=seconds()-1;assert.equal((await verifyTransfer(env,row,TX)).code,'outside_payment_window');d.sql.prepare('UPDATE bpj_ad_web3 SET expires=? WHERE order_id=?').run(seconds()-1,row.id);const next=await order(env,2);assert.notEqual(row.amount_units,next.amount_units);assert.equal(web3Status(row).state,'payment_expired');});
await test('payment and slot allocation are atomic and rollback on mid-batch failure',async()=>{const{d,env}=await setup(),row=await order(env),proof=await verified(env,row);d.failAt=4;await assert.rejects(()=>deliverWeb3(env,row,proof));assert.equal(d.sql.prepare('SELECT COUNT(*) n FROM bpj_ad_chain_receipts').get().n,0);assert.equal((await web3Order(d,row.id)).paid_at,null);d.failAt=null;assert.equal((await deliverWeb3(env,row,proof)).state,'live');});
await test('a transaction already consumed by another order cannot allocate an unpaid slot',async()=>{const{d,env}=await setup(),a=await order(env,1),b=await order(env,2);await deliverWeb3(env,a,await verified(env,a));await deliverWeb3(env,b,{code:'verified',tx:TX,block:1000});const row=await web3Order(d,b.id);assert.equal(row.state,'pending');assert.equal(row.slot,null);assert.equal(row.paid_at,null);});
await test('four payments share three lanes and replay never extends delivery',async()=>{const{d,env}=await setup();const rows=[];for(let n=1;n<=4;n++){const row=await order(env,n),tx='0x'+n.toString(16).repeat(64);await deliverWeb3(env,row,await verified(env,row,tx));rows.push(await web3Order(d,row.id));}assert.deepEqual(rows.map(r=>r.slot),[1,2,3,1]);assert.equal(rows[3].starts_at,rows[0].ends_at);assert.equal(rows[3].ends_at-rows[3].starts_at,30*86400);const before=JSON.stringify(rows[0]);await deliverWeb3(env,rows[0],{code:'verified',tx:'0x'+'1'.repeat(64),block:1000});assert.equal(JSON.stringify(await web3Order(d,rows[0].id)),before);});
await test('automatic scan discovers payment with no submitted transaction hash',async()=>{const{d,env}=await setup(),row=await order(env);receipt=receiptFor(row);logs=receipt.logs;assert.equal((await scanOrder(env,row)).state,'live');assert.equal((await web3Order(d,row.id)).tx,TX);});
await test('background watch catches payments after buyer closes page',async()=>{const{d,env}=await setup(),row=await order(env);receipt=receiptFor(row);logs=receipt.logs;await watchWeb3(env);assert.equal((await web3Order(d,row.id)).state,'paid');});
await test('empty scan advances cursor, while RPC failure never skips blocks',async()=>{const{d,env}=await setup(),row=await order(env);await scanOrder(env,row);assert.equal((await web3Order(d,row.id)).cursor,1001);d.sql.exec('UPDATE bpj_ad_web3 SET checked_at=0');rpcError=true;await assert.rejects(()=>scanOrder(env,row));assert.equal((await web3Order(d,row.id)).cursor,1001);});
await test('private endpoints require order capability and watch endpoint requires secret',async()=>{const{env}=await setup();await order(env);const req=(tokenValue,body)=>new Request('https://baipiaoji.com/api/ad-web3',{method:'POST',headers:{Authorization:'Bearer '+tokenValue},body:JSON.stringify(body)});assert.equal((await endpoint({env,request:req('bad',{action:'status'})})).status,401);assert.equal((await endpoint({env,request:req(token(9),{action:'status'})})).status,404);assert.equal((await endpoint({env,request:req(token(1),{action:'status'})})).status,200);assert.equal((await watchEndpoint({env,request:req('bad',{})})).status,401);});
await test('Web3 requests enforce origin, content rules, consent and server price',async()=>{const{env}=await setup();const b={action:'create',name:'Fixture',pitch:'Workflow tool',url:'https://fixture.example.org',cat:'coding',lang:'en',accept_queue:true,price_cents:1};const req=(body,origin='https://baipiaoji.com')=>new Request('https://baipiaoji.com/api/ad-web3',{method:'POST',headers:{Authorization:'Bearer '+token(8),Origin:origin},body:JSON.stringify(body)});assert.equal((await endpoint({env,request:req(b,'https://evil.example.org')})).status,403);assert.equal((await endpoint({env,request:req({...b,accept_queue:false})})).status,400);const r=await endpoint({env,request:req(b)});assert.equal(r.status,200);assert.equal((await r.json()).payment.amount,'49.000001');});
await test('doctor and public ads do not reveal recipient, credentials or transaction hashes',async()=>{const{env}=await setup(),row=await order(env);await deliverWeb3(env,row,await verified(env,row));for(const path of ['?doctor=1','?cat=coding']){const r=await ads({env,request:new Request('https://baipiaoji.com/api/ads'+path)});const body=await r.text();for(const value of [addr,TX,env.ADS_WATCH_SECRET,env.ADS_WEB3_RPC_URL])assert.equal(body.includes(value),false);} });
await test('test-network payments never appear in public inventory',async()=>{const{env}=await setup({ADS_WALLET_CHAIN:'base-sepolia'}),row=await order(env);await deliverWeb3(env,row,await verified(env,row));const r=await ads({env,request:new Request('https://baipiaoji.com/api/ads?cat=coding')});assert.equal((await r.json()).ads.length,0);});
await test('Stripe and Web3 paid orders compete for the SAME live lanes',async()=>{const{d,env}=await setup();const row=await order(env);await deliverWeb3(env,row,await verified(env,row));d.sql.prepare("INSERT INTO bpj_ad_checkout(id,token_hash,name,url,pitch,cat,lang,price_cents,currency,days,livemode,state,session,created) VALUES('card','hash','Card','https://card.example.org','Tool','coding','en',4900,'eur',30,1,'pending','cs_card',?)").run(seconds());await fulfill(d,{metadata:{bpj_order:'card'},payment_status:'paid',mode:'payment',client_reference_id:'card',id:'cs_card',payment_intent:'pi_card',livemode:true,amount_subtotal:4900,amount_total:4900,currency:'eur'},'evt_card','paid');assert.equal(d.sql.prepare("SELECT slot FROM bpj_ad_checkout WHERE id='card'").get().slot,2);});
console.log(`${passed} Web3 integration tests passed (real SQLite, mocked JSON-RPC).`);
}finally{globalThis.fetch=oldFetch;Date.now=realNow;}
