// Discovery hub only. Existing tools keep their processing origin and canonical URL.
export function buildToolkit({layout,railOf,esc,crumbLd,BASE,NAME,LOCALE,site,write,pushPage}){
 const zh=LOCALE.code==='zh',tds='https://thedollscout.com'+(zh?'/zh':''),route='/studio/toolkit',url=BASE+route;
 const groups=[
  {zh:'AI 与文本',en:'AI & text',rows:[['/studio/task-loop','任务回溯与预测','Task Loop','记录预期、证据和任务时间线。','Track expectations, evidence and task history.'],[tds+'/ai-portrait-background-remover','AI 人像抠图','AI portrait cutout','下载模型后在本机处理人像，不适用于任意物体。','Local portrait matting after model download; not general object removal.'],[tds+'/ai-audio-to-text','英文音频转文字','English audio transcription','本地 Whisper 模型，短英文音频导出 TXT 或 SRT。','Local Whisper model; short English audio to TXT or SRT.'],[tds+'/ai-text-summarizer','英文原文要点','English extractive highlights','从英文原文挑选句子，不是生成式摘要。','Select sentences from English source text; not generative summarization.']]},
  {zh:'图片与素材',en:'Images & assets',rows:[['/studio/product-images','商品图批处理','Product image batch tools','批量调整尺寸、裁切、格式，导出图片或 ZIP。','Batch resize, crop and convert; export images or ZIP.'],[tds+'/image-compressor','图片压缩与转换','Image compression & conversion','处理 JPEG、PNG、WebP，比较实际输出体积。','Process JPEG, PNG and WebP; compare actual output sizes.'],['/studio/video-variants','商品视频变体','Product video variants','编辑不同开场与画幅，导出成片与字幕。','Edit openings and frame sizes; export videos and captions.']]},
  {zh:'PDF 与文件',en:'PDFs & files',rows:[['/studio/pdf-tools','PDF 整理工作台','PDF workbench','合并、选页、旋转与图片转 PDF。','Merge, select and rotate pages; images to PDF.'],[tds+'/pdf-accessibility-checker','PDF 发布前预检','PDF accessibility preflight','检查结构与元数据线索，不是合规认证。','Check structural and metadata signals; not conformance certification.'],[tds+'/pdf-to-text','PDF 提取文字','PDF to text','按页提取已有文本，不含 OCR。','Extract existing page text; no OCR.'],[tds+'/compare-pdf-text','PDF 文字比较','Compare PDF text','查找已有文字差异，不是视觉比较。','Compare extracted wording; not visual differences.'],[tds+'/verify-file','文件副本核验','File verification','核对 SHA-256 与字节数，不证明身份或收件。','Compare SHA-256 and byte count; not identity or receipt proof.'],[tds+'/delivery-evidence','文件交付记录','Delivery record','记录文件清单与备注，导出本地记录。','Build a file inventory and notes; export a local record.']]},
  {zh:'数据与协作',en:'Data & collaboration',rows:[[tds+'/json-compare','JSON 校验与比较','JSON validation & comparison','保留长数字精度，按字段比较。','Preserve large numbers and compare fields.'],[tds+'/time-zone-planner','跨时区会议规划','Time-zone meeting planner','查看城市时间并导出日历，不查询忙闲。','Compare city times and export a calendar file; no availability lookup.'],['/studio/quote-compare','供应商报价比较','Supplier quote comparison','核对箱规、税运费与交期。','Compare pack sizes, freight, tax and lead times.']]}
 ];
 const title=zh?'通用工具，按任务找到入口':'Everyday tools, organized by task';
 const description=zh?'BPJ 通用工具导航：集中查找 AI、图片、PDF、JSON、文件核验与时区工具，清楚标明运行站点、用途和限制。':'Find AI, image, PDF, JSON, file-verification and time-zone tools in one BPJ directory, with clear hosting origins, outputs and limitations.';
 const link=r=>r[0].startsWith('https:')?r[0]:BASE+r[0];
 const body=`${railOf()}<link rel="stylesheet" href="${site.base_url}/studio-assets/studio.css"><main class="stage studio-main" id="main-content"><nav class="crumb"><a href="${BASE}/">${esc(NAME)}</a><i>/</i><a href="${BASE}/studio/">${zh?'自研工具':'BPJ tools'}</a><i>/</i><span>${zh?'通用工具导航':'Everyday toolkit'}</span></nav><header class="studio-hero"><h1>${title}</h1><p>${description}</p><p>${zh?'先选你要完成的任务。BPJ 工具直接打开，TDS 工具会前往原站使用；无需在这里上传文件。':'Choose the task you want to finish. BPJ tools open here; TDS tools open on their existing site. No file upload is needed in this directory.'}</p><nav class="studio-home-links" aria-label="${zh?'工具分类':'Tool categories'}">${groups.map((g,i)=>`<a href="#task-${i}">${zh?g.zh:g.en}</a>`).join('')}</nav></header>${groups.map((g,i)=>`<section class="studio-tools" id="task-${i}"><h2>${zh?g.zh:g.en}</h2><div class="studio-rows">${g.rows.map(r=>`<article class="studio-product"><span class="studio-meta">${r[0].startsWith('https:')?(zh?'TDS · 前往原站':'TDS · opens on TDS'):(zh?'BPJ · 本站工具':'BPJ · hosted here')}</span><h3><a href="${link(r)}">${esc(zh?r[1]:r[2])}</a></h3><p>${esc(zh?r[3]:r[4])}</p><a class="studio-button" href="${link(r)}">${zh?'打开工具':'Open tool'}</a></article>`).join('')}</div></section>`).join('')}<section class="studio-info"><h2>${zh?'专门的任务，去专门的站点':'Specialist tasks have their own home'}</h2><p>${zh?'潮玩购买、盲盒概率和收藏管理在 The Doll Scout；这里汇总日常数字工作工具。':'Collectible-toy buying guides, blind-box odds and collection management live on The Doll Scout. This directory focuses on everyday digital work.'}</p><a href="https://thedollscout.com/${zh?'zh/':''}">${zh?'探索 TDS 潮玩与收藏工具':'Explore TDS collectible guides and tools'}</a><p>${zh?'免费基础任务以各工具页面为准。AI 工具需要用户主动下载模型；是否支持你的设备、语言和文件格式，请先阅读限制。':'Check each tool for free-task scope, device support, languages and file limits. AI tools require an explicit model download.'}</p></section></main>`;
 const items=groups.flatMap(g=>g.rows);
 write('studio/toolkit.html',layout({title:(zh?'通用工具导航':'Everyday toolkit')+' - '+NAME,description,path:route,body,wide:true,schema:[crumbLd([{name:NAME,url:BASE+'/'},{name:title,url}]),{'@context':'https://schema.org','@type':'CollectionPage',name:title,url,description,mainEntity:{'@type':'ItemList',itemListElement:items.map((r,i)=>({'@type':'ListItem',position:i+1,name:zh?r[1]:r[2],url:link(r)}))}}]}));pushPage(url,'0.8');
}
