import {buildVideoBusiness,videoCloudOffer} from './video-business.mjs';
import {COPY,renderVideo} from '../assets/studio/video-view.mjs';
import {EDITION} from '../assets/studio/video-core.mjs';
export function buildVideo({layout,railOf,crumbLd,faqLd,BASE,NAME,LOCALE,site,write,pushPage}){
const lang=LOCALE.code==='zh'?'zh':'en',zh=lang==='zh',L=COPY[lang],path='/studio/video-variants',url=BASE+path,asset=site.base_url+'/studio-assets';
const FAQ=[{q:L.scopeTitle,a:L.scope},{q:zh?'视频和项目是否免费？':'Are videos and projects free?',a:L.free},{q:L.proTitle,a:L.pro}];
const body=`${railOf()}<link rel="stylesheet" href="${asset}/studio.css?v=${EDITION}"><link rel="stylesheet" href="${asset}/video.css?v=${EDITION}"><main class="stage studio-main" id="main-content"><nav class="crumb"><a href="${BASE}/">${NAME}</a><i>/</i><a href="${BASE}/studio/">${zh?'BPJ 自研工具':'Built by BPJ'}</a><i>/</i><a href="${BASE}/video/">${zh?'视频工作室':'Video studio'}</a><i>/</i><span>${L.title}</span></nav><header class="studio-hero"><span class="studio-sign">${zh?'BPJ 自主设计与开发':'Designed and built by BPJ'}</span><h1>${L.title}</h1><p>${L.intro}</p></header><noscript><p class="quote-notice">${zh?'启用 JavaScript 后可在本机制作与导出视频。':'Enable JavaScript to create and export video locally.'}</p></noscript>${renderVideo(lang,videoCloudOffer(BASE,zh,true))}<section class="studio-info">${FAQ.map(f=>`<h2>${f.q}</h2><p>${f.a}</p>`).join('')}<p><a href="${BASE}/pipeline/video">${zh?'核对视频工具的免费额度':'Check video-tool free allowances'}</a> · <a href="${BASE}/work-plan">${zh?'按实际工作规划 AI 方案':'Plan AI around your actual work'}</a></p></section></main><script type="module" src="${asset}/video-app.mjs?v=${EDITION}"></script><script type="module" src="${asset}/video-business.mjs?v=${EDITION}"></script>`;
write('studio/video-variants.html',layout({title:`${L.title} - BPJ`,description:L.intro,path,body,wide:true,schema:[crumbLd([{name:NAME,url:BASE+'/'},{name:zh?'BPJ 自研工具':'Built by BPJ',url:BASE+'/studio/'},{name:L.title,url}]),{'@context':'https://schema.org','@type':'WebApplication',name:L.title,url,description:L.intro,applicationCategory:'MultimediaApplication',operatingSystem:'Web browser',inLanguage:lang,softwareVersion:EDITION,creator:{'@type':'Organization',name:'BPJ',url:site.base_url},isAccessibleForFree:true,offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}},faqLd(FAQ)]}));pushPage(url+'.html','0.9');
buildVideoBusiness({layout,railOf,crumbLd,faqLd,BASE,NAME,LOCALE,site,write,pushPage});
}
