import {chromium} from '../../../../tools/revenue-studio/node_modules/playwright/index.mjs';
import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');let f=path.join(root,decodeURIComponent(u.pathname));if(!path.extname(f))f+='.html';if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml'})[path.extname(f)]||'text/plain');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true});
try{for(const lang of ['en','zh']){const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage(),errors=[],uploads=[];page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>{if(r.url().includes('/api/member')&&r.method()==='POST')uploads.push(r);});
await context.route('**/*',async route=>{const u=route.request().url();if(u.startsWith('https://www.tradingview-widget.com/embed-widget/'))return route.fulfill({contentType:'text/html',body:'<!doctype html><p>Isolated widget fixture</p>'});if(!u.startsWith(base))return route.abort();if(u.includes('/api/member'))return route.fulfill({json:{ok:true,ready:false}});return route.continue();});
await page.clock.install();
const url=base+(lang==='zh'?'/zh':'')+'/portfolio-tracker?__qa=1';await page.goto(url);await page.waitForFunction(()=>document.getElementById('data-status').textContent.includes('2026'));assert.equal(await page.locator('#metric-basket').textContent(),'—');
await page.locator('#calc-stress').click();assert.match(await page.locator('#stress-result').textContent(),/-18.00%/);await page.locator('#weight').fill('101');await page.locator('#calc-stress').click();assert.equal(await page.locator('#stress-result').textContent(),'');await page.locator('#weight').fill('20');
await page.locator('#calc-leverage').click();assert.match(await page.locator('#leverage-result').textContent(),/-5.45%/);await page.locator('#annual').fill('0');await page.locator('#years').fill('1');await page.locator('#calc-dca').click();assert.match(await page.locator('#dca-result').textContent(),/12,400/);
await page.locator('#thesis').fill('<script>Test only</script>');await page.locator('#counter').fill('A reason to change my mind');await page.locator('#save-local').click();await page.locator('#thesis').fill('changed');await page.locator('#restore-local').click();assert.equal(await page.locator('#thesis').inputValue(),'<script>Test only</script>');
const dp=page.waitForEvent('download');await page.locator('#export-json').click();const record=JSON.parse(fs.readFileSync(await(await dp).path(),'utf8'));assert.equal(record.product,'portfolio-tracker');
await page.locator('#import-json').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{}')});await page.waitForFunction(()=>document.getElementById('status').textContent.includes('format')||document.getElementById('status').textContent.includes('格式'));assert.equal(await page.locator('#thesis').inputValue(),'<script>Test only</script>');
await page.locator('#thesis').fill('changed');await page.locator('#import-json').setInputFiles({name:'good.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(record))});await page.waitForFunction(()=>document.getElementById('thesis').value.startsWith('<script>'));
const pp=page.waitForEvent('popup');await page.locator('#save-cloud').click();const popup=await pp;await popup.waitForFunction(()=>document.getElementById('payload')?.value.includes('portfolio-tracker'));assert.match(await popup.locator('#payload').inputValue(),/Test only/);assert.equal(uploads.length,0);await popup.close();
await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/tmp/portfolio-'+lang+'-desktop.png'});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'/tmp/portfolio-'+lang+'-mobile.png'});
// Provider URLs are tested without third-party scripts touching our research form.
await page.locator('#market-reload').click();assert.equal(await page.locator('.market-frame iframe').count(),2);await page.locator('#market-symbol').selectOption('TQQQ');assert.match(decodeURIComponent(await page.locator('#market-chart iframe').getAttribute('src')),/NASDAQ:TQQQ/);await page.locator('#market-toggle').click();assert.equal(await page.locator('.market-frame iframe').count(),0);await page.locator('#market-toggle').click();assert.equal(await page.locator('.market-frame iframe').count(),2);
// Synthetic market data only in this isolated browser response; never stored in published JSON.
const actual=JSON.parse(fs.readFileSync(path.join(root,'portfolio-assets/snapshot.json'))),manifest=JSON.parse(fs.readFileSync(path.join(root,'portfolio-assets/manifest.json'))),keys=[...manifest.stocks,...manifest.benchmarks].map(x=>x.ticker).concat('basket');const fixture={...actual,status:'tracking',as_of:'2026-10-06',dates:['2026-10-05','2026-10-06'],series:Object.fromEntries(keys.map(k=>[k,[100,110]])),metrics:Object.fromEntries(keys.map(k=>[k,{return_pct:10,max_drawdown_pct:0,excess_spy_pp:0}]))};
let responseFixture=fixture,failRefresh=false,recordRequests=0;await context.route('**/portfolio-assets/snapshot.json',route=>{recordRequests++;return failRefresh?route.fulfill({status:503,body:'test unavailable'}):route.fulfill({json:responseFixture});});await page.locator('#refresh-record').click();await page.waitForFunction(()=>document.getElementById('metric-basket').textContent==='+10.00%');assert.equal(await page.locator('#chart').isVisible(),true);assert.equal(await page.locator('#chart polyline').count(),4);const csvp=page.waitForEvent('download');await page.locator('#export-performance').click();assert.match(fs.readFileSync(await(await csvp).path(),'utf8'),/2026-10-06/);
assert.equal(await page.locator('#thesis').inputValue(),'<script>Test only</script>');
responseFixture={...fixture,dates:['2026-10-05','2026-10-06','2026-10-07'],as_of:'2026-10-07',series:Object.fromEntries(keys.map(k=>[k,[100,110,112]])),metrics:Object.fromEntries(keys.map(k=>[k,{return_pct:12,max_drawdown_pct:0,excess_spy_pp:0}]))};
await page.clock.runFor(61000);await page.waitForFunction(()=>document.getElementById('metric-basket').textContent==='+12.00%');assert.equal(await page.locator('#thesis').inputValue(),'<script>Test only</script>');
failRefresh=true;await page.clock.runFor(61000);await page.waitForFunction(()=>/failed|失败/.test(document.getElementById('record-refresh-status').textContent));assert.equal(await page.locator('#metric-basket').textContent(),'+12.00%');
await page.locator('#toggle-record').click();const stopped=recordRequests;await page.clock.runFor(120000);assert.equal(recordRequests,stopped);
failRefresh=false;responseFixture=actual;await page.locator('#toggle-record').click();await page.waitForFunction(()=>/failed|失败/.test(document.getElementById('record-refresh-status').textContent));assert.equal(await page.locator('#metric-basket').textContent(),'+12.00%');
responseFixture=fixture;await page.goto(url+'&embed=1');assert.equal(await page.locator('header').isVisible(),false);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);await context.close();console.log(lang+': calculators, failed import, local roundtrip, member handoff, chart, CSV, dynamic refresh, rollback retention, market selection, mobile and embed passed');}}
finally{await browser.close();server.close();}
