from pathlib import Path
import json,html
ROOT=Path(__file__).resolve().parents[2]
M=json.loads((ROOT/'portfolio-assets/manifest.json').read_text())
for zh in (False,True):
 def t(en,cn):return cn if zh else en
 prefix='/zh' if zh else '';lang='zh' if zh else 'en';url='https://agiscorecard.com'+prefix+'/portfolio-tracker'
 title=t('12-stock returns vs the market','12 股组合收益率对比')
 description=t('Compare the 12-stock basket with SPY, QQQ and TQQQ first. Automatically check published returns every 60 seconds, inspect each stock and follow delayed market quotes.','首屏对比 12 股组合与标普 SPY、QQQ、TQQQ 收益率，每 60 秒自动检查已发布记录，展开逐股表现，动态追踪延迟行情。')
 schema=[{'@context':'https://schema.org','@type':'WebApplication','name':title,'url':url,'applicationCategory':'FinanceApplication','operatingSystem':'Web','isAccessibleForFree':True,'offers':{'@type':'Offer','price':'0','priceCurrency':'USD'},'isPartOf':{'@type':'CollectionPage','url':'https://agiscorecard.com'+prefix+'/ai-tools'},'featureList':['Automatically updating delayed quotes and charts','Fixed-entry public portfolio','Same-window benchmark comparison','Position stress and contribution scenarios','Daily leverage path illustration','Local research records and export']},{'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'AGI Scorecard','item':'https://agiscorecard.com/'},{'@type':'ListItem','position':2,'name':t('Invest','投资'),'item':'https://agiscorecard.com'+prefix+'/invest'},{'@type':'ListItem','position':3,'name':t('Portfolio tracker','组合追踪'),'item':url}]}]
 fields=[('capital','Starting capital (USD)','起始本金（美元）',10000,0,1e9),('weight','Selected sleeve weight (%)','研究仓位占比（%）',20,0,100),('shock','Selected sleeve shock (%)','研究仓位冲击（%）',-50,-100,500),('rest','Rest-of-portfolio shock (%)','其余资产冲击（%）',-10,-100,500),('monthly','Month-end contribution (USD)','月末定投（美元）',200,0,1e7),('annual','Assumed annual return (%)','假设年回报（%）',5,-99,100),('years','Years (whole number)','年数（整数）',5,1,40)]
 def inputs(keys):return ''.join(f'<label for="{k}">{t(en,cn)}<input id="{k}" type="number" value="{v}" min="{mn}" max="{mx}" step="{1 if k=="years" else "any"}"></label>' for k,en,cn,v,mn,mx in fields if k in keys)
 rows=''.join(f'<tr><th scope="row">{x["ticker"]}</th><td data-return="{x["ticker"]}">—</td><td data-entry="{x["ticker"]}">—</td><td data-drawdown="{x["ticker"]}">—</td><td>{html.escape(x["name"])}</td><td>{t("8.33% initially","初始 8.33%") if x in M["stocks"] else t("Separate benchmark","独立对照")}</td></tr>' for x in M['stocks']+M['benchmarks'])
 page=f'''<!doctype html><html lang="{lang}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | AGI Scorecard</title><meta name="description" content="{description}"><link rel="canonical" href="{url}">
<link rel="alternate" hreflang="en" href="https://agiscorecard.com/portfolio-tracker"><link rel="alternate" hreflang="zh-Hans" href="https://agiscorecard.com/zh/portfolio-tracker"><link rel="alternate" hreflang="x-default" href="https://agiscorecard.com/portfolio-tracker">
<meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:url" content="{url}"><meta property="og:type" content="website"><meta property="og:image" content="https://agiscorecard.com/portfolio-assets/share.png"><meta name="twitter:card" content="summary_large_image"><meta name="dateModified" content="2026-10-03">
<link rel="stylesheet" href="/portfolio-assets/style.css"><script type="module" src="/portfolio-assets/app.mjs"></script>{''.join('<script type="application/ld+json">'+json.dumps(s,ensure_ascii=False)+'</script>' for s in schema)}</head>
<body data-language="{lang}"><a class="skip" href="#track">{t('Skip to tracker','跳至追踪表')}</a><header><a href="{'/cn' if zh else '/'}" class="brand">AGI Scorecard / {t('Invest','投资')}</a><nav><a href="{prefix}/invest">{t('Investment hub','投资板块')}</a><a href="#markets">{t('Market watch','动态行情')}</a><a href="#tools">{t('Tools','辅助工具')}</a><a href="{'/portfolio-tracker' if zh else '/zh/portfolio-tracker'}" lang="{'en' if zh else 'zh'}">{'English' if zh else '中文'}</a></nav></header>
<main><section id="track" class="returns-first"><p class="label">{t('PUBLIC PORTFOLIO · SAME-WINDOW RETURNS','公开组合 · 同期收益')}</p><h1>{title}</h1><p class="return-intro">{t('Equal-weight basket vs SPY (S&P 500), QQQ and TQQQ.','12 股等权组合 vs 标普 SPY、QQQ、TQQQ。')}</p>
<div class="comparison" id="comparison">{''.join('<article><h3>'+name+'</h3><strong id="metric-'+key+'">—</strong><span>'+t('Since entry','建仓以来')+'</span><p id="risk-'+key+'">'+t('Waiting for a complete entry session','等待完整建仓日行情')+'</p></article>' for key,name in [('basket',t('12-stock basket','12 股组合')),('SPY','SPY · S&P 500'),('QQQ','QQQ · Nasdaq-100'),('TQQQ','TQQQ · 3× daily')])}</div>
<div class="actions return-controls"><button id="refresh-record" class="primary" type="button">{t('Refresh returns','立即刷新收益')}</button><button id="toggle-record" type="button">{t('Pause record checks','暂停记录检查')}</button><button id="share" type="button">{t('Copy link','复制链接')}</button><span id="record-refresh-status" class="small" role="status">{t('Automatic checks every 60 seconds','每 60 秒自动检查')}</span></div><p class="notice" id="data-status" role="status">{t('Loading the dated record…','正在加载带日期的记录…')}</p>
<p class="small return-method">{t('Returns start at the October 2, 2026 New York close. Updated after each weekday close; this page checks the published record every 60 seconds. Model returns in USD, dividend/split-adjusted, before tax and trading costs.','收益起点：纽约时间 2026 年 10 月 2 日收盘。每个工作日收盘后更新数据，页面每 60 秒检查已发布记录。美元模拟收益，含分红及拆股调整，未扣税和交易成本。')} <a href="#method">{t('Fixed rules','固定规则')}</a> · <a href="#markets">{t('Live market watch','动态行情')}</a></p>

<details id="holdings" open><summary>{t('All 12 stocks and benchmark returns','12 只股票与基准收益率明细')}</summary><div class="scroll"><table><thead><tr><th>{t('Ticker','代码')}</th><th>{t('Return','收益率')}</th><th>{t('Entry close (USD, adjusted)','建仓复权价（美元）')}</th><th>{t('Max drawdown','最大回撤')}</th><th>{t('Security','证券')}</th><th>{t('Allocation','配置')}</th></tr></thead><tbody>{rows}</tbody></table></div></details>
<div class="chart-area"><svg id="chart" viewBox="0 0 900 290" role="img" aria-label="{t('Normalized portfolio values, starting at 100','起点为 100 的组合净值')}" hidden></svg><p id="chart-empty">{t('The record starts at the October 2 close (normalized to 100). A return curve appears after the next completed session.','以 10 月 2 日收盘为起点（净值 100），下一个交易日收盘后开始绘制收益曲线。')}</p><p id="chart-dates" class="small"></p><div class="legend"><span style="--color:#e0a951">{t('12-stock basket','12 股组合')}</span><span style="--color:#68c9c2">SPY</span><span style="--color:#909bff">QQQ</span><span style="--color:#ed91b4">TQQQ</span></div></div>
<p class="small">{t('TQQQ targets 3× the Nasdaq-100’s daily return before fees and expenses. Over longer periods its return can differ materially from 3× the index.','TQQQ 目标为纳斯达克 100 每日回报的 3 倍（费用前）；长期回报可能明显偏离指数累计回报的 3 倍。')} <a href="https://www.proshares.com/our-etfs/leveraged-and-inverse/tqqq" target="_blank" rel="noopener">ProShares</a></p><div class="actions"><button id="export-performance" type="button">{t('Download performance CSV','下载表现 CSV')}</button><a href="/portfolio-assets/manifest.json">{t('Registered rules (JSON)','登记规则（JSON）')}</a><a href="/portfolio-assets/snapshot.json">{t('Dated record / corrections','数据记录与修订')}</a></div></section>
<section id="markets"><div class="section-heading"><h2>{t('Follow the market as it changes.','动态追踪，跟随行情变化。')}</h2><span class="market-badge">{t('AUTO · DELAYED QUOTES','自动更新 · 延迟行情')}</span></div>
<p>{t('Quotes and charts update through TradingView while connected. US widget data is delayed; the quote time and closed-market state belong to the provider. Price movement is different from the registered portfolio’s dividend-adjusted return above.','连接期间，TradingView 行情与走势图自动更新。美股组件提供延迟行情，报价时间及休市状态以数据源为准。价格涨跌与上方登记组合的分红调整收益口径不同。')}</p>
<div class="market-controls"><label for="market-symbol">{t('Chart symbol','走势图标的')}<select id="market-symbol">{''.join('<option value="'+x['ticker']+'"'+(' selected' if x['ticker']=='NVDA' else '')+'>'+x['ticker']+' · '+html.escape(x['name'])+'</option>' for x in M['stocks']+M['benchmarks'])}</select></label><button type="button" id="market-reload">{t('Reconnect quotes','刷新行情连接')}</button><button type="button" id="market-toggle">{t('Pause market data','暂停行情')}</button></div>
<p id="market-status" class="small" role="status">{t('Market widgets connect when this section comes into view.','此区域进入视野后连接行情组件。')}</p><div class="market-grid"><div id="market-chart" class="market-frame"></div><div id="market-quotes" class="market-frame"></div></div>
<p class="small"><a id="market-source" href="https://www.tradingview.com/symbols/NASDAQ-NVDA/" target="_blank" rel="noopener noreferrer nofollow">{t('Open selected symbol','打开当前标的')}</a> · {t('Market data and charts by','行情与图表由')} <a href="https://www.tradingview.com/" target="_blank" rel="noopener nofollow">TradingView</a> {t('provided. If an embed is blank, reconnect or open the source; a loaded frame does not establish a fresh quote.','提供。组件空白时可重新连接或打开来源；组件载入不代表报价已更新。')} <a href="https://www.tradingview.com/widget-docs/markets/north-america/" target="_blank" rel="noopener">{t('Data coverage and delays','数据覆盖与延迟')}</a></p><p class="small">{t('Third-party frames receive ordinary connection information, but our research notes and calculator inputs are not passed to them.','第三方组件接收常规连接信息，本站不会向它传送研究笔记或计算器输入。')}</p></section>
<section id="tools"><h2>{t('Turn a market opinion into a risk budget.','把市场观点，变成可承受的风险。')}</h2><p>{t('Editable, fictional scenarios. These calculations are not forecasts or suggested allocations. Inputs stay in this tab until you choose to save.','以下是可修改的虚构情景，并非预测或建议仓位。输入在主动保存前仅保留在当前标签页。')}</p>{inputs(['capital'])}
<div class="tool-grid"><article><h3>{t('Position stress','仓位压力测算')}</h3><p>{t('What if this sleeve falls sharply and the rest falls too?','研究仓位大跌、其他资产也下跌，会怎样？')}</p><div class="fields">{inputs(['weight','shock','rest'])}</div><button id="calc-stress" class="primary" type="button">{t('Calculate stress','测算压力')}</button><output id="stress-result" aria-live="polite"></output></article>
<article><h3>{t('Contribution scenarios','定投情景对比')}</h3><p>{t('Compare your constant-return assumption with 0% and −5% a year.','将你的恒定回报假设与年回报 0%、−5% 对比。')}</p><div class="fields">{inputs(['monthly','annual','years'])}</div><button id="calc-dca" class="primary" type="button">{t('Compare assumptions','对比假设')}</button><output id="dca-result" aria-live="polite"></output></article>
<article><h3>{t('Why daily 3× is different','每日 3 倍为何不同')}</h3><p>{t('Enter comma-separated daily index returns (%). The default goes up 10% then almost exactly back to its starting point.','输入逗号分隔的每日指数涨跌（%）。默认先涨 10%，再几乎恰好跌回起点。')}</p><label for="path">{t('Daily index returns (%)','每日指数涨跌（%）')}<input id="path" value="10,-9.090909" maxlength="500"></label><button id="calc-leverage" class="primary" type="button">{t('Compare the paths','对比路径')}</button><output id="leverage-result" aria-live="polite"></output><p class="small">{t('Idealized daily reset; no fees, financing, tracking error or trading halts. This is not simulated TQQQ market history.','理想化每日重置；未含费用、融资、跟踪误差或停牌，非 TQQQ 历史行情模拟。')}</p></article></div>
<p class="small">{t('Stress uses weight × sleeve shock + remaining weight × other-assets shock. Contribution scenarios compound monthly at (1 + annual rate)^(1/12) − 1, with deposits at month-end; no tax, fees, inflation or variable return paths.','压力测算为仓位权重 × 仓位冲击 + 剩余权重 × 其他资产冲击。定投按（1 + 年回报）^(1/12) − 1 逐月复利，月末投入；不含税、费、通胀及变动收益路径。')}</p><a href="https://gushen.agiscorecard.com/{'zh' if zh else 'en'}/">{t('Open Gushen for editable portfolios, correlations and historical strategy comparisons','打开股神：编辑组合、核对相关性、比较历史策略')}</a></section>
<section class="journal"><h2>{t('Write the decision you will review.','写下你要复查的判断。')}</h2><div class="fields"><label for="thesis">{t('My thesis','我的判断')}<textarea id="thesis" rows="3" maxlength="2000"></textarea></label><label for="counter">{t('What would change my mind?','什么证据会改变判断？')}<textarea id="counter" rows="3" maxlength="2000"></textarea></label><label for="review">{t('Review date (no automatic reminder)','复查日期（不会自动提醒）')}<input id="review" type="date"></label></div><div class="actions"><button id="save-local" type="button">{t('Save locally','保存到本机')}</button><button id="restore-local" type="button">{t('Restore local copy','恢复本机记录')}</button><button id="export-json" type="button">{t('Export my record','导出我的记录')}</button><label class="button file">{t('Import record','导入记录')}<input id="import-json" type="file" accept="application/json,.json"></label><button id="erase-local" type="button">{t('Delete local copy','删除本机记录')}</button></div><p id="status" class="small" role="status" aria-live="polite"></p></section>
<section class="membership"><div><h2>{t('Keep your research across devices.','跨设备保留你的研究。')}</h2><p>{t('The public tracker and calculators are free. Existing AGI membership adds fifty cloud workspaces with ten versions each, for your assumptions and review notes.','公开追踪和计算器免费。现有 AGI 会员提供 50 个云端工作区，每个保留 10 版，保存你的假设和复盘笔记。')}</p><p class="small">{t('9 USDT / 30 days, plus the order matching fraction and network fees. No automatic renewal. No extra AI quota, buy/sell signals or automatic alerts. Cloud storage is not end-to-end encrypted.','9 USDT / 30 天，另加订单匹配尾数及网络费，不自动续费。不附加 AI 额度、买卖信号或自动提醒；云端存储非端到端加密。')}</p></div><div><button id="save-cloud" class="primary" type="button">{t('Open cloud save','打开云端保存')}</button><p class="small">{t('Review the record on the member page, then choose Save. Payment readiness is checked there.','在会员页审阅记录后，再主动点击保存；付款可用性在该页核验。')}</p></div></section>
<section id="method"><p>{t('Market widgets receive provider updates automatically. The official public performance record is computed after each weekday close at 22:40 UTC (06:40 the next day in Shanghai); job queues and provider availability can delay publication. This page checks for a published record every 60 seconds while visible and online. Refreshing never creates an unpublished valuation or changes the registered entry.', '行情组件自动接收数据源更新。公开组合收益记录在每个工作日收盘后 22:40 UTC（上海次日 06:40）计算；任务排队或行情缺失可能延迟发布。页面在可见且联网时每 60 秒检查已发布记录。刷新不会生成尚未发布的估值，也不会改动登记起点。')}</p><h2>{t('Rules you can audit','可核查的规则')}</h2><ol><li>{t('Selected October 3, 2026 (Shanghai): use the October 2, 2026 regular-session close in New York. This previous-close baseline replaces the unstarted October 5 plan at the owner’s request; it is not a portfolio registered before entry. If any entry price is missing, the complete basket remains unavailable; its start is never shifted silently.','2026 年 10 月 3 日（上海）按站主要求，改用纽约 10 月 2 日正常交易时段收盘价建仓，替代尚未开始的 10 月 5 日方案。此为事后选定的前一交易日基准，并非提前登记的真实交易。任一建仓价缺失则组合暂不可用，绝不静默移动起点。')}</li><li>{t('USD 10,000 per portfolio. Twelve stocks receive exactly 1/12 each initially, fractional shares assumed; no rebalancing or later deposits. SPY, QQQ and TQQQ are separate 100% benchmark sleeves. SPY is a tradable S&P 500 ETF proxy, not the index itself.','每个组合模拟 10,000 美元。12 股初始各 1/12，允许碎股，不再平衡或追加投入。SPY、QQQ、TQQQ 为各自 100% 持仓的独立对照。SPY 是可交易的标普 ETF 代理，不是指数本身。')}</li><li>{t('Vendor adjusted-close ratios proxy reinvested distributions and splits. Fund costs are already reflected in ETF prices. Trading costs, taxes and FX are excluded. The entry close is a valuation convention, not a promised execution price.','供应商复权收盘价比值近似反映分红再投和拆股；ETF 价格已体现基金内部费用。不含交易成本、税与汇率。起点收盘是估值约定，不是成交保证。')}</li><li>{t('Maximum drawdown is the largest close-to-close fall from a prior peak in this observation window, not an intraday or future worst-case loss. Excess return is a percentage-point difference from SPY, not risk-adjusted alpha. No annualization of this short record.','最大回撤为观察期内从前高到后续收盘的最大跌幅，不是日内或未来最大损失。超额收益是相对 SPY 的百分点差额，不是风险调整后 alpha。短期记录不作年化。')}</li><li>{t('Updates reuse the existing weekday post-close job. Every series must cover the same observed SPY sessions. On failed or partial data, the previous complete record is kept and flagged. Historical vendor corrections are logged. No silent removal of losers or substitution of tickers.','复用现有工作日收盘后任务更新。全部序列须覆盖相同 SPY 交易日；失败或部分缺失时保留并标记上次完整记录。供应商历史修订会留档，不静默移除亏损股或替换代码。')}</li></ol>
<p class="small">{t('Previous unstarted plan:','原未启动方案：')} <a href="/portfolio-assets/archive/social-basket-2026-10-03/manifest.json">{t('Archived rules','已归档规则')}</a> · <a href="/portfolio-assets/archive/social-basket-2026-10-03/snapshot.json">{t('Archived empty record','已归档空记录')}</a></p>
<p>{t('Selection source: a user-supplied social-post screenshot. Its original URL, timestamp, holdings and return claims have not been verified. The twelve-stock basket is our transparent test design; it is not an actual portfolio attributed to the author or a person in the image. No claim of guaranteed outperformance is adopted.','标的来自用户提供的社交帖子截图。原帖链接、发帖时间、实际持仓及收益承诺未核实。12 股组合是本站透明的实验设计，不代表发帖者或图中人物的真实组合，也不采纳保证跑赢的说法。')}</p><p>{t('SPCX security identity is checked against SpaceX’s issuer announcement and the price provider metadata. Missing or mismatched identity blocks the record.','SPCX 证券身份以 SpaceX 官方公告与行情元数据交叉核对；缺失或不匹配时不生成收益。')} <a href="{M['stocks'][6]['identity_source']}" target="_blank" rel="noopener">SpaceX IR</a> · <a href="https://www.ssga.com/us/en/institutional/etfs/state-street-spdr-sp-500-etf-trust-spy">SPY</a></p>
<p>{t('Educational research; not personalized investment advice. Prices and calculations can contain errors. A model’s past results do not establish future performance.','仅供研究，不构成个性化投资建议。行情与计算可能有误，模型历史表现不证明未来表现。')}</p><details><summary>{t('Embed this tracker','嵌入此追踪工具')}</summary><pre>{html.escape('<iframe src="'+url+'?embed=1" title="AGI portfolio tracker" width="100%" height="1100" loading="lazy"></iframe>')}</pre><a href="{url}" target="_blank" rel="noopener">AGI Scorecard</a></details></section><noscript>{t('The rules and holding list are available above. Enable JavaScript for current returns and calculations.','上述规则和标的列表可直接阅读。实时读取追踪记录和计算需要 JavaScript。')}</noscript></main><footer><a href="{prefix}/invest">{t('Investment hub','投资板块')}</a> · <a href="{prefix}/ai-infrastructure">{t('Company evidence','公司证据')}</a> · <a href="/privacy">{t('Privacy','隐私')}</a></footer></body></html>'''
 (ROOT/(prefix.strip('/')+'/' if prefix else '')/'portfolio-tracker.html').write_text(page)
print('Built portfolio tracker EN/ZH')
