import test from 'node:test';
import assert from 'node:assert/strict';
import {audit,inventory,inspectPage} from './workbench_growth.mjs';
import {sites} from '../revenue-studio/catalog.mjs';
import {languages,siteLanguages,route} from '../revenue-studio/i18n.mjs';
const rows=inventory();
function html(r){return `<html lang="${languages[r.lang].tag}"><link rel="canonical" href="${r.url}">${siteLanguages[r.site].map(l=>`<link rel="alternate" hreflang="${languages[l].tag}" href="${sites[r.site].origin+route(r.site,l,r.id==='hub'?'':r.id)}">`).join('')}<link rel="alternate" hreflang="x-default" href="${r.url}"><script type="application/ld+json">{"@type":"WebApplication"}</script><body data-product="${r.id==='hub'?'':r.id}"><section id="method"></section><section id="sharing"></section><button id="create-widget"></button></body></html>`;}
async function fixture(url){let text;const row=rows.find(r=>r.url===url);if(row)text=html(row);else if(url.endsWith('/manifest.json'))text=JSON.stringify({site:Object.keys(sites).find(s=>url.startsWith(sites[s].origin)),wired:[]});else if(url.endsWith('.mjs')||url.includes('/locales/'))text='x'.repeat(150);else if(url.endsWith('/sitemap.xml'))text=rows.map(r=>'<loc>'+r.url+'</loc>').join('');else if(url.includes('?doctor='))text=JSON.stringify({ok:true,selling:true,mode:'live',rails:{wallet:true},web3:{watch_healthy:true},private_field:'NEVER_STORE_THIS'});else if(url.endsWith('.md'))text='Canonical: '+rows.find(r=>r.url.replace(/\.html$/,'')+'.md'===url).url;else if(url.endsWith('.txt'))text='<!doctype html>'+url;else throw Error('unexpected fixture');return {status:200,url,text,headers:{}};}
test('all supported routes pass; no raw payment response or invented metrics',async()=>{const r=await audit({get:fixture});assert.equal(r.ok,true);assert.equal(r.counts.pages,rows.length);assert.equal(r.checkout.ready,true);assert.equal(r.outcomes.paid_buyers,null);assert.ok(!JSON.stringify(r).includes('NEVER_STORE_THIS'));assert.equal(r.marketing.draft_ready,null);});
test('canonical, header noindex, malformed schema and redirects turn report red',async()=>{const row=rows[0];assert.ok(inspectPage(row,html(row),{'x-robots-tag':'noindex'}).includes('indexable'));assert.ok(inspectPage(row,html(row).replace(row.url,'https://example.com')).includes('canonical'));assert.ok(inspectPage(row,html(row).replace('{"@type":"WebApplication"}','not json')).includes('structured_data'));const r=await audit({get:async url=>({...await fixture(url),url:url===row.url?url+'/':url})});assert.equal(r.ok,false);assert.ok(r.pages[0].errors.includes('redirected_canonical'));});
test('network failure is recorded and does not erase other domain results',async()=>{const r=await audit({get:async url=>{if(url.startsWith(sites.bpj.origin))throw Error('private diagnostic');return fixture(url);}});assert.equal(r.ok,false);assert.equal(r.counts.failed,rows.filter(r=>r.site==='bpj').length);assert.equal(r.checkout.ready,null);assert.ok(!JSON.stringify(r).includes('private diagnostic'));});
test('stale campaign readiness is not reused; current blockers preserved',async()=>{const queue={as_of:'2026-09-18',campaigns:[{id:'x',state:'blocked',blockers:['live_checkout_not_ready']}]};let r=await audit({get:fixture,now:'2026-09-19T12:00:00Z',queue});assert.equal(r.marketing.blocked,null);queue.as_of='2026-09-19';r=await audit({get:fixture,now:'2026-09-19T12:00:00Z',queue});assert.equal(r.marketing.blocked[0].reasons[0],'live_checkout_not_ready');assert.equal(r.marketing.sends,0);});
