const {chromium}=require(require.resolve('playwright',{paths:[process.cwd()+'/tools/revenue-studio/node_modules',process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES].filter(Boolean)}));
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');let p=path.join(root,decodeURIComponent(u.pathname));if(!path.extname(p))p+='.html';if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{const content=fs.readFileSync(p);res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.json':'application/json'})[path.extname(p)]||'text/plain');res.end(content);}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true});
try{for(const lang of ['en','zh']){const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());await page.goto(base+(lang==='zh'?'/zh/invest':'/invest')+'?__qa=1#research-workbench');await page.locator('#ir-calculate').click();assert.equal(await page.locator('#ir-return').textContent(),'+8.00%');assert.equal(await page.locator('#ir-stress').textContent(),'-18.00%');await page.locator('[data-example="nvda"]').click();await page.waitForFunction(()=>document.querySelector('#ir-company').value==='NVIDIA (NVDA)');
await page.locator('#research-workbench details').nth(2).locator('summary').click();assert.match(await page.locator('#ir-mode').textContent(),lang==='zh'?/示例/:/example/);
await page.locator('#ir-review').fill('2027-01-01');await page.locator('#ir-calculate').click();assert.match(await page.locator('#ir-completeness').textContent(),lang==='zh'?/齐全/:/supplied/);
await page.locator('#ir-save').click();assert.ok(await page.evaluate(()=>localStorage.getItem('agi-invest-research-v1')));
const downloadPromise=page.waitForEvent('download');await page.locator('#ir-export-json').click();const d=await downloadPromise;const f=await d.path();const record=JSON.parse(fs.readFileSync(f,'utf8'));assert.equal(record.mode,'sample');assert.equal(record.note.company,'NVIDIA (NVDA)');
const mdPromise=page.waitForEvent('download');await page.locator('#ir-export-md').click();const md=await mdPromise;assert.match(fs.readFileSync(await md.path(),'utf8'),lang==='zh'?/AI 复核任务/:/AI review task/);
await page.locator('#ir-own').click();assert.equal(await page.locator('#ir-company').inputValue(),'');await page.locator('#ir-import').setInputFiles({name:'research.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(record))});await page.waitForFunction(()=>document.querySelector('#ir-company').value==='NVIDIA (NVDA)');assert.equal(await page.locator('#ir-company').inputValue(),'NVIDIA (NVDA)');
await page.locator('#ir-delete').click();assert.equal(await page.evaluate(()=>localStorage.getItem('agi-invest-research-v1')),null);
await page.locator('#ir-entry').fill('0');await page.locator('#ir-calculate').click();assert.equal(await page.locator('#ir-result').isVisible(),false);assert.match(await page.locator('#ir-status').textContent(),lang==='zh'?/检查/:/Check/);await page.locator('#ir-entry').fill('40');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('#research-workbench details').nth(2).locator('summary').click();await page.locator('#research-workbench').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(process.env.INVEST_ARTIFACT_DIR||require('os').tmpdir(),'invest-'+lang+'-mobile.png')});
await page.setViewportSize({width:1365,height:1000});await page.screenshot({path:path.join(process.env.INVEST_ARTIFACT_DIR||require('os').tmpdir(),'invest-'+lang+'-desktop.png')});
await page.goto(base+(lang==='zh'?'/zh/invest':'/invest')+'?embed=research&__qa=1');await page.waitForFunction(()=>document.documentElement.classList.contains('research-embed'));assert.equal(await page.locator('body>header').isVisible(),false);assert.equal(await page.locator('#research-workbench').isVisible(),true);assert.deepEqual(errors,[]);await context.close();console.log(lang+': calculation, evidence, own/sample, export/import, storage, validation, mobile and embed passed');}
const context=await browser.newContext();const page=await context.newPage();await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await page.goto(base+'/invest');await page.evaluate(()=>{window.testEvents=[];window.gtag=(...args)=>window.testEvents.push(args);});await page.locator('#ir-calculate').click();assert.equal(await page.evaluate(()=>window.testEvents.length),0);await page.locator('#ir-measure').check();await page.locator('#ir-calculate').click();const events=await page.evaluate(()=>window.testEvents);assert.deepEqual(events,[['event','invest_tool_click',{location:'research_en_calculate',label:'sample'}]]);await context.close();console.log('Opt-in tool telemetry sends only action and sample/own category');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
