#!/usr/bin/env python3
"""Own only marked workbench fragments in the existing investment hub, EN + ZH."""
from pathlib import Path
import html,json,re
ROOT=Path(__file__).resolve().parents[1]
E=json.loads((ROOT/'invest-research/evidence.json').read_text())
def esc(s):return html.escape(str(s),quote=True)
def section(zh):
 def t(en,cn):return cn if zh else en
 lang='zh' if zh else 'en'
 def number(k,label,value,mn,mx,step='any'):
  return f'<label for="ir-{k}">{label}<input id="ir-{k}" type="number" min="{mn}" max="{mx}" step="{step}" value="{value}" required></label>'
 def field(k,label,kind='textarea'):
  control=f'<textarea id="ir-{k}" maxlength="3000" rows="2"></textarea>' if kind=='textarea' else f'<input id="ir-{k}" type="{kind}" maxlength="3000">'
  return f'<label for="ir-{k}">{label}{control}</label>'
 sources=''
 for s in E['sources']:
  copy=s[lang]
  sources+=f'''<div class="source"><h3>{esc(s['company'])}</h3><p>{esc(copy['observation'])}</p><p class="note">{esc(s['period'])}<br>{t('Published','披露')} {s['published']} · {t('Checked','核对')} {E['checked_at']}</p><p>{esc(copy['counter'])}</p><a href="{esc(s['source'])}" target="_blank" rel="noopener noreferrer">{t('Read company disclosure','打开公司披露')}</a><div class="actions"><button type="button" data-example="{s['id']}">{t('Use this example','载入该示例')}</button></div></div>'''
 rows=[
  ('Compute & networking','算力与网络','Revenue, gross margin, concentration','收入、毛利率、客户集中度','Capacity growth exceeds durable demand','产能增长快于持续需求'),
  ('Memory & manufacturing','存储与制造','Inventory, utilization, cash capex','库存、产能利用率、现金资本支出','A supply cycle erodes pricing','供给周期侵蚀价格'),
  ('Power & cooling','电力与散热','Order conversion, project returns, debt','订单兑现、项目回报、负债','Delays or financing absorb the benefit','延期或融资成本吞噬收益'),
  ('Cloud platforms','云平台','Cloud growth, cash flow, leases','云增长、现金流、租赁','Spending grows faster than monetization','支出增长快于变现'),
  ('Applications','应用软件','Paid retention, margins, cost to serve','付费留存、毛利、服务成本','Usage grows but unit economics worsen','使用量增长但单位经济恶化')]
 matrix=''.join('<tr>'+''.join('<td>'+esc(t(r[i],r[i+1]))+'</td>' for i in [0,2,4])+'</tr>' for r in rows)
 note_fields=''.join([field('company',t('Company / research subject','公司 / 研究对象'),'text'),field('published',t('Source publication date','来源披露日期'),'date'),field('period',t('Metric period and accounting basis','指标所属期间与会计口径'),'text'),field('source',t('Primary-source URL (https)','一手来源链接（https）'),'url'),field('thesis',t('What needs to be true?','什么条件必须成立？')),field('observation',t('Observed fact, units and currency','观察事实、单位、币种')),field('counter',t('Counterevidence / unknowns','反面证据 / 未知项')),field('flip',t('What would change your mind?','什么证据会改变你的判断？')),field('review',t('Your next review date (no automatic alert)','你的下次复查日期（不会自动提醒）'),'date')])
 numbers=''.join([number('growth',t('Annual EPS growth (%)','每股收益年增长率（%）'),20,-99,200),number('years',t('Years','年数'),3,1,20,'1'),number('entry',t('Starting P/E','起始市盈率'),40,.1,1000),number('exit',t('Ending P/E','期末市盈率'),25,.1,1000),number('weight',t('Selected sleeve weight (%)','所研究仓位占组合比例（%）'),20,0,100),number('shock',t('Sleeve price shock (%)','该仓位价格冲击（%）'),-50,-100,0),number('rest',t('Rest-of-portfolio shock (%)','其余资产价格冲击（%）'),-10,-100,0)])
 outputs=''.join(f'<dt>{t(en,cn)}</dt><dd id="ir-{k}">—</dd>' for k,en,cn in [('earnings','Cumulative EPS growth','累计每股收益增长'),('return','Cumulative price change','累计价格变化'),('annual','Annualized price change','年化价格变化'),('breakeven','Annual EPS growth needed to break even','价格持平所需 EPS 年增长率'),('stress','Portfolio stress return','组合压力损益'),('recovery','Gain needed to recover from that stress','该压力损失后的回本涨幅')])
 return f'''<section class="research" id="research-workbench" data-lang="{lang}" aria-labelledby="ir-title">
<h2 id="ir-title">{t('Turn an AI story into a research record','把 AI 故事变成可复查的投资研究')}</h2>
<p>{t('Trace the business benefit, inspect the evidence, then test how the price and your exposure could respond. Export a record you can revisit after the next filing.','先追踪业务如何受益，再核对证据，最后测算价格与仓位在不同假设下会怎样变化。导出研究记录，下次财报后重新检验。')}</p>
<p class="note">{t('Free research aid. US-listed company examples; not a stock ranking, live feed or buy/sell service. Framework reviewed September 28, 2026.','免费研究辅助。示例为美股公司，不是股票排名、实时行情或买卖服务。方法核对日期：2026-09-28。')}</p>
<details><summary>{t('1. Map where the AI benefit becomes cash','1. 看清 AI 利好在哪里变成现金')}</summary><p>{t('Editorial research questions, not an opportunity ranking. For each company compare the same period, unit and accounting basis. Separate realized revenue from orders, guidance and market narratives.','以下是编辑整理的研究问题，不是机会排名。公司之间应比较相同期间、单位和会计口径；已实现收入、订单、管理层指引与市场叙事要分开。')}</p><div class="scroll"><table><thead><tr><th>{t('Business layer','业务层')}</th><th>{t('Check','核对指标')}</th><th>{t('Counter-case','反面情景')}</th></tr></thead><tbody>{matrix}</tbody></table></div></details>
<details open><summary>{t('2. Start with a disclosed fact','2. 从一条已披露事实开始')}</summary><div class="evidence">{sources}</div><p class="note">{t('Dated snapshots, not automatically refreshed. A source supports its reported metric, not the example thesis. Sample review dates remain blank on purpose.','这是带日期的快照，不会自动刷新。来源支持披露指标，不代表它证明了示例假设；示例的复查日期特意留空。')}</p></details>
<details><summary>{t('3. Write your thesis and its failure condition','3. 写下假设，以及它何时不再成立')}</summary><div class="actions"><button type="button" id="ir-own">{t('Start my own research','开始自己的研究')}</button></div><p id="ir-mode" class="note">{t('Worked example','教学示例')}</p><div class="fields">{note_fields}</div><p class="note">{t('Entering a link does not verify it. AI can help extract and compare evidence; the source still needs checking.','填写链接不等于来源已核验。AI 可以辅助抽取和比较证据，原文仍需核对。')}</p></details>
<details open><summary>{t('4. Stress-test growth, valuation and exposure','4. 压力测试：增长、估值与仓位')}</summary><p>{t('Fictional example: EPS grows 20% a year for 3 years, but P/E falls from 40 to 25. Earnings rise 72.8%; the implied price change is only 8.0%, before dividends and costs. These inputs are not forecasts for either company above.','虚构示例：EPS 每年增长 20%，持续 3 年，但市盈率从 40 倍降到 25 倍。盈利累计增长 72.8%，对应价格却只变化 +8.0%，尚未计分红与成本。这些输入不是上面两家公司的预测。')}</p><div class="fields">{numbers}</div><p class="note">{t('Uses positive EPS and positive P/E only. Price factor = (1 + annual EPS growth)^years × ending P/E ÷ starting P/E. EPS growth must already reflect share dilution. Excludes dividends, fees, taxes and FX. Loss-making businesses need another method.','仅适用于正 EPS、正市盈率。价格倍数 =（1 + EPS 年增长率）^年数 × 期末市盈率 ÷ 起始市盈率；EPS 增长应已反映股本稀释。不含分红、费用、税与汇率。亏损公司需要其他方法。')}</p><p class="note">{t('Stress is a separate one-off scenario: weight × sleeve shock + (1 − weight) × other-assets shock. It is not a forecast, a target allocation, or a maximum-loss bound.','压力测试是独立的一次性冲击情景：仓位比例 × 该仓位冲击 +（1 − 仓位比例）× 其余资产冲击。不是预测、建议仓位或最大亏损上限。')}</p><div class="actions"><button class="primary" type="button" id="ir-calculate">{t('Calculate my assumptions','按假设计算')}</button></div><div class="result" id="ir-result" hidden><dl>{outputs}</dl></div><p id="ir-completeness" class="note"></p></details>
<h3>{t('Keep a record; ask AI to challenge it','留下记录，让 AI 找反证')}</h3><p>{t('Download a source-led brief with an AI review prompt, or a JSON file you can import next time. This tool does not call an AI model. Saving is optional and only uses this browser. Research text is never included in our tool events.','下载含来源与 AI 复核指令的研究文档，或下次可导入的 JSON。本工具不调用 AI 模型。保存是可选的，仅存于当前浏览器；工具事件不会包含研究正文。')}</p>
<div class="actions"><button type="button" id="ir-export-md">{t('Download AI review brief','下载 AI 复核文档')}</button><button type="button" id="ir-export-json">{t('Download JSON','下载 JSON')}</button><button type="button" id="ir-save">{t('Save in this browser','保存到当前浏览器')}</button><button type="button" id="ir-restore">{t('Restore saved record','恢复已存记录')}</button><button type="button" id="ir-delete">{t('Delete saved copy','删除已存副本')}</button></div><label for="ir-import">{t('Import a previous JSON record (50 KB max)','导入以前的 JSON 记录（最大 50 KB）')}<input type="file" id="ir-import" accept=".json,application/json"></label>
<label class="note"><input type="checkbox" id="ir-measure">{t('Share anonymous tool actions (sample / own), without inputs. Optional; regular site analytics are separate.','可选：分享匿名工具操作（示例 / 自填），不包含输入。站点常规访问统计另行运行。')}</label><p id="ir-status" class="status" role="status" aria-live="polite"></p>
<details><summary>{t('Research discipline and sources','研究纪律与方法来源')}</summary><p>{t('A 13F can arrive up to 45 days after quarter-end and does not show short stock positions. A filing-day closing price is not necessarily available to a follower: check the publication time, then use the next executable price. Historical model returns are not realized investor profits.','13F 最晚可在季末后 45 天披露，且不披露股票空头仓位。申报日收盘价不一定是跟随者可成交价：应核查披露时刻，再选择之后可执行的价格。历史模型回报不等于真实投资利润。')}</p><p><a href="https://www.sec.gov/divisions/investment/13ffaq">SEC 13F FAQ</a> · <a href="https://www.sec.gov/search-filings/edgar-application-programming-interfaces">SEC EDGAR API</a> · <a href="https://pages.stern.nyu.edu/~adamodar/New_Home_Page/valquestions/valquestions.htm">{t('Damodaran: cash flows and valuation assumptions','Damodaran：现金流与估值假设')}</a> · <a href="https://www.finra.org/investors/investing/investing-basics/asset-allocation-diversification">{t('FINRA: diversification','FINRA：分散投资')}</a></p><p class="note">{t('Next Q3 2026 13F deadline: November 16, 2026 (SEC calendar).','2026 Q3 的 13F 申报截止日为 2026-11-16（SEC 日历）。')}</p></details>
<div class="next"><p>{t('Need to check a number? Open FilingLens. Need to assess a paid alert service? Inspect SunWatch’s public record and current terms first. This research record is not automatically monitored by either service.','要核对财报数字，可打开 FilingLens。要评估付费提醒服务，先查看 SunWatch 的公开记录和当前条款。这份研究记录不会被任一服务自动监控。')}</p><div class="actions"><a class="action" data-research-action="filinglens" href="https://filinglens.agiscorecard.com/?src=invest-research">{t('Check a filing number (English)','核对财报数字（英文）')}</a><a class="action" data-research-action="record" href="https://invest.agiscorecard.com/{'' if zh else 'en/'}track-record">{t('Inspect SunWatch record','核查 SunWatch 记录')}</a></div></div>
<details><summary>{t('Embed this free workbench','嵌入免费研究工具')}</summary><pre>{esc('<iframe src="https://agiscorecard.com/'+('zh/' if zh else '')+'invest?embed=research&amp;utm_source=embed" title="'+t('AI investment research','AI 投资研究')+'" width="100%" height="1100" loading="lazy"></iframe>')}</pre><p><a href="{'/zh/invest' if zh else '/invest'}#research-workbench" target="_blank" rel="noopener">{t('Open full workbench on AGI Scorecard','在 AGI 记分牌打开完整工具')}</a> · <a href="/invest-research/evidence.json">{t('Dated source data (JSON)','带日期的来源数据（JSON）')}</a></p></details>
<noscript><p>{t('JavaScript is needed for calculations and exports. Sources, formulas and the research framework remain readable above.','计算和导出需要 JavaScript；上述来源、公式与研究框架仍可阅读。')}</p></noscript>
</section>'''

def replace_block(s,name,body,before):
 start=f'<!-- {name}:start -->';end=f'<!-- {name}:end -->';block=start+'\n'+body+'\n'+end
 if start in s:return re.sub(re.escape(start)+r'.*?'+re.escape(end),lambda m:block,s,flags=re.S)
 assert before in s,before
 return s.replace(before,block+'\n'+before,1)
for zh in [False,True]:
 p=ROOT/('zh/invest.html' if zh else 'invest.html');s=p.read_text()
 path='/zh/invest' if zh else '/invest'
 schema={'@context':'https://schema.org','@type':'WebApplication','name':'AI 投资研究工作台' if zh else 'AI investment research workbench','url':'https://agiscorecard.com'+path+'#research-workbench','applicationCategory':'FinanceApplication','operatingSystem':'Web','isAccessibleForFree':True,'offers':{'@type':'Offer','price':'0','priceCurrency':'USD'},'isPartOf':{'@type':'CollectionPage','url':'https://agiscorecard.com'+('/zh/ai-tools' if zh else '/ai-tools')},'featureList':['Source-led research records','Hypothetical EPS and P/E scenarios','Portfolio stress arithmetic','Local JSON and Markdown export']}
 head='<link rel="stylesheet" href="/invest-research/style.css">\n<script type="module" src="/invest-research/app.mjs"></script>\n<script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False)+'</script>'
 s=replace_block(s,'invest-research-head',head,'</head>')
 teaser='<div class="research-entry"><p>'+('用一条财报证据，写下你的 AI 投资假设；再看增长、估值和仓位如何影响结果。' if zh else 'Start with one disclosed fact. Test your AI thesis against growth, valuation and portfolio exposure.')+'</p><a href="#research-workbench">'+('开始研究' if zh else 'Open research workbench')+'</a></div>'
 # Keep historical headline and holdings dataset untouched; current feature has its own date.
 marker='<div class="capsule">' if zh else '<div style="margin:0 0 1.5rem;'
 teaser+='<div class="research-entry"><p>'+('新：20 家 AI 产业链公司的年度财务数据、带来源 AI 研究问题与云端笔记。' if zh else 'New: annual SEC facts for 20 AI infrastructure companies, source-linked AI research questions and cloud notes.')+'</p><a href="'+('/zh' if zh else '')+'/ai-infrastructure">'+('打开产业链工作台' if zh else 'Open infrastructure research')+'</a></div>'
 s=replace_block(s,'invest-research-entry',teaser,marker)
 s=replace_block(s,'invest-research-body',section(zh),'<h2>本板块的工具</h2>' if zh else '<h2>Tools in this section</h2>')
 p.write_text(s)
print('Updated existing EN and ZH investment workbenches')
