# -*- coding: utf-8 -*-
"""Generate /badge — docs page for the README-embeddable verdict badges
(SVGs generated by gen_badges.py). Badge embeds in third-party READMEs are
permanent branded backlinks — the flywheel mechanic behind /widget, extended
to GitHub."""
import gen_lib as g

DATE = "2026-07-11"

MD_1 = ("[![AGI by 2027](https://agiscorecard.com/badge/agi-2027.svg)]"
        "(https://agiscorecard.com/will-agi-arrive-2027?utm_source=badge)")
MD_2 = ("[![Situational Awareness scorecard](https://agiscorecard.com/badge/scorecard.svg)]"
        "(https://agiscorecard.com/?utm_source=badge)")
MD_3 = ("[![AGI-2027 Thesis Tracker](https://agiscorecard.com/badge/thesis-tracker.svg)]"
        "(https://agiscorecard.com/progress-index?utm_source=badge)")

capsule = ('<span class="verdict">Yes — drop a live AGI verdict into any README with one line of markdown.</span> '
           'These SVG badges show the current verdict on <strong>“AGI by 2027”</strong> and the full '
           '<em>Situational Awareness</em> scorecard tally. They are static files on a CDN, updated whenever a '
           'verdict changes — so your README always shows the live state of the AGI bet, never a stale copy.')

body = f"""<h2>The badges</h2>
<table><thead><tr><th>Badge</th><th>Preview</th><th>Shows</th></tr></thead><tbody>
<tr><td class="nowrap">AGI by 2027</td><td><img src="/badge/agi-2027.svg" alt="AGI by 2027 verdict badge" height="20"></td><td>The verdict on the headline prediction — resolves by Jan 1, 2028</td></tr>
<tr><td class="nowrap">Scorecard tally</td><td><img src="/badge/scorecard.svg" alt="Situational Awareness scorecard badge" height="20"></td><td>The live count across all graded predictions</td></tr>
<tr><td class="nowrap">Thesis Tracker</td><td><img src="/badge/thesis-tracker.svg" alt="AGI-2027 Thesis Tracker badge" height="20"></td><td>The single 0–100 score of how the whole 2027 bet is holding up</td></tr>
</tbody></table>
<h2>Embed (markdown)</h2>
<table><tbody>
<tr><td style="font-family:var(--mono);font-size:12px;line-height:1.6;word-break:break-all;" id="badge-md-1">{MD_1.replace('&', '&amp;').replace('<', '&lt;')}</td></tr>
<tr><td style="font-family:var(--mono);font-size:12px;line-height:1.6;word-break:break-all;" id="badge-md-2">{MD_2.replace('&', '&amp;').replace('<', '&lt;')}</td></tr>
<tr><td style="font-family:var(--mono);font-size:12px;line-height:1.6;word-break:break-all;" id="badge-md-3">{MD_3.replace('&', '&amp;').replace('<', '&lt;')}</td></tr>
</tbody></table>
<p><a href="#" onclick="navigator.clipboard.writeText(document.getElementById('badge-md-1').textContent+'\\n'+document.getElementById('badge-md-2').textContent+'\\n'+document.getElementById('badge-md-3').textContent);gtag('event','badge_copy',{{location:'badge_page'}});this.textContent='Copied ✓';return false;">Copy all snippets</a> — works in any GitHub/GitLab README, docs site, or blog that renders markdown. Plain HTML: use an <code>&lt;img&gt;</code> tag pointing at the same SVG URLs.</p>
<h2>Why embed one?</h2>
<p>If your project, paper, or reading list touches AGI timelines, the badge answers the first question every reader has — <em>where does the 2027 bet actually stand?</em> — without them leaving your page. When a verdict flips (the pre-registered conditions are public), the badge updates everywhere at once. No script, no iframe, no tracking beyond a standard image request.</p>
<h2>Rules</h2>
<ul>
<li><strong>Free</strong> for any use; the underlying data is CC BY 4.0.</li>
<li>Badges are updated when verdicts change — don't cache-bust or re-host them, or you'll freeze a live verdict.</li>
<li>Want more than a badge? The <a href="/widget.html">countdown widget</a> embeds the full live card, and <a href="/for-agents">/for-agents</a> documents the raw data endpoints.</li>
</ul>"""

faqs = [
    ("How do I add the AGI 2027 badge to my README?",
     "Paste one line of markdown: an image link to https://agiscorecard.com/badge/agi-2027.svg wrapped in a link to the verdict page. The /badge page has copy-paste snippets for both badges."),
    ("Do the badges update automatically?",
     "Yes. They are static SVGs regenerated whenever a scorecard verdict changes, so every README embedding them shows the current verdict with no action on your part."),
    ("Are the badges free to use?",
     "Yes — free for any use, commercial or not. The underlying dataset is CC BY 4.0; the badge itself just asks that you link it back to agiscorecard.com."),
]

related = [
    ("/for-agents", "All machine-readable endpoints, documented"),
    ("/skill", "Install the agent skill"),
    ("/will-agi-arrive-2027", "Will AGI arrive by 2027?"),
]

html = g.build(
    slug="badge",
    title="Live AGI Verdict Badges for Your README (Free SVG)",
    desc="Embed a live 'AGI by 2027' verdict badge in any README or blog with one line of markdown. Auto-updates when the scorecard verdict changes. Free, no script.",
    og_title="Live AGI verdict badges for your README",
    eyebrow="Badges",
    h1="Put a live AGI verdict badge in your README",
    capsule=capsule,
    body_html=body,
    faqs=faqs,
    related=related,
)

html = html.replace("Last updated: June 30, 2026", "Last updated: July 11, 2026")
html = html.replace('"datePublished": "2026-06-30", "dateModified": "2026-06-30"',
                    f'"datePublished": "{DATE}", "dateModified": "{DATE}"')
html = html.replace(
    '<div class="updated">Last updated: July 11, 2026 · Updated as verdicts change</div>',
    '<div class="updated">Last updated: July 11, 2026 · Updated as verdicts change</div>\n'
    '  <div class="byline" style="font-size:12px;color:var(--muted);margin:-0.9rem 0 1.5rem;">'
    'By the AGI Scorecard team · <a href="/about">methodology &amp; independence</a></div>')
crumb = ('<script type="application/ld+json">{"@context": "https://schema.org", "@type": "BreadcrumbList", '
         '"itemListElement": [{"@type": "ListItem", "position": 1, "name": "AGI Scorecard", "item": "https://agiscorecard.com/"}, '
         '{"@type": "ListItem", "position": 2, "name": "AGI questions, answered", "item": "https://agiscorecard.com/agi-questions"}, '
         '{"@type": "ListItem", "position": 3, "name": "Badges", "item": "https://agiscorecard.com/badge"}]}</script>\n')
i = html.index('<script type="application/ld+json">')
html = html[:i] + crumb + html[i:]
html = html.replace(
    'Not affiliated with any lab</footer>',
    'Not affiliated with any lab · <a href="/about" style="color:var(--muted);">About</a> · '
    '<a href="/privacy" style="color:var(--muted);">Privacy</a> · '
    '<a href="/advertise" style="color:var(--muted);">Advertise</a></footer>')

open(f"{g.OUT}/badge.html", "w").write(html)
print("badge.html written")
