import {messages} from './messages.mjs?v=independent1';
const lang=document.body.dataset.language||'en',t=messages[lang],$=id=>document.getElementById(id),products=await fetch('/member-assets/products.json?v=independent1').then(r=>r.json());
const site=document.body.dataset.memberSite||'bpj',keySlot='workbench-member-key:'+site,service=site==='bpj'?'baipiaoji-workbench':site+'-workbench';
const random=n=>[...crypto.getRandomValues(new Uint8Array(n))].map(x=>x.toString(16).padStart(2,'0')).join('');
let key='',member=null,selected=null,version=null,orders=[],ready=false,busy=false,handoff=null,spaces=null;
let authMode='key',accountUser=null,accountBackupKey='',authEpoch=0;
const accountText={zh:{backed:'当前密钥备份已确认；无需创建订单。',key:'当前方式：访问密钥',account:'当前免费账户：',choose:'请先登录免费账户，再点击“使用免费账户”。',changed:'账户已变化，请重新点击“使用免费账户”；待保存的工具草稿仍保留。',backup:'当前密钥未保存在本页。请填入已备份密钥后关联，或用账户密码更换密钥并重新备份。',linked:'已关联；原会员有效期和云项目保持不变。'},en:{backed:'Current key backup confirmed. No order is needed.',key:'Current access: key',account:'Free account: ',choose:'Sign in to a free account, then choose “Use free account”.',changed:'The account changed. Choose “Use free account” again; the tool draft is retained.',backup:'This page does not hold the key. Link your backed-up key, or replace it using your account password and back up the new key.',linked:'Linked. Membership dates and cloud projects are unchanged.'},de:{backed:'Sicherung des aktuellen Schlüssels bestätigt. Keine Bestellung erforderlich.',key:'Aktueller Zugang: Schlüssel',account:'Kostenloses Konto: ',choose:'Erst kostenlos anmelden, dann „Kostenloses Konto verwenden“ wählen.',changed:'Das Konto hat sich geändert. Konto erneut auswählen; der Werkzeugentwurf bleibt erhalten.',backup:'Der Schlüssel liegt hier nicht vor. Gesicherten Schlüssel verknüpfen oder mit dem Kontopasswort ersetzen und erneut sichern.',linked:'Verknüpft. Laufzeit und Cloud-Projekte bleiben unverändert.'},it:{backed:'Backup della chiave attuale confermato. Non serve alcun ordine.',key:'Accesso attuale: chiave',account:'Account gratuito: ',choose:'Accedi a un account gratuito, poi scegli “Usa account gratuito”.',changed:'L’account è cambiato. Selezionalo nuovamente; la bozza dello strumento è conservata.',backup:'La chiave non è presente qui. Collega quella salvata, oppure sostituiscila con la password dell’account e salva la nuova chiave.',linked:'Collegato. Scadenza e progetti cloud restano invariati.'}}[lang]||null;
// handoff = {nonce, json, id} for a project a tool tab handed over: its nonce, the exact JSON it sent, and the project the save belongs to
// (id null = the next new project). Only a save into that project is acknowledged, and the acknowledgement says whether the saved content
// is still exactly the handed-over draft, so the tool follows the revision without claiming its edits are saved (2026-09-25 audit V2, MV-2).
try{key=sessionStorage.getItem(keySlot)||'';}catch{}
$('key').value=key;
const notice=(text,error=false)=>{$('notice').textContent=text;$('notice').className=error?'error':'';};
const date=n=>new Date(n*1000).toLocaleString(lang==='zh'?'zh-CN':lang);
function el(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
function download(name,data){const a=el('a');a.href=URL.createObjectURL(new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
const defaultName=product=>(products.find(p=>p.id===product)?.name||product)+' '+new Date().toISOString().slice(0,10);
function storeKey(value){if(value!==key){if(site==='bpj')authEpoch++;selected=null;version=null;handoff=null;spaces=null;member=null;orders=[];$('payload').value='';$('name').value='';$('history').replaceChildren();$('space-list').replaceChildren(el('p',t.empty));$('member-status').textContent=t.inactive;renderOrders();}key=value;$('key').value=key;try{sessionStorage.setItem(keySlot,key);}catch{}}
// Only a draft handed over by the verified tool window survives an identity change.
function clearIdentityView(){
 const carry=!!handoff&&(!selected||selected.id===handoff.id),draft=carry?$('payload').value:'',name=carry?$('name').value:'',h=carry?handoff:null,target=carry?selected:null,rev=carry?version:null;
 selected=target;version=rev;spaces=null;member=null;orders=[];handoff=h;
 $('payload').value=draft;$('name').value=name;$('history').replaceChildren();$('space-list').replaceChildren(el('p',t.empty));$('member-status').textContent=t.inactive;$('usage').textContent='';$('key-saved').checked=false;$('consent').checked=false;renderOrders();
}
function clearAccountSecrets(){accountBackupKey='';key='';$('key').value='';try{sessionStorage.removeItem(keySlot);}catch{}if($('account-key'))$('account-key').value='';if($('account-password'))$('account-password').value='';}
function setAuthMode(mode,user=null){
 if(mode!==authMode||mode==='account'&&accountUser?.id!==user?.id){authEpoch++;clearIdentityView();clearAccountSecrets();}
 authMode=mode;accountUser=user;
 if(site==='bpj'){$('new-key').disabled=mode==='account';if($('account-confirm'))$('account-confirm').hidden=mode!=='account';}
 if($('account-mode'))$('account-mode').textContent=mode==='account'&&user?accountText.account+user.username:accountText.key;
}
async function accountApi(action,extra={},initial=false){
 if(site!=='bpj'||!initial&&!accountUser)throw Error(accountText.choose);
 const epoch=authEpoch,account=accountUser?.id;
 const r=await fetch('/api/account-member',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...(!initial?{account_id:account}:{}),...extra}),signal:AbortSignal.timeout(90000)}),j=await r.json();
 if(epoch!==authEpoch)throw Error(accountText.changed);
 if(!r.ok||!j.ok){if(['account_changed','authentication_required'].includes(j.code)&&!initial){authEpoch++;clearIdentityView();accountUser=null;clearAccountSecrets();$('account-mode').textContent=accountText.changed;}throw Error((['account_changed','authentication_required'].includes(j.code)?accountText.choose:t[errors[j.code]||'error'])+' ['+(j.code||r.status)+']');}
 return j;
}
const errors={wrong_site:'wrongSite',revision_conflict:'conflict',storage_quota:'quota',workspace_quota:'quota',membership_required:'required',rate_limited:'rate',consent_required:'consentRequired',not_ready:'unavailable',bad_backup:'badBackup',suspended:'suspended'};
async function api(action,extra={}){
 if(authMode==='account')return accountApi(action,extra);
 if(!/^[a-f0-9]{64}$/.test(key))throw Error(t.noKey);
 const epoch=authEpoch;const r=await fetch('/api/member',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},body:JSON.stringify({action,...extra}),signal:AbortSignal.timeout(90000)});const j=await r.json();if(epoch!==authEpoch)throw Error(accountText?.changed||t.error);if(!r.ok||!j.ok)throw Error(t[errors[j.code]||'error']+' ['+(j.code||r.status)+']');return j;
}
function on(id,fn){$(id).onclick=async()=>{if(busy)return;busy=true;$(id).disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{$(id).disabled=false;busy=false;}};}
function button(label,fn){const b=el('button',label);b.type='button';b.onclick=async()=>{if(busy)return;busy=true;b.disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{busy=false;b.disabled=false;}};return b;}
function parseBackup(value){const data=typeof value==='string'?JSON.parse(value):value;if(data?.version!==1||!products.some(p=>p.id===data.product)||!data.values||typeof data.values!=='object'||Array.isArray(data.values))throw Error(t.badBackup);if(new TextEncoder().encode(JSON.stringify(data)).length>65536)throw Error(t.quota);return data;}
function backupKey(){const value=authMode==='account'?accountBackupKey:key;if(!value)throw Error(authMode==='account'?accountText.backup:t.noKey);download(site+'-access-key.json',{service,version:1,key:value});}
async function refresh(){
 if(authMode==='account'?!accountUser:!key)return;spaces=null;member=await api('status');if(authMode==='account')$('key-saved').checked=member.key_backed_up;$('member-status').textContent=member.suspended?t.suspended:member.active?t.active+' '+date(member.ends_at):member.read_until&&member.read_until>Date.now()/1000?t.expired+' '+date(member.read_until):t.inactive;
 if(member.exists){orders=(await api('orders')).orders;renderOrders();}
 if(member.read_until>Date.now()/1000){const j=await api('list');spaces=j.spaces;$('usage').textContent=t.usage+': '+j.usage.bytes+' / '+member.plan.total_bytes;renderSpaces(j.spaces);}else{if(authMode==='account')spaces=[];$('space-list').replaceChildren(el('p',t.empty));$('usage').textContent='';}
 retarget();
}
// A save target this account does not own (another account's project, or one deleted since the tool saved) becomes a new project.
// The draft and the handoff stay, so the acknowledgement points the tool at the project that now exists (audit MV-4).
function retarget(){if(!selected||!spaces||spaces.some(x=>x.id===selected.id))return;if(handoff?.id===selected.id)handoff.id=null;$('name').value=defaultName(selected.product);selected=null;version=null;$('history').replaceChildren();}
function renderOrders(){
 $('payment').hidden=!orders.length;const target=$('orders');target.replaceChildren();
 for(const o of orders){const box=el('article');box.className='order';box.append(el('strong',o.state==='paid'?t.paid:o.state==='expired'?t.expiredOrder:t.pending),el('p','ID: '+o.id));if(['pending','expired'].includes(o.state)){
  if(o.state==='pending')box.append(el('p',t.quote));box.append(el('p',t.network));const dl=el('dl');for(const[label,value]of [[t.amount,o.payment.amount],[t.address,o.payment.address],[t.deadline,date(o.payment.expires)]]){dl.append(el('dt',label),el('dd',value));}box.append(dl);
  const actions=el('div');actions.className='actions';for(const[label,value]of [[t.copyAddress,o.payment.address],[t.copyAmount,o.payment.amount]])actions.append(button(label,async()=>{await navigator.clipboard.writeText(value);notice(t.copied);}));box.append(actions);
  const tx=el('input');tx.placeholder=t.tx;tx.setAttribute('aria-label',t.tx);box.append(tx,button(t.check,async()=>{notice(t.checking);const j=await api('check',{id:o.id,tx:tx.value.trim()});notice(j.order.state==='paid'?t.paid:t.pending+(j.order.check?' ('+j.order.check+')':''));await refresh();}),el('p',t.paymentNote));
 }if(o.payment.tx)box.append(el('p','Tx: '+o.payment.tx));target.append(box);}
}
function renderSpaces(spaces){const box=$('space-list');box.replaceChildren();if(!spaces.length)box.append(el('p',t.empty));for(const s of spaces){const b=button(s.name,()=>loadSpace(s,s.revision));b.className='workspace-item';b.append(el('small',(products.find(p=>p.id===s.product)?.name||s.product)+' · '+date(s.updated)));box.append(b);}}
async function loadSpace(space,revision){const j=await api('read',{id:space.id,revision});selected=space;version=revision;$('name').value=space.name;$('payload').value=JSON.stringify(j.data,null,2);const history=(await api('history',{id:space.id})).versions;$('history').replaceChildren(...history.map(v=>button(t.version+' '+v.revision+' · '+date(v.created),()=>loadSpace(space,v.revision))));notice(t.loaded);}
// A new account owns no project yet: keep the tool's handoff, pointed at the next new project (audit MV-1).
on('new-key',()=>{if(authMode==='account')throw Error(accountText.choose+' '+t.newKey);if(key&&member?.exists)throw Error(t.rotate);const draft=$('payload').value,name=$('name').value,h=handoff;storeKey(random(32));$('payload').value=draft;$('name').value=name;if(h){h.id=null;handoff=h;}member=null;orders=[];renderOrders();$('key-saved').checked=false;notice(t.keyReady);});
on('backup-key',backupKey);
// Logging in keeps a tool's handed-over draft, its save target and the handoff: on the first key in this tab, after a wrong key, and on a
// second click (the same key changes nothing). Before this, logging in wiped a revised project that came with a cloud context, so a paying
// member could not save revision 2 (audit V1, MV-3). A space opened from the list (not the handed-over one) is still cleared on a key change.
function adoptKey(v){if(v===key)return;const carry=!key||!!handoff&&(!selected||selected.id===handoff.id),keep=carry||!selected,draft=keep?$('payload').value:'',name=keep?$('name').value:'',s=selected,ver=version,h=handoff;storeKey(v);$('payload').value=draft;$('name').value=name;if(carry){selected=s;version=ver;handoff=h;}}
on('login',async()=>{const v=$('key').value.trim();if(!/^[a-f0-9]{64}$/.test(v))throw Error(t.badKey);setAuthMode('key');adoptKey(v);await refresh();});
$('key-file').onchange=async()=>{try{const f=$('key-file').files[0];if(!f||f.size>2048)throw Error(t.badKey);const j=JSON.parse(await f.text());if(j.service!==service||!/^([a-f0-9]{64})$/.test(j.key||''))throw Error(t.badKey);setAuthMode('key');adoptKey(j.key);$('key-saved').checked=true;await refresh();}catch(e){notice(e.message,true);}};
on('logout',async()=>{if(authMode==='account'){if(!accountUser)throw Error(accountText.choose);const response=await fetch('/api/account',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout',account_id:accountUser.id})});if(!response.ok)throw Error(t.error);setAuthMode('key');const draft=$('payload').value,name=$('name').value,h=handoff;storeKey('');$('payload').value=draft;$('name').value=name;handoff=h;notice(t.logout);return;}key='';try{sessionStorage.removeItem(keySlot);}catch{}location.reload();});
on('rotate',async()=>{if(!confirm(t.rotateConfirm))return;if(authMode==='account'){const j=await accountApi('replace_key',{password:$('account-password').value});$('account-password').value='';accountBackupKey=j.key;$('account-key').value=j.key;backupKey();await refresh();$('key-saved').checked=false;notice(t.keyReady);return;}const next=random(32),draft=$('payload').value,name=$('name').value,previous=selected,previousVersion=version,h=handoff;await api('rotate',{new_key:next});storeKey(next);selected=previous;version=previousVersion;handoff=h;$('payload').value=draft;$('name').value=name;backupKey();$('key-saved').checked=false;await refresh();notice(t.keyReady);});
on('checkout',async()=>{if(!$('key-saved').checked||!$('consent').checked)throw Error(t.consentRequired);if(!ready)throw Error(t.unavailable);if(authMode==='account'&&!member?.key_backed_up){if(!accountBackupKey)throw Error(accountText.backup);await accountApi('confirm_backup',{key:accountBackupKey,confirmed:true});}const j=await api('checkout',{nonce:random(16),accept_terms:true,key_saved:true,source:products.some(p=>p.id===new URLSearchParams(location.search).get('tool'))?new URLSearchParams(location.search).get('tool'):''});orders=[j.order];renderOrders();notice(t.pending);await refresh();$('payment').scrollIntoView({behavior:'smooth',block:'start'});});
on('refresh',refresh);
on('new-space',()=>{selected=null;version=null;handoff=null;$('name').value='';$('payload').value='';$('history').replaceChildren();notice(t.choose);});
$('backup-file').onchange=async()=>{try{const f=$('backup-file').files[0];if(!f||f.size>65536)throw Error(t.quota);const data=parseBackup(await f.text());selected=null;version=null;handoff=null;$('payload').value=JSON.stringify(data,null,2);$('name').value=f.name.replace(/\.json$/,'').slice(0,80);$('history').replaceChildren();notice(t.received);}catch(e){notice(e.message,true);}};
on('save',async()=>{const data=parseBackup($('payload').value),name=$('name').value.trim();if(!name||name.length>80)throw Error(t.name);const id=selected?.id||random(16),ours=!!handoff&&(handoff.id?handoff.id===id:!selected),same=ours&&JSON.stringify(data)===handoff.json;const j=await api('save',{id,revision:selected?.revision||0,name,data});selected={id,revision:j.revision,name,product:data.product};version=j.revision;if(ours){handoff.id=id;if(window.opener&&from===location.origin)window.opener.postMessage({kind:'workbench-saved',handoff:handoff.nonce,same,product:data.product,context:{id,revision:j.revision,name}},location.origin);}await refresh();await loadSpace(selected,j.revision);notice(t.saved);});
on('export',()=>{const data=parseBackup($('payload').value);download(data.product+'-inputs.json',data);});
on('delete',async()=>{if(!selected)throw Error(t.choose);if(!confirm(t.deleteConfirm))return;await api('delete',{id:selected.id});if(handoff&&(!handoff.id||handoff.id===selected.id))handoff=null;selected=null;version=null;$('payload').value='';$('name').value='';$('history').replaceChildren();await refresh();});
on('restore',()=>{const data=parseBackup($('payload').value),url=new URL(products.find(p=>p.id===data.product).urls[lang]);url.searchParams.set('restore','1');if(new URLSearchParams(location.search).has('__ci'))url.searchParams.set('__ci','1');const win=window.open(url.href,'_blank');if(!win)throw Error(t.noPopup);const handler=e=>{if(e.source!==win||e.origin!==url.origin||e.data?.kind!=='workbench-ready')return;win.postMessage({kind:'workbench-restore',data,context:selected?{id:selected.id,revision:selected.revision,name:selected.name}:null},url.origin);window.removeEventListener('message',handler);};window.addEventListener('message',handler);setTimeout(()=>window.removeEventListener('message',handler),120000);});
on('support',async()=>{const message=$('support-message').value.trim();if(!message||message.length>1000||/[a-f0-9]{64}/i.test(message))throw Error(t.supportHelp);await api('support',{message});$('support-message').value='';notice(t.supportSaved);});
if(site==='bpj'&&$('account-use')){
 on('account-use',async()=>{const j=await accountApi('status',{},true);setAuthMode('account',j.user);await refresh();});
 on('account-confirm',async()=>{if(authMode!=='account')throw Error(accountText.choose);if(!$('key-saved').checked)throw Error(t.consentRequired);const value=accountBackupKey||$('key').value.trim();if(!/^[a-f0-9]{64}$/.test(value))throw Error(accountText.backup);await accountApi('confirm_backup',{key:value,confirmed:true});await refresh();notice(accountText.backed);});
 on('account-create',async()=>{if(authMode!=='account')throw Error(accountText.choose);const j=await accountApi('create_key',{password:$('account-password').value});$('account-password').value='';accountBackupKey=j.key;$('account-key').value=j.key;await refresh();notice(t.keyReady);});
 on('account-link',async()=>{if(authMode!=='account')throw Error(accountText.choose);const value=$('key').value.trim();if(!/^[a-f0-9]{64}$/.test(value))throw Error(t.badKey);if(!$('key-saved').checked)throw Error(t.consentRequired);await accountApi('link_key',{key:value,key_saved:true,password:$('account-password').value});$('account-password').value='';accountBackupKey=value;$('account-key').value=value;await refresh();notice(accountText.linked);});
}
const origins=new Set([location.origin]);const from=new URLSearchParams(location.search).get('from');
if(window.opener&&origins.has(from)){
 const handler=e=>{if(e.source!==window.opener||e.origin!==from||e.data?.kind!=='workbench-save')return;try{const data=parseBackup(e.data.data);handoff=/^[a-f0-9]{32}$/.test(e.data.handoff||'')?{nonce:e.data.handoff,json:JSON.stringify(data),id:null}:null;const c=e.data.context;selected=c&&/^[a-f0-9]{32}$/.test(c.id||'')&&Number.isSafeInteger(c.revision)&&c.revision>0?{id:c.id,revision:c.revision,product:data.product,name:String(c.name||'').slice(0,80)}:null;version=selected?.revision||null;if(handoff)handoff.id=selected?.id||null;$('history').replaceChildren();$('payload').value=JSON.stringify(data,null,2);$('name').value=selected?.name||defaultName(data.product);retarget();notice(t.received);}catch(e){notice(e.message,true);}window.removeEventListener('message',handler);};window.addEventListener('message',handler);window.opener.postMessage({kind:'workbench-member-ready'},from);
}
try{const r=await fetch('/api/member',{cache:'no-store'}),j=await r.json();ready=r.ok&&j.ready===true;$('availability').textContent=ready?t.ready:t.notReady;if(key)await refresh();}catch{notice(t.error,true);$('availability').textContent=t.notReady;}
setInterval(async()=>{const o=orders.find(o=>o.state==='pending'&&o.payment.expires>Date.now()/1000);if(!o||(authMode==='account'?!accountUser:!key)||document.hidden||busy)return;busy=true;try{await api('check',{id:o.id});await refresh();}catch(e){notice(e.message,true);}finally{busy=false;}},60000);
