import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import assert from 'node:assert/strict';
import {memberRoute} from './server.mjs';import {mockChain,setupSites,KEY} from './test-fixtures.mjs';import {digest,seconds} from '../../sites/baipiaoji/lib/ad-commerce.js';import {messages} from './messages.mjs';import {memberCopy,memberURL} from '../revenue-studio/member-copy.mjs';import {siteLanguages,pageURL} from '../revenue-studio/i18n.mjs';import {sites,products} from '../revenue-studio/catalog.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'independent-member-browser-'));const {chromium}=createRequire(new URL('../revenue-studio/package.json',import.meta.url))('playwright');
for(const site of Object.keys(sites))execFileSync(process.execPath,[path.join(repo,'tools/revenue-studio/build.mjs'),'--site',site,'--out',path.join(tmp,site)]);execFileSync(process.execPath,[path.join(here,'build.mjs'),'--out',path.join(tmp,'bpj')]);
const reset=mockChain(),all=await setupSites();for(const site of Object.keys(sites))all[site].db.sql.prepare('INSERT INTO wb_members(id,token_hash,created,ends_at) VALUES(?,?,?,?)').run('browser-fixture',await digest(KEY),seconds(),seconds()+86400);
const browser=await chromium.launch({headless:true,...(process.env.WORKBENCH_CHROMIUM?{executablePath:process.env.WORKBENCH_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage','--single-process']}:{})});
const service=site=>site==='bpj'?'baipiaoji-workbench':site+'-workbench';
try{const context=await browser.newContext();const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 await context.route('**/*',async route=>{const req=route.request(),url=new URL(req.url()),site=Object.keys(sites).find(k=>sites[k].origin===url.origin);if(!site)return route.abort();
  if(url.pathname.startsWith('/api/member')){const response=await memberRoute(new Request(req.url(),{method:req.method(),headers:req.headers(),...(req.method()==='POST'?{body:req.postData()}: {})}),all[site].raw,site);return route.fulfill({status:response.status,headers:Object.fromEntries(response.headers),body:await response.text()});}
  let relative=url.pathname;if(!path.extname(relative))relative+='.html';const file=path.join(tmp,site,relative);if(!fs.existsSync(file))return route.fulfill({status:404,body:'fixture not found'});const ext=path.extname(file);return route.fulfill({body:fs.readFileSync(file),contentType:{'.html':'text/html','.mjs':'application/javascript','.js':'application/javascript','.json':'application/json','.css':'text/css','.wasm':'application/wasm'}[ext]||'text/plain'});
 });
 for(const site of Object.keys(sites))for(const lang of site==='bpj'?Object.keys(messages):siteLanguages[site]){
  const t=messages[lang],page=await context.newPage();await page.goto(memberURL(lang,site));await page.waitForFunction(()=>document.querySelector('#availability').textContent.includes('Web3'));
  assert.equal(await page.locator('.brand').textContent(),sites[site].name);for(const a of await page.locator('header nav a').all())assert.equal(new URL(await a.getAttribute('href'),page.url()).origin,sites[site].origin);
  const keyFile=(s)=>({name:'key.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({service:service(s),key:KEY}))});
  await page.locator('#key-file').setInputFiles(keyFile(site==='eco'?'bpj':'eco'));await page.waitForFunction(expected=>document.querySelector('#notice').textContent===expected,t.badKey);
  await page.locator('#key-file').setInputFiles(keyFile(site));await page.waitForFunction(()=>document.querySelector('#member-status').textContent.includes(new Date().getFullYear()));
  const product=products.find(p=>p.site===site&&!p.kind),values=Object.fromEntries(product.fields.map(f=>[f.key,f.value])),data={version:1,product:product.id,values};
  await page.locator('#backup-file').setInputFiles({name:product.id+'.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await page.locator('#name').fill(site+' '+lang);await page.locator('#save').click();await page.waitForFunction(expected=>document.querySelector('#notice').textContent===expected,t.saved);
  const download=page.waitForEvent('download');await page.locator('#export').click();assert.equal((await download).suggestedFilename(),product.id+'-inputs.json');
  const pp=page.waitForEvent('popup');await page.locator('#restore').click();const tool=await pp;await tool.waitForFunction(id=>document.querySelector('#field-'+id)!==null,product.fields[0].key);assert.equal(new URL(tool.url()).origin,sites[site].origin);
  const tl=await tool.locator('body').getAttribute('data-locale'),save=tool.waitForEvent('popup');await tool.getByRole('button',{name:memberCopy[tl].save,exact:true}).click();const portal=await save;await portal.waitForFunction(id=>document.querySelector('#payload')?.value.includes(id),product.id);assert.equal(new URL(portal.url()).origin,sites[site].origin);assert.ok(!portal.url().includes('baipiaoji.com')||site==='bpj');await portal.close();await tool.close();
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(site==='eco'&&lang==='en')await page.screenshot({path:path.join(tmp,'eco-independent-membership.png'),fullPage:true});
  await page.close();console.log('INDEPENDENT MEMBER UI OK '+site+'/'+lang);
 }
 // Same-site checkout with a new key creates unpaid orders only, never paid grants.
 for(const site of Object.keys(sites)){const page=await context.newPage();await page.goto(memberURL('en',site));await page.waitForFunction(()=>document.querySelector('#availability').textContent.includes('Web3'));await page.locator('#new-key').click();const dl=page.waitForEvent('download');await page.locator('#backup-key').click();assert.equal((await dl).suggestedFilename(),site+'-access-key.json');await page.locator('#key-saved').check();await page.locator('#consent').check();await page.locator('#checkout').click();await page.waitForFunction(()=>document.querySelector('#orders')?.textContent.includes('9.'));assert.equal(all[site].db.sql.prepare("SELECT COUNT(*) n FROM wb_orders WHERE state='paid'").get().n,0);await page.close();console.log('INDEPENDENT QUOTE UI OK '+site);}
 for(const [id,selector,value]of [['querysprint-projects','#query','SELECT 9 AS saved_query;'],['puzzleclub','#seed','saved-puzzle'],['classroompuzzles','#seed','saved-class'],['embedpuzzles','#embed-title','Saved puzzle embed']]){
  const tool=await context.newPage();await tool.goto(pageURL(products.find(p=>p.id===id),'en'));await tool.locator(selector).fill(value);const pp=tool.waitForEvent('popup');await tool.getByRole('button',{name:memberCopy.en.save,exact:true}).click();const portal=await pp;await portal.waitForFunction(v=>document.querySelector('#payload')?.value.includes(v),value);const rp=portal.waitForEvent('popup');await portal.locator('#restore').click();const restored=await rp;await restored.waitForFunction(({selector,value})=>document.querySelector(selector)?.value===value,{selector,value});await restored.close();await portal.close();await tool.close();console.log('SAME-SITE SPECIAL RESTORE OK '+id);
 }
 assert.deepEqual(errors,[]);console.log('Independent membership UI passed. Screenshot: '+path.join(tmp,'eco-independent-membership.png'));
}finally{reset();await browser.close();for(const v of Object.values(all))v.db.sql.close();}
